<?php 
switch($verse){
case 1:{?>Alif. Lam. Mim.<?php break;}
case 2:{?>This is the Scripture whereof there is no doubt, a guidance unto those who ward off ( evil ).<?php break;}
case 3:{?>Who believe in the unseen, and establish worship, and spend of that We have bestowed upon them;<?php break;}
case 4:{?>And who believe in that which is revealed unto thee ( Muhammad ) and that which was revealed before thee, and are certain of the Hereafter.<?php break;}
case 5:{?>These depend on guidance from their Lord. These are the successful.<?php break;}
case 6:{?>As for the disbelievers, whether thou warn them or thou warn them not it is all one for them; they believe not.<?php break;}
case 7:{?>Allah hath sealed their hearing and their hearts, and on their eyes there is a covering. Theirs will be an awful doom.<?php break;}
case 8:{?>And of mankind are some who say : We believe in Allah and the Last Day, when they believe not.<?php break;}
case 9:{?>They think to beguile Allah and those who believe, and they beguile nonesave themselves; but they perceive not.<?php break;}
case 10:{?>In their hearts is a disease, and Allah increaseth their disease. A painful doom theirs because they lie.<?php break;}
case 11:{?>And when it is said unto them : Make not mischief in the earth, they say : We are peacemakers only.<?php break;}
case 12:{?>Are not they indeed the mischief makers? But they perceive not.<?php break;}
case 13:{?>And when it is said unto them : Believe as the people believe, they say : Shall we believe as the foolish believe? Are not they indeed the foolish? But they know not.<?php break;}
case 14:{?>And when they fall in with those who believe, they say : We believe; but when they go apart to their devils they declare : Lo! we are with you; verily we did but mock.<?php break;}
case 15:{?>Allah ( Himself ) doth mock them, leaving them to wander blindly on in their contumacy.<?php break;}
case 16:{?>These are they who purchase error at the price of guidance, so their commerce doth not prosper, neither are they guided.<?php break;}
case 17:{?>Their likeness is as the likeness of one who kindleth fire, and when it sheddeth its light around him Allah taketh away their light and leaveth them in darkness, where they cannot see,<?php break;}
case 18:{?>Deaf, dumb and blind; and they return not<?php break;}
case 19:{?>Or like a rainstorm from the sky, wherein is darkness, thunder and the flash of lightning. They thrust their fingers in their ears by reason of the thunder-claps, for fear of dead Allah encompasseth the disbelievers ( in His guidance ).<?php break;}
case 20:{?>The lightning almost snatcheth away their sight from them. As often as it flasheth forth for them they walk therein, and when it darkeneth against them they stand still. If Allah willed, He could destroy their hearing and their sight Lo! Allah is Able to do all things.<?php break;}
case 21:{?>O mankind! Worship your Lord, Who hath created you and those before you, so that ye may ward off ( evil ).<?php break;}
case 22:{?>Who hath appointed the earth a resting-place for you, and the sky a canopy; and causeth water to pour down from the sky, thereby producing fruits as food for you. And do not set up rivals to Allah when ye know ( better ).<?php break;}
case 23:{?>And if ye are in doubt concerning that which We reveal unto Our slave ( Muhammad ), then produce a sura or the like thereof, and call your witnesses beside Allah if ye are truthful.<?php break;}
case 24:{?>And if ye do it not and ye can never do it - enguard yourselves against the fire prepared for disbelievers, whose fuel is of men and stones.<?php break;}
case 25:{?>And give glad tidings ( O Muhammad ) unto those who believe and do good works; that theirs are Gardens underneath which rivers flow; as often as they are regaled with food of the fruit thereof, they say : This is what was given us aforetime; and it is given to them in resemblance. There for them are pure companions; there for ever they abide.<?php break;}
case 26:{?>Lo! Allah disdaineth not to coin the similitude even of a gnat. Those who believe know that it is the truth from their Lord; but those who disbelieve say : What doth Allah wish ( to teach ) by such a similitude? He misleadeth many thereby, and He guideth many thereby; and He misleadeth thereby only miscreants;<?php break;}
case 27:{?>Those who break the covenant of Allah after ratifying it and sever that which Allah ordered to be joined, and ( who ) make mischief in the earth : Those are they who are the losers<?php break;}
case 28:{?>How disbelieve ye in Allah when ye were dead and He gave life to you! Then he will give you death, then life again, and then unto Him ye will return.<?php break;}
case 29:{?>He it is Who created for you all that is in the earth. Then turned He to the heaven, and fashioned it as seven heavens. And He is Knower of all things.<?php break;}
case 30:{?>And when thy Lord said unto the angels : Lo! I am about to place a viceroy in the earth, they said : wilt Thou place therein one who will do harm therein and will shed blood, while we, we hymn Thy praise and sanctify Thee? He said : Surely I know that which ye know not.<?php break;}
case 31:{?>And He taught Adam all the names, then showed them to the angels, saying : Inform me of the names of these, if ye are truthful.<?php break;}
case 32:{?>They said : Be glorified! We have no knowledge saving that which Thou hast taught us. Lo! Thou, only Thou, art the Knower, the Wise.<?php break;}
case 33:{?>He said : O Adam! Inform them of their names, and when he had informed them of their names, He said : Did I not tell you that I know the secret of the heavens and the earth? And I know that which ye disclose and which ye hide.<?php break;}
case 34:{?>And when We said unto the angels : Prostrate yourselves before Adam, they fell prostrate, all save Iblis He demurred through pride, and so became a disbeliever.<?php break;}
case 35:{?>And We said : O Adam! Dwell thou and thy wife in the Garden, and eat ye freely ( of the fruits ) thereof where ye will; but come not nigh this tree lest ye become wrongdoers.<?php break;}
case 36:{?>But Satan caused them to deflect therefrom and expelled them from the ( happy ) state in which they were; and We said : Fall down, one of you a foe unto the other! There shall be for you on earth a habitation and provision for a tune.<?php break;}
case 37:{?>Then Adam received from his Lord words ( of revelation ), and He relented toward him. Lo! He is the Relenting the Merciful.<?php break;}
case 38:{?>We said : Go down, all of you, from hence; but verily there cometh unto you from Me a guidance; and whoso followeth My guidance, there shall no fear come upon them neither shall they grieve.<?php break;}
case 39:{?>But they who disbelieve, and deny our revelations, such are rightful owners of the Fire. They will abide therein.<?php break;}
case 40:{?>O Children of Israel! Remember My favor wherewith I favored you, and fulfil your ( part of the ) covenant, I shall fulfil My ( part of the ) covenant and fear Me.<?php break;}
case 41:{?>And believe in that which I reveal, confirming that which ye possess already ( of the Scripture ), and be not first to disbelieve therein, and part not with My revelations for a trifling price, and keep your duty unto Me.<?php break;}
case 42:{?>Confound not truth with falsehood, nor knowingly conceal the truth.<?php break;}
case 43:{?>Establish worship, pay the poor-due, and bow your heads with those who bow ( in worship ).<?php break;}
case 44:{?>Enjoin ye righteousness upon mankind while ye yourselves forget ( to practise it )? And ye are readers of the Scripture! Have ye then no sense?<?php break;}
case 45:{?>Seek help in patience and prayer; and truly it is hard save for the humble-minded,<?php break;}
case 46:{?>Who know that they will have to meet their Lord, and that unto Him they are returning.<?php break;}
case 47:{?>O Children of Israel! Remember My favor wherewith I favored you and how I preferred you to ( all ) creatures.<?php break;}
case 48:{?>And guard yourselves against a day when no soul will in aught avail another, nor will intercession be accepted from it, nor will compensation be received from it, nor will they he helped.<?php break;}
case 49:{?>And ( remember ) when We did deliver you from Pharaoh ' s folk, who were afflicting you with dreadful torment, slaying your sons and sparing your women : That was a tremendous trial from your Lord.<?php break;}
case 50:{?>And when We brought you through the sea and rescued you, and drowned the folk of Pharaoh in your sight.<?php break;}
case 51:{?>And when We did appoint for Moses forty nights ( of solitude ), and then ye chose the calf, when he had gone from you, and were wrongdoers.<?php break;}
case 52:{?>Then, even after that, We pardoned you in order that ye might give thanks.<?php break;}
case 53:{?>And when We gave unto Moses the Scripture and the Criterion ( of right and wrong ), that ye might be led aright.<?php break;}
case 54:{?>And when Moses said unto his people : O my people! Ye have wronged yourselves by your choosing of the calf ( for worship ) so turn in penitence to your Creator, and kill ( the guilty ) yourselves. That will be best for you with your Creator and He will relent toward you. Lo! He is the Relenting, the Merciful.<?php break;}
case 55:{?>And when ye said : O Moses! We will not believe in thee till we see Allah plainly; and even while ye gazed the lightning seized you.<?php break;}
case 56:{?>Then We revived you after your extinction, that ye might give thanks.<?php break;}
case 57:{?>And We caused the white cloud to overshadow you and sent down on you the manna and the quails, ( saying ) : Eat of the good things wherewith We have provided you We wronged them not, but they did wrong themselves.<?php break;}
case 58:{?>And when We said : Go into this township and eat freely of that which is therein, and enter the gate prostrate, and say : "Repentance. " We will forgive you your sins and increase ( reward ) for the right-doers.<?php break;}
case 59:{?>But those who did wrong changed the word which had been told them for another saying, and We sent down upon the evil-doers wrath from Heaven for their evil doing.<?php break;}
case 60:{?>And when Moses asked for water for his people, We said : Smite with thy staff the rock. And there gushed out therefrom twelve springs ( so that ) each tribe knew their drinking place. Eat and drink of that which Allah hath provided, and do not act corruptly, making mischief in the earth.<?php break;}
case 61:{?>And when ye said : O Moses! We are weary of one kind of food; so call upon thy Lord for us that he bring forth for us of that which the earth groweth of its herbs and its cucumbers and its corn and its lentils and its onions. He said : Would ye exchange that which is higher for that which is lower? Go down to settled country, thus ye shall get that which ye demand. And humiliation and wretchedness were stamped upon them and they were visited with wrath from Allah. That was because they disbelieved in Allah ' s revelations and slew the prophets wrongfully. That was for their disobedience and transgression.<?php break;}
case 62:{?>Lo! those who believe ( in that which is revealed unto thee, Muhammad ), and those who are Jews, and Christians, and Sabaeans whoever believeth in Allah and the Last Day and doeth right surely their reward is with their Lord, and there shall no fear come upon them neither shall they grieve.<?php break;}
case 63:{?>And ( remember, O children of Israel ) when We made a covenant with you and caused the Mount to tower above you, ( saying ) : Hold fast that which We have given you, and remember that which is therein, that ye may ward off ( evil ).<?php break;}
case 64:{?>Then, even after that, ye turned away, and if it had not been for the grace of Allah and His mercy ye had been among the losers.<?php break;}
case 65:{?>And ye know of those of you who broke the Sabbath, bow We said unto them : Be ye apes, despised and hated!<?php break;}
case 66:{?>And We made it an example to their own and to succeeding generations, and an admonition to the God fearing.<?php break;}
case 67:{?>And when Moses said unto his people : Lo! Allah commandeth you that ye sacrifice a cow, they said : Dost thou make game of us? He answered : Allah forbid that I should be among the foolish!<?php break;}
case 68:{?>They said : Pray for us unto thy Lord that He make clear to us what ( cow ) she is. ( Moses ) answered : Lo! He saith, Verily she is a cow neither with calf nor immature; ( she is ) between the two conditions; so do that which ye are commanded.<?php break;}
case 69:{?>They said : Pray for us unto thy Lord that He make clear to us of what color she is. ( Moses ) answered : Lo! He saith : Verily she is a yellow cow. Bright is her color, gladdening beholders.<?php break;}
case 70:{?>They said : Pray for us unto thy Lord that He make clear to us what ( cow ) she is. Lo! cows are much alike to us; and lo! if Allah wills, we may be led aright.<?php break;}
case 71:{?>( Moses ) answered : Lo! He saith : Verily she is a cow unyoked; she plougheth not the soil nor watereth the tilth; whole and without mark. They said : Now thou bringest the truth. So they sacrificed her, though almost they did not.<?php break;}
case 72:{?>And ( remember ) when ye slew a man and disagreed concerning it and Allah brought forth that which ye were hiding.<?php break;}
case 73:{?>And We said : Smite him with some of it. Thus Allah bringeth the dead to life and showeth you His portents so that ye may understand.<?php break;}
case 74:{?>Then, even after that, your hearts were hardened and became as rocks, or worse than rocks, for hardness. For indeed there are rocks from out which rivers gush, and indeed there are rocks which split asunder so that water Soweth from them. And indeed there are rocks which fall down for the fear of Allah. Allah is not unaware of what ye do.<?php break;}
case 75:{?>Have ye any hope that they will be true to you when a party of them used to listen to the Word of Allah, then used to change it, after they had understood it knowingly?<?php break;}
case 76:{?>And when they fall in with those who believe, they say : We believe. But when they go apart one with another they say : Prate ye to them of that which Allah hath disclosed to you that they may contend with you before your Lord concerning it? Have ye then no sense?<?php break;}
case 77:{?>Are they then unaware that Allah knoweth that which they keep hidden and that which they proclaim?<?php break;}
case 78:{?>Among them are unlettered folk who know the scripture not except from hearsay. They but guess.<?php break;}
case 79:{?>Therefore woe be unto those who write the Scripture with their hands anthem say, "This is from Allah, " that they may purchase a small gain therewith. Woe unto them for that their hands have written, and woe unto them for that they earn thereby.<?php break;}
case 80:{?>And they say : The fire ( of punishment ) will not touch save for a certain number of days. Say : Have ye received a covenant from Allah truly Allah will not break His covenant or tell ye concerning Allah that which ye know not?<?php break;}
case 81:{?>Nay, but whosoever hath done evil and his sin surroundeth him; such are rightful owners of the Fire; they will abide therein.<?php break;}
case 82:{?>And those who believe and do good works : such are rightful owners of the Garden. They will abide therein.<?php break;}
case 83:{?>And ( remember ) when We made a covenant with the Children of Israel, ( saying ) : Worship none save Allah ( only ), and be good to parents and to kindred and to orphans and the needy, and speak kindly to mankind; and establish worship and pay the poor due. Then, after that, ye slid back, save a few of you, being averse.<?php break;}
case 84:{?>And when We made with you a covenant ( saying ) : Shed not the blood of your people nor turn ( a party of ) your people out of your dwellings. Then ye ratified ( Our covenant ) and ye were witnesses ( thereto ).<?php break;}
case 85:{?>Yet ye it is who stay each other and drive out a party of your people from their homes, supporting one another against them by sin and transgression, and if they came to you as captives ye would ransom them, whereas their expulsion was itself unlawful for you. Believe ye in part of the Scripture and disbelieve ye in part thereof? And what is the reward of those who do so save ignominy in the life of the world, and on the Day of Resurrection they will be consigned to the most grievous doom. For Allah is not unaware of what ye do.<?php break;}
case 86:{?>Such are those who buy the life of the world at the price of the Hereafter : Their punishment will not be lightened, neither will they have support.<?php break;}
case 87:{?>And verily We gave unto Moses the Scripture and We caused a train of messengers to follow after him, and We gave unto Jesus, son of Mary, clear proofs ( of Allah ' s sovereignty ), and We supported him with the holy Spirit is it ever so, that, when there cometh unto you a messenger ( from Allah ) with that which ye yourselves desire not, ye grow arrogant, and some ye disbelieve and some ye slay?<?php break;}
case 88:{?>And they say : Our hearts are hardened. Nay, but Allah hath cursed them for their unbelief. Little is that which they believe.<?php break;}
case 89:{?>And when there cometh unto them a Scripture from Allah, confirming that in their possession though before that they were asking for a signal triumph over those who disbelieved and when there cometh unto them that which they know ( to be the Truth ) they disbelieve therein. The curse of Allah is on disbelievers.<?php break;}
case 90:{?>Evil is that for which they sell their souls : that they should disbelieve in that which Allah hath revealed, grudging that Allah should reveal of His bounty unto whom He will of His bondmen. They have incurred anger upon anger. For disbelievers is a shameful doom.<?php break;}
case 91:{?>And when it is said unto them. Believe in that which Allah hath revealed, they say : We believe in that which was revealed unto us. And they disbelieve in that which cometh after it, though it is the truth confirming that which they possess. Say ( unto them, O Muhammad ) : Why then slew ye the Prophets of Allah aforetime, if ye are ( indeed ) believers?<?php break;}
case 92:{?>And Moses came unto you with clear proofs ( of Allah ' s sovereignty ), yet, while he was away, ye chose the calf ( for worship ) and ye were wrongdoers.<?php break;}
case 93:{?>And when We made with you a covenant and caused the Mount to tower above you, ( saying ) : Hold fast by that which We have given you, and hear ( Our Word ), they said : We hear and we rebel. And ( worship of ) the calf was made to sink into their hearts because of their rejection ( of the Covenant ). Say ( unto them ) : Evil is that which your belief enjoineth on you, if ye are believers.<?php break;}
case 94:{?>Say ( unto them ) : If the abode of the Hereafter in the providence of Allah is indeed for you alone and not for others of mankind ( as ye pretend ), then long for death ( for ye must long for death ) if ye are truthful.<?php break;}
case 95:{?>But they will never long for it, because of that which their own hands have sent before them. Allah is Aware of evildoers.<?php break;}
case 96:{?>And thou wilt find them greediest of mankind for life and ( greedier ) than the idolaters. ( Each ) one of them would like to be allowed to live a thousand years. And to live ( a thousand years ) would by no means remove him from the doom. Allah is Seer of what they do.<?php break;}
case 97:{?>Say ( O Muhammad, to mankind ) : Who is an enemy to Gabriel! For he it is who bath revealed ( this Scripture ) to thy heart by Allah ' s leave, confirming that which was ( re- vealed ) before it, and a guidance and glad tidings to believers;<?php break;}
case 98:{?>Who is an enemy to Allah, and His angels and His messengers, and Gabriel and Michael! Then, lo! Allah ( Him- self ) is an enemy to the disbelievers.<?php break;}
case 99:{?>Verily We have revealed unto thee clear tokens, and only miscreants will disbelieve in them.<?php break;}
case 100:{?>Is it ever so that when ye make a covenant a party of you set it aside? The truth is, most of them believe not.<?php break;}
case 101:{?>And when there cometh unto them a messenger from Allah, confirming that which they possess, a party of those who have received the Scripture fling the Scripture of Allah behind their backs as if they knew not,<?php break;}
case 102:{?>And follow that which the devils falsely related against the kingdom of Solomon. Solomon disbelieved not; but the devils disbelieved, teaching mankind magic and that which was revealed to the two angels in Babel, Harut and Marut. Nor did they ( the two angels ) teach it to anyone till they had said : We are only a temptation, therefore disbelieve not ( in the guidance of Allah ). And from these two ( angels ) people learn that by which they cause division between man and wife; but they injure thereby no one save by Allah ' s leave. And they learn that which harmeth them and profiteth them not. And surely they do know that he who trafficketh therein will have no ( happy ) portion in the Hereafter; and surely evil is the price for which they sell their souls, if they but knew.<?php break;}
case 103:{?>And if they had believed and kept from evil, a recompense from Allah would be better, if they only knew.<?php break;}
case 104:{?>O ye who believe, say not ( unto the Prophet ) : "Listen to us" but say "Look upon us, " and be ye listeners. For disbelievers is a painful doom.<?php break;}
case 105:{?>Neither those who disbelieve among the People of the Scripture nor the idolaters love that there should be sent down unto you any good thing from your Lord. But Allah chooseth for His mercy whom He will, and Allah is of infinite bounty.<?php break;}
case 106:{?>Such of Our revelations as We abrogate or cause to be forgotten, we bring ( in place ) one better or the like thereof. Knowest thou not that Allah is Able to do all things?<?php break;}
case 107:{?>Knowest thou not that it is Allah unto Whom belongeth the sovereignty of the heavens and earth; and ye have not, beside Allah, any friend or helper?<?php break;}
case 108:{?>Or would ye question your messenger as Moses was questioned aforetime? He who chooseth disbelief instead of faith, verily he hath gone astray from a plain road.<?php break;}
case 109:{?>Many of the People of the Scripture long to make you disbelievers after your belief, through envy on their own account, after the truth hath become manifest unto them. Forgive and be indulgent ( toward them ) until Allah give command. Lo! Allah is Able to do all things.<?php break;}
case 110:{?>Establish worship, and pay the poor due; and whatever of good ye send before ( you ) for your souls, ye will find it with Allah. Lo! Allah is Seer of what ye do.<?php break;}
case 111:{?>And they say : None entereth Paradise unless he be a Jew or a Christian. These are their own desires. Say : Bring your proof ( of what ye state ) if ye are truthful.<?php break;}
case 112:{?>Nay, but whosoever surrendereth his purpose to Allah while doing good, his reward is with his Lord; and there shall no fear come upon them neither shall they grieve.<?php break;}
case 113:{?>And the Jews say the Christians follow nothing ( true ), and the Christians say the Jews follow nothing ( true ); yet both are readers of the Scripture. Even thus speak those who know not. Allah will judge between them on the Day of Resurrection concerning that wherein they differ.<?php break;}
case 114:{?>And who doth greater wrong than he who forbiddeth the approach to the sanctuaries of Allah lest His name should be mentioned therein, and striveth for their ruin? As for such, it was never meant that they should enter them except in fear. Theirs in the world is ignominy and theirs in the Hereafter is an awful doom.<?php break;}
case 115:{?>Unto Allah belong the East and the West, and whither- soever ye turn, there is Allah ' s countenance. Lo! Allah is All Embracing, All Knowing.<?php break;}
case 116:{?>And they say : Allah hath taken unto Himself a Son. Be He glorified! Nay, but whatsoever is in the heaven and the earth, His. All are subservient unto Him.<?php break;}
case 117:{?>The Originator of the heavens and the earth! When He decreeth a thing, He saith unto it only : Be! and it is.<?php break;}
case 118:{?>And those who have no knowledge say : Why doth not Allah speak unto us, or some sign come unto us? Even thus, as they now speak, spake those ( who were ) before them. Their hearts are all alike. We have made clear the revelations for people who are sure.<?php break;}
case 119:{?>Lo! We have sent thee ( O Muhammad ) with the truth, a bringer of glad tidings and a warner. And thou wilt not be asked about the owners of hell fire.<?php break;}
case 120:{?>And the Jews will not be pleased with thee, nor will the Christians, till thou follow their creed. Say : Lo! the guidance of Allah ( Himself ) is Guidance. And if thou shouldst follow their desires after the knowledge which hath come unto thee, then wouldst thou have from Allah no protecting friend nor helper.<?php break;}
case 121:{?>Those unto whom We have given the Scripture, who read it with the right reading, those believe in it. And whoso disbelieveth in it, those are they who are the losers.<?php break;}
case 122:{?>O Children of Israel! Remember My favor wherewith I favored you and how I referred you to ( all ) creatures.<?php break;}
case 123:{?>And guard ( yours against a day when no soul will naught avail another, nor will compensation be accepted from it, nor will intercession be of Use to it; nor will they be helped.<?php break;}
case 124:{?>And ( remember ) when his Lord tried Abraham with ( His ) commands, and he fulfilled them, He said : Lo! I have appointed thee a leader for mankind. ( Abraham ) said : And of my offspring ( will there be leurders )? He said : My covenant includeth not wrongdoers.<?php break;}
case 125:{?>And when We made the House ( at Mecca ) a resort for mankind and a sanctuary, ( saying ) : Take as your place of worship the place where Abraham stood ( to pray ). And We imposed a duty upon Abraham and Ishmael, ( saying ) : Purify My house for those who go around and those who meditate therein and those who bow down and prostrate themselves ( in worship ).<?php break;}
case 126:{?>And when Abraham prayed : My Lord! Make this a region of security and bestow upon its people fruits, such of them as believe in Allah and the Last Day, He answered : As for him who disbelieveth, I shall leave him in contentment for a while, then I shall compel him to the doom of fire a hapless journey ' s end!<?php break;}
case 127:{?>And when Abraham and Ishmael were raising the foundations of the House, ( Abraham prayed ) : Our Lord! Accept from us ( this duty ). Lo! Thou, only Thou, art the Nearer, the Knower.<?php break;}
case 128:{?>Our Lord! And make us submissive unto Thee and of our seed a nation submissive unto Thee, and show us our ways of worship, and relent toward us. Lo! Thou, only Thou, art the Relenting, the Merciful.<?php break;}
case 129:{?>Our Lord! And raise up in their midst a messenger from among them who shall recite unto them Thy revelations, and shall instruct them in the Scripture and in wisdom and shall make them grow. Lo! Thou, only Thou, art the Mighty, Wise.<?php break;}
case 130:{?>And who forsaketh the religion of Abraham save him who befooleth himself? Verily We chose him in the world, and lo! in the Hereafter he is among the righteous.<?php break;}
case 131:{?>When his Lord said unto him : Surrender! he said : I have surrendered to the Lord of the Worlds.<?php break;}
case 132:{?>The same did Abraham enjoin upon his sons, and also Jacob, ( saying ) : O my sons! Lo! Allah hath chosen for you the ( true ) religion; therefore die not save as men who have surrendered ( unto Him ).<?php break;}
case 133:{?>Or were ye present when death came to Jacob, when he said unto his sons : What will ye worship after me? They said : We shall worship thy God, the God of thy fathers, Abraham and Ishmael and Isaac, One God, and unto Him we have surrendered.<?php break;}
case 134:{?>Those are a people who have passed away. Theirs is that which they earned, and yours is that which ye earn. And ye will not be asked of what they used to do.<?php break;}
case 135:{?>And they say : Be Jews or Christians, then ye will be rightly guided. Say ( unto them, O Muhammad ) : Nay, but ( we follow ) the religion of Abraham, the upright, and he was not of the idolaters.<?php break;}
case 136:{?>Say ( O Muslims ) : We believe in Allah and that which is revealed unto Us and that which was revealed unto Abraham, and Ishmael, and Isaac, and Jacob. and the tribes, and that which Moses and Jesus received, add that which the Prophets received from their Lord. We make no distinction between any of them, and unto Him we have surrendered.<?php break;}
case 137:{?>And if they believe in the like of that which ye believe, then are they rightly guided. But if they turn away, then are they in schism, and Allah will suffice thee ( for defence ) against them. He is the Hearer, the Knower.<?php break;}
case 138:{?>( We take our ) color from Allah, and who is better than Allah at coloring. We are His worshippers.<?php break;}
case 139:{?>Say ( unto the People of the Scripture ) : Dispute ye with us concerning Allah when He is our Lord and your Lord? Ours are our works and yours your works. We look to Him alone.<?php break;}
case 140:{?>Or say ye that Abraham, and Ishmael, and Isaac, and Jacob, and the tribes were Jews or Christians? Say : Do ye know best, or doth Allah? And who is more unjust than he who hideth a testimony which he hath received from Allah? Allah is not unaware of what ye do.<?php break;}
case 141:{?>Those are a people who have passed away; theirs is that which they earned and yours that which ye earn. And ye will not be asked of what they used to do.<?php break;}
case 142:{?>The foolish of the people will say : What hath turned them from the qiblah which they formerly observed? Say : Unto Allah belong the East and the West. He guideth whom He will unto a straight path.<?php break;}
case 143:{?>Thus We have appointed you a middle nation, that ye may be witnesses against mankind. and that the messenger may be a witness against you. And We appointed the qiblah which ye formerly observed only that We might know him who followeth the messenger, from him who turneth on his heels. In truth it was a hard ( test ) save for those whom Allah guided. But it was not Allah ' s purpose that your faith should be in vain, for Allah is full of pity, Merciful toward mankind.<?php break;}
case 144:{?>We have seen the turning of thy face to heaven ( for guidance, O Muhammad ). And now verily We shall make thee turn ( in prayer ) toward a qiblah which is dear to thee. So turn thy face toward the Inviolable Place of Worship, and ye ( O Muslims ), wheresoever ye may be, turn your faces when ye pray ) toward it. Lo! those who have received the Scripture know that ( this Revelation ) is the Truth from their Lord. And Allah is not unaware of what they do.<?php break;}
case 145:{?>And even if thou broughtest unto those who have received the Scripture all kinds of portents, they would not follow thy qiblah, nor canst thou be a follower of their qiblah; nor are some of them followers of the qiblah of others. And if thou shouldst follow their desires after the knowledge which hath come unto thee, then surely wert thou of the evil doers.<?php break;}
case 146:{?>Those unto whom We gave the Scripture recognize ( this revelation ) as they recognize their sons. But lo! a party of them knowingly conceal the truth.<?php break;}
case 147:{?>It is the Truth from thy Lord ( O Muhammad ), so be not thou of those who waver.<?php break;}
case 148:{?>And each one hath a goal toward which he turneth; so vie with one another in good works. Wheresoever ye may be, Allah will bring you all together. Lo! Allah is Able to do all things.<?php break;}
case 149:{?>And whencesoever thou comest forth ( for prayer, O Muhammad ) turn thy face toward the Inviolable Place of Worship. Lo! it is the Truth from thy Lord Allah is not unaware of what ye do.<?php break;}
case 150:{?>Whencesoever thou comest forth turn thy face toward the Inviolable Place of Worship; and wheresoever ye may be ( O Muslims ) turn your faces toward it ( when ye pray ) so that men may have no argument against you, save such of them as do injustice Fear them not, but fear Me and so that I may complete My grace upon you, and that ye may be guided.<?php break;}
case 151:{?>Even as We have sent unto you a messenger from among you, who reciteth unto you Our revelations and causeth you to grow, and teacheth you the Scripture and wisdom, and teacheth you that which ye knew not. '<?php break;}
case 152:{?>Therefore remember Me, I will remember you. Give thanks to Me, and reject not Me.<?php break;}
case 153:{?>O ye who believe! Seek help in steadfastness, and prayer. Lo! Allah is with the steadfast.<?php break;}
case 154:{?>And call not those who are slain in the way of Allah "dead. " Nay, they are living, only ye perceive not.<?php break;}
case 155:{?>And surely We shall try you with something of fear and hunger, and loss of wealth and lives and crops; but give glad tidings to the steadfast,<?php break;}
case 156:{?>Who say, when a misfortune striketh them : Lo! we are Allah ' s and Lo! unto Him we are returning.<?php break;}
case 157:{?>Such are they on whom are blessings from their Lord, and mercy. Such are the rightly guided.<?php break;}
case 158:{?>Lo! ( the mountains ) Al-Safa and Al-Marwah are among the indications of Allah. It is therefore no sin for him who is on pilgrimage to the House ( of God ) or visiteth it, to go around them ( as the pagan custom is ). And he who doeth good of his own accord ( for him ), Lo! Allah is Responsive, Aware.<?php break;}
case 159:{?>Those who hide the proofs and the guidance which We revealed, after We had made it clear in the Scripture : such are accursed of Allah and accursed of those who have the power to curse.<?php break;}
case 160:{?>Except such of them as repent and amend and make manifest ( the truth ). These it is toward whom I relent. I am the Relenting, the Merciful.<?php break;}
case 161:{?>Lo! those who disbelieve, and die while they are disbelievers; on them is the curse of Allah and of angels and of men combined.<?php break;}
case 162:{?>They ever dwell therein. The doom will not be lightened for them, neither will they be reprieved.<?php break;}
case 163:{?>Your God is One God; there is no God save Him, the Beneficent, the Merciful.<?php break;}
case 164:{?>Lo! in the creation of the heavens and the earth, and the difference of night and day, and the ships which run upon the sea with that which is of use to men, and the water which Allah sendeth down from the sky, thereby reviving the earth after its death, and dispersing all kinds of beasts therein, and ( in ) the ordinance of the winds, and the clouds obedient between heaven and earth : are signs ( of Allah ' s sovereignty ) for people who have sense.<?php break;}
case 165:{?>Yet of mankind are some who take unto themselves objects of worship which they set as ) rivals to Allah, loving them with a love like ( that which is the due ) of Allah ( only ) Those who believe are stauncher in their love for Allah, that those who do evil had but known, ( on the day ) when they behold the doom, that power belongeth wholly to Allah, and that Allah is severe in punishment!<?php break;}
case 166:{?>( On the day ) when those who were followed disown those who followed ( them ), and they behold the doom, and all their aims collapse with them.<?php break;}
case 167:{?>And those who were but followers will say : If a return were possible for us, we would disown them even as they have disowned us. Thus will Allah show them their own deeds as anguish for them, and they will not emerge from the Fire.<?php break;}
case 168:{?>O mankind! Eat of that which is lawful and wholesome in the earth, and follow not the footsteps of the devil. Lo! he is an open enemy for you.<?php break;}
case 169:{?>He enjoineth upon you only the evil and the foul, and that ye should tell concerning Allah that which ye know not.<?php break;}
case 170:{?>And when it is said unto them : Follow that which Allah hath revealed, they say : We follow that wherein we found our fathers. What! Even though their fathers were wholly unintelligent and had no guidance?<?php break;}
case 171:{?>The likeness of those who disbelieve ( in relation to the messenger ) is as the likeness of one who calleth unto that which heareth naught except a shout and cry. Deaf, dumb, blind, therefore they have no sense.<?php break;}
case 172:{?>O ye who believe! Eat of the good things wherewith We have provided you, and render thanks to Allah if it is ( indeed ) He whom ye worship.<?php break;}
case 173:{?>He hath forbidden you only carrion, and blood, and swineflesh, and that which hath been immolated to ( the name of ) any other than Allah. But he who is driven by necessity, neither craving nor transgressing, it is no sin for him. Lo! Allah is Forgiving, Merciful.<?php break;}
case 174:{?>Lo! those who hide aught of the Scripture which Allah hath revealed, and purchase a small gain therewith, they eat into their bellies nothing else than fire. Allah will not speak to them on the Day of Resurrection, nor will He make them grow. Theirs will be a painful doom.<?php break;}
case 175:{?>Those are they who purchase error at the price of guidance, and torment at the price of pardon. How constant are they in their strife to reach the Fire!<?php break;}
case 176:{?>That is because Allah hath revealed the Scripture with the truth. Lo! those who find ( a cause of ) disagreement in the Scripture are in open schism.<?php break;}
case 177:{?>It is not righteousness that ye turn your faces to the East and the West; but righteous is he who believeth in Allah and the Last Day and the angels and the Scripture and the Prophets; and giveth his wealth, for love of Him, to kinsfolk and to orphans and the needy and the wayfarer and to those who ask, and to set slaves free; and observeth proper worship and payeth the poor due. And those who keep their treaty when they make one, and the patient in tribulation and adversity and time of stress. Such are they who are sincere. Such are the God fearing.<?php break;}
case 178:{?>O ye who believe! Retaliation is prescribed for you in the matter of the murdered; the freeman for the freeman, and the slave for the slave, and the female for the female. And for him who is forgiven somewhat by his ( injured ) brother, prosecution according to usage and payment unto him in kindness. This is an alleviation and a mercy from your Lord. He who transgresseth after this will have a painful doom.<?php break;}
case 179:{?>And there is life for you in retaliation, O men of understanding, that ye may ward off ( evil ).<?php break;}
case 180:{?>It is prescribed for you, when one of you approacheth death, if he leave wealth, that he bequeath unto parents and near relatives in kindness. ( This is ) a duty for all those who ward off ( evil ).<?php break;}
case 181:{?>And whoso changeth ( the will ) after he hath heard it the sin thereof is only upon those who change it. Lo! Allah is Hearer, Knower.<?php break;}
case 182:{?>But he who feareth from a testator some unjust or sinful clause, and maketh peace between the parties, ( it shall be ) no sin for him. Lo! Allah is Forgiving, Merciful.<?php break;}
case 183:{?>O ye who believe! Fasting is prescribed for you, even as it was prescribed for those before you, that ye may ward off evil );<?php break;}
case 184:{?>( Fast ) a certain number of days; and ( for ) him who is sick among you, or on a journey, ( the same ) number of other days; and for those who can afford it there is a ransom : the feeding of a man in need. But whoso doeth good of his own accord, it is better for him : and that ye fast is better for you if ye did but know<?php break;}
case 185:{?>The month of Ramadan in which was revealed the Quran, a guidance for mankind, and clear proofs of the guidance, and the Criterion ( of right and wrong ). And whosoever of you is present, let him fast the month, and whosoever of you is sick or on a journey, ( let him fast the same ) number of other days. Allah desireth for you ease; He desireth not hardship for you; and ( He desireth ) that ye should complete the period, and that ye should magnify Allah for having guided you, and that peradventure ye may be thankful.<?php break;}
case 186:{?>And when My servant question thee concerning Me, then surely I am nigh. I answer the prayer of the suppliant when he crieth unto Me. So let them bear My call and let them trust in Me, in order that they may be led aright.<?php break;}
case 187:{?>It is made lawful for you to go unto your wives on the night of the fast. They are raiment for you and ye are raiment for them. Allah is aware that ye were deceiving yourselves in this respect and He hath turned in mercy toward you and relieved you. So hold intercourse with them and seek that which Allah hath ordained for you, and eat and drink until the white thread becometh distinct to you from the black thread of the dawn. Then strictly observe the fast till nightfall and touch them not, but be at your devotions in the mosques. These are the limits imposed by Allah, so approach them not. Thus Allah expoundeth His revelations to mankind that they may ward off ( evil ).<?php break;}
case 188:{?>And eat not up your property among yourselves in vanity, nor seek by it to gain the hearing of the judges that ye may knowingly devour a portion of the property of others wrongfully.<?php break;}
case 189:{?>They ask thee, ( O Muhammad ), of new moons. Say : They are fixed seasons for mankind and for the pilgrimage. It is not righteousness that ye go to houses by the backs thereof ( as do the idolaters at certain seasons ), but the righteous man is he who wardeth off ( evil ). So go to houses by the gates thereof, and observe your duty to Allah, that ye may be successful<?php break;}
case 190:{?>Fight in the way of Allah against those who fight against you, but begin not hostilities. Lo! Allah loveth not, aggressors.<?php break;}
case 191:{?>And slay them wherever ye find them, and drive them out of the places whence they drove you out, for persecution is worse than slaughter. And fight not with them at the Inviolable Place of Worship until they first attack you there, but if they attack you ( there ) then slay them. Such is the reward of disbelievers.<?php break;}
case 192:{?>But if they desist, then lo! Allah is Forgiving, Merciful.<?php break;}
case 193:{?>And fight them until persecution is no more, and religion is for Allah. But if they desist, then let there be no hostility except against wrongdoers.<?php break;}
case 194:{?>The forbidden month for the forbidden month, and forbidden things in retaliation. And one who attacketh you, attack him like manner as he attacked you. Observe your duty to Allah, and know that Allah is with those who ward off ( evil ).<?php break;}
case 195:{?>Spend your wealth for the cause of Allah, and be not cast by your own hands to ruin; and do good. Lo! Allah loveth the beneficent<?php break;}
case 196:{?>Perform the pilgrimage and the visit ( to Mecca ) for Allah. And if ye are prevented, then send such gifts as can be obtained with ease, and shave not your heads until the gifts have reached their destination. And whoever among you is sick or hath an ailment of the head must pay a ransom of fasting or alms giving or offering. And if ye are in safety, then whosoever contenteth himself with the Visit for the Pilgrimage ( shall give ) such gifts as can be had with ease. And whosoever cannot find ( such gifts, then a fast of three days while on the pilgrimage, and of seven when ye have returned; that is, ten in all. That is for him whose folk are not present at the Inviolable Place of Worship. Observe your duty to Allah, and know that Allah is severe in punishment.<?php break;}
case 197:{?>The pilgrimage is ( in ) the well known months, and whoever is minded to perform the pilgrimage therein ( let him remember that ) there is ( to be ) no lewdness nor abuse nor angry conversation on the pilgrimage. And whatsoever good ye do Allah knoweth it. So make provision for yourselves ( here after ); for the best provision is to ward off evil. Therefore keep your duty unto Me, O men of understanding.<?php break;}
case 198:{?>It is no sin for you that ye seek the bounty of your Lord ( by trading ). But, when ye press on in the multitude from Arafat, remember Allah by the sacred monument. Remember Him as He hath guided you, although before ye were of those astray.<?php break;}
case 199:{?>Then hasten onward from the place whence the multitude hasteneth onward, and ask forgiveness of Allah. Lo! Allah is Forgiving, Merciful.<?php break;}
case 200:{?>And when ye have completed your devotions, then remember Allah as ye remember your fathers or with a more lively remembrance. But of mankind is he who saith : "our Lord! Give unto us in the world, " and he hath no portion in the Hereafter.<?php break;}
case 201:{?>And of them ( also ) is he who saith : "Our Lord! Give unto us in the world that which is good and in the Hereafter that which is good, and guard us from the doom of Fire. "<?php break;}
case 202:{?>For them there is in store a goodly portion out of that which they have earned. Allah is swift at reckoning.<?php break;}
case 203:{?>Remember Allah through the appointed days. Then whoso hasteneth ( his departure ) by two days, it is no sin for him, and whoso delayeth, it is no sin for him; that is for him who wardeth off ( evil ). Be careful of your duty to Allah, and know that unto Him ye will be gathered.<?php break;}
case 204:{?>And of mankind there is he whose conversation on the life of this world pleaseth thee ( Muhammad ), and he calleth Allah to witness as to that which is in his heart; yet he is the most rigid of opponents.<?php break;}
case 205:{?>And when he turneth away ( from thee ) his effort in the land is to make mischief therein and to destroy the crops and the cattle; and Allah loveth not mischief.<?php break;}
case 206:{?>And when it is said unto him : Be careful of thy duty to Allah, pride taketh him to sin. Hell will settle his account, an evil resting place.<?php break;}
case 207:{?>And of mankind is he who would sell himself, seeking the pleasure of Allah; and Allah hath compassion on ( His ) bondmen.<?php break;}
case 208:{?>O ye who believe! Come, all of you, into submission ( unto Him ); and follow not the footsteps of the devil. Lo! he is an open enemy for you.<?php break;}
case 209:{?>And if ye slide back after the clear proofs have come unto you, then know that Allah is Mighty, Wise.<?php break;}
case 210:{?>Wait they for naught else than that Allah should come unto them in the shadows of the clouds with the angels? Then the case would be already judged. All cases go back to Allah ( for judgment ).<?php break;}
case 211:{?>Ask of the Children of Israel how many a clear revelation We gave them! He who altereth the grace of Allah after it hath come unto him ( for him ), lo! Allah is severe in punishment.<?php break;}
case 212:{?>Beautified is the life of the world for those who disbelieve; they make a jest of the believers. But those who keep their duty to Allah will be above them on the Day of Resurrection. Allah giveth without stint to whom He will.<?php break;}
case 213:{?>Mankind were one community, and Allah sent ( unto them ) Prophets as bearers of good tidings and as warners, and revealed therewith the Scripture with the truth that it might judge between mankind concerning that wherein they differed. And only those unto whom ( the Scripture ) was given differed concerning it, after clear proofs had come unto them, through hatred one of another. And Allah by His will guided those w believe unto the truth of that concerning which they differed. Allah guideth whom He will unto a straight path<?php break;}
case 214:{?>Or think ye that ye will enter Paradise while yet there hath not come unto you the like of ( that which came to ) those who passed away before you? Affliction and adversity befell them, they were shaken as with earthquake, till the messenger ( of Allah ) and those who believed along with him said : When cometh Allah ' s help? Now surely Allah ' s help is nigh.<?php break;}
case 215:{?>They ask thee, ( O Muhammad ), what they shall spend. Say : That which ye spend for good ( must go ) to parents and near kindred and orphans and the needy and the wayfarer. And whatsoever good ye do, lo! Allah is Aware of it.<?php break;}
case 216:{?>Warfare is ordained for you, though it is hateful unto you; but it may happen that ye hate a thing which is good for you, and it may happen that ye love a thing which is bad for you. Allah knoweth, ye know not.<?php break;}
case 217:{?>They question thee ( O Muhammad ) with regard to warfare in the sacred month. Say : Warfare therein is a great ( transgression ), but to turn ( men ) from the way of Allah, and to disbelieve in Him and in the Inviolable Place of Worship, and to expel his people thence, is a greater with Allah; for persecution is worse than killing. And they will not cease from fighting against you till they have made you renegades from your religion, if they can. And whoso becometh a renegade and dieth in his disbelief : such are they whose works have fallen both in the world and the Hereafter. Such are rightful owners of the Fire : they will abide there in.<?php break;}
case 218:{?>Lo! those who believe, and those who emigrate ( to escape the persecution ) and strive in the way of Allah, these have hope of Allah ' s mercy. Allah is Forgiving, Merciful.<?php break;}
case 219:{?>They question thee about strong drink and games of chance. Say : In both is great sin, and ( some ) utility for men; but the sin of them is greater than their usefulness. And they ask thee what they ought to spend. Say : That which is superfluous. Thus Allah maketh plain to you ( His ) revelations, that haply ye may reflect<?php break;}
case 220:{?>Upon the world and the Hereafter. And they question thee concerning orphans. Say : To improve their lot is best. And if ye mingle your affairs with theirs, then ( they are ) your brothers. Allah knoweth him who spoileth from him who improveth. Had Allah willed He could have overburdened you. Allah is Mighty, Wise.<?php break;}
case 221:{?>Wed not idolatresses till they believe; for lo! a believing bondwoman is better than an idolatress though she please you; and give not your daughters in marriage to idolaters till they believe, for lo! a believing slave is better than an idolater though he please you. These invite unto the Fire, and Allah inviteth unto the Garden, and unto forgiveness by His grace, and expoundeth thus His revelations to mankind that haply they may remember.<?php break;}
case 222:{?>They question thee ( O Muhammad ) concerning menstruation. Say : It is an illness, so let women alone at such time and go not in unto them till they are cleansed. And when they have purified themselves, then go in unto them as Allah hath enjoined upon you. Truly Allah loveth those who turn unto Him, and loveth those who have a care for cleanness.<?php break;}
case 223:{?>Your women are a tilth for you ( to cultivate ) go to your tilth as ye will, and send ( good deeds ) before you for your souls, and fear Allah, and know that ye will ( one day ) meet Him. Give glad tidings to believers, ( O Muhammad ).<?php break;}
case 224:{?>And make not Allah, by your oaths, a hindrance to your being righteous and observing your duty unto Him and making peace among mankind. Allah is Nearer, Knower.<?php break;}
case 225:{?>Allah will not take you to task for that which unintentional in your oaths. But He will take you to task for that which your hearts have garnered. Allah is Forgiving, Clement.<?php break;}
case 226:{?>Those who forswear their wives must wait four months; then, if they change their mind, lo! Allah is Forgiving, Merciful.<?php break;}
case 227:{?>And if they decide upon divorce ( let them remember that ) Allah is Nearer, Knower.<?php break;}
case 228:{?>Women who are divorced shall wait, keeping themselves apart, three ( monthly ) courses. And it is not lawful for them that they should conceal that which Allah hath created in their wombs if they are believers in Allah and the Last Day. And their husbands would do better to take them back in that case if they desire a reconciliation. And they ( women ) have rights similar to those ( of men ) over them in kindness, and men are a degree above them. Allah is Mighty, Wise.<?php break;}
case 229:{?>Divorce must be pronounced twice and then ( a woman ) must be retained in honor or released in kindness. And it is not lawful for you that ye take from women aught of that which ye have given them; except ( in the case ) when both fear that they may not be able to keep within the limits ( imposed by ) Allah. And if ye fear that they may not be able to keep the limits of Allah, in that case it is no sin for either of them if the woman ransom herself. These are the limits ( imposed by ) Allah. Transgress them not. For whoso transgresseth Allah ' s limits : such are wrongdoers.<?php break;}
case 230:{?>And if he hath divorced her ( the third time ), then she is not lawful unto him thereafter until she hath wedded another husband. Then if he ( the other husband ) divorce her it is no sin for both of them that they come together again if they consider that they are able to observe the limits of Allah. These are the limits of Allah. He manifesteth them for people who have knowledge.<?php break;}
case 231:{?>When ye have divorced women, and they have reached their term, then retain them in kindness or release them in kindness. Retain them not to their hurt so that ye transgress ( the limits ). He who doeth that hath wronged his soul. Make not the revelations of Allah a laughing stock ( by your behavior ), but remember Allah ' s grace upon you and that which He hath revealed unto you of the Scripture and of wisdom, whereby He doth exhort you. Observe your duty to Allah and know that Allah is Aware of all things.<?php break;}
case 232:{?>And when ye have divorced women and they reach their term, place not difficulties in the way of their marrying their husbands if it is agreed between them in kindness. This is an admonition for him among you who believeth in Allah and the Last Day. That is more virtuous for you, and cleaner. Allah knoweth : ye know not.<?php break;}
case 233:{?>Mothers shall suckle their children for two whole years; ( that is ) for those who wish to complete the suckling. The duty of feeding and clothing nursing mothers in a seemly manner is upon the father of the child. No one should be charged beyond his capacity. A mother should not be made to suffer because of her child, nor should he to whom the child is born ( be made to suffer ) because of his child. And on the ( father ' s ) heir is incumbent the like of that ( which was incumbent on the father ). If they desire to wean the child by mutual consent and ( after ) consultation, it is no sin for them; and if ye wish to give your children out to nurse, it is no sin for you, provided that ye pay what is due from you in kindness. Observe your duty to Allah, and know that Allah is Seer of what ye do.<?php break;}
case 234:{?>Such of you as die and leave behind them wives, they ( the wives ) shall wait, keeping themselves apart, four months and ten days. And when they reach the term ( prescribed for them ) then there is no sin for you in aught that they may do with themselves in decency. Allah is Informed of what ye do.<?php break;}
case 235:{?>There is no sin for you in that which ye proclaim or hide in your minds concerning your troth with women. Allah knoweth that ye will remember them. But plight not your troth with women except by uttering a recognized form of words. And do not consummate the marriage until ( the term ) prescribed is run. Know that Allah knoweth what is in your minds, so beware of Him; and know that Allah is Forgiving, Clement.<?php break;}
case 236:{?>It is no sin for you if ye divorce women while yet ye have not touched them, nor appointed unto them a portion. Provide for them, the rich according to his means, and the straitened according to his means, a fair provision. ( This is ) a bounden duty for those who do good.<?php break;}
case 237:{?>If ye divorce them before ye have touched them and ye have appointed unto them a portion, then ( pay the ) half of that which ye appointed, unless they ( the women ) agree to forgo it, or he agreeth to forgo it in whose hand is the marriage tie. To forgo is nearer to piety; And forget not kindness among yourselves. Allah is Seer of what ye do.<?php break;}
case 238:{?>Be guardians of your prayers, and of the midmost prayer, and stand up with devotion to Allah.<?php break;}
case 239:{?>And if ye go in fear, then ( pray ) standing or on horseback. And when ye are again in safety, remember Allah, as He hath taught you that which ( heretofore ) ye knew not.<?php break;}
case 240:{?>( In the case of ) those of you who are about to die and leave behind them wives, they should bequeath unto their wives a provision for the year without turning them out, but if they go out ( of their own accord ) there is no sin for you in that which they do of themselves within their rights. Allah is Mighty, Wise.<?php break;}
case 241:{?>For divorced women a provision in kindness : a duty for those who ward off ( evil ).<?php break;}
case 242:{?>Thus Allah expoundeth unto you His revelations so that ye may understand.<?php break;}
case 243:{?>Bethink thee ( O Muhammad ) of those of old, who went forth from their habitations in their thousands, fearing death, and Allah said unto them : Die, and then He brought them back to life. Lo! Allah is a Lord of Kindness to mankind, but most of mankind give not thanks.<?php break;}
case 244:{?>Fight in the way of Allah, and know that Allah is Nearer, Knower.<?php break;}
case 245:{?>Who is it that will lend unto Allah a goodly loan, so that He may give it increase manifold? Allah straiteneth and enlargeth. Unto Him ye will return.<?php break;}
case 246:{?>Bethink thee of the leaders of the Children of Israel after Moses, how they said unto a Prophet whom they had : Set up for us a King and we will fight in Allah ' s way. He said : Would ye then refrain from fighting if fighting were prescribed for you? They said : Why should we not fight in Allah ' s way when we have been driven from our dwellings with our children? Yet, when fighting was prescribed for them, they turned away, all save a few of them. Allah is Aware of evil doers.<?php break;}
case 247:{?>Their Prophet said unto them : Lo! Allah hath raised up Saul to be a king for you. They said : How can he have kingdom over us when we are more deserving of the kingdom than he is, since he hath not been given wealth enough? He said : Lo! Allah hath chosen him above you, and hath increased him abundantly in wisdom and stature. Allah bestoweth His sovereignty on whom He will. Allah is All Embracing, All Knowing.<?php break;}
case 248:{?>And their Prophet said unto them : Lo! the token of his kingdom is that there shall come unto you the ark wherein is peace of reassurance from your Lord, and a remnant of that which the house of Moses and the house of Aaron left behind, the angels bearing it. Lo! herein shall be a token for you if ( in truth ) ye are believers.<?php break;}
case 249:{?>And when Saul set out with the army, be said : Lo! Allah will try you by ( the ordeal of ) a river. Whosoever therefore drinketh thereof he is not of me, and whosoever tasteth it not he is of me, save him who taketh ( thereof ) in the hollow of his hand. But they drank thereof, all save a few of them. And after he had crossed ( the river ), he and those who believed with him, they said : We have no power this day against Goliath and his hosts. But those who knew that they would meet their Lord exclaimed : How many a little company hath overcome a mighty host by Allah ' s leave! Allah is with the steadfast.<?php break;}
case 250:{?>And when they went into the field against Goliath and his hosts they said : Our Lord! Bestow on us endurance, make our foothold sure, and give us help against the disbelieving folk.<?php break;}
case 251:{?>So they routed them by Allah ' s leave and David slew Goliath; and Allah gave him the kingdom and wisdom, and taught him of that which He willeth. And if Allah had not repelled some men by others the earth would have been corrupted. But Allah is a Lord of Kindness to ( His ) creatures.<?php break;}
case 252:{?>These are the portents of Allah which We recite unto thee ( Muhammad ) with truth, and Lo! thou art of the number of ( Our ) messengers;<?php break;}
case 253:{?>Of those messengers, some of whom We have caused to excel others, and of whom there are some unto whom Allah spake, while some of them He exalted ( above others ) in degree; and We gave Jesus, son of Mary, clear proofs ( of Allah ' s sovereignty ) and We supported him with the holy Spirit. And if Allah had so willed it, those who followed after them would not have fought one with another after the clear proofs had come unto them. But they differed, some of them believing and some disbelieving. And if Allah had so willed it, they would not have fought one with another; but Allah doeth what He will.<?php break;}
case 254:{?>O ye who believe! Spend of that wherewith We have provided you ere a day come when there will be no trafficking, nor friendship, nor intercession. The disbelievers, they are the wrong doers.<?php break;}
case 255:{?>Allah! There is no god but He,-the Living, the Self-subsisting, Eternal. No slumber can seize Him nor sleep. His are all things in the heavens and on earth. Who is there can intercede in His presence except as He permitteth? He knoweth what (appeareth to His creatures as) before or after or behind them. Nor shall they compass aught of His knowledge except as He willeth. His Throne doth extend over the heavens and the earth, and He feeleth no fatigue in guarding and preserving them for He is the Most High, the Supreme (in glory).<?php break;}
case 256:{?>There is no compulsion in religion. The right direction is henceforth distinct from error. And he who rejecteth false deities and believeth in Allah hath grasped a firm hand hold which will never break. Allah is Hearer, Knower.<?php break;}
case 257:{?>Allah is-the Protecting Friend of those who believe. He bringeth them out of darkness into light. As for those who disbelieve, their patrons are false deities. They bring them out of light into darkness. Such are rightful owners of the Fire. They will abide therein.<?php break;}
case 258:{?>Bethink thee of him who had an argument with Abraham about his Lord, because Allah had given him the kingdom; how, when Abraham said : My Lord is He who giveth life and causeth death, he answered : I give life and cause death. Abraham said : Lo! Allah causeth the sun to rise in the East, so do thou cause it to come up from the West. Thus was the disbeliever abashed. And Allah guideth not wrong doing folk.<?php break;}
case 259:{?>Or ( bethink thee of ) the like of him who, passing by a township which had fallen into utter ruin, exclaimed : How shall Allah give this township life after its death? And Allah made him die a hundred years, then brought him back to life. He said : How long hast thou tarried? ( The man ) said : I have tarried a day or part of a day. ( He ) said : Nay, but thou hast tarried for a hundred years. Just look at thy food and drink which have rotted! Look at thine ass! And, that We may make thee a token unto mankind, look at the bones, how We adjust them and then cover them with flesh! And when ( the matter ) became clear unto him, he said : I know now that Allah is Able to do all things.<?php break;}
case 260:{?>And when Abraham said ( unto his Lord ) : My lord! Show me how Thou givest life to the dead, He said : Dost thou not believe? Abraham said : Yea, but ( I ask ) in order that my heart may be at ease. ( His Lord ) said : Take four of the birds and cause them to incline unto thee, then place a part of them on each hill, then call them, they will come to thee in haste. And know that Allah is Mighty, Wise.<?php break;}
case 261:{?>The likeness of those who spend their wealth in Allah ' s way is as the likeness of a grain which groweth seven ears, in every ear a hundred grains. Allah giveth increase manifold to whom He will. Allah is All Embracing, All Knowing.<?php break;}
case 262:{?>Those who spend their wealth for the cause of Allah and afterward make not reproach and injury to follow that which they have spent; their reward is with their Lord, and there shall no fear come upon them, neither shall they grieve.<?php break;}
case 263:{?>A kind word with forgiveness is better than alms giving followed by injury. Allah is Absolute, Clement.<?php break;}
case 264:{?>O ye who believe! Render not vain your alms giving by reproach and injury, like him who spendeth his wealth only to be seen of men and believeth not in Allah and the Last Day. His likeness is as the likeness of a rock whereon is dust of earth; a rainstorm smiteth it, leaving it smooth and bare. They have no control of aught of that which they have gained. Allah guideth not the disbelieving folk.<?php break;}
case 265:{?>And the likeness of those who spend their wealth in search of Allah ' s pleasure, and for the strengthening of their souls, is as the likeness of a garden on a height. The rainstorm smiteth it and it bringeth forth its fruit twofold. And if the rainstorm smite it not, then the shower. Allah is Seer of what ye do.<?php break;}
case 266:{?>Would any of you like to have a garden of palm trees and vines, with rivers flowing underneath it, with all kinds of fruit for him therein; and old age hath stricken him and be hath feeble off spring; and a fiery whirlwind striketh it and it is ( all ) consumed by fire. Thus Allah maketh plain His revelations unto you, in order that ye may give thought.<?php break;}
case 267:{?>O ye who believe! Spend of the good things which ye have earned, and of that which we bring forth from the earth for you, and seek not the bad ( with intent ) to spend thereof ( in charity ) when ye would not take it for yourselves save with disdain; and know that Allah is Absolute, Owner of Praise.<?php break;}
case 268:{?>The devil promiseth you destitution and enjoineth on you lewdness. But Allah promiseth you forgiveness from Himself with bounty. Allah is All Embracing, All Knowing.<?php break;}
case 269:{?>He giveth wisdom unto whom He will, and he unto whom wisdom is given, he truly hath received abundant good But none remember except men of understanding.<?php break;}
case 270:{?>Whatever alms ye spend or vow ye vow, Lo! Allah knoweth it, Wrong doers have no helpers.<?php break;}
case 271:{?>If ye publish your alms giving, it is well, but if ye hide it and give it to the poor, it will be better for you, and will atone for some of your ill deeds. Allah is Informed of what ye do.<?php break;}
case 272:{?>The guiding of them is not thy duty ( O Muhammad ), but Allah guideth whom He will. And whatsoever good thing ye spend, it is for yourselves, when ye spend not save in search of Allah ' s countenance; and whatsoever good thing ye spend, it will be repaid to you in full, and ye will not be wronged.<?php break;}
case 273:{?>( Alms are ) for the poor who are straitened for the cause of Allah, who cannot travel in the land ( for trade ). The unthinking man accounteth them wealthy because of their restraint. Thou shalt know them by their mark : They do not beg of men with importunity. And whatsoever good thing ye spend, lo! Allah knoweth it.<?php break;}
case 274:{?>Those who spend their wealth by night and day, by stealth and openly, verily their reward is with their Lord, and there shall no fear come upon them neither shall they grieve.<?php break;}
case 275:{?>Those who swallow usury cannot rise up save as he ariseth whom the devil hath prostrated by ( his ) touch. That is because they say : Trade is just like usury; whereas Allah permitteth trading and forbiddeth usury. He unto whom an admonition from his Lord cometh, and ( he ) refraineth ( in obedience thereto ), he shall keep ( the profits of ) that which is past, and his affair ( henceforth ) is with Allah. As for him who returneth ( to usury ) Such are rightful owners of the Fire. They will abide therein.<?php break;}
case 276:{?>Allah hath blighted usury and made alms giving fruitful. Allah loveth not the impious and guilty.<?php break;}
case 277:{?>Lo! those who believe and do good works and establish worship and pay the poor due, their reward is with their Lord and there shall no fear come upon them neither shall they grieve.<?php break;}
case 278:{?>O ye who believe! Observe your duty to Allah, and give up what remaineth ( due to you ) from usury, if ye are ( in truth ) believers.<?php break;}
case 279:{?>And if ye do not, then be warned of war ( against you ) from Allah and His messenger. And if ye repent, then ye have your principal ( without interest ). Wrong not, and ye shall not be wronged,<?php break;}
case 280:{?>And if the debtor is in straitened circumstances, then ( let there be ) postponement to ( the time of ) ease; and that ye remit the debt as alms giving would be better for you if ye did but know.<?php break;}
case 281:{?>And guard yourselves against a day in which ye will be brought back to Allah. Then every soul will be paid in full that which it hath earned, and they will not be wronged.<?php break;}
case 282:{?>O ye who believe! When ye contract a debt for a fixed term, record it in writing. Let a scribe record it in writing between you in ( terms of ) equity. No scribe should refuse to write as Allah hath taught him, so let him write, and let him who incurreth the debt dictate, and let him observe his duty to Allah his Lord, and diminish naught thereof. But if he who oweth the debt is of low understanding, or weak, or unable himself to dictate, then let the guardian of his interests dictate in ( terms of ) equity. And call to witness, from among your men, two witnesses. And if two men be not ( at hand ) then a man and two women, of such as ye approve as witnesses, so that if the one erreth ( through forgetfulness ) the other will remember. And the witnesses must not refuse when they are summoned. Be not averse to writing down ( the contract ) whether it be small or great, with ( record of ) the term thereof. That is more equitable in the sight of Allah and more sure for testimony, and the best way of avoiding doubt between you; save only in the case when it is actual merchandise which ye transfer among yourselves from hand to hand. In that case it is no sin for you if ye write it not. And have witnesses when ye sell one to another, and let no harm be done to scribe or witness. If ye do ( harm to them ) lo! it is a sin in you. Observe your duty to Allah. Allah is teaching you. And Allah is Knower of all things.<?php break;}
case 283:{?>If ye be on a journey and cannot find a scribe, then a pledge in hand ( shall suffice ). And if one of you entrusteth to another let him who is trusted deliver up that which is entrusted to him ( according to the pact between them ) and let him observe his duty to Allah. Hide not testimony. He who hideth it, verily his heart is sinful. Allah is Aware of what ye do.<?php break;}
case 284:{?>Unto Allah ( belongeth ) whatsoever is in the heavens and whatsoever is in the earth; and whether ye make known what is in your minds or hide it, Allah will bring you to account for it. He will forgive whom He will and He will punish whom He will. Allah is Able to do all things.<?php break;}
case 285:{?>The messenger believeth in that which hath been revealed unto him from his Lord and ( so do ) the believers. Each one believeth in Allah and His angels and His scriptures and His messengers We make no distinction between any of His messengers and they say : We hear, and we obey. ( Grant us ) Thy forgiveness, our Lord. Unto Thee is the journeying.<?php break;}
case 286:{?>Allah tasketh not a soul beyond its scope. For it ( is only ) that which it hath earned, and against it ( only ) that which it hath deserved. Our Lord! Condemn us not if we forget, or miss the mark! Our Lord! Lay not on us such a burden as Thou didst lay on those before us! Our Lord! Impose not on us that which we have not the strength to bear! Pardon us, absolve us and have mercy on us, Thou, our Protector, and give us victory over the disbelieving folk.<?php break;}
}?>