<?php 
switch($verse){
case 1:{?>Alif. Lam. Mim.<?php break;}
case 2:{?>Allah! There is no God save Him, the Alive, the Eternal.<?php break;}
case 3:{?>He hath revealed unto thee ( Muhammad ) the Scripture with truth, confirming that which was ( revealed ) before it, even as He revealed the Torah and the Gospel<?php break;}
case 4:{?>Aforetime, for a guidance to mankind; and hath revealed the Criterion ( of right and wrong ). Lo! those who disbelieve the revelations of Allah, theirs will be a heavy doom. Allah is Mighty, Able to Requite ( the wrong ).<?php break;}
case 5:{?>Lo! nothing in the earth or in the heavens is hidden from Allah.<?php break;}
case 6:{?>He it is who fashioneth you in the wombs as pleaseth Him. There is no God save Him, the Almighty, the Wise.<?php break;}
case 7:{?>He it is Who hath revealed unto thee ( Muhammad ) the Scripture wherein are clear revelations. They are the substance of the Book. and others ( which are ) allegorical. But those in whose hearts is doubt pursue, forsooth, that which is allegorical seeking ( to cause ) dissension by seeking to explain it. None knoweth its explanation save Allah. And those who are of sound instruction say : We believe therein; the whole is from our Lord; but only men of understanding really heed.<?php break;}
case 8:{?>Our Lord! Cause not our hearts to stray after Thou hast guided us, and bestow upon us mercy from Thy Presence. Lo! Thou, only Thou art the Bestower.<?php break;}
case 9:{?>Our Lord! it is Thou Who gatherest mankind together to a Day of which there is no doubt. Lo! Allah faileth not to keep the tryst.<?php break;}
case 10:{?>( On that day ) neither the riches not the progeny of those who disbelieve will aught avail them with Allah. They will be fuel for fire.<?php break;}
case 11:{?>Like Pharaoh ' s folk and those who were before them, they disbelieved Our revelations and so Allah seized them for their sins. And Allah is severe in punishment.<?php break;}
case 12:{?>Say ( O Muhammad ) unto those who disbelieve : Ye shall be overcome and gathered unto Hell, an evil resting place.<?php break;}
case 13:{?>There was a token for you in two hosts which met : one army fighting in the way of Allah, and another disbelieving, whom they saw as twice their number, clearly, with their very eyes. Thus Allah strengtheneth with His succour whom He will. Lo! herein verily is a lesson for those who have eyes.<?php break;}
case 14:{?>Beautified for mankind is love of the joys ( that come ) from women and offspring, and stored up heaps of gold and silver, and horses branded ( with their mark ), and cattle and land. That is comfort of the life of the world. Allah! With Him is a more excellent abode.<?php break;}
case 15:{?>Say : Shall I inform you of something better than that? For those who keep from evil, with their Lord, are Gardens underneath which rivers flow, and pure companions, and contentment from Allah. Allah is Seer of His bondmen,<?php break;}
case 16:{?>Those who say : Our Lord! Lo! we believe. So forgive us our sins and guard us from the punishment of Fire;<?php break;}
case 17:{?>The steadfast, and the truthful, and the obedient, those who spend ( and hoard not ), those who pray for pardon in the watches of the night.<?php break;}
case 18:{?>Allah ( Himself ) is witness that there is no God save Him. And the angels and the men of learning ( too are witness ). Maintaining His creation in justice, there is no God save Him, the Almighty, the Wise.<?php break;}
case 19:{?>Lo! religion with Allah ( is ) The Surrender ( to His will and guidance ). Those who ( formerly ) received the Scripture differed only after knowledge came unto them, through transgression among themselves. Whoso disbelieveth the revelations of Allah ( will find that ) Lo! Allah is swift at reckoning.<?php break;}
case 20:{?>And if they argue with thee, ( O Muhammad ), say : I have surrendered my purpose to Allah and ( so have ) those who follow me. And say unto those who have received the Scripture and those who read not : Have ye ( too ) surrendered? If they surrender, then truly they are rightly guided, and if they turn away, then it is thy duty only to convey the message ( unto them ). Allah is Seer of ( His ) bondmen.<?php break;}
case 21:{?>Lo! those who disbelieve the revelations of Allah, and slay the Prophets wrongfully, and slay those of mankind who enjoin equity : promise them a painful doom.<?php break;}
case 22:{?>Those are they whose works have failed in the world and the Hereafter; and they have no helpers.<?php break;}
case 23:{?>Hast thou not seen how those who have received the Scripture invoke the Scripture of Allah ( in their disputes ) that it may judge between them; then a faction of them turn away, being opposed ( to it )?<?php break;}
case 24:{?>That is because they say : The Fire will not touch us save for a certain number of days. That which they used to invent hath deceived them regarding their religion.<?php break;}
case 25:{?>How ( will it be with them ) when We have brought them all together to a Day of which there is no doubt, when every soul will be paid in full what it hath earned, and they will not be wronged.<?php break;}
case 26:{?>Say : O Allah! Owner of Sovereignty! Thou givest sovereignty unto whom Thou wilt, and Thou withdrawest sovereignty from whom Thou wilt. Thou exaltest whom Thou wilt and Thou abasest whom Thou wilt. In Thy hand is the good. Lo! Thou art Able to do all things.<?php break;}
case 27:{?>Thou causest the night to pass into the day, and Thou causest the day to pass into the night. And Thou bringest forth the living from the dead, and Thou bringest forth the dead from the living. And Thou givest sustenance to whom Thou choosest, without stint.<?php break;}
case 28:{?>Let not the believers take disbelievers for their friends in preference to believers. Whoso doeth that hath no connection with Allah unless ( it be ) that ye but guard yourselves against them, taking ( as it were ) security. Allah biddeth you beware ( only ) of Himself. Unto Allah is the journeying.<?php break;}
case 29:{?>Say, ( O Muhammad ) : Whether ye hide that which is in your breasts or reveal it, Allah knoweth it. He knoweth that which is in the heavens and that which is in the earth, and Allah is Able to do all things.<?php break;}
case 30:{?>On the day when every soul will find itself confronted with all that it hath done of good and all ' that it hath done of evil ( every soul ) will long that there might be a mighty apace of distance between it and that ( evil ). Allah biddeth you beware of Him. And Allah is full of pity for ( His ) bondmen.<?php break;}
case 31:{?>Say, ( O Muhammad, to mankind ) : If ye love Allah, follow me; Allah will love you and forgive you your sins. Allah is Forgiving, Merciful.<?php break;}
case 32:{?>Say : Obey Allah and the messenger. But if they turn away, Lo! Allah loveth not the disbelievers ( in His guidance ).<?php break;}
case 33:{?>Lo! Allah preferred Adam and Noah and the Family of Abraham and the Family of ' Imran above ( all His ) creatures.<?php break;}
case 34:{?>They were descendants one of another. Allah is Hearer, Knower.<?php break;}
case 35:{?>( Remember ) when the wife of Imran said : My Lord I have vowed unto Thee that which is in my belly as a consecrated ( offering ). Accept it from me. Lo! Thou, only Thou, art the Hearer, the Knower!<?php break;}
case 36:{?>And when she was delivered she said : My Lord! Lo! I am delivered of a female. Allah knew best of what she was delivered. the male is not as the female; and Lo! I have named her Mary, and Lo! I crave Thy protection for her and for her offspring from Satan the outcast.<?php break;}
case 37:{?>And her Lord accepted her with full acceptance and vouchsafed to her a goodly growth; and made Zachariah her guardian. Whenever Zachariah went into the sanctuary where she was, he found that she had food. He said : O Mary! Whence cometh unto thee this ( food )? She answered : It is from Allah. Allah giveth without stint to whom He will.<?php break;}
case 38:{?>Then Zachariah prayed unto his Lord and said : My Lord! Bestow upon me of Thy bounty goodly offspring. Lo! Thou an the Hearer of Prayer.<?php break;}
case 39:{?>And the angels called to him as he stood praying in the sanctuary : Allah giveth thee glad tidings of ( a son whose name is ) John, ( who cometh ) to confirm a word from Allah, lordly, chaste, a Prophet of the righteous.<?php break;}
case 40:{?>He said : My Lord! How can I have a son when age hath overtaken me already and my wife is barren? ( The angel ) answered : So ( it will be ). Allah doeth what He will.<?php break;}
case 41:{?>He said : My Lord! Appoint a token for me. ( The angel ) said : The token unto thee ( shall be ) that thou shalt not speak unto mankind three days except by signs. Remember thy Lord much, and praise ( Him ) in the early hours of night and morning.<?php break;}
case 42:{?>And when the angels said : O Mary! Lo! Allah hath chosen thee and made thee pure, and hath preferred thee above ( all ) the women of creation.<?php break;}
case 43:{?>O Mary! Be obedient to thy Lord, prostrate thyself and bow with those who bow ( in worship ).<?php break;}
case 44:{?>This is of the tidings of things hidden. We reveal it unto thee ( Mohammad ). Thou wast not present with them when they threw their pens ( to know ) which of them should be the guardian of Mary, nor wast thou present with them when they quarrelled ( thereupon ).<?php break;}
case 45:{?>( And remember ) when the angels said : O Mary! Allah giveth thee glad tidings of a word from Him, whose name is the Messiah, Jesus, son of Mary, illustrious in the world and the Hereafter, and one of those brought near ( unto Allah ).<?php break;}
case 46:{?>He will speak unto mankind in his cradle and in his manhood, and he is of the righteous.<?php break;}
case 47:{?>She said : My Lord! How can I have a child when no mortal hath touched me? He said : So ( it will be ). Allah createth what He will. if He decreeth a thing, He saith unto it only : Be! and it is.<?php break;}
case 48:{?>And He will teach him the Scripture and wisdom, and the Torah and the Gospel.<?php break;}
case 49:{?>And will make him a messenger unto the children of Israel, ( saying ) : Lo! I come unto you with a sign from your Lord. Lo! I fashion for you out of clay the likeness of a bird, and I breathe into it and it is a bird, by Allah ' s leave. I heal him who was born blind, and the leper, and I raise the dead, by Allah ' s leave. And I announce unto you what ye eat and what ye store up in your houses. Lo! herein verily is a portent for you, if ye are believers.<?php break;}
case 50:{?>And ( I come ) confirming that which was before me of the Torah, and to make lawful some of that which was forbidden unto you. I come unto you with a sign from your Lord, so keep your duty to Allah and obey me<?php break;}
case 51:{?>Lo! Allah is my Lord and your Lord, so worship Him. That is a straight path.<?php break;}
case 52:{?>But when Jesus became conscious of their disbelief, he cried : Who will be my helpers in the cause of Allah? The disciples said : We will be Allah ' s helpers. We believe in Allah, and bear thou witness that we have surrendered ( unto Him ).<?php break;}
case 53:{?>Our Lord! We believe in that which Thou hast revealed and we follow him whom Thou hast sent. Enroll us among those who witness ( to the truth ).<?php break;}
case 54:{?>And they ( the disbelievers ) schemed, and Allah schemed ( against them ) : and Allah is the best of schemers.<?php break;}
case 55:{?>( And remember ) when Allah said : O Jesus! Lo! I am gathering thee and causing thee to ascend unto Me, and am cleansing thee of those who disbelieve and am setting those who follow thee above those who disbelieve until the Day of Resurrection. Then unto Me ye will ( all ) return, and I shall judge between you as to that wherein ye used to differ.<?php break;}
case 56:{?>As for those who disbelieve I shah chastise them with a heavy chastisement in the world and the Hereafter; and they will have no helpers.<?php break;}
case 57:{?>And as for those who believe and do good works, He will pay them their wages in full. Allah loveth not wrongdoers.<?php break;}
case 58:{?>This ( which ) We recite unto thee is a revelation and a wise reminder.<?php break;}
case 59:{?>Lo! the likeness of Jesus with Allah is as the likeness of Adam. He created him of dust, then He said unto him : Be! and he is.<?php break;}
case 60:{?>( This is ) the truth from thy Lord ( O Muhammad ), so be not thou of those who waver.<?php break;}
case 61:{?>And whoso disputeth with thee concerning him, after the knowledge which hath come unto thee, say ( unto him ) : Come! We will summon our sons and your sons, and our women and your women, and ourselves and yourselves, then we will pray humbly ( to our Lord ) and ( solemnly ) invoke the curse of Allah upon those who lie.<?php break;}
case 62:{?>Lo! This verily is the true narrative. There is no God save Allah, and lo! Allah is the Mighty,, the Wise.<?php break;}
case 63:{?>And if they turn away, then Lo! Allah is Aware of ( who are ) the corrupters.<?php break;}
case 64:{?>Say : O People of the Scripture. Come to an agreement between us and you : that we shall worship none but Allah, and that we shall ascribe no partners unto Him, and that none of us shall take others for lords beside Allah. And if they turn away, then say : Bear witness that we are they who have surrendered ( unto Him ).<?php break;}
case 65:{?>O People of the Scripture! Why will ye argue about Abraham, when the Torah and the Gospel were not revealed till after him? Have ye then no sense?<?php break;}
case 66:{?>Lo! ye are those who argue about that whereof ye have some knowledge : Why then argue ye concerning that whereof ye have no knowledge? Allah knoweth. Ye know not.<?php break;}
case 67:{?>Abraham was not a Jew, nor yet a Christian; but he was an upright man who had surrendered ( to Allah ), and he was not of the idolaters.<?php break;}
case 68:{?>Lo! those of mankind who have the best claim to Abraham are those who followed him, and this Prophet and those who believe ( with him ); and Allah is the Protecting Friend of the believers.<?php break;}
case 69:{?>A party of the people of the Scripture long to make you go astray; and they make none to go astray except themselves, but they perceive not.<?php break;}
case 70:{?>O People of the Scripture! Why disbelieve ye in the revelations of Allah, when ye ( yourselves ) bear witness ( to theft truth )?<?php break;}
case 71:{?>O People of the Scripture! Why confound ye truth with falsehood and knowingly conceal the troth?<?php break;}
case 72:{?>And a party of the People of the Scripture say : Believe in that which hath been revealed, unto those who believe at the opening of the day, and disbelieve at the end thereof, in order that they may return;<?php break;}
case 73:{?>And believe not save in one who followeth your religion. Say ( O Muhammad ) : Lo! the guidance is Allah ' s guidance. that any one is given the like of that which was given unto you or that they may argue with you in the presence of their Lord. Say ( O Muhammad ) : Lo! the bounty is in Allah ' s hand. He bestoweth it on whom He will. Allah is All Embracing, All Knowing.<?php break;}
case 74:{?>He selecteth for His mercy whom He will. Allah is of infinite bounty.<?php break;}
case 75:{?>Among the People of the Scripture there is he who, if thou trust him with a weight of treasure, will return it to thee. And among them there is he who, if thou trust him with a piece of gold, will not return it to thee unless thou keep standing over him. That is because they say : We have no duty to the Gentiles. They speak a lie concerning Allah knowingly.<?php break;}
case 76:{?>Nay, but ( the chosen of Allah is ) he who fulfilleth his pledge and wardeth off ( evil ); for lot Allah loveth those who ward off ( evil ).<?php break;}
case 77:{?>Lo! those who purchase a small gain at the cost of Allah ' s covenant and their oaths, they have no portion in the Hereafter. Allah will neither speak to them nor look upon them on the Day of Resurrection, nor will He make them grow. Theirs will be a painful doom.<?php break;}
case 78:{?>And Lo! there is a party of them who distort the Scripture with their tongues, that ye may think that what they say is from the Scripture, when it is not from the Scripture. And they say : It is from Allah, when it is not from Allah; and they speak a lie concerning Allah knowingly.<?php break;}
case 79:{?>It is not ( possible ) for any human being unto whom Allah had given the Scripture and wisdom and the Prophethood that he should afterwards have said unto mankind : Be slaves of me instead of Allah; but ( what he said was ) : Be ye faithful servants of the Lord by virtue of your constant teaching of the Scripture and of your constant study thereof.<?php break;}
case 80:{?>And he commanded you not that ye should take the angels and the Prophets for lords. Would he command you to disbelieve after ye had surrendered ( to Allah )?<?php break;}
case 81:{?>When Allah made ( His ) covenant with the Prophets, ( He said ) : Behold that which I have given you of the Scripture and knowledge. And afterward there will come unto you a messenger, confirming that which ye possess. Ye shall believe in him and ye shah help him. He said : Do ye agree, and will ye take up My burden ( which I lay upon you ) in this ( matter )? They answered : We agree. He said : Then bear ye witness. I will be a witness with you.<?php break;}
case 82:{?>Then whosoever after this shall turn away : they will be miscreants.<?php break;}
case 83:{?>Seek they other than the religion of Allah, when unto Him submitteth whosoever is in the heavens and the earth, willingly, or unwillingly, and unto Him they will be returned.<?php break;}
case 84:{?>Say ( O Muhammad ) : We believe in Allah and that which is revealed unto us and that which was revealed unto Abraham and Ishmael and Isaac and Jacob and the tribes, and that which was vouchsafed unto Moses and Jesus and the Prophets from their Lord. We make no distinction between any of them, and unto Him we have surrendered.<?php break;}
case 85:{?>And whoso seeketh as religion other than the Surrender ( to Allah ) it will not be accepted from him, and he will be a loser in the Hereafter.<?php break;}
case 86:{?>How shall Allah guide a people who disbelieved after their belief and ( after ) they bore witness that the messenger is true and after clear proofs ( of Allah ' s sovereignty ) had come unto them. And Allah guideth not wrongdoing folk.<?php break;}
case 87:{?>As for such, their guerdon is that on them rests the curse of Allah and of angels and of men combined.<?php break;}
case 88:{?>They will abide therein. Their doom will not be lightened, neither will they be reprieved;<?php break;}
case 89:{?>Save those who afterward repent and do right. Lo! Allah is Forgiving, Merciful.<?php break;}
case 90:{?>Lo! those who disbelieve after their ( profession of ) belief, and afterward grow violent in disbelief : their repentance will not be accepted. And such are those who are astray.<?php break;}
case 91:{?>Lo! those who disbelieve, and die in disbelief, the ( whole ) earth full of gold would not be accepted from such an one if it were offered as a ransom ( for his soul ). Theirs will be a painful doom and they will have no helpers.<?php break;}
case 92:{?>Ye will not attain unto piety until ye spend of that which ye love. And whatsoever ye spend, Allah is aware thereof.<?php break;}
case 93:{?>All food was lawful unto the children of Israel, save that which Israel forbade himself, ( in days ) before the Torah was revealed. Say : Produce the Torah and read it ( unto us ) if ye are truthful.<?php break;}
case 94:{?>And whoever shall invent a falsehood after that concerning Allah, such will be wrong doers.<?php break;}
case 95:{?>Say : Allah speaketh truth. So follow the religion of Abraham, the upright. He was not of the idolaters.<?php break;}
case 96:{?>Lo! the first Sanctuary appointed for mankind was that at Mecca, a blessed place, a guidance to the peoples;<?php break;}
case 97:{?>Wherein are plain memorials ( of Allah ' s guidance ); the place where Abraham stood up to pray; and whosoever entereth it is safe. And pilgrimage to the House is a duty unto Allah for mankind, for him who can find a way thither. As for him who disbelieveth, ( let him know that ) Lo! Allah is Independent of ( all ) creatures.<?php break;}
case 98:{?>Say : O People of the Scripture! Why disbelieve ye in the revelations of Allah, when Allah ( Himself ) is Witness of what ye do?<?php break;}
case 99:{?>Say : O People of the Scripture! Why drive ye hack believers from the way of Allah, seeking to make it crooked, when ye are witnesses ( to Allah ' s guidance )? Allah is not unaware of what ye do.<?php break;}
case 100:{?>O ye who believe! If ye obey a party of those who have received the Scripture they will make you disbelievers after your belief.<?php break;}
case 101:{?>How can ye disbelieve, when Allah ' s revelations are recited unto you, and His messenger is in your midst? He who holdeth fast to Allah, he indeed is guided unto a right path.<?php break;}
case 102:{?>O ye who believe! Observe your duty to Allah with right observance, and die not save as those who have surrendered ( unto Him );<?php break;}
case 103:{?>And hold fast, all of you together, to the cable of Allah, and do not separate. And remember Allah ' s favor unto you : how ye were enemies and He made friendship between your hearts so that ye became as brothers by His grace; and ( how ) ye were upon the brink of an abyss of fire, and He did save you from it. Thus Allah maketh clear His revelations unto you, that haply ye may be guided,<?php break;}
case 104:{?>And there may spring from you a nation who invite to goodness, and enjoin right conduct and forbid indecency. Such are they who are successful.<?php break;}
case 105:{?>And be ye not as those who separated and disputed after the clear proofs had come unto them. For such there is an awful doom,<?php break;}
case 106:{?>On the day when ( some ) faces will be whitened and ( some ) faces will be blackened; and as for those whose faces have been blackened, it will be said unto them : Disbelieved ye after your ( profession of ) belief? Then taste the punishment for that ye disbelieved.<?php break;}
case 107:{?>As for those whose faces have been whitened, Lo! in the mercy of Allah they dwell for ever.<?php break;}
case 108:{?>These are revelations of Allah. We recite them unto thee in truth. Allah willeth no injustice to ( His ) creatures.<?php break;}
case 109:{?>Unto Allah belongeth whatsoever is in the heavens and whatsoever is in the earth; and unto Allah all things are returned.<?php break;}
case 110:{?>Ye are the best community that hath been raised up for mankind. Ye enjoin right conduct and forbid indecency; and ye believe in Allah. And if the People of the Scripture had believed it had been better for them. Some of them are believers; but most of them are evil livers.<?php break;}
case 111:{?>They will not harm you save a trifling hurt, and if they fight against you they will turn and flee. And afterward they will not be helped.<?php break;}
case 112:{?>Ignominy shall be theft portion wheresoever they are found save ( where they grasp ) a rope from Allah and a rope from men. They have incurred anger from their Lord, and wretchedness is laid upon them. That is because they used to disbelieve the revelations of Allah, and slew the Prophets wrongfully. That is because they were rebellious and used to transgress.<?php break;}
case 113:{?>They are not all alike. Of the People of the Scripture there is a staunch community who recite the revelations of Allah in the night season, falling prostrate ( before Him ).<?php break;}
case 114:{?>They believe in Allah and the Last Day, and enjoin right conduct and forbid indecency, and vie one with another in good works. They are of the righteous.<?php break;}
case 115:{?>And whatever good they do, they will not be denied the meed thereof. Allah is Aware of those who ward off ( evil ).<?php break;}
case 116:{?>Lo! the riches and the progeny of those who disbelieve will not avail them aught against Allah; and such are rightful owners of the Fire. They will abide therein.<?php break;}
case 117:{?>The likeness of that which they spend in this life of the world is as the likeness of a biting, icy wind which smiteth the harvest of a people who have wronged themselves, and devastateth it. Allah wronged them not, but they did wrong themselves.<?php break;}
case 118:{?>O ye who believe! Take not for intimates others than your own folk, who would spare no pains to ruin you; they love to hamper you. Hatred is revealed by ( the utterance of ) their mouths, but that which their breasts hide is greater. We have made plain for you the revelations if ye will understand.<?php break;}
case 119:{?>O ye are those who love them though they love you not, and ye believe in all the Scripture. When they fall in with you they say : We believe; but when they go apart they bite their finger tips at you, for rage. Say : Perish in your rage! Lo! Allah is Aware of what is hidden in ( your ) breasts.<?php break;}
case 120:{?>If a lucky chance befall you, it is evil unto them, and if disaster strike you they rejoice thereat. But if ye persevere and keep from evil their guile will never harm you. Lo! Allah is Surrounding what they do.<?php break;}
case 121:{?>And remember when thou settedst forth at daybreak from thy housefolk to assign to the believers their positions for the battle, Allah was Hearer, Knower.<?php break;}
case 122:{?>When two parties of you almost fell away, and Allah was their Protecting Friend. In Allah do believers put their trust.<?php break;}
case 123:{?>Allah had already given you the victory at Badr, when ye were contemptible. So observe your duty to Allah in order that ye may be thankful.<?php break;}
case 124:{?>And when thou didst say unto the believers : Is it not sufficient for you that your Lord should support you with three thousand angels sent down ( to your help )?<?php break;}
case 125:{?>Nay, but if ye persevere, and keep from evil, and ( the enemy ) attack you suddenly, your Lord will help you with five thousand angels sweeping on.<?php break;}
case 126:{?>Allah ordained this only as a message of good cheer for you, and that thereby your hearts might be at rest. Victory cometh only from Allah, the Mighty, the Wise<?php break;}
case 127:{?>That He may cut off a part of those who disbelieve, or overwhelm them so that they retire, frustrated.<?php break;}
case 128:{?>It is no concern at all of thee ( Muhammad ) whether He relent toward them or punish them; for they are evil doers.<?php break;}
case 129:{?>Unto Allah belongeth whatsoever is in the heavens and whatsoever is in the earth. He forgiveth whom He will, and punisheth whom He will. Allah is Forgiving, Merciful.<?php break;}
case 130:{?>O ye who believe! Devour not usury, doubling and quadrupling ( the sum lent ). Observe your duty to Allah, that ye may be successful.<?php break;}
case 131:{?>And ward off ( from yourselves ) the Fire prepared for disbelievers.<?php break;}
case 132:{?>And obey Allah and the messenger, that ye may find mercy.<?php break;}
case 133:{?>And vie one with another for forgiveness from your Lord, and for a Paradise as wide as are the heavens and the earth, prepared for those who ward off ( evil );<?php break;}
case 134:{?>Those who spend ( of that which Allah hath given them ) in ease and in adversity, those who control their wrath and are forgiving toward mankind; Allah loveth the good;<?php break;}
case 135:{?>And those who, when they do an evil thing or wrong themselves, remember Allah and implore forgiveness for their sins. Who forgiveth sins save Allah only?. and will not knowingly repeat ( the wrong ) they did.<?php break;}
case 136:{?>The reward of such will be forgiveness from their Lord, and Gardens underneath which rivers flow, wherein they will abide for ever, a bountiful reward for workers!<?php break;}
case 137:{?>Systems have passed away before you. Do but travel in the land and see the nature of the consequence for those who did deny ( the messengers ).<?php break;}
case 138:{?>This is a declaration for mankind, a guidance and an admonition unto those who ward off ( evil ).<?php break;}
case 139:{?>Faint not nor grieve, for ye will overcome them if ye are ( indeed ) believers.<?php break;}
case 140:{?>If ye have received a blow, the ( disbelieving ) people have received a blow the like thereof : These are ( only ) the vicissitudes which We cause to follow one another for mankind, to the end that Allah may know those who believe and may choose witnesses from among you; and Allah loveth not wrong doers.<?php break;}
case 141:{?>And that Allah may prove those who believe, and may blight the disbelievers.<?php break;}
case 142:{?>Or deemed ye that ye would enter Paradise while yet Allah knoweth not those of you who really strive, nor knoweth those ( of you ) who are steadfast?<?php break;}
case 143:{?>And verily ye used to wish for death before ye met it ( in the field ). Now ye have seen it with your eyes!<?php break;}
case 144:{?>Muhammad is but a messenger, messengers ( the like of whom ) have passed away before him. Will it be that, when he dieth or is slain, ye will turn back on your heels? He who turneth back doth no hurt to Allah, and Allah will reward the thankful.<?php break;}
case 145:{?>No soul can ever die except by Allah ' s leave and at a term appointed. Whoso desireth the reward of the world, We bestow on him thereof; and whoso desireth the reward of the Hereafter, thankful. We bestow on him thereof. We shall reward the<?php break;}
case 146:{?>And with how many a prophet have there been a number of devoted men who fought ( beside him ). They quailed not for aught that befell them in the way of Allah, nor did they weaken, nor were they brought low. Allah loveth the steadfast.<?php break;}
case 147:{?>Their cry was only that they said : Our Lord! Forgive us for our sins and wasted efforts, make our foothold sure, and give us victory over the disbelieving folk.<?php break;}
case 148:{?>So Allah gave them the reward of the world and the good reward of the Hereafter. Allah loveth those whose deeds are good.<?php break;}
case 149:{?>O ye who believe! If ye obey those who disbelieve, they will make you turn back on your heels, and ye turn back as losers.<?php break;}
case 150:{?>But Allah is your Protector, and He is the best of helpers.<?php break;}
case 151:{?>We shall cast terror into the hearts of those who disbelieve because they ascribe unto Allah partners, for which no warrant hath been revealed. Their habitation is the Fire, and hapless the abode of the wrong doers.<?php break;}
case 152:{?>Allah verily made good His promise unto you when ye routed them by His leave, until ( the moment ) when your courage failed you, and ye disagreed about the order and ye disobeyed, after He had shown you that for which ye long. Some of you desired the world, and some of you desired the Hereafter. Therefore He made you flee from them, that He might try you. Yet now He hath forgiven you. Allah is a Lord of Kindness to believers.<?php break;}
case 153:{?>When ye climbed ( the hill ) and paid no heed to anyone, while the messenger, in your rear, was calling you ( to fight ). Therefor He rewarded you grief for ( his ) grief, that ( He might teach ) you not to sorrow either for that which ye missed or for that which befell you. Allah is Informed of what ye do.<?php break;}
case 154:{?>Then, after grief, He sent clown security for you. As slumber did it overcome a party of you, while ( the other ) party, who were anxious on their own account, thought wrongly of Allah, the thought of ignorance. They said : Have we any part in the cause? Say ( O Muhammad ) : The cause belongeth wholly to Allah. They hide within themselves ( a thought ) which they reveal not unto thee, saying : Had we had any part in the cause we should not have been slain here. Say : Even though ye had been in your houses, those appointed to be slain would have gone forth to the places where they were to lie. ( All this hath been ) in order that Allah might try what is in your breasts and prove what is in your hearts. Allah is Aware of what is hidden in the breasts ( of men ).<?php break;}
case 155:{?>Lo! those of you who turned back on the day when the two hosts met, Satan alone it was who caused them to backslide, because of some of that which they have earned. Now Allah hath forgiven them. Lo! Allah is Forgiving. Clement.<?php break;}
case 156:{?>O ye who believe! Be not as those who disbelieved and said of their brethren who went abroad in the land or were fighting in the field : If they had been ( here ) with us they would not have died or been killed; that Allah may make it anguish in their hearts. Allah giveth life and causeth death; and Allah is Seer of what ye do.<?php break;}
case 157:{?>And what though ye be slain in Allah ' s way or die therein? Surely pardon from Allah and mercy are better than all that they amass.<?php break;}
case 158:{?>What though ye be slain or die, when unto Allah ye are gathered?<?php break;}
case 159:{?>It was by the mercy of Allah that thou wast lenient with them ( O Muhammad ), for if thou hadst been stern and fierce of heart they would have dispersed from round about thee. So pardon them and ask forgiveness for them and consult with them upon the conduct of affairs. And when thou art resolved, then put thy trust in Allah. Lo! Allah loveth those who put their trust ( in Him ).<?php break;}
case 160:{?>If Allah is your helper none can overcome you, and if He withdraw His help from you, who is there who can help you? In Allah let believers put their trust.<?php break;}
case 161:{?>It is not for any Prophet to deceive ( mankind ). Whoso deceiveth will bring his deceit with him on the Day of Resurrection. Then every soul will be paid in full what it hath earned; and they will not be wronged.<?php break;}
case 162:{?>Is one who followeth the pleasure of Allah as one who hath earned condemnation from Allah, whose habitation is the Fire, a hapless journey ' s end?<?php break;}
case 163:{?>There are degrees ( of grace and reprobation ) with Allah, and Allah is Seer of what ye do.<?php break;}
case 164:{?>Allah verily hath shown grace to the believers by sending unto them a messenger of their own who reciteth unto them His revelations, and causeth them to grow, and teacheth them the Scripture and wisdom; although before ( he came to them ) they were in flagrant error.<?php break;}
case 165:{?>And was it so, when a disaster smote you, though ye had smitten ( them with a disaster ) twice ( as great ), that ye said : How is this? Say ( unto them, O Muhammad ) : It is from yourselves. Lo! Allah is Able to do all things.<?php break;}
case 166:{?>That which befell you, on the day when the two armies met, was by permission of Allah; that He might know the true believers;<?php break;}
case 167:{?>And that He might know the hypocrites, unto whom it was said : Come, fight in the way of Allah, or defend yourselves. They answered : If we knew aught of fighting we would follow you. On that day they were nearer disbelief than faith. They utter with their mouths a thing which is not in their hearts. Allah is best aware of what they hide.<?php break;}
case 168:{?>Those who, while they sat at home, said of their brethren ( who were fighting for the cause of Allah ) : If they had been guided by us they would not have been slain. Say ( unto them, O Muhammad ) : Then avert death from yourselves if ye are truthful.<?php break;}
case 169:{?>Think not of those, who are slain in the way of Allah, as dead. Nay, they are living. With their Lord they have provision.<?php break;}
case 170:{?>Jubilant ( are they ) because of that which Allah hath bestowed upon them of His bounty, rejoicing for the sake of those who have not joined them but are left behind : that there shall no fear come upon them neither shall they grieve.<?php break;}
case 171:{?>They rejoice because of favor from Allah and kindness, and that Allah wasteth not the wage of the believers.<?php break;}
case 172:{?>As for those who heard the call of Allah and His messenger after the harm befell them ( in the fight ); for such of them as do right and ward off ( evil ), there is great reward,<?php break;}
case 173:{?>Those unto whom men said : Lo! the people have gathered against you, therefor fear them. ( The threat of danger ) but increased the faith of them and they cried : Allah is sufficient for us! Most Excellent is He in Whom we trust!<?php break;}
case 174:{?>So they returned with grace and favor from Allah, and no harm touched them. They followed the good pleasure of Allah, and Allah is of infinite bounty.<?php break;}
case 175:{?>It is only the devil who would make ( men ) fear his partisans. Fear them not; fear Me, if ye are true believers.<?php break;}
case 176:{?>Let not their conduct grieve thee, who run easily to disbelief, for Lo! they injure Allah not at all. It is Allah ' s will to assign them no portion in the Hereafter, and theirs will be an awful doom.<?php break;}
case 177:{?>Those who purchase disbelief at the price of faith harm Allah not at all, but theirs will be a painful doom.<?php break;}
case 178:{?>And let not those who disbelieve imagine that the rein We give them bodeth good unto their souls. We only give them rein that they may grow in sinfulness. And theirs will be a shameful doom.<?php break;}
case 179:{?>It is not ( the purpose ) of Allah to leave you in your present state till He shall separate the wicked from the good. And it is not ( the purpose of ) Allah to let you know the unseen. But Allah chooseth of His messengers whom He will, ( to receive knowledge thereof. ) So believe in Allah and His messengers. If ye believe and ward off ( evil ), yours will be a vast reward.<?php break;}
case 180:{?>And let not those who hoard up that which Allah hath bestowed upon them of His bounty think that it is better for them. Nay, it is worse for them. That which they hoard will be their collar on the Day of Resurrection. Allah ' s is the heritage of the heavens and the earth, and Allah is Informed of what ye do.<?php break;}
case 181:{?>Verily Allah heard the saying of those who said, ( when asked for contributions to the war ) : "Allah, forsooth, is poor, and we are rich! We shall record their saying with their slaying of the Prophets wrongfully and We shall say : Taste ye the punishment of burning!<?php break;}
case 182:{?>This is on account of that which your own hands have sent before ( you to the judgment ). Allah is no oppressor of ( His ) bondmen.<?php break;}
case 183:{?>( The same are ) those who say : Lo! Allah hath charged us that we believe not in any messenger until he bring us an offering which fire ( from heaven ) shall devour. Say ( unto them, O Muhammad ) : Messengers came unto you before me with miracles, and with that ( very miracle ) which ye describe. Why then did ye slay them? ( Answer that ) if ye are truthful<?php break;}
case 184:{?>And if they deny thee, even so did they deny messengers who were before thee, who came with miracles and with the Psalms and with the Scripture giving light.<?php break;}
case 185:{?>Every soul will taste of death. And ye will be paid on the Day of Resurrection only that which ye have fairly earned. Whoso is removed from the Fire and is made to enter Paradise, he indeed is triumphant. The life of this world is but comfort of illusion.<?php break;}
case 186:{?>Assuredly ye will be tried in your property and in your persons, and ye will hear much wrong from those who were given the Scripture before you, and from the idolaters. But if ye persevere and ward off ( evil ), then that is of the steadfast heart of things.<?php break;}
case 187:{?>And ( remember ) when Allah laid a charge on those who had received the Scripture ( He said ) : Ye are to expound it to mankind and not to hide it. But they flung it behind their backs and bought thereby a little gain. Verily evil is that which they have gained thereby.<?php break;}
case 188:{?>Think not that those who exult in what they have given, and love to be praised for what they have not done Think not, they are in safety from the doom. A painful doom is theirs.<?php break;}
case 189:{?>Unto Allah belongeth the Sovereignty of the heavens and the earth. Allah is Able to do all things.<?php break;}
case 190:{?>Lo! In the creation of the heavens and the earth and ( in ) the difference of night and day are tokens ( of His sovereignty ) for men of understanding,<?php break;}
case 191:{?>Such as remember Allah, standing, sitting, and reclining, and consider the creation of the heavens and the earth, ( and say ) : Our Lord! Thou createdst not this in vain. Glory be to Thee! Preserve us from the doom of Fire<?php break;}
case 192:{?>Our Lord! Whom Thou causest to enter the Fire : him indeed Thou hast confounded. For evil doers there will be no helpers.<?php break;}
case 193:{?>Our Lord! Lo! we have heard a crier calling unto Faith : "Believe ye in your Lord!" So we believed. Our Lord! Therefor forgive us our sins, and remit from us our evil deeds, and make us die the death of the righteous.<?php break;}
case 194:{?>Our Lord! And give us that which Thou hast promised to us by Thy messengers. Confound us not upon the Day of Resurrection. Lo! Thou breakest not the tryst.<?php break;}
case 195:{?>And their Lord hath heard them ( and He saith ) : Lo! I suffer not the work of any worker, male or female, to be lost. Ye proceed one from another. So those who fled and were driven forth from their homes and suffered damage for My cause, and fought and were slain, verity I shall remit their evil deeds from them and verily I shall bring them into Gardens underneath which rivers flow. A reward from Allah. And with Allah is the fairest of rewards.<?php break;}
case 196:{?>Let not the vicissitude ( of the success ) of those who disbelieve, in the land, deceive thee ( O Muhammad ).<?php break;}
case 197:{?>It is but a brief comfort. And afterward their habitation will be hell, an ill abode.<?php break;}
case 198:{?>But those who keep their duty to their Lord, for them are Gardens underneath which rivers flow, wherein they will be safe for ever. A gift of welcome from their Lord. That which Allah hath in store is better for the righteous.<?php break;}
case 199:{?>And Lo! of the People of the Scripture there are some who believe in Allah and that which is revealed unto you and that which was revealed unto them, humbling themselves before Allah. They purchase not a trifling gain at the price of the revelations of Allah. Verily their reward is with their Lord, and Lo! Allah is swift to take account.<?php break;}
case 200:{?>O ye who believe! Endure, outdo all others in endurance, be ready, and observe your duty to Allah, in order that ye may succeed.<?php break;}
}?>