<?php 
switch($verse){
case 1:{?>O Prophet! Keep thy duty to Allah and obey not the disbelievers and the hypocrites. Lo! Allah is Knower, Wise.<?php break;}
case 2:{?>And follow that which is inspired in thee from thy Lord. Lo! Allah is Aware of what ye do.<?php break;}
case 3:{?>And put thy trust in Allah, for Allah is sufficient as Trustee.<?php break;}
case 4:{?>Allah hath not assigned unto any man two hearts within his body, nor hath he made your wives whom ye declare ( to be your mothers ) your mothers, nor hath he made those whom ye claim ( to be your sons ) your sons. This is but a saying of your mouths. But Allah sayeth the truth and He soweth the way.<?php break;}
case 5:{?>Proclaim their real parentage. That will be more equitable in the sight of Allah. And if ye know not their fathers, then ( they are ) your brethren in the faith, and your clients. And there is no sin for you in the mistakes that ye make unintentionally, but what your hearts purpose ( that will be a sin for you ). Allah is Forgiving, Merciful.<?php break;}
case 6:{?>The Prophet is closer to the believers than their selves, and his wives are ( as ) their mothers. And the owners of kinship are closer one to another in the ordinance of Allah than ( other ) believers and the fugitives ( who fled from Mecca ) except that ye should do kindness to your friends. This is written in the Book ( of nature ).<?php break;}
case 7:{?>And when We exacted a covenant from the Prophets, and from thee ( O Muhammad ) and from Noah and Abraham and Moses and Jesus son of Mary. We took from them a solemn covenant;<?php break;}
case 8:{?>That He may ask the loyal of their loyalty. And He hath prepared a painful doom for the unfaithful.<?php break;}
case 9:{?>O ye who believe Remember Allah ' s favor unto you when there came against you hosts, and We sent against them a great wind and hosts ye could not see. And Allah is ever Seer of what ye do.<?php break;}
case 10:{?>When they came upon you from above you and from below you, and when eyes grew wild and hearts reached to the throats, and ye were imagining vain thoughts concerning Allah.<?php break;}
case 11:{?>There were the believers sorely tried, and shaken with a mighty shock.<?php break;}
case 12:{?>And When the hypocrites, and those in whose hearts is a disease, were saying : Allah and His messenger promised us naught but delusion.<?php break;}
case 13:{?>And when a party of them said : O folk of Yathrib! There is no stand ( possible ) for you, therefor turn back. And certain of them ( even ) sought permission of the Prophet, saying : Our homes lie open ( to the enemy ). And they lay not open. They but wished to flee.<?php break;}
case 14:{?>If the enemy had entered from all sides and they had been exhorted to treachery, they would have committed it, and would have hesitated thereupon but little.<?php break;}
case 15:{?>And verily they had already sworn unto Allah that they would not turn their backs ( to the foe ). An oath to Allah must he answered for.<?php break;}
case 16:{?>Say : Flight will not avail you if ye flee from death or killing, and then ye dwell in comfort but a little while.<?php break;}
case 17:{?>Say : Who is he who can preserve you from Allah if He intendeth harm for you, or intendeth mercy for you. They will not find that they have any friend or helper other than Allah<?php break;}
case 18:{?>Allah already knoweth those of you who hinder, and those who say unto their brethren : "Come ye hither unto us!" and they come not to the stress of battle save a little,<?php break;}
case 19:{?>Being sparing of their help to you ( believers ). But when the fear cometh, then thou ( Muhammad ) seest them regarding thee with rolling eyes like one who fainteth unto death. Then, when the fear departeth, they scald you with sharp tongues in their greed for wealth ( from the spoil ). Such have not believed. Therefor Allah maketh their deeds fruitless. And that is easy for Allah.<?php break;}
case 20:{?>They hold that the clans have not retired ( for good ); and if the Clans should advance ( again ), they would fain be in the desert with the wandering Arabs, asking for the news of you and if they were among you, they would not give battle, save a little.<?php break;}
case 21:{?>Verily in the messenger of Allah ye have a good example for him who looketh unto Allah and the last Day, and remembereth Allah much.<?php break;}
case 22:{?>And when the true believers saw the clans, they said : This is that which Allah and His messenger promised us. Allah and His messenger are true. It did but confirm them in their faith and resignation.<?php break;}
case 23:{?>Of the believers are men who are true to that which they covenanted with Allah. Some of them have paid their vow by death ( in battle ), and some of them still are waiting; and they have not altered in the least;<?php break;}
case 24:{?>That Allah may reward the true men for their truth, and punish the hypocrites if He will, or relent toward them ( if He will ). Lo! Allah is Forgiving, Merciful.<?php break;}
case 25:{?>And Allah repulsed the disbelievers in their wrath; they gained no good. Allah averted their attack from the believers. Allah is Strong, Mighty.<?php break;}
case 26:{?>And He brought those of the People of the Scripture who supported them down from their strongholds, and cast panic into their hearts. Some ye slew, and ye made captive some.<?php break;}
case 27:{?>And He caused you to inherit their land and their houses and their wealth, and land ye have not trodden. Allah is Able to do all things.<?php break;}
case 28:{?>O Prophet! Say unto thy wives : If ye desire the world ' s life and its adornment, come! I will content you and will release you with a fair release.<?php break;}
case 29:{?>But if ye desire Allah and His messenger and the abode of the Hereafter, then lo! Allah hath prepared for the good among you an immense reward.<?php break;}
case 30:{?>O ye wives of the Prophet! Whosoever of you committeth manifest lewdness, the punishment for her will be doubled, and that is easy for Allah.<?php break;}
case 31:{?>And whosoever of you is submissive unto Allah and His messenger and doeth right, We shall give her reward twice over, and We have prepared for her a rich provision.<?php break;}
case 32:{?>O ye wives of the Prophet! Ye are not like any other women. If ye keep your duty ( to Allah ), then be not soft of speech, lest he in whose heart is a disease aspire ( to you ), but utter customary speech.<?php break;}
case 33:{?>And stay in your houses. Bedizen not yourselves with the bedizenment of the Time of ignorance. Be regular in prayer, and pay the poor due, and obey Allah and His messenger. Allah ' s wish is but to remove uncleanness far from you, O Folk of the Household, and cleanse you with a thorough cleansing.<?php break;}
case 34:{?>And bear in mind that which is recited in your houses of the revelations of Allah and wisdom. Lo! Allah is Subtile, Aware.<?php break;}
case 35:{?>Lo! men who surrender unto Allah, and women who surrender, and men who believe and women who believe, and men who obey and women who obey, and men who speak the truth and women who speak the truth, and men who persevere ( in righteousness ) and women who persevere, and men who are humble and women who are humble, and men who give alms and women who give alms, and men who fast and women who fast, and men who guard their modesty and women who guard ( their modesty ), and men who remember Allah much and women who remember Allah hath prepared for them forgiveness and a vast reward.<?php break;}
case 36:{?>And it becometh not a believing man or a believing woman, when Allah and His messenger have decided and affair ( for them ), that they should ( after that ) claim any say in their affair; and whoso is rebellious to Allah and His messenger, be verily goeth astray in error manifest.<?php break;}
case 37:{?>And when thou saidst unto him on whom Allah hath conferred favor and thou hast conferred favor : Keep thy wife to thyself, and fear Allah. And thou didst hide in thy mind that which Allah was to bring to light, and thou didst fear mankind whereas Allah had a better right that thou shouldst fear Him. So when Zeyd had performed the necessary formality ( of divorce ) from her, We gave her unto thee in marriage, so that ( henceforth ) there may be no sin for believers in respect of wives of their adopted sons, when the latter have performed the necessary formality ( of release ) from them. The commandment of Allah must be fulfilled.<?php break;}
case 38:{?>There is no reproach for the Prophet in that which Allah maketh his due. That was Allah ' s way with those who passed away of old and the commandment of Allah is certain destiny.<?php break;}
case 39:{?>Who delivered the messages of Allah and feared Him, and feared none save Allah. Allah keepeth good account.<?php break;}
case 40:{?>Muhammad is not the father of any man among you, but he is the messenger of Allah and the Seal of the Prophets; and Allah is Aware of all things.<?php break;}
case 41:{?>O ye who believe! Remember Allah with much remembrance.<?php break;}
case 42:{?>And glorify Him early and late.<?php break;}
case 43:{?>He it is who blesseth you, and His angels ( bless you ), that He may bring you forth from darkness unto light; and He is Merciful to the believers.<?php break;}
case 44:{?>Their salutation on the day when they shall meet Him will be : Peace. And He hath prepared for them a goodly recompense.<?php break;}
case 45:{?>O Prophet! Lo! We have sent thee as a witness and a bringer of good tidings and a warner<?php break;}
case 46:{?>And as a summoner unto Allah by His permission, and as a lamp that giveth light.<?php break;}
case 47:{?>And announce unto the believers the good tidings that they will have great bounty from Allah.<?php break;}
case 48:{?>And incline not to the disbelievers and the hypocrites. Disregard their noxious talk, and put thy trust in Allah. Allah is sufficient as Trustee.<?php break;}
case 49:{?>O ye who believe! If ye wed believing women and divorce them before ye have touched them, then there is no period that ye should reckon. But content them and release them handsomely.<?php break;}
case 50:{?>O Prophet! Lo! We have made lawful unto thee thy wives unto whom thou hast paid their dowries, and those whom thy right hand possesseth of those whom Allah hath given thee as spoils of war, and the daughters of thine uncle on the father ' s side and the daughters of thine aunts on the father ' s side, and the daughters of thine uncles on the mother ' s side emigrated with thee, and a believing woman if she give herself unto the Prophet and the Prophet desire to ask her in marriage, a privilege for thee only, not for the ( rest of ) believers. We are aware of that which We enjoined upon them concerning their wives and those whom their right hands possess that thou mayst be free from blame, for Allah is Forgiving, Merciful.<?php break;}
case 51:{?>Thou canst defer whom thou wilt of them and receive unto thee whom thou wilt, and whomsoever thou desirest of those whom thou hast set aside ( temporarily ), it is no sin for thee ( to receive her again ); that is better; that they may be comforted and not grieve, and may all be pleased with what thou givest them. Allah knoweth what is in your hearts ( O men ) and Allah is Forgiving, Clement.<?php break;}
case 52:{?>It is not allowed thee to take ( other ) women henceforth nor that thou shouldst change them for other wives even though their beauty pleased thee, save those whom thy right hand possesseth. And Allah is Watcher over all things.<?php break;}
case 53:{?>O ye who believe! Enter not the dwellings of the Prophet for a meal without waiting for the proper time, unless permission be granted you. But if ye are invited, enter, and, when, your meal is ended, then disperse. Linger not for conversation. Lo! that would cause annoyance to the Prophet, and he would be shy of ( asking ) you ( to go ); but Allah is not shy of the truth. And when ye ask of them ( the wives of the Prophet ) anything, ask it of them from behind a curtain. That is purer for your hearts and for their hearts. And it is not for you to cause annoyance to the messenger of Allah, nor that ye should ever marry his wives after him. Lo! that in Allah ' s sight would be an enormity.<?php break;}
case 54:{?>Whether ye divulge a thing or keep it hidden, lo! Allah is ever Knower of all things.<?php break;}
case 55:{?>It is no sin for them ( thy wives ) ( to converse freely ) with their fathers, or their sons : or their brothers, or their brothers sons, or the sons of their sisters or of their own women, or their slaves. O women! Keep your duty to Allah. Lo! Allah is Witness over all things.<?php break;}
case 56:{?>Lo! Allah and His angels shower blessings on the Prophet. O ye who believe! Ask blessings on him and salute him with a worthy salutation.<?php break;}
case 57:{?>Lo! those who malign Allah and His messenger, Allah hath cursed them in the world and the Hereafter, and hath prepared for them the doom of the disdained.<?php break;}
case 58:{?>And those who malign believing men and believing women undeservedly, they bear the guilt of slander and manifest sin.<?php break;}
case 59:{?>O Prophet! Tell thy wives and thy daughters and the women of the believers to draw their cloaks close round them ( when they go abroad ). That will be better, that so they may be recognized and not annoyed. Allah is ever Forgiving, Merciful.<?php break;}
case 60:{?>If the hypocrites, and those in whose hearts is a disease, and the alarmists in the city do not cease, We verify shall urge thee on against them, then they will be your neighbors in it but a little while.<?php break;}
case 61:{?>Accursed, they will be seized wherever found and slain with a ( fierce ) slaughter.<?php break;}
case 62:{?>That was the way of Allah in the case of those who passed away of old; thou wilt not find for the way of Allah aught of power to change.<?php break;}
case 63:{?>Men ask you of the Hour. Say : The knowledge of it is with Allah only. What can convey ( the knowledge ) unto thee? It may be that the Hour is nigh.<?php break;}
case 64:{?>Lo! Allah hath cursed the disbelievers, and hath prepared for them a flaming fire,<?php break;}
case 65:{?>Wherein they will abide for ever. They will find ( then ) no protecting friend nor helper.<?php break;}
case 66:{?>On the day when their faces are turned over in the fire, they say : Oh, would that we had obeyed Allah and had obeyed His messenger!<?php break;}
case 67:{?>And they say : Our Lord! Lo! we obeyed our princes and great men, and they misled us from the Way.<?php break;}
case 68:{?>Our Lord! Oh, give them double torment and curse them with a mighty curse.<?php break;}
case 69:{?>O ye who believe! Be not as those who slandered Moses, but Allah proved his innocence of that which they alleged, and he was well esteemed in Allah ' s sight.<?php break;}
case 70:{?>O ye who believe! Guard your duty to Allah, and speak words straight to the point;<?php break;}
case 71:{?>He will adjust your works for you and will forgive you your sins. Whosoever obeyeth Allah and His messenger, he verily hath gained a signal victory.<?php break;}
case 72:{?>Lo! We offered the trust unto the heavens and the earth and the hills, but they shrank from bearing it and were afraid of it. And man assumed it. Lo! he hath proved a tyrant and a fool.<?php break;}
case 73:{?>Allah punisheth hypocritical men and hypocritical women, and idolatrous men and idolatrous women. But Allah pardoneth believing men and believing women, and Allah is Forgiving, Merciful.<?php break;}
}?>