-- MySQL Script generated by MySQL Workbench
-- Sun Jan 22 20:55:05 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mini_picopi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mini_picopi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mini_picopi` DEFAULT CHARACTER SET utf8 ;
USE `mini_picopi` ;

-- -----------------------------------------------------
-- Table `mini_picopi`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_picopi`.`city` (
  `city_id`VARCHAR(40) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `country_id` VARCHAR(3) NULL DEFAULT NULL,
  `state_id` VARCHAR(40) NULL DEFAULT NULL,
  `type` VARCHAR(3) NULL DEFAULT NULL,
  `verify` TINYINT(1) NOT NULL DEFAULT 0,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`city_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mini_picopi`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_picopi`.`country` (
  `country_id` VARCHAR(3) NOT NULL,
  `iso_code_2` VARCHAR(2) NULL DEFAULT NULL,
  `iso_code_3` VARCHAR(3) NULL DEFAULT NULL,
  `name` VARCHAR(70) NULL DEFAULT NULL,
  `phone_code` VARCHAR(10) NULL DEFAULT NULL,
  `order` INT(11) NULL DEFAULT NULL,
  `default` TINYINT(1) NULL DEFAULT 0,
  `active` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`country_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mini_picopi`.`edu_school`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_picopi`.`edu_school` (
  `school_id` VARCHAR(40) NOT NULL,
  `school_code` VARCHAR(100) NULL DEFAULT NULL,
  `token_school` VARCHAR(32) NULL DEFAULT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `description` LONGTEXT NULL DEFAULT NULL,
  `school_type_id` VARCHAR(2) NULL DEFAULT NULL,
  `school_grade_id` ENUM('1', '2', '3', '4', '5', '6') NULL DEFAULT NULL,
  `public_private` ENUM('U', 'I') NULL DEFAULT 'U',
  `open` TINYINT(1) NULL DEFAULT 0,
  `principal` VARCHAR(100) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `language` VARCHAR(10) NULL DEFAULT 'en',
  `country_id` VARCHAR(3) NULL DEFAULT NULL,
  `state_id` VARCHAR(20) NULL DEFAULT NULL,
  `city_id` VARCHAR(20) NULL DEFAULT NULL,
  `student` INT(11) NULL DEFAULT NULL,
  `prevent_change_school` TINYINT(1) NULL DEFAULT 0,
  `prevent_resign` TINYINT(1) NULL DEFAULT 0,
  `use_token` TINYINT(1) NULL DEFAULT 0,
  `time_import_first` DATETIME NULL DEFAULT NULL,
  `time_import_last` DATETIME NULL DEFAULT NULL,
  `admin_import_first` BIGINT(20) NULL DEFAULT NULL,
  `admin_import_last` BIGINT(20) NULL DEFAULT NULL,
  `ip_import_first` VARCHAR(45) NULL DEFAULT NULL,
  `ip_import_last` VARCHAR(45) NULL DEFAULT NULL,
  `time_create` TIMESTAMP NULL DEFAULT NULL,
  `time_edit` TIMESTAMP NULL DEFAULT NULL,
  `admin_create` VARCHAR(40) NULL DEFAULT NULL,
  `admin_edit` VARCHAR(40) NULL DEFAULT NULL,
  `ip_create` VARCHAR(50) NULL DEFAULT NULL,
  `ip_edit` VARCHAR(50) NULL DEFAULT NULL,
  `active` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`school_id`),
  UNIQUE INDEX `nama` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mini_picopi`.`edu_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_picopi`.`edu_admin` (
  `admin_id` VARCHAR(40) NOT NULL,
  `school_id` VARCHAR(40) NULL DEFAULT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `gender` ENUM('M', 'W') NOT NULL DEFAULT 'M',
  `birth_place` VARCHAR(100) NULL DEFAULT NULL,
  `birth_day` DATE NULL DEFAULT NULL,
  `username` VARCHAR(50) NULL DEFAULT NULL,
  `admin_level` INT(11) NULL DEFAULT 0,
  `token_admin` VARCHAR(32) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(200) NULL DEFAULT NULL,
  `country_id` BIGINT(20) NULL DEFAULT NULL,
  `state_id` VARCHAR(40) NULL DEFAULT NULL,
  `city_id`VARCHAR(40) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `password_initial` VARCHAR(45) NULL DEFAULT NULL,
  `auth` VARCHAR(45) NULL DEFAULT NULL,
  `time_create` TIMESTAMP NULL DEFAULT NULL,
  `time_edit` TIMESTAMP NULL DEFAULT NULL,
  `time_last_activity` DATETIME NULL DEFAULT NULL,
  `admin_create` VARCHAR(40) NULL DEFAULT NULL,
  `admin_edit` VARCHAR(40) NULL DEFAULT NULL,
  `ip_create` VARCHAR(50) NULL DEFAULT NULL,
  `ip_edit` VARCHAR(50) NULL DEFAULT NULL,
  `ip_last_activity` VARCHAR(40) NULL DEFAULT NULL,
  `blocked` TINYINT(1) NULL DEFAULT 0,
  `active` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`admin_id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `admin_school_id_idx` (`school_id` ASC) VISIBLE,
  CONSTRAINT `admin_school_id`
    FOREIGN KEY (`school_id`)
    REFERENCES `mini_picopi`.`edu_school` (`school_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mini_picopi`.`edu_grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_picopi`.`edu_grade` (
  `grade_id` VARCHAR(40) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `time_create` TIMESTAMP NULL DEFAULT NULL,
  `time_edit` TIMESTAMP NULL DEFAULT NULL,
  `admin_create` VARCHAR(40) NULL DEFAULT NULL,
  `admin_edit` VARCHAR(40) NULL DEFAULT NULL,
  `ip_create` VARCHAR(50) NULL DEFAULT NULL,
  `ip_edit` VARCHAR(50) NULL DEFAULT NULL,
  `order` INT(11) NULL DEFAULT NULL,
  `default` TINYINT(1) NULL DEFAULT 0,
  `active` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`grade_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mini_picopi`.`edu_school_program`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_picopi`.`edu_school_program` (
  `school_program_id` VARCHAR(40) NOT NULL,
  `school_id` VARCHAR(40) NULL DEFAULT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `order` INT(11) NULL DEFAULT NULL,
  `default` BIGINT(20) NULL DEFAULT 0,
  `time_create` TIMESTAMP NULL DEFAULT NULL,
  `time_edit` TIMESTAMP NULL DEFAULT NULL,
  `admin_create` VARCHAR(40) NULL DEFAULT NULL,
  `admin_edit` VARCHAR(40) NULL DEFAULT NULL,
  `ip_create` VARCHAR(50) NULL DEFAULT NULL,
  `ip_edit` VARCHAR(50) NULL DEFAULT NULL,
  `active` INT(11) NULL DEFAULT 1,
  PRIMARY KEY (`school_program_id`),
  INDEX `school_program_school_id_idx` (`school_id` ASC) VISIBLE,
  CONSTRAINT `school_program_school_id`
    FOREIGN KEY (`school_id`)
    REFERENCES `mini_picopi`.`edu_school` (`school_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mini_picopi`.`edu_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_picopi`.`edu_class` (
  `class_id` VARCHAR(40) NOT NULL,
  `token_class` VARCHAR(32) NULL DEFAULT NULL,
  `school_id` VARCHAR(40) NULL DEFAULT NULL,
  `class_code` VARCHAR(20) NULL DEFAULT NULL,
  `grade_id` VARCHAR(40) NULL DEFAULT NULL,
  `school_program_id` VARCHAR(40) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `time_create` TIMESTAMP NULL DEFAULT NULL,
  `time_edit` TIMESTAMP NULL DEFAULT NULL,
  `admin_create` VARCHAR(40) NULL DEFAULT NULL,
  `admin_edit` VARCHAR(40) NULL DEFAULT NULL,
  `ip_create` VARCHAR(50) NULL DEFAULT NULL,
  `ip_edit` VARCHAR(50) NULL DEFAULT NULL,
  `order` INT(11) NULL DEFAULT NULL,
  `default` TINYINT(1) NULL DEFAULT 0,
  `active` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`class_id`),
  INDEX `class_grade_id_idx` (`grade_id` ASC) VISIBLE,
  INDEX `class_school_id_idx` (`school_id` ASC) VISIBLE,
  INDEX `class_school_program_id_idx` (`school_program_id` ASC) VISIBLE,
  CONSTRAINT `class_grade_id`
    FOREIGN KEY (`grade_id`)
    REFERENCES `mini_picopi`.`edu_grade` (`grade_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `class_school_id`
    FOREIGN KEY (`school_id`)
    REFERENCES `mini_picopi`.`edu_school` (`school_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `class_school_program_id`
    FOREIGN KEY (`school_program_id`)
    REFERENCES `mini_picopi`.`edu_school_program` (`school_program_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mini_picopi`.`edu_student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_picopi`.`edu_student` (
  `student_id` VARCHAR(40) NOT NULL,
  `token_student` VARCHAR(32) NULL DEFAULT NULL,
  `school_id` VARCHAR(40) NULL DEFAULT NULL,
  `reg_number` VARCHAR(20) NULL DEFAULT NULL,
  `reg_number_national` VARCHAR(20) NULL DEFAULT NULL,
  `grade_id` VARCHAR(40) NULL DEFAULT NULL,
  `class_id` VARCHAR(40) NULL DEFAULT NULL,
  `username` VARCHAR(100) NULL DEFAULT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `gender` ENUM('M', 'W') NULL DEFAULT 'M',
  `birth_place` VARCHAR(100) NULL DEFAULT NULL,
  `birth_day` DATE NULL DEFAULT NULL,
  `phone` VARCHAR(30) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `password_initial` VARCHAR(45) NULL DEFAULT NULL,
  `auth` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `country_id` BIGINT(20) NULL DEFAULT NULL,
  `state_id` VARCHAR(40) NULL DEFAULT NULL,
  `city_id`VARCHAR(40) NULL DEFAULT NULL,
  `religion_id` VARCHAR(2) NULL DEFAULT NULL,
  `prevent_change_school` TINYINT(1) NULL DEFAULT 0,
  `prevent_resign` TINYINT(1) NULL DEFAULT 0,
  `time_create` TIMESTAMP NULL DEFAULT NULL,
  `time_edit` TIMESTAMP NULL DEFAULT NULL,
  `admin_create` VARCHAR(40) NULL DEFAULT NULL,
  `admin_edit` VARCHAR(40) NULL DEFAULT NULL,
  `ip_create` VARCHAR(50) NULL DEFAULT NULL,
  `ip_edit` VARCHAR(50) NULL DEFAULT NULL,
  `blocked` TINYINT(1) NULL DEFAULT 0,
  `active` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`student_id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `student_class_id_idx` (`class_id` ASC) VISIBLE,
  INDEX `student_school_id_idx` (`school_id` ASC) VISIBLE,
  INDEX `student_grade_id` (`grade_id` ASC) VISIBLE,
  CONSTRAINT `student_school_id`
    FOREIGN KEY (`school_id`)
    REFERENCES `mini_picopi`.`edu_school` (`school_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `student_class_id`
    FOREIGN KEY (`class_id`)
    REFERENCES `mini_picopi`.`edu_class` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `student_grade_id`
    FOREIGN KEY (`grade_id`)
    REFERENCES `mini_picopi`.`edu_grade` (`grade_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mini_picopi`.`edu_teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_picopi`.`edu_teacher` (
  `teacher_id` VARCHAR(40) NOT NULL,
  `token_teacher` VARCHAR(32) NULL DEFAULT NULL,
  `school_id` VARCHAR(40) NULL DEFAULT NULL,
  `reg_number` VARCHAR(20) NULL DEFAULT NULL,
  `reg_number_national` VARCHAR(20) NULL DEFAULT NULL,
  `username` VARCHAR(100) NULL DEFAULT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `gender` ENUM('M', 'W') NULL DEFAULT 'M',
  `birth_place` VARCHAR(100) NULL DEFAULT NULL,
  `birth_day` DATE NULL DEFAULT NULL,
  `phone` VARCHAR(30) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `country_id` BIGINT(20) NULL DEFAULT NULL,
  `state_id` VARCHAR(40) NULL DEFAULT NULL,
  `city_id`VARCHAR(40) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `password_initial` VARCHAR(45) NULL DEFAULT NULL,
  `auth` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `religion_id` VARCHAR(2) NULL DEFAULT NULL,
  `time_create` TIMESTAMP NULL DEFAULT NULL,
  `time_edit` TIMESTAMP NULL DEFAULT NULL,
  `time_last_activity` DATETIME NULL DEFAULT NULL,
  `admin_create` VARCHAR(40) NULL DEFAULT NULL,
  `admin_edit` VARCHAR(40) NULL DEFAULT NULL,
  `ip_create` VARCHAR(50) NULL DEFAULT NULL,
  `ip_edit` VARCHAR(50) NULL DEFAULT NULL,
  `ip_last_activity` VARCHAR(40) NULL DEFAULT NULL,
  `blocked` TINYINT(1) NULL DEFAULT 0,
  `active` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`teacher_id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `teacher_school_id_idx` (`school_id` ASC) VISIBLE,
  CONSTRAINT `teacher_school_id`
    FOREIGN KEY (`school_id`)
    REFERENCES `mini_picopi`.`edu_school` (`school_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mini_picopi`.`edu_test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_picopi`.`edu_test` (
  `test_id` VARCHAR(40) NOT NULL,
  `school_id` VARCHAR(40) NULL DEFAULT NULL,
  `name` TEXT NULL DEFAULT NULL,
  `class` TEXT NULL DEFAULT NULL,
  `school_program_id` VARCHAR(40) NULL DEFAULT NULL,
  `subject` VARCHAR(255) NULL DEFAULT NULL,
  `teacher_id` VARCHAR(40) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `guidance` TEXT NULL DEFAULT NULL,
  `open` TINYINT(1) NULL DEFAULT 0,
  `has_limits` TINYINT(1) NULL DEFAULT 1,
  `trial_limits` INT(11) NULL DEFAULT 1,
  `threshold` FLOAT NULL DEFAULT 75,
  `assessment_methods` ENUM('H', 'N') NULL DEFAULT 'H',
  `number_of_question` INT(11) NULL DEFAULT 10,
  `number_of_option` INT(11) NULL DEFAULT 5,
  `question_per_page` INT(11) NULL DEFAULT 10,
  `random` TINYINT(1) NULL DEFAULT 1,
  `duration` BIGINT(20) NULL DEFAULT 3600,
  `has_alert` TINYINT(1) NULL DEFAULT 1,
  `alert_time` BIGINT(20) NULL DEFAULT 300,
  `alert_message` TEXT NULL DEFAULT NULL,
  `standard_score` DOUBLE NULL DEFAULT 1,
  `penalty` DOUBLE NULL DEFAULT 0,
  `order` INT(11) NULL DEFAULT NULL,
  `score_notification` TINYINT(1) NULL DEFAULT 0,
  `publish_answer` TINYINT(1) NULL DEFAULT 0,
  `time_answer_publication` DATETIME NULL DEFAULT NULL,
  `test_availability` ENUM('F', 'L') NULL DEFAULT 'F',
  `available_from` DATETIME NULL DEFAULT NULL,
  `available_to` DATETIME NULL DEFAULT NULL,
  `autosubmit` TINYINT(1) NULL DEFAULT NULL,
  `time_create` TIMESTAMP NULL DEFAULT NULL,
  `time_edit` TIMESTAMP NULL DEFAULT NULL,
  `member_create` VARCHAR(40) NULL DEFAULT NULL,
  `role_create` CHAR(1) NULL DEFAULT NULL,
  `member_edit` VARCHAR(40) NULL DEFAULT NULL,
  `role_edit` CHAR(1) NULL DEFAULT NULL,
  `ip_create` VARCHAR(50) NULL DEFAULT NULL,
  `ip_edit` VARCHAR(50) NULL DEFAULT NULL,
  `active` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`test_id`),
  INDEX `test_school_id_idx` (`school_id` ASC) VISIBLE,
  INDEX `test_school_program_id_idx` (`school_program_id` ASC) VISIBLE,
  INDEX `test_teacher_id_idx` (`teacher_id` ASC) VISIBLE,
  CONSTRAINT `test_school_id`
    FOREIGN KEY (`school_id`)
    REFERENCES `mini_picopi`.`edu_school` (`school_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `test_school_program_id`
    FOREIGN KEY (`school_program_id`)
    REFERENCES `mini_picopi`.`edu_school_program` (`school_program_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `test_teacher_id`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `mini_picopi`.`edu_teacher` (`teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mini_picopi`.`edu_answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_picopi`.`edu_answer` (
  `answer_id` VARCHAR(40) NOT NULL,
  `school_id` VARCHAR(40) NULL DEFAULT NULL,
  `test_id` VARCHAR(40) NULL DEFAULT NULL,
  `student_id` VARCHAR(40) NULL DEFAULT NULL,
  `start` DATETIME NULL DEFAULT NULL,
  `end` DATETIME NULL DEFAULT NULL,
  `answer` TEXT NULL DEFAULT NULL,
  `true` INT(11) NULL DEFAULT NULL,
  `false` INT(11) NULL DEFAULT NULL,
  `initial_score` DOUBLE NULL DEFAULT NULL,
  `penalty` DOUBLE NULL DEFAULT NULL,
  `final_score` DOUBLE NULL DEFAULT NULL,
  `percent` DOUBLE NULL DEFAULT NULL,
  `active` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`answer_id`),
  INDEX `answer_school_id_idx` (`school_id` ASC) VISIBLE,
  INDEX `answer_student_id_idx` (`student_id` ASC) VISIBLE,
  INDEX `answer_test_id_idx` (`test_id` ASC) VISIBLE,
  CONSTRAINT `answer_school_id`
    FOREIGN KEY (`school_id`)
    REFERENCES `mini_picopi`.`edu_school` (`school_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `answer_student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `mini_picopi`.`edu_student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `answer_test_id`
    FOREIGN KEY (`test_id`)
    REFERENCES `mini_picopi`.`edu_test` (`test_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mini_picopi`.`edu_article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_picopi`.`edu_article` (
  `article_id` VARCHAR(40) NOT NULL,
  `school_id` VARCHAR(40) NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `content` LONGTEXT NULL DEFAULT NULL,
  `open` TINYINT(1) NULL DEFAULT 0,
  `class` TEXT NULL DEFAULT NULL,
  `time_create` TIMESTAMP NULL DEFAULT NULL,
  `time_edit` TIMESTAMP NULL DEFAULT NULL,
  `member_create` VARCHAR(40) NULL DEFAULT NULL,
  `role_create` CHAR(1) NULL DEFAULT NULL,
  `member_edit` VARCHAR(40) NULL DEFAULT NULL,
  `role_edit` CHAR(1) NULL DEFAULT NULL,
  `ip_create` VARCHAR(50) NULL DEFAULT NULL,
  `ip_edit` VARCHAR(50) NULL DEFAULT NULL,
  `reader` LONGTEXT NULL DEFAULT NULL,
  `read` BIGINT(20) NULL DEFAULT NULL,
  `active` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`article_id`),
  INDEX `article_school_id_idx` (`school_id` ASC) VISIBLE,
  CONSTRAINT `article_school_id`
    FOREIGN KEY (`school_id`)
    REFERENCES `mini_picopi`.`edu_school` (`school_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mini_picopi`.`edu_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_picopi`.`edu_info` (
  `info_id` VARCHAR(40) NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `content` LONGTEXT NULL DEFAULT NULL,
  `time_create` TIMESTAMP NULL DEFAULT NULL,
  `time_edit` TIMESTAMP NULL DEFAULT NULL,
  `admin_create` VARCHAR(40) NULL DEFAULT NULL,
  `admin_edit` VARCHAR(40) NULL DEFAULT NULL,
  `ip_create` VARCHAR(50) NULL DEFAULT NULL,
  `ip_edit` VARCHAR(50) NULL DEFAULT NULL,
  `active` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`info_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mini_picopi`.`edu_mail_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_picopi`.`edu_mail_list` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `active` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mini_picopi`.`edu_member_school`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_picopi`.`edu_member_school` (
  `member_id` BIGINT(20) NOT NULL,
  `school_id` INT(11) NOT NULL,
  `role` CHAR(1) NOT NULL DEFAULT 'S',
  `class_id` BIGINT(20) NULL DEFAULT NULL,
  `time_create` TIMESTAMP NULL DEFAULT NULL,
  `active` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`member_id`, `school_id`, `role`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mini_picopi`.`edu_question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_picopi`.`edu_question` (
  `question_id` VARCHAR(40) NOT NULL,
  `basic_competence` VARCHAR(20) NULL DEFAULT NULL,
  `content` LONGTEXT NULL DEFAULT NULL,
  `school_id` VARCHAR(40) NULL DEFAULT NULL,
  `test_id` VARCHAR(40) NULL DEFAULT NULL,
  `order` INT(11) NULL DEFAULT NULL,
  `multiple_choice` TINYINT(1) NULL DEFAULT 0,
  `random` TINYINT(1) NULL DEFAULT 0,
  `numbering` VARCHAR(50) NULL DEFAULT 'upper-alpha',
  `digest` VARCHAR(40) NULL DEFAULT NULL,
  `time_create` TIMESTAMP NULL DEFAULT NULL,
  `member_create` VARCHAR(50) NULL DEFAULT NULL,
  `time_edit` TIMESTAMP NULL DEFAULT NULL,
  `member_edit` VARCHAR(50) NULL DEFAULT NULL,
  `active` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`question_id`),
  INDEX `question_test_id_idx` (`test_id` ASC) VISIBLE,
  INDEX `question_school_id_idx` (`school_id` ASC) VISIBLE,
  CONSTRAINT `question_test_id`
    FOREIGN KEY (`test_id`)
    REFERENCES `mini_picopi`.`edu_test` (`test_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `question_school_id`
    FOREIGN KEY (`school_id`)
    REFERENCES `mini_picopi`.`edu_school` (`school_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mini_picopi`.`edu_option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_picopi`.`edu_option` (
  `option_id` VARCHAR(40) NOT NULL,
  `school_id` VARCHAR(40) NULL DEFAULT NULL,
  `test_id` VARCHAR(40) NULL DEFAULT NULL,
  `question_id` VARCHAR(40) NULL DEFAULT NULL,
  `content` LONGTEXT NULL DEFAULT NULL,
  `order` INT(11) NULL DEFAULT NULL,
  `score` DOUBLE NULL DEFAULT NULL,
  `time_create` TIMESTAMP NULL DEFAULT NULL,
  `member_create` VARCHAR(20) NULL DEFAULT NULL,
  `time_edit` TIMESTAMP NULL DEFAULT NULL,
  `member_edit` VARCHAR(20) NULL DEFAULT NULL,
  `active` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`option_id`),
  INDEX `option_question_id_idx` (`question_id` ASC) VISIBLE,
  INDEX `option_test_id_idx` (`test_id` ASC) VISIBLE,
  INDEX `option_school_id_idx` (`school_id` ASC) VISIBLE,
  CONSTRAINT `option_question_id`
    FOREIGN KEY (`question_id`)
    REFERENCES `mini_picopi`.`edu_question` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `option_test_id`
    FOREIGN KEY (`test_id`)
    REFERENCES `mini_picopi`.`edu_test` (`test_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `option_school_id`
    FOREIGN KEY (`school_id`)
    REFERENCES `mini_picopi`.`edu_school` (`school_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mini_picopi`.`edu_school_response`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_picopi`.`edu_school_response` (
  `school_response_id` VARCHAR(40) NOT NULL,
  `school` VARCHAR(100) NULL DEFAULT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `content` LONGTEXT NULL DEFAULT NULL,
  `time` DATETIME NULL DEFAULT NULL,
  `active` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`school_response_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mini_picopi`.`edu_test_collection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_picopi`.`edu_test_collection` (
  `test_collection_id` INT(11) NOT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `number_of_question` INT(11) NULL DEFAULT 0,
  `number_of_option` INT(11) NULL DEFAULT 0,
  `grade_id` BIGINT(20) NULL DEFAULT NULL,
  `file_name` VARCHAR(100) NULL DEFAULT NULL,
  `file_path` VARCHAR(50) NULL DEFAULT NULL,
  `file_size` BIGINT(20) NULL DEFAULT NULL,
  `file_md5` VARCHAR(45) NULL DEFAULT NULL,
  `file_sha1` VARCHAR(45) NULL DEFAULT NULL,
  `time_create` TIMESTAMP NULL DEFAULT NULL,
  `time_edit` TIMESTAMP NULL DEFAULT NULL,
  `ip_create` VARCHAR(50) NULL DEFAULT NULL,
  `ip_edit` VARCHAR(50) NULL DEFAULT NULL,
  `taken` BIGINT(20) NULL DEFAULT 0,
  `active` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`test_collection_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mini_picopi`.`edu_test_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_picopi`.`edu_test_member` (
  `test_member_id` VARCHAR(40) NOT NULL,
  `school_id` VARCHAR(40) NULL DEFAULT NULL,
  `student_id` VARCHAR(40) NULL DEFAULT NULL,
  `test_id` VARCHAR(40) NULL DEFAULT NULL,
  `sessions_id` VARCHAR(32) NULL DEFAULT NULL,
  `time_enter` DATETIME NULL DEFAULT NULL,
  `ip_enter` VARCHAR(45) NULL DEFAULT NULL,
  `time_exit` DATETIME NULL DEFAULT NULL,
  `ip_exit` VARCHAR(45) NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT 1,
  `member_edit` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`test_member_id`),
  INDEX `test_member_school_id_idx` (`school_id` ASC) VISIBLE,
  INDEX `test_member_student_id_idx` (`student_id` ASC) VISIBLE,
  INDEX `test_member_test_id_idx` (`test_id` ASC) VISIBLE,
  CONSTRAINT `test_member_school_id`
    FOREIGN KEY (`school_id`)
    REFERENCES `mini_picopi`.`edu_school` (`school_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `test_member_student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `mini_picopi`.`edu_student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `test_member_test_id`
    FOREIGN KEY (`test_id`)
    REFERENCES `mini_picopi`.`edu_test` (`test_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mini_picopi`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_picopi`.`member` (
  `member_id` BIGINT(20) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `phone_code` VARCHAR(10) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `gender` CHAR(1) NULL DEFAULT NULL,
  `birth_day` DATE NULL DEFAULT NULL,
  `birth_place` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `auth` VARCHAR(45) NULL DEFAULT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  `background` TEXT NULL DEFAULT NULL,
  `circle_avatar` TINYINT(1) NULL DEFAULT 0,
  `picture_hash` VARCHAR(4) NULL DEFAULT NULL,
  `picture_crop_position` VARCHAR(45) NULL DEFAULT NULL,
  `img_360_compress` TINYINT(1) NULL DEFAULT 0,
  `show_compass` TINYINT(1) NULL DEFAULT 1,
  `autoplay_360` TINYINT(1) NULL DEFAULT 0,
  `autorotate_360` INT(11) NULL DEFAULT 0,
  `following` BIGINT(20) NULL DEFAULT NULL,
  `follower` BIGINT(20) NULL DEFAULT NULL,
  `language` VARCHAR(10) NULL DEFAULT 'en',
  `country_id` VARCHAR(3) NULL DEFAULT NULL,
  `state_id` VARCHAR(40) NULL DEFAULT NULL,
  `city_id`VARCHAR(40) NULL DEFAULT NULL,
  `state` VARCHAR(100) NULL DEFAULT NULL,
  `city` VARCHAR(100) NULL DEFAULT NULL,
  `time_register` DATETIME NULL DEFAULT NULL,
  `last_activity_ip` VARCHAR(45) NULL DEFAULT NULL,
  `last_activity_time` DATETIME NULL DEFAULT NULL,
  `last_update_avatar_time` DATETIME NULL DEFAULT NULL,
  `last_seen_ip` VARCHAR(45) NULL DEFAULT NULL,
  `last_seen_time` DATETIME NULL DEFAULT NULL,
  `confirmed` TINYINT(1) NULL DEFAULT 0,
  `blocked` TINYINT(1) NULL DEFAULT 0,
  `active` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`member_id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mini_picopi`.`state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_picopi`.`state` (
  `state_id` VARCHAR(40) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `country_id` VARCHAR(3) NOT NULL,
  `state_code` VARCHAR(7) NULL DEFAULT NULL,
  `subdivision_code` VARCHAR(7) NULL DEFAULT NULL,
  `type` VARCHAR(3) NULL DEFAULT NULL,
  `verify` TINYINT(1) NULL DEFAULT 0,
  `active` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`state_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

USE `mini_picopi` ;

-- -----------------------------------------------------
-- procedure reset_admin_password
-- -----------------------------------------------------

DELIMITER $$
USE `mini_picopi`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `reset_admin_password` (IN `in_username` VARCHAR(100), IN `in_password` VARCHAR(100))  NO SQL BEGIN
DECLARE 
`val_member_id` BIGINT DEFAULT NULL;


SELECT `admin_id` INTO `val_member_id` FROM `edu_admin` WHERE `username` like `in_username`;


IF `val_member_id` IS NOT NULL THEN
UPDATE `edu_admin` SET `password` = md5(md5(`in_password`)) WHERE `admin_id` = `val_member_id`;
UPDATE `member` SET `password` = md5(md5(`in_password`)) WHERE `member_id` = `val_member_id`;
END IF;


END$$

DELIMITER ;

-- -----------------------------------------------------
-- function city_id_to_name
-- -----------------------------------------------------

DELIMITER $$
USE `mini_picopi`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `city_id_to_name` (`in_city_id` BIGINT) RETURNS VARCHAR(100) CHARSET latin1 NO SQL begin


declare `out_name` varchar(100) default null;
select `city`.`name` into `out_name` from `city` where `city`.`city_id` = `in_city_id`;
return `out_name`;


end$$

DELIMITER ;

-- -----------------------------------------------------
-- function city_name_to_id
-- -----------------------------------------------------

DELIMITER $$
USE `mini_picopi`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `city_name_to_id` (`in_name` VARCHAR(100), `in_state_id` BIGINT, `in_country_id` VARCHAR(3)) RETURNS VARCHAR(40) NO SQL begin


declare `out_city_id` bigint default 0;


if `in_name` = '' or `in_name` is null then
return null;
end if;


select `city`.`city_id` into `out_city_id`
from `city` where `city`.`name` like `in_name` and (`city`.`state_id` = `in_state_id` or `in_state_id` = '' or `in_state_id` = 0 or `in_state_id` is null) and `city`.`country_id` = `in_country_id` limit 0,1;


if `out_city_id` is null or `out_city_id` = 0 then
INSERT INTO `city` 
(`name`, `state_id`, `country_id`) values
(`in_name`, `in_state_id`, `in_country_id`);
select last_insert_id() into `out_city_id`;
end if;


return `out_city_id`;
end$$

DELIMITER ;

-- -----------------------------------------------------
-- function country_id_to_name
-- -----------------------------------------------------

DELIMITER $$
USE `mini_picopi`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `country_id_to_name` (`cid` VARCHAR(5)) RETURNS VARCHAR(100) CHARSET latin1 NO SQL begin
declare `cname` varchar(100);


select `country`.`name` into `cname` from `country` where `country`.`country_id` like `cid` limit 0,1;
return `cname`;
end$$

DELIMITER ;

-- -----------------------------------------------------
-- function get_class_id_from_name
-- -----------------------------------------------------

DELIMITER $$
USE `mini_picopi`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `get_class_id_from_name` (`in_class` VARCHAR(100), `in_school` BIGINT) RETURNS VARCHAR(40) NO SQL begin
declare `out_id` bigint default null;
select `edu_class`.`class_id` into `out_id`
from `edu_class`
where `edu_class`.`name` like `in_class`
and `edu_class`.`school_id` = `in_school`
limit 0, 1;


if `out_id` is null then
INSERT INTO `edu_class` 
(`school_id`, `name`, `time_create`, `time_edit`, `active`) values
(`in_school`, `in_class`, now(), now(), '1');
select last_insert_id() into `out_id`;
end if;




return `out_id`;
end$$

DELIMITER ;

-- -----------------------------------------------------
-- function get_school_id_from_name
-- -----------------------------------------------------

DELIMITER $$
USE `mini_picopi`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `get_school_id_from_name` (`in_school` VARCHAR(100)) RETURNS VARCHAR(40) NO SQL begin
declare `out_id` bigint default null;
select `edu_school`.`school_id` into `out_id`
from `edu_school`
where `edu_school`.`name` like `in_school`
limit 0, 1;
return `out_id`;
end$$

DELIMITER ;

-- -----------------------------------------------------
-- function get_school_program_id_from_name
-- -----------------------------------------------------

DELIMITER $$
USE `mini_picopi`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `get_school_program_id_from_name` (`in_school_program` VARCHAR(100), `in_school` BIGINT) RETURNS VARCHAR(40) NO SQL begin
declare `out_id` bigint default null;
select `edu_school_program`.`school_program_id` into `out_id`
from `edu_school_program`
where `edu_school_program`.`name` like `in_school_program`
and `edu_school_program`.`school_id` = `in_school`
limit 0, 1;


if `out_id` is null then
INSERT INTO `edu_school_program` 
(`school_id`, `name`, `time_create`, `time_edit`, `active`) values
(`in_school`, `in_school_program`, now(), now(), '1');
select last_insert_id() into `out_id`;
end if;




return `out_id`;
end$$

DELIMITER ;

-- -----------------------------------------------------
-- function state_id_to_name
-- -----------------------------------------------------

DELIMITER $$
USE `mini_picopi`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `state_id_to_name` (`in_state_id` BIGINT) RETURNS VARCHAR(100) CHARSET latin1 NO SQL begin


declare `out_name` varchar(100) default null;
select `state`.`name` into `out_name` from `state` where `state`.`state_id` = `in_state_id`;
return `out_name`;


end$$

DELIMITER ;

-- -----------------------------------------------------
-- function state_name_to_id
-- -----------------------------------------------------

DELIMITER $$
USE `mini_picopi`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `state_name_to_id` (`in_name` VARCHAR(100), `in_country_id` VARCHAR(3)) RETURNS VARCHAR(40) NO SQL begin


declare `out_state_id` bigint default 0;


if `in_name` = '' or `in_name` is null then
return null;
end if;


select `state`.`state_id` into `out_state_id`
from `state` where `state`.`name` like `in_name` and `state`.`country_id` = `in_country_id` limit 0,1;


if `out_state_id` > 0 then
return `out_state_id`;
end if;


if `out_state_id` is null or `out_state_id` = 0 then
INSERT INTO `state` 
(`name`, `country_id`) values
(`in_name`, `in_country_id`);
select last_insert_id() into `out_state_id`;
end if;


return `out_state_id`;
end$$

DELIMITER ;
USE `mini_picopi`;

DELIMITER $$
USE `mini_picopi`$$
CREATE TRIGGER `after_delete_edu_admin` AFTER DELETE ON `edu_admin` FOR EACH ROW begin
DELETE FROM `edu_member_school` where `role` = 'A' and `member_id` = OLD.`admin_id`;
end$$

USE `mini_picopi`$$
CREATE TRIGGER `after_delete_edu_student` AFTER DELETE ON `edu_student` FOR EACH ROW begin
DELETE FROM `edu_member_school` where `role` = 'S' and `member_id` = OLD.`student_id`;
end$$

USE `mini_picopi`$$
CREATE TRIGGER `after_delete_edu_teacher` AFTER DELETE ON `edu_teacher` FOR EACH ROW begin
DELETE FROM `edu_member_school` where `role` = 'T' and `member_id` = OLD.`teacher_id`;
end$$

USE `mini_picopi`$$
CREATE TRIGGER `after_delete_edu_test` AFTER DELETE ON `edu_test` FOR EACH ROW begin
DELETE FROM `edu_question` where `edu_question`.`test_id` = OLD.`test_id`;


DELETE FROM `edu_answer` where `edu_answer`.`test_id` = OLD.`test_id`;


DELETE FROM `edu_test_member` where `edu_test_member`.`test_id` = OLD.`test_id`;
end$$

USE `mini_picopi`$$
CREATE TRIGGER `after_delete_edu_question` AFTER DELETE ON `edu_question` FOR EACH ROW begin
DELETE FROM `edu_option` where `edu_option`.`question_id` = OLD.`question_id`;
end$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
