<?php 
switch($verse){
case 1:{?>Alif Laam Raa, (inilah) suatu kitab yang ayat-ayatnya disusun dengan rapi serta dijelaskan secara terperinci yang diturunkan dari sisi (Allah) yang Maha Bijaksana lagi Maha Tahu,<?php break;}
case 2:{?>agar kamu tidak menyembah selain Allah. Sesungguhnya aku (Muhammad) adalah pemberi peringatan dan pembawa kabar gembira kepadamu daripada-Nya,<?php break;}
case 3:{?>dan hendaklah kamu meminta ampun kepada Tuhanmu dan bertobat kepada-Nya. (Jika kamu, mengerjakan yang demikian), niscaya Dia akan memberi kenikmatan yang baik (terus menerus) kepadamu sampai kepada waktu yang telah ditentukan dan Dia akan memberi kepada tiap-tiap orang yang mempunyai keutamaan (balasan) keutamaannya. Jika kamu berpaling, maka sesungguhnya aku takut kamu akan ditimpa siksa hari kiamat.<?php break;}
case 4:{?>Kepada Allah-lah kembalimu, dan Dia Maha Kuasa atas segala sesuatu.<?php break;}
case 5:{?>Ingatlah, sesungguhnya (orang munafik itu) memalingkan dada mereka untuk menyembunyikan diri daripadanya (Muhammad). Ingatlah, di waktu mereka menyelimuti dirinya dengan kain, Allah mengetahui apa yang mereka sembunyikan dan apa yang mereka lahirkan, sesungguhnya Allah Maha Mengetahui segala isi hati.<?php break;}
case 6:{?>Dan tidak ada suatu binatang melata pun di bumi melainkan Allah-lah yang memberi rezekinya, dan Dia mengetahui tempat berdiam binatang itu dan tempat penyimpanannya. Semuanya tertulis dalam kitab yang nyata (Lohmahfuz).<?php break;}
case 7:{?>Dan Dia-lah yang menciptakan langit dan bumi dalam enam masa, dan adalah Arasy-Nya di atas air, agar Dia menguji siapakah di antara kamu yang lebih baik amalnya, dan jika kamu berkata (kepada penduduk Mekah): &quot;Sesungguhnya kamu akan dibangkitkan sesudah mati&quot;, niscaya orang-orang yang kafir itu akan berkata: &quot;Ini tidak lain hanyalah sihir yang nyata&quot;.<?php break;}
case 8:{?>Dan sesungguhnya jika kami undurkan azab dari mereka sampai kepada suatu waktu yang ditentukan, niscaya mereka akan berkata: &quot;Apakah yang menghalanginya?&quot; Ingatlah, di waktu azab itu datang kepada mereka tidaklah dapat dipalingkan dari mereka dan mereka diliputi oleh azab yang dahulunya mereka selalu memperolok-olokkannya.<?php break;}
case 9:{?>Dan jika Kami rasakan kepada manusia suatu rahmat (nikmat) dari Kami, kemudian rahmat itu Kami cabut daripadanya, pastilah dia menjadi putus asa lagi tidak berterima kasih.<?php break;}
case 10:{?>Dan jika Kami rasakan kepadanya kebahagiaan sesudah bencana yang menimpanya, niscaya dia akan berkata: &quot;Telah hilang bencana-bencana itu dari padaku&quot;; sesungguhnya dia sangat gembira lagi bangga,<?php break;}
case 11:{?>kecuali orang-orang yang sabar (terhadap bencana), dan mengerjakan amal-amal saleh; mereka itu beroleh ampunan dan pahala yang besar.<?php break;}
case 12:{?>Maka boleh jadi kamu hendak meninggalkan sebahagian dari apa yang diwahyukan kepadamu dan sempit karenanya dadamu, karena khawatir bahwa mereka akan mengatakan: &quot;Mengapa tidak diturunkan kepadanya perbendaharaan (kekayaan) atau datang bersama-sama dengan dia seorang malaikat?&quot; Sesungguhnya kamu hanyalah seorang pemberi peringatan dan Allah Pemelihara segala sesuatu.<?php break;}
case 13:{?>Bahkan mereka mengatakan: &quot;Muhammad telah membuat-buat Al Qur'an itu&quot;, Katakanlah: &quot;(Kalau demikian), maka datangkanlah sepuluh surah-surah yang dibuat-buat yang menyamainya, dan panggillah orang-orang yang kamu sanggup (memanggilnya) selain Allah, jika kamu memang orang-orang yang benar&quot;.<?php break;}
case 14:{?>Jika mereka yang kamu seru itu tidak menerima seruanmu (ajakanmu) itu maka (katakanlah olehmu): &quot;Ketahuilah, sesungguhnya Al Qur'an itu diturunkan dengan ilmu Allah dan bahwasanya tidak ada Tuhan selain Dia, maka maukah kamu berserah diri (kepada Allah)?&quot;<?php break;}
case 15:{?>Barang siapa yang menghendaki kehidupan dunia dan perhiasannya, niscaya Kami berikan kepada mereka balasan pekerjaan mereka di dunia dengan sempurna dan mereka di dunia itu tidak akan dirugikan.<?php break;}
case 16:{?>Itulah orang-orang yang tidak memperoleh di akhirat, kecuali neraka dan lenyaplah di akhirat itu apa yang telah mereka usahakan di dunia dan sia-sialah apa yang telah mereka kerjakan?<?php break;}
case 17:{?>Apakah (orang-orang kafir itu sama dengan) orang-orang yang mempunyai bukti yang nyata (Al Qur'an) dari Tuhannya, dan diikuti pula oleh seorang saksi (Muhammad) dari Allah dan sebelum Al Qur'an itu telah ada kitab Musa yang menjadi pedoman dan rahmat? Mereka itu beriman kepada Al Qur'an. Dan barang siapa di antara mereka (orang-orang Quraisy) dan sekutu-sekutunya yang kafir kepada Al Qur'an, maka nerakalah tempat yang diancamkan baginya karena itu janganlah kamu ragu-ragu terhadap Al Qur'an itu. Sesungguhnya (Al Qur'an) itu benar-benar dari Tuhanmu, tetapi kebanyakan manusia tidak beriman.<?php break;}
case 18:{?>Dan siapakah yang lebih lalim daripada orang yang membuat-buat dusta terhadap Allah? Mereka itu akan dihadapkan kepada Tuhan mereka dan para saksi akan berkata: &quot;Orang-orang inilah yang telah berdusta terhadap Tuhan mereka&quot;. Ingatlah, kutukan Allah (ditimpakan) atas orang-orang yang lalim.<?php break;}
case 19:{?>(yaitu) orang-orang yang menghalangi (manusia) dari jalan Allah dan menghendaki (supaya) jalan itu bengkok. Dan mereka itulah orang-orang yang tidak percaya akan adanya hari akhirat.<?php break;}
case 20:{?>Orang-orang itu tidak mampu menghalang-halangi Allah untuk (mengazab mereka) di bumi ini, dan sekali-kali tidak adalah bagi mereka penolong selain Allah. Siksaan itu dilipat gandakan kepada mereka. Mereka selalu tidak dapat mendengar (kebenaran) dan mereka selalu tidak dapat melihat (nya).<?php break;}
case 21:{?>Mereka itulah orang-orang yang merugikan dirinya sendiri, dan lenyaplah dari mereka apa yang selalu mereka ada-adakan.<?php break;}
case 22:{?>Pasti mereka itu di akhirat menjadi orang-orang yang paling merugi.<?php break;}
case 23:{?>Sesungguhnya orang-orang yang beriman dan mengerjakan amal-amal saleh dan merendahkan diri kepada Tuhan mereka, mereka itu adalah penghuni-penghuni surga mereka kekal di dalamnya.<?php break;}
case 24:{?>Perbandingan kedua golongan itu (orang-orang kafir dan orang-orang mukmin), seperti orang buta dan tuli dengan orang yang dapat melihat dan dapat mendengar. Adakah kedua golongan itu sama keadaan dan sifatnya? Maka tidakkah kamu mengambil pelajaran (daripada perbandingan itu)?<?php break;}
case 25:{?>Dan sesungguhnya Kami telah mengutus Nuh kepada kaumnya, (dia berkata): &quot;Sesungguhnya aku adalah pemberi peringatan yang nyata bagi kamu,<?php break;}
case 26:{?>agar kamu tidak menyembah selain Allah. Sesungguhnya aku khawatir kamu akan ditimpa azab (pada) hari yang sangat menyedihkan&quot;.<?php break;}
case 27:{?>Maka berkatalah pemimpin-pemimpin yang kafir dari kaumnya: &quot;Kami tidak melihat kamu, melainkan (sebagai) seorang manusia (biasa) seperti kami, dan kami tidak melihat orang-orang yang mengikuti kamu melainkan orang-orang yang hina dina di antara kami yang lekas percaya saja, dan kami tidak melihat kamu memiliki sesuatu kelebihan apa pun atas kami, bahkan kami yakin bahwa kamu adalah orang-orang yang dusta&quot;.<?php break;}
case 28:{?>Berkata Nuh: &quot;Hai kaumku, bagaimana pikiranmu, jika aku ada mempunyai bukti yang nyata dari Tuhanku, dan diberinya aku rahmat dari sisi-Nya, tetapi rahmat itu disamarkan bagimu. Apa akan kami paksakankah kamu menerimanya, padahal kamu tiada menyukainya?&quot;<?php break;}
case 29:{?>Dan (dia berkata): &quot;Hai kaumku, aku tiada meminta harta benda kepada kamu (sebagai upah) bagi seruanku. Upahku hanyalah dari Allah dan aku sekali-kali tidak akan mengusir orang-orang yang telah beriman. Sesungguhnya mereka akan bertemu dengan Tuhannya, akan tetapi aku memandangmu suatu kaum yang tidak mengetahui&quot;.<?php break;}
case 30:{?>Dan (dia berkata): &quot;Hai kaumku, siapakah yang akan menolongku dari (azab) Allah jika aku mengusir mereka. Maka tidakkah kamu mengambil pelajaran?&quot;<?php break;}
case 31:{?>Dan aku tidak mengatakan kepada kamu (bahwa): &quot;Aku mempunyai gudang-gudang rezeki dan kekayaan dari Allah, dan aku tiada mengetahui yang gaib, dan tidak (pula) aku mengatakan: &quot;Bahwa sesungguhnya aku adalah malaikat&quot;, dan tidak juga aku mengatakan kepada orang-orang yang dipandang hina oleh penglihatanmu: &quot;Sekali-kali Allah tidak akan mendatangkan kebaikan kepada mereka&quot;. Allah lebih mengetahui apa yang ada pada diri mereka; sesungguhnya aku, kalau begitu benar-benar termasuk orang-orang yang lalim.<?php break;}
case 32:{?>Mereka berkata: &quot;Hai Nuh, sesungguhnya kamu telah berbantah dengan kami, dan kamu telah memperpanjang bantahanmu terhadap kami, maka datangkanlah kepada kami azab yang kamu ancamkan kepada kami, jika kamu termasuk orang-orang yang benar&quot;.<?php break;}
case 33:{?>Nuh menjawab: &quot;Hanyalah Allah yang akan mendatangkan azab itu kepadamu jika Dia menghendaki dan kamu sekali-kali tidak dapat melepaskan diri.<?php break;}
case 34:{?>Dan tidaklah bermanfaat kepadamu nasihatku jika aku hendak memberi nasihat kepada kamu, sekiranya Allah hendak menyesatkan kamu, Dia adalah Tuhanmu dan kepada-Nya-lah kamu dikembalikan&quot;.<?php break;}
case 35:{?>Malahan kaum Nuh itu berkata: &quot;Dia cuma membuat-buat nasihatnya saja&quot;. Katakanlah: &quot;Jika aku membuat-buat nasihat itu, maka hanya akulah yang memikul dosaku, dan aku berlepas diri dari dosa yang kamu perbuat&quot;.<?php break;}
case 36:{?>Dan diwahyukan kepada Nuh, bahwasanya sekali-kali tidak akan beriman di antara kaummu, kecuali orang yang telah beriman (saja), karena itu janganlah kamu bersedih hati tentang apa yang selalu mereka kerjakan.<?php break;}
case 37:{?>Dan buatlah bahtera itu dengan pengawasan dan petunjuk wahyu Kami, dan janganlah kamu bicarakan dengan Aku tentang orang yang lalim itu; sesungguhnya mereka itu akan ditenggelamkan.<?php break;}
case 38:{?>Dan mulailah Nuh membuat bahtera. Dan setiap kali pemimpin kaumnya berjalan melewati Nuh, mereka mengejeknya. Berkatalah Nuh: &quot;Jika kamu mengejek kami, maka sesungguhnya kami (pun) mengejekmu sebagaimana kamu sekalian mengejek (kami).<?php break;}
case 39:{?>Kelak kamu akan mengetahui siapa yang akan ditimpa oleh azab yang menghinakannya dan yang akan ditimpa azab yang kekal.&quot;<?php break;}
case 40:{?>Hingga apabila perintah Kami datang dan dapur telah memancarkan air, Kami berfirman: &quot;Muatkanlah ke dalam bahtera itu dari masing-masing binatang sepasang (jantan dan betina), dan keluargamu kecuali orang yang telah terdahulu ketetapan terhadapnya dan (muatkan pula) orang-orang yang beriman.&quot; Dan tidak beriman bersama dengan Nuh itu kecuali sedikit.<?php break;}
case 41:{?>Dan Nuh berkata: &quot;Naiklah kamu sekalian ke dalamnya dengan menyebut nama Allah di waktu berlayar dan berlabuhnya.&quot; Sesungguhnya Tuhanku benar-benar Maha Pengampun lagi Maha Penyayang.<?php break;}
case 42:{?>Dan bahtera itu berlayar membawa mereka dalam gelombang laksana gunung. Dan Nuh memanggil anaknya sedang anak itu berada di tempat yang jauh terpencil: &quot;Hai anakku, naiklah (ke kapal) bersama kami dan janganlah kamu berada bersama orang-orang yang kafir.&quot;<?php break;}
case 43:{?>Anaknya menjawab: &quot;Aku akan mencari perlindungan ke gunung yang dapat memeliharaku dari air bah!&quot; Nuh berkata: &quot;Tidak ada yang melindungi hari ini dari azab Allah selain Allah (saja) Yang Maha Penyayang&quot;. Dan gelombang menjadi penghalang antara keduanya; maka jadilah anak itu termasuk orang-orang yang ditenggelamkan.<?php break;}
case 44:{?>Dan difirmankan: &quot;Hai bumi telanlah airmu, dan hai langit (hujan) berhentilah,&quot; Dan air pun disurutkan, perintahpun diselesaikan dan bahtera itu pun berlabuh di atas bukit Judi, dan dikatakan: &quot;Binasalah orang-orang yang lalim.&quot;<?php break;}
case 45:{?>Dan Nuh berseru kepada Tuhannya sambil berkata: &quot;Ya Tuhanku, sesungguhnya anakku, termasuk keluargaku, dan sesungguhnya janji Engkau itulah yang benar. Dan Engkau adalah Hakim yang seadil-adilnya.&quot;<?php break;}
case 46:{?>Allah berfirman: &quot;Hai Nuh, sesungguhnya dia bukanlah termasuk keluargamu (yang dijanjikan akan diselamatkan), sesungguhnya (perbuatannya) perbuatan yang tidak baik. Sebab itu janganlah kamu memohon kepada-Ku sesuatu yang kamu tidak mengetahui (hakikat) nya. Sesungguhnya Aku memperingatkan kepadamu supaya kamu jangan termasuk orang-orang yang tidak berpengetahuan.&quot;<?php break;}
case 47:{?>Nuh berkata: &quot;Ya Tuhanku, sesungguhnya aku berlindung kepada Engkau dari memohon kepada Engkau sesuatu yang aku tiada mengetahui (hakikat) nya. Dan sekiranya Engkau tidak memberi ampun kepadaku, dan (tidak) menaruh belas kasihan kepadaku, niscaya aku akan termasuk orang-orang yang merugi.&quot;<?php break;}
case 48:{?>Difirmankan: &quot;Hai Nuh, turunlah dengan selamat sejahtera dan penuh keberkatan dari Kami atasmu dan atas umat-umat (yang mukmin) dari orang-orang yang bersamamu. Dan ada (pula) umat-umat yang Kami beri kesenangan pada mereka (dalam kehidupan dunia), kemudian mereka akan ditimpa azab yang pedih dari Kami.&quot;<?php break;}
case 49:{?>Itu adalah di antara berita-berita penting tentang yang gaib yang Kami wahyukan kepadamu (Muhammad); tidak pernah kamu mengetahuinya dan tidak (pula) kaummu sebelum ini. Maka bersabarlah; sesungguhnya kesudahan yang baik adalah bagi orang-orang yang bertakwa.<?php break;}
case 50:{?>Dan kepada kaum Ad (Kami utus) saudara mereka, Hud. Ia berkata: &quot;Hai kaumku, sembahlah Allah, sekali-kali tidak ada bagimu Tuhan selain Dia. Kamu hanyalah mengada-adakan saja.<?php break;}
case 51:{?>Hai kaumku, aku tidak meminta upah kepadamu bagi seruanku ini, Upahku tidak lain hanyalah dari Allah yang telah menciptakanku. Maka tidakkah kamu memikirkan (nya)?&quot;<?php break;}
case 52:{?>Dan (dia berkata): &quot;Hai kaumku, mohonlah ampun kepada Tuhanmu lalu bertobatlah kepada-Nya, niscaya Dia menurunkan hujan yang sangat deras atasmu, dan Dia akan menambahkan kekuatan kepada kekuatanmu, dan janganlah kamu berpaling dengan berbuat dosa.&quot;<?php break;}
case 53:{?>Kaum Ad berkata: &quot;Hai Hud, kamu tidak mendatangkan kepada kami suatu bukti yang nyata, dan kami sekali-kali tidak akan meninggalkan sembahan-sembahan kami karena perkataanmu, dan kami sekali-kali tidak akan mempercayai kamu.<?php break;}
case 54:{?>Kami tidak mengatakan melainkan bahwa sebagian sembahan kami telah menimpakan penyakit gila atas dirimu.&quot; Hud menjawab: &quot;Sesungguhnya aku jadikan Allah sebagai saksiku dan saksikanlah olehmu sekalian bahwa sesungguhnya aku berlepas diri dari apa yang kamu persekutukan,<?php break;}
case 55:{?>dari selain-Nya, sebab itu jalankanlah tipu dayamu semuanya terhadapku dan janganlah kamu memberi tangguh kepadaku.<?php break;}
case 56:{?>Sesungguhnya aku bertawakal kepada Allah Tuhanku dan Tuhanmu. Tidak ada suatu binatang melata pun melainkan Dia-lah yang memegang ubun-ubunnya. Sesungguhnya Tuhanku di atas jalan yang lurus.&quot;<?php break;}
case 57:{?>Jika kamu berpaling, maka sesungguhnya aku telah menyampaikan kepadamu apa (amanat) yang aku diutus (untuk menyampaikan) nya kepadamu. Dan Tuhanku akan mengganti (kamu) dengan kaum yang lain (dari) kamu; dan kamu tidak dapat membuat mudarat kepada-Nya sedikit pun. Sesungguhnya Tuhanku adalah Maha Pemelihara segala sesuatu.<?php break;}
case 58:{?>Dan tatkala datang azab Kami, Kami selamatkan Hud dan orang-orang yang beriman bersama dia dengan rahmat dari Kami; dan Kami selamatkan (pula) mereka (di akhirat) dari 'azab yang berat.<?php break;}
case 59:{?>Dan itulah (kisah) kaum Ad yang mengingkari tanda-tanda kekuasaan Tuhan mereka, dan mendurhakai rasul-rasul Allah dan mereka menuruti perintah semua penguasa yang sewenang-wenang lagi menentang (kebenaran).<?php break;}
case 60:{?>Dan mereka selalu diikuti dengan kutukan di dunia ini dan (begitu pula) di hari kiamat. Ingatlah, sesungguhnya kaum Ad itu kafir kepada Tuhan mereka. Ingatlah, kebinasaanlah bagi kaum Ad (yaitu) kaum Hud itu.<?php break;}
case 61:{?>Dan kepada Tsamud (Kami utus) saudara mereka Saleh. Saleh berkata: &quot;Hai kaumku, sembahlah Allah, sekali-kali tidak ada bagimu Tuhan selain Dia. Dia telah menciptakan kamu dari bumi (tanah) dan menjadikan kamu pemakmurnya, karena itu mohonlah ampunan-Nya, kemudian bertobatlah kepada-Nya. Sesungguhnya Tuhanku amat dekat (rahmat-Nya) lagi memperkenankan (doa hamba-Nya).&quot;<?php break;}
case 62:{?>Kaum Tsamud berkata: &quot;Hai Saleh, sesungguhnya kamu sebelum ini adalah seorang di antara kami yang kami harapkan, apakah kamu melarang kami untuk menyembah apa yang disembah oleh bapak-bapak kami? dan sesungguhnya kami betul-betul dalam keraguan yang menggelisahkan terhadap agama yang kamu serukan kepada kami.&quot;<?php break;}
case 63:{?>Saleh berkata: &quot;Hai kaumku, bagaimana pikiranmu jika aku mempunyai bukti yang nyata dari Tuhanku dan diberi-Nya aku rahmat (kenabian) dari-Nya, maka siapakah yang akan menolong aku dari (azab) Allah jika aku mendurhakai-Nya. Sebab itu kamu tidak menambah apa pun kepadaku selain daripada kerugian.<?php break;}
case 64:{?>Hai kaumku, inilah unta betina dari Allah, sebagai mukjizat (yang menunjukkan kebenaran) untukmu, sebab itu biarkanlah dia makan di bumi Allah, dan janganlah kamu mengganggunya dengan gangguan apa pun yang akan menyebabkan kamu ditimpa azab yang dekat.&quot;<?php break;}
case 65:{?>Mereka membunuh unta itu, maka berkata Saleh: &quot;Bersukarialah kamu sekalian di rumahmu selama tiga hari, itu adalah janji yang tidak dapat didustakan.&quot;<?php break;}
case 66:{?>Maka tatkala datang azab Kami, Kami selamatkan Saleh beserta orang-orang yang beriman bersama dia dengan rahmat dari Kami dan (Kami selamatkan) dari kehinaan di hari itu. Sesungguhnya Tuhanmu Dia-lah Yang Maha Kuat lagi Maha Perkasa.<?php break;}
case 67:{?>Dan satu suara keras yang mengguntur menimpa orang-orang yang lalim itu, lalu mereka mati bergelimpangan di rumahnya.<?php break;}
case 68:{?>Seolah-olah mereka belum pernah berdiam di tempat itu. Ingatlah, sesungguhnya kaum Tsamud mengingkari Tuhan mereka. Ingatlah, kebinasaanlah bagi kaum Tsamud.<?php break;}
case 69:{?>Dan sesungguhnya utusan-utusan Kami (malaikat-malaikat) telah datang kepada Ibrahim dengan membawa kabar gembira, mereka mengucapkan: &quot;Salaman&quot; (Selamat). Ibrahim menjawab: &quot;Salamun&quot; (Selamatlah), maka tidak lama kemudian Ibrahim menyuguhkan daging anak sapi yang dipanggang.<?php break;}
case 70:{?>Maka tatkala dilihatnya tangan mereka tidak menjamahnya, Ibrahim memandang aneh perbuatan mereka, dan merasa takut kepada mereka. Malaikat itu berkata: &quot;Jangan kamu takut, sesungguhnya kami adalah (malaikat-malaikat) yang diutus kepada kaum Lut.&quot;<?php break;}
case 71:{?>Dan istrinya berdiri (di balik tirai) lalu dia tersenyum. Maka Kami sampaikan kepadanya berita gembira tentang (kelahiran) Ishak dan dari Ishak (akan lahir putranya) Yakub.<?php break;}
case 72:{?>Istrinya berkata: &quot;Sungguh mengherankan, apakah aku akan melahirkan anak padahal aku adalah seorang perempuan tua, dan ini suamiku pun dalam keadaan yang sudah tua pula? Sesungguhnya ini benar-benar suatu yang sangat aneh.<?php break;}
case 73:{?>Para malaikat itu berkata: &quot;Apakah kamu merasa heran tentang ketetapan Allah? (Itu adalah) rahmat Allah dan keberkatan-Nya, dicurahkan atas kamu, hai ahlulbait! Sesungguhnya Allah Maha Terpuji lagi Maha Pemurah.&quot;<?php break;}
case 74:{?>Maka tatkala rasa takut hilang dari Ibrahim dan berita gembira telah datang kepadanya, dia pun bersoal jawab dengan (malaikat-malaikat) Kami tentang kaum Lut.<?php break;}
case 75:{?>Sesungguhnya Ibrahim itu benar-benar seorang yang penyantun lagi pengiba dan suka kembali kepada Allah.<?php break;}
case 76:{?>Hai Ibrahim, tinggalkanlah soal jawab ini, sesungguhnya telah datang ketetapan Tuhanmu, dan sesungguhnya mereka itu akan didatangi azab yang tidak dapat ditolak.<?php break;}
case 77:{?>Dan tatkala datang utusan-utusan Kami (para malaikat) itu kepada Lut, dia merasa susah dan merasa sempit dadanya karena kedatangan mereka, dan dia berkata: &quot;Ini adalah hari yang amat sulit.&quot;<?php break;}
case 78:{?>Dan datanglah kepadanya kaumnya dengan bergegas-gegas. Dan sejak dahulu mereka selalu melakukan perbuatan-perbuatan yang keji. Lut berkata: &quot;Hai kaumku, inilah putri-putri (negeri) ku mereka lebih suci bagimu, maka bertakwalah kepada Allah dan janganlah kamu mencemarkan (nama) ku terhadap tamuku ini. Tidak adakah di antaramu seorang yang berakal?&quot;<?php break;}
case 79:{?>Mereka menjawab: &quot;Sesungguhnya kamu telah tahu bahwa kami tidak mempunyai keinginan terhadap putri-putrimu, dan sesungguhnya kamu tentu mengetahui apa yang sebenarnya kami kehendaki.&quot;<?php break;}
case 80:{?>Lut berkata: &quot;Seandainya aku ada mempunyai kekuatan (untuk menolakmu) atau kalau aku dapat berlindung kepada keluarga yang kuat (tentu aku lakukan).&quot;<?php break;}
case 81:{?>Para utusan (malaikat) berkata: &quot;Hai Lut, sesungguhnya kami adalah utusan-utusan Tuhanmu, sekali-kali mereka tidak akan dapat mengganggu kamu, sebab itu pergilah dengan membawa keluarga dan pengikut-pengikut kamu di akhir malam dan janganlah ada seorang di antara kamu yang tertinggal, kecuali istrimu. Sesungguhnya dia akan ditimpa azab yang menimpa mereka karena sesungguhnya saat jatuhnya azab kepada mereka ialah di waktu subuh; bukankah subuh itu sudah dekat?&quot;.<?php break;}
case 82:{?>Maka tatkala datang azab Kami, Kami jadikan negeri kaum Lut itu yang di atas ke bawah (Kami balikkan), dan Kami hujani mereka dengan batu dari tanah yang terbakar dengan bertubi-tubi,<?php break;}
case 83:{?>yang diberi tanda oleh Tuhanmu, dan siksaan itu tiadalah jauh dari orang-orang yang zalim.<?php break;}
case 84:{?>Dan kepada (penduduk) Mad-yan (Kami utus) saudara mereka, Syuaib. Ia berkata: &quot;Hai kaumku, sembahlah Allah, sekali-kali tiada Tuhan bagimu selain Dia. Dan janganlah kamu kurangi takaran dan timbangan, sesungguhnya aku melihat kamu dalam keadaan yang baik (mampu) dan sesungguhnya aku khawatir terhadapmu akan azab hari yang membinasakan (kiamat).&quot;<?php break;}
case 85:{?>Dan Syuaib berkata: &quot;Hai kaumku, cukupkanlah takaran dan timbangan dengan adil, dan janganlah kamu merugikan manusia terhadap hak-hak mereka dan janganlah kamu membuat kejahatan di muka bumi dengan membuat kerusakan.<?php break;}
case 86:{?>Sisa (keuntungan) dari Allah adalah lebih baik bagimu jika kamu orang-orang yang beriman. Dan aku bukanlah seorang penjaga atas dirimu.&quot;<?php break;}
case 87:{?>Mereka berkata: &quot;Hai Syuaib, apakah agamamu yang menyuruh kamu agar kami meninggalkan apa yang disembah oleh bapak-bapak kami atau melarang kami memperbuat apa yang kami kehendaki tentang harta kami. Sesungguhnya kamu adalah orang yang sangat penyantun lagi berakal.&quot;<?php break;}
case 88:{?>Syuaib berkata: &quot;Hai kaumku, bagaimana pikiranmu jika aku mempunyai bukti yang nyata dari Tuhanku dan dianugerahi-Nya aku daripada-Nya rezeki yang baik (patutkah aku menyalahi perintah-Nya)? Dan aku tidak berkehendak menyalahi kamu (dengan mengerjakan) apa yang aku larang. Aku tidak bermaksud kecuali (mendatangkan) perbaikan selama aku masih berkesanggupan. Dan tidak ada taufik bagiku melainkan dengan (pertolongan) Allah. Hanya kepada Allah aku bertawakal dan hanya kepada-Nya-lah aku kembali.<?php break;}
case 89:{?>Hai kaumku, janganlah hendaknya pertentangan antara aku (dengan kamu) menyebabkan kamu menjadi jahat hingga kamu ditimpa azab seperti yang menimpa kaum Nuh atau kaum Hud atau kaum Saleh, sedang kaum Lut tidak (pula) jauh (tempatnya) dari kamu.<?php break;}
case 90:{?>Dan mohonlah ampun kepada Tuhanmu kemudian bertobatlah kepada-Nya. Sesungguhnya Tuhanku Maha Penyayang lagi Maha Pengasih.<?php break;}
case 91:{?>Mereka berkata: &quot;Hai Syuaib, kami tidak banyak mengerti tentang apa yang kamu katakan itu dan sesungguhnya kami benar-benar melihat kamu seorang yang lemah di antara kami; kalau tidaklah karena keluargamu tentulah kami telah merajam kamu, sedang kamu pun bukanlah seorang yang berwibawa di sisi kami.<?php break;}
case 92:{?>Syuaib menjawab: &quot;Hai kaumku, apakah keluargaku lebih terhormat menurut pandanganmu daripada Allah, sedang Allah kamu jadikan sesuatu yang terbuang di belakangmu? Sesungguhnya (pengetahuan) Tuhanku meliputi apa yang kamu kerjakan.&quot;<?php break;}
case 93:{?>Dan (dia berkata): &quot;Hai kaumku, berbuatlah menurut kemampuanmu, sesungguhnya aku pun berbuat (pula). Kelak kamu akan mengetahui siapa yang akan ditimpa azab yang menghinakannya dan siapa yang berdusta. Dan tunggulah azab (Tuhan), sesungguhnya aku pun menunggu bersama kamu.&quot;<?php break;}
case 94:{?>Dan tatkala datang azab Kami, Kami selamatkan Syuaib dan orang-orang yang beriman bersama-sama dengan dia dengan rahmat dari Kami, dan orang-orang yang zalim dibinasakan oleh satu suara yang mengguntur, lalu jadilah mereka mati bergelimpangan di rumahnya.<?php break;}
case 95:{?>Seolah-olah mereka belum pernah berdiam di tempat itu. Ingatlah, kebinasaanlah bagi penduduk Mad-yan sebagaimana kaum Tsamud telah binasa.<?php break;}
case 96:{?>Dan sesungguhnya Kami telah mengutus Musa dengan tanda-tanda (kekuasaan) Kami dan mukjizat yang nyata,<?php break;}
case 97:{?>kepada Firaun dan pemimpin-pemimpin kaumnya, tetapi mereka mengikut perintah Firaun, padahal perintah Firaun sekali-kali bukanlah (perintah) yang benar.<?php break;}
case 98:{?>Ia berjalan di muka kaumnya di Hari Kiamat lalu memasukkan mereka ke dalam neraka. Neraka itu seburuk-buruk tempat yang didatangi.<?php break;}
case 99:{?>Dan mereka selalu diikuti dengan kutukan di dunia ini dan (begitu pula) di hari kiamat. Laknat itu seburuk-buruk pemberian yang diberikan.<?php break;}
case 100:{?>Itu adalah sebahagian dari berita-berita negeri (yang telah dibinasakan) yang Kami ceritakan kepadamu (Muhammad); di antara negeri-negeri itu ada yang masih kedapatan bekas-bekasnya dan ada (pula) yang telah musnah.<?php break;}
case 101:{?>Dan Kami tidaklah menganiaya mereka, tetapi merekalah yang menganiaya diri mereka sendiri, karena itu tiadalah bermanfaat sedikit pun kepada mereka sembahan-sembahan yang mereka seru selain Allah, di waktu azab Tuhanmu datang. Dan sembahan-sembahan itu tidaklah menambah kepada mereka kecuali kebinasaan belaka.<?php break;}
case 102:{?>Dan begitulah azab Tuhanmu, apabila Dia mengazab penduduk negeri-negeri yang berbuat zalim. Sesungguhnya azab-Nya itu adalah sangat pedih lagi keras.<?php break;}
case 103:{?>Sesungguhnya pada yang demikian itu benar-benar terdapat pelajaran bagi orang-orang yang takut kepada azab akhirat. Hari kiamat itu adalah suatu hari yang semua manusia dikumpulkan untuk (menghadapi) nya, dan hari itu adalah suatu hari yang disaksikan (oleh segala makhluk).<?php break;}
case 104:{?>Dan kami tiadalah mengundurkannya, melainkan sampai waktu yang tertentu.<?php break;}
case 105:{?>Di kala datang hari itu, tidak ada seorang pun yang berbicara, melainkan dengan izin-Nya; maka di antara mereka ada yang celaka dan ada yang berbahagia.<?php break;}
case 106:{?>Adapun orang-orang yang celaka, maka (tempatnya) di dalam neraka, di dalamnya mereka mengeluarkan dan menarik nafas (dengan merintih).<?php break;}
case 107:{?>Mereka kekal di dalamnya selama ada langit dan bumi, kecuali jika Tuhanmu menghendaki (yang lain). Sesungguhnya Tuhanmu Maha Pelaksana terhadap apa yang Dia kehendaki.<?php break;}
case 108:{?>Adapun orang-orang yang berbahagia, maka tempatnya di dalam surga mereka kekal di dalamnya selama ada langit dan bumi, kecuali jika Tuhanmu menghendaki (yang lain); sebagai karunia yang tiada putus-putusnya.<?php break;}
case 109:{?>Maka janganlah kamu berada dalam keragu-raguan tentang apa yang disembah oleh mereka. Mereka tidak menyembah melainkan sebagaimana nenek moyang mereka menyembah dahulu. Dan sesungguhnya Kami pasti akan menyempurnakan dengan secukup-cukupnya pembalasan (terhadap) mereka dengan tidak dikurangi sedikit pun.<?php break;}
case 110:{?>Dan sesungguhnya Kami telah memberikan Kitab (Taurat) kepada Musa, lalu diperselisihkan tentang Kitab itu. Dan seandainya tidak ada ketetapan yang telah terdahulu dari Tuhanmu, niscaya telah ditetapkan hukuman di antara mereka. Dan sesungguhnya mereka (orang-orang kafir Mekah) dalam keraguan yang menggelisahkan terhadap Al Qur'an.<?php break;}
case 111:{?>Dan sesungguhnya kepada masing-masing (mereka yang berselisih itu) pasti Tuhanmu akan menyempurnakan dengan cukup, (balasan) pekerjaan mereka. Sesungguhnya Dia Maha Mengetahui apa yang mereka kerjakan.<?php break;}
case 112:{?>Maka tetaplah kamu pada jalan yang benar, sebagaimana diperintahkan kepadamu dan (juga) orang yang telah tobat beserta kamu dan janganlah kamu melampaui batas. Sesungguhnya Dia Maha Melihat apa yang kamu kerjakan.<?php break;}
case 113:{?>Dan janganlah kamu cenderung kepada orang-orang yang zalim yang menyebabkan kamu disentuh api neraka, dan sekali-kali kamu tiada mempunyai seorang penolong pun selain daripada Allah, kemudian kamu tidak akan diberi pertolongan.<?php break;}
case 114:{?>Dan dirikanlah sembahyang itu pada kedua tepi siang (pagi dan petang) dan pada bahagian permulaan daripada malam. Sesungguhnya perbuatan-perbuatan yang baik itu menghapuskan (dosa) perbuatan-perbuatan yang buruk. Itulah peringatan bagi orang-orang yang ingat.<?php break;}
case 115:{?>Dan bersabarlah, karena sesungguhnya Allah tiada menyia-nyiakan pahala orang-orang yang berbuat kebaikan.<?php break;}
case 116:{?>Maka mengapa tidak ada dari umat-umat yang sebelum kamu orang-orang yang mempunyai keutamaan yang melarang daripada (mengerjakan) kerusakan di muka bumi, kecuali sebahagian kecil di antara orang-orang yang telah Kami selamatkan di antara mereka, dan orang-orang yang zalim hanya mementingkan kenikmatan yang mewah yang ada pada mereka, dan mereka adalah orang-orang yang berdosa.<?php break;}
case 117:{?>Dan Tuhanmu sekali-kali tidak akan membinasakan negeri-negeri secara zalim, sedang penduduknya orang-orang yang berbuat kebaikan.<?php break;}
case 118:{?>Jika Tuhanmu menghendaki, tentu Dia menjadikan manusia umat yang satu, tetapi mereka senantiasa berselisih pendapat.<?php break;}
case 119:{?>Kecuali orang-orang yang diberi rahmat oleh Tuhanmu. Dan untuk itulah Allah menciptakan mereka. Kalimat Tuhanmu (keputusan-Nya) telah ditetapkan: sesungguhnya Aku akan memenuhi Neraka Jahanam dengan jin dan manusia (yang durhaka) semuanya.<?php break;}
case 120:{?>Dan semua kisah dari rasul-rasul Kami ceritakan kepadamu, ialah kisah-kisah yang dengannya Kami teguhkan hatimu; dan dalam surat ini telah datang kepadamu kebenaran serta pengajaran dan peringatan bagi orang-orang yang beriman.<?php break;}
case 121:{?>Dan katakanlah kepada orang-orang yang tidak beriman: &quot;Berbuatlah menurut kemampuanmu; sesungguhnya kami-pun berbuat (pula).&quot;<?php break;}
case 122:{?>Dan tunggulah (akibat perbuatanmu); sesungguhnya kami pun menunggu (pula).&quot;<?php break;}
case 123:{?>Dan kepunyaan Allah-lah apa yang gaib di langit dan di bumi dan kepada-Nya-lah dikembalikan urusan-urusan semuanya, maka sembahlah Dia, dan bertawakallah kepada-Nya. Dan sekali-kali Tuhanmu tidak lalai dari apa yang kamu kerjakan.<?php break;}
}?>