<?php 
switch($verse){
case 1:{?>Alif, laam, raa. Ini adalah ayat-ayat kitab (Al Qur'an) yang nyata (dari Allah).<?php break;}
case 2:{?>Sesungguhnya Kami menurunkannya berupa Al Qur'an dengan berbahasa Arab, agar kamu memahaminya.<?php break;}
case 3:{?>Kami menceriterakan kepadamu kisah yang paling baik dengan mewahyukan Al Qur'an ini kepadamu, dan sesungguhnya kamu sebelum (Kami mewahyukan) nya adalah termasuk orang-orang yang belum mengetahui.<?php break;}
case 4:{?>(Ingatlah), ketika Yusuf berkata kepada ayahnya: &quot;Wahai ayahku, sesungguhnya aku bermimpi melihat sebelas bintang, matahari dan bulan; kulihat semuanya sujud kepadaku.&quot;<?php break;}
case 5:{?>Ayahnya berkata: &quot;Hai anakku, janganlah kamu ceritakan mimpimu itu kepada saudara-saudaramu, maka mereka membuat makar (untuk membinasakan) mu. Sesungguhnya setan itu adalah musuh yang nyata bagi manusia.&quot;<?php break;}
case 6:{?>Dan demikianlah Tuhanmu, memilih kamu (untuk menjadi Nabi) dan diajarkan-Nya kepadamu sebahagian dari takbir mimpi-mimpi dan disempurnakan-Nya nikmat-Nya kepadamu dan kepada keluarga Yakub, sebagaimana Dia telah menyempurnakan nikmat-Nya kepada dua orang bapakmu sebelum itu, (yaitu) Ibrahim dan Ishak. Sesungguhnya Tuhanmu Maha Mengetahui lagi Maha Bijaksana.<?php break;}
case 7:{?>Sesungguhnya ada beberapa tanda-tanda kekuasaan Allah pada (kisah) Yusuf dan saudara-saudaranya bagi orang-orang yang bertanya.<?php break;}
case 8:{?>(Yaitu) ketika mereka berkata: &quot;Sesungguhnya Yusuf dan saudara kandungnya (Bunyamin) lebih dicintai oleh ayah kita daripada kita sendiri, padahal kita (ini) adalah satu golongan (yang kuat). Sesungguhnya ayah kita adalah dalam kekeliruan yang nyata.<?php break;}
case 9:{?>Bunuhlah Yusuf atau buanglah dia ke suatu daerah (yang tak dikenal) supaya perhatian ayahmu tertumpah kepadamu saja, dan sesudah itu hendaklah kamu menjadi orang-orang yang baik.&quot;<?php break;}
case 10:{?>Seseorang di antara mereka berkata: &quot;Janganlah kamu bunuh Yusuf, tetapi masukkanlah dia ke dasar sumur supaya dia dipungut oleh beberapa orang musafir, jika kamu hendak berbuat.&quot;<?php break;}
case 11:{?>Mereka berkata: &quot;Wahai ayah kami, apa sebabnya kamu tidak mempercayai kami terhadap Yusuf, padahal sesungguhnya kami adalah orang-orang yang mengingini kebaikan baginya.<?php break;}
case 12:{?>Biarkanlah dia pergi bersama kami besok pagi, agar dia (dapat) bersenang-senang dan (dapat) bermain-main, dan sesungguhnya kami pasti menjaganya.&quot;<?php break;}
case 13:{?>Berkata Yakub; &quot;Sesungguhnya kepergian kamu bersama Yusuf amat menyedihkanku dan aku khawatir kalau-kalau dia dimakan serigala, sedang kamu lengah daripadanya.&quot;<?php break;}
case 14:{?>Mereka berkata: &quot;Jika ia benar-benar dimakan serigala, sedang kami golongan (yang kuat), sesungguhnya kami kalau demikian adalah orang-orang yang merugi.&quot;<?php break;}
case 15:{?>Maka tatkala mereka membawanya dan sepakat memasukkannya ke dasar sumur (lalu mereka masukkan dia), dan (di waktu dia sudah dalam sumur) kami wahyukan kepada Yusuf: &quot;Sesungguhnya kamu akan menceritakan kepada mereka perbuatan mereka ini, sedang mereka tiada ingat lagi.&quot;<?php break;}
case 16:{?>Kemudian mereka datang kepada ayah mereka di sore hari sambil menangis.<?php break;}
case 17:{?>Mereka berkata: &quot;Wahai ayah kami, sesungguhnya kami pergi berlomba-lomba dan kami tinggalkan Yusuf di dekat barang-barang kami, lalu dia dimakan serigala, dan kamu sekali-kali tidak akan percaya kepada kami, sekalipun kami adalah orang-orang yang benar.&quot;<?php break;}
case 18:{?>Mereka datang membawa baju gamisnya (yang berlumuran) dengan darah palsu. Ya'qub berkata: &quot;Sebenarnya dirimu sendirilah yang memandang baik perbuatan (yang buruk) itu; maka kesabaran yang baik itulah (kesabaranku). Dan Allah sajalah yang dimohon pertolongan-Nya terhadap apa yang kamu ceritakan.&quot;<?php break;}
case 19:{?>Kemudian datanglah kelompok orang-orang musafir, lalu mereka menyuruh seorang pengambil air, maka dia menurunkan timbanya dia berkata: &quot;Oh; kabar gembira, ini seorang anak muda!&quot; Kemudian mereka menyembunyikan dia sebagai barang dagangan. Dan Allah Maha Mengetahui apa yang mereka kerjakan.<?php break;}
case 20:{?>Dan mereka menjual Yusuf dengan harga yang murah, yaitu beberapa dirham saja, dan mereka merasa tidak tertarik hatinya kepada Yusuf.<?php break;}
case 21:{?>Dan orang Mesir yang membelinya berkata kepada istrinya: &quot;Berikanlah kepadanya tempat (dan layanan) yang baik, boleh jadi dia bermanfaat kepada kita atau kita pungut dia sebagai anak.&quot; Dan demikian pulalah Kami memberikan kedudukan yang baik kepada Yusuf di muka bumi (Mesir), dan agar Kami ajarkan kepadanya takbir mimpi. Dan Allah berkuasa terhadap urusan-Nya, tetapi kebanyakan manusia tiada mengetahuinya.<?php break;}
case 22:{?>Dan tatkala dia cukup dewasa, Kami berikan kepadanya hikmah dan ilmu. Demikianlah Kami memberi balasan kepada orang-orang yang berbuat baik.<?php break;}
case 23:{?>Dan wanita (Zulaikha) yang Yusuf tinggal di rumahnya menggoda Yusuf untuk menundukkan dirinya (kepadanya) dan dia menutup pintu-pintu, seraya berkata: &quot;Marilah ke sini.&quot; Yusuf berkata: &quot;Aku berlindung kepada Allah, sungguh tuanku telah memperlakukan aku dengan baik.&quot; Sesungguhnya orang-orang yang zalim tiada akan beruntung.<?php break;}
case 24:{?>Sesungguhnya wanita itu telah bermaksud (melakukan perbuatan itu) dengan Yusuf, dan Yusuf pun bermaksud (melakukan pula) dengan wanita itu andaikata dia tiada melihat tanda (dari) Tuhannya. Demikianlah, agar Kami memalingkan daripadanya kemungkaran dan kekejian. Sesungguhnya Yusuf itu termasuk hamba-hamba Kami yang terpilih.<?php break;}
case 25:{?>Dan keduanya berlomba-lomba menuju pintu dan wanita itu menarik baju gamis Yusuf dari belakang hingga koyak dan kedua-duanya mendapati suami wanita itu di muka pintu. Wanita itu berkata: &quot;Apakah pembalasan terhadap orang yang bermaksud berbuat serong dengan istrimu, selain dipenjarakan atau (dihukum) dengan azab yang pedih?&quot;<?php break;}
case 26:{?>Yusuf berkata: &quot;Dia menggodaku untuk menundukkan diriku (kepadanya)&quot;, dan seorang saksi dari keluarga wanita itu memberikan kesaksiannya: &quot;Jika baju gamisnya koyak di muka, maka wanita itu benar dan Yusuf termasuk orang-orang yang dusta.<?php break;}
case 27:{?>Dan jika baju gamisnya koyak di belakang, maka wanita itulah yang dusta, dan Yusuf termasuk orang-orang yang benar.&quot;<?php break;}
case 28:{?>Maka tatkala suami wanita itu melihat baju gamis Yusuf koyak di belakang berkatalah dia: &quot;Sesungguhnya (kejadian) itu adalah di antara tipu daya kamu, sesungguhnya tipu daya kamu adalah besar.&quot;<?php break;}
case 29:{?>(Hai) Yusuf: &quot;Berpalinglah dari ini dan (kamu hai istriku) mohon ampunlah atas dosamu itu, karena kamu sesungguhnya termasuk orang-orang yang berbuat salah.&quot;<?php break;}
case 30:{?>Dan wanita-wanita di kota berkata: &quot;Istri Al Aziz menggoda bujangnya untuk menundukkan dirinya (kepadanya), sesungguhnya cintanya kepada bujangnya itu adalah sangat mendalam. Sesungguhnya kami memandangnya dalam kesesatan yang nyata.&quot;<?php break;}
case 31:{?>Maka tatkala wanita itu (Zulaikha) mendengar cercaan mereka, diundangnyalah wanita-wanita itu dan disediakannya bagi mereka tempat duduk, dan diberikannya kepada masing-masing mereka sebuah pisau (untuk memotong jamuan), kemudian dia berkata (kepada Yusuf): &quot;Keluarlah (nampakkanlah dirimu) kepada mereka.&quot; Maka tatkala wanita-wanita itu melihatnya, mereka kagum kepada (keelokan rupa) nya dan mereka melukai (jari) tangannya dan berkata: &quot;Maha sempurna Allah, ini bukanlah manusia. Sesungguhnya ini tidak lain hanyalah malaikat yang mulia.&quot;<?php break;}
case 32:{?>Wanita itu berkata: &quot;Itulah dia orang yang kamu cela aku karena (tertarik) kepadanya, dan sesungguhnya aku telah menggoda dia untuk menundukkan dirinya (kepadaku) akan tetapi dia menolak. Dan sesungguhnya jika dia tidak menaati apa yang aku perintahkan kepadanya, niscaya dia akan dipenjarakan dan dia akan termasuk golongan orang-orang yang hina.&quot;<?php break;}
case 33:{?>Yusuf berkata: &quot;Wahai Tuhanku, penjara lebih aku sukai daripada memenuhi ajakan mereka kepadaku. Dan jika tidak Engkau hindarkan dari padaku tipu daya mereka, tentu aku akan cenderung untuk (memenuhi keinginan mereka) dan tentulah aku termasuk orang-orang yang bodoh.&quot;<?php break;}
case 34:{?>Maka Tuhannya memperkenankan doa Yusuf, dan Dia menghindarkan Yusuf dari tipu daya mereka. Sesungguhnya Dia-lah Yang Maha Mendengar lagi Maha Mengetahui.<?php break;}
case 35:{?>Kemudian timbul pikiran pada mereka setelah melihat tanda-tanda (kebenaran Yusuf) bahwa mereka harus memenjarakannya sampai sesuatu waktu.<?php break;}
case 36:{?>Dan bersama dengan dia masuk pula ke dalam penjara dua orang pemuda. Berkatalah salah seorang di antara keduanya: &quot;Sesungguhnya aku bermimpi, bahwa aku memeras anggur.&quot; Dan yang lainnya berkata: &quot;Sesungguhnya aku bermimpi, bahwa aku membawa roti di atas kepalaku, sebahagiannya dimakan burung.&quot; Berikanlah kepada kami takbirnya; sesungguhnya kami memandang kamu termasuk orang-orang yang pandai (menakbirkan mimpi).<?php break;}
case 37:{?>Yusuf berkata: Tidak disampaikan kepada kamu berdua makanan yang akan diberikan kepadamu melainkan aku telah dapat menerangkan jenis makanan itu, sebelum makanan itu sampai kepadamu. Yang demikian itu adalah sebagian dari apa yang diajarkan kepadaku oleh Tuhanku. Sesungguhnya aku telah meninggalkan agama orang-orang yang tidak beriman kepada Allah, sedang mereka ingkar kepada hari kemudian.<?php break;}
case 38:{?>Dan aku mengikut agama bapak-bapakku yaitu Ibrahim, Ishak dan Yakub. Tiadalah patut bagi kami (para Nabi) mempersekutukan sesuatu apa pun dengan Allah. Yang demikian itu adalah dari karunia Allah kepada kami dan kepada manusia (seluruhnya); tetapi kebanyakan manusia itu tidak mensyukuri (Nya).<?php break;}
case 39:{?>Hai kedua penghuni penjara, manakah yang baik, tuhan-tuhan yang bermacam-macam itu ataukah Allah Yang Maha Esa lagi Maha Perkasa?<?php break;}
case 40:{?>Kamu tidak menyembah yang selain Allah kecuali hanya (menyembah) nama-nama yang kamu dan nenek moyangmu membuat-buatnya. Allah tidak menurunkan suatu keterangan pun tentang nama-nama itu. Keputusan itu hanyalah kepunyaan Allah. Dia telah memerintahkan agar kamu tidak menyembah selain Dia. Itulah agama yang lurus, tetapi kebanyakan manusia tidak mengetahui.<?php break;}
case 41:{?>Hai kedua penghuni penjara, &quot;Adapun salah seorang di antara kamu berdua, akan memberi minum tuannya dengan khamar; adapun yang seorang lagi maka ia akan disalib, lalu burung memakan sebagian dari kepalanya. Telah diputuskan perkara yang kamu berdua menanyakannya (kepadaku).&quot;<?php break;}
case 42:{?>Dan Yusuf berkata kepada orang yang diketahuinya akan selamat di antara mereka berdua: &quot;Terangkanlah keadaanku kepada tuanmu.&quot; Maka setan menjadikan dia lupa menerangkan (keadaan Yusuf) kepada tuannya. Karena itu tetaplah dia (Yusuf) dalam penjara beberapa tahun lamanya.<?php break;}
case 43:{?>Raja berkata (kepada orang-orang terkemuka dari kaumnya): &quot;Sesungguhnya aku bermimpi melihat tujuh ekor sapi betina yang gemuk-gemuk dimakan oleh tujuh ekor sapi betina yang kurus-kurus dan tujuh bulir (gandum) yang hijau dan tujuh bulir lainnya yang kering.&quot; Hai orang-orang yang terkemuka: &quot;Terangkanlah kepadaku tentang takbir mimpiku itu jika kamu dapat menakbirkan mimpi.&quot;<?php break;}
case 44:{?>Mereka menjawab: &quot;(Itu) adalah mimpi-mimpi yang kosong dan kami sekali-kali tidak tahu menakbirkan mimpi itu.&quot;<?php break;}
case 45:{?>Dan berkatalah orang yang selamat di antara mereka berdua dan teringat (kepada Yusuf) sesudah beberapa waktu lamanya: &quot;Aku akan memberitakan kepadamu tentang (orang yang pandai) menakbirkan mimpi itu, maka utuslah aku (kepadanya).&quot;<?php break;}
case 46:{?>(Setelah pelayan itu berjumpa dengan Yusuf dia berseru): &quot;Yusuf, hai orang yang amat dipercaya, terangkanlah kepada kami tentang tujuh ekor sapi betina yang gemuk-gemuk yang dimakan oleh tujuh ekor sapi betina yang kurus-kurus dan tujuh bulir (gandum) yang hijau dan (tujuh) lainnya yang kering agar aku kembali kepada orang-orang itu, agar mereka mengetahuinya.&quot;<?php break;}
case 47:{?>Yusuf berkata: &quot;Supaya kamu bertanam tujuh tahun (lamanya) sebagaimana biasa; maka apa yang kamu tuai hendaklah kamu biarkan dibulirnya kecuali sedikit untuk kamu makan.<?php break;}
case 48:{?>Kemudian sesudah itu akan datang tujuh tahun yang amat sulit, yang menghabiskan apa yang kamu simpan untuk menghadapinya (tahun sulit), kecuali sedikit dari (bibit gandum) yang kamu simpan.<?php break;}
case 49:{?>Kemudian setelah itu akan datang tahun yang padanya manusia diberi hujan (dengan cukup) dan di masa itu mereka memeras anggur.&quot;<?php break;}
case 50:{?>Raja berkata: &quot;Bawalah dia kepadaku.&quot; Maka tatkala utusan itu datang kepada Yusuf, berkatalah Yusuf: &quot;Kembalilah kepada tuanmu dan tanyakanlah kepadanya bagaimana halnya wanita-wanita yang telah melukai tangannya. Sesungguhnya Tuhanku Maha Mengetahui tipu daya mereka.&quot;<?php break;}
case 51:{?>Raja berkata (kepada wanita-wanita itu): &quot;Bagaimana keadaanmu ketika kamu menggoda Yusuf untuk menundukkan dirinya (kepadamu)?&quot; Mereka berkata: Maha Sempurna Allah, kami tiada mengetahui sesuatu keburukan daripadanya. Berkata istri Al Aziz: &quot;Sekarang jelaslah kebenaran itu, akulah yang menggodanya untuk menundukkan dirinya (kepadaku), dan sesungguhnya dia termasuk orang-orang yang benar.&quot;<?php break;}
case 52:{?>(Yusuf berkata): &quot;Yang demikian itu agar dia (Al Aziz) mengetahui bahwa sesungguhnya aku tidak berkhianat kepadanya di belakangnya, dan bahwasanya Allah tidak meridai tipu daya orang-orang yang berkhianat.<?php break;}
case 53:{?>Dan aku tidak membebaskan diriku (dari kesalahan), karena sesungguhnya nafsu itu selalu menyuruh kepada kejahatan, kecuali nafsu yang diberi rahmat oleh Tuhanku. Sesungguhnya Tuhanku Maha Pengampun lagi Maha Penyayang.<?php break;}
case 54:{?>Dan raja berkata: &quot;Bawalah Yusuf kepadaku, agar aku memilih dia sebagai orang yang rapat kepadaku&quot;. Maka tatkala raja telah bercakap-cakap dengan dia, dia berkata: &quot;Sesungguhnya kamu (mulai) hari ini menjadi seorang yang berkedudukan tinggi lagi dipercaya pada sisi kami&quot;.<?php break;}
case 55:{?>Berkata Yusuf: &quot;Jadikanlah aku bendaharawan negara (Mesir); sesungguhnya aku adalah orang yang pandai menjaga, lagi berpengetahuan.&quot;<?php break;}
case 56:{?>Dan demikianlah Kami memberi kedudukan kepada Yusuf di negeri Mesir; (dia berkuasa penuh) pergi menuju ke mana saja yang ia kehendaki di bumi Mesir itu. Kami melimpahkan rahmat Kami kepada siapa yang Kami kehendaki dan Kami tidak menyia-nyiakan pahala orang-orang yang berbuat baik.<?php break;}
case 57:{?>Dan sesungguhnya pahala di akhirat itu lebih baik, bagi orang-orang yang beriman dan selalu bertakwa.<?php break;}
case 58:{?>Dan saudara-saudara Yusuf datang (ke Mesir) lalu mereka masuk ke (tempat) nya. Maka Yusuf mengenal mereka, sedang mereka tidak kenal (lagi) kepadanya.<?php break;}
case 59:{?>Dan tatkala Yusuf menyiapkan untuk mereka bahan makanannya, ia berkata: &quot;Bawalah kepadaku saudaramu yang se ayah dengan kamu (Bunyamin), tidakkah kamu melihat bahwa aku menyempurnakan sukatan dan aku adalah sebaik-baik penerima tamu?<?php break;}
case 60:{?>Jika kamu tidak membawanya kepadaku, maka kamu tidak akan mendapat sukatan lagi dari padaku dan jangan kamu mendekatiku&quot;.<?php break;}
case 61:{?>Mereka berkata: &quot;Kami akan membujuk ayahnya untuk membawanya (ke mari) dan sesungguhnya kami benar-benar akan melaksanakannya&quot;.<?php break;}
case 62:{?>Yusuf berkata kepada bujang-bujangnya: &quot;Masukkanlah barang-barang (penukar kepunyaan mereka) ke dalam karung-karung mereka, supaya mereka mengetahuinya apabila mereka telah kembali kepada keluarganya, mudah-mudahan mereka kembali lagi&quot;.<?php break;}
case 63:{?>Maka tatkala mereka telah kembali kepada ayah mereka (Yakub) mereka berkata: &quot;Wahai ayah kami, kami tidak akan mendapat sukatan (gandum) lagi, (jika tidak membawa saudara kami), sebab itu biarkanlah saudara kami pergi bersama-sama kami supaya kami mendapat sukatan, dan sesungguhnya kami benar-benar akan menjaganya&quot;.<?php break;}
case 64:{?>Berkata Yakub: &quot;Bagaimana aku akan mempercayakannya (Bunyamin) kepadamu, kecuali seperti aku telah mempercayakan saudaranya (Yusuf) kepada kamu dahulu?&quot;. Maka Allah adalah sebaik-baik Penjaga dan Dia adalah Maha Penyayang di antara para penyayang.<?php break;}
case 65:{?>Tatkala mereka membuka barang-barangnya, mereka menemukan kembali barang-barang (penukaran) mereka, dikembalikan kepada mereka. Mereka berkata: &quot;Wahai ayah kami apa lagi yang kita inginkan. Ini barang-barang kita, dikembalikan kepada kita, dan kami akan dapat memberi makan keluarga kami, dan kami akan dapat memelihara saudara kami, dan kami akan mendapat tambahan sukatan (gandum) seberat beban seekor unta. Itu adalah sukatan yang mudah (bagi raja Mesir)&quot;.<?php break;}
case 66:{?>Yakub berkata: &quot;Aku sekali-kali tidak akan melepaskannya (pergi) bersama-sama kamu, sebelum kamu memberikan kepadaku janji yang teguh atas nama Allah, bahwa kamu pasti akan membawanya kepadaku kembali, kecuali jika kamu dikepung musuh&quot;. Tatkala mereka memberikan janji mereka, maka Yakub berkata: &quot;Allah adalah saksi terhadap apa yang kita ucapkan (ini)&quot;.<?php break;}
case 67:{?>Dan Yakub berkata: &quot;Hai anak-anakku janganlah kamu (bersama-sama) masuk dari satu pintu gerbang, dan masuklah dari pintu-pintu gerbang yang berlain-lain; namun demikian aku tiada dapat melepaskan kamu barang sedikit pun daripada (takdir) Allah. Keputusan menetapkan (sesuatu) hanyalah hak Allah; kepada-Nya-lah aku bertawakal dan hendaklah kepada-Nya saja orang-orang yang bertawakal berserah diri&quot;.<?php break;}
case 68:{?>Dan tatkala mereka masuk menurut yang diperintahkan ayah mereka, maka (cara yang mereka lakukan itu) tiadalah melepaskan mereka sedikit pun dari takdir Allah, akan tetapi itu hanya suatu keinginan pada diri Yakub yang telah ditetapkannya. Dan sesungguhnya dia mempunyai pengetahuan, karena Kami telah mengajarkan kepadanya. Akan tetapi kebanyakan manusia tiada mengetahui.<?php break;}
case 69:{?>Dan tatkala mereka masuk ke (tempat) Yusuf, Yusuf membawa saudaranya (Bunyamin) ke tempatnya, Yusuf berkata: &quot;Sesungguhnya aku (ini) adalah saudaramu, maka janganlah kamu berdukacita terhadap apa yang telah mereka kerjakan&quot;.<?php break;}
case 70:{?>Maka tatkala telah disiapkan untuk mereka bahan makanan mereka, Yusuf memasukkan piala (tempat minum) ke dalam karung saudaranya. Kemudian berteriaklah seseorang yang menyerukan: &quot;Hai kafilah, sesungguhnya kamu adalah orang-orang yang mencuri&quot;.<?php break;}
case 71:{?>Mereka menjawab, sambil menghadap kepada penyeru-penyeru itu: &quot;Barang apakah yang hilang dari kamu?&quot;<?php break;}
case 72:{?>Penyeru-penyeru itu berkata: &quot;Kami kehilangan piala raja, dan siapa yang dapat mengembalikannya akan memperoleh bahan makanan (seberat) beban unta, dan aku menjamin terhadapnya&quot;.<?php break;}
case 73:{?>Saudara-saudara Yusuf menjawab: &quot;Demi Allah sesungguhnya kamu mengetahui bahwa kami datang bukan untuk membuat kerusakan di negeri (ini) dan kami bukanlah para pencuri&quot;.<?php break;}
case 74:{?>Mereka berkata: &quot;Tetapi apa balasannya jika kamu betul-betul pendusta?&quot;.<?php break;}
case 75:{?>Mereka menjawab: &quot;Balasannya, ialah pada siapa diketemukan (barang yang hilang) dalam karungnya, maka dia sendirilah balasannya (tebusannya) Demikianlah Kami memberi pembalasan kepada orang-orang yang zalim.&quot;<?php break;}
case 76:{?>Maka mulailah Yusuf (memeriksa) karung-karung mereka sebelum (memeriksa) karung saudaranya sendiri, kemudian dia mengeluarkan piala raja itu dari karung saudaranya. Demikianlah Kami atur untuk (mencapai maksud) Yusuf. Tiadalah patut Yusuf menghukum saudaranya menurut undang-undang raja, kecuali Allah menghendakinya. Kami tinggikan derajat orang yang Kami kehendaki: dan di atas tiap-tiap orang yang berpengetahuan itu ada lagi Yang Maha Mengetahui.<?php break;}
case 77:{?>Mereka berkata: &quot;Jika ia mencuri, maka sesungguhnya telah pernah mencuri pula saudaranya sebelum itu&quot;. Maka Yusuf menyembunyikan kejengkelan itu pada dirinya dan tidak menampakkannya kepada mereka. Dia berkata (dalam hatinya): &quot;Kamu lebih buruk kedudukanmu (sifat-sifatmu) dan Allah Maha Mengetahui apa yang kamu terangkan itu&quot;.<?php break;}
case 78:{?>Mereka berkata: &quot;Wahai Al Aziz, sesungguhnya ia mempunyai ayah yang sudah lanjut usianya, lantaran itu ambillah salah seorang di antara kami sebagai gantinya, sesungguhnya kami melihat kamu termasuk orang-orang yang berbuat baik&quot;.<?php break;}
case 79:{?>Berkata Yusuf: &quot;Aku mohon perlindungan kepada Allah daripada menahan seorang, kecuali orang yang kami ketemukan harta benda kami padanya, jika kami berbuat demikian, maka benar-benarlah kami orang-orang yang zalim&quot;.<?php break;}
case 80:{?>Maka tatkala mereka berputus asa daripada (putusan) Yusuf mereka menyendiri sambil berunding dengan berbisik-bisik. Berkatalah yang tertua di antara mereka: &quot;Tidakkah kamu ketahui bahwa sesungguhnya ayahmu telah mengambil janji dari kamu dengan nama Allah dan sebelum itu kamu telah menyia-nyiakan Yusuf. Sebab itu aku tidak akan meninggalkan negeri Mesir, sampai ayahku mengizinkan kepadaku (untuk kembali), atau Allah memberi keputusan terhadapku. Dan Dia adalah Hakim yang sebaik-baiknya&quot;.<?php break;}
case 81:{?>Kembalilah kepada ayahmu dan katakanlah: &quot;Wahai ayah kami! Sesungguhnya anakmu telah mencuri; dan kami hanya menyaksikan apa yang kami ketahui, dan sekali-kali kami tidak dapat menjaga (mengetahui) barang yang gaib.<?php break;}
case 82:{?>Dan tanyalah (penduduk) negeri yang kami berada di situ, dan kafilah yang kami datang bersamanya, dan sesungguhnya kami adalah orang-orang yang benar&quot;.<?php break;}
case 83:{?>Ya'qub berkata: &quot;Hanya dirimu sendirilah yang memandang baik perbuatan (yang buruk) itu. Maka kesabaran yang baik itulah (kesabaranku). Mudah-mudahan Allah mendatangkan mereka semuanya kepadaku; sesungguhnya Dia-lah Yang Maha Mengetahui lagi Maha Bijaksana&quot;.<?php break;}
case 84:{?>Dan Yakub berpaling dari mereka (anak-anaknya) seraya berkata: &quot;Aduhai duka citaku terhadap Yusuf&quot;, dan kedua matanya menjadi putih karena kesedihan dan dia adalah seorang yang menahan amarahnya (terhadap anak-anaknya).<?php break;}
case 85:{?>Mereka berkata: &quot;Demi Allah, senantiasa kamu mengingat Yusuf, sehingga kamu mengidapkan penyakit yang berat atau termasuk orang-orang yang binasa&quot;.<?php break;}
case 86:{?>Yakub menjawab: &quot;Sesungguhnya hanyalah kepada Allah aku mengadukan kesusahan dan kesedihanku, dan aku mengetahui dari Allah apa yang kamu tiada mengetahuinya.&quot;<?php break;}
case 87:{?>Hai anak-anakku, pergilah kamu, maka carilah berita tentang Yusuf dan saudaranya dan jangan kamu berputus asa dari rahmat Allah. Sesungguhnya tiada berputus asa dari rahmat Allah, melainkan kaum yang kafir&quot;.<?php break;}
case 88:{?>Maka ketika mereka masuk ke (tempat) Yusuf, mereka berkata: &quot;Hai Al Aziz, kami dan keluarga kami telah ditimpa kesengsaraan dan kami datang membawa barang-barang yang tak berharga, maka sempurnakanlah sukatan untuk kami, dan bersedekahlah kepada kami, sesungguhnya Allah memberi balasan kepada orang-orang yang bersedekah.&quot;<?php break;}
case 89:{?>Yusuf berkata: &quot;Apakah kamu mengetahui (kejelekan) apa yang telah kamu lakukan terhadap Yusuf dan saudaranya ketika kamu tidak mengetahui (akibat) perbuatanmu itu?&quot;.<?php break;}
case 90:{?>Mereka berkata: &quot;Apakah kamu ini benar-benar Yusuf?&quot; Yusuf menjawab: &quot;Akulah Yusuf dan ini saudaraku. Sesungguhnya Allah telah melimpahkan karunia-Nya kepada kami&quot;. Sesungguhnya barang siapa yang bertakwa dan bersabar, maka sesungguhnya Allah tidak menyia-nyiakan pahala orang-orang yang berbuat baik&quot;.<?php break;}
case 91:{?>Mereka berkata: &quot;Demi Allah, sesungguhnya Allah telah melebihkan kamu atas kami, dan sesungguhnya kami adalah orang-orang yang bersalah (berdosa)&quot;.<?php break;}
case 92:{?>Dia (Yusuf) berkata: &quot;Pada hari ini tak ada cercaan terhadap kamu, mudah-mudahan Allah mengampuni (kamu), dan Dia adalah Maha Penyayang di antara para penyayang.&quot;<?php break;}
case 93:{?>Pergilah kamu dengan membawa baju gamisku ini, lalu letakkanlah dia ke wajah ayahku, nanti ia akan melihat kembali; dan bawalah keluargamu semuanya kepadaku&quot;.<?php break;}
case 94:{?>Tatkala kafilah itu telah keluar (dari negeri Mesir) berkata ayah mereka: &quot;Sesungguhnya aku mencium bau Yusuf, sekiranya kamu tidak menuduhku lemah akal (tentu kamu membenarkan aku)&quot;.<?php break;}
case 95:{?>Keluarganya berkata: &quot;Demi Allah, sesungguhnya kamu masih dalam kekeliruanmu yang dahulu&quot;.<?php break;}
case 96:{?>Tatkala telah tiba pembawa kabar gembira itu, maka diletakkannya baju gamis itu ke wajah Yakub, lalu kembalilah dia dapat melihat. Berkata Yakub: &quot;Tidakkah aku katakan kepadamu, bahwa aku mengetahui dari Allah apa yang kamu tidak mengetahuinya&quot;.<?php break;}
case 97:{?>Mereka berkata: &quot;Wahai ayah kami, mohonkanlah ampun bagi kami terhadap dosa-dosa kami, sesungguhnya kami adalah orang-orang yang bersalah (berdosa)&quot;.<?php break;}
case 98:{?>Ya'qub berkata: &quot;Aku akan memohonkan ampun bagimu kepada Tuhanku. Sesungguhnya Dia-lah Yang Maha Pengampun lagi Maha Penyayang&quot;.<?php break;}
case 99:{?>Maka tatkala mereka masuk ke (tempat) Yusuf: Yusuf merangkul ibu bapanya dan dia berkata: &quot;Masuklah kamu ke negeri Mesir, insya Allah dalam keadaan aman&quot;.<?php break;}
case 100:{?>Dan ia menaikkan kedua ibu-bapaknya ke atas singgasana. Dan mereka (semuanya) merebahkan diri seraya sujud kepada Yusuf. Dan berkata Yusuf: &quot;Wahai ayahku inilah takbir mimpiku yang dahulu itu; sesungguhnya Tuhanku telah menjadikannya suatu kenyataan. Dan sesungguhnya Tuhanku telah berbuat baik kepadaku, ketika Dia membebaskan aku dari rumah penjara dan ketika membawa kamu dari dusun padang pasir, setelah setan merusakkan (hubungan) antaraku dan saudara-saudaraku. Sesungguhnya Tuhanku Maha Lembut terhadap apa yang Dia kehendaki. Sesungguhnya Dia-lah Yang Maha Mengetahui lagi Maha Bijaksana.<?php break;}
case 101:{?>Ya Tuhanku, sesungguhnya Engkau telah menganugerahkan kepadaku sebahagian kerajaan dan telah mengajarkan kepadaku sebahagian takbir mimpi. (Ya Tuhan). Pencipta langit dan bumi. Engkaulah Pelindungku di dunia dan di akhirat, wafatkanlah aku dalam keadaan Islam dan gabungkanlah aku dengan orang-orang yang saleh.<?php break;}
case 102:{?>Demikian itu (adalah) di antara berita-berita yang gaib yang Kami wahyukan kepadamu (Muhammad); padahal kamu tidak berada pada sisi mereka, ketika mereka memutuskan rencananya (untuk memasukkan Yusuf ke dalam sumur) dan mereka sedang mengatur tipu daya.<?php break;}
case 103:{?>Dan sebahagian besar manusia tidak akan beriman, walaupun kamu sangat menginginkannya.<?php break;}
case 104:{?>Dan kamu sekali-kali tidak meminta upah kepada mereka (terhadap seruanmu ini), itu tidak lain hanyalah pengajaran bagi semesta alam.<?php break;}
case 105:{?>Dan banyak sekali tanda-tanda (kekuasaan Allah) di langit dan di bumi yang mereka melaluinya, sedang mereka berpaling daripadanya.<?php break;}
case 106:{?>Dan sebahagian besar dari mereka tidak beriman kepada Allah, melainkan dalam keadaan mempersekutukan Allah (dengan sembahan-sembahan lain).<?php break;}
case 107:{?>Apakah mereka merasa aman dari kedatangan siksa Allah yang meliputi mereka, atau kedatangan kiamat kepada mereka secara mendadak, sedang mereka tidak menyadarinya?<?php break;}
case 108:{?>Katakanlah: &quot;Inilah jalan (agama) ku, aku dan orang-orang yang mengikutiku mengajak (kamu) kepada Allah dengan hujah yang nyata, Maha Suci Allah, dan aku tiada termasuk orang-orang yang musyrik&quot;.<?php break;}
case 109:{?>Kami tidak mengutus sebelum kamu, melainkan orang laki-laki yang Kami berikan wahyu kepadanya di antara penduduk negeri. Maka tidakkah mereka bepergian di muka bumi lalu melihat bagaimana kesudahan orang-orang sebelum mereka (yang mendustakan rasul) dan sesungguhnya kampung akhirat adalah lebih baik bagi orang-orang yang bertakwa. Maka tidakkah kamu memikirkannya?<?php break;}
case 110:{?>Sehingga apabila para rasul tidak mempunyai harapan lagi (tentang keimanan mereka) dan telah meyakini bahwa mereka telah didustakan, datanglah kepada para rasul itu pertolongan Kami, lalu diselamatkan orang-orang yang Kami kehendaki. Dan tidak dapat ditolak siksa Kami daripada orang-orang yang berdosa.<?php break;}
case 111:{?>Sesungguhnya pada kisah-kisah mereka itu terdapat pengajaran bagi orang-orang yang mempunyai akal. Al Qur'an itu bukanlah cerita yang dibuat-buat, akan tetapi membenarkan (kitab-kitab) yang sebelumnya dan menjelaskan segala sesuatu, dan sebagai petunjuk dan rahmat bagi kaum yang beriman.<?php break;}
}?>