<?php 
switch($verse){
case 1:{?>Telah pasti datangnya ketetapan Allah maka janganlah kamu meminta agar disegerakan (datang) nya. Maha Suci Allah dan Maha Tinggi dari apa yang mereka persekutukan.<?php break;}
case 2:{?>Dia menurunkan para malaikat dengan (membawa) wahyu dengan perintah-Nya kepada siapa yang Dia kehendaki di antara hamba-hamba-Nya, yaitu: &quot;Peringatkanlah olehmu sekalian, bahwasanya tidak ada Tuhan (yang hak) melainkan Aku, maka hendaklah kamu bertakwa kepada-Ku&quot;.<?php break;}
case 3:{?>Dia menciptakan langit dan bumi dengan hak. Maha Tinggi Allah daripada apa yang mereka persekutukan.<?php break;}
case 4:{?>Dia telah menciptakan manusia dari mani, tiba-tiba ia menjadi pembantah yang nyata.<?php break;}
case 5:{?>Dan Dia telah menciptakan binatang ternak untuk kamu; padanya ada (bulu) yang menghangatkan dan berbagai-bagai manfaat, dan sebagiannya kamu makan.<?php break;}
case 6:{?>Dan kamu memperoleh pandangan yang indah padanya, ketika kamu membawanya kembali ke kandang dan ketika kamu melepaskannya ke tempat penggembalaan.<?php break;}
case 7:{?>Dan ia memikul beban-bebanmu ke suatu negeri yang kamu tidak sanggup sampai kepadanya, melainkan dengan kesukaran-kesukaran (yang memayahkan) diri. Sesungguhnya Tuhanmu benar-benar Maha Pengasih lagi Maha Penyayang,<?php break;}
case 8:{?>dan (Dia telah menciptakan) kuda, bagal, dan keledai, agar kamu menungganginya dan (menjadikannya) perhiasan. Dan Allah menciptakan apa yang kamu tidak mengetahuinya.<?php break;}
case 9:{?>Dan hak bagi Allah (menerangkan) jalan yang lurus, dan di antara jalan-jalan ada yang bengkok. Dan jikalau Dia menghendaki, tentulah Dia memimpin kamu semuanya (kepada jalan yang benar).<?php break;}
case 10:{?>Dia-lah, Yang telah menurunkan air hujan dari langit untuk kamu, sebagiannya menjadi minuman dan sebagiannya (menyuburkan) tumbuh-tumbuhan, yang pada (tempat tumbuhnya) kamu menggembalakan ternakmu.<?php break;}
case 11:{?>Dia menumbuhkan bagi kamu dengan air hujan itu tanam-tanaman; zaitun, kurma, anggur dan segala macam buah-buahan. Sesungguhnya pada yang demikian itu benar-benar ada tanda (kekuasaan Allah) bagi kaum yang memikirkan.<?php break;}
case 12:{?>Dan Dia menundukkan malam dan siang, matahari dan bulan untukmu. Dan bintang-bintang itu ditundukkan (untukmu) dengan perintah-Nya. Sesungguhnya pada yang demikian itu benar-benar ada tanda-tanda (kekuasaan Allah) bagi kaum yang memahami (nya),<?php break;}
case 13:{?>dan Dia (menundukkan pula) apa yang Dia ciptakan untuk kamu di bumi ini dengan berlain-lainan macamnya. Sesungguhnya pada yang demikian itu benar-benar terdapat tanda (kekuasaan Allah) bagi kaum yang mengambil pelajaran.<?php break;}
case 14:{?>Dan Dia-lah, Allah yang menundukkan lautan (untukmu) agar kamu dapat memakan daripadanya daging yang segar (ikan), dan kamu mengeluarkan dari lautan itu perhiasan yang kamu pakai; dan kamu melihat bahtera berlayar padanya, dan supaya kamu mencari (keuntungan) dari karunia-Nya, dan supaya kamu bersyukur.<?php break;}
case 15:{?>Dan Dia menancapkan gunung-gunung di bumi supaya bumi itu tidak guncang bersama kamu, (dan Dia menciptakan) sungai-sungai dan jalan-jalan agar kamu mendapat petunjuk,<?php break;}
case 16:{?>dan (Dia ciptakan) tanda-tanda (penunjuk jalan). Dan dengan bintang-bintang itulah mereka mendapat petunjuk.<?php break;}
case 17:{?>Maka apakah (Allah) yang menciptakan itu sama dengan yang tidak dapat menciptakan (apa-apa)? Maka mengapa kamu tidak mengambil pelajaran.<?php break;}
case 18:{?>Dan jika kamu menghitung-hitung nikmat Allah, niscaya kamu tak dapat menentukan jumlahnya. Sesungguhnya Allah benar-benar Maha Pengampun lagi Maha Penyayang.<?php break;}
case 19:{?>Dan Allah mengetahui apa yang kamu rahasiakan dan apa yang kamu lahirkan.<?php break;}
case 20:{?>Dan berhala-berhala yang mereka seru selain Allah, tidak dapat membuat sesuatu apapun, sedang berhala-berhala itu (sendiri) dibuat orang.<?php break;}
case 21:{?>(Berhala-berhala itu) benda mati tidak hidup, dan berhala-berhala itu tidak mengetahui bilakah penyembah-penyembahnya akan dibangkitkan.<?php break;}
case 22:{?>Tuhan kamu adalah Tuhan Yang Maha Esa. Maka orang-orang yang tidak beriman kepada akhirat, hati mereka mengingkari (keesaan Allah), sedangkan mereka sendiri adalah orang-orang yang sombong.<?php break;}
case 23:{?>Tidak diragukan lagi bahwa sesungguhnya Allah mengetahui apa yang mereka rahasiakan dan apa yang mereka lahirkan. Sesungguhnya Allah tidak menyukai orang-orang yang sombong.<?php break;}
case 24:{?>Dan apabila dikatakan kepada mereka: &quot;Apakah yang telah diturunkan Tuhanmu?&quot; Mereka menjawab: &quot;Dongeng-dongengan orang-orang dahulu&quot;.<?php break;}
case 25:{?>(ucapan mereka) menyebabkan mereka memikul dosa-dosanya dengan sepenuh-penuhnya pada hari kiamat, dan sebahagian dosa-dosa orang yang mereka sesatkan yang tidak mengetahui sedikit pun (bahwa mereka disesatkan). Ingatlah, amat buruklah dosa yang mereka pikul itu.<?php break;}
case 26:{?>Sesungguhnya orang-orang yang sebelum mereka telah mengadakan makar, maka Allah menghancurkan rumah-rumah mereka dari fondasinya, lalu atap (rumah itu) jatuh menimpa mereka dari atas, dan datanglah azab itu kepada mereka dari tempat yang tidak mereka sadari.<?php break;}
case 27:{?>Kemudian Allah menghinakan mereka di hari kiamat, dan berfirman: &quot;Di manakah sekutu-sekutu-Ku itu (yang karena membelanya) kamu selalu memusuhi mereka (nabi-nabi dan orang-orang mukmin)?&quot; Berkatalah orang-orang yang telah diberi ilmu): &quot;Sesungguhnya kehinaan dan azab hari ini ditimpakan atas orang-orang yang kafir&quot;.<?php break;}
case 28:{?>(Yaitu) orang-orang yang dimatikan oleh para malaikat dalam keadaan berbuat lalim kepada diri mereka sendiri, lalu mereka menyerah diri (sambil berkata); &quot;Kami sekali-kali tidak mengerjakan sesuatu kejahatan pun&quot;. (Malaikat menjawab): &quot;Ada, sesungguhnya Allah Maha Mengetahui apa yang telah kamu kerjakan&quot;.<?php break;}
case 29:{?>Maka masukilah pintu-pintu neraka Jahanam, kamu kekal di dalamnya. Maka amat buruklah tempat orang-orang yang menyombongkan diri itu.<?php break;}
case 30:{?>Dan dikatakan kepada orang-orang yang bertakwa: &quot;Apakah yang telah diturunkan oleh Tuhanmu?&quot; Mereka menjawab: &quot;(Allah telah menurunkan) kebaikan&quot;. Orang-orang yang berbuat baik di dunia ini mendapat (pembalasan) yang baik. Dan sesungguhnya kampung akhirat adalah lebih baik dan itulah sebaik-baik tempat bagi orang yang bertakwa,<?php break;}
case 31:{?>(yaitu) surga Adn yang mereka masuk ke dalamnya, mengalir di bawahnya sungai-sungai, di dalam surga itu mereka mendapat segala apa yang mereka kehendaki. Demikianlah Allah memberi balasan kepada orang-orang yang bertakwa.<?php break;}
case 32:{?>(yaitu) orang-orang yang diwafatkan dalam keadaan baik oleh para malaikat dengan mengatakan (kepada mereka): &quot;Salaamun'alaikum, masuklah kamu ke dalam surga itu disebabkan apa yang telah kamu kerjakan&quot;.<?php break;}
case 33:{?>Tidak ada yang ditunggu-tunggu orang kafir selain dari datangnya para malaikat kepada mereka atau datangnya perintah Tuhanmu. Demikianlah yang telah diperbuat oleh orang-orang (kafir) sebelum mereka. Dan Allah tidak menganiaya mereka, akan tetapi merekalah yang selalu menganiaya diri mereka sendiri.<?php break;}
case 34:{?>Maka mereka ditimpa oleh (akibat) kejahatan perbuatan mereka dan mereka diliputi oleh azab yang selalu mereka perolok-olokkan.<?php break;}
case 35:{?>Dan berkatalah orang-orang musyrik: &quot;Jika Allah menghendaki, niscaya kami tidak akan menyembah sesuatu apa pun selain Dia, baik kami maupun bapak-bapak kami, dan tidak pula kami mengharamkan sesuatu pun tanpa (izin) -Nya&quot;. Demikianlah yang diperbuat orang-orang sebelum mereka; maka tidak ada kewajiban atas para rasul, selain dari menyampaikan (amanat Allah) dengan terang.<?php break;}
case 36:{?>Dan sesungguhnya Kami telah mengutus rasul pada tiap-tiap umat (untuk menyerukan): &quot;Sembahlah Allah (saja), dan jauhilah Thaghut itu&quot;, maka di antara umat itu ada orang-orang yang diberi petunjuk oleh Allah dan ada pula di antaranya orang-orang yang telah pasti kesesatan baginya. Maka berjalanlah kamu di muka bumi dan perhatikanlah bagaimana kesudahan orang-orang yang mendustakan (rasul-rasul).<?php break;}
case 37:{?>Jika kamu sangat mengharapkan agar mereka dapat petunjuk, maka sesungguhnya Allah tiada memberi petunjuk kepada orang yang disesatkan-Nya, dan sekali-kali mereka tiada mempunyai penolong.<?php break;}
case 38:{?>Mereka bersumpah dengan nama Allah dengan sumpahnya yang sungguh-sungguh: &quot;Allah tidak akan membangkitkan orang yang mati&quot;. (Tidak demikian), bahkan (pasti Allah akan membangkitkannya), sebagai suatu janji yang benar dari Allah, akan tetapi kebanyakan manusia tiada mengetahui.<?php break;}
case 39:{?>agar Allah menjelaskan kepada mereka apa yang mereka perselisihkan itu, dan agar orang-orang kafir itu mengetahui bahwasanya mereka adalah orang-orang yang berdusta.<?php break;}
case 40:{?>Sesungguhnya perkataan Kami terhadap sesuatu apabila Kami menghendakinya, Kami hanya mengatakan kepadanya: &quot;Kun (jadilah)&quot;, maka jadilah ia.<?php break;}
case 41:{?>Dan orang-orang yang berhijrah karena Allah sesudah mereka dianiaya, pasti Kami akan memberikan tempat yang bagus kepada mereka di dunia. Dan sesungguhnya pahala di akhirat adalah lebih besar, kalau mereka mengetahui,<?php break;}
case 42:{?>(yaitu) orang-orang yang sabar dan hanya kepada Tuhan saja mereka bertawakal.<?php break;}
case 43:{?>Dan Kami tidak mengutus sebelum kamu, kecuali orang-orang lelaki yang Kami beri wahyu kepada mereka; maka bertanyalah kepada orang yang mempunyai pengetahuan jika kamu tidak mengetahui,<?php break;}
case 44:{?>keterangan-keterangan (mukjizat) dan kitab-kitab. Dan Kami turunkan kepadamu Al Qur'an, agar kamu menerangkan kepada umat manusia apa yang telah diturunkan kepada mereka dan supaya mereka memikirkan,<?php break;}
case 45:{?>maka apakah orang-orang yang membuat makar yang jahat itu, merasa aman (dari bencana) ditenggelamkannya bumi oleh Allah bersama mereka, atau datangnya azab kepada mereka dari tempat yang tidak mereka sadari,<?php break;}
case 46:{?>atau Allah mengazab mereka di waktu mereka dalam perjalanan, maka sekali-kali mereka tidak dapat menolak (azab itu),<?php break;}
case 47:{?>atau Allah mengazab mereka dengan berangsur-angsur (sampai binasa). Maka sesungguhnya Tuhanmu adalah Maha Pengasih lagi Maha Penyayang.<?php break;}
case 48:{?>Dan apakah mereka tidak memperhatikan segala sesuatu yang telah diciptakan Allah yang bayangannya berbolak-balik ke kanan dan ke kiri dalam keadaan sujud kepada Allah, sedang mereka berendah diri?<?php break;}
case 49:{?>Dan kepada Allah sajalah bersujud segala apa yang berada di langit dan semua makhluk yang melata di bumi dan (juga) para malaikat, sedang mereka (malaikat) tidak menyombongkan diri.<?php break;}
case 50:{?>Mereka takut kepada Tuhan mereka yang di atas mereka dan melaksanakan apa yang diperintahkan (kepada mereka).<?php break;}
case 51:{?>Allah berfirman: &quot;Janganlah kamu menyembah dua tuhan; sesungguhnya Dia-lah Tuhan Yang Maha Esa, maka hendaklah kepada-Ku saja kamu takut&quot;.<?php break;}
case 52:{?>Dan kepunyaan-Nya-lah segala apa yang ada di langit dan di bumi, dan untuk-Nya-lah ketaatan itu selama-lamanya. Maka mengapa kamu bertakwa kepada selain Allah?<?php break;}
case 53:{?>Dan apa saja nikmat yang ada pada kamu, maka dari Allah-lah (datangnya), dan bila kamu ditimpa oleh kemudaratan, maka hanya kepada-Nya-lah kamu meminta pertolongan.<?php break;}
case 54:{?>Kemudian apabila Dia telah menghilangkan kemudaratan itu daripada kamu, tiba-tiba sebahagian daripada kamu mempersekutukan Tuhannya dengan (yang lain),<?php break;}
case 55:{?>biarlah mereka mengingkari nikmat yang telah Kami berikan kepada mereka; maka bersenang-senanglah kamu. Kelak kamu akan mengetahui (akibatnya).<?php break;}
case 56:{?>Dan mereka sediakan untuk berhala-berhala yang mereka tiada mengetahui (kekuasaannya), satu bahagian dari rezeki yang telah Kami berikan kepada mereka. Demi Allah, sesungguhnya kamu akan ditanyai tentang apa yang telah kamu ada-adakan.<?php break;}
case 57:{?>Dan mereka menetapkan bagi Allah anak-anak perempuan. Maha Suci Allah, sedang untuk mereka sendiri (mereka tetapkan) apa yang mereka sukai (yaitu anak-anak laki-laki).<?php break;}
case 58:{?>Dan apabila seseorang dari mereka diberi kabar dengan (kelahiran) anak perempuan, hitamlah (merah padamlah) mukanya, dan dia sangat marah.<?php break;}
case 59:{?>Ia menyembunyikan dirinya dari orang banyak, disebabkan buruknya berita yang disampaikan kepadanya. Apakah dia akan memeliharanya dengan menanggung kehinaan ataukah akan menguburkannya ke dalam tanah (hidup-hidup)? Ketahuilah, alangkah buruknya apa yang mereka tetapkan itu.<?php break;}
case 60:{?>Orang-orang yang tidak beriman kepada kehidupan akhirat, mempunyai sifat yang buruk; dan Allah mempunyai sifat yang Maha Tinggi; dan Dia-lah Yang Maha Perkasa lagi Maha Bijaksana.<?php break;}
case 61:{?>Jika Allah menghukum manusia karena kezalimannya, niscaya tidak akan ditinggalkan-Nya di muka bumi sesuatu pun dari makhluk yang melata, tetapi Allah menangguhkan mereka sampai kepada waktu yang ditentukan. Maka apabila telah tiba waktu (yang ditentukan) bagi mereka, tidaklah mereka dapat mengundurkannya barang sesaat pun dan tidak (pula) mendahulukannya.<?php break;}
case 62:{?>Dan mereka menetapkan bagi Allah apa yang mereka sendiri membencinya, dan lidah mereka mengucapkan kedustaan, yaitu bahwa sesungguhnya merekalah yang akan mendapat kebaikan. Tiadalah diragukan bahwa nerakalah bagi mereka, dan sesungguhnya mereka segera dimasukkan (ke dalamnya).<?php break;}
case 63:{?>Demi Allah, sesungguhnya Kami telah mengutus rasul-rasul Kami kepada umat-umat sebelum kamu, tetapi setan menjadikan umat-umat itu memandang baik perbuatan mereka (yang buruk), maka setan menjadi pemimpin mereka di hari itu dan bagi mereka azab yang sangat pedih.<?php break;}
case 64:{?>Dan Kami tidak menurunkan kepadamu Al Kitab (Al Qur'an) ini, melainkan agar kamu dapat menjelaskan kepada mereka apa yang mereka perselisihkan itu dan menjadi petunjuk dan rahmat bagi kaum yang beriman.<?php break;}
case 65:{?>Dan Allah menurunkan dari langit air (hujan) dan dengan air itu dihidupkan-Nya bumi sesudah matinya. Sesungguhnya pada yang demikian itu benar-benar terdapat tanda-tanda (kebesaran Tuhan) bagi orang-orang yang mendengarkan (pelajaran).<?php break;}
case 66:{?>Dan sesungguhnya pada binatang ternak itu benar-benar terdapat pelajaran bagi kamu. Kami memberimu minum daripada apa yang berada dalam perutnya (berupa) susu yang bersih antara tahi dan darah, yang mudah ditelan bagi orang-orang yang meminumnya.<?php break;}
case 67:{?>Dan dari buah kurma dan anggur, kamu buat minuman yang memabukkan dan rezeki yang baik. Sesungguhnya pada yang demikian itu benar-benar terdapat tanda (kebesaran Allah) bagi orang yang memikirkan.<?php break;}
case 68:{?>Dan Tuhanmu mewahyukan kepada lebah: &quot;Buatlah sarang-sarang di bukit-bukit, di pohon-pohon kayu, dan di tempat-tempat yang dibikin manusia&quot;.<?php break;}
case 69:{?>kemudian makanlah dari tiap-tiap (macam) buah-buahan dan tempuhlah jalan Tuhanmu yang telah dimudahkan (bagimu). Dari perut lebah itu keluar minuman (madu) yang bermacam-macam warnanya, di dalamnya terdapat obat yang menyembuhkan bagi manusia. Sesungguhnya pada yang demikian itu benar-benar terdapat tanda (kebesaran Tuhan) bagi orang-orang yang memikirkan.<?php break;}
case 70:{?>Allah menciptakan kamu, kemudian mewafatkan kamu; dan di antara kamu ada yang dikembalikan kepada umur yang paling lemah (pikun), supaya dia tidak mengetahui lagi sesuatu pun yang pernah diketahuinya. Sesungguhnya Allah Maha Mengetahui lagi Maha Kuasa.<?php break;}
case 71:{?>Dan Allah melebihkan sebahagian kamu dari sebahagian yang lain dalam hal rezeki, tetapi orang-orang yang dilebihkan (rezekinya itu) tidak mau memberikan rezeki mereka kepada budak-budak yang mereka miliki, agar mereka sama (merasakan) rezeki itu. Maka mengapa mereka mengingkari nikmat Allah?<?php break;}
case 72:{?>Allah menjadikan bagi kamu istri-istri dari jenis kamu sendiri dan menjadikan bagimu dari istri-istri kamu itu, anak anak dan cucu-cucu, dan memberimu rezeki dari yang baik-baik. Maka mengapakah mereka beriman kepada yang batil dan mengingkari nikmat Allah?&quot;<?php break;}
case 73:{?>Dan mereka menyembah selain Allah, sesuatu yang tidak dapat memberikan rezeki kepada mereka sedikit pun dari langit dan bumi, dan tidak berkuasa (sedikit jua pun).<?php break;}
case 74:{?>Maka janganlah kamu mengadakan sekutu-sekutu bagi Allah. Sesungguhnya Allah mengetahui, sedang kamu tidak mengetahui.<?php break;}
case 75:{?>Allah membuat perumpamaan dengan seorang hamba sahaya yang dimiliki yang tidak dapat bertindak terhadap sesuatu pun dan seorang yang Kami beri rezeki yang baik dari Kami, lalu dia menafkahkan sebagian dari rezeki itu secara sembunyi dan secara terang-terangan, adakah mereka itu sama? Segala puji hanya bagi Allah, tetapi kebanyakan mereka tiada mengetahui.<?php break;}
case 76:{?>Dan Allah membuat (pula) perumpamaan: dua orang lelaki yang seorang bisu, tidak dapat berbuat sesuatu pun dan dia menjadi beban atas penanggungnya, ke mana saja dia disuruh oleh penanggungnya itu, dia tidak dapat mendatangkan suatu kebajikan pun. Samakah orang itu dengan orang yang menyuruh berbuat keadilan, dan dia berada pula di atas jalan yang lurus?<?php break;}
case 77:{?>Dan kepunyaan Allah-lah segala apa yang tersembunyi di langit dan di bumi. Tidak adalah kejadian kiamat itu, melainkan seperti sekejap mata atau lebih cepat (lagi). Sesungguhnya Allah Maha Kuasa atas segala sesuatu.<?php break;}
case 78:{?>Dan Allah mengeluarkan kamu dari perut ibumu dalam keadaan tidak mengetahui sesuatu pun, dan Dia memberi kamu pendengaran, penglihatan dan hati, agar kamu bersyukur.<?php break;}
case 79:{?>Tidakkah mereka memperhatikan burung-burung yang dimudahkan terbang di angkasa bebas. Tidak ada yang menahannya selain daripada Allah. Sesungguhnya pada yang demikian itu benar-benar terdapat tanda-tanda (kebesaran Tuhan) bagi orang-orang yang beriman.<?php break;}
case 80:{?>Dan Allah menjadikan bagimu rumah-rumahmu sebagai tempat tinggal dan Dia menjadikan bagi kamu rumah-rumah (kemah-kemah) dari kulit binatang ternak yang kamu merasa ringan (membawa) nya di waktu kamu berjalan dan waktu kamu bermukim dan (dijadikan-Nya pula) dari bulu domba, bulu unta dan bulu kambing, alat-alat rumah tangga dan perhiasan (yang kamu pakai) sampai waktu (tertentu).<?php break;}
case 81:{?>Dan Allah menjadikan bagimu tempat bernaung dari apa yang telah Dia ciptakan, dan Dia jadikan bagimu tempat-tempat tinggal di gunung-gunung, dan Dia jadikan bagimu pakaian yang memeliharamu dari panas dan pakaian (baju besi) yang memelihara kamu dalam peperangan. Demikianlah Allah menyempurnakan nikmat-Nya atasmu agar kamu berserah diri (kepada-Nya).<?php break;}
case 82:{?>Jika mereka tetap berpaling, maka sesungguhnya kewajiban yang dibebankan atasmu (Muhammad) hanyalah menyampaikan (amanat Allah) dengan terang.<?php break;}
case 83:{?>Mereka mengetahui nikmat Allah, kemudian mereka mengingkarinya dan kebanyakan mereka adalah orang-orang yang kafir.<?php break;}
case 84:{?>Dan (ingatlah) akan hari (ketika) Kami bangkitkan dari tiap-tiap umat seorang saksi (rasul), kemudian tidak diizinkan kepada orang-orang yang kafir (untuk membela diri) dan tidak (pula) mereka dibolehkan meminta maaf.<?php break;}
case 85:{?>Dan apabila orang-orang lalim telah menyaksikan azab, maka tidaklah diringankan azab bagi mereka dan tidak pula mereka diberi tangguh.<?php break;}
case 86:{?>Dan apabila orang-orang yang mempersekutukan (Allah) melihat sekutu-sekutu mereka, mereka berkata: &quot;Ya Tuhan kami mereka inilah sekutu-sekutu kami yang dahulu kami sembah selain dari Engkau&quot;. Lalu sekutu-sekutu mereka mengatakan kepada mereka: &quot;Sesungguhnya kamu benar-benar orang-orang yang dusta&quot;.<?php break;}
case 87:{?>Dan mereka menyatakan ketundukannya kepada Allah pada hari itu dan hilanglah dari mereka apa yang selalu mereka ada-adakan.<?php break;}
case 88:{?>Orang-orang yang kafir dan menghalangi (manusia) dari jalan Allah, Kami tambahkan kepada mereka siksaan di atas siksaan disebabkan mereka selalu berbuat kerusakan.<?php break;}
case 89:{?>(Dan ingatlah) akan hari (ketika) Kami, bangkitkan pada tiap-tiap umat seorang saksi atas mereka dari mereka sendiri, dan Kami datangkan kamu (Muhammad) menjadi saksi atas seluruh umat manusia. Dan Kami turunkan kepadamu Al Kitab (Al Qur'an) untuk menjelaskan segala sesuatu dan petunjuk serta rahmat dan kabar gembira bagi orang-orang yang berserah diri.<?php break;}
case 90:{?>Sesungguhnya Allah menyuruh (kamu) berlaku adil dan berbuat kebajikan, memberi kepada kaum kerabat, dan Allah melarang dari perbuatan keji, kemungkaran dan permusuhan. Dia memberi pengajaran kepadamu agar kamu dapat mengambil pelajaran.<?php break;}
case 91:{?>Dan tepatilah perjanjian dengan Allah apabila kamu berjanji dan janganlah kamu membatalkan sumpah-sumpah (mu) itu, sesudah meneguhkannya, sedang kamu telah menjadikan Allah sebagai saksimu (terhadap sumpah-sumpah itu). Sesungguhnya Allah mengetahui apa yang kamu perbuat.<?php break;}
case 92:{?>Dan janganlah kamu seperti seorang perempuan yang menguraikan benangnya yang sudah dipintal dengan kuat, menjadi cerai berai kembali, kamu menjadikan sumpah (perjanjian) mu sebagai alat penipu di antaramu, disebabkan adanya satu golongan yang lebih banyak jumlahnya dari golongan yang lain. Sesungguhnya Allah hanya menguji kamu dengan hal itu. Dan sesungguhnya di hari kiamat akan dijelaskan-Nya kepadamu apa yang dahulu kamu perselisihkan itu.<?php break;}
case 93:{?>Dan kalau Allah menghendaki, niscaya Dia menjadikan kamu satu umat (saja), tetapi Allah menyesatkan siapa yang dikehendaki-Nya dan memberi petunjuk kepada siapa yang dikehendaki-Nya. Dan sesungguhnya kamu akan ditanya tentang apa yang telah kamu kerjakan.<?php break;}
case 94:{?>Dan janganlah kamu jadikan sumpah-sumpahmu sebagai alat penipu di antaramu, yang menyebabkan tergelincir kaki (mu) sesudah kokoh tegaknya, dan kamu rasakan kemelaratan (di dunia) karena kamu menghalangi (manusia) dari jalan Allah: dan bagimu azab yang besar.<?php break;}
case 95:{?>Dan janganlah kamu tukar perjanjianmu dengan Allah dengan harga yang sedikit (murah), sesungguhnya apa yang ada di sisi Allah, itulah yang lebih baik bagimu jika kamu mengetahui.<?php break;}
case 96:{?>Apa yang di sisimu akan lenyap, dan apa yang ada di sisi Allah adalah kekal. Dan sesungguhnya Kami akan memberi balasan kepada orang-orang yang sabar dengan pahala yang lebih baik dari apa yang telah mereka kerjakan.<?php break;}
case 97:{?>Barang siapa yang mengerjakan amal saleh, baik laki-laki maupun perempuan dalam keadaan beriman, maka sesungguhnya akan Kami berikan kepadanya kehidupan yang baik dan sesungguhnya akan Kami beri balasan kepada mereka dengan pahala yang lebih baik dari apa yang telah mereka kerjakan.<?php break;}
case 98:{?>Apabila kamu membaca Al Qur'an, hendaklah kamu meminta perlindungan kepada Allah dari setan yang terkutuk.<?php break;}
case 99:{?>Sesungguhnya setan ini tidak ada kekuasaannya atas orang-orang yang beriman dan bertawakal kepada Tuhannya.<?php break;}
case 100:{?>Sesungguhnya kekuasaannya (setan) hanyalah atas orang-orang yang mengambilnya jadi pemimpin dan atas orang-orang yang mempersekutukannya dengan Allah.<?php break;}
case 101:{?>Dan apabila Kami letakkan suatu ayat di tempat ayat yang lain sebagai penggantinya padahal Allah lebih mengetahui apa yang diturunkan-Nya, mereka berkata: &quot;Sesungguhnya kamu adalah orang yang mengada-adakan saja&quot;. Bahkan kebanyakan mereka tiada mengetahui.<?php break;}
case 102:{?>Katakanlah: &quot;Ruhul Qudus (Jibril) menurunkan Al Qur'an itu dari Tuhanmu dengan benar, untuk meneguhkan (hati) orang-orang yang telah beriman, dan menjadi petunjuk serta kabar gembira bagi orang-orang yang berserah diri (kepada Allah)&quot;.<?php break;}
case 103:{?>Dan sesungguhnya Kami mengetahui bahwa mereka berkata: &quot;Sesungguhnya Al Qur'an itu diajarkan oleh seorang manusia kepadanya (Muhammad)&quot;. Padahal bahasa orang yang mereka tuduhkan (bahwa) Muhammad belajar kepadanya bahasa Ajam, sedang Al Qur'an adalah dalam bahasa Arab yang terang.<?php break;}
case 104:{?>Sesungguhnya orang-orang yang tidak beriman kepada ayat-ayat Allah (Al Qur'an) Allah tidak akan memberi petunjuk kepada mereka dan bagi mereka azab yang pedih.<?php break;}
case 105:{?>Sesungguhnya yang mengada-adakan kebohongan, hanyalah orang-orang yang tidak beriman kepada ayat-ayat Allah, dan mereka itulah orang-orang pendusta.<?php break;}
case 106:{?>Barang siapa yang kafir kepada Allah sesudah dia beriman (dia mendapat kemurkaan Allah), kecuali orang yang dipaksa kafir padahal hatinya tetap tenang dalam beriman (dia tidak berdosa), akan tetapi orang yang melapangkan dadanya untuk kekafiran, maka kemurkaan Allah menimpanya dan baginya azab yang besar.<?php break;}
case 107:{?>Yang demikian itu disebabkan karena sesungguhnya mereka mencintai kehidupan di dunia lebih dari akhirat, dan bahwasanya Allah tiada memberi petunjuk kepada kaum yang kafir.<?php break;}
case 108:{?>Mereka itulah orang-orang yang hati, pendengaran dan penglihatannya telah dikunci mati oleh Allah dan mereka itulah orang-orang yang lalai.<?php break;}
case 109:{?>Pastilah bahwa mereka di akhirat nanti adalah orang-orang yang merugi.<?php break;}
case 110:{?>Dan sesungguhnya Tuhanmu (pelindung) bagi orang-orang yang berhijrah sesudah menderita cobaan, kemudian mereka berjihad dan sabar; sesungguhnya Tuhanmu sesudah itu benar-benar Maha Pengampun lagi Maha Penyayang.<?php break;}
case 111:{?>(Ingatlah) suatu hari (ketika) tiap-tiap diri datang untuk membela dirinya sendiri dan bagi tiap-tiap diri disempurnakan (balasan) apa yang telah dikerjakannya, sedang mereka tidak dianiaya (dirugikan).<?php break;}
case 112:{?>Dan Allah telah membuat suatu perumpamaan (dengan) sebuah negeri yang dahulunya aman lagi tenteram, rezekinya datang kepadanya melimpah ruah dari segenap tempat, tetapi (penduduk) nya mengingkari nikmat-nikmat Allah; karena itu Allah merasakan kepada mereka pakaian kelaparan dan ketakutan, disebabkan apa yang selalu mereka perbuat.<?php break;}
case 113:{?>Dan sesungguhnya telah datang kepada mereka seorang rasul dari mereka sendiri tetapi mereka mendustakannya; karena itu mereka dimusnahkan azab dan mereka adalah orang-orang yang zalim.<?php break;}
case 114:{?>Maka makanlah yang halal lagi baik dari rezeki yang telah diberikan Allah kepadamu; dan syukurilah nikmat Allah jika kamu hanya kepada-Nya saja menyembah.<?php break;}
case 115:{?>Sesungguhnya Allah hanya mengharamkan atasmu (memakan) bangkai, darah, daging babi dan apa yang disembelih dengan menyebut nama selain Allah; tetapi barang siapa yang terpaksa memakannya dengan tidak menganiaya dan tidak pula melampaui batas, maka sesungguhnya Allah Maha Pengampun lagi Maha Penyayang.<?php break;}
case 116:{?>Dan janganlah kamu mengatakan terhadap apa yang disebut-sebut oleh lidahmu secara dusta &quot;Ini halal dan ini haram&quot;, untuk mengada-adakan kebohongan terhadap Allah. Sesungguhnya orang-orang yang mengada-adakan kebohongan terhadap Allah tiadalah beruntung.<?php break;}
case 117:{?>(Itu adalah) kesenangan yang sedikit; dan bagi mereka azab yang pedih.<?php break;}
case 118:{?>Dan terhadap orang-orang Yahudi, Kami haramkan apa yang telah Kami ceritakan dahulu kepadamu; dan Kami tiada menganiaya mereka, akan tetapi merekalah yang menganiaya diri mereka sendiri.<?php break;}
case 119:{?>Kemudian, sesungguhnya Tuhanmu (mengampuni) bagi orang-orang yang mengerjakan kesalahan karena kebodohannya, kemudian mereka bertobat sesudah itu dan memperbaiki (dirinya); sesungguhnya Tuhanmu sesudah itu benar-benar Maha Pengampun lagi Maha Penyayang.<?php break;}
case 120:{?>Sesungguhnya Ibrahim adalah seorang imam yang dapat dijadikan teladan lagi patuh kepada Allah dan hanif. Dan sekali-kali bukanlah dia termasuk orang-orang yang mempersekutukan (Tuhan),<?php break;}
case 121:{?>(lagi) yang mensyukuri nikmat-nikmat Allah, Allah telah memilihnya dan menunjukinya kepada jalan yang lurus.<?php break;}
case 122:{?>Dan Kami berikan kepadanya kebaikan di dunia. Dan sesungguhnya dia di akhirat benar-benar termasuk orang-orang yang saleh.<?php break;}
case 123:{?>Kemudian Kami wahyukan kepadamu (Muhammad): &quot;Ikutilah agama Ibrahim seorang yang hanif.&quot; dan bukanlah dia termasuk orang-orang yang mempersekutukan Tuhan.<?php break;}
case 124:{?>Sesungguhnya diwajibkan (menghormati) hari Sabtu atas orang-orang (Yahudi) yang berselisih padanya. Dan sesungguhnya Tuhanmu benar-benar akan memberi putusan di antara mereka di hari kiamat terhadap apa yang telah mereka perselisihkan itu.<?php break;}
case 125:{?>Serulah (manusia) kepada jalan Tuhanmu dengan hikmah dan pelajaran yang baik dan bantahlah mereka dengan cara yang baik. Sesungguhnya Tuhanmu Dialah yang lebih mengetahui tentang siapa yang tersesat dari jalan-Nya dan Dialah yang lebih mengetahui orang-orang yang mendapat petunjuk.<?php break;}
case 126:{?>Dan jika kamu memberikan balasan, maka balaslah dengan balasan yang sama dengan siksaan yang ditimpakan kepadamu. Akan tetapi jika kamu bersabar, sesungguhnya itulah yang lebih baik bagi orang-orang yang sabar.<?php break;}
case 127:{?>Bersabarlah (hai Muhammad) dan tiadalah kesabaranmu itu melainkan dengan pertolongan Allah dan janganlah kamu bersedih hati terhadap (kekafiran) mereka dan janganlah kamu bersempit dada terhadap apa yang mereka tipu dayakan.<?php break;}
case 128:{?>Sesungguhnya Allah beserta orang-orang yang bertakwa dan orang-orang yang berbuat kebaikan.<?php break;}
}?>