<?php 
switch($verse){
case 1:{?>Maha Suci Allah, yang telah memperjalankan hamba-Nya pada suatu malam dari Al Masjidilharam ke Al Masjidilaksa yang telah Kami berkahi sekelilingnya agar Kami perlihatkan kepadanya sebagian dari tanda-tanda (kebesaran) Kami. Sesungguhnya Dia adalah Maha Mendengar lagi Maha Melihat.<?php break;}
case 2:{?>Dan Kami berikan kepada Musa kitab (Taurat) dan Kami jadikan kitab Taurat itu petunjuk bagi Bani Israel (dengan firman): &quot;Janganlah kamu mengambil penolong selain Aku,<?php break;}
case 3:{?>(yaitu) anak cucu dari orang-orang yang Kami bawa bersama-sama Nuh. Sesungguhnya dia adalah hamba (Allah) yang banyak bersyukur.<?php break;}
case 4:{?>Dan telah Kami tetapkan terhadap Bani Israel dalam kitab itu: &quot;Sesungguhnya kamu akan membuat kerusakan di muka bumi ini dua kali dan pasti kamu akan menyombongkan diri dengan kesombongan yang besar.&quot;<?php break;}
case 5:{?>Maka apabila datang saat hukuman bagi (kejahatan) pertama dari kedua (kejahatan) itu, Kami datangkan kepadamu hamba-hamba Kami yang mempunyai kekuatan yang besar, lalu mereka merajalela di kampung-kampung, dan itulah ketetapan yang pasti terlaksana.<?php break;}
case 6:{?>Kemudian Kami berikan kepadamu giliran untuk mengalahkan mereka kembali dan Kami membantumu dengan harta kekayaan dan anak-anak dan Kami jadikan kamu kelompok yang lebih besar.<?php break;}
case 7:{?>Jika kamu berbuat baik (berarti) kamu berbuat baik bagi dirimu sendiri dan jika kamu berbuat jahat maka kejahatan itu bagi dirimu sendiri, dan apabila datang saat hukuman bagi (kejahatan) yang kedua, (Kami datangkan orang-orang lain) untuk menyuramkan muka-muka kamu dan mereka masuk ke dalam mesjid, sebagaimana musuh-musuhmu memasukinya pada kali pertama dan untuk membinasakan sehabis-habisnya apa saja yang mereka kuasai.<?php break;}
case 8:{?>Mudah-mudahan Tuhanmu akan melimpahkan rahmat (Nya) kepadamu; dan sekiranya kamu kembali kepada (kedurhakaan), niscaya Kami kembali (mengazabmu) dan Kami jadikan neraka Jahanam penjara bagi orang-orang yang tidak beriman.<?php break;}
case 9:{?>Sesungguhnya Al Qur'an ini memberikan petunjuk kepada (jalan) yang lebih lurus dan memberi kabar gembira kepada orang-orang Mukmin yang mengerjakan amal saleh bahwa bagi mereka ada pahala yang besar,<?php break;}
case 10:{?>dan sesungguhnya orang-orang yang tidak beriman kepada kehidupan akhirat, Kami sediakan bagi mereka azab yang pedih.<?php break;}
case 11:{?>Dan manusia berdoa untuk kejahatan sebagaimana ia berdoa untuk kebaikan. Dan adalah manusia bersifat tergesa-gesa.<?php break;}
case 12:{?>Dan Kami jadikan malam dan siang sebagai dua tanda, lalu Kami hapuskan tanda malam dan Kami jadikan tanda siang itu terang, agar kamu mencari karunia dari Tuhanmu, dan supaya kamu mengetahui bilangan tahun-tahun dan perhitungan. Dan segala sesuatu telah Kami terangkan dengan jelas.<?php break;}
case 13:{?>Dan tiap-tiap manusia itu telah Kami tetapkan amal perbuatannya (sebagaimana tetapnya kalung) pada lehernya. Dan Kami keluarkan baginya pada hari kiamat sebuah kitab yang dijumpainya terbuka.<?php break;}
case 14:{?>&quot;Bacalah kitabmu, cukuplah dirimu sendiri pada waktu ini sebagai penghisab terhadapmu.&quot;<?php break;}
case 15:{?>Barang siapa yang berbuat sesuai dengan hidayah (Allah), maka sesungguhnya dia berbuat itu untuk (keselamatan) dirinya sendiri; dan barang siapa yang sesat maka sesungguhnya dia tersesat bagi (kerugian) dirinya sendiri. Dan seorang yang berdosa tidak dapat memikul dosa orang lain, dan Kami tidak akan mengazab sebelum Kami mengutus seorang rasul.<?php break;}
case 16:{?>Dan jika Kami hendak membinasakan suatu negeri, maka Kami perintahkan kepada orang-orang yang hidup mewah di negeri itu (supaya menaati Allah) tetapi mereka melakukan kedurhakaan dalam negeri itu, maka sudah sepantasnya berlaku terhadapnya perkataan (ketentuan Kami), kemudian Kami hancurkan negeri itu sehancur-hancurnya.<?php break;}
case 17:{?>Dan berapa banyaknya kaum sesudah Nuh telah Kami binasakan. Dan cukuplah Tuhanmu Maha Mengetahui lagi Maha Melihat dosa hamba-hamba-Nya.<?php break;}
case 18:{?>Barang siapa menghendaki kehidupan sekarang (duniawi), maka Kami segerakan baginya di dunia itu apa yang Kami kehendaki bagi orang yang Kami kehendaki dan Kami tentukan baginya neraka Jahanam; ia akan memasukinya dalam keadaan tercela dan terusir.<?php break;}
case 19:{?>Dan barang siapa yang menghendaki kehidupan akhirat dan berusaha ke arah itu dengan sungguh-sungguh sedang ia adalah mukmin, maka mereka itu adalah orang-orang yang usahanya dibalas dengan baik.<?php break;}
case 20:{?>Kepada masing-masing golongan baik golongan ini maupun golongan itu Kami berikan bantuan dari kemurahan Tuhanmu. Dan kemurahan Tuhanmu tidak dapat dihalangi.<?php break;}
case 21:{?>Perhatikanlah bagaimana Kami lebihkan sebagian dari mereka atas sebagian (yang lain). Dan pasti kehidupan akhirat lebih tinggi tingkatnya dan lebih besar keutamaannya.<?php break;}
case 22:{?>Janganlah kamu adakan tuhan yang lain di samping Allah, agar kamu tidak menjadi tercela dan tidak ditinggalkan (Allah).<?php break;}
case 23:{?>Dan Tuhanmu telah memerintahkan supaya kamu jangan menyembah selain Dia dan hendaklah kamu berbuat baik pada ibu bapakmu dengan sebaik-baiknya. Jika salah seorang di antara keduanya atau kedua-duanya sampai berumur lanjut dalam pemeliharaanmu, maka sekali-kali janganlah kamu mengatakan kepada keduanya perkataan &quot;ah&quot; dan janganlah kamu membentak mereka dan ucapkanlah kepada mereka perkataan yang mulia.<?php break;}
case 24:{?>Dan rendahkanlah dirimu terhadap mereka berdua dengan penuh kesayangan dan ucapkanlah: &quot;Wahai Tuhanku, kasihilah mereka keduanya, sebagaimana mereka berdua telah mendidik aku waktu kecil&quot;.<?php break;}
case 25:{?>Tuhanmu lebih mengetahui apa yang ada dalam hatimu; jika kamu orang-orang yang baik, maka sesungguhnya Dia Maha Pengampun bagi orang-orang yang bertobat.<?php break;}
case 26:{?>Dan berikanlah kepada keluarga-keluarga yang dekat akan haknya, kepada orang miskin dan orang yang dalam perjalanan; dan janganlah kamu menghambur-hamburkan (hartamu) secara boros.<?php break;}
case 27:{?>Sesungguhnya pemboros-pemboros itu adalah saudara-saudara setan dan setan itu adalah sangat ingkar kepada Tuhannya.<?php break;}
case 28:{?>Dan jika kamu berpaling dari mereka untuk memperoleh rahmat dari Tuhanmu yang kamu harapkan, maka katakanlah kepada mereka ucapan yang pantas.<?php break;}
case 29:{?>Dan janganlah kamu jadikan tanganmu terbelenggu pada lehermu dan janganlah kamu terlalu mengulurkannya karena itu kamu menjadi tercela dan menyesal.<?php break;}
case 30:{?>Sesungguhnya Tuhanmu melapangkan rezeki kepada siapa yang Dia kehendaki dan menyempitkannya; sesungguhnya Dia Maha Mengetahui lagi Maha Melihat akan hamba-hamba-Nya.<?php break;}
case 31:{?>Dan janganlah kamu membunuh anak-anakmu karena takut kemiskinan. Kami lah yang akan memberi rezeki kepada mereka dan juga kepadamu. Sesungguhnya membunuh mereka adalah suatu dosa yang besar.<?php break;}
case 32:{?>Dan janganlah kamu mendekati zina; sesungguhnya zina itu adalah suatu perbuatan yang keji dan suatu jalan yang buruk.<?php break;}
case 33:{?>Dan janganlah kamu membunuh jiwa yang diharamkan Allah (membunuhnya), melainkan dengan suatu (alasan) yang benar. Dan barang siapa dibunuh secara lalim, maka sesungguhnya Kami telah memberi kekuasaan kepada ahli warisnya, tetapi janganlah ahli waris itu melampaui batas dalam membunuh. Sesungguhnya ia adalah orang yang mendapat pertolongan.<?php break;}
case 34:{?>Dan janganlah kamu mendekati harta anak yatim, kecuali dengan cara yang lebih baik (bermanfaat) sampai ia dewasa dan penuhilah janji; sesungguhnya janji itu pasti diminta pertanggungan jawabnya.<?php break;}
case 35:{?>Dan sempurnakanlah takaran apabila kamu menakar dan timbanglah dengan neraca yang benar. Itulah yang lebih utama (bagimu) dan lebih baik akibatnya.<?php break;}
case 36:{?>Dan janganlah kamu mengikuti apa yang kamu tidak mempunyai pengetahuan tentangnya. Sesungguhnya pendengaran, penglihatan dan hati, semuanya itu akan diminta pertanggungan jawabnya.<?php break;}
case 37:{?>Dan janganlah kamu berjalan di muka bumi ini dengan sombong, karena sesungguhnya kamu sekali-kali tidak dapat menembus bumi dan sekali-kali kamu tidak akan sampai setinggi gunung.<?php break;}
case 38:{?>Semua itu kejahatannya amat dibenci di sisi Tuhanmu.<?php break;}
case 39:{?>Itulah sebagian hikmah yang diwahyukan Tuhan kepadamu. Dan janganlah kamu mengadakan tuhan yang lain di samping Allah, yang menyebabkan kamu dilemparkan ke dalam neraka dalam keadaan tercela lagi dijauhkan (dari rahmat Allah).<?php break;}
case 40:{?>Maka apakah patut Tuhan memilihkan bagimu anak-anak laki-laki sedang Dia sendiri mengambil anak-anak perempuan di antara para malaikat? Sesungguhnya kamu benar-benar mengucapkan kata-kata yang besar (dosanya).<?php break;}
case 41:{?>Dan sesungguhnya dalam Al Qur'an ini Kami telah ulang-ulangi (peringatan-peringatan), agar mereka selalu ingat. Dan ulangan peringatan itu tidak lain hanyalah menambah mereka lari (dari kebenaran).<?php break;}
case 42:{?>Katakanlah: &quot;Jika ada tuhan-tuhan di samping-Nya, sebagaimana yang mereka katakan, niscaya tuhan-tuhan itu mencari jalan kepada Tuhan yang mempunyai Arasy&quot;.<?php break;}
case 43:{?>Maha Suci dan Maha Tinggi Dia dari apa yang mereka katakan dengan ketinggian yang sebesar-besarnya.<?php break;}
case 44:{?>Langit yang tujuh, bumi dan semua yang ada di dalamnya bertasbih kepada Allah. Dan tak ada suatu pun melainkan bertasbih dengan memuji-Nya, tetapi kamu sekalian tidak mengerti tasbih mereka. Sesungguhnya Dia adalah Maha Penyantun lagi Maha Pengampun.<?php break;}
case 45:{?>Dan apabila kamu membaca Al Qur'an niscaya Kami adakan antara kamu dan orang-orang yang tidak beriman kepada kehidupan akhirat, suatu dinding yang tertutup.<?php break;}
case 46:{?>dan Kami adakan tutupan di atas hati mereka dan sumbatan di telinga mereka, agar mereka tidak dapat memahaminya. Dan apabila kamu menyebut Tuhanmu saja dalam Al Qur'an, niscaya mereka berpaling ke belakang karena bencinya.<?php break;}
case 47:{?>Kami lebih mengetahui dalam keadaan bagaimana mereka mendengarkan sewaktu mereka mendengarkan kamu, dan sewaktu mereka berbisik-bisik (yaitu) ketika orang-orang lalim itu berkata: &quot;Kamu tidak lain hanyalah mengikuti seorang laki-laki yang kena sihir&quot;.<?php break;}
case 48:{?>Lihatlah bagaimana mereka membuat perumpamaan-perumpamaan terhadapmu; karena itu mereka menjadi sesat dan tidak dapat lagi menemukan jalan (yang benar).<?php break;}
case 49:{?>Dan mereka berkata: &quot;Apakah bila kami telah menjadi tulang belulang dan benda-benda yang hancur, apa benar-benarkah kami akan dibangkitkan kembali sebagai makhluk yang baru?&quot;<?php break;}
case 50:{?>Katakanlah: &quot;Jadilah kamu sekalian batu atau besi,<?php break;}
case 51:{?>atau suatu makhluk dari makhluk yang tidak mungkin (hidup) menurut pikiranmu&quot;. Maka mereka akan bertanya: &quot;Siapa yang akan menghidupkan kami kembali?&quot; Katakanlah: &quot;Yang telah menciptakan kamu pada kali yang pertama&quot;. Lalu mereka akan menggeleng-gelengkan kepala mereka kepadamu dan berkata, &quot;Kapan itu (akan terjadi)?&quot; Katakanlah: &quot;Mudah-mudahan waktu berbangkit itu dekat&quot;,<?php break;}
case 52:{?>yaitu pada hari Dia memanggil kamu, lalu kamu mematuhi-Nya sambil memuji-Nya dan kamu mengira, bahwa kamu tidak berdiam (di dalam kubur) kecuali sebentar saja.<?php break;}
case 53:{?>Dan katakanlah kepada hamba-hamba-Ku: &quot; Hendaklah mereka mengucapkan perkataan yang lebih baik (benar). Sesungguhnya setan itu menimbulkan perselisihan di antara mereka. Sesungguhnya setan itu adalah musuh yang nyata bagi manusia.<?php break;}
case 54:{?>Tuhanmu lebih mengetahui tentang kamu. Dia akan memberi rahmat kepadamu jika Dia menghendaki dan Dia akan mengazabmu, jika Dia menghendaki. Dan Kami tidaklah mengutusmu untuk menjadi penjaga bagi mereka.<?php break;}
case 55:{?>Dan Tuhanmu lebih mengetahui siapa yang (ada) di langit dan di bumi. Dan sesungguhnya telah Kami lebihkan sebagian nabi-nabi itu atas sebagian (yang lain), dan kami berikan Zabur (kepada) Daud.<?php break;}
case 56:{?>Katakanlah: &quot;Panggillah mereka yang kamu anggap (tuhan) selain Allah, maka mereka tidak akan mempunyai kekuasaan untuk menghilangkan bahaya dari padamu dan tidak pula memindahkannya&quot;.<?php break;}
case 57:{?>Orang-orang yang mereka seru itu, mereka sendiri mencari jalan kepada Tuhan mereka siapa di antara mereka yang lebih dekat (kepada Allah) dan mengharapkan rahmat-Nya dan takut akan azab-Nya; sesungguhnya azab Tuhanmu adalah suatu yang (harus) ditakuti.<?php break;}
case 58:{?>Tak ada suatu negeri pun (yang durhaka penduduknya), melainkan Kami membinasakannya sebelum hari kiamat atau Kami azab (penduduknya) dengan azab yang sangat keras. Yang demikian itu telah tertulis di dalam kitab (Lohmahfuz).<?php break;}
case 59:{?>Dan sekali-kali tidak ada yang menghalangi Kami untuk mengirimkan (kepadamu) tanda-tanda (kekuasaan Kami), melainkan karena tanda-tanda itu telah didustakan oleh orang-orang dahulu. Dan telah kami berikan kepada Tsamud unta betina itu (sebagai mukjizat) yang dapat dilihat, tetapi mereka menganiaya unta betina itu. Dan Kami tidak memberi tanda-tanda itu melainkan untuk menakuti.<?php break;}
case 60:{?>Dan (ingatlah), ketika Kami wahyukan kepadamu: &quot;Sesungguhnya (ilmu) Tuhanmu meliputi segala manusia&quot;. Dan Kami tidak menjadikan mimpi yang telah Kami perlihatkan kepadamu, melainkan sebagai ujian bagi manusia dan (begitu pula) pohon kayu yang terkutuk dalam Al Qur'an. Dan Kami menakut-nakuti mereka, tetapi yang demikian itu hanyalah menambah besar kedurhakaan mereka.<?php break;}
case 61:{?>Dan (ingatlah), tatkala Kami berfirman kepada para malaikat: &quot;Sujudlah kamu semua kepada Adam&quot;, lalu mereka sujud kecuali iblis. Dia berkata: &quot;Apakah aku akan sujud kepada orang yang Engkau ciptakan dari tanah?&quot;<?php break;}
case 62:{?>Dia (iblis) berkata: &quot;Terangkanlah kepadaku inikah orangnya yang Engkau muliakan atas diriku? Sesungguhnya jika Engkau memberi tangguh kepadaku sampai hari kiamat, niscaya benar-benar akan aku sesatkan keturunannya, kecuali sebahagian kecil&quot;.<?php break;}
case 63:{?>Tuhan berfirman: &quot;Pergilah, barang siapa di antara mereka yang mengikuti kamu, maka sesungguhnya neraka Jahanam adalah balasanmu semua, sebagai suatu pembalasan yang cukup.<?php break;}
case 64:{?>Dan hasunglah siapa yang kamu sanggupi di antara mereka dengan ajakanmu, dan kerahkanlah terhadap mereka pasukan berkuda dan pasukanmu yang berjalan kaki dan berserikatlah dengan mereka pada harta dan anak-anak dan beri janjilah mereka. Dan tidak ada yang dijanjikan oleh setan kepada mereka melainkan tipuan belaka.<?php break;}
case 65:{?>Sesungguhnya hamba-hamba-Ku, Kamu tidak dapat berkuasa atas mereka. Dan cukuplah Tuhan-mu sebagai Penjaga&quot;.<?php break;}
case 66:{?>Tuhan-mu adalah yang melayarkan kapal-Kapal di lautan untukmu, agar kamu mencari sebahagian dari karunia-Nya. Sesungguhnya Dia adalah Maha Penyayang terhadapmu.<?php break;}
case 67:{?>Dan apabila kamu ditimpa bahaya di lautan, niscaya hilanglah siapa yang kamu seru kecuali Dia. Maka tatkala Dia menyelamatkan Kamu ke daratan, kamu berpaling. Dan manusia adalah selalu tidak berterima kasih.<?php break;}
case 68:{?>Maka apakah kamu merasa aman (dari hukuman Tuhan) yang menjungkir balikkan sebagian daratan bersama kamu atau Dia meniupkan (angin keras yang membawa) batu-batu kecil? dan kamu tidak akan mendapat seorang pelindung pun bagi kamu,<?php break;}
case 69:{?>atau apakah kamu merasa aman dari dikembalikan-Nya kamu ke laut sekali lagi, lalu Dia meniupkan atas kamu angin taupan dan ditenggelamkan-Nya kamu disebabkan kekafiranmu. Dan kamu tidak akan mendapat seorang penolong pun dalam hal ini terhadap (siksaan) Kami.<?php break;}
case 70:{?>Dan sesungguhnya telah Kami muliakan anak-anak Adam, Kami angkut mereka di daratan dan di lautan, Kami beri mereka rezeki dari yang baik-baik dan Kami lebihkan mereka dengan kelebihan yang sempurna atas kebanyakan makhluk yang telah Kami ciptakan.<?php break;}
case 71:{?>(Ingatlah) suatu hari (yang di hari itu) Kami panggil tiap umat dengan pemimpinnya; dan barang siapa yang diberikan kitab amalannya di tangan kanannya maka mereka ini akan membaca kitabnya itu, dan mereka tidak dianiaya sedikit pun.<?php break;}
case 72:{?>Dan barang siapa yang buta (hatinya) di dunia ini, niscaya di akhirat (nanti) ia akan lebih buta (pula) dan lebih tersesat dari jalan (yang benar).<?php break;}
case 73:{?>Dan sesungguhnya mereka hampir memalingkan kamu dari apa yang telah Kami wahyukan kepadamu, agar kamu membuat yang lain secara bohong terhadap Kami; dan kalau sudah begitu tentulah mereka mengambil kamu jadi sahabat yang setia.<?php break;}
case 74:{?>Dan kalau Kami tidak memperkuat (hati) mu, niscaya kamu hampir-hampir condong sedikit kepada mereka,<?php break;}
case 75:{?>kalau terjadi demikian, benar-benarlah Kami akan rasakan kepadamu (siksaan) berlipat ganda di dunia ini dan begitu (pula siksaan) berlipat ganda sesudah mati, dan kamu tidak akan mendapat seorang penolongpun terhadap Kami.<?php break;}
case 76:{?>Dan sesungguhnya benar-benar mereka hampir membuatmu gelisah di negeri (Mekah) untuk mengusirmu daripadanya dan kalau terjadi demikian, niscaya sepeninggalmu mereka tidak tinggal, melainkan sebentar saja.<?php break;}
case 77:{?>(Kami menetapkan yang demikian) sebagai suatu ketetapan terhadap rasul-rasul Kami yang Kami utus sebelum kamu dan tidak akan kamu dapati perubahan bagi ketetapan Kami itu.<?php break;}
case 78:{?>Dirikanlah salat dari sesudah matahari tergelincir sampai gelap malam dan (dirikanlah pula salat) subuh. Sesungguhnya salat subuh itu disaksikan (oleh malaikat).<?php break;}
case 79:{?>Dan pada sebahagian malam hari bersembahyang tahajudlah kamu sebagai suatu ibadah tambahan bagimu: mudah-mudahan Tuhan-mu mengangkat kamu ke tempat yang terpuji.<?php break;}
case 80:{?>Dan katakanlah: &quot;Ya Tuhan-ku, masukkanlah aku secara masuk yang benar dan keluarkanlah (pula) aku secara keluar yang benar dan berikanlah kepadaku dari sisi Engkau kekuasaan yang menolong.<?php break;}
case 81:{?>Dan katakanlah: &quot;Yang benar telah datang dan yang batil telah lenyap&quot;. Sesungguhnya yang batil itu adalah sesuatu yang pasti lenyap.<?php break;}
case 82:{?>Dan Kami turunkan dari Al Qur'an suatu yang menjadi penawar dan rahmat bagi orang-orang yang beriman dan Al Qur'an itu tidaklah menambah kepada orang-orang yang lalim selain kerugian.<?php break;}
case 83:{?>Dan apabila Kami berikan kesenangan kepada manusia niscaya berpalinglah dia: dan membelakang dengan sikap yang sombong; dan apabila dia ditimpa kesusahan niscaya dia berputus asa.<?php break;}
case 84:{?>Katakanlah: &quot;Tiap-tiap orang berbuat menurut keadaannya masing-masing&quot;. Maka Tuhanmu lebih mengetahui siapa yang lebih benar jalannya.<?php break;}
case 85:{?>Dan mereka bertanya kepadamu tentang roh. Katakanlah: &quot;Roh itu termasuk urusan Tuhan-ku, dan tidaklah kamu diberi pengetahuan melainkan sedikit&quot;.<?php break;}
case 86:{?>Dan sesungguhnya jika Kami menghendaki, niscaya Kami lenyapkan apa yang telah Kami wahyukan kepadamu, dan dengan pelenyapan itu, kamu tidak akan mendapatkan seorang pembela pun terhadap Kami,<?php break;}
case 87:{?>kecuali karena rahmat dari Tuhanmu. Sesungguhnya karunia-Nya atasmu adalah besar.<?php break;}
case 88:{?>Katakanlah: &quot;Sesungguhnya jika manusia dan jin berkumpul untuk membuat yang serupa Al Qur'an ini, niscaya mereka tidak akan dapat membuat yang serupa dengan dia, sekalipun sebagian mereka menjadi pembantu bagi sebagian yang lain&quot;.<?php break;}
case 89:{?>Dan sesungguhnya Kami telah mengulang-ulang kepada manusia dalam Al Qur'an ini tiap-tiap macam perumpamaan, tapi kebanyakan manusia tidak menyukai kecuali mengingkari (nya).<?php break;}
case 90:{?>Dan mereka berkata: &quot;Kami sekali-kali tidak percaya kepadamu hingga kamu memancarkan mata air dari bumi untuk kami,<?php break;}
case 91:{?>atau kamu mempunyai sebuah kebun kurma dan anggur, lalu kamu alirkan sungai-sungai di celah kebun yang deras alirannya,<?php break;}
case 92:{?>atau kamu jatuhkan langit berkeping-keping atas kami, sebagaimana kamu katakan atau kamu datangkan Allah dan malaikat-malaikat berhadapan muka dengan kami.<?php break;}
case 93:{?>Atau kamu mempunyai sebuah rumah dari emas, atau kamu naik ke langit. Dan kami sekali-kali tidak akan mempercayai kenaikanmu itu hingga kamu turunkan atas kami sebuah kitab yang kami baca&quot; Katakanlah: &quot;Maha Suci Tuhanku, bukankah aku ini hanya seorang manusia yang menjadi rasul?&quot;<?php break;}
case 94:{?>Dan tidak ada sesuatu yang menghalangi manusia untuk beriman tatkala datang petunjuk kepadanya, kecuali perkataan mereka: &quot;Adakah Allah mengutus seorang manusia menjadi rasul?&quot;<?php break;}
case 95:{?>Katakanlah: &quot;Kalau seandainya ada malaikat-malaikat yang berjalan-jalan sebagai penghuni di bumi, niscaya Kami turunkan dari langit kepada mereka malaikat menjadi rasul&quot;.<?php break;}
case 96:{?>Katakanlah: &quot;Cukuplah Allah menjadi saksi antara aku dan kamu sekalian. Sesungguhnya Dia adalah Maha Mengetahui lagi Maha Melihat akan hamba-hamba-Nya&quot;.<?php break;}
case 97:{?>Dan barangsiapa yang ditunjuki Allah, dialah yang mendapat petunjuk dan Barang siapa yang Dia sesatkan maka sekali-kali kamu tidak akan mendapat penolong-penolong bagi mereka selain dari Dia. Dan Kami akan mengumpulkan mereka pada hari kiamat (diseret) atas muka mereka dalam keadaan buta, bisu dan pekak. Tempat kediaman mereka adalah neraka Jahanam. Tiap-tiap kali nyala api Jahanam itu akan padam Kami tambah lagi bagi mereka nyalanya.<?php break;}
case 98:{?>Itulah balasan bagi mereka, karena sesungguhnya mereka kafir kepada ayat-ayat Kami dan (karena mereka) berkata: &quot;Apakah bila kami telah menjadi tulang belulang dan benda-benda yang hancur, apakah kami benar-benar akan dibangkitkan kembali sebagai makhluk baru?&quot;<?php break;}
case 99:{?>Dan apakah mereka tidak memperhatikan bahwasanya Allah yang menciptakan langit dan bumi adalah kuasa (pula) menciptakan yang serupa dengan mereka, dan telah menetapkan waktu yang tertentu bagi mereka yang tidak ada keraguan padanya? Maka orang-orang lalim itu tidak menghendaki kecuali kekafiran.<?php break;}
case 100:{?>Katakanlah: &quot;Kalau seandainya kamu menguasai khazanah rahmat Tuhanku, niscaya khazanah itu kamu tahan, karena takut membelanjakannya&quot;. Dan adalah manusia itu sangat kikir.<?php break;}
case 101:{?>Dan sesungguhnya Kami telah memberikan kepada Musa sembilan buah mukjizat yang nyata, maka tanyakanlah kepada Bani Israel, tatkala Musa datang kepada mereka lalu Firaun berkata kepadanya: &quot;Sesungguhnya aku sangka kamu, hai Musa, seorang yang kena sihir&quot;.<?php break;}
case 102:{?>Musa menjawab: &quot;Sesungguhnya kamu telah mengetahui, bahwa tiada yang menurunkan mukjizat-mukjizat itu kecuali Tuhan Yang memelihara langit dan bumi sebagai bukti-bukti yang nyata: dan sesungguhnya aku mengira kamu, hai Firaun, seorang yang akan binasa&quot;.<?php break;}
case 103:{?>Kemudian (Firaun) hendak mengusir mereka (Musa dan pengikut-pengikutnya) dari bumi (Mesir) itu, maka Kami tenggelamkan dia (Firaun), serta orang-orang yang bersama-sama dia seluruhnya,<?php break;}
case 104:{?>dan Kami berfirman sesudah itu kepada Bani Israel: &quot;Diamlah di negeri ini, maka apabila datang masa berbangkit, niscaya Kami datangkan kamu dalam keadaan bercampur baur (dengan musuhmu)&quot;.<?php break;}
case 105:{?>Dan Kami turunkan (Al Qur'an itu dengan sebenar-benarnya dan Al Qur'an itu telah turun dengan (membawa) kebenaran. Dan Kami tidak mengutus kamu, melainkan sebagai pembawa berita gembira dan pemberi peringatan.<?php break;}
case 106:{?>Dan Al Qur'an itu telah Kami turunkan dengan berangsur-angsur agar kamu membacakannya perlahan-lahan kepada manusia dan Kami menurunkannya bagian demi bagian.<?php break;}
case 107:{?>Katakanlah: &quot;Berimanlah kamu kepadanya atau tidak usah beriman (sama saja bagi Allah). Sesungguhnya orang-orang yang diberi pengetahuan sebelumnya apabila Al Qur'an dibacakan kepada mereka, mereka menyungkur atas muka mereka sambil bersujud,<?php break;}
case 108:{?>dan mereka berkata: &quot;Maha Suci Tuhan kami; sesungguhnya janji Tuhan kami pasti dipenuhi&quot;.<?php break;}
case 109:{?>Dan mereka menyungkur atas muka mereka sambil menangis dan mereka bertambah khusyuk.<?php break;}
case 110:{?>Katakanlah: &quot;Serulah Allah atau serulah Ar-Rahman. Dengan nama yang mana saja kamu seru, Dia mempunyai al asmaaulhusna (nama-nama yang terbaik) dan janganlah kamu mengeraskan suaramu dalam salatmu dan janganlah pula merendahkannya dan carilah jalan tengah di antara kedua itu&quot;<?php break;}
case 111:{?>Dan katakanlah: &quot;Segala puji bagi Allah Yang tidak mempunyai anak dan tidak mempunyai sekutu dalam kerajaan-Nya dan Dia bukan pula hina yang memerlukan penolong dan agungkanlah Dia dengan pengagungan yang sebesar-besarnya.<?php break;}
}?>