<?php 
switch($verse){
case 1:{?>Segala puji bagi Allah yang telah menurunkan kepada hamba-Nya Al Kitab (Al Qur'an) dan Dia tidak mengadakan kebengkokan di dalamnya;<?php break;}
case 2:{?>sebagai bimbingan yang lurus, untuk memperingatkan akan siksaan yang sangat pedih dari sisi Allah dan memberi berita gembira kepada orang-orang yang beriman, yang mengerjakan amal saleh, bahwa mereka akan mendapat pembalasan yang baik,<?php break;}
case 3:{?>mereka kekal di dalamnya untuk selama-lamanya.<?php break;}
case 4:{?>Dan untuk memperingatkan kepada orang-orang yang berkata: &quot;Allah mengambil seorang anak&quot;.<?php break;}
case 5:{?>Mereka sekali-kali tidak mempunyai pengetahuan tentang hal itu, begitu pula nenek moyang mereka. Alangkah jeleknya kata-kata yang keluar dari mulut mereka; mereka tidak mengatakan (sesuatu) kecuali dusta.<?php break;}
case 6:{?>Maka (apakah) barangkali kamu akan membunuh dirimu karena bersedih hati sesudah mereka berpaling, sekiranya mereka tidak beriman kepada keterangan ini (Al Qur'an).<?php break;}
case 7:{?>Sesungguhnya Kami telah menjadikan apa yang ada di bumi sebagai perhiasan baginya, agar Kami menguji mereka siapakah di antara mereka yang terbaik perbuatannya.<?php break;}
case 8:{?>Dan sesungguhnya Kami benar-benar akan menjadikan (pula) apa yang di atasnya menjadi tanah rata lagi tandus.<?php break;}
case 9:{?>Atau kamu mengira bahwa orang-orang yang mendiami gua dan (yang mempunyai) raqim itu, mereka termasuk tanda-tanda kekuasaan Kami yang mengherankan?<?php break;}
case 10:{?>(Ingatlah) tatkala pemuda-pemuda itu mencari tempat berlindung ke dalam gua lalu mereka berdoa: &quot;Wahai Tuhan kami berikanlah rahmat kepada kami dari sisi-Mu dan sempurnakanlah bagi kami petunjuk yang lurus dalam urusan kami (ini)&quot;.<?php break;}
case 11:{?>Maka Kami tutup telinga mereka beberapa tahun dalam gua itu,<?php break;}
case 12:{?>kemudian Kami bangunkan mereka, agar Kami mengetahui manakah di antara kedua golongan itu yang lebih tepat dalam menghitung berapa lamanya mereka tinggal (dalam gua itu).<?php break;}
case 13:{?>Kami ceritakan kisah mereka kepadamu (Muhammad) dengan sebenarnya. Sesungguhnya mereka itu adalah pemuda-pemuda yang beriman kepada Tuhan mereka dan Kami tambahkan kepada mereka petunjuk;<?php break;}
case 14:{?>dan Kami telah meneguhkan hati mereka di waktu mereka berdiri lalu mereka berkata: &quot;Tuhan kami adalah Tuhan langit dan bumi; kami sekali-kali tidak menyeru Tuhan selain Dia, sesungguhnya kami kalau demikian telah mengucapkan perkataan yang amat jauh dari kebenaran&quot;.<?php break;}
case 15:{?>Kaum kami ini telah menjadikan selain Dia sebagai tuhan-tuhan (untuk di sembah). Mengapa mereka tidak mengemukakan alasan yang terang (tentang kepercayaan mereka?) Siapakah yang lebih lalim daripada orang-orang yang mengada-adakan kebohongan terhadap Allah?<?php break;}
case 16:{?>Dan apabila kamu meninggalkan mereka dan apa yang mereka sembah selain Allah, maka carilah tempat berlindung ke dalam gua itu niscaya Tuhanmu akan melimpahkan sebagian rahmat-Nya kepadamu dan menyediakan sesuatu yang berguna bagimu dalam urusan kamu.<?php break;}
case 17:{?>Dan kamu akan melihat matahari ketika terbit, condong dari gua mereka ke sebelah kanan, dan bila matahari itu terbenam menjauhi mereka ke sebelah kiri sedang mereka berada dalam tempat yang luas dalam gua itu. Itu adalah sebagian dari tanda-tanda (kebesaran) Allah. Barang siapa yang diberi petunjuk oleh Allah, maka dialah yang mendapat petunjuk; dan barang siapa yang disesatkan-Nya, maka kamu tak akan mendapatkan seorang pemimpin pun yang dapat memberi petunjuk kepadanya.<?php break;}
case 18:{?>Dan kamu mengira mereka itu bangun padahal mereka tidur; dan Kami balik-balikkan mereka ke kanan dan ke kiri, sedang anjing mereka mengunjurkan kedua lengannya di muka pintu gua. Dan jika kamu menyaksikan mereka tentulah kamu akan berpaling dari mereka dengan melarikan (diri) dan tentulah (hati) kamu akan dipenuhi dengan ketakutan terhadap mereka.<?php break;}
case 19:{?>Dan demikianlah Kami bangunkan mereka agar mereka saling bertanya di antara mereka sendiri. Berkatalah salah seorang di antara mereka: &quot;Sudah berapa lamakah kamu berada (di sini?)&quot;. Mereka menjawab: &quot;Kita berada (di sini) sehari atau setengah hari&quot;. Berkata (yang lain lagi): &quot;Tuhan kamu lebih mengetahui berapa lamanya kamu berada (di sini). Maka suruhlah salah seorang di antara kamu pergi ke kota dengan membawa uang perakmu ini, dan hendaklah dia lihat manakah makanan yang lebih baik, maka hendaklah dia membawa makanan itu untukmu, dan hendaklah dia berlaku lemah lembut dan janganlah sekali-kali menceritakan halmu kepada seseorang pun.<?php break;}
case 20:{?>Sesungguhnya jika mereka dapat mengetahui tempatmu, niscaya mereka akan melempar kamu dengan batu, atau memaksamu kembali kepada agama mereka, dan jika demikian niscaya kamu tidak akan beruntung selama-lamanya&quot;.<?php break;}
case 21:{?>Dan demikian (pula) Kami mempertemukan (manusia) dengan mereka, agar manusia itu mengetahui, bahwa janji Allah itu benar, dan bahwa kedatangan hari kiamat tidak ada keraguan padanya. Ketika orang-orang itu berselisih tentang urusan mereka, orang-orang itu berkata: &quot;Dirikanlah sebuah bangunan di atas (gua) mereka, Tuhan mereka lebih mengetahui tentang mereka&quot;. Orang-orang yang berkuasa atas urusan mereka berkata: &quot;Sesungguhnya kami akan mendirikan sebuah rumah peribadatan di atasnya&quot;.<?php break;}
case 22:{?>Nanti (ada orang yang akan) mengatakan (jumlah mereka) adalah tiga orang yang keempat adalah anjingnya, dan (yang lain) mengatakan: &quot;(Jumlah mereka) adalah lima orang yang keenam adalah anjingnya&quot;, sebagai terkaan terhadap barang yang gaib; dan (yang lain lagi) mengatakan: &quot;(Jumlah mereka) tujuh orang, yang kedelapan adalah anjingnya&quot;. Katakanlah: &quot;Tuhanku lebih mengetahui jumlah mereka; tidak ada orang yang mengetahui (bilangan) mereka kecuali sedikit&quot;. Karena itu janganlah kamu (Muhammad) bertengkar tentang hal mereka, kecuali pertengkaran lahir saja dan jangan kamu menanyakan tentang mereka (pemuda-pemuda itu) kepada seorang pun di antara mereka.<?php break;}
case 23:{?>Dan jangan sekali-kali kamu mengatakan terhadap sesuatu: &quot;Sesungguhnya aku akan mengerjakan itu besok pagi,<?php break;}
case 24:{?>kecuali (dengan menyebut): &quot;Insya-Allah&quot;. Dan ingatlah kepada Tuhanmu jika kamu lupa dan katakanlah: &quot;Mudah-mudahan Tuhanku akan memberiku petunjuk kepada yang lebih dekat kebenarannya daripada ini&quot;.<?php break;}
case 25:{?>Dan mereka tinggal dalam gua mereka tiga ratus tahun dan ditambah sembilan tahun (lagi).<?php break;}
case 26:{?>Katakanlah: &quot;Allah lebih mengetahui berapa lamanya mereka tinggal (di gua); kepunyaan-Nya-lah semua yang tersembunyi di langit dan di bumi. Alangkah terang penglihatan-Nya dan alangkah tajam pendengaran-Nya; tak ada seorang pelindung pun bagi mereka selain daripada-Nya; dan Dia tidak mengambil seorang pun menjadi sekutu-Nya dalam menetapkan keputusan&quot;.<?php break;}
case 27:{?>Dan bacakanlah apa yang diwahyukan kepadamu, yaitu kitab Tuhan-mu (Al Qur'an). Tidak ada (seorang pun) yang dapat mengubah kalimat-kalimat-Nya. Dan kamu tidak akan dapat menemukan tempat berlindung selain daripada-Nya.<?php break;}
case 28:{?>Dan bersabarlah kamu bersama-sama dengan orang-orang yang menyeru Tuhannya di pagi dan senja hari dengan mengharap keridaan-Nya; dan janganlah kedua matamu berpaling dari mereka (karena) mengharapkan perhiasan kehidupan dunia ini; dan janganlah kamu mengikuti orang yang hatinya telah Kami lalaikan dari mengingati Kami, serta menuruti hawa nafsunya dan adalah keadaannya itu melewati batas.<?php break;}
case 29:{?>Dan katakanlah: &quot;Kebenaran itu datangnya dari Tuhanmu; maka barangsiapa yang ingin (beriman) hendaklah ia beriman, dan barang siapa yang ingin (kafir) biarlah ia kafir&quot;. Sesungguhnya Kami telah sediakan bagi orang-orang lalim itu neraka, yang gejolaknya mengepung mereka. Dan jika mereka meminta minum, niscaya mereka akan diberi minum dengan air seperti besi yang mendidih yang menghanguskan muka. Itulah minuman yang paling buruk dan tempat istirahat yang paling jelek.<?php break;}
case 30:{?>Sesungguhnya mereka yang beriman dan beramal saleh, tentulah Kami tidak akan menyia-nyiakan pahala orang-orang yang mengerjakan amalan (nya) dengan baik.<?php break;}
case 31:{?>Mereka itulah (orang-orang yang) bagi mereka surga Adn, mengalir sungai-sungai di bawahnya; dalam surga itu mereka dihiasi dengan gelang emas dan mereka memakai pakaian hijau dari sutera halus dan sutera tebal, sedang mereka duduk sambil bersandar di atas dipan-dipan yang indah. Itulah pahala yang sebaik-baiknya, dan tempat-istirahat yang indah;<?php break;}
case 32:{?>Dan berikanlah kepada mereka sebuah perumpamaan dua orang laki-laki, Kami jadikan bagi seorang di antara keduanya (yang kafir) dua buah kebun anggur dan Kami kelilingi kedua kebun itu dengan pohon-pohon kurma dan di antara kedua kebun itu Kami buatkan ladang.<?php break;}
case 33:{?>Kedua buah kebun itu menghasilkan buahnya, dan kebun itu tiada kurang buahnya sedikit pun dan Kami alirkan sungai di celah-celah kedua kebun itu,<?php break;}
case 34:{?>dan dia mempunyai kekayaan besar, maka ia berkata kepada kawannya (yang mukmin) ketika ia bercakap-cakap dengan dia: &quot;Hartaku lebih banyak dari pada hartamu dan pengikut-pengikutku lebih kuat&quot;.<?php break;}
case 35:{?>Dan dia memasuki kebunnya sedang dia zalim terhadap dirinya sendiri; ia berkata: &quot;Aku kira kebun ini tidak akan binasa selama-lamanya,<?php break;}
case 36:{?>dan aku tidak mengira hari kiamat itu akan datang, dan jika sekiranya aku di kembalikan kepada Tuhanku, pasti aku akan mendapat tempat kembali yang lebih baik daripada kebun-kebun itu&quot;.<?php break;}
case 37:{?>Kawannya (yang mukmin) berkata kepadanya sedang dia bercakap-cakap dengannya: &quot;Apakah kamu kafir kepada (Tuhan) yang menciptakan kamu dari tanah, kemudian dari setetes air mani, lalu Dia menjadikan kamu seorang laki-laki yang sempurna?<?php break;}
case 38:{?>Tetapi aku (percaya bahwa): Dialah Allah, Tuhanku, dan aku tidak mempersekutukan seorang pun dengan Tuhanku.<?php break;}
case 39:{?>Dan mengapa kamu tidak mengucapkan tatkala kamu memasuki kebunmu &quot;MAA SYAA ALLAH, LAA QUWWATA ILLAA BILLAH&quot; (Sungguh atas kehendak Allah semua ini terwujud, tiada kekuatan kecuali dengan pertolongan Allah). Sekiranya kamu anggap aku lebih sedikit darimu dalam hal harta dan keturunan,<?php break;}
case 40:{?>maka mudah-mudahan Tuhanku, akan memberi kepadaku (kebun) yang lebih baik daripada kebunmu (ini); dan mudah-mudahan Dia mengirimkan ketentuan (petir) dari langit kepada kebunmu, hingga (kebun itu) menjadi tanah yang licin.<?php break;}
case 41:{?>atau airnya menjadi surut ke dalam tanah, maka sekali-kali kamu tidak dapat menemukannya lagi&quot;.<?php break;}
case 42:{?>Dan harta kekayaannya dibinasakan, lalu ia membulak-balikkan kedua tangannya (tanda menyesal) terhadap apa yang ia telah belanjakan untuk itu, sedang pohon anggur itu roboh bersama para-paranya dan dia berkata: &quot;Aduhai kiranya dulu aku tidak mempersekutukan seorang pun dengan Tuhanku&quot;.<?php break;}
case 43:{?>Dan tidak ada bagi dia segolongan pun yang akan menolongnya selain Allah; dan sekali-kali ia tidak dapat membela dirinya.<?php break;}
case 44:{?>Di sana pertolongan itu hanya dari Allah Yang Hak. Dia adalah sebaik-baik Pemberi pahala dan sebaik-baik Pemberi balasan.<?php break;}
case 45:{?>Dan berilah perumpamaan kepada mereka (manusia), kehidupan dunia adalah sebagai air hujan yang Kami turunkan dari langit, maka menjadi subur karenanya tumbuh-tumbuhan di muka bumi, kemudian tumbuh-tumbuhan itu menjadi kering yang diterbangkan oleh angin. Dan adalah Allah Maha Kuasa atas segala sesuatu.<?php break;}
case 46:{?>Harta dan anak-anak adalah perhiasan kehidupan dunia tetapi amalan-amalan yang kekal lagi saleh adalah lebih baik pahalanya di sisi Tuhanmu serta lebih baik untuk menjadi harapan.<?php break;}
case 47:{?>Dan (ingatlah) akan hari (yang ketika itu) Kami perjalankan gunung-gunung dan kamu akan melihat bumi itu datar dan Kami kumpulkan seluruh manusia, dan tidak Kami tinggalkan seorang pun dari mereka.<?php break;}
case 48:{?>Dan mereka akan dibawa ke hadapan Tuhanmu dengan berbaris. Sesungguhnya kamu datang kepada Kami, sebagaimana Kami menciptakan kamu pada kali yang pertama; bahkan kamu mengatakan bahwa Kami sekali-kali tidak akan menetapkan bagi kamu waktu (memenuhi) perjanjian.<?php break;}
case 49:{?>Dan diletakkanlah kitab, lalu kamu akan melihat orang-orang yang bersalah ketakutan terhadap apa yang (tertulis) di dalamnya, dan mereka berkata: &quot;Aduhai celaka kami, kitab apakah ini yang tidak meninggalkan yang kecil dan tidak (pula) yang besar, melainkan ia mencatat semuanya; dan mereka dapati apa yang telah mereka kerjakan ada (tertulis). Dan Tuhanmu tidak menganiaya seorang jua pun&quot;.<?php break;}
case 50:{?>Dan (ingatlah) ketika Kami berfirman kepada para malaikat: &quot;Sujudlah kamu kepada Adam&quot;, maka sujudlah mereka kecuali iblis. Dia adalah dari golongan jin, maka ia mendurhakai perintah Tuhannya. Patutkah kamu mengambil dia dan turunan-turunannya sebagai pemimpin selain daripada-Ku, sedang mereka adalah musuhmu? Amat buruklah iblis itu sebagai pengganti (Allah) bagi orang-orang yang lalim.<?php break;}
case 51:{?>Aku tidak menghadirkan mereka (iblis dan anak cucunya) untuk menyaksikan penciptaan langit dan bumi dan tidak (pula) penciptaan diri mereka sendiri; dan tidaklah Aku mengambil orang-orang yang menyesatkan itu sebagai penolong.<?php break;}
case 52:{?>Dan (ingatlah) akan hari (yang ketika itu) Dia berfirman: &quot;Panggillah olehmu sekalian sekutu-sekutu-Ku yang kamu katakan itu&quot;. Mereka lalu memanggilnya tetapi sekutu-sekutu itu tidak membalas seruan mereka dan Kami adakan untuk mereka tempat kebinasaan (neraka).<?php break;}
case 53:{?>Dan orang-orang yang berdosa melihat neraka, maka mereka meyakini, bahwa mereka akan jatuh ke dalamnya dan mereka tidak menemukan tempat berpaling daripadanya.<?php break;}
case 54:{?>Dan sesungguhnya Kami telah mengulang-ulangi bagi manusia dalam Al Qur'an ini bermacam-macam perumpamaan. Dan manusia adalah makhluk yang paling banyak membantah.<?php break;}
case 55:{?>Dan tidak ada sesuatu pun yang menghalangi manusia dari beriman, ketika petunjuk telah datang kepada mereka, dan memohon ampun kepada Tuhannya, kecuali (keinginan menanti) datangnya hukum (Allah yang telah berlaku pada) umat-umat yang dahulu atau datangnya azab atas mereka dengan nyata.<?php break;}
case 56:{?>Dan tidaklah Kami mengutus rasul-rasul melainkan sebagai pembawa berita gembira dan sebagai pemberi peringatan; tetapi orang-orang yang kafir membantah dengan yang batil agar dengan demikian mereka dapat melenyapkan yang hak, dan mereka menganggap ayat-ayat Kami dan peringatan-peringatan terhadap mereka sebagai olok-olokkan.<?php break;}
case 57:{?>Dan siapakah yang lebih lalim daripada orang yang telah diperingatkan dengan ayat-ayat dari Tuhannya lalu dia berpaling daripadanya dan melupakan apa yang telah dikerjakan oleh kedua tangannya? Sesungguhnya Kami telah meletakkan tutupan di atas hati mereka, (sehingga mereka tidak) memahaminya, dan (Kami letakkan pula) sumbatan di telinga mereka; dan kendati pun kamu menyeru mereka kepada petunjuk, niscaya mereka tidak akan mendapat petunjuk selama-lamanya,<?php break;}
case 58:{?>Dan Tuhanmulah Yang Maha Pengampun, lagi mempunyai rahmat. Jika Dia mengazab mereka karena perbuatan mereka, tentu Dia akan menyegerakan azab bagi mereka. Tetapi bagi mereka ada waktu yang tertentu (untuk mendapat azab) yang mereka sekali-kali tidak akan menemukan tempat berlindung daripadanya.<?php break;}
case 59:{?>Dan (penduduk) negeri itu telah Kami binasakan ketika mereka berbuat lalim, dan telah Kami tetapkan waktu tertentu bagi kebinasaan mereka.<?php break;}
case 60:{?>Dan (ingatlah) ketika Musa berkata kepada muridnya: &quot;Aku tidak akan berhenti (berjalan) sebelum sampai ke pertemuan dua buah lautan; atau aku akan berjalan sampai bertahun-tahun&quot;.<?php break;}
case 61:{?>Maka tatkala mereka sampai ke pertemuan dua buah laut itu, mereka lalai akan ikannya, lalu ikan itu melompat mengambil jalannya ke laut itu.<?php break;}
case 62:{?>Maka tatkala mereka berjalan lebih jauh, berkatalah Musa kepada muridnya: &quot;Bawalah ke mari makanan kita; sesungguhnya kita telah merasa letih karena perjalanan kita ini&quot;.<?php break;}
case 63:{?>Muridnya menjawab: &quot;Tahukah kamu tatkala kita mencari tempat berlindung di batu tadi, maka sesungguhnya aku lupa (menceritakan tentang) ikan itu dan tidak adalah yang melupakan aku untuk menceritakannya kecuali setan dan ikan itu mengambil jalannya ke laut dengan cara yang aneh sekali.&quot;<?php break;}
case 64:{?>Musa berkata: &quot;Itulah (tempat) yang kita cari&quot;. Lalu keduanya kembali, mengikuti jejak mereka semula.<?php break;}
case 65:{?>Lalu mereka bertemu dengan seorang hamba di antara hamba-hamba Kami, yang telah Kami berikan kepadanya rahmat dari sisi Kami, dan yang telah Kami ajarkan kepadanya ilmu dari sisi Kami.<?php break;}
case 66:{?>Musa berkata kepada Khidhr: &quot;Bolehkah aku mengikutimu supaya kamu mengajarkan kepadaku ilmu yang benar di antara ilmu-ilmu yang telah diajarkan kepadamu?&quot;<?php break;}
case 67:{?>Dia menjawab: &quot;Sesungguhnya kamu sekali-kali tidak akan sanggup sabar bersamaku.<?php break;}
case 68:{?>Dan bagaimana kamu dapat sabar atas sesuatu, yang kamu belum mempunyai pengetahuan yang cukup tentang hal itu?&quot;<?php break;}
case 69:{?>Musa berkata: &quot;Insya Allah kamu akan mendapati aku sebagai seorang yang sabar, dan aku tidak akan menentangmu dalam sesuatu urusan pun&quot;.<?php break;}
case 70:{?>Dia berkata: &quot;Jika kamu mengikutiku, maka janganlah kamu menanyakan kepadaku tentang sesuatu apa pun, sampai aku sendiri menerangkannya kepadamu&quot;.<?php break;}
case 71:{?>Maka berjalanlah keduanya, hingga tatkala keduanya menaiki perahu lalu Khidhr melobanginya. Musa berkata: &quot;Mengapa kamu melobangi perahu itu yang akibatnya kamu menenggelamkan penumpangnya?&quot; Sesungguhnya kamu telah berbuat sesuatu kesalahan yang besar.<?php break;}
case 72:{?>Dia (Khidhr) berkata: &quot;Bukankah aku telah berkata: &quot;Sesungguhnya kamu sekali-kali tidak akan sabar bersama dengan aku&quot;<?php break;}
case 73:{?>Musa berkata: &quot;Janganlah kamu menghukum aku karena kelupaanku dan janganlah kamu membebani aku dengan sesuatu kesulitan dalam urusanku&quot;.<?php break;}
case 74:{?>Maka berjalanlah keduanya; hingga tatkala keduanya berjumpa dengan seorang anak, maka Khidhr membunuhnya. Musa berkata: &quot;Mengapa kamu bunuh jiwa yang bersih, bukan karena dia membunuh orang lain? Sesungguhnya kamu telah melakukan suatu yang mungkar&quot;.<?php break;}
case 75:{?>Khidhr berkata: &quot;Bukankah sudah kukatakan kepadamu, bahwa sesungguhnya kamu tidak akan dapat sabar bersamaku?&quot;<?php break;}
case 76:{?>Musa berkata: &quot;Jika aku bertanya kepadamu tentang sesuatu sesudah (kali) ini, maka janganlah kamu memperbolehkan aku menyertaimu, sesungguhnya kamu sudah cukup memberikan uzur padaku&quot;.<?php break;}
case 77:{?>Maka keduanya berjalan; hingga tatkala keduanya sampai kepada penduduk suatu negeri, mereka minta dijamu kepada penduduk negeri itu tetapi penduduk negeri itu tidak mau menjamu mereka, kemudian keduanya mendapatkan dalam negeri itu dinding rumah yang hampir roboh, maka Khidhr menegakkan dinding itu. Musa berkata: &quot;Jikalau kamu mau, niscaya kamu mengambil upah untuk itu&quot;.<?php break;}
case 78:{?>Khidhr berkata: &quot;Inilah perpisahan antara aku dengan kamu; Aku akan memberitahukan kepadamu tujuan perbuatan-perbuatan yang kamu tidak dapat sabar terhadapnya.<?php break;}
case 79:{?>Adapun bahtera itu adalah kepunyaan orang-orang miskin yang bekerja di laut, dan aku bertujuan merusakkan bahtera itu, karena di hadapan mereka ada seorang raja yang merampas tiap-tiap bahtera.<?php break;}
case 80:{?>Dan adapun anak itu maka kedua orang tuanya adalah orang-orang mukmin, dan kami khawatir bahwa dia akan mendorong kedua orang tuanya itu kepada kesesatan dan kekafiran.<?php break;}
case 81:{?>Dan kami menghendaki, supaya Tuhan mereka mengganti bagi mereka dengan anak lain yang lebih baik kesuciannya dari anaknya itu dan lebih dalam kasih sayangnya (kepada ibu bapaknya).<?php break;}
case 82:{?>Adapun dinding rumah itu adalah kepunyaan dua orang anak yatim di kota itu, dan di bawahnya ada harta benda simpanan bagi mereka berdua, sedang ayahnya adalah seorang yang saleh, maka Tuhanmu menghendaki agar supaya mereka sampai kepada kedewasaannya dan mengeluarkan simpanannya itu, sebagai rahmat dari Tuhanmu; dan bukanlah aku melakukannya itu menurut kemauanku sendiri. Demikian itu adalah tujuan perbuatan-perbuatan yang kamu tidak dapat sabar terhadapnya&quot;.<?php break;}
case 83:{?>Mereka akan bertanya kepadamu (Muhammad) tentang Zulkarnain. Katakanlah: &quot;Aku akan bacakan kepadamu cerita tentangnya&quot;.<?php break;}
case 84:{?>Sesungguhnya Kami telah memberi kekuasaan kepadanya di (muka) bumi, dan Kami telah memberikan kepadanya jalan (untuk mencapai) segala sesuatu,<?php break;}
case 85:{?>maka dia pun menempuh suatu jalan.<?php break;}
case 86:{?>Hingga apabila dia telah sampai ke tempat terbenam matahari, dia melihat matahari terbenam di dalam laut yang berlumpur hitam, dan dia mendapati di situ segolongan umat. Kami berkata: &quot;Hai Zulkarnain, kamu boleh menyiksa atau boleh berbuat kebaikan terhadap mereka&quot;.<?php break;}
case 87:{?>Berkata Zulkarnain: &quot;Adapun orang yang aniaya, maka kami kelak akan mengazabnya, kemudian dia dikembalikan kepada Tuhannya, lalu Tuhan mengazabnya dengan azab yang tidak ada taranya.<?php break;}
case 88:{?>Adapun orang-orang yang beriman dan beramal saleh, maka baginya pahala yang terbaik sebagai balasan, dan akan kami titahkan kepadanya (perintah) yang mudah dari perintah-perintah kami&quot;.<?php break;}
case 89:{?>Kemudian dia menempuh jalan (yang lain).<?php break;}
case 90:{?>Hingga apabila dia telah sampai ke tempat terbit matahari (sebelah Timur) dia mendapati matahari itu menyinari segolongan umat yang Kami tidak menjadikan bagi mereka sesuatu yang melindunginya dari (cahaya) matahari itu,<?php break;}
case 91:{?>demikianlah. Dan sesungguhnya ilmu Kami meliputi segala apa yang ada padanya.<?php break;}
case 92:{?>Kemudian dia menempuh suatu jalan (yang lain lagi).<?php break;}
case 93:{?>Hingga apabila dia telah sampai di antara dua buah gunung, dia mendapati di hadapan kedua bukit itu suatu kaum yang hampir tidak mengerti pembicaraan.<?php break;}
case 94:{?>Mereka berkata: &quot;Hai Zulkarnain, sesungguhnya Ya'juj dan Makjuj itu orang-orang yang membuat kerusakan di muka bumi, maka dapatkah kami memberikan sesuatu pembayaran kepadamu, supaya kamu membuat dinding antara kami dan mereka?&quot;<?php break;}
case 95:{?>Zulkarnain berkata: &quot;Apa yang telah dikuasakan oleh Tuhanku kepadaku terhadapnya adalah lebih baik, maka tolonglah aku dengan kekuatan (manusia dan alat-alat), agar aku membuatkan dinding antara kamu dan mereka,<?php break;}
case 96:{?>berilah aku potongan-potongan besi&quot; Hingga apabila besi itu telah sama rata dengan kedua (puncak) gunung itu, berkatalah Zulkarnain: Tiuplah (api itu)&quot;. Hingga apabila besi itu sudah menjadi (merah seperti) api, dia pun berkata: &quot;Berilah aku tembaga (yang mendidih) agar kutuangkan ke atas besi panas itu&quot;.<?php break;}
case 97:{?>Maka mereka tidak bisa mendakinya dan mereka tidak bisa (pula) melobanginya.<?php break;}
case 98:{?>Zulkarnain berkata: &quot;Ini (dinding) adalah rahmat dari Tuhanku, maka apabila sudah datang janji Tuhanku Dia akan menjadikannya hancur luluh; dan janji Tuhanku itu adalah benar&quot;.<?php break;}
case 99:{?>Kami biarkan mereka di hari itu bercampur aduk antara satu dengan yang lain, kemudian ditiup lagi sangkakala, lalu Kami kumpulkan mereka itu semuanya.<?php break;}
case 100:{?>dan Kami nampakkan Jahanam pada hari itu kepada orang-orang kafir dengan jelas.<?php break;}
case 101:{?>yaitu orang-orang yang matanya dalam keadaan tertutup dari memperhatikan tanda-tanda kebesaran-Ku, dan adalah mereka tidak sanggup mendengar.<?php break;}
case 102:{?>Maka apakah orang-orang kafir menyangka bahwa mereka (dapat) mengambil hamba-hamba-Ku menjadi penolong selain Aku? Sesungguhnya Kami telah menyediakan neraka Jahanam tempat tinggal bagi orang-orang kafir.<?php break;}
case 103:{?>Katakanlah: &quot;Apakah akan Kami beritahukan kepadamu tentang orang-orang yang paling merugi perbuatannya?&quot;<?php break;}
case 104:{?>Yaitu orang-orang yang telah sia-sia perbuatannya dalam kehidupan dunia ini, sedangkan mereka menyangka bahwa mereka berbuat sebaik-baiknya.<?php break;}
case 105:{?>Mereka itu orang-orang yang kafir terhadap ayat-ayat Tuhan mereka dan (kafir terhadap) perjumpaan dengan Dia. Maka hapuslah amalan-amalan mereka, dan Kami tidak mengadakan suatu penilaian bagi (amalan) mereka pada hari kiamat.<?php break;}
case 106:{?>Demikianlah balasan mereka itu neraka Jahanam, disebabkan kekafiran mereka dan disebabkan mereka menjadikan ayat-ayat-Ku dan rasul-rasul-Ku sebagai olok-olok.<?php break;}
case 107:{?>Sesungguhnya orang-orang yang beriman dan beramal saleh, bagi mereka adalah surga Firdaus menjadi tempat tinggal,<?php break;}
case 108:{?>mereka kekal di dalamnya, mereka tidak ingin berpindah daripadanya.<?php break;}
case 109:{?>Katakanlah: &quot;Kalau sekiranya lautan menjadi tinta untuk (menulis) kalimat-kalimat Tuhanku, sungguh habislah lautan itu sebelum habis (ditulis) kalimat-kalimat Tuhanku, meskipun Kami datangkan tambahan sebanyak itu (pula).<?php break;}
case 110:{?>Katakanlah: &quot;Sesungguhnya aku ini hanya seorang manusia seperti kamu, yang diwahyukan kepadaku: &quot;Bahwa sesungguhnya Tuhan kamu itu adalah Tuhan Yang Esa&quot;. Barang siapa mengharap perjumpaan dengan Tuhannya maka hendaklah ia mengerjakan amal yang saleh dan janganlah ia mempersekutukan seorang pun dalam beribadah kepada Tuhannya&quot;.<?php break;}
}?>