<?php 
switch($verse){
case 1:{?>Hai manusia, bertakwalah kepada Tuhanmu; sesungguhnya keguncangan hari kiamat itu adalah suatu kejadian yang sangat besar (dahsyat).<?php break;}
case 2:{?>(Ingatlah) pada hari (ketika) kamu melihat keguncangan itu, lalailah semua wanita yang menyusui anaknya dari anak yang disusuinya dan gugurlah kandungan segala wanita yang hamil, dan kamu lihat manusia dalam keadaan mabuk, padahal sebenarnya mereka tidak mabuk, akan tetapi azab Allah itu sangat keras.<?php break;}
case 3:{?>Di antara manusia ada orang yang membantah tentang Allah tanpa ilmu pengetahuan dan mengikuti setiap setan yang sangat jahat,<?php break;}
case 4:{?>yang telah ditetapkan terhadap setan itu, bahwa barang siapa yang berkawan dengan dia, tentu dia akan menyesatkannya, dan membawanya ke azab neraka.<?php break;}
case 5:{?>Hai manusia, jika kamu dalam keraguan tentang kebangkitan (dari kubur), maka (ketahuilah) sesungguhnya Kami telah menjadikan kamu dari tanah, kemudian dari setetes mani, kemudian dari segumpal darah, kemudian dari segumpal daging yang sempurna kejadiannya dan yang tidak sempurna, agar Kami jelaskan kepada kamu dan Kami tetapkan dalam rahim, apa yang Kami kehendaki sampai waktu yang sudah ditentukan, kemudian Kami keluarkan kamu sebagai bayi, kemudian (dengan berangsur-angsur) kamu sampailah kepada kedewasaan, dan di antara kamu ada yang diwafatkan dan (ada pula) di antara kamu yang dipanjangkan umurnya sampai pikun, supaya dia tidak mengetahui lagi sesuatupun yang dahulunya telah diketahuinya. Dan kamu lihat bumi ini kering, kemudian apabila telah Kami turunkan air di atasnya, hiduplah bumi itu dan suburlah dan menumbuhkan berbagai macam tumbuh-tumbuhan yang indah.<?php break;}
case 6:{?>Yang demikian itu, karena sesungguhnya Allah, Dialah yang hak dan sesungguhnya Dialah yang menghidupkan segala yang mati dan sesungguhnya Allah Maha Kuasa atas segala suatu,<?php break;}
case 7:{?>dan sesungguhnya hari kiamat itu pastilah datang, tak ada keraguan padanya; dan bahwasanya Allah membangkitkan semua orang di dalam kubur.<?php break;}
case 8:{?>Dan di antara manusia ada orang-orang yang membantah tentang Allah tanpa ilmu pengetahuan, tanpa petunjuk dan tanpa kitab (wahyu) yang bercahaya,<?php break;}
case 9:{?>dengan memalingkan lambungnya untuk menyesatkan manusia dari jalan Allah. Ia mendapat kehinaan di dunia dan di hari kiamat Kami merasakan kepadanya azab neraka yang membakar.<?php break;}
case 10:{?>(Akan dikatakan kepadanya): &quot;Yang demikian itu, adalah disebabkan perbuatan yang dikerjakan oleh kedua tangan kamu dahulu dan sesungguhnya Allah sekali-kali bukanlah penganiaya hamba-hamba-Nya&quot;.<?php break;}
case 11:{?>Dan di antara manusia ada orang yang menyembah Allah dengan berada di tepi; maka jika ia memperoleh kebajikan, tetaplah ia dalam keadaan itu, dan jika ia ditimpa oleh suatu bencana, berbaliklah ia ke belakang. Rugilah ia di dunia dan di akhirat. Yang demikian itu adalah kerugian yang nyata.<?php break;}
case 12:{?>Ia menyeru selain Allah, sesuatu yang tidak dapat memberi mudarat dan tidak (pula) memberi manfaat kepadanya. Yang demikian itu adalah kesesatan yang jauh.<?php break;}
case 13:{?>Ia menyeru sesuatu yang sebenarnya mudaratnya lebih dekat dari manfaatnya. Sesungguhnya yang diserunya itu adalah sejahat-jahat penolong dan sejahat-jahat kawan.<?php break;}
case 14:{?>Sesungguhnya Allah memasukkan orang-orang yang beriman dan mengerjakan amal yang saleh ke dalam surga-surga yang di bawahnya mengalir sungai-sungai. Sesungguhnya Allah berbuat apa yang Dia kehendaki.<?php break;}
case 15:{?>Barangsiapa yang menyangka bahwa Allah sekali-kali tiada menolongnya (Muhammad) di dunia dan akhirat, maka hendaklah ia merentangkan tali ke langit, kemudian hendaklah ia melaluinya, kemudian hendaklah ia pikirkan apakah tipu dayanya itu dapat melenyapkan apa yang menyakitkan hatinya.<?php break;}
case 16:{?>Dan demikianlah Kami telah menurunkan Al Qur'an yang merupakan ayat-ayat yang nyata; dan bahwasanya Allah memberikan petunjuk kepada siapa yang Dia kehendaki.<?php break;}
case 17:{?>Sesungguhnya orang-orang beriman, orang-orang Yahudi, orang-orang Shaabi-iin, orang-orang Nasrani, orang-orang Majusi dan orang-orang musyrik, Allah akan memberi keputusan di antara mereka pada hari kiamat. Sesungguhnya Allah menyaksikan segala sesuatu.<?php break;}
case 18:{?>Apakah kamu tiada mengetahui, bahwa kepada Allah bersujud apa yang ada di langit, di bumi, matahari, bulan, bintang, gunung, pohon-pohonan, binatang-binatang yang melata dan sebagian besar daripada manusia? Dan banyak di antara manusia yang telah ditetapkan azab atasnya. Dan barang siapa yang dihinakan Allah maka tidak seorang pun yang memuliakannya. Sesungguhnya Allah berbuat apa yang Dia kehendaki.<?php break;}
case 19:{?>Inilah dua golongan (golongan mukmin dan golongan kafir) yang bertengkar, mereka saling bertengkar mengenai Tuhan mereka. Maka orang kafir akan dibuatkan untuk mereka pakaian-pakaian dari api neraka. Disiramkan air yang sedang mendidih ke atas kepala mereka.<?php break;}
case 20:{?>Dengan air itu dihancur luluhkan segala apa yang ada dalam perut mereka dan juga kulit (mereka).<?php break;}
case 21:{?>Dan untuk mereka cambuk-cambuk dari besi.<?php break;}
case 22:{?>Setiap kali mereka hendak keluar dari neraka lantaran kesengsaraan mereka, niscaya mereka dikembalikan ke dalamnya. (Kepada mereka dikatakan): &quot;Rasailah azab yang membakar ini&quot;.<?php break;}
case 23:{?>Sesungguhnya Allah memasukkan orang-orang beriman dan mengerjakan amal yang saleh ke dalam surga-surga yang dibawahnya mengalir sungai-sungai. Di surga itu mereka diberi perhiasan dengan gelang-gelang dari emas dan mutiara, dan pakaian mereka adalah sutera.<?php break;}
case 24:{?>Dan mereka diberi petunjuk kepada ucapan-ucapan yang baik dan ditunjuki (pula) kepada jalan (Allah) yang terpuji.<?php break;}
case 25:{?>Sesungguhnya orang-orang yang kafir dan menghalangi manusia dari jalan Allah dan Masjidilharam yang telah Kami jadikan untuk semua manusia, baik yang bermukim di situ maupun di padang pasir dan siapa yang bermaksud di dalamnya melakukan kejahatan secara lalim, niscaya akan Kami rasakan kepadanya sebahagian siksa yang pedih.<?php break;}
case 26:{?>Dan (ingatlah), ketika Kami memberikan tempat kepada Ibrahim di tempat Baitullah (dengan mengatakan): &quot;Janganlah kamu memperserikatkan sesuatu pun dengan Aku dan sucikanlah rumah-Ku ini bagi orang-orang yang tawaf, dan orang-orang yang beribadah dan orang-orang yang rukuk dan sujud.<?php break;}
case 27:{?>Dan berserulah kepada manusia untuk mengerjakan haji, niscaya mereka akan datang kepadamu dengan berjalan kaki, dan mengendarai unta yang kurus yang datang dari segenap penjuru yang jauh,<?php break;}
case 28:{?>supaya mereka menyaksikan berbagai manfaat bagi mereka dan supaya mereka menyebut nama Allah pada hari yang telah ditentukan atas rezeki yang Allah telah berikan kepada mereka berupa binatang ternak. Maka makanlah sebahagian daripadanya dan (sebahagian lagi) berikanlah untuk dimakan orang-orang yang sengsara lagi fakir.<?php break;}
case 29:{?>Kemudian hendaklah mereka menghilangkan kotoran yang ada pada badan mereka dan hendaklah mereka menyempurnakan nazar-nazar mereka dan hendaklah mereka melakukan tawaf sekeliling rumah yang tua itu (Baitullah).<?php break;}
case 30:{?>Demikianlah (perintah Allah). Dan barang siapa mengagungkan apa-apa yang terhormat di sisi Allah maka itu adalah lebih baik baginya di sisi Tuhannya. Dan telah dihalalkan bagi kamu semua binatang ternak, terkecuali yang diterangkan kepadamu keharamannya, maka jauhilah olehmu berhala-berhala yang najis itu dan jauhilah perkataan-perkataan dusta.<?php break;}
case 31:{?>dengan ikhlas kepada Allah, tidak mempersekutukan sesuatu dengan Dia. Barang siapa mempersekutukan sesuatu dengan Allah, maka adalah ia seolah-olah jatuh dari langit lalu disambar oleh burung, atau diterbangkan angin ke tempat yang jauh.<?php break;}
case 32:{?>Demikianlah (perintah Allah). Dan barang siapa mengagungkan syiar-syiar Allah, maka sesungguhnya itu timbul dari ketakwaan hati.<?php break;}
case 33:{?>Bagi kamu pada binatang-binatang hadyu, itu ada beberapa manfaat, sampai kepada waktu yang ditentukan, kemudian tempat wajib (serta akhir masa) menyembelihnya ialah setelah sampai ke Baitul Atiq (Baitullah).<?php break;}
case 34:{?>Dan bagi tiap-tiap umat telah Kami syariatkan penyembelihan (kurban), supaya mereka menyebut nama Allah terhadap binatang ternak yang telah direzekikan Allah kepada mereka, maka Tuhanmu ialah Tuhan Yang Maha Esa, karena itu berserah dirilah kamu kepada-Nya. Dan berilah kabar gembira kepada orang-orang yang tunduk patuh (kepada Allah),<?php break;}
case 35:{?>(yaitu) orang-orang yang apabila disebut nama Allah gemetarlah hati mereka, orang-orang yang sabar terhadap apa yang menimpa mereka, orang-orang yang mendirikan sembahyang dan orang-orang yang menafkahkan sebagian dari apa yang telah Kami rezekikan kepada mereka.<?php break;}
case 36:{?>Dan telah Kami jadikan untuk kamu unta-unta itu sebahagian dari syiar Allah, kamu memperoleh kebaikan yang banyak padanya, maka sebutlah olehmu nama Allah ketika kamu menyembelihnya dalam keadaan berdiri (dan telah terikat). Kemudian apabila telah roboh (mati), maka makanlah sebagiannya dan beri makanlah orang yang rela dengan apa yang ada padanya (yang tidak meminta-minta) dan orang yang meminta. Demikianlah Kami telah menundukkan unta-unta itu kepada kamu, mudah-mudahan kamu bersyukur.<?php break;}
case 37:{?>Daging-daging unta dan darahnya itu sekali-kali tidak dapat mencapai (keridaan) Allah, tetapi ketakwaan dari kamulah yang dapat mencapainya. Demikianlah Allah telah menundukkannya untuk kamu supaya kamu mengagungkan Allah terhadap hidayah-Nya kepada kamu. Dan berilah kabar gembira kepada orang-orang yang berbuat baik.<?php break;}
case 38:{?>Sesungguhnya Allah membela orang-orang yang telah beriman. Sesungguhnya Allah tidak menyukai tiap-tiap orang yang berkhianat lagi mengingkari nikmat.<?php break;}
case 39:{?>Telah diizinkan (berperang) bagi orang-orang yang diperangi, karena sesungguhnya mereka telah dianiaya. Dan sesungguhnya Allah, benar-benar Maha Kuasa menolong mereka itu.<?php break;}
case 40:{?>(yaitu) orang-orang yang telah diusir dari kampung halaman mereka tanpa alasan yang benar, kecuali karena mereka berkata: &quot;Tuhan kami hanyalah Allah&quot;. Dan sekiranya Allah tiada menolak (keganasan) sebagian manusia dengan sebagian yang lain, tentulah telah dirobohkan biara-biara Nasrani, gereja-gereja, rumah-rumah ibadah orang Yahudi dan mesjid-mesjid, yang di dalamnya banyak disebut nama Allah. Sesungguhnya Allah pasti menolong orang yang menolong (agama) -Nya. Sesungguhnya Allah benar-benar Maha Kuat lagi Maha Perkasa.<?php break;}
case 41:{?>(yaitu) orang-orang yang jika Kami teguhkan kedudukan mereka di muka bumi, niscaya mereka mendirikan sembahyang, menunaikan zakat, menyuruh berbuat yang makruf dan mencegah dari perbuatan yang mungkar; dan kepada Allah-lah kembali segala urusan.<?php break;}
case 42:{?>Dan jika mereka (orang-orang musyrik) mendustakan kamu, maka sesungguhnya telah mendustakan juga sebelum mereka kaum Nuh, Ad dan Tsamud.<?php break;}
case 43:{?>dan kaum Ibrahim dan kaum Lut,<?php break;}
case 44:{?>dan penduduk Madyan, dan telah didustakan Musa, lalu Aku tangguhkan (azab-Ku) untuk orang-orang kafir, kemudian Aku azab mereka, maka (lihatlah) bagaimana besarnya kebencian-Ku (kepada mereka itu).<?php break;}
case 45:{?>Berapa banyak kota yang Kami telah membinasakannya, yang penduduknya dalam keadaan lalim, maka (tembok-tembok) kota itu roboh menutupi atap-atapnya dan (berapa banyak pula) sumur yang telah ditinggalkan dan istana yang tinggi,<?php break;}
case 46:{?>maka apakah mereka tidak berjalan di muka bumi, lalu mereka mempunyai hati yang dengan itu mereka dapat memahami atau mempunyai telinga yang dengan itu mereka dapat mendengar? Karena sesungguhnya bukanlah mata itu yang buta, tetapi yang buta, ialah hati yang di dalam dada.<?php break;}
case 47:{?>Dan mereka meminta kepadamu agar azab itu disegerakan, padahal Allah sekali-kali tidak akan menyalahi janji-Nya. Sesungguhnya sehari di sisi Tuhanmu adalah seperti seribu tahun menurut perhitunganmu.<?php break;}
case 48:{?>Dan berapalah banyaknya kota yang Aku tangguhkan (azab-Ku) kepadanya, yang penduduknya berbuat lalim, kemudian Aku azab mereka, dan hanya kepada-Ku lah kembalinya (segala sesuatu).<?php break;}
case 49:{?>Katakanlah: &quot;Hai manusia, sesungguhnya aku adalah seorang pemberi peringatan yang nyata kepada kamu&quot;.<?php break;}
case 50:{?>Maka orang-orang yang beriman dan mengerjakan amal-amal yang saleh, bagi mereka ampunan dan rezeki yang mulia.<?php break;}
case 51:{?>Dan orang-orang yang berusaha dengan maksud menentang ayat-ayat Kami dengan melemahkan (kemauan untuk beriman); mereka itu adalah penghuni-penghuni neraka.<?php break;}
case 52:{?>Dan Kami tidak mengutus sebelum kamu seorang rasul pun dan tidak (pula) seorang nabi, melainkan apabila ia mempunyai sesuatu keinginan, setan pun memasukkan godaan-godaan terhadap keinginan itu, Allah menghilangkan apa yang dimasukkan oleh setan itu, dan Allah menguatkan ayat-ayat-Nya. Dan Allah Maha Mengetahui lagi Maha Bijaksana,<?php break;}
case 53:{?>agar Dia menjadikan apa yang dimasukkan oleh setan itu, sebagai cobaan bagi orang-orang yang di dalam hatinya ada penyakit dan yang kasar hatinya. Dan sesungguhnya orang-orang yang lalim itu, benar-benar dalam permusuhan yang sangat,<?php break;}
case 54:{?>dan agar orang-orang yang telah diberi ilmu, meyakini bahwasanya Al Qur'an itulah yang hak dari Tuhanmu lalu mereka beriman dan tunduk hati mereka kepadanya, dan sesungguhnya Allah adalah Pemberi petunjuk bagi orang-orang yang beriman kepada jalan yang lurus.<?php break;}
case 55:{?>Dan senantiasalah orang-orang kafir itu berada dalam keragu-raguan terhadap Al Qur'an, hingga datang kepada mereka saat (kematiannya) dengan tiba-tiba atau datang kepada mereka azab hari kiamat.<?php break;}
case 56:{?>Kekuasaan di hari itu ada pada Allah, Dia memberi keputusan di antara mereka. Maka orang-orang yang beriman dan beramal saleh adalah di dalam surga yang penuh kenikmatan.<?php break;}
case 57:{?>Dan orang-orang yang kafir dan mendustakan ayat-ayat Kami, maka bagi mereka azab yang menghinakan.<?php break;}
case 58:{?>Dan orang-orang yang berhijrah di jalan Allah, kemudian mereka dibunuh atau mati, benar-benar Allah akan memberikan kepada mereka rezeki yang baik (surga). Dan sesungguhnya Allah adalah sebaik-baik pemberi rezeki.<?php break;}
case 59:{?>Sesungguhnya Allah akan memasukkan mereka ke dalam suatu tempat (surga) yang mereka menyukainya. Dan sesungguhnya Allah Maha Mengetahui lagi Maha Penyantun.<?php break;}
case 60:{?>Demikianlah, dan barang siapa membalas seimbang dengan penganiayaan yang pernah ia derita kemudian ia dianiaya lagi, pasti Allah akan menolongnya. Sesungguhnya Allah benar-benar Maha Pemaaf lagi Maha Pengampun.<?php break;}
case 61:{?>Yang demikian itu, adalah karena sesungguhnya Allah (kuasa) memasukkan malam ke dalam siang dan memasukkan siang ke dalam malam dan bahwasanya Allah Maha Mendengar lagi Maha Melihat.<?php break;}
case 62:{?>(Kuasa Allah) yang demikian itu, adalah karena sesungguhnya Allah, Dialah (Tuhan) Yang Hak dan sesungguhnya apa saja yang mereka seru selain Allah, itulah yang batil, dan sesungguhnya Allah, Dialah Yang Maha Tinggi lagi Maha Besar.<?php break;}
case 63:{?>Apakah kamu tiada melihat, bahwasanya Allah menurunkan air dari langit, lalu jadilah bumi itu hijau? Sesungguhnya Allah Maha Halus lagi Maha Mengetahui.<?php break;}
case 64:{?>Kepunyaan Allah-lah segala yang ada di langit dan segala yang ada di bumi. Dan sesungguhnya Allah benar-benar Maha Kaya lagi Maha Terpuji.<?php break;}
case 65:{?>Apakah kamu tiada melihat bahwasanya Allah menundukkan bagimu apa yang ada di bumi dan bahtera yang berlayar di lautan dengan perintah-Nya. Dan Dia menahan (benda-benda) langit jatuh ke bumi, melainkan dengan izin-Nya? Sesungguhnya Allah benar-benar Maha Pengasih lagi Maha Penyayang kepada Manusia.<?php break;}
case 66:{?>Dan Dialah Allah yang telah menghidupkan kamu, kemudian mematikan kamu, kemudian menghidupkan kamu (lagi), sesungguhnya manusia itu, benar-benar sangat mengingkari nikmat.<?php break;}
case 67:{?>Bagi tiap-tiap umat telah Kami tetapkan syariat tertentu yang mereka lakukan, maka janganlah sekali-kali mereka membantah kamu dalam urusan (syariat) ini dan serulah kepada (agama) Tuhanmu. Sesungguhnya kamu benar-benar berada pada jalan yang lurus.<?php break;}
case 68:{?>Dan jika mereka membantah kamu, maka katakanlah: &quot;Allah lebih mengetahui tentang apa yang kamu kerjakan&quot;.<?php break;}
case 69:{?>Allah akan mengadili di antara kamu pada hari kiamat tentang apa yang kamu dahulu selalu berselisih padanya.<?php break;}
case 70:{?>Apakah kamu tidak mengetahui bahwa sesungguhnya Allah mengetahui apa saja yang ada di langit dan di bumi?; bahwasanya yang demikian itu terdapat dalam sebuah kitab (Lohmahfuz) Sesungguhnya yang demikian itu amat mudah bagi Allah.<?php break;}
case 71:{?>Dan mereka menyembah selain Allah, apa yang Allah tidak menurunkan keterangan tentang itu, dan apa yang mereka sendiri tiada mempunyai pengetahuan terhadapnya. Dan bagi orang-orang yang lalim sekali-kali tidak ada seorang penolong pun.<?php break;}
case 72:{?>Dan apabila dibacakan di hadapan mereka ayat-ayat Kami yang terang, niscaya kamu melihat tanda-tanda keingkaran pada muka orang-orang yang kafir itu. Hampir-hampir mereka menyerang orang-orang yang membacakan ayat-ayat Kami di hadapan mereka. Katakanlah: &quot;Apakah akan aku kabarkan kepadamu yang lebih buruk daripada itu, yaitu neraka?&quot;. Allah telah mengancamkannya kepada orang-orang yang kafir. Dan neraka itu adalah seburuk-buruknya tempat kembali.<?php break;}
case 73:{?>Hai manusia, telah dibuat perumpamaan, maka dengarkanlah olehmu perumpamaan itu. Sesungguhnya segala yang kamu seru selain Allah sekali-kali tidak dapat menciptakan seekor lalat pun, walaupun mereka bersatu untuk menciptakannya. Dan jika lalat itu merampas sesuatu dari mereka, tiadalah mereka dapat merebutnya kembali dari lalat itu. Amat lemahlah yang menyembah dan amat lemah (pulalah) yang disembah.<?php break;}
case 74:{?>Mereka tidak mengenal Allah dengan sebenar-benarnya. Sesungguhnya Allah benar-benar Maha Kuat lagi Maha Perkasa.<?php break;}
case 75:{?>Allah memilih utusan-utusan (Nya) dari malaikat dan dari manusia; sesungguhnya Allah Maha Mendengar lagi Maha Melihat.<?php break;}
case 76:{?>Allah mengetahui apa yang di hadapan mereka dan apa yang di belakang mereka. Dan hanya kepada Allah dikembalikan semua urusan.<?php break;}
case 77:{?>Hai orang-orang yang beriman, rukuklah kamu, sujudlah kamu, sembahlah Tuhanmu dan perbuatlah kebajikan, supaya kamu mendapat kemenangan.<?php break;}
case 78:{?>Dan berjihadlah kamu pada jalan Allah dengan jihad yang sebenar-benarnya. Dia telah memilih kamu dan Dia sekali-kali tidak menjadikan untuk kamu dalam agama suatu kesempitan. (Ikutilah) agama orang tuamu Ibrahim. Dia (Allah) telah menamai kamu sekalian orang-orang muslim dari dahulu, dan (begitu pula) dalam (Al Qur'an) ini, supaya Rasul itu menjadi saksi atas dirimu dan supaya kamu semua menjadi saksi atas segenap manusia, maka dirikanlah sembahyang, tunaikanlah zakat dan berpeganglah kamu pada tali Allah. Dia adalah Pelindungmu, maka Dialah sebaik-baik Pelindung dan sebaik-baik Penolong.<?php break;}
}?>