<?php 
switch($verse){
case 1:{?>Thaa Siin (Surat) ini adalah ayat-ayat Al Qur'an, dan (ayat-ayat) Kitab yang menjelaskan,<?php break;}
case 2:{?>untuk menjadi petunjuk dan berita gembira untuk orang-orang yang beriman,<?php break;}
case 3:{?>(yaitu) orang-orang yang mendirikan sembahyang dan menunaikan zakat dan mereka yakin akan adanya negeri akhirat.<?php break;}
case 4:{?>Sesungguhnya orang-orang yang tidak beriman kepada negeri akhirat, Kami jadikan mereka memandang indah perbuatan-perbuatan mereka, maka mereka bergelimang (dalam kesesatan).<?php break;}
case 5:{?>Mereka itulah orang-orang yang mendapat (di dunia) azab yang buruk dan mereka di akhirat adalah orang-orang yang paling merugi.<?php break;}
case 6:{?>Dan sesungguhnya kamu benar-benar diberi Al Qur'an dari sisi (Allah) Yang Maha Bijaksana lagi Maha Mengetahui.<?php break;}
case 7:{?>(Ingatlah) ketika Musa berkata kepada keluarganya: &quot;Sesungguhnya aku melihat api. Aku kelak akan membawa kepadamu kabar daripadanya, atau aku membawa kepadamu suluh api supaya kamu dapat berdiang&quot;.<?php break;}
case 8:{?>Maka tatkala dia tiba di (tempat) api itu, diserulah dia: &quot;Bahwa telah diberkati orang-orang yang berada di dekat api itu, dan orang-orang yang berada di sekitarnya. Dan Maha Suci Allah, Tuhan semesta Alam&quot;.<?php break;}
case 9:{?>(Allah berfirman): &quot;Hai Musa, sesungguhnya Akulah Allah, Yang Maha Perkasa lagi Maha Bijaksana,<?php break;}
case 10:{?>dan lemparkanlah tongkatmu&quot;. Maka tatkala (tongkat itu menjadi ular dan) Musa melihatnya bergerak-gerak seperti dia seekor ular yang gesit, larilah ia berbalik ke belakang tanpa menoleh. &quot;Hai Musa, janganlah kamu takut. Sesungguhnya orang yang dijadikan rasul, tidak takut di hadapan-Ku.<?php break;}
case 11:{?>tetapi orang yang berlaku lalim, kemudian ditukarnya kezalimannya dengan kebaikan (Allah akan mengampuninya); maka sesungguhnya Aku Maha Pengampun lagi Maha Penyayang.<?php break;}
case 12:{?>Dan masukkanlah tanganmu ke leher bajumu, niscaya ia akan ke luar putih (bersinar) bukan karena penyakit. (Kedua mukjizat ini) termasuk sembilan buah mukjizat (yang akan dikemukakan) kepada Firaun dan kaumnya. Sesungguhnya mereka adalah kaum yang fasik&quot;.<?php break;}
case 13:{?>Maka tatkala mukjizat-mukjizat Kami yang jelas itu sampai kepada mereka, berkatalah mereka: &quot;Ini adalah sihir yang nyata&quot;.<?php break;}
case 14:{?>Dan mereka mengingkarinya karena kelaliman dan kesombongan (mereka) padahal hati mereka meyakini (kebenaran) nya. Maka perhatikanlah betapa kesudahan orang-orang yang berbuat kebinasaan.<?php break;}
case 15:{?>Dan sesungguhnya Kami telah memberi ilmu kepada Daud dan Sulaiman; dan keduanya mengucapkan: &quot;Segala puji bagi Allah yang melebihkan kami dari kebanyakan hamba-hamba-Nya yang beriman&quot;.<?php break;}
case 16:{?>Dan Sulaiman telah mewarisi Daud, dan dia berkata: &quot;Hai Manusia, kami telah diberi pengertian tentang suara burung dan kami diberi segala sesuatu. Sesungguhnya (semua) ini benar-benar suatu karunia yang nyata&quot;.<?php break;}
case 17:{?>Dan dihimpunkan untuk Sulaiman tentaranya dari jin, manusia dan burung lalu mereka itu diatur dengan tertib (dalam barisan).<?php break;}
case 18:{?>Hingga apabila mereka sampai di lembah semut berkatalah seekor semut: Hai semut-semut, masuklah ke dalam sarang-sarangmu, agar kamu tidak diinjak oleh Sulaiman dan tentaranya, sedangkan mereka tidak menyadari&quot;;<?php break;}
case 19:{?>maka dia tersenyum dengan tertawa karena (mendengar) perkataan semut itu. Dan dia berdoa: &quot;Ya Tuhanku, berilah aku ilham untuk tetap mensyukuri nikmat-Mu yang telah Engkau anugerahkan kepadaku dan kepada dua orang ibu bapakku dan untuk mengerjakan amal saleh yang Engkau ridai; dan masukkanlah aku dengan rahmat-Mu ke dalam golongan hamba-hamba-Mu yang saleh&quot;.<?php break;}
case 20:{?>Dan dia memeriksa burung-burung lalu berkata: &quot;Mengapa aku tidak melihat hud-hud, apakah dia termasuk yang tidak hadir.<?php break;}
case 21:{?>Sungguh aku benar-benar akan mengazabnya dengan azab yang keras, atau benar-benar menyembelihnya kecuali jika benar-benar dia datang kepadaku dengan alasan yang terang&quot;.<?php break;}
case 22:{?>Maka tidak lama kemudian (datanglah hud-hud), lalu ia berkata: &quot;Aku telah mengetahui sesuatu yang kamu belum mengetahuinya; dan kubawa kepadamu dari negeri Saba suatu berita penting yang diyakini,<?php break;}
case 23:{?>Sesungguhnya aku menjumpai seorang wanita yang memerintah mereka, dan dia dianugerahi segala sesuatu serta mempunyai singgasana yang besar.<?php break;}
case 24:{?>Aku mendapati dia dan kaumnya menyembah matahari, selain Allah; dan setan telah menjadikan mereka memandang indah perbuatan-perbuatan mereka lalu menghalangi mereka dari jalan (Allah), sehingga mereka tidak dapat petunjuk,<?php break;}
case 25:{?>agar mereka tidak menyembah Allah Yang mengeluarkan apa yang terpendam di langit dan di bumi dan Yang mengetahui apa yang kamu sembunyikan dan apa yang kamu nyatakan.<?php break;}
case 26:{?>Allah, tiada Tuhan (yang berhak disembah) kecuali Dia, Tuhan Yang mempunyai Arasy yang besar&quot;.<?php break;}
case 27:{?>Berkata Sulaiman: &quot;Akan kami lihat, apa kamu benar, ataukah kamu termasuk orang-orang yang berdusta.<?php break;}
case 28:{?>Pergilah dengan (membawa) suratku ini, lalu jatuhkanlah kepada mereka, kemudian berpalinglah dari mereka, lalu perhatikanlah apa yang mereka bicarakan&quot;<?php break;}
case 29:{?>Berkata ia (Balqis): &quot;Hai pembesar-pembesar, sesungguhnya telah dijatuhkan kepadaku sebuah surat yang mulia.<?php break;}
case 30:{?>Sesungguhnya surat itu, dari Sulaiman dan sesungguhnya (isi) nya: &quot;Dengan menyebut nama Allah Yang Maha Pemurah lagi Maha Penyayang.<?php break;}
case 31:{?>Bahwa janganlah kamu sekalian berlaku sombong terhadapku dan datanglah kepadaku sebagai orang-orang berserah diri&quot;.<?php break;}
case 32:{?>Berkata dia (Balqis): &quot;Hai para pembesar berilah aku pertimbangan dalam urusanku (ini) aku tidak pernah memutuskan sesuatu persoalan sebelum kamu berada dalam majelis (ku)&quot;.<?php break;}
case 33:{?>Mereka menjawab: &quot;Kita adalah orang-orang yang memiliki kekuatan dan (juga) memiliki keberanian yang sangat (dalam peperangan), dan keputusan berada di tanganmu; maka pertimbangkanlah apa yang akan kamu perintahkan&quot;.<?php break;}
case 34:{?>Dia berkata: &quot;Sesungguhnya raja-raja apabila memasuki suatu negeri, niscaya mereka membinasakannya, dan menjadikan penduduknya yang mulia jadi hina; dan demikian pulalah yang akan mereka perbuat.<?php break;}
case 35:{?>Dan sesungguhnya aku akan mengirim utusan kepada mereka dengan (membawa) hadiah, dan (aku akan) menunggu apa yang akan dibawa kembali oleh utusan-utusan itu.<?php break;}
case 36:{?>Maka tatkala utusan itu sampai kepada Sulaiman, Sulaiman berkata: &quot;Apakah (patut) kamu menolong aku dengan harta? maka apa yang diberikan Allah kepadaku lebih baik daripada apa yang diberikan-Nya kepadamu; tetapi kamu merasa bangga dengan hadiahmu.<?php break;}
case 37:{?>Kembalilah kepada mereka sungguh kami akan mendatangi mereka dengan bala tentara yang mereka tidak kuasa melawannya, dan pasti kami akan mengusir mereka dari negeri itu (Saba) dengan terhina dan mereka menjadi (tawanan-tawanan) yang hina dina&quot;.<?php break;}
case 38:{?>Berkata Sulaiman: &quot;Hai pembesar-pembesar, siapakah di antara kamu sekalian yang sanggup membawa singgasananya kepadaku sebelum mereka datang kepadaku sebagai orang-orang yang berserah diri&quot;.<?php break;}
case 39:{?>Berkata 'Ifrit (yang cerdik) dari golongan jin: &quot;Aku akan datang kepadamu dengan membawa singgasana itu kepadamu sebelum kamu berdiri dari tempat dudukmu; sesungguhnya aku benar-benar kuat untuk membawanya lagi dapat dipercaya&quot;.<?php break;}
case 40:{?>Berkatalah seorang yang mempunyai ilmu dari Al Kitab: &quot;Aku akan membawa singgasana itu kepadamu sebelum matamu berkedip&quot;. Maka tatkala Sulaiman melihat singgasana itu terletak di hadapannya, iapun berkata: &quot;Ini termasuk kurnia Tuhanku untuk mencoba aku apakah aku bersyukur atau mengingkari (akan nikmat-Nya). Dan barang siapa yang bersyukur maka sesungguhnya dia bersyukur untuk (kebaikan) dirinya sendiri dan barang siapa yang ingkar, maka sesungguhnya Tuhanku Maha Kaya lagi Maha Mulia&quot;.<?php break;}
case 41:{?>Dia berkata: &quot;Robahlah baginya singgasananya; maka kita akan melihat apakah dia mengenal ataukah dia termasuk orang-orang yang tidak mengenal (nya)&quot;.<?php break;}
case 42:{?>Dan ketika Balqis datang, ditanyakanlah kepadanya: &quot;Serupa inikah singgasanamu?&quot; Dia menjawab: &quot;Seakan-akan singgasana ini singgasanaku, kami telah diberi pengetahuan sebelumnya dan kami adalah orang-orang yang berserah diri&quot;.<?php break;}
case 43:{?>Dan apa yang disembahnya selama ini selain Allah, mencegahnya (untuk melahirkan keislamannya), karena sesungguhnya dia dahulunya termasuk orang-orang yang kafir.<?php break;}
case 44:{?>Dikatakan kepadanya: &quot;Masuklah ke dalam istana&quot;. Maka tatkala dia melihat lantai istana itu, dikiranya kolam air yang besar, dan disingkapkannya kedua betisnya. Berkatalah Sulaiman: &quot;Sesungguhnya ia adalah istana licin terbuat dari kaca&quot;. Berkatalah Balqis: &quot;Ya Tuhanku, sesungguhnya aku telah berbuat lalim terhadap diriku dan aku berserah diri bersama Sulaiman kepada Allah, Tuhan semesta alam&quot;.<?php break;}
case 45:{?>Dan sesungguhnya Kami telah mengutus kepada (kaum) Tsamud saudara mereka Saleh (yang berseru): &quot;Sembahlah Allah&quot;. Tetapi tiba-tiba mereka (jadi) dua golongan yang bermusuhan.<?php break;}
case 46:{?>Dia berkata: &quot;Hai kaumku mengapa kamu minta disegerakan keburukan sebelum (kamu minta) kebaikan? Hendaklah kamu meminta ampun kepada Allah, agar kamu mendapat rahmat&quot;.<?php break;}
case 47:{?>Mereka menjawab: &quot;Kami mendapat nasib yang malang, disebabkan kamu dan orang-orang yang besertamu&quot;. Saleh berkata: &quot;Nasibmu ada pada sisi Allah, (bukan kami yang menjadi sebab), tetapi kamu kaum yang diuji&quot;.<?php break;}
case 48:{?>Dan adalah di kota itu, sembilan orang laki-laki yang membuat kerusakan di muka bumi, dan mereka tidak berbuat kebaikan.<?php break;}
case 49:{?>Mereka berkata: &quot;Bersumpahlah kamu dengan nama Allah, bahwa kita sungguh-sungguh akan menyerangnya dengan tiba-tiba beserta keluarganya di malam hari, kemudian kita katakan kepada warisnya (bahwa) kita tidak menyaksikan kematian keluarganya itu, dan sesungguhnya kita adalah orang-orang yang benar&quot;.<?php break;}
case 50:{?>Dan merekapun merencanakan makar dengan sungguh-sungguh dan Kami merencanakan makar (pula), sedang mereka tidak menyadari.<?php break;}
case 51:{?>Maka perhatikanlah betapa sesungguhnya akibat makar mereka itu, bahwasanya Kami membinasakan mereka dan kaum mereka semuanya.<?php break;}
case 52:{?>Maka itulah rumah-rumah mereka dalam keadaan runtuh disebabkan kelaliman mereka. Sesungguhnya pada yang demikian itu (terdapat) pelajaran bagi kaum yang mengetahui.<?php break;}
case 53:{?>Dan telah Kami selamatkan orang-orang yang beriman dan mereka itu selalu bertakwa.<?php break;}
case 54:{?>Dan (ingatlah kisah) Lut, ketika dia berkata kepada kaumnya: &quot;Mengapa kamu mengerjakan perbuatan fahisyah itu sedang kamu melihat (nya)?&quot;<?php break;}
case 55:{?>Mengapa kamu mendatangi laki-laki untuk (memenuhi) nafsu (mu), bukan (mendatangi) wanita? Sebenarnya kamu adalah kaum yang tidak mengetahui (akibat perbuatanmu)&quot;.<?php break;}
case 56:{?>Maka tidak lain jawaban kaumnya melainkan mengatakan: &quot;Usirlah Lut beserta keluarganya dari negerimu; karena sesungguhnya mereka itu orang-orang yang (mendakwakan dirinya) bersih&quot;.<?php break;}
case 57:{?>Maka Kami selamatkan dia beserta keluarganya, kecuali istrinya. Kami telah menakdirkan dia termasuk orang-orang yang tertinggal (dibinasakan).<?php break;}
case 58:{?>Dan Kami turunkan hujan atas mereka (hujan batu), maka amat buruklah hujan yang ditimpakan atas orang-orang yang diberi peringatan itu.<?php break;}
case 59:{?>Katakanlah: &quot;Segala puji bagi Allah dan kesejahteraan atas hamba-hamba-Nya yang dipilih-Nya. Apakah Allah yang lebih baik, ataukah apa yang mereka persekutukan dengan Dia?&quot;<?php break;}
case 60:{?>Atau siapakah yang telah menciptakan langit dan bumi dan yang menurunkan air untukmu dari langit, lalu Kami tumbuhkan dengan air itu kebun-kebun yang berpemandangan indah, yang kamu sekali-kali tidak mampu menumbuhkan pohon-pohonnya? Apakah di samping Allah ada tuhan (yang lain)? Bahkan (sebenarnya) mereka adalah orang-orang yang menyimpang (dari kebenaran).<?php break;}
case 61:{?>Atau siapakah yang telah menjadikan bumi sebagai tempat berdiam, dan yang menjadikan sungai-sungai di celah-celahnya, dan yang menjadikan gunung-gunung untuk (mengokohkan) nya dan menjadikan suatu pemisah antara dua laut? Apakah di samping Allah ada tuhan (yang lain)? Bahkan (sebenarnya) kebanyakan dari mereka tidak mengetahui.<?php break;}
case 62:{?>Atau siapakah yang memperkenankan (doa) orang yang dalam kesulitan apabila ia berdoa kepada-Nya, dan yang menghilangkan kesusahan dan yang menjadikan kamu (manusia) sebagai khalifah di bumi? Apakah di samping Allah ada tuhan (yang lain)? Amat sedikitlah kamu mengingati (Nya).<?php break;}
case 63:{?>Atau siapakah yang memimpin kamu dalam kegelapan di daratan dan lautan dan siapa (pula) kah yang mendatangkan angin sebagai kabar gembira sebelum (kedatangan) rahmat-Nya? Apakah di samping Allah ada tuhan (yang lain)? Maha Tinggi Allah terhadap apa yang mereka persekutukan (dengan-Nya).<?php break;}
case 64:{?>Atau siapakah yang menciptakan (manusia dari permulaannya), kemudian mengulanginya (lagi), dan siapa (pula) yang memberikan rezeki kepadamu dari langit dan bumi? Apakah di samping Allah ada tuhan (yang lain)?. Katakanlah: &quot;Unjukkanlah bukti kebenaranmu, jika kamu memang orang-orang yang benar&quot;.<?php break;}
case 65:{?>Katakanlah: &quot;Tidak ada seorang pun di langit dan di bumi yang mengetahui perkara yang gaib, kecuali Allah&quot;, dan mereka tidak mengetahui bila mereka akan dibangkitkan.<?php break;}
case 66:{?>Sebenarnya pengetahuan mereka tentang akhirat tidak sampai (kesana) malahan mereka ragu-ragu tentang akhirat itu, lebih-lebih lagi mereka buta daripadanya.<?php break;}
case 67:{?>Berkatalah orang-orang yang kafir; &quot;Apakah setelah kita menjadi tanah dan (begitu pula) bapak-bapak kita; apakah sesungguhnya kita akan dikeluarkan (dari kubur)?<?php break;}
case 68:{?>Sesungguhnya kami telah diberi ancaman dengan ini dan (juga) bapak-bapak kami dahulu; ini tidak lain hanyalah dongengan-dongengan orang dahulu kala&quot;.<?php break;}
case 69:{?>Katakanlah: &quot;Berjalanlah kamu (di muka) bumi, lalu perhatikanlah bagaimana akibat orang-orang yang berdosa.<?php break;}
case 70:{?>Dan janganlah kamu berduka cita terhadap mereka, dan janganlah (dadamu) merasa sempit terhadap apa yang mereka tipudayakan&quot;.<?php break;}
case 71:{?>Dan mereka (orang-orang kafir) berkata: &quot;Bilakah datangnya azab itu, jika memang kamu orang-orang yang benar&quot;.<?php break;}
case 72:{?>Katakanlah: &quot;Mungkin telah hampir datang kepadamu sebagian dari (azab) yang kamu minta (supaya) disegerakan itu.<?php break;}
case 73:{?>Dan sesungguhnya Tuhanmu benar-benar mempunyai karunia yang besar (yang diberikan-Nya) kepada manusia, tetapi kebanyakan mereka tidak mensyukuri (nya).<?php break;}
case 74:{?>Dan sesungguhnya Tuhanmu, benar-benar mengetahui apa yang disembunyikan hati mereka dan apa yang mereka nyatakan.<?php break;}
case 75:{?>Tiada sesuatu pun yang gaib di langit dan di bumi, melainkan (terdapat) dalam kitab yang nyata (Lohmahfuz).<?php break;}
case 76:{?>Sesungguhnya Al Qur'an ini menjelaskan kepada Bani Israel sebahagian besar dari (perkara-perkara) yang mereka berselisih tentangnya.<?php break;}
case 77:{?>Dan sesungguhnya Al Qur'an itu benar-benar menjadi petunjuk dan rahmat bagi orang-orang yang beriman.<?php break;}
case 78:{?>Sesungguhnya Tuhanmu akan menyelesaikan perkara antara mereka dengan keputusan-Nya, dan Dia Maha Perkasa lagi Maha Mengetahui.<?php break;}
case 79:{?>Sebab itu bertawakallah kepada Allah, sesungguhnya kamu berada di atas kebenaran yang nyata.<?php break;}
case 80:{?>Sesungguhnya kamu tidak dapat menjadikan orang-orang yang mati mendengar dan (tidak pula) menjadikan orang-orang yang tuli mendengar panggilan, apabila mereka telah berpaling membelakang.<?php break;}
case 81:{?>Dan kamu sekali-kali tidak dapat memimpin (memalingkan) orang-orang buta dari kesesatan mereka. Kamu tidak dapat menjadikan (seorang pun) mendengar, kecuali orang-orang yang beriman kepada ayat-ayat Kami, lalu mereka berserah diri.<?php break;}
case 82:{?>Dan apabila perkataan telah jatuh atas mereka, Kami keluarkan sejenis binatang melata dari bumi yang akan mengatakan kepada mereka, bahwa sesungguhnya manusia dahulu tidak yakin kepada ayat-ayat Kami.<?php break;}
case 83:{?>Dan (ingatlah) hari (ketika) Kami kumpulkan dari tiap-tiap umat segolongan orang-orang yang mendustakan ayat-ayat Kami, lalu mereka dibagi-bagi (dalam kelompok-kelompok).<?php break;}
case 84:{?>Hingga apabila mereka datang, Allah berfirman: &quot;Apakah kamu telah mendustakan ayat-ayat-Ku, padahal ilmu kamu tidak meliputinya, atau apakah yang telah kamu kerjakan?&quot;<?php break;}
case 85:{?>Dan jatuhlah perkataan (azab) atas mereka disebabkan kelaliman mereka, maka mereka tidak dapat berkata (apa-apa).<?php break;}
case 86:{?>Apakah mereka tidak memperhatikan, bahwa sesungguhnya Kami telah menjadikan malam supaya mereka beristirahat padanya dan siang yang menerangi? Sesungguhnya pada yang demikian itu terdapat tanda-tanda (kekuasaan Allah) bagi orang-orang yang beriman.<?php break;}
case 87:{?>Dan (ingatlah) hari (ketika) ditiup sangkakala, maka terkejutlah segala yang di langit dan segala yang di bumi, kecuali siapa yang dikehendaki Allah. Dan semua mereka datang menghadap-Nya dengan merendahkan diri.<?php break;}
case 88:{?>Dan kamu lihat gunung-gunung itu, kamu sangka dia tetap di tempatnya, padahal ia berjalan sebagai jalannya awan. (Begitulah) perbuatan Allah yang membuat dengan kokoh tiap-tiap sesuatu; sesungguhnya Allah Maha Mengetahui apa yang kamu kerjakan.<?php break;}
case 89:{?>Barang siapa yang membawa kebaikan, maka ia memperoleh (balasan) yang lebih baik daripadanya, sedang mereka itu adalah orang-orang yang aman tenteram dari kejutan yang dahsyat pada hari itu.<?php break;}
case 90:{?>Dan barang siapa yang membawa kejahatan, maka disungkurkanlah muka mereka ke dalam neraka. Tiadalah kamu dibalasi, melainkan (setimpal) dengan apa yang dahulu kamu kerjakan.<?php break;}
case 91:{?>Aku hanya diperintahkan untuk menyembah Tuhan negeri ini (Mekah) Yang telah menjadikannya suci dan kepunyaan-Nya-lah segala sesuatu, dan aku diperintahkan supaya aku termasuk orang-orang yang berserah diri.<?php break;}
case 92:{?>Dan supaya aku membacakan Al Qur'an (kepada manusia). Maka barang siapa yang mendapat petunjuk maka sesungguhnya ia hanyalah mendapat petunjuk untuk (kebaikan) dirinya, dan barang siapa yang sesat maka katakanlah: &quot;Sesungguhnya aku (ini) tidak lain hanyalah salah seorang pemberi peringatan&quot;.<?php break;}
case 93:{?>Dan katakanlah: &quot;Segala puji bagi Allah, Dia akan memperlihatkan kepadamu tanda-tanda kebesaran-Nya, maka kamu akan mengetahuinya. Dan Tuhanmu tiada lalai dari apa yang kamu kerjakan&quot;.<?php break;}
}?>