<?php 
switch($verse){
case 1:{?>Thaa Siin Miim<?php break;}
case 2:{?>Ini adalah ayat-ayat Kitab (Al Qur'an) yang nyata (dari Allah).<?php break;}
case 3:{?>Kami membacakan kepadamu sebagian dari kisah Musa dan Firaun dengan benar untuk orang-orang yang beriman.<?php break;}
case 4:{?>Sesungguhnya Firaun telah berbuat sewenang-wenang di muka bumi dan menjadikan penduduknya berpecah belah, dengan menindas segolongan dari mereka, menyembelih anak laki-laki mereka dan membiarkan hidup anak-anak perempuan mereka. Sesungguhnya Firaun termasuk orang-orang yang berbuat kerusakan.<?php break;}
case 5:{?>Dan Kami hendak memberi karunia kepada orang-orang yang tertindas di bumi (Mesir) itu dan hendak menjadikan mereka pemimpin dan menjadikan mereka orang-orang yang mewarisi (bumi),<?php break;}
case 6:{?>dan akan Kami teguhkan kedudukan mereka di muka bumi dan akan Kami perlihatkan kepada Firaun dan Haman beserta tentaranya apa yang selalu mereka khawatirkan dari mereka itu<?php break;}
case 7:{?>Dan Kami ilhamkan kepada ibu Musa; &quot;Susuilah dia, dan apabila kamu khawatir terhadapnya maka jatuhkanlah dia ke sungai (Nil). Dan janganlah kamu khawatir dan janganlah (pula) bersedih hati, karena sesungguhnya Kami akan mengembalikannya kepadamu, dan menjadikannya (salah seorang) dari para rasul.<?php break;}
case 8:{?>Maka dipungutlah ia oleh keluarga Firaun yang akibatnya dia menjadi musuh dan kesedihan bagi mereka. Sesungguhnya Firaun dan Haman beserta tentaranya adalah orang-orang yang bersalah.<?php break;}
case 9:{?>Dan berkatalah istri Firaun: &quot;(Ia) adalah penyejuk mata hati bagiku dan bagimu. Janganlah kamu membunuhnya, mudah-mudahan ia bermanfaat kepada kita atau kita ambil ia menjadi anak&quot;, sedang mereka tiada menyadari.<?php break;}
case 10:{?>Dan menjadi kosonglah hati ibu Musa. Sesungguhnya hampir saja ia menyatakan rahasia tentang Musa, seandainya tidak Kami teguhkan hatinya, supaya ia termasuk orang-orang yang percaya (kepada janji Allah).<?php break;}
case 11:{?>Dan berkatalah ibu Musa kepada saudara Musa yang perempuan: &quot;Ikutilah dia&quot; Maka kelihatanlah olehnya Musa dari jauh, sedang mereka tidak mengetahuinya,<?php break;}
case 12:{?>dan Kami cegah Musa dari menyusu kepada perempuan-perempuan yang mau menyusui (nya) sebelum itu; maka berkatalah saudara Musa: &quot;Maukah kamu aku tunjukkan kepadamu ahlulbait yang akan memeliharanya untukmu dan mereka dapat berlaku baik kepadanya?&quot;.<?php break;}
case 13:{?>Maka Kami kembalikan Musa kepada ibunya, supaya senang hatinya dan tidak berduka cita dan supaya ia mengetahui bahwa janji Allah itu adalah benar, tetapi kebanyakan manusia tidak mengetahuinya.<?php break;}
case 14:{?>Dan setelah Musa cukup umur dan sempurna akalnya, Kami berikan kepadanya hikmah (kenabian) dan pengetahuan. Dan demikianlah Kami memberi balasan kepada orang-orang yang berbuat baik.<?php break;}
case 15:{?>Dan Musa masuk ke kota (Memphis) ketika penduduknya sedang lengah, maka didapatinya di dalam kota itu dua orang laki-laki yang berkelahi; yang seorang dari golongannya (Bani Israel) dan seorang (lagi) dari musuhnya (kaum Firaun). Maka orang yang dari golongannya meminta pertolongan kepadanya, untuk mengalahkan orang yang dari musuhnya lalu Musa meninjunya, dan matilah musuhnya itu. Musa berkata: &quot;Ini adalah perbuatan syaitan sesungguhnya syaitan itu adalah musuh yang menyesatkan lagi nyata (permusuhannya).<?php break;}
case 16:{?>Musa mendoa: &quot;Ya Tuhanku, sesungguhnya aku telah menganiaya diriku sendiri karena itu ampunilah aku&quot;. Maka Allah mengampuninya, sesungguhnya Allah Dialah Yang Maha Pengampun lagi Maha Penyayang.<?php break;}
case 17:{?>Musa berkata: &quot;Ya Tuhanku, demi nikmat yang telah Engkau anugerahkan kepadaku, aku sekali-kali tiada akan menjadi penolong bagi orang-orang yang berdosa&quot;.<?php break;}
case 18:{?>Karena itu, jadilah Musa di kota itu merasa takut menunggu-nunggu dengan khawatir (akibat perbuatannya), maka tiba-tiba orang yang meminta pertolongan kemarin berteriak meminta pertolongan kepadanya. Musa berkata kepadanya: &quot;Sesungguhnya kamu benar-benar orang sesat yang nyata (kesesatannya)&quot;.<?php break;}
case 19:{?>Maka tatkala Musa hendak memegang dengan keras orang yang menjadi musuh keduanya, musuhnya berkata: &quot;Hai Musa, apakah kamu bermaksud hendak membunuhku, sebagaimana kamu kemarin telah membunuh seorang manusia? Kamu tidak bermaksud melainkan hendak menjadi orang yang berbuat sewenang-wenang di negeri (ini), dan tiadalah kamu hendak menjadi salah seorang dari orang-orang yang mengadakan perdamaian&quot;.<?php break;}
case 20:{?>Dan datanglah seorang laki-laki dari ujung kota bergegas-gegas seraya berkata: &quot;Hai Musa, sesungguhnya pembesar negeri sedang berunding tentang kamu untuk membunuhmu, sebab itu keluarlah (dari kota ini) sesungguhnya aku termasuk orang-orang yang memberi nasihat kepadamu&quot;.<?php break;}
case 21:{?>Maka keluarlah Musa dari kota itu dengan rasa takut menunggu-nunggu dengan khawatir, dia berdoa: &quot;Ya Tuhanku, selamatkanlah aku dari orang-orang yang lalim itu&quot;.<?php break;}
case 22:{?>Dan tatkala ia menghadap kejurusan negeri Madyan ia berdoa (lagi): &quot;Mudah-mudahan Tuhanku memimpinku ke jalan yang benar&quot;.<?php break;}
case 23:{?>Dan tatkala ia sampai di sumber air negeri Mad-yan ia menjumpai di sana sekumpulan orang yang sedang meminumkan (ternaknya), dan ia menjumpai di belakang orang banyak itu, dua orang wanita yang sedang menghambat (ternaknya). Musa berkata: &quot;Apakah maksudmu (dengan berbuat begitu)?&quot; Kedua wanita itu menjawab: &quot;Kami tidak dapat meminumkan (ternak kami), sebelum pengembala-pengembala itu memulangkan (ternaknya), sedang bapak kami adalah orang tua yang telah lanjut umurnya&quot;.<?php break;}
case 24:{?>Maka Musa memberi minum ternak itu untuk (menolong) keduanya, kemudian dia kembali ke tempat yang teduh lalu berdoa: &quot;Ya Tuhanku sesungguhnya aku sangat memerlukan sesuatu kebaikan yang Engkau turunkan kepadaku&quot;.<?php break;}
case 25:{?>Kemudian datanglah kepada Musa salah seorang dari kedua wanita itu berjalan kemalu-maluan, ia berkata: &quot;Sesungguhnya bapakku memanggil kamu agar ia memberi balasan terhadap (kebaikan) mu memberi minum (ternak) kami&quot;. Maka tatkala Musa mendatangi bapaknya (Syuaib) dan menceritakan kepadanya cerita (mengenai dirinya). Syuaib berkata: &quot;Janganlah kamu takut. Kamu telah selamat dari orang-orang yang lalim itu&quot;.<?php break;}
case 26:{?>Salah seorang dari kedua wanita itu berkata: &quot;Ya bapakku ambillah ia sebagai orang yang bekerja (pada kita), karena sesungguhnya orang yang paling baik yang kamu ambil untuk bekerja (pada kita) ialah orang yang kuat lagi dapat dipercaya&quot;.<?php break;}
case 27:{?>Berkatalah dia (Syuaib): &quot;Sesungguhnya aku bermaksud menikahkan kamu dengan salah seorang dari kedua anakku ini, atas dasar bahwa kamu bekerja denganku delapan tahun dan jika kamu cukupkan sepuluh tahun maka itu adalah (suatu kebaikan) dari kamu, maka aku tidak hendak memberati kamu. Dan kamu insya Allah akan mendapatiku termasuk orang-orang yang baik&quot;.<?php break;}
case 28:{?>Dia (Musa) berkata: &quot;Itulah (perjanjian) antara aku dan kamu. Mana saja dari kedua waktu yang ditentukan itu aku sempurnakan, maka tidak ada tuntutan tambahan atas diriku (lagi). Dan Allah adalah saksi atas apa yang kita ucapkan&quot;.<?php break;}
case 29:{?>Maka tatkala Musa telah menyelesaikan waktu yang ditentukan dan dia berangkat dengan keluarganya, dilihatnyalah api di lereng gunung ia berkata kepada keluarganya: &quot;Tunggulah (di sini), sesungguhnya aku melihat api, mudah-mudahan aku dapat membawa suatu berita kepadamu dari (tempat) api itu atau (membawa) sesuluh api, agar kamu dapat menghangatkan badan&quot;.<?php break;}
case 30:{?>Maka tatkala Musa sampai ke (tempat) api itu, diserulah dia dari (arah) pinggir lembah yang diberkahi, dari sebatang pohon kayu, yaitu: &quot;Ya Musa, sesungguhnya aku adalah Allah, Tuhan semesta alam,<?php break;}
case 31:{?>dan lemparkanlah tongkatmu. Maka tatkala (tongkat itu menjadi ular dan) Musa melihatnya bergerak-gerak seolah-olah dia seekor ular yang gesit, larilah ia berbalik ke belakang tanpa menoleh. (Kemudian Musa diseru): &quot;Hai Musa, datanglah kepada-Ku dan janganlah kamu takut. Sesungguhnya kamu termasuk orang-orang yang aman.<?php break;}
case 32:{?>Masukkanlah tanganmu ke leher bajumu, niscaya ia ke luar putih tidak bercacat bukan karena penyakit, dan dekapkanlah kedua tanganmu (ke dada) mu bila ketakutan, maka yang demikian itu adalah dua mukjizat dari Tuhanmu (yang akan kamu hadapkan kepada Firaun dan pembesar-pembesarnya). Sesungguhnya mereka adalah orang-orang yang fasik&quot;.<?php break;}
case 33:{?>Musa berkata: &quot;Ya Tuhanku sesungguhnya aku, telah membunuh seorang manusia dari golongan mereka, maka aku takut mereka akan membunuhku.<?php break;}
case 34:{?>Dan saudaraku Harun dia lebih fasih lidahnya daripadaku, maka utuslah dia bersamaku sebagai pembantuku untuk membenarkan (perkataan) ku; sesungguhnya aku khawatir mereka akan mendustakanku&quot;.<?php break;}
case 35:{?>Allah berfirman: &quot;Kami akan membantumu dengan saudaramu, dan Kami berikan kepadamu berdua kekuasaan yang besar, maka mereka tidak dapat mencapaimu; (berangkatlah kamu berdua) dengan membawa mukjizat Kami, kamu berdua dan orang yang mengikuti kamulah yang menang&quot;.<?php break;}
case 36:{?>Maka tatkala Musa datang kepada mereka dengan (membawa) mukjizat-mukjizat Kami yang nyata, mereka berkata: &quot;Ini tidak lain hanyalah sihir yang dibuat-buat dan kami belum pernah mendengar (seruan yang seperti) ini pada nenek moyang kami dahulu&quot;.<?php break;}
case 37:{?>Musa menjawab: &quot;Tuhanku lebih mengetahui orang yang (patut) membawa petunjuk dari sisi-Nya dan siapa yang akan mendapat kesudahan (yang baik) di negeri akhirat. Sesungguhnya tidaklah akan mendapat kemenangan orang-orang yang lalim&quot;.<?php break;}
case 38:{?>Dan berkata Firaun: &quot;Hai pembesar kaumku, aku tidak mengetahui tuhan bagimu selain aku. Maka bakarlah hai Haman untukku tanah liat, kemudian buatkanlah untukku bangunan yang tinggi supaya aku dapat naik melihat Tuhan Musa, dan sesungguhnya aku benar-benar yakin bahwa dia termasuk orang-orang pendusta&quot;.<?php break;}
case 39:{?>Dan berlaku angkuhlah Firaun dan bala tentaranya di bumi (Mesir) tanpa alasan yang benar dan mereka menyangka bahwa mereka tidak akan dikembalikan kepada Kami.<?php break;}
case 40:{?>Maka Kami hukumlah Firaun dan bala tentaranya, lalu Kami lemparkan mereka ke dalam laut. Maka lihatlah bagaimana akibat orang-orang yang lalim.<?php break;}
case 41:{?>Dan Kami jadikan mereka pemimpin-pemimpin yang menyeru (manusia) ke neraka dan pada hari kiamat mereka tidak akan ditolong.<?php break;}
case 42:{?>Dan Kami ikutkanlah laknat kepada mereka di dunia ini; dan pada hari kiamat mereka termasuk orang-orang yang dijauhkan (dari rahmat Allah).<?php break;}
case 43:{?>Dan sesungguhnya telah Kami berikan kepada Musa Al-Kitab (Taurat) sesudah Kami binasakan generasi-generasi yang terdahulu, untuk menjadi pelita bagi manusia dan petunjuk dan rahmat, agar mereka ingat.<?php break;}
case 44:{?>Dan tidaklah kamu (Muhammad) berada di sisi yang sebelah barat ketika Kami menyampaikan perintah kepada Musa, dan tiada pula kamu termasuk orang-orang yang menyaksikan.<?php break;}
case 45:{?>Tetapi Kami telah mengadakan beberapa generasi, dan berlalulah atas mereka masa yang panjang, dan tiadalah kamu tinggal bersama-sama penduduk Mad-yan dengan membacakan ayat-ayat Kami kepada mereka, tetapi Kami telah mengutus rasul-rasul.<?php break;}
case 46:{?>Dan tiadalah kamu berada di dekat gunung Thur ketika Kami menyeru (Musa), tetapi (Kami beritahukan itu kepadamu) sebagai rahmat dari Tuhanmu, supaya kamu memberi peringatan kepada kaum (Quraisy) yang sekali-kali belum datang kepada mereka pemberi peringatan sebelum kamu agar mereka ingat.<?php break;}
case 47:{?>Dan agar mereka tidak mengatakan ketika azab menimpa mereka disebabkan apa yang mereka kerjakan: &quot;Ya Tuhan kami, mengapa Engkau tidak mengutus seorang rasul kepada kami, lalu kami mengikuti ayat-ayat Engkau dan jadilah kami termasuk orang-orang mukmin&quot;<?php break;}
case 48:{?>Maka tatkala datang kepada mereka kebenaran dari sisi Kami, mereka berkata: &quot;Mengapakah tidak diberikan kepadanya (Muhammad) seperti yang telah diberikan kepada Musa dahulu?&quot;. Dan bukankah mereka itu telah ingkar (juga) kepada apa yang diberikan kepada Musa dahulu?; mereka dahulu telah berkata: &quot;Musa dan Harun adalah dua ahli sihir yang bantu membantu&quot;. Dan mereka (juga) berkata: &quot;Sesungguhnya Kami tidak mempercayai masing-masing mereka itu'.<?php break;}
case 49:{?>Katakanlah: &quot;Datangkanlah olehmu sebuah kitab dari sisi Allah yang kitab itu lebih (dapat) memberi petunjuk daripada keduanya (Taurat dan Al Qur'an) niscaya aku mengikutinya, jika kamu sungguh orang-orang yang benar&quot;.<?php break;}
case 50:{?>Maka jika mereka tidak menjawab (tantanganmu), ketahuilah bahwa sesungguhnya mereka hanyalah mengikuti hawa nafsu mereka (belaka). Dan siapakah yang lebih sesat daripada orang yang mengikuti hawa nafsunya dengan tidak mendapat petunjuk dari Allah sedikit pun. Sesungguhnya Allah tidak memberi petunjuk kepada orang-orang yang lalim.<?php break;}
case 51:{?>Dan sesungguhnya telah Kami turunkan berturut-turut perkataan ini (Al Qur'an) kepada mereka agar mereka mendapat pelajaran.<?php break;}
case 52:{?>Orang-orang yang telah Kami datangkan kepada mereka Al Kitab sebelum Al Qur'an, mereka beriman (pula) dengan Al Qur'an itu.<?php break;}
case 53:{?>Dan apabila dibacakan (Al Qur'an itu) kepada mereka, mereka berkata: &quot;Kami beriman kepadanya; sesungguhnya; Al Qur'an itu adalah suatu kebenaran dari Tuhan Kami, sesungguhnya Kami sebelumnya adalah orang-orang yang membenarkan (nya).<?php break;}
case 54:{?>Mereka itu diberi pahala dua kali disebabkan kesabaran mereka, dan mereka menolak kejahatan dengan kebaikan, dan sebagian dari apa yang telah Kami rezekikan kepada mereka, mereka nafkahkan.<?php break;}
case 55:{?>Dan apabila mereka mendengar perkataan yang tidak bermanfaat, mereka berpaling daripadanya dan mereka berkata: &quot;Bagi kami amal-amal kami dan bagimu amal-amalmu, kesejahteraan atas dirimu, kami tidak ingin bergaul dengan orang-orang jahil&quot;.<?php break;}
case 56:{?>Sesungguhnya kamu tidak akan dapat memberi petunjuk kepada orang yang kamu kasihi, tetapi Allah memberi petunjuk kepada orang yang dikehendaki-Nya, dan Allah lebih mengetahui orang-orang yang mau menerima petunjuk.<?php break;}
case 57:{?>Dan mereka berkata: &quot;Jika kami mengikuti petunjuk bersama kamu, niscaya kami akan diusir dari negeri kami&quot;. Dan apakah Kami tidak meneguhkan kedudukan mereka dalam daerah haram (tanah suci) yang aman, yang didatangkan ke tempat itu buah-buahan dari segala macam (tumbuh-tumbuhan) untuk menjadi rezeki (bagimu) dari sisi Kami?. Tetapi kebanyakan mereka tidak mengetahui.<?php break;}
case 58:{?>Dan berapa banyaknya (penduduk) negeri yang telah Kami binasakan, yang sudah bersenang-senang dalam kehidupannya; maka itulah tempat kediaman mereka yang tiada didiami (lagi) sesudah mereka, kecuali sebahagian kecil. Dan Kami adalah pewarisnya.<?php break;}
case 59:{?>Dan tidak adalah Tuhanmu membinasakan kota-kota, sebelum Dia mengutus di ibukota itu seorang rasul yang membacakan ayat-ayat Kami kepada mereka; dan tidak pernah (pula) Kami membinasakan kota-kota; kecuali penduduknya dalam keadaan melakukan kelaliman.<?php break;}
case 60:{?>Dan apa saja yang diberikan kepada kamu, maka itu adalah kenikmatan hidup duniawi dan perhiasannya; sedang apa yang di sisi Allah adalah lebih baik dan lebih kekal. Maka apakah kamu tidak memahaminya?<?php break;}
case 61:{?>Maka apakah orang yang Kami janjikan kepadanya suatu janji yang baik (surga) lalu ia memperolehnya, sama dengan orang yang Kami berikan kepadanya kenikmatan hidup duniawi; kemudian dia pada hari kiamat termasuk orang-orang yang diseret (ke dalam neraka)?<?php break;}
case 62:{?>Dan (ingatlah) hari (di waktu) Allah menyeru mereka seraya berkata: &quot;Dimanakah sekutu-sekutu-Ku yang dahulu kamu katakan?&quot;<?php break;}
case 63:{?>Berkatalah orang-orang yang telah tetap hukuman atas mereka; &quot;Ya Tuhan kami, mereka inilah orang-orang yang kami sesatkan itu; kami telah menyesatkan mereka sebagaimana kami (sendiri) sesat, kami menyatakan berlepas diri (dari mereka) kepada Engkau, mereka sekali-kali tidak menyembah kami&quot;.<?php break;}
case 64:{?>Dikatakan (kepada mereka): &quot;Serulah olehmu sekutu-sekutu kamu&quot;, lalu mereka menyerunya, maka sekutu-sekutu itu tidak memperkenankan (seruan) mereka, dan mereka melihat azab. (Mereka ketika itu berkeinginan) kiranya mereka dahulu menerima petunjuk.<?php break;}
case 65:{?>Dan (ingatlah) hari (di waktu) Allah menyeru mereka, seraya berkata: &quot;Apakah jawabanmu kepada para rasul?&quot;<?php break;}
case 66:{?>Maka gelaplah bagi mereka segala macam alasan pada hari itu, karena itu mereka tidak saling tanya menanya.<?php break;}
case 67:{?>Adapun orang yang bertobat dan beriman, serta mengerjakan amal yang saleh, semoga dia termasuk orang-orang yang beruntung.<?php break;}
case 68:{?>Dan Tuhanmu menciptakan apa yang Dia kehendaki dan memilihnya. Sekali-kali tidak ada pilihan bagi mereka. Maha Suci Allah dan Maha Tinggi dari apa yang mereka persekutukan (dengan Dia).<?php break;}
case 69:{?>Dan Tuhanmu mengetahui apa yang disembunyikan (dalam) dada mereka dan apa yang mereka nyatakan.<?php break;}
case 70:{?>Dan Dialah Allah, tidak ada Tuhan (yang berhak disembah) melainkan Dia, bagi-Nyalah segala puji di dunia dan di akhirat, dan bagi-Nyalah segala penentuan dan hanya kepada-Nyalah kamu dikembalikan.<?php break;}
case 71:{?>Katakanlah: &quot;Terangkanlah kepadaku, jika Allah menjadikan untukmu malam itu terus menerus sampai hari kiamat, siapakah Tuhan selain Allah yang akan mendatangkan sinar terang kepadamu? Maka apakah kamu tidak mendengar?&quot;<?php break;}
case 72:{?>Katakanlah: &quot;Terangkanlah kepadaku, jika Allah menjadikan untukmu siang itu terus menerus sampai hari kiamat, siapakah Tuhan selain Allah yang akan mendatangkan malam kepadamu yang kamu beristirahat padanya? Maka apakah kamu tidak memperhatikan?&quot;<?php break;}
case 73:{?>Dan karena rahmat-Nya, Dia jadikan untukmu malam dan siang, supaya kamu beristirahat pada malam itu dan supaya kamu mencari sebahagian dari karunia-Nya (pada siang hari) dan agar kamu bersyukur kepada-Nya.<?php break;}
case 74:{?>Dan (ingatlah) hari (di waktu) Allah menyeru mereka, seraya berkata: &quot;Di manakah sekutu-sekutu-Ku yang dahulu kamu katakan?&quot;<?php break;}
case 75:{?>Dan Kami datangkan dari tiap-tiap umat seorang saksi, lalu Kami berkata &quot;Tunjukkanlah bukti kebenaranmu&quot;, maka tahulah mereka bahwasanya yang hak itu kepunyaan Allah dan lenyaplah dari mereka apa yang dahulunya mereka ada-adakan.<?php break;}
case 76:{?>Sesungguhnya Karun adalah termasuk kaum Musa, maka ia berlaku aniaya terhadap mereka, dan Kami telah menganugerahkan kepadanya perbendaharaan harta yang kunci-kuncinya sungguh berat dipikul oleh sejumlah orang yang kuat-kuat. (Ingatlah) ketika kaumnya berkata kepadanya: &quot;Janganlah kamu terlalu bangga; sesungguhnya Allah tidak menyukai orang-orang yang terlalu membanggakan diri&quot;.<?php break;}
case 77:{?>Dan carilah pada apa yang telah dianugerahkan Allah kepadamu (kebahagiaan) negeri akhirat, dan janganlah kamu melupakan bahagianmu dari (kenikmatan) duniawi dan berbuat baiklah (kepada orang lain) sebagaimana Allah telah berbuat baik kepadamu, dan janganlah kamu berbuat kerusakan di (muka) bumi. Sesungguhnya Allah tidak menyukai orang-orang yang berbuat kerusakan.<?php break;}
case 78:{?>Karun berkata: &quot;Sesungguhnya aku hanya diberi harta itu, karena ilmu yang ada padaku&quot;. Dan apakah ia tidak mengetahui, bahwasanya Allah sungguh telah membinasakan umat-umat sebelumnya yang lebih kuat daripadanya, dan lebih banyak mengumpulkan harta? Dan tidaklah perlu ditanya kepada orang-orang yang berdosa itu, tentang dosa-dosa mereka.<?php break;}
case 79:{?>Maka keluarlah Karun kepada kaumnya dalam kemegahannya. Berkatalah orang-orang yang menghendaki kehidupan dunia: &quot;Moga-moga kiranya kita mempunyai seperti apa yang telah diberikan kepada Karun; sesungguhnya ia benar-benar mempunyai keberuntungan yang besar&quot;.<?php break;}
case 80:{?>Berkatalah orang-orang yang dianugerahi ilmu: &quot;Kecelakaan yang besarlah bagimu, pahala Allah adalah lebih baik bagi orang-orang yang beriman dan beramal saleh, dan tidak diperoleh pahala itu kecuali oleh orang-orang yang sabar&quot;.<?php break;}
case 81:{?>Maka Kami benamkanlah Karun beserta rumahnya ke dalam bumi. Maka tidak ada baginya suatu golongan pun yang menolongnya terhadap azab Allah. dan tiadalah ia termasuk orang-orang (yang dapat) membela (dirinya).<?php break;}
case 82:{?>Dan jadilah orang-orang yang kemarin mencita-citakan kedudukan Karun itu. berkata: &quot;Aduhai. benarlah Allah melapangkan rezeki bagi siapa yang Dia kehendaki dari hamba-hamba-Nya dan menyempitkannya; kalau Allah tidak melimpahkan karunia-Nya atas kita benar-benar Dia telah membenamkan kita (pula). Aduhai benarlah, tidak beruntung orang-orang yang mengingkari (nikmat Allah)&quot;.<?php break;}
case 83:{?>Negeri akhirat itu, Kami jadikan untuk orang-orang yang tidak ingin menyombongkan diri dan berbuat kerusakan di (muka) bumi. Dan kesudahan (yang baik) itu adalah bagi orang-orang yang bertakwa.<?php break;}
case 84:{?>Barang siapa yang datang dengan (membawa) kebaikan, maka baginya (pahala) yang lebih baik daripada kebaikannya itu; dan barang siapa yang datang dengan (membawa) kejahatan, maka tidaklah diberi pembalasan kepada orang-orang yang telah mengerjakan kejahatan itu, melainkan (seimbang) dengan apa yang dahulu mereka kerjakan.<?php break;}
case 85:{?>Sesungguhnya yang mewajibkan atasmu (melaksanakan hukum-hukum) Al Qur'an, benar-benar akan mengembalikan kamu ke tempat kembali. Katakanlah: &quot;Tuhanku mengetahui orang yang membawa petunjuk dan orang yang dalam kesesatan yang nyata&quot;.<?php break;}
case 86:{?>Dan kamu tidak pernah mengharap agar Al Qur'an diturunkan kepadamu, tetapi ia (diturunkan) karena suatu rahmat yang besar dari Tuhanmu, sebab itu janganlah sekali-kali kamu menjadi penolong bagi orang-orang kafir.<?php break;}
case 87:{?>Dan janganlah sekali-kali mereka dapat menghalangimu dari (menyampaikan) ayat-ayat Allah, sesudah ayat-ayat itu diturunkan kepadamu, dan serulah mereka kepada (jalan) Tuhanmu, dan janganlah sekali-kali kamu termasuk orang-orang yang mempersekutukan Tuhan.<?php break;}
case 88:{?>Janganlah kamu sembah di samping (menyembah) Allah, tuhan apapun yang lain. Tidak ada Tuhan (yang berhak disembah) melainkan Dia. Tiap-tiap sesuatu pasti binasa, kecuali Allah. Bagi-Nya lah segala penentuan, dan hanya kepada-Nya lah kamu dikembalikan.<?php break;}
}?>