<?php 
switch($verse){
case 1:{?>Alif laam miim.<?php break;}
case 2:{?>Apakah manusia itu mengira bahwa mereka dibiarkan (saja) mengatakan: &quot;Kami telah beriman&quot;, sedang mereka tidak diuji lagi?<?php break;}
case 3:{?>Dan sesungguhnya Kami telah menguji orang-orang yang sebelum mereka, maka sesungguhnya Allah mengetahui orang-orang yang benar dan sesungguhnya Dia mengetahui orang-orang yang dusta.<?php break;}
case 4:{?>Ataukah orang-orang yang mengerjakan kejahatan itu mengira bahwa mereka akan luput dari (azab) Kami? Amatlah buruk apa yang mereka tetapkan itu.<?php break;}
case 5:{?>Barang siapa yang mengharap pertemuan dengan Allah, maka sesungguhnya waktu (yang dijanjikan) Allah itu, pasti datang. Dan Dialah Yang Maha Mendengar lagi Maha Mengetahui.<?php break;}
case 6:{?>Dan barang siapa yang berjihad, maka sesungguhnya jihadnya itu adalah untuk dirinya sendiri. Sesungguhnya Allah benar-benar Maha Kaya (tidak memerlukan sesuatu) dari semesta alam.<?php break;}
case 7:{?>Dan orang-orang yang beriman dan beramal saleh, benar-benar akan Kami hapuskan dari mereka dosa-dosa mereka dan benar-benar akan Kami beri mereka balasan yang lebih baik dari apa yang mereka kerjakan.<?php break;}
case 8:{?>Dan Kami wajibkan manusia (berbuat) kebaikan kepada dua orang ibu-bapaknya. Dan jika keduanya memaksamu untuk mempersekutukan Aku dengan sesuatu yang tidak ada pengetahuanmu tentang itu, maka janganlah kamu mengikuti keduanya. Hanya kepada-Ku-lah kembalimu, lalu Aku kabarkan kepadamu apa yang telah kamu kerjakan.<?php break;}
case 9:{?>Dan orang-orang yang beriman dan mengerjakan amal saleh benar-benar akan Kami masukkan mereka ke dalam (golongan) orang-orang yang saleh.<?php break;}
case 10:{?>Dan di antara manusia ada orang yang berkata: &quot;Kami beriman kepada Allah&quot;, maka apabila ia disakiti (karena ia beriman) kepada Allah, ia menganggap fitnah manusia itu sebagai azab Allah. Dan sungguh jika datang pertolongan dari Tuhanmu, mereka pasti akan berkata: &quot;Sesungguhnya kami adalah besertamu.&quot; Bukankah Allah lebih mengetahui apa yang ada dalam dada semua manusia?<?php break;}
case 11:{?>Dan sesungguhnya Allah benar-benar mengetahui orang-orang yang beriman: dan sesungguhnya Dia mengetahui orang-orang yang munafik.<?php break;}
case 12:{?>Dan berkatalah orang-orang kafir kepada orang-orang yang beriman: &quot;Ikutilah jalan kami, dan nanti kami akan memikul dosa-dosamu&quot;, dan mereka (sendiri) sedikit pun tidak (sanggup), memikul dosa-dosa mereka. Sesungguhnya mereka adalah benar-benar orang pendusta.<?php break;}
case 13:{?>Dan sesungguhnya mereka akan memikul beban (dosa) mereka, dan beban-beban (dosa yang lain) di samping beban-beban mereka sendiri, dan sesungguhnya mereka akan ditanya pada hari kiamat tentang apa yang selalu mereka ada-adakan.<?php break;}
case 14:{?>Dan sesungguhnya Kami telah mengutus Nuh kepada kaumnya, maka ia tinggal di antara mereka seribu tahun kurang lima puluh tahun. Maka mereka ditimpa banjir besar, dan mereka adalah orang-orang yang lalim.<?php break;}
case 15:{?>Maka Kami selamatkan Nuh dan penumpang-penumpang bahtera itu dan Kami jadikan peristiwa itu pelajaran bagi semua umat manusia.<?php break;}
case 16:{?>Dan (ingatlah) Ibrahim, ketika ia berkata kepada kaumnya: &quot;Sembahlah olehmu Allah dan bertakwalah kepada-Nya. Yang demikian itu adalah lebih baik bagimu, jika kamu mengetahui.<?php break;}
case 17:{?>Sesungguhnya apa yang kamu sembah selain Allah itu adalah berhala, dan kamu membuat dusta. Sesungguhnya yang kamu sembah selain Allah itu tidak mampu memberikan rezeki kepadamu; maka mintalah rezeki itu di sisi Allah, dan sembahlah Dia dan bersyukurlah kepada-Nya. Hanya kepada-Nya lah kamu akan dikembalikan.<?php break;}
case 18:{?>Dan jika kamu (orang kafir) mendustakan, maka umat yang sebelum kamu juga telah mendustakan. Dan kewajiban rasul itu, tidak lain hanyalah menyampaikan (agama Allah) dengan seterang-terangnya.&quot;<?php break;}
case 19:{?>Dan apakah mereka tidak memperhatikan bagaimana Allah menciptakan (manusia) dari permulaannya, kemudian mengulanginya (kembali). Sesungguhnya yang demikian itu adalah mudah bagi Allah.<?php break;}
case 20:{?>Katakanlah: &quot;Berjalanlah di (muka) bumi, maka perhatikanlah bagaimana Allah menciptakan (manusia) dari permulaannya, kemudian Allah menjadikannya sekali lagi. Sesungguhnya Allah Maha Kuasa atas segala sesuatu.<?php break;}
case 21:{?>Allah mengazab siapa yang dikehendaki-Nya dan memberi rahmat kepada siapa yang dikehendaki-Nya, dan hanya kepada-Nya-lah kamu akan dikembalikan.<?php break;}
case 22:{?>Dan kamu sekali-kali tidak dapat melepaskan diri (dari azab Allah) di bumi dan tidak (pula) di langit dan sekali-kali tiadalah bagimu pelindung dan penolong selain Allah.<?php break;}
case 23:{?>Dan orang-orang yang kafir kepada ayat-ayat Allah dan pertemuan dengan Dia, mereka putus asa dari rahmat-Ku, dan mereka itu mendapat azab yang pedih.<?php break;}
case 24:{?>Maka tidak adalah jawaban kaum Ibrahim, selain mengatakan: &quot;Bunuhlah atau bakarlah dia&quot;, lalu Allah menyelamatkannya dari api. Sesungguhnya pada yang demikian itu benar-benar terdapat tanda-tanda kebesaran Allah bagi orang-orang yang beriman.<?php break;}
case 25:{?>Dan berkata Ibrahim: &quot;Sesungguhnya berhala-berhala yang kamu sembah selain Allah adalah untuk menciptakan perasaan kasih sayang di antara kamu dalam kehidupan dunia ini kemudian di hari kiamat sebahagian kamu mengingkari sebahagian (yang lain) dan sebahagian kamu mela'nati sebahagian (yang lain); dan tempat kembalimu ialah neraka, dan sekali-kali tak ada bagimu para penolongpun.<?php break;}
case 26:{?>Maka Lut membenarkan (kenabian) nya. Dan berkatalah Ibrahim: &quot;Sesungguhnya aku akan berpindah ke (tempat yang diperintahkan) Tuhanku (kepadaku); sesungguhnya Dialah yang Maha Perkasa lagi Maha Bijaksana.<?php break;}
case 27:{?>Dan Kami anugrahkan kepada Ibrahim, Ishak dan Yaqub, dan Kami jadikan kenabian dan Al Kitab pada keturunannya, dan Kami berikan kepadanya balasannya di dunia; dan sesungguhnya dia di akhirat, benar-benar termasuk orang-orang yang saleh.<?php break;}
case 28:{?>Dan (ingatlah) ketika Lut berkata kepada kaumnya: &quot;Sesungguhnya kamu benar-benar mengerjakan perbuatan yang amat keji yang belum pernah dikerjakan oleh seorang pun dari umat-umat sebelum kamu&quot;.<?php break;}
case 29:{?>Apakah sesungguhnya kamu patut mendatangi laki-laki, menyamun dan mengerjakan kemungkaran di tempat-tempat pertemuanmu? Maka jawaban kaumnya tidak lain hanya mengatakan: &quot;Datangkanlah kepada kami azab Allah, jika kamu termasuk orang-orang yang benar&quot;.<?php break;}
case 30:{?>Lut berdoa: &quot;Ya Tuhanku, tolonglah aku (dengan menimpakan azab) atas kaum yang berbuat kerusakan itu&quot;.<?php break;}
case 31:{?>Dan tatkala utusan Kami (para malaikat) datang kepada Ibrahim membawa kabar gembira, mereka mengatakan: &quot;Sesungguhnya kami akan menghancurkan penduduk (Sodom) ini, sesungguhnya penduduknya adalah orang-orang yang lalim&quot;.<?php break;}
case 32:{?>Berkata Ibrahim: &quot;Sesungguhnya di kota itu ada Lut&quot;. Para malaikat berkata: &quot;Kami lebih mengetahui siapa yang ada di kota itu. Kami sungguh-sungguh akan menyelamatkan dia dan pengikut-pengikutnya kecuali istrinya. Dia adalah termasuk orang-orang yang tertinggal (dibinasakan).<?php break;}
case 33:{?>Dan tatkala datang utusan-utusan Kami (para malaikat) itu kepada Lut, dia merasa susah karena (kedatangan) mereka, dan (merasa) tidak mempunyai kekuatan untuk melindungi mereka dan mereka berkata: &quot;Janganlah kamu takut dan jangan (pula) susah. Sesungguhnya kami akan menyelamatkan kamu dan pengikut-pengikutmu, kecuali istrimu, dia adalah termasuk orang-orang yang tertinggal (dibinasakan).&quot;<?php break;}
case 34:{?>Sesungguhnya Kami akan menurunkan azab dari langit atas penduduk kota ini karena mereka berbuat fasik.<?php break;}
case 35:{?>Dan sesungguhnya Kami tinggalkan daripadanya satu tanda yang nyata bagi orang-orang yang berakal.<?php break;}
case 36:{?>Dan (Kami telah mengutus) kepada penduduk Mad-yan, saudara mereka Syuaib, maka ia berkata: &quot;Hai kaumku, sembahlah olehmu Allah, harapkanlah (pahala) hari akhir, dan jangan kamu berkeliaran di muka bumi berbuat kerusakan&quot;.<?php break;}
case 37:{?>Maka mereka mendustakan Syuaib, lalu mereka ditimpa gempa yang dahsyat, dan jadilah mereka mayit-mayit yang bergelimpangan di tempat-tempat tinggal mereka.<?php break;}
case 38:{?>Dan (juga) kaum Ad dan Tsamud, dan sungguh telah nyata bagi kamu (kehancuran mereka) dari (puing-puing) tempat tinggal mereka. Dan setan menjadikan mereka memandang baik perbuatan-perbuatan mereka, lalu ia menghalangi mereka dari jalan (Allah), sedangkan mereka adalah orang-orang yang berpandangan tajam.<?php break;}
case 39:{?>Dan (juga) Karun, Firaun dan Haman. Dan sesungguhnya telah datang kepada mereka Musa dengan (membawa bukti-bukti) keterangan-keterangan yang nyata. Akan tetapi mereka berlaku sombong di (muka) bumi, dan tiadalah mereka orang-orang yang luput (dari kehancuran itu).<?php break;}
case 40:{?>Maka masing-masing (mereka itu) Kami siksa disebabkan dosanya, maka di antara mereka ada yang Kami timpakan kepadanya hujan batu kerikil dan di antara mereka ada yang ditimpa suara keras yang mengguntur, dan di antara mereka ada yang Kami benamkan ke dalam bumi, dan di antara mereka ada yang Kami tenggelamkan, dan Allah sekali-kali tidak hendak menganiaya mereka, akan tetapi merekalah yang menganiaya diri mereka sendiri.<?php break;}
case 41:{?>Perumpamaan orang-orang yang mengambil pelindung-pelindung selain Allah adalah seperti laba-laba yang membuat rumah. Dan sesungguhnya rumah yang paling lemah ialah rumah laba-laba kalau mereka mengetahui.<?php break;}
case 42:{?>Sesungguhnya Allah mengetahui apa saja yang mereka seru selain Allah. Dan Dia Maha Perkasa lagi Maha Bijaksana.<?php break;}
case 43:{?>Dan perumpamaan-perumpamaan ini Kami buatkan untuk manusia; dan tiada yang memahaminya kecuali orang-orang yang berilmu.<?php break;}
case 44:{?>Allah menciptakan langit dan bumi dengan hak. Sesungguhnya pada yang demikian itu terdapat tanda-tanda kekuasaan Allah bagi orang-orang mu'min.<?php break;}
case 45:{?>Bacalah apa yang telah diwahyukan kepadamu, yaitu Al Kitab (Al Qur'an) dan dirikanlah salat. Sesungguhnya salat itu mencegah dari (perbuatan-perbuatan) keji dan mungkar. Dan sesungguhnya mengingat Allah (salat) adalah lebih besar (keutamaannya dari ibadah-ibadah yang lain). Dan Allah mengetahui apa yang kamu kerjakan.<?php break;}
case 46:{?>Dan janganlah kamu berdebat dengan Ahli Kitab, melainkan dengan cara yang paling baik, kecuali dengan orang-orang lalim di antara mereka, dan katakanlah: &quot;Kami telah beriman kepada (kitab-kitab) yang diturunkan kepada kami dan yang diturunkan kepadamu; Tuhan kami dan Tuhanmu adalah satu; dan kami hanya kepada-Nya berserah diri&quot;.<?php break;}
case 47:{?>Dan demikian (pulalah) Kami turunkan kepadamu Al Kitab (Al Qur'an), maka orang-orang yang telah Kami berikan kepada mereka Al Kitab (Taurat) mereka beriman kepadanya (Al Qur'an); dan di antara mereka (orang-orang kafir Mekah) ada yang beriman kepadanya. Dan tidak adalah yang mengingkari ayat-ayat Kami selain orang-orang kafir.<?php break;}
case 48:{?>Dan kamu tidak pernah membaca sebelumnya (Al Qur'an) sesuatu Kitab pun dan kamu tidak (pernah) menulis suatu kitab dengan tangan kananmu; andai kata (kamu pernah membaca dan menulis), benar-benar ragulah orang yang mengingkari (mu).<?php break;}
case 49:{?>Sebenarnya, Al Qur'an itu adalah ayat-ayat yang nyata di dalam dada orang-orang yang diberi ilmu. Dan tidak ada yang mengingkari ayat-ayat Kami kecuali orang-orang yang lalim.<?php break;}
case 50:{?>Dan orang-orang kafir Mekah berkata: &quot;Mengapa tidak diturunkan kepadanya mukjizat-mukjizat dari Tuhannya?&quot; Katakanlah: &quot;Sesungguhnya mukjizat-mukjizat itu terserah kepada Allah. Dan sesungguhnya aku hanya seorang pemberi peringatan yang nyata&quot;.<?php break;}
case 51:{?>Dan apakah tidak cukup bagi mereka bahwasanya Kami telah menurunkan kepadamu Al Kitab (Al Qur'an) sedang dia dibacakan kepada mereka? Sesungguhnya dalam (Al Qur'an) itu terdapat rahmat yang besar dan pelajaran bagi orang-orang yang beriman.<?php break;}
case 52:{?>Katakanlah: &quot;Cukuplah Allah menjadi saksi antaraku dan antaramu. Dia mengetahui apa yang di langit dan di bumi. Dan orang-orang yang percaya kepada yang batil dan ingkar kepada Allah, mereka itulah orang-orang yang merugi.<?php break;}
case 53:{?>Dan mereka meminta kepadamu supaya segera diturunkan azab. Kalau tidaklah karena waktu yang telah ditetapkan benar-benar telah datang azab kepada mereka, dan azab itu benar-benar akan datang kepada mereka dengan tiba-tiba, sedang mereka tidak menyadarinya.<?php break;}
case 54:{?>Mereka meminta kepadamu supaya segera diturunkan azab. Dan sesungguhnya Jahanam benar-benar meliputi orang-orang yang kafir,<?php break;}
case 55:{?>pada hari mereka ditutup oleh azab dari atas mereka dan dari bawah kaki mereka dan Allah berkata (kepada mereka): &quot;Rasailah (pembalasan dari) apa yang telah kamu kerjakan&quot;<?php break;}
case 56:{?>Hai hamba-hamba-Ku yang beriman, sesungguhnya bumi-Ku luas, maka sembahlah Aku saja.<?php break;}
case 57:{?>Tiap-tiap yang berjiwa akan merasakan mati. Kemudian hanyalah kepada Kami kamu dikembalikan.<?php break;}
case 58:{?>Dan orang-orang yang beriman dan mengerjakan amal-amal yang saleh, sesungguhnya akan Kami tempatkan mereka pada tempat-tempat yang tinggi di dalam surga, yang mengalir sungai-sungai di bawahnya, mereka kekal di dalamnya. Itulah sebaik-baik pembalasan bagi orang-orang yang beramal,<?php break;}
case 59:{?>(yaitu) yang bersabar dan bertawakal kepada Tuhannya.<?php break;}
case 60:{?>Dan berapa banyak binatang yang tidak (dapat) membawa (mengurus) rezekinya sendiri. Allah-lah yang memberi rezeki kepadanya dan kepadamu dan Dia Maha Mendengar lagi Maha Mengetahui.<?php break;}
case 61:{?>Dan sesungguhnya jika kamu tanyakan kepada mereka: &quot;Siapakah yang menjadikan langit dan bumi dan menundukkan matahari dan bulan?&quot; Tentu mereka akan menjawab: &quot;Allah&quot;, maka betapakah mereka (dapat) dipalingkan (dari jalan yang benar).<?php break;}
case 62:{?>Allah melapangkan rezeki bagi siapa yang dikehendaki-Nya di antara hamba-hamba-Nya dan Dia (pula) yang menyempitkan baginya. Sesungguhnya Allah Maha Mengetahui segala sesuatu.<?php break;}
case 63:{?>Dan sesungguhnya jika kamu menanyakan kepada mereka: &quot;Siapakah yang menurunkan air dari langit lalu menghidupkan dengan air itu bumi sesudah matinya?&quot; Tentu mereka akan menjawab: &quot;Allah&quot;. Katakanlah: &quot;Segala puji bagi Allah&quot;, tetapi kebanyakan mereka tidak memahami (nya).<?php break;}
case 64:{?>Dan tiadalah kehidupan dunia ini melainkan senda gurau dan main-main. Dan sesungguhnya akhirat itulah yang sebenarnya kehidupan, kalau mereka mengetahui.<?php break;}
case 65:{?>Maka apabila mereka naik kapal mereka mendoa kepada Allah dengan memurnikan ketaatan kepada-Nya; maka tatkala Allah menyelamatkan mereka sampai ke darat, tiba-tiba mereka (kembali) mempersekutukan (Allah),<?php break;}
case 66:{?>agar mereka mengingkari nikmat yang telah Kami berikan kepada mereka dan agar mereka (hidup) bersenang-senang (dalam kekafiran). Kelak mereka akan mengetahui (akibat perbuatannya).<?php break;}
case 67:{?>Dan apakah mereka tidak memperhatikan, bahwa sesungguhnya Kami telah menjadikan (negeri mereka) tanah suci yang aman, sedang manusia sekitarnya rampok-merampok. Maka mengapa (sesudah nyata kebenaran) mereka masih percaya kepada yang bathil dan ingkar kepada nikmat Allah?<?php break;}
case 68:{?>Dan siapakah yang lebih lalim daripada orang-orang yang mengada-adakan kedustaan terhadap Allah atau mendustakan yang hak tatkala yang hak itu datang kepadanya? Bukankah dalam neraka Jahanam itu ada tempat bagi orang-orang yang kafir?<?php break;}
case 69:{?>Dan orang-orang yang berjihad untuk (mencari keridaan) Kami, benar-benar akan Kami tunjukkan Kepada mereka jalan-jalan Kami. Dan sesungguhnya Allah benar-benar beserta orang-orang yang berbuat baik.<?php break;}
}?>