<?php 
switch($verse){
case 1:{?>Alif Laam Miim.<?php break;}
case 2:{?>Telah dikalahkan bangsa Rumawi,<?php break;}
case 3:{?>di negeri yang terdekat dan mereka sesudah dikalahkan itu akan menang,<?php break;}
case 4:{?>dalam beberapa tahun (lagi). Bagi Allah-lah urusan sebelum dan sesudah (mereka menang). Dan di hari (kemenangan bangsa Rumawi) itu bergembiralah orang-orang yang beriman,<?php break;}
case 5:{?>karena pertolongan Allah. Dia menolong siapa yang dikehendaki-Nya. Dan Dialah Yang Maha Perkasa lagi Maha Penyayang.<?php break;}
case 6:{?>(sebagai) janji yang sebenar-benarnya dari Allah. Allah tidak akan menyalahi janji-Nya, tetapi kebanyakan manusia tidak mengetahui.<?php break;}
case 7:{?>Mereka hanya mengetahui yang lahir (saja) dari kehidupan dunia; sedang mereka tentang (kehidupan) akhirat adalah lalai.<?php break;}
case 8:{?>Dan mengapa mereka tidak memikirkan tentang (kejadian) diri mereka?, Allah tidak menjadikan langit dan bumi dan apa yang ada di antara keduanya melainkan dengan (tujuan) yang benar dan waktu yang ditentukan. Dan sesungguhnya kebanyakan di antara manusia benar-benar ingkar akan pertemuan dengan Tuhannya.<?php break;}
case 9:{?>Dan apakah mereka tidak mengadakan perjalanan di muka bumi dan memperhatikan bagaimana akibat (yang diderita) oleh orang-orang yang sebelum mereka? Orang-orang itu adalah lebih kuat dari mereka (sendiri) dan telah mengolah bumi (tanah) serta memakmurkannya lebih banyak dari apa yang telah mereka makmurkan. Dan telah datang kepada mereka rasul-rasul mereka dengan membawa bukti-bukti yang nyata. Maka Allah sekali-kali tidak berlaku lalim kepada mereka, akan tetapi merekalah yang berlaku lalim kepada diri sendiri.<?php break;}
case 10:{?>Kemudian, akibat orang-orang yang mengerjakan kejahatan adalah (azab) yang lebih buruk, karena mereka mendustakan ayat-ayat Allah dan mereka selalu memperolok-oloknya.<?php break;}
case 11:{?>Allah menciptakan (manusia) dari permulaan, kemudian mengembalikan (menghidupkan) nya kembali; kemudian kepada-Nyalah kamu dikembalikan.<?php break;}
case 12:{?>Dan pada hari terjadinya kiamat, orang-orang yang berdosa terdiam berputus asa.<?php break;}
case 13:{?>Dan sekali-kali tidak ada pemberi syafa'at bagi mereka dari berhala-berhala mereka dan adalah mereka mengingkari berhala mereka itu.<?php break;}
case 14:{?>Dan pada hari terjadinya kiamat, di hari itu mereka (manusia) bergolong-golongan.<?php break;}
case 15:{?>Adapun orang-orang yang beriman dan mengerjakan amal saleh, maka mereka di dalam taman (surga) bergembira.<?php break;}
case 16:{?>Adapun orang-orang yang kafir dan mendustakan ayat-ayat Kami (Al Qur'an) serta (mendustakan) menemui hari akhirat, maka mereka tetap berada di dalam siksaan (neraka).<?php break;}
case 17:{?>Maka bertasbihlah kepada Allah di waktu kamu berada di petang hari dan waktu kamu berada di waktu subuh,<?php break;}
case 18:{?>dan bagi-Nyalah segala puji di langit dan di bumi dan di waktu kamu berada pada petang hari dan di waktu kamu berada di waktu Zuhur.<?php break;}
case 19:{?>Dia mengeluarkan yang hidup dari yang mati dan mengeluarkan yang mati dari yang hidup dan menghidupkan bumi sesudah matinya. Dan seperti itulah kamu akan dikeluarkan (dari kubur).<?php break;}
case 20:{?>Dan di antara tanda-tanda kekuasaan-Nya ialah Dia menciptakan kamu dari tanah, kemudian tiba-tiba kamu (menjadi) manusia yang berkembang biak.<?php break;}
case 21:{?>Dan di antara tanda-tanda kekuasaan-Nya ialah Dia menciptakan untukmu istri-istri dari jenismu sendiri, supaya kamu cenderung dan merasa tenteram kepadanya, dan dijadikan-Nya di antaramu rasa kasih dan sayang. Sesungguhnya pada yang demikian itu benar-benar terdapat tanda-tanda bagi kaum yang berpikir.<?php break;}
case 22:{?>Dan di antara tanda-tanda kekuasaan-Nya ialah menciptakan langit dan bumi dan berlain-lainan bahasamu dan warna kulitmu. Sesungguhnya pada yang demikian itu benar-benar terdapat tanda-tanda bagi orang-orang yang mengetahui.<?php break;}
case 23:{?>Dan di antara tanda-tanda kekuasaan-Nya ialah tidurmu di waktu malam dan siang hari dan usahamu mencari sebagian dari karunia-Nya. Sesungguhnya pada yang demikian itu benar-benar terdapat tanda-tanda bagi kaum yang mendengarkan.<?php break;}
case 24:{?>Dan di antara tanda-tanda kekuasaan-Nya, Dia memperlihatkan kepadamu kilat untuk (menimbulkan) ketakutan dan harapan, dan Dia menurunkan air hujan dari langit, lalu menghidupkan bumi dengan air itu sesudah matinya. Sesungguhnya pada yang demikian itu benar-benar terdapat tanda-tanda bagi kaum yang mempergunakan akalnya.<?php break;}
case 25:{?>Dan di antara tanda-tanda kekuasaan-Nya ialah berdirinya langit dan bumi dengan iradah-Nya. Kemudian apabila Dia memanggil kamu sekali panggil dari bumi, seketika itu (juga) kamu keluar (dari kubur).<?php break;}
case 26:{?>Dan kepunyaan-Nyalah siapa saja yang ada di langit dan di bumi. Semuanya hanya kepada-Nya tunduk.<?php break;}
case 27:{?>Dan Dialah yang menciptakan (manusia) dari permulaan, kemudian mengembalikan (menghidupkan) nya kembali, dan menghidupkan kembali itu adalah lebih mudah bagi-Nya. Dan bagi-Nya lah sifat yang Maha Tinggi di langit dan di bumi; dan Dialah Yang Maha Perkasa lagi Maha Bijaksana.<?php break;}
case 28:{?>Dia membuat perumpamaan untuk kamu dari dirimu sendiri. Apakah ada diantara hamba-sahaya yang dimiliki oleh tangan kananmu, sekutu bagimu dalam (memiliki) rezeki yang telah Kami berikan kepadamu; maka kamu sama dengan mereka dalam (hak mempergunakan) rezeki itu, kamu takut kepada mereka sebagaimana kamu takut kepada dirimu sendiri? Demikianlah Kami jelaskan ayat-ayat bagi kaum yang berakal.<?php break;}
case 29:{?>Tetapi orang-orang yang lalim, mengikuti hawa nafsunya tanpa ilmu pengetahuan; maka siapakah yang akan menunjuki orang yang telah disesatkan Allah? Dan tiadalah bagi mereka seorang penolongpun.<?php break;}
case 30:{?>Maka hadapkanlah wajahmu dengan lurus kepada agama (Allah); (tetaplah atas) fitrah Allah yang telah menciptakan manusia menurut fitrah itu. Tidak ada perubahan pada fitrah Allah. (Itulah) agama yang lurus; tetapi kebanyakan manusia tidak mengetahui,<?php break;}
case 31:{?>dengan kembali bertobat kepada-Nya dan bertakwalah kepada-Nya serta dirikanlah salat dan janganlah kamu termasuk orang-orang yang mempersekutukan Allah,<?php break;}
case 32:{?>yaitu orang-orang yang memecah belah agama mereka dan mereka menjadi beberapa golongan. Tiap-tiap golongan merasa bangga dengan apa yang ada pada golongan mereka.<?php break;}
case 33:{?>Dan apabila manusia disentuh oleh suatu bahaya, mereka menyeru Tuhannya dengan kembali bertobat kepada-Nya, kemudian apabila Tuhan merasakan kepada mereka barang sedikit rahmat daripada-Nya, tiba-tiba sebahagian daripada mereka mempersekutukan Tuhannya,<?php break;}
case 34:{?>sehingga mereka mengingkari akan rahmat yang telah Kami berikan kepada mereka. Maka bersenang-senanglah kamu sekalian kelak kamu akan mengetahui (akibat perbuatanmu).<?php break;}
case 35:{?>Atau pernahkah Kami menurunkan kepada mereka keterangan, lalu keterangan itu menunjukkan (kebenaran) apa yang mereka selalu mempersekutukan dengan Tuhan?<?php break;}
case 36:{?>Dan apabila Kami rasakan sesuatu rahmat kepada manusia, niscaya mereka gembira dengan rahmat itu. Dan apabila mereka ditimpa sesuatu musibah (bahaya) disebabkan kesalahan yang telah dikerjakan oleh tangan mereka sendiri, tiba-tiba mereka itu berputus asa.<?php break;}
case 37:{?>Dan apakah mereka tidak memperhatikan bahwa sesungguhnya Allah melapangkan rezeki bagi siapa yang dikehendaki-Nya dan Dia (pula) yang menyempitkan (rezeki itu). Sesungguhnya pada yang demikian itu benar-benar terdapat tanda-tanda (kekuasaan Allah) bagi kaum yang beriman.<?php break;}
case 38:{?>Maka berikanlah kepada kerabat yang terdekat akan haknya, demikian (pula) kepada fakir miskin dan orang-orang yang dalam perjalanan. Itulah yang lebih baik bagi orang-orang yang mencari keridaan Allah; dan mereka itulah orang-orang beruntung.<?php break;}
case 39:{?>Dan sesuatu riba (tambahan) yang kamu berikan agar dia bertambah pada harta manusia, maka riba itu tidak menambah pada sisi Allah. Dan apa yang kamu berikan berupa zakat yang kamu maksudkan untuk mencapai keridaan Allah, maka (yang berbuat demikian) itulah orang-orang yang melipat gandakan (pahalanya).<?php break;}
case 40:{?>Allah-lah yang menciptakan kamu, kemudian memberimu rezeki, kemudian mematikanmu, kemudian menghidupkanmu (kembali). Adakah di antara yang kamu sekutukan dengan Allah itu yang dapat berbuat sesuatu dari yang demikian itu? Maha Sucilah Dia dan Maha Tinggi dari apa yang mereka persekutukan.<?php break;}
case 41:{?>Telah nampak kerusakan di darat dan di laut disebabkan karena perbuatan tangan manusia, supaya Allah merasakan kepada mereka sebahagian dari (akibat) perbuatan mereka, agar mereka kembali (ke jalan yang benar).<?php break;}
case 42:{?>Katakanlah: &quot;Adakan perjalanan di muka bumi dan perhatikanlah bagaimana kesudahan orang-orang yang dahulu. Kebanyakan dari mereka itu adalah orang-orang yang mempersekutukan (Allah)&quot;.<?php break;}
case 43:{?>Oleh karena itu, hadapkanlah wajahmu kepada agama yang lurus (Islam) sebelum datang dari Allah suatu hari yang tak dapat ditolak (kedatangannya): pada hari itu mereka terpisah-pisah.<?php break;}
case 44:{?>Barang siapa yang kafir maka dia sendirilah yang menanggung (akibat) kekafirannya itu; dan barang siapa yang beramal saleh maka untuk diri mereka sendirilah mereka menyiapkan (tempat yang menyenangkan),<?php break;}
case 45:{?>agar Allah memberi pahala kepada orang-orang yang beriman dan beramal saleh dari karunia-Nya. Sesungguhnya Dia tidak menyukai orang-orang yang ingkar.<?php break;}
case 46:{?>Dan di antara tanda-tanda kekuasaan-Nya ialah bahwa Dia mengirimkan angin sebagai pembawa berita gembira dan untuk merasakan kepadamu sebagian dari rahmat-Nya dan supaya kapal dapat berlayar dengan perintah-Nya dan (juga) supaya kamu dapat mencari karunia-Nya; mudah-mudahan kamu bersyukur.<?php break;}
case 47:{?>Dan sesungguhnya Kami telah mengutus sebelum kamu beberapa orang rasul kepada kaumnya, mereka datang kepadanya dengan membawa keterangan-keterangan (yang cukup), lalu Kami melakukan pembalasan terhadap orang-orang yang berdosa. Dan Kami selalu berkewajiban menolong orang-orang yang beriman.<?php break;}
case 48:{?>Allah, Dialah yang mengirim angin, lalu angin itu menggerakkan awan dan Allah membentangkannya di langit menurut yang dikehendaki-Nya, dan menjadikannya bergumpal-gumpal; lalu kamu lihat hujan ke luar dari celah-celahnya, maka apabila hujan itu turun mengenai hamba-hamba-Nya yang dikehendaki-Nya tiba-tiba mereka menjadi gembira.<?php break;}
case 49:{?>Dan sesungguhnya sebelum hujan diturunkan kepada mereka, mereka benar-benar telah berputus asa.<?php break;}
case 50:{?>Maka perhatikanlah bekas-bekas rahmat Allah, bagaimana Allah menghidupkan bumi yang sudah mati. Sesungguhnya (Tuhan yang berkuasa seperti) demikian benar-benar (berkuasa) menghidupkan orang-orang yang telah mati. Dan Dia Maha Kuasa atas segala sesuatu.<?php break;}
case 51:{?>Dan sungguh, jika Kami mengirimkan angin (kepada tumbuh-tumbuhan) lalu mereka melihat (tumbuh-tumbuhan itu) menjadi kuning (kering), benar-benar tetaplah mereka sesudah itu menjadi orang yang ingkar.<?php break;}
case 52:{?>Maka sesungguhnya kamu tidak akan sanggup menjadikan orang-orang yang mati itu dapat mendengar, dan menjadikan orang-orang yang tuli dapat mendengar seruan, apabila mereka itu berpaling membelakang.<?php break;}
case 53:{?>Dan kamu sekali-kali tidak akan dapat memberi petunjuk kepada orang-orang yang buta (mata hatinya) dari kesesatannya. Dan kamu tidak dapat memperdengarkan (petunjuk Tuhan) melainkan kepada orang-orang yang beriman dengan ayat-ayat Kami, mereka itulah orang-orang yang berserah diri (kepada Kami).<?php break;}
case 54:{?>Allah, Dialah yang menciptakan kamu dari keadaan lemah, kemudian Dia menjadikan (kamu) sesudah keadaan lemah itu menjadi kuat, kemudian Dia menjadikan (kamu) sesudah kuat itu lemah (kembali) dan beruban. Dia menciptakan apa yang dikehendaki-Nya dan Dialah Yang Maha Mengetahui lagi Maha Kuasa.<?php break;}
case 55:{?>Dan pada hari terjadinya kiamat, bersumpahlah orang-orang yang berdosa; &quot;Mereka tidak berdiam (dalam kubur) melainkan sesaat (saja)&quot;. Seperti demikianlah mereka selalu dipalingkan (dari kebenaran).<?php break;}
case 56:{?>Dan berkata orang-orang yang diberi ilmu pengetahuan dan keimanan (kepada orang-orang yang kafir): &quot;Sesungguhnya kamu telah berdiam (dalam kubur) menurut ketetapan Allah, sampai hari berbangkit; maka inilah hari berbangkit itu akan tetapi kamu selalu tidak meyakini (nya).<?php break;}
case 57:{?>Maka pada hari itu tidak bermanfaat (lagi) bagi orang-orang yang lalim permintaan uzur mereka, dan tidak pula mereka diberi kesempatan bertobat lagi.<?php break;}
case 58:{?>Dan sesungguhnya telah Kami buat dalam Al Qur'an ini segala macam perumpamaan untuk manusia. Dan sesungguhnya jika kamu membawa kepada mereka suatu ayat, pastilah orang-orang yang kafir itu akan berkata: &quot;Kamu tidak lain hanyalah orang-orang yang membuat kepalsuan belaka&quot;.<?php break;}
case 59:{?>Demikianlah Allah mengunci mati hati orang-orang yang tidak (mau) memahami.<?php break;}
case 60:{?>Maka bersabarlah kamu, sesungguhnya janji Allah adalah benar dan sekali-kali janganlah orang-orang yang tidak meyakini (kebenaran ayat-ayat Allah) itu menggelisahkan kamu.<?php break;}
}?>