<?php 
switch($verse){
case 1:{?>Segala puji bagi Allah Pencipta langit dan bumi, Yang menjadikan malaikat sebagai utusan-utusan (untuk mengurus berbagai macam urusan) yang mempunyai sayap, masing-masing (ada yang) dua, tiga dan empat. Allah menambahkan pada ciptaan-Nya apa yang dikehendaki-Nya. Sesungguhnya Allah Maha Kuasa atas segala sesuatu.<?php break;}
case 2:{?>Apa saja yang Allah anugerahkan kepada manusia berupa rahmat, maka tidak ada seorang pun yang dapat menahannya; dan apa saja yang ditahan oleh Allah maka tidak seorang pun yang sanggup untuk melepaskannya sesudah itu. Dan Dia-lah Yang Maha Perkasa lagi Maha Bijaksana.<?php break;}
case 3:{?>Hai manusia, ingatlah akan nikmat Allah kepadamu. Adakah pencipta selain Allah yang dapat memberikan rezeki kepada kamu dari langit dan bumi? Tidak ada Tuhan (yang berhak disembah) selain Dia; maka mengapakah kamu berpaling (dari ketauhidan)?<?php break;}
case 4:{?>Dan jika mereka mendustakan kamu (sesudah kamu beri peringatan), maka sungguh telah didustakan pula rasul-rasul sebelum kamu. Dan hanya kepada Allah-lah dikembalikan segala urusan.<?php break;}
case 5:{?>Hai manusia, sesungguhnya janji Allah adalah benar, maka sekali-kali janganlah kehidupan dunia memperdayakan kamu dan sekali-kali janganlah syetan yang pandai menipu, memperdayakan kamu tentang Allah.<?php break;}
case 6:{?>Sesungguhnya setan itu adalah musuh bagimu, maka anggaplah ia musuh (mu), karena sesungguhnya setan-setan itu hanya mengajak golongannya supaya mereka menjadi penghuni neraka yang menyala-nyala.<?php break;}
case 7:{?>Orang-orang yang kafir bagi mereka azab yang keras. Dan orang-orang yang beriman dan mengerjakan amal saleh bagi mereka ampunan dan pahala yang besar.<?php break;}
case 8:{?>Maka apakah orang yang dijadikan (setan) menganggap baik pekerjaannya yang buruk lalu dia meyakini pekerjaan itu baik, (sama dengan orang yang tidak ditipu oleh setan)? maka sesungguhnya Allah menyesatkan siapa yang dikehendaki-Nya dan menunjuki siapa yang dikehendaki-Nya; maka janganlah dirimu binasa karena kesedihan terhadap mereka. Sesungguhnya Allah Maha Mengetahui apa yang mereka perbuat.<?php break;}
case 9:{?>Dan Allah, Dialah Yang mengirimkan angin; lalu angin itu menggerakkan awan, maka Kami halau awan itu ke suatu negeri yang mati lalu Kami hidupkan bumi setelah matinya dengan hujan itu. Demikianlah kebangkitan itu.<?php break;}
case 10:{?>Barang siapa yang menghendaki kemuliaan, maka bagi Allah-lah kemuliaan itu semuanya. Kepada-Nya lah naik perkataan-perkataan yang baik dan amal yang saleh dinaikkan-Nya. Dan orang-orang yang merencanakan kejahatan bagi mereka azab yang keras, dan rencana jahat mereka akan hancur.<?php break;}
case 11:{?>Dan Allah menciptakan kamu dari tanah kemudian dari air mani, kemudian Dia menjadikan kamu berpasangan (laki-laki dan perempuan). Dan tidak ada seorang perempuanpun mengandung dan tidak (pula) melahirkan melainkan dengan sepengetahuan-Nya. Dan sekali-kali tidak dipanjangkan umur seorang yang berumur panjang dan tidak pula dikurangi umurnya, melainkan (sudah ditetapkan) dalam Kitab (Lohmahfuz). Sesungguhnya yang demikian itu bagi Allah adalah mudah.<?php break;}
case 12:{?>Dan tiada sama (antara) dua laut; yang ini tawar, segar, sedap diminum dan yang lain asin lagi pahit. Dan dari masing-masing laut itu kamu dapat memakan daging yang segar dan kamu dapat mengeluarkan perhiasan yang dapat kamu memakainya, dan pada masing-masingnya kamu lihat kapal-kapal berlayar membelah laut supaya kamu dapat mencari karunia-Nya dan supaya kamu bersyukur.<?php break;}
case 13:{?>Dia memasukkan malam ke dalam siang dan memasukkan siang ke dalam malam dan menundukkan matahari dan bulan, masing-masing berjalan menurut waktu yang ditentukan. Yang (berbuat) demikian Allah Tuhanmu, kepunyaan-Nya lah kerajaan. Dan orang-orang yang kamu seru (sembah) selain Allah tiada mempunyai apa-apa walaupun setipis kulit ari.<?php break;}
case 14:{?>Jika kamu menyeru mereka, mereka tiada mendengar seruanmu; dan kalau mereka mendengar, mereka tidak dapat memperkenankan permintaanmu. Dan di hari kiamat mereka akan mengingkari kemusyrikanmu dan tidak ada yang dapat memberikan keterangan kepadamu sebagai yang diberikan oleh Yang Maha Mengetahui.<?php break;}
case 15:{?>Hai manusia, kamulah yang berkehendak kepada Allah; dan Allah Dia-lah Yang Maha Kaya (tidak memerlukan sesuatu) lagi Maha Terpuji.<?php break;}
case 16:{?>Jika Dia menghendaki, niscaya Dia memusnahkan kamu dan mendatangkan makhluk yang baru (untuk menggantikan kamu).<?php break;}
case 17:{?>Dan yang demikian itu sekali-kali tidak sulit bagi Allah.<?php break;}
case 18:{?>Dan orang yang berdosa tidak akan memikul dosa orang lain. Dan jika seseorang yang berat dosanya memanggil (orang lain) untuk memikul dosanya itu tiadalah akan dipikulkan untuknya sedikit pun meskipun (yang dipanggilnya itu) kaum kerabatnya. Sesungguhnya yang dapat kamu beri peringatan hanya orang-orang yang takut kepada azab Tuhannya (sekalipun) mereka tidak melihat-Nya dan mereka mendirikan sembahyang. Dan barang siapa yang menyucikan dirinya, sesungguhnya ia menyucikan diri untuk kebaikan dirinya sendiri. Dan kepada Allah-lah kembali (mu).<?php break;}
case 19:{?>Dan tidaklah sama orang yang buta dengan orang yang melihat.<?php break;}
case 20:{?>dan tidak (pula) sama gelap gulita dengan cahaya.<?php break;}
case 21:{?>dan tidak (pula) sama yang teduh dengan yang panas.<?php break;}
case 22:{?>dan tidak (pula) sama orang-orang yang hidup dan orang-orang yang mati. Sesungguhnya Allah memberikan pendengaran kepada siapa yang dikehendaki-Nya dan kamu sekali-kali tiada sanggup menjadikan orang yang di dalam kubur dapat mendengar.<?php break;}
case 23:{?>Kamu tidak lain hanyalah seorang pemberi peringatan.<?php break;}
case 24:{?>Sesungguhnya Kami mengutus kamu dengan membawa kebenaran sebagai pembawa berita gembira dan sebagai pemberi peringatan. Dan tidak ada suatu umat pun melainkan telah ada padanya seorang pemberi peringatan.<?php break;}
case 25:{?>Dan jika mereka mendustakan kamu, maka sesungguhnya orang-orang yang sebelum mereka telah mendustakan (rasul-rasulnya); kepada mereka telah datang rasul-rasulnya dengan membawa mukjizat yang nyata, zubur, dan kitab yang memberi penjelasan yang sempurna.<?php break;}
case 26:{?>Kemudian Aku azab orang-orang yang kafir; maka (lihatlah) bagaimana (hebatnya) akibat kemurkaan-Ku.<?php break;}
case 27:{?>Tidakkah kamu melihat bahwasanya Allah menurunkan hujan dari langit lalu Kami hasilkan dengan hujan itu buah-buahan yang beraneka macam jenisnya. Dan di antara gunung-gunung itu ada garis-garis putih dan merah yang beraneka macam warnanya dan ada (pula) yang hitam pekat.<?php break;}
case 28:{?>Dan demikian (pula) di antara manusia, binatang-binatang melata dan binatang-binatang ternak ada yang bermacam-macam warnanya (dan jenisnya). Sesungguhnya yang takut kepada Allah di antara hamba-hamba-Nya, hanyalah ulama. Sesungguhnya Allah Maha perkasa lagi Maha Pengampun.<?php break;}
case 29:{?>Sesungguhnya orang-orang yang selalu membaca kitab Allah dan mendirikan salat dan menafkahkan sebahagian dari rezeki yang Kami anugerahkan kepada mereka dengan diam-diam dan terang-terangan, mereka itu mengharapkan perniagaan yang tidak akan merugi,<?php break;}
case 30:{?>agar Allah menyempurnakan kepada mereka pahala mereka dan menambah kepada mereka dari karunia-Nya. Sesungguhnya Allah Maha Pengampun lagi Maha Mensyukuri.<?php break;}
case 31:{?>Dan apa yang telah Kami wahyukan kepadamu yaitu Al Kitab (Al Qur'an) itulah yang benar, dengan membenarkan kitab-kitab yang sebelumnya. Sesungguhnya Allah benar-benar Maha Mengetahui lagi Maha Melihat (keadaan) hamba-hamba-Nya.<?php break;}
case 32:{?>Kemudian Kitab itu Kami wariskan kepada orang-orang yang Kami pilih di antara hamba-hamba Kami, lalu di antara mereka ada yang menganiaya diri mereka sendiri dan di antara mereka ada yang pertengahan dan di antara mereka ada (pula) yang lebih dahulu berbuat kebaikan dengan izin Allah. Yang demikian itu adalah karunia yang amat besar.<?php break;}
case 33:{?>(Bagi mereka) surga Adn, mereka masuk ke dalamnya, di dalamnya mereka diberi perhiasan dengan gelang-gelang dari emas, dan dengan mutiara, dan pakaian mereka di dalamnya adalah sutera.<?php break;}
case 34:{?>Dan mereka berkata: &quot;Segala puji bagi Allah yang telah menghilangkan duka cita dari kami. Sesungguhnya Tuhan kami benar-benar Maha Pengampun lagi Maha Mensyukuri.<?php break;}
case 35:{?>Yang menempatkan kami dalam tempat yang kekal (surga) dari karunia-Nya; di dalamnya kami tiada merasa lelah dan tiada pula merasa lesu&quot;.<?php break;}
case 36:{?>Dan orang-orang kafir bagi mereka neraka Jahanam. Mereka tidak dibinasakan sehingga mereka mati dan tidak (pula) diringankan dari mereka azabnya. Demikianlah kami membalas setiap orang yang sangat kafir.<?php break;}
case 37:{?>Dan mereka berteriak di dalam neraka itu: &quot;Ya Tuhan kami, keluarkanlah kami niscaya kami akan mengerjakan amal yang saleh berlainan dengan yang telah kami kerjakan&quot;. Dan apakah Kami tidak memanjangkan umurmu dalam masa yang cukup untuk berpikir bagi orang yang mau berpikir, dan (apakah tidak) datang kepada kamu pemberi peringatan? maka rasakanlah (azab Kami) dan tidak ada bagi orang-orang yang lalim seorang penolongpun.<?php break;}
case 38:{?>Sesungguhnya Allah mengetahui yang tersembunyi di langit dan di bumi. Sesungguhnya Dia Maha Mengetahui segala isi hati.<?php break;}
case 39:{?>Dia-lah yang menjadikan kamu khalifah-khalifah di muka bumi. Barang siapa yang kafir, maka (akibat) kekafirannya menimpa dirinya sendiri. Dan kekafiran orang-orang yang kafir itu tidak lain hanyalah akan menambah kemurkaan pada sisi Tuhannya dan kekafiran orang-orang yang kafir itu tidak lain hanyalah akan menambah kerugian mereka belaka.<?php break;}
case 40:{?>Katakanlah: &quot;Terangkanlah kepada-Ku tentang sekutu-sekutumu yang kamu seru selain Allah. Perlihatkanlah kepada-Ku (bahagian) manakah dari bumi ini yang telah mereka ciptakan ataukah mereka mempunyai saham dalam (penciptaan) langit atau adakah Kami memberi kepada mereka sebuah Kitab sehingga mereka mendapat keterangan-keterangan yang jelas daripadanya? Sebenarnya orang-orang yang lalim itu sebahagian dari mereka tidak menjanjikan kepada sebahagian yang lain, melainkan tipuan belaka&quot;.<?php break;}
case 41:{?>Sesungguhnya Allah menahan langit dan bumi supaya jangan lenyap; dan sungguh jika keduanya akan lenyap tidak ada seorang pun yang dapat menahan keduanya selain Allah. Sesungguhnya Dia adalah Maha Penyantun lagi Maha Pengampun.<?php break;}
case 42:{?>Dan mereka bersumpah dengan nama Allah dengan sekuat-kuat sumpah; sesungguhnya jika datang kepada mereka seorang pemberi peringatan, niscaya mereka akan lebih mendapat petunjuk dari salah satu umat-umat (yang lain). Tatkala datang kepada mereka pemberi peringatan, maka kedatangannya itu tidak menambah kepada mereka, kecuali jauhnya mereka dari (kebenaran),<?php break;}
case 43:{?>karena kesombongan (mereka) di muka bumi dan karena rencana (mereka) yang jahat. Rencana yang jahat itu tidak akan menimpa selain orang yang merencanakannya sendiri. Tiadalah yang mereka nanti-nantikan melainkan (berlakunya) sunnah (Allah yang telah berlaku) kepada orang-orang yang terdahulu. Maka sekali-kali kamu tidak akan mendapat penggantian bagi sunah Allah, dan sekali-kali tidak (pula) akan menemui penyimpangan bagi sunah Allah itu.<?php break;}
case 44:{?>Dan apakah mereka tidak berjalan di muka bumi, lalu melihat bagaimana kesudahan orang-orang yang sebelum mereka, sedangkan orang-orang itu adalah lebih besar kekuatannya dari mereka? Dan tiada sesuatu pun yang dapat melemahkan Allah baik di langit maupun di bumi. Sesungguhnya Allah Maha Mengetahui lagi Maha Kuasa.<?php break;}
case 45:{?>Dan kalau sekiranya Allah menyiksa manusia disebabkan usahanya, niscaya Dia tidak akan meninggalkan di atas permukaan bumi suatu makhluk yang melata pun akan tetapi Allah menangguhkan (penyiksaan) mereka, sampai waktu yang tertentu; maka apabila datang ajal mereka, maka sesungguhnya Allah adalah Maha Melihat (keadaan) hamba-hamba-Nya.<?php break;}
}?>