<?php 
switch($verse){
case 1:{?>Kitab (Al Qur'an ini) diturunkan oleh Allah Yang Maha Perkasa lagi Maha Bijaksana.<?php break;}
case 2:{?>Sesungguhnya Kami menurunkan kepadamu Kitab (Al Qur'an) dengan (membawa) kebenaran. Maka sembahlah Allah dengan memurnikan ketaatan kepada-Nya.<?php break;}
case 3:{?>Ingatlah, hanya kepunyaan Allah-lah agama yang bersih (dari syirik). Dan orang-orang yang mengambil pelindung selain Allah (berkata): &quot;Kami tidak menyembah mereka melainkan supaya mereka mendekatkan kami kepada Allah dengan sedekat-dekatnya&quot;. Sesungguhnya Allah akan memutuskan di antara mereka tentang apa yang mereka berselisih padanya. Sesungguhnya Allah tidak menunjuki orang-orang yang pendusta dan sangat ingkar.<?php break;}
case 4:{?>Kalau sekiranya Allah hendak mengambil anak, tentu Dia akan memilih apa yang dikehendaki-Nya di antara ciptaan-ciptaan yang telah diciptakan-Nya. Maha Suci Allah. Dia-lah Allah Yang Maha Esa lagi Maha Mengalahkan.<?php break;}
case 5:{?>Dia menciptakan langit dan bumi dengan (tujuan) yang benar; Dia menutupkan malam atas siang dan menutupkan siang atas malam dan menundukkan matahari dan bulan, masing-masing berjalan menurut waktu yang ditentukan. Ingatlah Dialah Yang Maha Perkasa lagi Maha Pengampun.<?php break;}
case 6:{?>Dia menciptakan kamu dari seorang diri kemudian Dia jadikan daripadanya istrinya dan Dia menurunkan untuk kamu delapan ekor yang berpasangan dari binatang ternak. Dia menjadikan kamu dalam perut ibumu kejadian demi kejadian dalam tiga kegelapan. Yang (berbuat) demikian itu adalah Allah, Tuhan kamu, Tuhan Yang mempunyai kerajaan. Tidak ada Tuhan (yang berhak disembah) selain Dia; maka bagaimana kamu dapat dipalingkan?<?php break;}
case 7:{?>Jika kamu kafir, maka sesungguhnya Allah tidak memerlukan (iman) mu dan Dia tidak meridai kekafiran bagi hamba-Nya; dan jika kamu bersyukur, niscaya Dia meridai bagimu kesyukuranmu itu; dan seorang yang berdosa tidak akan memikul dosa orang lain. Kemudian kepada Tuhanmulah kembalimu lalu Dia memberitakan kepadamu apa yang telah kamu kerjakan. Sesungguhnya Dia Maha Mengetahui apa yang tersimpan dalam (dada) mu.<?php break;}
case 8:{?>Dan apabila manusia itu ditimpa kemudaratan, dia memohon (pertolongan) kepada Tuhannya dengan kembali kepada-Nya; kemudian apabila Tuhan memberikan nikmat-Nya kepadanya lupalah dia akan kemudaratan yang pernah dia berdoa (kepada Allah) untuk (menghilangkannya) sebelum itu, dan dia mengada-adakan sekutu-sekutu bagi Allah untuk menyesatkan (manusia) dari jalan-Nya. Katakanlah: &quot;Bersenang-senanglah dengan kekafiranmu itu sementara waktu; sesungguhnya kamu termasuk penghuni neraka&quot;.<?php break;}
case 9:{?>(Apakah kamu hai orang musyrik yang lebih beruntung) ataukah orang yang beribadah di waktu-waktu malam dengan sujud dan berdiri, sedang ia takut kepada (azab) akhirat dan mengharapkan rahmat Tuhannya? Katakanlah: &quot;Adakah sama orang-orang yang mengetahui dengan orang-orang yang tidak mengetahui?&quot; Sesungguhnya orang yang berakallah yang dapat menerima pelajaran.<?php break;}
case 10:{?>Katakanlah: &quot;Hai hamba-hamba-Ku yang beriman, bertakwalah kepada Tuhanmu&quot;. Orang-orang yang berbuat baik di dunia ini memperoleh kebaikan. Dan bumi Allah itu adalah luas. Sesungguhnya hanya orang-orang yang bersabarlah yang dicukupkan pahala mereka tanpa batas.<?php break;}
case 11:{?>Katakanlah: &quot;Sesungguhnya aku diperintahkan supaya menyembah Allah dengan memurnikan ketaatan kepada-Nya dalam (menjalankan) agama.<?php break;}
case 12:{?>Dan aku diperintahkan supaya menjadi orang yang pertama-tama berserah diri&quot;.<?php break;}
case 13:{?>Katakanlah: &quot;Sesungguhnya aku takut akan siksaan hari yang besar jika aku durhaka kepada Tuhanku&quot;.<?php break;}
case 14:{?>Katakanlah: &quot;Hanya Allah saja Yang aku sembah dengan memurnikan ketaatan kepada-Nya dalam (menjalankan) agamaku&quot;.<?php break;}
case 15:{?>Maka sembahlah olehmu (hai orang-orang musyrik) apa yang kamu kehendaki selain Dia. Katakanlah: &quot;Sesungguhnya orang-orang yang rugi ialah orang-orang yang merugikan diri mereka sendiri dan keluarganya pada hari kiamat&quot;. Ingatlah yang demikian itu adalah kerugian yang nyata.<?php break;}
case 16:{?>Bagi mereka lapisan-lapisan dari api di atas mereka dan di bawah mereka pun lapisan-lapisan (dari api). Demikianlah Allah mempertakuti hamba-hamba-Nya dengan azab itu. Maka bertakwalah kepada-Ku hai hamba-hamba-Ku.<?php break;}
case 17:{?>Dan orang-orang yang menjauhi thaghut (yaitu) tidak menyembahnya dan kembali kepada Allah, bagi mereka berita gembira; sebab itu sampaikanlah berita itu kepada hamba-hamba-Ku,<?php break;}
case 18:{?>yang mendengarkan perkataan lalu mengikuti apa yang paling baik di antaranya. Mereka itulah orang-orang yang telah diberi Allah petunjuk dan mereka itulah orang-orang yang mempunyai akal.<?php break;}
case 19:{?>Apakah (kamu hendak mengubah nasib) orang-orang yang telah pasti ketentuan azab atasnya? Apakah kamu akan menyelamatkan orang yang berada dalam api neraka?<?php break;}
case 20:{?>Tetapi orang-orang yang bertakwa kepada Tuhannya mereka mendapat tempat-tempat yang tinggi, di atasnya dibangun pula tempat-tempat yang tinggi yang di bawahnya mengalir sungai-sungai. Allah telah berjanji dengan sebenar-benarnya. Allah tidak akan memungkiri janji-Nya.<?php break;}
case 21:{?>Apakah kamu tidak memperhatikan, bahwa sesungguhnya Allah menurunkan air dari langit, maka diaturnya menjadi sumber-sumber air di bumi kemudian ditumbuhkan-Nya dengan air itu tanam-tanaman yang bermacam-macam warnanya, lalu ia menjadi kering lalu kamu melihatnya kekuning-kuningan, kemudian dijadikan-Nya hancur berderai-derai. Sesungguhnya pada yang demikian itu benar-benar terdapat pelajaran bagi orang-orang yang mempunyai akal.<?php break;}
case 22:{?>Maka apakah orang-orang yang dibukakan Allah hatinya untuk (menerima) agama Islam lalu ia mendapat cahaya dari Tuhannya (sama dengan orang yang membatu hatinya)? Maka kecelakaan yang besarlah bagi mereka yang telah membatu hatinya untuk mengingat Allah. Mereka itu dalam kesesatan yang nyata.<?php break;}
case 23:{?>Allah telah menurunkan perkataan yang paling baik (yaitu) Al Qur'an yang serupa (mutu ayat-ayatnya) lagi berulang-ulang, gemetar karenanya kulit orang-orang yang takut kepada Tuhannya, kemudian menjadi tenang kulit dan hati mereka di waktu mengingat Allah. Itulah petunjuk Allah, dengan kitab itu Dia menunjuki siapa yang dikehendaki-Nya. Dan barang siapa yang disesatkan Allah, maka tidak ada seorang pun pemberi petunjuk baginya.<?php break;}
case 24:{?>Maka apakah orang-orang yang menoleh dengan mukanya menghindari azab yang buruk pada hari kiamat (sama dengan orang mukmin yang tidak kena azab)? Dan dikatakan kepada orang-orang yang lalim: &quot;Rasakanlah olehmu balasan apa yang telah kamu kerjakan&quot;.<?php break;}
case 25:{?>Orang-orang yang sebelum mereka telah mendustakan (rasul-rasul), maka datanglah kepada mereka azab dari arah yang tidak mereka sangka.<?php break;}
case 26:{?>Maka Allah merasakan kepada mereka kehinaan pada kehidupan dunia. Dan sesungguhnya azab pada hari akhirat lebih besar kalau mereka mengetahui.<?php break;}
case 27:{?>Sesungguhnya telah Kami buatkan bagi manusia dalam Al Qur'an ini setiap macam perumpamaan supaya mereka dapat pelajaran.<?php break;}
case 28:{?>(Ialah) Al Qur'an dalam bahasa Arab yang tidak ada kebengkokan (di dalamnya) supaya mereka bertakwa.<?php break;}
case 29:{?>Allah membuat perumpamaan (yaitu) seorang laki-laki (budak) yang dimiliki oleh beberapa orang yang berserikat yang dalam perselisihan dan seorang budak yang menjadi milik penuh dari seorang laki-laki (saja); Adakah kedua budak itu sama halnya? Segala puji bagi Allah, tetapi kebanyakan mereka tidak mengetahui.<?php break;}
case 30:{?>Sesungguhnya kamu akan mati dan sesungguhnya mereka akan mati (pula).<?php break;}
case 31:{?>Kemudian sesungguhnya kamu pada hari kiamat akan berbantah-bantah di hadapan Tuhanmu.<?php break;}
case 32:{?>Maka siapakah yang lebih lalim daripada orang yang membuat-buat dusta terhadap Allah dan mendustakan kebenaran ketika datang kepadanya? Bukankah di neraka Jahanam tersedia tempat tinggal bagi orang-orang yang kafir?<?php break;}
case 33:{?>Dan orang yang membawa kebenaran (Muhammad) dan membenarkannya, mereka itulah orang-orang yang bertakwa.<?php break;}
case 34:{?>Mereka memperoleh apa yang mereka kehendaki pada sisi Tuhan mereka. Demikianlah balasan orang-orang yang berbuat baik,<?php break;}
case 35:{?>agar Allah akan menutupi (mengampuni) bagi mereka perbuatan yang paling buruk yang mereka kerjakan dan membalas mereka dengan upah yang lebih baik dari apa yang telah mereka kerjakan.<?php break;}
case 36:{?>Bukankah Allah cukup untuk melindungi hamba-hamba-Nya. Dan mereka mempertakuti kamu dengan (sembahan-sembahan) yang selain Allah? Dan siapa yang disesatkan Allah, maka tidak seorang pun pemberi petunjuk baginya.<?php break;}
case 37:{?>Dan barang siapa yang diberi petunjuk oleh Allah, maka tidak seorang pun yang dapat menyesatkannya. Bukankah Allah Maha Perkasa lagi mempunyai (kekuasaan untuk) mengazab?<?php break;}
case 38:{?>Dan sungguh jika kamu bertanya kepada mereka: &quot;Siapakah yang menciptakan langit dan bumi?&quot;, niscaya mereka menjawab: &quot;Allah&quot;. Katakanlah: &quot;Maka terangkanlah kepadaku tentang apa yang kamu seru selain Allah, jika Allah hendak mendatangkan kemudaratan kepadaku, apakah berhala-berhalamu itu dapat menghilangkan kemudaratan itu, atau jika Allah hendak memberi rahmat kepadaku, apakah mereka dapat menahan rahmat-Nya?. Katakanlah: &quot;Cukuplah Allah bagiku&quot;. Kepada-Nya lah bertawakal orang-orang yang berserah diri.<?php break;}
case 39:{?>Katakanlah: &quot;Hai kaumku, bekerjalah sesuai dengan keadaanmu, sesungguhnya aku akan bekerja (pula), maka kelak kamu akan mengetahui,<?php break;}
case 40:{?>siapa yang akan mendapat siksa yang menghinakannya dan lagi ditimpa oleh azab yang kekal&quot;.<?php break;}
case 41:{?>Sesungguhnya kami menurunkan kepadamu Al Kitab (Al Qur'an) untuk manusia dengan membawa kebenaran; siapa yang mendapat petunjuk, maka (petunjuk itu) untuk dirinya sendiri, dan siapa yang sesat maka sesungguhnya dia semata-mata sesat buat (kerugian) dirinya sendiri dan kamu sekali-kali bukanlah orang yang bertanggung jawab terhadap mereka.<?php break;}
case 42:{?>Allah memegang jiwa (orang) ketika matinya dan (memegang) jiwa (orang) yang belum mati di waktu tidurnya; maka Dia tahanlah jiwa (orang) yang telah Dia tetapkan kematiannya dan Dia melepaskan jiwa yang lain sampai waktu yang ditentukan. Sesungguhnya pada yang demikian itu terdapat tanda-tanda kekuasaan Allah bagi kaum yang berpikir.<?php break;}
case 43:{?>Bahkan mereka mengambil pemberi syafaat selain Allah. Katakanlah: &quot;Dan apakah (kamu mengambilnya juga) meskipun mereka tidak memiliki sesuatupun dan tidak berakal?&quot;<?php break;}
case 44:{?>Katakanlah: &quot;Hanya kepunyaan Allah syafaat itu semuanya. Kepunyaan-Nya kerajaan langit dan bumi. Kemudian kepada-Nya lah kamu dikembalikan&quot;.<?php break;}
case 45:{?>Dan apabila hanya nama Allah saja yang disebut, kesallah hati orang-orang yang tidak beriman kepada kehidupan akhirat; dan apabila nama sembahan-sembahan selain Allah yang disebut, tiba-tiba mereka bergirang hati.<?php break;}
case 46:{?>Katakanlah: &quot;ya Allah, Pencipta langit dan bumi, Yang mengetahui barang gaib dan yang nyata, Engkaulah Yang memutuskan antara hamba-hamba-Mu tentang apa yang selalu mereka memperselisihkannya&quot;.<?php break;}
case 47:{?>Dan sekiranya orang-orang yang lalim mempunyai apa yang ada di bumi semuanya dan (ada pula) sebanyak itu besertanya, niscaya mereka akan menebus dirinya dengan itu dari siksa yang buruk pada hari kiamat. Dan jelaslah bagi mereka azab dari Allah yang belum pernah mereka perkirakan.<?php break;}
case 48:{?>Dan (jelaslah) bagi mereka akibat buruk dari apa yang telah mereka perbuat dan mereka diliputi oleh pembalasan yang mereka dahulu selalu memperolok-olokkannya.<?php break;}
case 49:{?>Maka apabila manusia ditimpa bahaya ia menyeru Kami, kemudian apabila Kami berikan kepadanya nikmat dari Kami ia berkata: &quot;Sesungguhnya aku diberi nikmat itu hanyalah karena kepintaranku&quot;. Sebenarnya itu adalah ujian, tetapi kebanyakan mereka itu tidak mengetahui.<?php break;}
case 50:{?>Sungguh orang-orang yang sebelum mereka (juga) telah mengatakan itu pula, maka tiadalah berguna bagi mereka apa yang dahulu mereka usahakan.<?php break;}
case 51:{?>Maka mereka ditimpa akibat buruk dari apa yang mereka usahakan. Dan orang-orang yang lalim di antara mereka akan ditimpa akibat buruk dari usahanya dan mereka tidak dapat melepaskan diri.<?php break;}
case 52:{?>Dan tidakkah mereka mengetahui bahwa Allah melapangkan rezeki dan menyempitkannya bagi siapa yang dikehendaki-Nya? Sesungguhnya pada yang demikian itu terdapat tanda-tanda kekuasaan Allah bagi kaum yang beriman.<?php break;}
case 53:{?>Katakanlah: &quot;Hai hamba-hamba-Ku yang melampaui batas terhadap diri mereka sendiri, janganlah kamu berputus asa dari rahmat Allah. Sesungguhnya Allah mengampuni dosa-dosa semuanya. Sesungguhnya Dialah Yang Maha Pengampun lagi Maha Penyayang.<?php break;}
case 54:{?>Dan kembalilah kamu kepada Tuhanmu, dan berserah dirilah kepada-Nya sebelum datang azab kepadamu kemudian kamu tidak dapat ditolong (lagi).<?php break;}
case 55:{?>Dan ikutilah sebaik-baik apa yang telah diturunkan kepadamu dari Tuhanmu sebelum datang azab kepadamu dengan tiba-tiba, sedang kamu tidak menyadarinya,<?php break;}
case 56:{?>supaya jangan ada orang yang mengatakan: &quot;Amat besar penyesalanku atas kelalaianku dalam (menunaikan kewajiban) terhadap Allah, sedang aku sesungguhnya termasuk orang-orang yang memperolok-olokkan (agama Allah).<?php break;}
case 57:{?>atau supaya jangan ada yang berkata: 'Kalau sekiranya Allah memberi petunjuk kepadaku tentulah aku termasuk orang-orang yang bertakwa'.<?php break;}
case 58:{?>Atau supaya jangan ada yang berkata ketika ia melihat azab: 'Kalau sekiranya aku dapat kembali (ke dunia), niscaya aku akan termasuk orang-orang berbuat baik'.<?php break;}
case 59:{?>(Bukan demikian) sebenarnya telah datang keterangan-keterangan-Ku kepadamu lalu kamu mendustakannya dan kamu menyombongkan diri dan adalah kamu termasuk orang-orang yang kafir&quot;.<?php break;}
case 60:{?>Dan pada hari kiamat kamu akan melihat orang-orang yang berbuat dusta terhadap Allah, mukanya menjadi hitam. Bukankah dalam neraka Jahanam itu ada tempat bagi orang-orang yang menyombongkan diri?<?php break;}
case 61:{?>Dan Allah menyelamatkan orang-orang yang bertakwa karena kemenangan mereka, mereka tiada disentuh oleh azab (neraka dan tidak pula) mereka berduka cita.<?php break;}
case 62:{?>Allah menciptakan segala sesuatu dan Dia memelihara segala sesuatu.<?php break;}
case 63:{?>Kepunyaan-Nya lah kunci-kunci (perbendaharaan) langit dan bumi. Dan orang-orang yang kafir terhadap ayat-ayat Allah, mereka itulah orang-orang yang merugi.<?php break;}
case 64:{?>Katakanlah: &quot;Maka apakah kamu menyuruh aku menyembah selain Allah, hai orang-orang yang tidak berpengetahuan?&quot;<?php break;}
case 65:{?>Dan sesungguhnya telah diwahyukan kepadamu dan kepada (nabi-nabi) yang sebelummu: &quot;Jika kamu mempersekutukan (Tuhan), niscaya akan hapuslah amalmu dan tentulah kamu termasuk orang-orang yang merugi.<?php break;}
case 66:{?>Karena itu, maka hendaklah Allah saja kamu sembah dan hendaklah kamu termasuk orang-orang yang bersyukur&quot;.<?php break;}
case 67:{?>Dan mereka tidak mengagungkan Allah dengan pengagungan yang semestinya padahal bumi seluruhnya dalam genggaman-Nya pada hari kiamat dan langit digulung dengan tangan kanan-Nya. Maha Suci Tuhan dan Maha Tinggi Dia dari apa yang mereka persekutukan.<?php break;}
case 68:{?>Dan ditiuplah sangkakala, maka matilah siapa yang di langit dan di bumi kecuali siapa yang dikehendaki Allah. Kemudian ditiup sangkakala itu sekali lagi, maka tiba-tiba mereka berdiri menunggu (putusannya masing-masing).<?php break;}
case 69:{?>Dan terang benderanglah bumi (padang mahsyar) dengan cahaya (keadilan) Tuhannya; dan diberikanlah buku (perhitungan perbuatan masing-masing) dan didatangkanlah para nabi dan saksi-saksi dan diberi keputusan di antara mereka dengan adil, sedang mereka tidak dirugikan.<?php break;}
case 70:{?>Dan disempurnakan bagi tiap-tiap jiwa (balasan) apa yang telah dikerjakannya dan Dia lebih mengetahui apa yang mereka kerjakan.<?php break;}
case 71:{?>Orang-orang kafir dibawa ke neraka Jahanam berombong-rombongan. Sehingga apabila mereka sampai ke neraka itu dibukakanlah pintu-pintunya dan berkatalah kepada mereka penjaga-penjaganya: &quot;Apakah belum pernah datang kepadamu rasul-rasul di antaramu yang membacakan kepadamu ayat-ayat Tuhanmu dan memperingatkan kepadamu akan pertemuan dengan hari ini?&quot; Mereka menjawab: &quot;Benar (telah datang)&quot;. Tetapi telah pasti berlaku ketetapan azab terhadap orang-orang yang kafir.<?php break;}
case 72:{?>Dikatakan (kepada mereka): &quot;Masukilah pintu-pintu neraka Jahanam itu, sedang kamu kekal di dalamnya&quot;. Maka neraka Jahanam itulah seburuk-buruk tempat bagi orang-orang yang menyombongkan diri.<?php break;}
case 73:{?>Dan orang-orang yang bertakwa kepada Tuhannya dibawa ke dalam surga berombong-rombongan (pula). Sehingga apabila mereka sampai ke surga itu sedang pintu-pintunya telah terbuka dan berkatalah kepada mereka penjaga-penjaganya: &quot;Kesejahteraan (dilimpahkan) atasmu, berbahagialah kamu! maka masukilah surga ini, sedang kamu kekal di dalamnya&quot;.<?php break;}
case 74:{?>Dan mereka mengucapkan: &quot;Segala puji bagi Allah yang telah memenuhi janji-Nya kepada kami dan telah (memberi) kepada kami tempat ini sedang kami (diperkenankan) menempati tempat dalam surga di mana saja yang kami kehendaki.&quot; Maka surga itulah sebaik-baik balasan bagi orang-orang yang beramal.<?php break;}
case 75:{?>Dan kamu (Muhammad) akan melihat malaikat-malaikat berlingkar di sekeliling Arasy bertasbih sambil memuji Tuhannya; dan diberi putusan di antara hamba-hamba Allah dengan adil dan diucapkan: &quot;Segala puji bagi Allah, Tuhan semesta alam&quot;.<?php break;}
}?>