<?php 
switch($verse){
case 1:{?>Hai sekalian manusia, bertakwalah kepada Tuhan-mu yang telah menciptakan kamu dari diri yang satu, dan daripadanya Allah menciptakan istrinya; dan daripada keduanya Allah memperkembang biakkan laki-laki dan perempuan yang banyak. Dan bertakwalah kepada Allah yang dengan (mempergunakan) nama-Nya kamu saling meminta satu sama lain, dan (peliharalah) hubungan silaturahmi. Sesungguhnya Allah selalu menjaga dan mengawasi kamu.<?php break;}
case 2:{?>Dan berikanlah kepada anak-anak yatim (yang sudah balig) harta mereka, jangan kamu menukar yang baik dengan yang buruk dan jangan kamu makan harta mereka bersama hartamu. Sesungguhnya tindakan-tindakan (menukar dan memakan) itu, adalah dosa yang besar.<?php break;}
case 3:{?>Dan jika kamu takut tidak akan dapat berlaku adil terhadap (hak-hak) perempuan yatim (bilamana kamu mengawininya), maka kawinilah wanita-wanita (lain) yang kamu senangi: dua, tiga atau empat. Kemudian jika kamu takut tidak akan dapat berlaku adil, maka (kawinilah) seorang saja, atau budak-budak yang kamu miliki. Yang demikian itu adalah lebih dekat kepada tidak berbuat aniaya.<?php break;}
case 4:{?>Berikanlah maskawin (mahar) kepada wanita (yang kamu nikahi) sebagai pemberian dengan penuh kerelaan. Kemudian jika mereka menyerahkan kepada kamu sebagian dari maskawin itu dengan senang hati, maka makanlah (ambillah) pemberian itu (sebagai makanan) yang sedap lagi baik akibatnya.<?php break;}
case 5:{?>Dan janganlah kamu serahkan kepada orang-orang yang belum sempurna akalnya, harta (mereka yang ada dalam kekuasaanmu) yang dijadikan Allah sebagai pokok kehidupan. Berilah mereka belanja dan pakaian (dari hasil harta itu) dan ucapkanlah kepada mereka kata-kata yang baik.<?php break;}
case 6:{?>Dan ujilah anak yatim itu sampai mereka cukup umur untuk kawin. Kemudian jika menurut pendapatmu mereka telah cerdas (pandai memelihara harta), maka serahkanlah kepada mereka harta-hartanya. Dan janganlah kamu makan harta anak yatim lebih dari batas kepatutan dan (janganlah kamu) tergesa-gesa (membelanjakannya) sebelum mereka dewasa. Barang siapa (di antara pemelihara itu) mampu, maka hendaklah ia menahan diri (dari memakan harta anak yatim itu) dan barang siapa miskin, maka bolehlah ia makan harta itu menurut yang patut. Kemudian apabila kamu menyerahkan harta kepada mereka, maka hendaklah kamu adakan saksi-saksi (tentang penyerahan itu) bagi mereka. Dan cukuplah Allah sebagai Pengawas (atas persaksian itu).<?php break;}
case 7:{?>Bagi laki-laki ada hak bagian dari harta peninggalan ibu-bapak dan kerabatnya, dan bagi wanita ada hak bagian (pula) dari harta peninggalan ibu-bapak dan kerabatnya, baik sedikit atau banyak menurut bahagian yang telah ditetapkan.<?php break;}
case 8:{?>Dan apabila sewaktu pembagian itu hadir kerabat, anak yatim dan orang miskin, maka berilah mereka dari harta itu (sekedarnya) dan ucapkanlah kepada mereka perkataan yang baik.<?php break;}
case 9:{?>Dan hendaklah takut kepada Allah orang-orang yang seandainya meninggalkan di belakang mereka anak-anak yang lemah, yang mereka khawatir terhadap (kesejahteraan) mereka. Oleh sebab itu hendaklah mereka bertakwa kepada Allah dan hendaklah mereka mengucapkan perkataan yang benar.<?php break;}
case 10:{?>Sesungguhnya orang-orang yang memakan harta anak yatim secara lalim, sebenarnya mereka itu menelan api sepenuh perutnya dan mereka akan masuk ke dalam api yang menyala-nyala (neraka).<?php break;}
case 11:{?>Allah mensyariatkan bagimu tentang (pembagian pusaka untuk) anak-anakmu. Yaitu: bahagian seorang anak lelaki sama dengan bahagian dua orang anak perempuan; dan jika anak itu semuanya perempuan lebih dari dua, maka bagi mereka dua pertiga dari harta yang ditinggalkan; jika anak perempuan itu seorang saja, maka ia memperoleh separo harta. Dan untuk dua orang ibu-bapak, bagi masing-masingnya seperenam dari harta yang ditinggalkan, jika yang meninggal itu mempunyai anak; jika orang yang meninggal tidak mempunyai anak dan ia diwarisi oleh ibu-bapaknya (saja), maka ibunya mendapat sepertiga; jika yang meninggal itu mempunyai beberapa saudara, maka ibunya mendapat seperenam. (Pembagian-pembagian tersebut di atas) sesudah dipenuhi wasiat yang ia buat atau (dan) sesudah dibayar utangnya. (Tentang) orang tuamu dan anak-anakmu, kamu tidak mengetahui siapa di antara mereka yang lebih dekat (banyak) manfaatnya bagimu. Ini adalah ketetapan dari Allah. Sesungguhnya Allah Maha Mengetahui lagi Maha Bijaksana.<?php break;}
case 12:{?>Dan bagimu (suami-suami) seperdua dari harta yang ditinggalkan oleh istri-istrimu, jika mereka tidak mempunyai anak. Jika istri-istrimu itu mempunyai anak, maka kamu mendapat seperempat dari harta yang ditinggalkannya sesudah dipenuhi wasiat yang mereka buat atau (dan) sesudah dibayar utangnya. Para istri memperoleh seperempat harta yang kamu tinggalkan jika kamu tidak mempunyai anak. Jika kamu mempunyai anak, maka para istri memperoleh seperdelapan dari harta yang kamu tinggalkan sesudah dipenuhi wasiat yang kamu buat atau (dan) sesudah dibayar utang-utangmu. Jika seseorang mati, baik laki-laki maupun perempuan yang tidak meninggalkan ayah dan tidak meninggalkan anak, tetapi mempunyai seorang saudara laki-laki (seibu saja) atau seorang saudara perempuan (seibu saja), maka bagi masing-masing dari kedua jenis saudara itu seperenam harta. Tetapi jika saudara-saudara seibu itu lebih dari seorang, maka mereka bersekutu dalam yang sepertiga itu, sesudah dipenuhi wasiat yang dibuat olehnya atau sesudah dibayar hutangnya dengan tidak memberi mudarat (kepada ahli waris). (Allah menetapkan yang demikian itu sebagai) syariat yang benar-benar dari Allah, dan Allah Maha Mengetahui lagi Maha Penyantun.<?php break;}
case 13:{?>(Hukum-hukum tersebut) itu adalah ketentuan-ketentuan dari Allah. Barang siapa taat kepada Allah dan Rasul-Nya, niscaya Allah memasukkannya ke dalam surga yang mengalir di dalamnya sungai-sungai, sedang mereka kekal di dalamnya; dan itulah kemenangan yang besar.<?php break;}
case 14:{?>Dan barang siapa yang mendurhakai Allah dan Rasul-Nya dan melanggar ketentuan-ketentuan-Nya, niscaya Allah memasukkannya ke dalam api neraka sedang ia kekal di dalamnya; dan baginya siksa yang menghinakan.<?php break;}
case 15:{?>Dan (terhadap) para wanita yang mengerjakan perbuatan keji, hendaklah ada empat orang saksi di antara kamu (yang menyaksikannya). Kemudian apabila mereka telah memberi persaksian, maka kurunglah mereka (wanita-wanita itu) dalam rumah sampai mereka menemui ajalnya, atau sampai Allah memberi jalan yang lain kepadanya.<?php break;}
case 16:{?>Dan terhadap dua orang yang melakukan perbuatan keji di antara kamu, maka berilah hukuman kepada keduanya, kemudian jika keduanya bertobat dan memperbaiki diri, maka biarkanlah mereka. Sesungguhnya Allah Maha Penerima tobat lagi Maha Penyayang.<?php break;}
case 17:{?>Sesungguhnya tobat di sisi Allah hanyalah tobat bagi orang-orang yang mengerjakan kejahatan lantaran kejahilan, yang kemudian mereka bertobat dengan segera, maka mereka itulah yang diterima Allah tobatnya; dan Allah Maha Mengetahui lagi Maha Bijaksana.<?php break;}
case 18:{?>Dan tidaklah tobat itu diterima Allah dari orang-orang yang mengerjakan kejahatan (yang) hingga apabila datang ajal kepada seseorang di antara mereka, (barulah) ia mengatakan: &quot;Sesungguhnya saya bertobat sekarang&quot; Dan tidak (pula diterima tobat) orang-orang yang mati sedang mereka di dalam kekafiran. Bagi orang-orang itu telah Kami sediakan siksa yang pedih.<?php break;}
case 19:{?>Hai orang-orang yang beriman, tidak halal bagi kamu mempusakai wanita dengan jalan paksa dan janganlah kamu menyusahkan mereka karena hendak mengambil kembali sebagian dari apa yang telah kamu berikan kepadanya, terkecuali bila mereka melakukan pekerjaan keji yang nyata. Dan bergaullah dengan mereka secara patut. Kemudian bila kamu tidak menyukai mereka, (maka bersabarlah) karena mungkin kamu tidak menyukai sesuatu, padahal Allah menjadikan padanya kebaikan yang banyak.<?php break;}
case 20:{?>Dan jika kamu ingin mengganti istrimu dengan istri yang lain, sedang kamu telah memberikan kepada seseorang di antara mereka harta yang banyak, maka janganlah kamu mengambil kembali daripadanya barang sedikit pun. Apakah kamu akan mengambilnya kembali dengan jalan tuduhan yang dusta dan dengan (menanggung) dosa yang nyata? [4.21] Bagaimana kamu akan mengambilnya kembali, padahal sebagian kamu telah bergaul (bercampur) dengan yang lain sebagai suami-istri. Dan mereka (istri-istrimu) telah mengambil dari kamu perjanjian yang kuat.<?php break;}
case 21:{?>Bagaimana kamu akan mengambilnya kembali, padahal sebagian kamu telah bergaul (bercampur) dengan yang lain sebagai suami istri. Dan mereka (istri-istrimu) telah mengambil dari kamu perjanjian yang kuat.<?php break;}
case 22:{?>Dan janganlah kamu kawini wanita-wanita yang telah dikawini oleh ayahmu, terkecuali pada masa yang telah lampau. Sesungguhnya perbuatan itu amat keji dan dibenci Allah dan seburuk-buruk jalan (yang ditempuh).<?php break;}
case 23:{?>Diharamkan atas kamu (mengawini) ibu-ibumu; anak-anakmu yang perempuan; saudara-saudaramu yang perempuan, saudara-saudara bapakmu yang perempuan; saudara-saudara ibumu yang perempuan; anak-anak perempuan dari saudara-saudaramu yang laki-laki; anak-anak perempuan dari saudara-saudaramu yang perempuan; ibu-ibumu yang menyusui kamu; saudara perempuan sepersusuan; ibu-ibu istrimu (mertua); anak-anak istrimu yang dalam pemeliharaanmu dari istri yang telah kamu campuri, tetapi jika kamu belum campur dengan istrimu itu (dan sudah kamu ceraikan), maka tidak berdosa kamu mengawininya; (dan diharamkan bagimu) istri-istri anak kandungmu (menantu); dan menghimpunkan (dalam perkawinan) dua perempuan yang bersaudara, kecuali yang telah terjadi pada masa lampau; sesungguhnya Allah Maha Pengampun lagi Maha Penyayang,<?php break;}
case 24:{?>dan (diharamkan juga kamu mengawini) wanita yang bersuami, kecuali budak-budak yang kamu miliki (Allah telah menetapkan hukum itu) sebagai ketetapan-Nya atas kamu. Dan dihalalkan bagi kamu selain yang demikian (yaitu) mencari istri-istri dengan hartamu untuk dikawini bukan untuk berzina. Maka istri-istri yang telah kamu nikmati (campuri) di antara mereka, berikanlah kepada mereka maharnya (dengan sempurna), sebagai suatu kewajiban; dan tiadalah mengapa bagi kamu terhadap sesuatu yang kamu telah saling merelakannya, sesudah menentukan mahar itu. Sesungguhnya Allah Maha Mengetahui lagi Maha Bijaksana.<?php break;}
case 25:{?>Dan barang siapa di antara kamu (orang merdeka) yang tidak cukup perbelanjaannya untuk mengawini wanita merdeka lagi beriman, ia boleh mengawini wanita yang beriman, dari budak-budak yang kamu miliki. Allah mengetahui keimananmu; sebahagian kamu adalah dari sebahagian yang lain, karena itu kawinilah mereka dengan seizin tuan mereka dan berilah maskawin mereka menurut yang patut, sedang mereka pun wanita-wanita yang memelihara diri, bukan pezina dan bukan (pula) wanita yang mengambil laki-laki lain sebagai piaraannya; dan apabila mereka telah menjaga diri dengan kawin, kemudian mereka mengerjakan perbuatan yang keji (zina), maka atas mereka separo hukuman dari hukuman wanita-wanita merdeka yang bersuami. (Kebolehan mengawini budak) itu, adalah bagi orang-orang yang takut kepada kesulitan menjaga diri (dari perbuatan zina) di antaramu, dan kesabaran itu lebih baik bagimu. Dan Allah Maha Pengampun lagi Maha Penyayang.<?php break;}
case 26:{?>Allah hendak menerangkan (hukum syariat-Nya) kepadamu, dan menunjukimu kepada jalan-jalan orang yang sebelum kamu (para nabi dan salihin) dan (hendak) menerima tobatmu. Dan Allah Maha Mengetahui lagi Maha Bijaksana.<?php break;}
case 27:{?>Dan Allah hendak menerima tobatmu, sedang orang-orang yang mengikuti hawa nafsunya bermaksud supaya kamu berpaling sejauh-jauhnya (dari kebenaran).<?php break;}
case 28:{?>Allah hendak memberikan keringanan kepadamu, dan manusia dijadikan bersifat lemah.<?php break;}
case 29:{?>Hai orang-orang yang beriman, janganlah kamu saling memakan harta sesamamu dengan jalan yang batil, kecuali dengan jalan perniagaan yang berlaku dengan suka sama-suka di antara kamu. Dan janganlah kamu membunuh dirimu; sesungguhnya Allah adalah Maha Penyayang kepadamu.<?php break;}
case 30:{?>Dan barang siapa berbuat demikian dengan melanggar hak dan aniaya, maka Kami kelak akan memasukkannya ke dalam neraka. Yang demikian itu adalah mudah bagi Allah.<?php break;}
case 31:{?>Jika kamu menjauhi dosa-dosa besar di antara dosa-dosa yang dilarang kamu mengerjakannya, niscaya Kami hapus kesalahan-kesalahanmu (dosa-dosamu yang kecil) dan Kami masukkan kamu ke tempat yang mulia (surga).<?php break;}
case 32:{?>Dan janganlah kamu iri hati terhadap apa yang dikaruniakan Allah kepada sebahagian kamu lebih banyak dari sebahagian yang lain. (Karena) bagi orang laki-laki ada bahagian daripada apa yang mereka usahakan, dan bagi para wanita (pun) ada bahagian dari apa yang mereka usahakan, dan mohonlah kepada Allah sebagian dari karunia-Nya. Sesungguhnya Allah Maha Mengetahui segala sesuatu.<?php break;}
case 33:{?>Bagi tiap-tiap harta peninggalan dari harta yang ditinggalkan ibu bapak dan karib kerabat, Kami jadikan pewaris-pewarisnya. Dan (jika ada) orang-orang yang kamu telah bersumpah setia dengan mereka, maka berilah kepada mereka bahagiannya. Sesungguhnya Allah menyaksikan segala sesuatu.<?php break;}
case 34:{?>Kaum laki-laki itu adalah pemimpin bagi kaum wanita, oleh karena Allah telah melebihkan sebahagian mereka (laki-laki) atas sebahagian yang lain (wanita), dan karena mereka (laki-laki) telah menafkahkan sebagian dari harta mereka. Sebab itu maka wanita yang saleh, ialah yang taat kepada Allah lagi memelihara diri ketika suaminya tidak ada, oleh karena Allah telah memelihara (mereka). Wanita-wanita yang kamu khawatirkan nusyuznya, maka nasihatilah mereka dan pisahkanlah mereka di tempat tidur mereka, dan pukullah mereka. Kemudian jika mereka menaatimu, maka janganlah kamu mencari-cari jalan untuk menyusahkannya. Sesungguhnya Allah Maha Tinggi lagi Maha Besar.<?php break;}
case 35:{?>Dan jika kamu khawatirkan ada persengketaan antara keduanya, maka kirimlah seorang hakam dari keluarga laki-laki dan seorang hakam dari keluarga perempuan. Jika kedua orang hakam itu bermaksud mengadakan perbaikan, niscaya Allah memberi taufik kepada suami-istri itu. Sesungguhnya Allah Maha Mengetahui lagi Maha Mengenal.<?php break;}
case 36:{?>Sembahlah Allah dan janganlah kamu mempersekutukan-Nya dengan sesuatu pun. Dan berbuat baiklah kepada dua orang ibu-bapa, karib-kerabat, anak-anak yatim, orang-orang miskin, tetangga yang dekat dan tetangga yang jauh, teman sejawat, ibnu sabil dan hamba sahayamu. Sesungguhnya Allah tidak menyukai orang-orang yang sombong dan membangga-banggakan diri,<?php break;}
case 37:{?>(yaitu) orang-orang yang kikir, dan menyuruh orang lain berbuat kikir dan menyembunyikan karunia Allah yang telah diberikan-Nya kepada mereka. Dan kami telah menyediakan untuk orang-orang kafir siksa yang menghinakan.<?php break;}
case 38:{?>Dan (juga) orang-orang yang menafkahkan harta-harta mereka karena riya kepada manusia, dan orang-orang yang tidak beriman kepada Allah dan kepada hari kemudian. Barang siapa yang mengambil setan itu menjadi temannya, maka setan itu adalah teman yang seburuk-buruknya.<?php break;}
case 39:{?>Apakah kemudaratannya bagi mereka, kalau mereka beriman kepada Allah dan hari kemudian dan menafkahkan sebahagian rezeki yang telah diberikan Allah kepada mereka? Dan adalah Allah Maha Mengetahui keadaan mereka.<?php break;}
case 40:{?>Sesungguhnya Allah tidak menganiaya seseorang walaupun sebesar zarrah, dan jika ada kebajikan sebesar zarrah, niscaya Allah akan melipat gandakannya dan memberikan dari sisi-Nya pahala yang besar.<?php break;}
case 41:{?>Maka bagaimanakah (halnya orang kafir nanti), apabila Kami mendatangkan seseorang saksi (rasul) dari tiap-tiap umat dan Kami mendatangkan kamu (Muhammad) sebagai saksi atas mereka itu (sebagai umatmu).<?php break;}
case 42:{?>Di hari itu orang-orang kafir dan orang-orang yang mendurhakai rasul, ingin supaya mereka disama-ratakan dengan tanah, dan mereka tidak dapat menyembunyikan (dari Allah) sesuatu kejadianpun.<?php break;}
case 43:{?>Hai orang-orang yang beriman, janganlah kamu salat, sedang kamu dalam keadaan mabuk, sehingga kamu mengerti apa yang kamu ucapkan, (jangan pula hampiri mesjid) sedang kamu dalam keadaan junub, terkecuali sekedar berlalu saja, hingga kamu mandi. Dan jika kamu sakit atau sedang dalam musafir atau kembali dari tempat buang air atau kamu telah menyentuh perempuan, kemudian kamu tidak mendapat air, maka bertayamumlah kamu dengan tanah yang baik (suci); sapulah mukamu dan tanganmu. Sesungguhnya Allah Maha Pemaaf lagi Maha Pengampun.<?php break;}
case 44:{?>Apakah kamu tidak melihat orang-orang yang telah diberi bahagian dari Al Kitab (Taurat)? Mereka membeli (memilih) kesesatan (dengan petunjuk) dan mereka bermaksud supaya kamu tersesat (menyimpang) dari jalan (yang benar).<?php break;}
case 45:{?>Dan Allah lebih mengetahui (daripada kamu) tentang musuh-musuhmu. Dan cukuplah Allah menjadi Pelindung (bagimu). Dan cukuplah Allah menjadi Penolong (bagimu).<?php break;}
case 46:{?>Yaitu orang-orang Yahudi, mereka merubah perkataan dari tempat-tempatnya. Mereka berkata: &quot;Kami mendengar&quot;, tetapi kami tidak mau menurutinya. Dan (mereka mengatakan pula): &quot;Dengarlah&quot; sedang kamu sebenarnya tidak mendengar apa-apa. Dan (mereka mengatakan): &quot;Raa'ina&quot;, dengan memutar-mutar lidahnya dan mencela agama. Sekiranya mereka mengatakan: &quot;Kami mendengar dan patuh, dan dengarlah, dan perhatikanlah kami&quot;, tentulah itu lebih baik bagi mereka dan lebih tepat, akan tetapi Allah mengutuk mereka, karena kekafiran mereka. Mereka tidak beriman kecuali iman yang sangat tipis.<?php break;}
case 47:{?>Hai orang-orang yang telah diberi Al Kitab, berimanlah kamu kepada apa yang telah Kami turunkan (Al Qur'an) yang membenarkan Kitab yang ada pada kamu sebelum Kami merobah muka (mu), lalu Kami putarkan ke belakang atau Kami kutuk mereka sebagaimana Kami telah mengutuk orang-orang (yang berbuat ma'siat) pada hari Sabtu. Dan ketetapan Allah pasti berlaku.<?php break;}
case 48:{?>Sesungguhnya Allah tidak akan mengampuni dosa syirik, dan Dia mengampuni segala dosa yang selain dari (syirik) itu, bagi siapa yang dikehendaki-Nya. Barang siapa yang mempersekutukan Allah, maka sungguh ia telah berbuat dosa yang besar.<?php break;}
case 49:{?>Apakah kamu tidak memperhatikan orang yang menganggap dirinya bersih? Sebenarnya Allah membersihkan siapa yang dikehendaki-Nya dan mereka tidak dianiaya sedikit pun.<?php break;}
case 50:{?>Perhatikanlah, betapakah mereka mengada-adakan dusta terhadap Allah? Dan cukuplah perbuatan itu menjadi dosa yang nyata (bagi mereka).<?php break;}
case 51:{?>Apakah kamu tidak memperhatikan orang-orang yang diberi bahagian dari Al Kitab? Mereka percaya kepada jibt dan thaghut, dan mengatakan kepada orang-orang kafir (musyrik Mekah), bahwa mereka itu lebih benar jalannya dari orang-orang yang beriman.<?php break;}
case 52:{?>Mereka itulah orang yang dikutuki Allah. Barang siapa yang dikutuki Allah, niscaya kamu sekali-kali tidak akan memperoleh penolong baginya.<?php break;}
case 53:{?>Ataukah ada bagi mereka bahagian dari kerajaan (kekuasaan)? Kendati pun ada, mereka tidak akan memberikan sedikit pun (kebajikan) kepada manusia,<?php break;}
case 54:{?>ataukah mereka dengki kepada manusia (Muhammad) lantaran karunia yang Allah telah berikan kepadanya? sesungguhnya Kami telah memberikan Kitab dan Hikmah kepada keluarga Ibrahim, dan Kami telah memberikan kepadanya kerajaan yang besar.<?php break;}
case 55:{?>Maka di antara mereka (orang-orang yang dengki itu), ada orang-orang yang beriman kepadanya, dan di antara mereka ada orang-orang yang menghalangi (manusia) beriman kepadanya. Dan cukuplah (bagi mereka) Jahanam yang menyala-nyala apinya.<?php break;}
case 56:{?>Sesungguhnya orang-orang yang kafir kepada ayat-ayat Kami, kelak akan Kami masukkan mereka ke dalam neraka. Setiap kali kulit mereka hangus, Kami ganti kulit mereka dengan kulit yang lain, supaya mereka merasakan azab. Sesungguhnya Allah Maha Perkasa lagi Maha Bijaksana.<?php break;}
case 57:{?>Dan orang-orang yang beriman dan mengerjakan amal-amal saleh, kelak akan Kami masukkan mereka ke dalam surga yang di dalamnya mengalir sungai-sungai; kekal mereka di dalamnya; mereka di dalamnya mempunyai istri-istri yang suci, dan Kami masukkan mereka ke tempat yang teduh lagi nyaman.<?php break;}
case 58:{?>Sesungguhnya Allah menyuruh kamu menyampaikan amanat kepada yang berhak menerimanya, dan (menyuruh kamu) apabila menetapkan hukum di antara manusia supaya kamu menetapkan dengan adil. Sesungguhnya Allah memberi pengajaran yang sebaik-baiknya kepadamu. Sesungguhnya Allah adalah Maha Mendengar lagi Maha Melihat.<?php break;}
case 59:{?>Hai orang-orang yang beriman, taatilah Allah dan taatilah Rasul (Nya), dan ulil amri di antara kamu. Kemudian jika kamu berlainan pendapat tentang sesuatu, maka kembalikanlah ia kepada Allah (Al Qur'an) dan Rasul (sunnahnya), jika kamu benar-benar beriman kepada Allah dan hari kemudian. Yang demikian itu lebih utama (bagimu) dan lebih baik akibatnya.<?php break;}
case 60:{?>Apakah kamu tidak memperhatikan orang-orang yang mengaku dirinya telah beriman kepada apa yang diturunkan kepadamu dan kepada apa yang diturunkan sebelum kamu? Mereka hendak berhakim kepada thaghut, padahal mereka telah diperintah mengingkari thaghut itu. Dan syaitan bermaksud menyesatkan mereka (dengan) penyesatan yang sejauh-jauhnya.<?php break;}
case 61:{?>Apabila dikatakan kepada mereka: &quot;Marilah kamu (tunduk) kepada hukum yang Allah telah turunkan dan kepada hukum Rasul&quot;, niscaya kamu lihat orang-orang munafik menghalangi (manusia) dengan sekuat-kuatnya dari (mendekati) kamu.<?php break;}
case 62:{?>Maka bagaimanakah halnya apabila mereka (orang-orang munafik) ditimpa sesuatu musibah disebabkan perbuatan tangan mereka sendiri, kemudian mereka datang kepadamu sambil bersumpah: &quot;Demi Allah, kami sekali-kali tidak menghendaki selain penyelesaian yang baik dan perdamaian yang sempurna&quot;.<?php break;}
case 63:{?>Mereka itu adalah orang-orang yang Allah mengetahui apa yang di dalam hati mereka. Karena itu berpalinglah kamu dari mereka, dan berilah mereka pelajaran, dan katakanlah kepada mereka perkataan yang berbekas pada jiwa mereka.<?php break;}
case 64:{?>Dan kami tidak mengutus seseorang rasul, melainkan untuk ditaati dengan seizin Allah. Sesungguhnya jika mereka ketika menganiaya dirinya datang kepadamu, lalu memohon ampun kepada Allah, dan Rasul pun memohonkan ampun untuk mereka, tentulah mereka mendapati Allah Maha Penerima tobat lagi Maha Penyayang.<?php break;}
case 65:{?>Maka demi Tuhanmu, mereka (pada hakekatnya) tidak beriman hingga mereka menjadikan kamu hakim dalam perkara yang mereka perselisihkan, kemudian mereka tidak merasa keberatan dalam hati mereka terhadap putusan yang kamu berikan, dan mereka menerima dengan sepenuhnya.<?php break;}
case 66:{?>Dan sesungguhnya kalau Kami perintahkan kepada mereka: &quot;Bunuhlah dirimu atau keluarlah kamu dari kampungmu&quot;, niscaya mereka tidak akan melakukannya, kecuali sebagian kecil dari mereka. Dan sesungguhnya kalau mereka melaksanakan pelajaran yang diberikan kepada mereka, tentulah hal yang demikian itu lebih baik bagi mereka dan lebih menguatkan (iman mereka),<?php break;}
case 67:{?>dan kalau demikian, pasti Kami berikan kepada mereka pahala yang besar dari sisi Kami,<?php break;}
case 68:{?>dan pasti Kami tunjuki mereka kepada jalan yang lurus.<?php break;}
case 69:{?>Dan barang siapa yang menaati Allah dan Rasul (Nya), mereka itu akan bersama-sama dengan orang-orang yang dianugerahi nikmat oleh Allah, yaitu: Nabi-nabi, para shiddiiqiin, orang-orang yang mati syahid dan orang-orang saleh. Dan mereka itulah teman yang sebaik-baiknya.<?php break;}
case 70:{?>Yang demikian itu adalah karunia dari Allah, dan Allah cukup mengetahui.<?php break;}
case 71:{?>Hai orang-orang yang beriman, bersiap siagalah kamu, dan majulah (ke medan pertempuran) berkelompok-kelompok, atau majulah bersama-sama!<?php break;}
case 72:{?>Dan sesungguhnya di antara kamu ada orang yang sangat berlambat-lambat (ke medan pertempuran). Maka jika kamu ditimpa musibah ia berkata: &quot;Sesungguhnya Tuhan telah menganugerahkan nikmat kepada saya karena saya tidak ikut berperang bersama mereka&quot;.<?php break;}
case 73:{?>Dan sungguh jika kamu beroleh karunia (kemenangan) dari Allah, tentulah dia mengatakan seolah-olah belum pernah ada hubungan kasih sayang antara kamu dengan dia: &quot;Wahai, kiranya saya ada bersama-sama mereka, tentu saya mendapat kemenangan yang besar (pula)&quot;.<?php break;}
case 74:{?>Karena itu hendaklah orang-orang yang menukar kehidupan dunia dengan kehidupan akhirat berperang di jalan Allah. Barang siapa yang berperang di jalan Allah, lalu gugur atau memperoleh kemenangan maka kelak akan Kami berikan kepadanya pahala yang besar.<?php break;}
case 75:{?>Mengapa kamu tidak mau berperang di jalan Allah dan (membela) orang-orang yang lemah baik laki-laki, wanita-wanita maupun anak-anak yang semuanya berdoa: &quot;Ya Tuhan kami, keluarkanlah kami dari negeri ini (Mekah) yang lalim penduduknya dan berilah kami pelindung dari sisi Engkau, dan berilah kami penolong dari sisi Engkau!&quot;.<?php break;}
case 76:{?>Orang-orang yang beriman berperang di jalan Allah, dan orang-orang yang kafir berperang di jalan thaghut, sebab itu perangilah kawan-kawan setan itu, karena sesungguhnya tipu daya setan itu adalah lemah.<?php break;}
case 77:{?>Tidakkah kamu perhatikan orang-orang yang dikatakan kepada mereka: &quot;Tahanlah tanganmu (dari berperang), dirikanlah sembahyang dan tunaikanlah zakat!&quot; Setelah diwajibkan kepada mereka berperang, tiba-tiba sebahagian dari mereka (golongan munafik) takut kepada manusia (musuh), seperti takutnya kepada Allah, bahkan lebih sangat dari itu takutnya. Mereka berkata: &quot;Ya Tuhan kami, mengapa Engkau wajibkan berperang kepada kami? Mengapa tidak Engkau tangguhkan (kewajiban berperang) kepada kami beberapa waktu lagi?&quot; Katakanlah: &quot;Kesenangan di dunia ini hanya sebentar dan akhirat itu lebih baik untuk orang-orang yang bertakwa dan kamu tidak akan dianiaya sedikit pun.<?php break;}
case 78:{?>Di mana saja kamu berada, kematian akan mendapatkan kamu, kendati pun kamu di dalam benteng yang tinggi lagi kokoh, dan jika mereka memperoleh kebaikan, mereka mengatakan: &quot;Ini adalah dari sisi Allah&quot;, dan kalau mereka ditimpa sesuatu bencana mereka mengatakan: &quot;Ini (datangnya) dari sisi kamu (Muhammad)&quot;. Katakanlah: &quot;Semuanya (datang) dari sisi Allah&quot;. Maka mengapa orang-orang itu (orang munafik) hampir-hampir tidak memahami pembicaraan sedikit pun?<?php break;}
case 79:{?>Apa saja nikmat yang kamu peroleh adalah dari Allah, dan apa saja bencana yang menimpamu, maka dari (kesalahan) dirimu sendiri. Kami mengutusmu menjadi Rasul kepada segenap manusia. Dan cukuplah Allah menjadi saksi.<?php break;}
case 80:{?>Barang siapa yang menaati Rasul itu, sesungguhnya ia telah menaati Allah. Dan barang siapa yang berpaling (dari ketaatan itu), maka Kami tidak mengutusmu untuk menjadi pemelihara bagi mereka.<?php break;}
case 81:{?>Dan mereka (orang-orang munafik) mengatakan: &quot;(Kewajiban kami hanyalah) taat&quot;. Tetapi apabila mereka telah pergi dari sisimu, sebahagian dari mereka mengatur siasat di malam hari (mengambil keputusan) lain dari yang telah mereka katakan tadi. Allah menulis siasat yang mereka atur di malam hari itu, maka berpalinglah kamu dari mereka dan tawakallah kepada Allah. Cukuplah Allah menjadi Pelindung.<?php break;}
case 82:{?>Maka apakah mereka tidak memperhatikan Al Qur'an? Kalau kiranya Al Qur'an itu bukan dari sisi Allah, tentulah mereka mendapat pertentangan yang banyak di dalamnya.<?php break;}
case 83:{?>Dan apabila datang kepada mereka suatu berita tentang keamanan atau pun ketakutan, mereka lalu menyiarkannya. Dan kalau mereka menyerahkannya kepada Rasul dan Ulil Amri di antara mereka, tentulah orang-orang yang ingin mengetahui kebenarannya (akan dapat) mengetahuinya dari mereka (Rasul dan Ulil Amri). Kalau tidaklah karena karunia dan rahmat Allah kepada kamu, tentulah kamu mengikut setan, kecuali sebahagian kecil saja (di antaramu).<?php break;}
case 84:{?>Maka berperanglah kamu pada jalan Allah, tidaklah kamu dibebani melainkan dengan kewajiban kamu sendiri. Kobarkanlah semangat para mukmin (untuk berperang). Mudah-mudahan Allah menolak serangan orang-orang yang kafir itu. Allah amat besar kekuatan dan amat keras siksaan (Nya).<?php break;}
case 85:{?>Barang siapa yang memberikan syafa'at yang baik, niscaya ia akan memperoleh bahagian (pahala) daripadanya. Dan barang siapa yang memberi syafa'at yang buruk, niscaya ia akan memikul bahagian (dosa) daripadanya. Allah Maha Kuasa atas segala sesuatu.<?php break;}
case 86:{?>Apabila kamu dihormati dengan suatu penghormatan, maka balaslah penghormatan itu dengan yang lebih baik, atau balaslah (dengan yang serupa). Sesungguhnya Allah memperhitungkan segala sesuatu.<?php break;}
case 87:{?>Allah, tidak ada Tuhan (yang berhak disembah) selain Dia. Sesungguhnya Dia akan mengumpulkan kamu di hari kiamat, yang tidak ada keraguan terjadinya. Dan siapakah orang yang lebih benar perkataan (nya) daripada Allah.<?php break;}
case 88:{?>Maka mengapa kamu (terpecah) menjadi dua golongan dalam (menghadapi) orang-orang munafik, padahal Allah telah membalikkan mereka kepada kekafiran, disebabkan usaha mereka sendiri? Apakah kamu bermaksud memberi petunjuk kepada orang-orang yang telah disesatkan Allah? Barang siapa yang disesatkan Allah, sekali-kali kamu tidak mendapatkan jalan (untuk memberi petunjuk) kepadanya.<?php break;}
case 89:{?>Mereka ingin supaya kamu menjadi kafir sebagaimana mereka telah menjadi kafir, lalu kamu menjadi sama (dengan mereka). Maka janganlah kamu jadikan di antara mereka penolong-penolong (mu), hingga mereka berhijrah pada jalan Allah. Maka jika mereka berpaling, tawan dan bunuhlah mereka di mana saja kamu menemuinya, dan janganlah kamu ambil seorang pun di antara mereka pelindung, dan jangan (pula) menjadi penolong,<?php break;}
case 90:{?>kecuali orang-orang yang meminta perlindungan kepada sesuatu kaum, yang antara kamu dan kaum itu telah ada perjanjian (damai) atau orang-orang yang datang kepada kamu sedang hati mereka merasa keberatan untuk memerangi kamu dan memerangi kaumnya. Kalau Allah menghendaki, tentu Dia memberi kekuasaan kepada mereka terhadap kamu, lalu pastilah mereka memerangimu. Tetapi jika mereka membiarkan kamu, dan tidak memerangi kamu serta mengemukakan perdamaian kepadamu maka Allah tidak memberi jalan bagimu (untuk menawan dan membunuh) mereka.<?php break;}
case 91:{?>Kelak kamu akan dapati (golongan-golongan) yang lain, yang bermaksud supaya mereka aman daripada kamu dan aman (pula) dari kaumnya. Setiap mereka diajak kembali kepada fitnah (syirik), mereka pun terjun ke dalamnya. Karena itu jika mereka tidak membiarkan kamu dan (tidak) mau mengemukakan perdamaian kepadamu, serta (tidak) menahan tangan mereka (dari memerangimu), maka tawanlah mereka dan bunuhlah mereka di mana saja kamu menemui mereka, dan merekalah orang-orang yang Kami berikan kepadamu alasan yang nyata (untuk menawan dan membunuh) mereka.<?php break;}
case 92:{?>Dan tidak layak bagi seorang mukmin membunuh seorang mukmin (yang lain), kecuali karena tersalah (tidak sengaja), dan barang siapa membunuh seorang mukmin karena tersalah (hendaklah) ia memerdekakan seorang hamba sahaya yang beriman serta membayar diat yang diserahkan kepada keluarganya (si terbunuh itu), kecuali jika mereka (keluarga terbunuh) bersedekah. Jika ia (si terbunuh) dari kaum yang memusuhimu, padahal ia mukmin, maka (hendaklah si pembunuh) memerdekakan hamba-sahaya yang mukmin. Dan jika ia (si terbunuh) dari kaum (kafir) yang ada perjanjian (damai) antara mereka dengan kamu, maka (hendaklah si pembunuh) membayar diat yang diserahkan kepada keluarganya (si terbunuh) serta memerdekakan hamba sahaya yang mukmin. Barang siapa yang tidak memperolehnya, maka hendaklah ia (si pembunuh) berpuasa dua bulan berturut-turut sebagai cara tobat kepada Allah. Dan adalah Allah Maha Mengetahui lagi Maha Bijaksana.<?php break;}
case 93:{?>Dan barang siapa yang membunuh seorang mukmin dengan sengaja, maka balasannya ialah Jahanam, kekal ia di dalamnya dan Allah murka kepadanya, dan mengutukinya serta menyediakan azab yang besar baginya.<?php break;}
case 94:{?>Hai orang-orang yang beriman, apabila kamu pergi (berperang) di jalan Allah, maka telitilah dan janganlah kamu mengatakan kepada orang yang mengucapkan &quot;salam&quot; kepadamu: &quot;Kamu bukan seorang mukmin&quot; (lalu kamu membunuhnya), dengan maksud mencari harta benda kehidupan di dunia, karena di sisi Allah ada harta yang banyak. Begitu jugalah keadaan kamu dahulu, lalu Allah menganugerahkan nikmat-Nya atas kamu, maka telitilah. Sesungguhnya Allah Maha Mengetahui apa yang kamu kerjakan.<?php break;}
case 95:{?>Tidaklah sama antara mukmin yang duduk (yang tidak turut berperang) yang tidak mempunyai uzur dengan orang-orang yang berjihad di jalan Allah dengan harta mereka dan jiwanya. Allah melebihkan orang-orang yang berjihad dengan harta dan jiwanya atas orang-orang yang duduk satu derajat. Kepada masing-masing mereka Allah menjanjikan pahala yang baik (surga) dan Allah melebihkan orang-orang yang berjihad atas orang yang duduk dengan pahala yang besar,<?php break;}
case 96:{?>(yaitu) beberapa derajat daripada-Nya, ampunan serta rahmat. Dan adalah Allah Maha Pengampun lagi Maha Penyayang.<?php break;}
case 97:{?>Sesungguhnya orang-orang yang diwafatkan malaikat dalam keadaan menganiaya diri sendiri, (kepada mereka) malaikat bertanya: &quot;Dalam keadaan bagaimana kamu ini?&quot;. Mereka menjawab: &quot;Adalah kami orang-orang yang tertindas di negeri (Mekah)&quot;. Para malaikat berkata: &quot;Bukankah bumi Allah itu luas, sehingga kamu dapat berhijrah di bumi itu?&quot;. Orang-orang itu tempatnya neraka Jahanam, dan Jahanam itu seburuk-buruk tempat kembali,<?php break;}
case 98:{?>kecuali mereka yang tertindas baik laki-laki atau wanita atau pun anak-anak yang tidak mampu berdaya upaya dan tidak mengetahui jalan (untuk hijrah),<?php break;}
case 99:{?>mereka itu, mudah-mudahan Allah memaafkannya. Dan adalah Allah Maha Pemaaf lagi Maha Pengampun.<?php break;}
case 100:{?>Barang siapa berhijrah di jalan Allah, niscaya mereka mendapati di muka bumi ini tempat hijrah yang luas dan rezeki yang banyak. Barang siapa keluar dari rumahnya dengan maksud berhijrah kepada Allah dan Rasul-Nya, kemudian kematian menimpanya (sebelum sampai ke tempat yang dituju), maka sungguh telah tetap pahalanya di sisi Allah. Dan adalah Allah Maha Pengampun lagi Maha Penyayang.<?php break;}
case 101:{?>Dan apabila kamu bepergian di muka bumi, maka tidaklah mengapa kamu menqashar sembahyang(mu), jika kamu takut diserang orang-orang kafir. Sesungguhnya orang-orang kafir itu adalah musuh yang nyata bagimu.<?php break;}
case 102:{?>Dan apabila kamu berada di tengah-tengah mereka (sahabatmu) lalu kamu hendak mendirikan salat bersama-sama mereka, maka hendaklah segolongan dari mereka berdiri (salat) besertamu dan menyandang senjata, kemudian apabila mereka (yang salat besertamu) sujud (telah menyempurnakan serakaat), maka hendaklah mereka pindah dari belakangmu (untuk menghadapi musuh) dan hendaklah datang golongan yang kedua yang belum bersembahyang, lalu bersembahyanglah mereka denganmu, dan hendaklah mereka bersiap siaga dan menyandang senjata. Orang-orang kafir ingin supaya kamu lengah terhadap senjatamu dan harta bendamu, lalu mereka menyerbu kamu dengan sekaligus. Dan tidak ada dosa atasmu meletakkan senjata-senjatamu, jika kamu mendapat sesuatu kesusahan karena hujan atau karena kamu memang sakit; dan siap-siagalah kamu. Sesungguhnya Allah telah menyediakan azab yang menghinakan bagi orang-orang kafir itu.<?php break;}
case 103:{?>Maka apabila kamu telah menyelesaikan salat (mu), ingatlah Allah di waktu berdiri, di waktu duduk dan di waktu berbaring. Kemudian apabila kamu telah merasa aman, maka dirikanlah salat itu (sebagaimana biasa). Sesungguhnya salat itu adalah kewajiban yang ditentukan waktunya atas orang-orang yang beriman.<?php break;}
case 104:{?>Janganlah kamu berhati lemah dalam mengejar mereka (musuhmu). Jika kamu menderita kesakitan, maka sesungguhnya mereka pun menderita kesakitan (pula), sebagaimana kamu menderitanya, sedang kamu mengharap dari Allah apa yang tidak mereka harapkan. Dan adalah Allah Maha Mengetahui lagi Maha Bijaksana.<?php break;}
case 105:{?>Sesungguhnya Kami telah menurunkan Kitab kepadamu dengan membawa kebenaran, supaya kamu mengadili antara manusia dengan apa yang telah Allah wahyukan kepadamu, dan janganlah kamu menjadi penantang (orang yang tidak bersalah), karena (membela) orang-orang yang khianat,<?php break;}
case 106:{?>dan mohonlah ampun kepada Allah. Sesungguhnya Allah Maha Pengampun lagi Maha Penyayang.<?php break;}
case 107:{?>Dan janganlah kamu berdebat (untuk membela) orang-orang yang mengkhianati dirinya. Sesungguhnya Allah tidak menyukai orang-orang yang selalu berkhianat lagi bergelimang dosa,<?php break;}
case 108:{?>mereka bersembunyi dari manusia, tetapi mereka tidak bersembunyi dari Allah, padahal Allah beserta mereka, ketika pada suatu malam mereka menetapkan keputusan rahasia yang Allah tidak ridai. Dan adalah Allah Maha Meliputi (ilmu-Nya) terhadap apa yang mereka kerjakan.<?php break;}
case 109:{?>Beginilah kamu, kamu sekalian adalah orang-orang yang berdebat untuk (membela) mereka dalam kehidupan dunia ini. Maka siapakah yang akan mendebat Allah untuk (membela) mereka pada hari kiamat? Atau siapakah yang jadi pelindung mereka (terhadap siksa Allah)?<?php break;}
case 110:{?>Dan barang siapa yang mengerjakan kejahatan dan menganiaya dirinya, kemudian ia mohon ampun kepada Allah, niscaya ia mendapati Allah Maha Pengampun lagi Maha Penyayang.<?php break;}
case 111:{?>Barang siapa yang mengerjakan dosa, maka sesungguhnya ia mengerjakannya untuk (kemudaratan) dirinya sendiri. Dan Allah Maha Mengetahui lagi Maha Bijaksana.<?php break;}
case 112:{?>Dan barang siapa yang mengerjakan kesalahan atau dosa, kemudian dituduhkannya kepada orang yang tidak bersalah, maka sesungguhnya ia telah berbuat suatu kebohongan dan dosa yang nyata.<?php break;}
case 113:{?>Sekiranya bukan karena karunia Allah dan rahmat-Nya kepadamu, tentulah segolongan dari mereka berkeinginan keras untuk menyesatkanmu. Tetapi mereka tidak menyesatkan melainkan dirinya sendiri, dan mereka tidak dapat membahayakanmu sedikit pun kepadamu. Dan (juga karena) Allah telah menurunkan Kitab dan hikmah kepadamu, dan telah mengajarkan kepadamu apa yang belum kamu ketahui. Dan adalah karunia Allah sangat besar atasmu.<?php break;}
case 114:{?>Tidak ada kebaikan pada kebanyakan bisikan bisikan mereka, kecuali bisikan-bisikan dari orang yang menyuruh (manusia) memberi sedekah, atau berbuat makruf, atau mengadakan perdamaian di antara manusia. Dan barang siapa yang berbuat demikian karena mencari keridaan Allah, maka kelak Kami memberi kepadanya pahala yang besar.<?php break;}
case 115:{?>Dan barang siapa yang menentang Rasul sesudah jelas kebenaran baginya, dan mengikuti jalan yang bukan jalan orang-orang mukmin, Kami biarkan ia leluasa terhadap kesesatan yang telah dikuasinya itu dan Kami masukkan ia ke dalam Jahanam, dan Jahanam itu seburuk-buruk tempat kembali.<?php break;}
case 116:{?>Sesungguhnya Allah tidak mengampuni dosa mempersekutukan (sesuatu) dengan Dia, dan Dia mengampuni dosa yang selain dari syirik itu bagi siapa yang dikehendaki-Nya. Barang siapa yang mempersekutukan (sesuatu) dengan Allah, maka sesungguhnya ia telah tersesat sejauh-jauhnya.<?php break;}
case 117:{?>Yang mereka sembah selain Allah itu, tidak lain hanyalah berhala, dan (dengan menyembah berhala itu) mereka tidak lain hanyalah menyembah setan yang durhaka,<?php break;}
case 118:{?>yang dilaknati Allah dan setan itu mengatakan: &quot;Saya benar-benar akan mengambil dari hamba-hamba Engkau bahagian yang sudah ditentukan (untuk saya),<?php break;}
case 119:{?>dan aku benar-benar akan menyesatkan mereka, dan akan membangkitkan angan-angan kosong pada mereka dan akan menyuruh mereka (memotong telinga-telinga binatang ternak), lalu mereka benar-benar memotongnya, dan akan aku suruh mereka (merubah ciptaan Allah), lalu benar-benar mereka merobahnya&quot;. Barang siapa yang menjadikan setan menjadi pelindung selain Allah, maka sesungguhnya ia menderita kerugian yang nyata.<?php break;}
case 120:{?>Setan itu memberikan janji-janji kepada mereka dan membangkitkan angan-angan kosong pada mereka, padahal setan itu tidak menjanjikan kepada mereka selain dari tipuan belaka.<?php break;}
case 121:{?>Mereka itu tempatnya Jahanam dan mereka tidak memperoleh tempat lari daripadanya.<?php break;}
case 122:{?>Orang-orang yang beriman dan mengerjakan amalan saleh, kelak akan Kami masukkan ke dalam surga yang mengalir sungai-sungai di dalamnya, mereka kekal di dalamnya selama-lamanya. Allah telah membuat suatu janji yang benar. Dan siapakah yang lebih benar perkataannya daripada Allah?<?php break;}
case 123:{?>(Pahala dari Allah) itu bukanlah menurut angan-anganmu yang kosong dan tidak (pula) menurut angan-angan Ahli Kitab. Barang siapa yang mengerjakan kejahatan, niscaya akan diberi pembalasan dengan kejahatan itu dan ia tidak mendapat pelindung dan tidak (pula) penolong baginya selain dari Allah.<?php break;}
case 124:{?>Barang siapa yang mengerjakan amal-amal saleh, baik laki-laki maupun wanita sedang ia orang yang beriman, maka mereka itu masuk ke dalam surga dan mereka tidak dianiaya walau sedikit pun.<?php break;}
case 125:{?>Dan siapakah yang lebih baik agamanya daripada orang yang ikhlas menyerahkan dirinya kepada Allah, sedang dia pun mengerjakan kebaikan, dan ia mengikuti agama Ibrahim yang lurus? Dan Allah mengambil Ibrahim menjadi kesayangan-Nya.<?php break;}
case 126:{?>Kepunyaan Allah-lah apa yang di langit dan apa yang di bumi, dan adalah (pengetahuan) Allah Maha Meliputi segala sesuatu.<?php break;}
case 127:{?>Dan mereka minta fatwa kepadamu tentang para wanita. Katakanlah: &quot;Allah memberi fatwa kepadamu tentang mereka, dan apa yang dibacakan kepadamu dalam Al Qur'an (juga memfatwakan) tentang para wanita yatim yang kamu tidak memberikan kepada mereka apa yang ditetapkan untuk mereka, sedang kamu ingin mengawini mereka dan tentang anak-anak yang masih dipandang lemah. Dan (Allah menyuruh kamu) supaya kamu mengurus anak-anak yatim secara adil. Dan kebajikan apa saja yang kamu kerjakan, maka sesungguhnya Allah adalah Maha Mengetahuinya&quot;.<?php break;}
case 128:{?>Dan jika seorang wanita khawatir akan nusyuz atau sikap tidak acuh dari suaminya, maka tidak mengapa bagi keduanya mengadakan perdamaian yang sebenar-benarnya, dan perdamaian itu lebih baik (bagi mereka) walaupun manusia itu menurut tabiatnya kikir, Dan jika kamu bergaul dengan istrimu secara baik dan memelihara dirimu (dari nusyuz dan sikap tak acuh), maka sesungguhnya Allah adalah Maha Mengetahui apa yang kamu kerjakan.<?php break;}
case 129:{?>Dan kamu sekali-kali tidak akan dapat berlaku adil di antara istri- istri (mu), walaupun kamu sangat ingin berbuat demikian, karena itu janganlah kamu terlalu cenderung (kepada yang kamu cintai), sehingga kamu biarkan yang lain terkatung-katung. Dan jika kamu mengadakan perbaikan dan memelihara diri (dari kecurangan), maka sesungguhnya Allah Maha Pengampun lagi Maha Penyayang.<?php break;}
case 130:{?>Jika keduanya bercerai, maka Allah akan memberi kecukupan kepada masing-masing dari limpahan karunia-Nya. Dan adalah Allah Maha Luas (karunia-Nya) lagi Maha Bijaksana.<?php break;}
case 131:{?>Dan kepunyaan Allah-lah apa yang di langit dan yang di bumi, dan sungguh Kami telah memerintahkan kepada orang-orang yang diberi kitab sebelum kamu dan (juga) kepada kamu; bertakwalah kepada Allah. Tetapi jika kamu kafir, maka (ketahuilah), sesungguhnya apa yang di langit dan apa yang di bumi hanyalah kepunyaan Allah dan Allah Maha Kaya lagi Maha Terpuji.<?php break;}
case 132:{?>Dan kepunyaan Allah-lah apa yang di langit dan apa yang di bumi. Cukuplah Allah sebagai Pemelihara.<?php break;}
case 133:{?>Jika Allah menghendaki, niscaya Dia musnahkan kamu wahai manusia, dan Dia datangkan umat yang lain (sebagai penggantimu). Dan adalah Allah Maha Kuasa berbuat demikian.<?php break;}
case 134:{?>Barang siapa yang menghendaki pahala di dunia saja (maka ia merugi), karena di sisi Allah ada pahala dunia dan akhirat. Dan Allah Maha Mendengar lagi Maha Melihat.<?php break;}
case 135:{?>Wahai orang-orang yang beriman, jadilah kamu orang yang benar-benar penegak keadilan, menjadi saksi karena Allah biar pun terhadap dirimu sendiri atau ibu bapa dan kaum kerabatmu. Jika ia kaya atau pun miskin, maka Allah lebih tahu kemaslahatannya. Maka janganlah kamu mengikuti hawa nafsu karena ingin menyimpang dari kebenaran. Dan jika kamu memutar balikkan (kata-kata) atau enggan menjadi saksi, maka sesungguhnya Allah adalah Maha Mengetahui segala apa yang kamu kerjaan.<?php break;}
case 136:{?>Wahai orang-orang yang beriman, tetaplah beriman kepada Allah dan Rasul-Nya dan kepada kitab yang Allah turunkan kepada Rasul-Nya, serta kitab yang Allah turunkan sebelumnya. Barang siapa yang kafir kepada Allah, malaikat-malaikat-Nya, kitab-kitab-Nya, rasul-rasul-Nya dan hari kemudian, maka sesungguhnya orang itu telah sesat sejauh-jauhnya.<?php break;}
case 137:{?>Sesungguhnya orang-orang yang beriman kemudian kafir, kemudian beriman (pula), kemudian kafir lagi, kemudian bertambah kekafirannya, maka sekali-kali Allah tidak akan memberi ampunan kepada mereka, dan tidak (pula) menunjuki mereka kepada jalan yang lurus.<?php break;}
case 138:{?>Kabarkanlah kepada orang-orang munafik bahwa mereka akan mendapat siksaan yang pedih,<?php break;}
case 139:{?>(yaitu) orang-orang yang mengambil orang-orang kafir menjadi teman-teman penolong dengan meninggalkan orang-orang mukmin. Apakah mereka mencari kekuatan di sisi orang kafir itu? Maka sesungguhnya semua kekuatan kepunyaan Allah.<?php break;}
case 140:{?>Dan sungguh Allah telah menurunkan kepada kamu di dalam Al Qur'an bahwa apabila kamu mendengar ayat-ayat Allah diingkari dan diperolok-olokkan (oleh orang-orang kafir), maka janganlah kamu duduk beserta mereka, sehingga mereka memasuki pembicaraan yang lain. Karena sesungguhnya (kalau kamu berbuat demikian), tentulah kamu serupa dengan mereka. Sesungguhnya Allah akan mengumpulkan semua orang-orang munafik dan orang-orang kafir di dalam Jahanam,<?php break;}
case 141:{?>(yaitu) orang-orang yang menunggu-nunggu (peristiwa) yang akan terjadi pada dirimu (hai orang-orang mukmin). Maka jika terjadi bagimu kemenangan dari Allah mereka berkata: &quot;Bukankah kami (turut berperang) beserta kamu?&quot; Dan jika orang-orang kafir mendapat keberuntungan (kemenangan) mereka berkata: &quot;Bukankah kami turut memenangkanmu, dan membela kamu dari orang-orang mukmin?&quot; Maka Allah akan memberi keputusan di antara kamu di hari kiamat dan Allah sekali-kali tidak akan memberi jalan kepada orang-orang kafir untuk memusnahkan orang-orang yang beriman.<?php break;}
case 142:{?>Sesungguhnya orang-orang munafik itu menipu Allah, dan Allah akan membalas tipuan mereka. Dan apabila mereka berdiri untuk salat mereka berdiri dengan malas. Mereka bermaksud riya (dengan salat) di hadapan manusia. Dan tidaklah mereka menyebut Allah kecuali sedikit sekali.<?php break;}
case 143:{?>Mereka dalam keadaan ragu-ragu antara yang demikian (iman atau kafir): tidak masuk kepada golongan ini (orang-orang beriman) dan tidak (pula) kepada golongan itu (orang-orang kafir). Barang siapa yang disesatkan Allah, maka kamu sekali-kali tidak akan mendapat jalan (untuk memberi petunjuk) baginya.<?php break;}
case 144:{?>Hai orang-orang yang beriman, janganlah kamu mengambil orang-orang kafir menjadi wali dengan meninggalkan orang-orang mukmin. Inginkah kamu mengadakan alasan yang nyata bagi Allah (untuk menyiksamu)?<?php break;}
case 145:{?>Sesungguhnya orang-orang munafik itu (ditempatkan) pada tingkatan yang paling bawah dari neraka. Dan kamu sekali-kali tidak akan mendapat seorang penolongpun bagi mereka.<?php break;}
case 146:{?>Kecuali orang-orang yang tobat dan mengadakan perbaikan dan berpegang teguh pada (agama) Allah dan tulus ikhlas (mengerjakan) agama mereka karena Allah. Maka mereka itu adalah bersama-sama orang yang beriman dan kelak Allah akan memberikan kepada orang-orang yang beriman pahala yang besar.<?php break;}
case 147:{?>Mengapa Allah akan menyiksamu, jika kamu bersyukur dan beriman? Dan Allah adalah Maha Mensyukuri lagi Maha Mengetahui.<?php break;}
case 148:{?>Allah tidak menyukai ucapan buruk, (yang diucapkan) dengan terang kecuali oleh orang yang dianiaya. Allah adalah Maha Mendengar lagi Maha Mengetahui.<?php break;}
case 149:{?>Jika kamu menyatakan sesuatu kebaikan atau menyembunyikan atau memaafkan sesuatu kesalahan (orang lain), maka sesungguhnya Allah Maha Pemaaf lagi Maha Kuasa.<?php break;}
case 150:{?>Sesungguhnya orang-orang yang kafir kepada Allah dan rasu-rasul-Nya, dan bermaksud memperbedakan antara (keimanan kepada) Allah dan rasul-rasul-Nya, dengan mengatakan: &quot;Kami beriman kepada yang sebahagian dan kami kafir terhadap sebahagian (yang lain)&quot;, serta bermaksud (dengan perkataan itu) mengambil jalan (tengah) di antara yang demikian (iman atau kafir),<?php break;}
case 151:{?>merekalah orang-orang yang kafir sebenar-benarnya. Kami telah menyediakan untuk orang-orang yang kafir itu siksaan yang menghinakan.<?php break;}
case 152:{?>Orang-orang yang beriman kepada Allah dan para rasul-Nya dan tidak membeda-bedakan seorang pun di antara mereka, kelak Allah akan memberikan kepada mereka pahalanya. Dan adalah Allah Maha Pengampun lagi Maha Penyayang.<?php break;}
case 153:{?>Ahli Kitab meminta kepadamu agar kamu menurunkan kepada mereka sebuah Kitab dari langit. Maka sesungguhnya mereka telah meminta kepada Musa yang lebih besar dari itu. Mereka berkata: &quot;Perlihatkanlah Allah kepada kami dengan nyata&quot;. Maka mereka disambar petir karena kelalimannya, dan mereka menyembah anak sapi, sesudah datang kepada mereka bukti-bukti yang nyata, lalu Kami maafkan (mereka) dari yang demikian. Dan telah Kami berikan kepada Musa keterangan yang nyata.<?php break;}
case 154:{?>Dan telah Kami angkat ke atas (kepala) mereka bukit Thursina untuk (menerima) perjanjian (yang telah Kami ambil dari) mereka. Dan kami perintahkan kepada mereka: &quot;Masukilah pintu gerbang itu sambil bersujud&quot;, dan Kami perintahkan (pula), kepada mereka: &quot;Janganlah kamu melanggar peraturan mengenai hari Sabtu&quot;, dan Kami telah mengambil dari mereka perjanjian yang kokoh.<?php break;}
case 155:{?>Maka (Kami lakukan terhadap mereka beberapa tindakan), disebabkan mereka melanggar perjanjian itu, dan karena kekafiran mereka terhadap keterangan-keterangan Allah dan mereka membunuh nabi-nabi tanpa (alasan) yang benar dan mengatakan: &quot;Hati kami tertutup.&quot; Bahkan, sebenarnya Allah telah mengunci mati hati mereka karena kekafirannya, karena itu mereka tidak beriman kecuali sebahagian kecil dari mereka.<?php break;}
case 156:{?>Dan karena kekafiran mereka (terhadap Isa), dan tuduhan mereka terhadap Maryam dengan kedustaan besar (zina),<?php break;}
case 157:{?>dan karena ucapan mereka: &quot;Sesungguhnya Kami telah membunuh Al Masih, Isa putra Maryam, Rasul Allah&quot;, padahal mereka tidak membunuhnya dan tidak (pula) menyalibnya, tetapi (yang mereka bunuh ialah) orang yang diserupakan dengan 'Isa bagi mereka. Sesungguhnya orang-orang yang berselisih paham tentang (pembunuhan) Isa, benar-benar dalam keragu-raguan tentang yang dibunuh itu. Mereka tidak mempunyai keyakinan tentang siapa yang dibunuh itu, kecuali mengikuti persangkaan belaka, mereka tidak (pula) yakin bahwa yang mereka bunuh itu adalah Isa.<?php break;}
case 158:{?>Tetapi (yang sebenarnya), Allah telah mengangkat Isa kepada-Nya. Dan adalah Allah Maha Perkasa lagi Maha Bijaksana.<?php break;}
case 159:{?>Tidak ada seorang pun dari Ahli Kitab, kecuali akan beriman kepadanya (Isa) sebelum kematiannya. Dan di hari Kiamat nanti Isa itu akan menjadi saksi terhadap mereka.<?php break;}
case 160:{?>Maka disebabkan kelaliman orang-orang Yahudi, Kami haramkan atas mereka (memakan makanan) yang baik-baik (yang dahulunya) dihalalkan bagi mereka, dan karena mereka banyak menghalangi (manusia) dari jalan Allah,<?php break;}
case 161:{?>dan disebabkan mereka memakan riba, padahal sesungguhnya mereka telah dilarang daripadanya, dan karena mereka memakan harta orang dengan jalan yang batil. Kami telah menyediakan untuk orang-orang yang kafir di antara mereka itu siksa yang pedih.<?php break;}
case 162:{?>Tetapi orang-orang yang mendalam ilmunya di antara mereka dan orang-orang mukmin, mereka beriman kepada apa yang telah diturunkan kepadamu (Al Qur'an), dan apa yang telah diturunkan sebelummu dan orang-orang yang mendirikan shalat, menunaikan zakat, dan yang beriman kepada Allah dan hari kemudian. Orang-orang itulah yang akan Kami berikan kepada mereka pahala yang besar.<?php break;}
case 163:{?>Sesungguhnya Kami telah memberikan wahyu kepadamu sebagaimana Kami telah memberikan wahyu kepada Nuh dan nabi-nabi yang kemudiannya, dan Kami telah memberikan wahyu (pula) kepada Ibrahim, Ismail, Ishak, Yakub dan anak cucunya, Isa, Ayub, Yunus, Harun dan Sulaiman. Dan Kami berikan Zabur kepada Daud.<?php break;}
case 164:{?>Dan (kami telah mengutus) rasul-rasul yang sungguh telah Kami kisahkan tentang mereka kepadamu dahulu, dan rasul-rasul yang tidak Kami kisahkan tentang mereka kepadamu. Dan Allah telah berbicara kepada Musa dengan langsung.<?php break;}
case 165:{?>(Mereka kami utus) selaku rasul-rasul pembawa berita gembira dan pemberi peringatan agar supaya tidak ada alasan bagi manusia membantah Allah sesudah diutusnya rasul-rasul itu. Dan adalah Allah Maha Perkasa lagi Maha Bijaksana.<?php break;}
case 166:{?>(Mereka tidak mau mengakui yang diturunkan kepadamu itu), tetapi Allah mengakui Al Qur'an yang diturunkan-Nya kepadamu. Allah menurunkannya dengan ilmu-Nya; dan malaikat-malaikat pun menjadi saksi (pula). Cukuplah Allah yang mengakuinya.<?php break;}
case 167:{?>Sesungguhnya orang-orang yang kafir dan menghalang-halangi (manusia) dari jalan Allah, benar-benar telah sesat sejauh-jauhnya.<?php break;}
case 168:{?>Sesungguhnya orang-orang yang kafir dan melakukan kelaliman, Allah sekali-kali tidak akan mengampuni (dosa) mereka dan tidak (pula) akan menunjukkan jalan kepada mereka,<?php break;}
case 169:{?>kecuali jalan ke neraka Jahanam; mereka kekal di dalamnya selama-lamanya. Dan yang demikian itu adalah mudah bagi Allah.<?php break;}
case 170:{?>Wahai manusia, sesungguhnya telah datang Rasul (Muhammad) itu kepadamu dengan (membawa) kebenaran dari Tuhanmu, maka berimanlah kamu, itulah yang lebih baik bagimu. Dan jika kamu kafir, (maka kekafiran itu tidak merugikan Allah sedikit pun) karena sesungguhnya apa yang di langit dan di bumi itu adalah kepunyaan Allah. Dan adalah Allah Maha Mengetahui lagi Maha Bijaksana.<?php break;}
case 171:{?>Wahai Ahli Kitab, janganlah kamu melampaui batas dalam agamamu, dan janganlah kamu mengatakan terhadap Allah kecuali yang benar. Sesungguhnya Al Masih, Isa putra Maryam itu, adalah utusan Allah dan (yang diciptakan dengan) kalimat-Nya yang disampaikan-Nya kepada Maryam, dan (dengan tiupan) roh dari-Nya. Maka berimanlah kamu kepada Allah dan rasul-rasul-Nya dan janganlah kamu mengatakan: &quot;(Tuhan itu) tiga&quot;, berhentilah (dari ucapan itu). (Itu) lebih baik bagimu. Sesungguhnya Allah Tuhan Yang Maha Esa, Maha Suci Allah dari mempunyai anak, segala yang di langit dan di bumi adalah kepunyaan-Nya. Cukuplah Allah sebagai Pemelihara.<?php break;}
case 172:{?>Al Masih sekali-kali tidak enggan menjadi hamba bagi Allah dan tidak (pula enggan) malaikat-malaikat yang terdekat (kepada Allah). Barang siapa yang enggan dari menyembah-Nya dan menyombongkan diri, nanti Allah akan mengumpulkan mereka semua kepada-Nya.<?php break;}
case 173:{?>Adapun orang-orang yang beriman dan berbuat amal saleh, maka Allah akan menyempurnakan pahala mereka dan menambah untuk mereka sebagian dari karunia-Nya. Adapun orang-orang yang enggan dan menyombongkan diri, maka Allah akan menyiksa mereka dengan siksaan yang pedih, dan mereka tidak akan memperoleh bagi diri mereka, pelindung dan penolong selain daripada Allah.<?php break;}
case 174:{?>Hai manusia, sesungguhnya telah datang kepadamu bukti kebenaran dari Tuhanmu, (Muhammad dengan mukjizatnya) dan telah Kami turunkan kepadamu cahaya yang terang benderang (Al Qur'an).<?php break;}
case 175:{?>Adapun orang-orang yang beriman kepada Allah dan berpegang kepada (agama)-Nya, niscaya Allah akan memasukkan mereka ke dalam rahmat yang besar dari-Nya (surga) dan limpahan karunia-Nya. Dan menunjuki mereka kepada jalan yang lurus (untuk sampai) kepada-Nya.<?php break;}
case 176:{?>Mereka meminta fatwa kepadamu (tentang kalalah). Katakanlah: &quot;Allah memberi fatwa kepadamu tentang kalalah (yaitu): jika seorang meninggal dunia, dan ia tidak mempunyai anak dan mempunyai saudara perempuan, maka bagi saudaranya yang perempuan itu seperdua dari harta yang ditinggalkannya, dan saudaranya yang laki-laki mempusakai (seluruh harta saudara perempuan), jika ia tidak mempunyai anak; tetapi jika saudara perempuan itu dua orang, maka bagi keduanya dua pertiga dari harta yang ditinggalkan oleh yang meninggal. Dan jika mereka (ahli waris itu terdiri dari) saudara-saudara laki dan perempuan, maka bahagian seorang saudara laki-laki sebanyak bahagian dua orang saudara perempuan. Allah menerangkan (hukum ini) kepadamu, supaya kamu tidak sesat. Dan Allah Maha Mengetahui segala sesuatu.<?php break;}
}?>