<?php 
switch($verse){
case 1:{?>Haa Miim.<?php break;}
case 2:{?>Diturunkan Kitab ini (Al Qur'an) dari Allah Yang Maha Perkasa lagi Maha Mengetahui,<?php break;}
case 3:{?>Yang Mengampuni dosa dan Menerima tobat lagi keras hukuman-Nya; Yang mempunyai karunia. Tiada Tuhan (yang berhak disembah) selain Dia. Hanya kepada-Nya lah kembali (semua makhluk).<?php break;}
case 4:{?>Tidak ada yang memperdebatkan tentang ayat-ayat Allah, kecuali orang-orang yang kafir. Karena itu janganlah pulang balik mereka dengan bebas dari suatu kota ke kota yang lain memperdayakan kamu.<?php break;}
case 5:{?>Sebelum mereka, kaum Nuh dan golongan-golongan yang bersekutu sesudah mereka telah mendustakan (rasul) dan tiap-tiap umat telah merencanakan makar terhadap rasul mereka untuk menawannya dan mereka membantah dengan (alasan) yang batil untuk melenyapkan kebenaran dengan yang batil itu; karena itu Aku azab mereka. Maka betapa (pedihnya) azab-Ku?<?php break;}
case 6:{?>Dan demikianlah telah pasti berlaku ketetapan azab Tuhanmu terhadap orang-orang kafir, karena sesungguhnya mereka adalah penghuni neraka.<?php break;}
case 7:{?>(Malaikat-malaikat) yang memikul Arasy dan malaikat yang berada di sekelilingnya bertasbih memuji Tuhannya dan mereka beriman kepada-Nya serta memintakan ampun bagi orang-orang yang beriman (seraya mengucapkan): &quot;Ya Tuhan kami, rahmat dan ilmu Engkau meliputi segala sesuatu, maka berilah ampunan kepada orang-orang yang bertobat dan mengikuti jalan Engkau dan peliharalah mereka dari siksaan neraka yang menyala-nyala,<?php break;}
case 8:{?>ya Tuhan kami, dan masukkanlah mereka ke dalam surga Adn yang telah Engkau janjikan kepada mereka dan orang-orang yang saleh di antara bapak-bapak mereka, dan istri-istri mereka, dan keturunan mereka semua. Sesungguhnya Engkaulah Yang Maha Perkasa lagi Maha Bijaksana,<?php break;}
case 9:{?>dan peliharalah mereka dari (balasan) kejahatan. Dan orang-orang yang Engkau pelihara dari (pembalasan) kejahatan pada hari itu, maka sesungguhnya telah Engkau anugerahkan rahmat kepadanya dan itulah kemenangan yang besar&quot;.<?php break;}
case 10:{?>Sesungguhnya orang-orang yang kafir diserukan kepada mereka (pada hari kiamat): &quot;Sesungguhnya kebencian Allah (kepadamu) lebih besar daripada kebencianmu kepada dirimu sendiri karena kamu diseru untuk beriman lalu kamu kafir&quot;<?php break;}
case 11:{?>Mereka menjawab: &quot;Ya Tuhan kami Engkau telah mematikan kami dua kali dan telah menghidupkan kami dua kali (pula), lalu kami mengakui dosa-dosa kami. Maka adakah sesuatu jalan (bagi kami) untuk keluar (dari neraka)?&quot;<?php break;}
case 12:{?>Yang demikian itu adalah karena kamu kafir apabila Allah saja yang disembah. Dan kamu percaya apabila Allah dipersekutukan, maka putusan (sekarang ini) adalah pada Allah Yang Maha Tinggi lagi Maha Besar.<?php break;}
case 13:{?>Dia-lah yang memperlihatkan kepadamu tanda-tanda (kekuasaan) -Nya dan menurunkan untukmu rezeki dari langit. Dan tiadalah mendapat pelajaran kecuali orang-orang yang kembali (kepada Allah).<?php break;}
case 14:{?>Maka sembahlah Allah dengan memurnikan ibadah kepada-Nya, meskipun orang-orang kafir tidak menyukai (nya).<?php break;}
case 15:{?>(Dialah) Yang Maha Tinggi derajat-Nya, Yang mempunyai Arasy, Yang mengutus Jibril dengan (membawa) perintah-Nya kepada siapa yang dikehendaki-Nya di antara hamba-hamba-Nya, supaya dia memperingatkan (manusia) tentang hari pertemuan (hari kiamat),<?php break;}
case 16:{?>(yaitu) hari (ketika) mereka keluar (dari kubur); tiada suatu pun dari keadaan mereka yang tersembunyi bagi Allah. (Lalu Allah berfirman): &quot;Kepunyaan siapakah kerajaan pada hari ini?&quot; Kepunyaan Allah Yang Maha Esa lagi Maha Mengalahkan.<?php break;}
case 17:{?>Pada hari ini tiap-tiap jiwa diberi balasan dengan apa yang diusahakannya. Tidak ada yang dirugikan pada hari ini. Sesungguhnya Allah amat cepat hisabnya.<?php break;}
case 18:{?>Berilah mereka peringatan dengan hari yang dekat (hari kiamat, yaitu) ketika hati (menyesak) sampai di kerongkongan dengan menahan kesedihan. Orang-orang yang lalim tidak mempunyai teman setia seorang pun dan tidak (pula) mempunyai seorang pemberi syafaat yang diterima syafaatnya.<?php break;}
case 19:{?>Dia mengetahui (pandangan) mata yang khianat dan apa yang disembunyikan oleh hati.<?php break;}
case 20:{?>Dan Allah menghukum dengan keadilan. Dan sembahan-sembahan yang mereka sembah selain Allah tiada dapat menghukum dengan sesuatu apa pun. Sesungguhnya Allah, Dia-lah Yang Maha Mendengar lagi Maha Melihat.<?php break;}
case 21:{?>Dan apakah mereka tidak mengadakan perjalanan di muka bumi, lalu memperhatikan betapa kesudahan orang-orang yang sebelum mereka. Mereka itu adalah lebih hebat kekuatannya daripada mereka dan (lebih banyak) bekas-bekas mereka di muka bumi, maka Allah mengazab mereka disebabkan dosa-dosa mereka. Dan mereka tidak mempunyai seorang pelindung dari azab Allah.<?php break;}
case 22:{?>Yang demikian itu adalah karena telah datang kepada mereka rasul-rasul mereka dengan membawa bukti-bukti yang nyata lalu mereka kafir; maka Allah mengazab mereka. Sesungguhnya Dia Maha Kuat lagi Maha Keras hukuman-Nya.<?php break;}
case 23:{?>Dan Sesungguhnya telah Kami utus Musa dengan membawa ayat-ayat Kami dan keterangan yang nyata,<?php break;}
case 24:{?>kepada Firaun, Haman dan Qarun; maka mereka berkata: &quot; (Ia) adalah seorang ahli sihir yang pendusta&quot;.<?php break;}
case 25:{?>Maka tatkala Musa datang kepada mereka membawa kebenaran dari sisi Kami mereka berkata: &quot;Bunuhlah anak-anak orang-orang yang beriman bersama dengan dia dan biarkanlah hidup wanita-wanita mereka&quot;. Dan tipu daya orang-orang kafir itu tak lain hanyalah sia-sia (belaka).<?php break;}
case 26:{?>Dan berkata Firaun (kepada pembesar-pembesarnya): &quot;Biarkanlah aku membunuh Musa dan hendaklah ia memohon kepada Tuhannya, karena sesungguhnya aku khawatir dia akan menukar agamamu atau menimbulkan kerusakan di muka bumi&quot;.<?php break;}
case 27:{?>Dan Musa berkata: &quot;Sesungguhnya aku berlindung kepada Tuhanku dan Tuhanmu dari setiap orang yang menyombongkan diri yang tidak beriman kepada hari berhisab&quot;.<?php break;}
case 28:{?>Dan seorang laki-laki yang beriman di antara pengikut-pengikut Firaun yang menyembunyikan imannya berkata: &quot;Apakah kamu akan membunuh seorang laki-laki karena dia menyatakan: &quot;Tuhanku ialah Allah, padahal dia telah datang kepadamu dengan membawa keterangan-keterangan dari Tuhanmu. Dan jika ia seorang pendusta maka dialah yang menanggung (dosa) dustanya itu; dan jika ia seorang yang benar niscaya sebagian (bencana) yang diancamkannya kepadamu akan menimpamu&quot;. Sesungguhnya Allah tidak menunjuki orang-orang yang melampaui batas lagi pendusta.<?php break;}
case 29:{?>(Musa berkata): &quot;Hai kaumku, untukmulah kerajaan pada hari ini dengan berkuasa di muka bumi. Siapakah yang akan menolong kita dari azab Allah jika azab itu menimpa kita!&quot; Firaun berkata: &quot;Aku tidak mengemukakan kepadamu, melainkan apa yang aku pandang baik; dan aku tiada menunjukkan kepadamu selain jalan yang benar&quot;.<?php break;}
case 30:{?>Dan orang yang beriman itu berkata: &quot;Hai kaumku, sesungguhnya aku khawatir kamu akan ditimpa (bencana) seperti peristiwa kehancuran golongan yang bersekutu.<?php break;}
case 31:{?>(Yakni) seperti keadaan kaum Nuh, Ad, Tsamud dan orang-orang yang datang sesudah mereka. Dan Allah tidak menghendaki berbuat kelaliman terhadap hamba-hamba-Nya.<?php break;}
case 32:{?>Hai kaumku, sesungguhnya aku khawatir terhadapmu akan siksaan hari panggil-memanggil,<?php break;}
case 33:{?>(yaitu) hari (ketika) kamu (lari) berpaling ke belakang, tidak ada bagimu seorang pun yang menyelamatkan kamu dari (azab) Allah, dan siapa yang disesatkan Allah, niscaya tidak ada baginya seorang pun yang akan memberi petunjuk.<?php break;}
case 34:{?>Dan sesungguhnya telah datang Yusuf kepadamu dengan membawa keterangan-keterangan, tetapi kamu senantiasa dalam keraguan tentang apa yang dibawanya kepadamu, hingga ketika dia meninggal, kamu berkata: &quot;Allah tidak akan mengirim seorang (rasul pun) sesudahnya&quot;. Demikianlah Allah menyesatkan orang-orang yang melampaui batas dan ragu-ragu.<?php break;}
case 35:{?>(Yaitu) orang-orang yang memperdebatkan ayat-ayat Allah tanpa alasan yang sampai kepada mereka. Amat besar kemurkaan (bagi mereka) di sisi Allah dan di sisi orang-orang yang beriman. Demikianlah Allah mengunci mati hati orang yang sombong dan sewenang-wenang.<?php break;}
case 36:{?>Dan berkatalah Firaun: &quot;Hai Haman, buatkanlah bagiku sebuah bangunan yang tinggi supaya aku sampai ke pintu-pintu,<?php break;}
case 37:{?>(yaitu) pintu-pintu langit, supaya aku dapat melihat Tuhan Musa dan sesungguhnya aku memandangnya seorang pendusta&quot;. Demikianlah dijadikan Firaun memandang baik perbuatan yang buruk itu, dan dia dihalangi dari jalan (yang benar); dan tipu daya Firaun itu tidak lain hanyalah membawa kerugian.<?php break;}
case 38:{?>Orang yang beriman itu berkata: &quot;Hai kaumku, ikutilah aku, aku akan menunjukkan kepadamu jalan yang benar.<?php break;}
case 39:{?>Hai kaumku, sesungguhnya kehidupan dunia ini hanyalah kesenangan (sementara) dan sesungguhnya akhirat itulah negeri yang kekal.<?php break;}
case 40:{?>Barang siapa mengerjakan perbuatan jahat, maka dia tidak akan dibalas melainkan sebanding dengan kejahatan itu. Dan barang siapa mengerjakan amal yang saleh baik laki-laki maupun perempuan sedang ia dalam keadaan beriman, maka mereka akan masuk surga, mereka diberi rezeki di dalamnya tanpa hisab.<?php break;}
case 41:{?>Hai kaumku, bagaimanakah kamu, aku menyeru kamu kepada keselamatan, tetapi kamu menyeru aku ke neraka?<?php break;}
case 42:{?>(Kenapa) kamu menyeruku supaya kafir kepada Allah dan mempersekutukan-Nya dengan apa yang tidak kuketahui padahal aku menyeru kamu (beriman) kepada Yang Maha Perkasa lagi Maha Pengampun?<?php break;}
case 43:{?>Sudah pasti bahwa apa yang kamu seru supaya aku (beriman) kepadanya tidak dapat memperkenankan seruan apa pun baik di dunia maupun di akhirat. Dan sesungguhnya kita kembali kepada Allah dan sesungguhnya orang-orang yang melampaui batas, mereka itulah penghuni neraka.<?php break;}
case 44:{?>Kelak kamu akan ingat kepada apa yang kukatakan kepada kamu. Dan aku menyerahkan urusanku kepada Allah. Sesungguhnya Allah Maha Melihat akan hamba-hamba-Nya&quot;.<?php break;}
case 45:{?>Maka Allah memeliharanya dari kejahatan tipu daya mereka, dan Firaun beserta kaumnya dikepung oleh azab yang amat buruk.<?php break;}
case 46:{?>Kepada mereka dinampakkan neraka pada pagi dan petang, dan pada hari terjadinya Kiamat. (Dikatakan kepada malaikat): &quot;Masukkanlah Firaun dan kaumnya ke dalam azab yang sangat keras&quot;.<?php break;}
case 47:{?>Dan (ingatlah), ketika mereka berbantah-bantah dalam neraka, maka orang-orang yang lemah berkata kepada orang-orang yang menyombongkan diri: &quot;Sesungguhnya kami adalah pengikut-pengikutmu, maka dapatkah kamu menghindarkan dari kami sebahagian azab api neraka?&quot;<?php break;}
case 48:{?>Orang-orang yang menyombongkan diri menjawab: &quot;Sesungguhnya kita semua sama-sama dalam neraka karena sesungguhnya Allah telah menetapkan keputusan antara hamba-hamba- (Nya)&quot;.<?php break;}
case 49:{?>Dan orang-orang yang berada dalam neraka berkata kepada penjaga-penjaga neraka Jahanam: &quot;Mohonkanlah kepada Tuhanmu supaya Dia meringankan azab dari kami barang sehari&quot;.<?php break;}
case 50:{?>Penjaga Jahanam berkata: &quot;Dan apakah belum datang kepada kamu rasul-rasulmu dengan membawa keterangan-keterangan?&quot; Mereka menjawab: &quot;Benar, sudah datang&quot;. Penjaga-penjaga Jahanam berkata: &quot;Berdoalah kamu&quot;. Dan doa orang-orang kafir itu hanyalah sia-sia belaka.<?php break;}
case 51:{?>Sesungguhnya Kami menolong rasul-rasul Kami dan orang-orang yang beriman dalam kehidupan dunia dan pada hari berdirinya saksi-saksi (hari kiamat),<?php break;}
case 52:{?>(yaitu) hari yang tiada berguna bagi orang-orang lalim permintaan maafnya dan bagi merekalah laknat dan bagi merekalah tempat tinggal yang buruk.<?php break;}
case 53:{?>Dan sesungguhnya telah Kami berikan petunjuk kepada Musa; dan Kami wariskan Taurat kepada Bani Israel,<?php break;}
case 54:{?>untuk menjadi petunjuk dan peringatan bagi orang-orang yang berpikir.<?php break;}
case 55:{?>Maka bersabarlah kamu, karena sesungguhnya janji Allah itu benar, dan mohonlah ampunan untuk dosamu dan bertasbihlah seraya memuji Tuhanmu pada waktu petang dan pagi.<?php break;}
case 56:{?>Sesungguhnya orang-orang yang memperdebatkan tentang ayat-ayat Allah tanpa alasan yang sampai kepada mereka tidak ada dalam dada mereka melainkan hanyalah (keinginan akan) kebesaran yang mereka sekali-kali tiada akan mencapainya, maka mintalah perlindungan kepada Allah. Sesungguhnya Dia Maha Mendengar lagi Maha Melihat.<?php break;}
case 57:{?>Sesungguhnya penciptaan langit dan bumi lebih besar daripada penciptaan manusia akan tetapi kebanyakan manusia tidak mengetahui.<?php break;}
case 58:{?>Dan tidaklah sama orang yang buta dengan orang yang melihat, dan tidaklah (pula sama) orang-orang yang beriman serta mengerjakan amal saleh dengan orang-orang yang durhaka. Sedikit sekali kamu mengambil pelajaran.<?php break;}
case 59:{?>Sesungguhnya hari kiamat pasti akan datang, tidak ada keraguan tentangnya, akan tetapi kebanyakan manusia tiada beriman.<?php break;}
case 60:{?>Dan Tuhanmu berfirman: &quot;Berdoalah kepada-Ku, niscaya akan Kuperkenankan bagimu. Sesungguhnya orang-orang yang menyombongkan diri dari menyembah-Ku akan masuk neraka Jahanam dalam keadaan hina dina&quot;.<?php break;}
case 61:{?>Allah-lah yang menjadikan malam untuk kamu supaya kamu beristirahat padanya; dan menjadikan siang terang benderang. Sesungguhnya Allah benar-benar mempunyai karunia yang dilimpahkan atas manusia, akan tetapi kebanyakan manusia tidak bersyukur.<?php break;}
case 62:{?>Yang demikian itu adalah Allah, Tuhanmu, Pencipta segala sesuatu, tiada Tuhan (yang berhak disembah) melainkan Dia; maka bagaimanakah kamu dapat dipalingkan?<?php break;}
case 63:{?>Seperti demikianlah dipalingkan orang-orang yang selalu mengingkari ayat-ayat Allah.<?php break;}
case 64:{?>Allah-lah yang menjadikan bumi bagi kamu tempat menetap dan langit sebagai atap, dan membentuk kamu lalu membaguskan rupamu serta memberi kamu rezeki dengan sebahagian yang baik-baik. Yang demikian itu adalah Allah Tuhanmu, Maha Agung Allah, Tuhan semesta alam.<?php break;}
case 65:{?>Dialah Yang hidup kekal, tiada Tuhan (yang berhak disembah) melainkan Dia; maka sembahlah Dia dengan memurnikan ibadah kepada-Nya. Segala puji bagi Allah Tuhan semesta alam.<?php break;}
case 66:{?>Katakanlah (ya Muhammad): &quot;Sesungguhnya aku dilarang menyembah sembahan yang kamu sembah selain Allah setelah datang kepadaku keterangan-keterangan dari Tuhanku; dan aku diperintahkan supaya tunduk patuh kepada Tuhan semesta alam.<?php break;}
case 67:{?>Dia-lah yang menciptakan kamu dari tanah kemudian dari setetes, air mani, sesudah itu dari segumpal darah, kemudian dilahirkannya kamu sebagai seorang anak, kemudian (kamu dibiarkan hidup) supaya kamu sampai kepada masa (dewasa), kemudian (dibiarkan kamu hidup lagi) sampai tua, di antara kamu ada yang diwafatkan sebelum itu. (Kami perbuat demikian) supaya kamu sampai kepada ajal yang ditentukan dan supaya kamu memahami (nya).<?php break;}
case 68:{?>Dia-lah yang menghidupkan dan mematikan, maka apabila Dia menetapkan sesuatu urusan, Dia hanya berkata kepadanya: &quot;Jadilah&quot;, maka jadilah ia.<?php break;}
case 69:{?>Apakah kamu tidak melihat kepada orang-orang yang membantah ayat-ayat Allah? Bagaimanakah mereka dapat dipalingkan?<?php break;}
case 70:{?>(Yaitu) orang-orang yang mendustakan Al Kitab (Al Qur'an) dan wahyu yang dibawa oleh rasul-rasul Kami yang telah Kami utus. Kelak mereka akan mengetahui,<?php break;}
case 71:{?>ketika belenggu dan rantai dipasang di leher mereka, seraya mereka diseret,<?php break;}
case 72:{?>ke dalam air yang sangat panas, kemudian mereka dibakar dalam api,<?php break;}
case 73:{?>kemudian dikatakan kepada mereka: &quot;Manakah berhala-berhala yang selalu kamu persekutukan<?php break;}
case 74:{?>(yang kamu sembah) selain Allah?&quot; Mereka menjawab: &quot;Mereka telah hilang lenyap dari kami, bahkan kami dahulu tiada pernah menyembah sesuatu&quot;. Seperti demikianlah Allah menyesatkan orang-orang kafir.<?php break;}
case 75:{?>Yang demikian itu disebabkan karena kamu bersuka ria di muka bumi dengan tidak benar dan karena kamu selalu bersuka ria (dalam kemaksiatan).<?php break;}
case 76:{?>(Dikatakan kepada mereka): &quot;Masuklah kamu ke pintu-pintu neraka Jahanam, dan kamu kekal di dalamnya. Maka itulah seburuk-buruk tempat bagi orang-orang yang sombong&quot;.<?php break;}
case 77:{?>Maka bersabarlah kamu, sesungguhnya janji Allah adalah benar; maka meskipun Kami perlihatkan kepadamu sebagian siksa yang Kami ancamkan kepada mereka atau pun Kami wafatkan kamu (sebelum ajal menimpa mereka), namun kepada Kami sajalah mereka dikembalikan.<?php break;}
case 78:{?>Dan sesungguhnya telah Kami utus beberapa orang rasul sebelum kamu, di antara mereka ada yang Kami ceritakan kepadamu dan di antara mereka ada (pula) yang tidak Kami ceritakan kepadamu. Tidak dapat bagi seorang rasul membawa suatu mukjizat, melainkan dengan seizin Allah; maka apabila telah datang perintah Allah, diputuskan (semua perkara) dengan adil. Dan ketika itu rugilah orang-orang yang berpegang kepada yang batil.<?php break;}
case 79:{?>Allah-lah yang menjadikan binatang ternak untuk kamu, sebagiannya untuk kamu kendarai dan sebagiannya untuk kamu makan.<?php break;}
case 80:{?>Dan (ada lagi) manfaat-manfaat yang lain pada binatang ternak itu untuk kamu dan supaya kamu mencapai suatu keperluan yang tersimpan dalam hati dengan mengendarainya. Dan kamu dapat diangkut dengan mengendarai binatang-binatang itu dan dengan mengendarai bahtera.<?php break;}
case 81:{?>Dan Dia memperlihatkan kepada kamu tanda-tanda (kekuasaan-Nya); maka tanda-tanda (kekuasaan) Allah yang manakah yang kamu ingkari?<?php break;}
case 82:{?>Maka apakah mereka tiada mengadakan perjalanan di muka bumi lalu memperhatikan betapa kesudahan orang-orang yang sebelum mereka. Adalah orang-orang yang sebelum mereka itu lebih hebat kekuatannya dan (lebih banyak) bekas-bekas mereka di muka bumi, maka apa yang mereka usahakan itu tidak dapat menolong mereka.<?php break;}
case 83:{?>Maka tatkala datang kepada mereka rasul-rasul (yang diutus kepada) mereka dengan membawa keterangan-keterangan, mereka merasa senang dengan pengetahuan yang ada pada mereka dan mereka dikepung oleh azab Allah yang selalu mereka perolok-olokkan itu.<?php break;}
case 84:{?>Maka tatkala mereka melihat azab Kami, mereka berkata: &quot;Kami beriman hanya kepada Allah saja dan kami kafir kepada sembahan-sembahan yang telah kami persekutukan dengan Allah.<?php break;}
case 85:{?>Maka iman mereka tiada berguna bagi mereka tatkala mereka telah melihat siksa Kami. Itulah sunah Allah yang telah berlaku terhadap hamba-hamba-Nya. Dan di waktu itu binasalah orang-orang kafir.<?php break;}
}?>