<?php 
switch($verse){
case 1:{?>Haa Miim.<?php break;}
case 2:{?>Diturunkan dari Tuhan Yang Maha Pemurah lagi Maha Penyayang.<?php break;}
case 3:{?>Kitab yang dijelaskan ayat-ayatnya, yakni bacaan dalam bahasa Arab, untuk kaum yang mengetahui,<?php break;}
case 4:{?>yang membawa berita gembira dan yang membawa peringatan, tetapi kebanyakan mereka berpaling (daripadanya); maka mereka tidak (mau) mendengarkan.<?php break;}
case 5:{?>Mereka berkata: &quot;Hati kami berada dalam tutupan (yang menutupi) apa yang kamu seru kami kepadanya dan di telinga kami ada sumbatan dan antara kami dan kamu ada dinding, maka bekerjalah kamu; sesungguhnya kami bekerja (pula)&quot;.<?php break;}
case 6:{?>Katakanlah: &quot;Bahwasanya aku hanyalah seorang manusia seperti kamu, diwahyukan kepadaku bahwasanya Tuhan kamu adalah Tuhan Yang Maha Esa, maka tetaplah pada jalan yang lurus menuju kepada-Nya dan mohonlah ampun kepada-Nya. Dan kecelakaan yang besarlah bagi orang-orang yang mempersekutukan (Nya),<?php break;}
case 7:{?>(yaitu) orang-orang yang tidak menunaikan zakat dan mereka kafir akan adanya (kehidupan) akhirat.<?php break;}
case 8:{?>Sesungguhnya orang-orang yang beriman dan mengerjakan amal yang saleh mereka mendapat pahala yang tiada putus-putusnya&quot;.<?php break;}
case 9:{?>Katakanlah: &quot;Sesungguhnya patutkah kamu kafir kepada Yang menciptakan bumi dalam dua masa dan kamu adakan sekutu-sekutu bagi-Nya? (Yang bersifat) demikian itulah Tuhan semesta alam&quot;.<?php break;}
case 10:{?>Dan Dia menciptakan di bumi itu gunung-gunung yang kokoh di atasnya. Dia memberkahinya dan Dia menentukan padanya kadar makanan-makanan (penghuni) nya dalam empat masa. (Penjelasan itu sebagai jawaban) bagi orang-orang yang bertanya.<?php break;}
case 11:{?>Kemudian Dia menuju langit dan langit itu masih merupakan asap, lalu Dia berkata kepadanya dan kepada bumi: &quot;Datanglah kamu keduanya menurut perintah-Ku dengan suka hati atau terpaksa&quot;. Keduanya menjawab: &quot;Kami datang dengan suka hati&quot;.<?php break;}
case 12:{?>Maka Dia menjadikannya tujuh langit dalam dua masa dan Dia mewahyukan pada tiap-tiap langit urusannya. Dan Kami hiasi langit yang dekat dengan bintang-bintang yang cemerlang dan Kami memeliharanya dengan sebaik-baiknya. Demikianlah ketentuan Yang Maha Perkasa lagi Maha Mengetahui.<?php break;}
case 13:{?>Jika mereka berpaling maka katakanlah: &quot;Aku telah memperingatkan kamu dengan petir, seperti petir yang menimpa kaum Ad dan kaum Tsamud&quot;.<?php break;}
case 14:{?>Ketika rasul-rasul datang kepada mereka dari depan dan dari belakang mereka (dengan menyerukan): &quot;Janganlah kamu menyembah selain Allah&quot;. Mereka menjawab: &quot;Kalau Tuhan kami menghendaki tentu Dia akan menurunkan malaikat-malaikat-Nya, maka sesungguhnya kami kafir kepada wahyu yang kamu diutus membawanya.<?php break;}
case 15:{?>Adapun kaum 'Aad maka mereka menyombongkan diri di muka bumi tanpa alasan yang benar dan berkata: &quot;Siapakah yang lebih besar kekuatannya dari kami?&quot; Dan apakah mereka itu tidak memperhatikan bahwa Allah yang menciptakan mereka adalah lebih besar kekuatan-Nya dari mereka? Dan adalah mereka mengingkari tanda-tanda (kekuatan) Kami.<?php break;}
case 16:{?>Maka Kami meniupkan angin yang amat gemuruh kepada mereka dalam beberapa hari yang sial, karena Kami hendak merasakan kepada mereka itu siksaan yang menghinakan dalam kehidupan dunia. Dan sesungguhnya siksaan akhirat lebih menghinakan sedang mereka tidak diberi pertolongan.<?php break;}
case 17:{?>Dan adapun kaum Tsamud maka mereka telah Kami beri petunjuk tetapi mereka lebih menyukai buta (kesesatan) dari petunjuk itu, maka mereka disambar petir azab yang menghinakan disebabkan apa yang telah mereka kerjakan.<?php break;}
case 18:{?>Dan Kami selamatkan orang-orang yang beriman dan mereka adalah orang-orang yang bertakwa.<?php break;}
case 19:{?>Dan (ingatlah) hari (ketika) musuh-musuh Allah digiring ke dalam neraka lalu mereka dikumpulkan (semuanya).<?php break;}
case 20:{?>Sehingga apabila mereka sampai ke neraka, pendengaran, penglihatan dan kulit mereka menjadi saksi terhadap mereka tentang apa yang telah mereka kerjakan.<?php break;}
case 21:{?>Dan mereka berkata kepada kulit mereka: &quot;Mengapa kamu menjadi saksi terhadap kami?&quot; Kulit mereka menjawab: &quot;Allah yang menjadikan segala sesuatu pandai berkata telah menjadikan kami pandai (pula) berkata, dan Dia-lah yang menciptakan kamu pada kali yang pertama dan hanya kepada-Nyalah kamu dikembalikan.<?php break;}
case 22:{?>Kamu sekali-kali tidak dapat bersembunyi dari persaksian pendengaran, penglihatan dan kulitmu terhadapmu bahkan kamu mengira bahwa Allah tidak mengetahui kebanyakan dari apa yang kamu kerjakan.<?php break;}
case 23:{?>Dan yang demikian itu adalah prasangkamu yang telah kamu sangka terhadap Tuhanmu, prasangka itu telah membinasakan kamu, maka jadilah kamu termasuk orang-orang yang merugi.<?php break;}
case 24:{?>Jika mereka bersabar (menderita azab) maka nerakalah tempat diam mereka dan jika mereka mengemukakan alasan-alasan, maka tidaklah mereka termasuk orang-orang yang diterima alasannya.<?php break;}
case 25:{?>Dan Kami tetapkan bagi mereka teman-teman yang menjadikan mereka memandang bagus apa yang ada di hadapan dan di belakang mereka dan tetaplah atas mereka keputusan azab pada umat-umat yang terdahulu sebelum mereka dari jin dan manusia; sesungguhnya mereka adalah orang-orang yang merugi.<?php break;}
case 26:{?>Dan orang-orang yang kafir berkata: &quot;Janganlah kamu mendengar dengan sungguh-sungguh akan Al Qur'an ini dan buatlah hiruk-pikuk terhadapnya, supaya kamu dapat mengalahkan (mereka).<?php break;}
case 27:{?>Maka sesungguhnya Kami akan merasakan azab yang keras kepada orang-orang kafir dan Kami akan memberi balasan kepada mereka dengan seburuk-buruk pembalasan bagi apa yang telah mereka kerjakan.<?php break;}
case 28:{?>Demikianlah balasan (terhadap) musuh-musuh Allah, (yaitu) neraka; mereka mendapat tempat tinggal yang kekal di dalamnya sebagai pembalasan atas keingkaran mereka terhadap ayat-ayat Kami.<?php break;}
case 29:{?>Dan orang-orang kafir berkata: &quot;Ya Tuhan kami perlihatkanlah kami dua jenis orang yang telah menyesatkan kami (yaitu) sebagian dari jin dan manusia agar kami letakkan keduanya di bawah telapak kaki kami supaya kedua jenis itu menjadi orang-orang yang hina&quot;.<?php break;}
case 30:{?>Sesungguhnya orang-orang yang mengatakan: &quot;Tuhan kami ialah Allah&quot; kemudian mereka meneguhkan pendirian mereka, maka malaikat akan turun kepada mereka (dengan mengatakan): &quot;Janganlah kamu merasa takut dan janganlah kamu merasa sedih; dan bergembiralah kamu dengan (memperoleh) surga yang telah dijanjikan Allah kepadamu&quot;.<?php break;}
case 31:{?>Kami lah Pelindung-pelindungmu dalam kehidupan dunia dan di akhirat; di dalamnya kamu memperoleh apa yang kamu inginkan dan memperoleh (pula) di dalamnya apa yang kamu minta.<?php break;}
case 32:{?>Sebagai hidangan (bagimu) dari Tuhan Yang Maha Pengampun lagi Maha Penyayang.<?php break;}
case 33:{?>Siapakah yang lebih baik perkataannya daripada orang yang menyeru kepada Allah, mengerjakan amal yang saleh dan berkata: &quot;Sesungguhnya aku termasuk orang-orang yang berserah diri?&quot;<?php break;}
case 34:{?>Dan tidaklah sama kebaikan dan kejahatan. Tolaklah (kejahatan itu) dengan cara yang lebih baik, maka tiba-tiba orang yang antaramu dan antara dia ada permusuhan seolah-olah telah menjadi teman yang sangat setia.<?php break;}
case 35:{?>Sifat-sifat yang baik itu tidak dianugerahkan melainkan kepada orang-orang yang sabar dan tidak dianugerahkan melainkan kepada orang-orang yang mempunyai keberuntungan yang besar.<?php break;}
case 36:{?>Dan jika setan mengganggumu dengan suatu gangguan, maka mohonlah perlindungan kepada Allah. Sesungguhnya Dia-lah Yang Maha Mendengar lagi Maha Mengetahui.<?php break;}
case 37:{?>Dan sebagian dari tanda-tanda kekuasaan-Nya ialah malam, siang, matahari dan bulan. Janganlah bersujud kepada matahari dan janganlah (pula) kepada bulan, tetapi bersujudlah kepada Allah Yang menciptakannya, jika kamu hanya kepada-Nya saja menyembah.<?php break;}
case 38:{?>Jika mereka menyombongkan diri, maka mereka (malaikat) yang di sisi Tuhanmu bertasbih kepada-Nya di malam dan siang hari, sedang mereka tidak jemu-jemu.<?php break;}
case 39:{?>Dan sebagian dari tanda-tanda (kekuasaan) Nya bahwa kamu melihat bumi itu kering tandus, maka apabila Kami turunkan air di atasnya, niscaya ia bergerak dan subur. Sesungguhnya Tuhan Yang menghidupkannya tentu dapat menghidupkan yang mati; sesungguhnya Dia Maha Kuasa atas segala sesuatu.<?php break;}
case 40:{?>Sesungguhnya orang-orang yang mengingkari ayat-ayat Kami, mereka tidak tersembunyi dari Kami. Maka apakah orang-orang yang dilemparkan ke dalam neraka lebih baik ataukah orang-orang yang datang dengan aman sentosa pada hari kiamat? Perbuatlah apa yang kamu kehendaki; sesungguhnya Dia Maha Melihat apa yang kamu kerjakan.<?php break;}
case 41:{?>Sesungguhnya orang-orang yang mengingkari Al Qur'an ketika Al Qur'an itu datang kepada mereka, (mereka itu pasti akan celaka), dan sesungguhnya Al Qur'an itu adalah kitab yang mulia.<?php break;}
case 42:{?>Yang tidak datang kepadanya (Al Qur'an) kebatilan baik dari depan maupun dari belakangnya, yang diturunkan dari Tuhan Yang Maha Bijaksana lagi Maha Terpuji.<?php break;}
case 43:{?>Tidaklah ada yang dikatakan (oleh orang-orang kafir) kepadamu itu selain apa yang sesungguhnya telah dikatakan kepada rasul-rasul sebelum kamu. Sesungguhnya Tuhan kamu benar-benar mempunyai ampunan dan hukuman yang pedih.<?php break;}
case 44:{?>Dan jika Kami jadikan Al Qur'an itu suatu bacaan dalam selain bahasa Arab tentulah mereka mengatakan: &quot;Mengapa tidak dijelaskan ayat-ayatnya?&quot;. Apakah (patut Al Qur'an) dalam bahasa asing, sedang (rasul adalah orang) Arab? Katakanlah: &quot;Al Qur'an itu adalah petunjuk dan penawar bagi orang-orang yang beriman. Dan orang-orang yang tidak beriman pada telinga mereka ada sumbatan, sedang Al Qur'an itu suatu kegelapan bagi mereka. Mereka itu adalah (seperti) orang-orang yang dipanggil dari tempat yang jauh&quot;.<?php break;}
case 45:{?>Dan sesungguhnya telah Kami berikan kepada Musa Taurat lalu diperselisihkan tentang Taurat itu. Kalau tidak ada keputusan yang telah terdahulu dari Tuhanmu, tentulah orang-orang kafir itu sudah dibinasakan. Dan sesungguhnya mereka terhadap Al Qur'an benar-benar dalam keragu-raguan yang membingungkan.<?php break;}
case 46:{?>Barang siapa yang mengerjakan amal yang saleh maka (pahalanya) untuk dirinya sendiri dan barang siapa yang berbuat jahat maka (dosanya) atas dirinya sendiri; dan sekali-kali tidaklah Tuhanmu menganiaya hamba-hamba (Nya).<?php break;}
case 47:{?>Kepada-Nya lah dikembalikan pengetahuan tentang hari kiamat. Dan tidak ada buah-buahan keluar dari kelopaknya dan tidak seorang perempuan pun mengandung dan tidak (pula) melahirkan, melainkan dengan sepengetahuan-Nya. Pada hari Tuhan memanggil mereka: &quot;Di manakah sekutu-sekutu-Ku itu?&quot;; mereka menjawab: &quot;Kami nyatakan kepada Engkau bahwa tidak ada seorang pun di antara kami yang memberi kesaksian (bahwa Engkau punya sekutu)&quot;.<?php break;}
case 48:{?>Dan lenyaplah dari mereka apa yang selalu mereka sembah dahulu, dan mereka yakin bahwa tidak ada bagi mereka sesuatu jalan keluar pun.<?php break;}
case 49:{?>Manusia tidak jemu memohon kebaikan, dan jika mereka ditimpa malapetaka dia menjadi putus asa lagi putus harapan.<?php break;}
case 50:{?>Dan jika Kami merasakan kepadanya sesuatu rahmat dari Kami sesudah dia ditimpa kesusahan, pastilah dia berkata: &quot;Ini adalah hakku, dan aku tidak yakin bahwa hari kiamat itu akan datang. Dan jika aku dikembalikan kepada Tuhanku maka sesungguhnya aku akan memperoleh kebaikan pada sisi-Nya&quot;. Maka Kami benar-benar akan memberitakan kepada orang-orang kafir apa yang telah mereka kerjakan dan akan Kami rasakan kepada mereka azab yang keras.<?php break;}
case 51:{?>Dan apabila Kami memberikan nikmat kepada manusia, ia berpaling dan menjauhkan diri; tetapi apabila ia ditimpa malapetaka maka ia banyak berdoa.<?php break;}
case 52:{?>Katakanlah: &quot;Bagaimana pendapatmu jika (Al Qur'an) itu datang dari sisi Allah, kemudian kamu mengingkarinya. Siapakah yang lebih sesat daripada orang yang selalu berada dalam penyimpangan yang jauh?&quot;<?php break;}
case 53:{?>Kami akan memperlihatkan kepada mereka tanda-tanda (kekuasaan) Kami di segenap ufuk dan pada diri mereka sendiri, sehingga jelaslah bagi mereka bahwa Al Qur'an itu adalah benar. Dan apakah Tuhanmu tidak cukup (bagi kamu) bahwa sesungguhnya Dia menyaksikan segala sesuatu?<?php break;}
case 54:{?>Ingatlah bahwa sesungguhnya mereka adalah dalam keraguan tentang pertemuan dengan Tuhan mereka. Ingatlah, bahwa sesungguhnya Dia Maha Meliputi segala sesuatu.<?php break;}
}?>