<?php 
switch($verse){
case 1:{?>Haa Miim.<?php break;}
case 2:{?>'Ain Siin Qaaf.<?php break;}
case 3:{?>Demikianlah Allah Yang Maha Perkasa lagi Maha Bijaksana, mewahyukan kepada kamu dan kepada orang-orang yang sebelum kamu.<?php break;}
case 4:{?>Kepunyaan-Nya lah apa yang ada di langit dan apa yang ada di bumi. Dan Dialah Yang Maha Tinggi lagi Maha Besar.<?php break;}
case 5:{?>Hampir saja langit itu pecah dari sebelah atasnya (karena kebesaran Tuhan) dan malaikat-malaikat bertasbih serta memuji Tuhannya dan memohonkan ampun bagi orang-orang yang ada di bumi. Ingatlah, bahwa sesungguhnya Allah Dia-lah Yang Maha Pengampun lagi Maha Penyayang.<?php break;}
case 6:{?>Dan orang-orang yang mengambil pelindung-pelindung selain Allah, Allah mengawasi (perbuatan) mereka; dan kamu (ya Muhammad) bukanlah orang yang diserahi mengawasi mereka.<?php break;}
case 7:{?>Demikianlah Kami wahyukan kepadamu Al Qur'an dalam bahasa Arab supaya kamu memberi peringatan kepada umulqura (penduduk Mekah) dan penduduk (negeri-negeri) sekelilingnya serta memberi peringatan (pula) tentang hari berkumpul (kiamat) yang tidak ada keraguan padanya. Segolongan masuk surga dan segolongan masuk neraka.<?php break;}
case 8:{?>Dan kalau Allah menghendaki niscaya Allah menjadikan mereka satu umat (saja), tetapi Dia memasukkan orang-orang yang dikehendaki-Nya ke dalam rahmat-Nya. Dan orang-orang yang lalim tidak ada bagi mereka seorang pelindung pun dan tidak pula seorang penolong.<?php break;}
case 9:{?>Atau patutkah mereka mengambil pelindung-pelindung selain Allah? Maka Allah, Dialah Pelindung (yang sebenarnya) dan Dia menghidupkan orang-orang yang mati dan Dia adalah Maha Kuasa atas segala sesuatu.<?php break;}
case 10:{?>Tentang sesuatu apa pun kamu berselisih maka putusannya (terserah) kepada Allah. (Yang mempunyai sifat-sifat demikian) itulah Allah Tuhanku. Kepada-Nya lah aku bertawakal dan kepada-Nya lah aku kembali.<?php break;}
case 11:{?>(Dia) Pencipta langit dan bumi. Dia menjadikan bagi kamu dari jenis kamu sendiri pasangan-pasangan dan dari jenis binatang ternak pasangan-pasangan (pula), dijadikan-Nya kamu berkembang biak dengan jalan itu. Tidak ada sesuatu pun yang serupa dengan Dia, dan Dia-lah Yang Maha Mendengar lagi Maha Melihat.<?php break;}
case 12:{?>Kepunyaan-Nya-lah perbendaharaan langit dan bumi; Dia melapangkan rezeki bagi siapa yang dikehendaki-Nya dan menyempitkan (nya). Sesungguhnya Dia Maha Mengetahui segala sesuatu.<?php break;}
case 13:{?>Dia telah mensyariatkan kamu tentang agama apa yang telah diwasiatkan-Nya kepada Nuh dan apa yang telah Kami wahyukan kepadamu dan apa yang telah Kami wasiatkan kepada Ibrahim, Musa dan Isa yaitu: Tegakkanlah agama dan janganlah kamu berpecah belah tentangnya. Amat berat bagi orang-orang musyrik agama yang kamu seru mereka kepadanya. Allah menarik kepada agama itu orang yang dikehendaki-Nya dan memberi petunjuk kepada (agama) -Nya orang yang kembali (kepada-Nya).<?php break;}
case 14:{?>Dan mereka (ahli kitab) tidak berpecah belah melainkan sesudah datangnya pengetahuan kepada mereka karena kedengkian antara mereka. Kalau tidaklah karena sesuatu ketetapan yang telah ada dari Tuhanmu dahulunya (untuk menangguhkan azab) sampai kepada waktu yang ditentukan, pastilah mereka telah dibinasakan. Dan sesungguhnya orang-orang yang diwariskan kepada mereka Al-Kitab (Taurat dan Injil) sesudah mereka, benar-benar berada dalam keraguan yang menggoncangkan tentang kitab itu.<?php break;}
case 15:{?>Maka karena itu serulah (mereka kepada agama itu) dan tetaplah sebagaimana diperintahkan kepadamu dan janganlah mengikuti hawa nafsu mereka dan katakanlah: &quot;Aku beriman kepada semua Kitab yang diturunkan Allah dan aku diperintahkan supaya berlaku adil di antara kamu. Allah-lah Tuhan kami dan Tuhan kamu. Bagi kami amal-amal kami dan bagi kamu amal-amal kamu. Tidak ada pertengkaran antara kami dan kamu, Allah mengumpulkan antara kita dan kepada-Nya lah kembali (kita)&quot;<?php break;}
case 16:{?>Dan orang-orang yang membantah (agama) Allah sesudah agama itu diterima maka bantahan mereka itu sia-sia saja di sisi Tuhan mereka. Mereka mendapat kemurkaan (Allah) dan bagi mereka azab yang sangat keras.<?php break;}
case 17:{?>Allah-lah yang menurunkan kitab dengan (membawa) kebenaran dan (menurunkan) neraca (keadilan). Dan tahukah kamu, boleh jadi hari kiamat itu (sudah) dekat?<?php break;}
case 18:{?>Orang-orang yang tidak beriman kepada hari kiamat meminta supaya hari itu segera didatangkan dan orang-orang yang beriman merasa takut kepadanya dan mereka yakin bahwa kiamat itu adalah benar (akan terjadi). Ketahuilah bahwa sesungguhnya orang-orang yang membantah tentang terjadinya kiamat itu benar-benar dalam kesesatan yang jauh.<?php break;}
case 19:{?>Allah Maha Lembut terhadap hamba-hamba-Nya; Dia memberi rezeki kepada siapa yang dikehendaki-Nya dan Dialah Yang Maha Kuat lagi Maha Perkasa.<?php break;}
case 20:{?>Barang siapa yang menghendaki keuntungan di akhirat akan Kami tambah keuntungan itu baginya dan barang siapa yang menghendaki keuntungan di dunia Kami berikan kepadanya sebagian dari keuntungan dunia dan tidak ada baginya suatu bahagian pun di akhirat.<?php break;}
case 21:{?>Apakah mereka mempunyai sembahan-sembahan selain Allah yang mensyariatkan untuk mereka agama yang tidak diizinkan Allah? Sekiranya tak ada ketetapan yang menentukan (dari Allah) tentulah mereka telah dibinasakan. Dan sesungguhnya orang-orang yang lalim itu akan memperoleh azab yang amat pedih.<?php break;}
case 22:{?>Kamu lihat orang-orang yang lalim sangat ketakutan karena kejahatan-kejahatan yang telah mereka kerjakan, sedang siksaan menimpa mereka. Dan orang-orang yang saleh (berada) di dalam taman-taman surga, mereka memperoleh apa yang mereka kehendaki di sisi Tuhan mereka. Yang demikian itu adalah karunia yang besar.<?php break;}
case 23:{?>Itulah (karunia) yang (dengan itu) Allah menggembirakan hamba-hamba-Nya yang beriman dan mengerjakan amal saleh. Katakanlah: &quot;Aku tidak meminta kepadamu sesuatu upah pun atas seruanku kecuali kasih sayang dalam kekeluargaan&quot;. Dan siapa yang mengerjakan kebaikan akan Kami tambahkan baginya kebaikan pada kebaikannya itu. Sesungguhnya Allah Maha Pengampun lagi Maha Mensyukuri.<?php break;}
case 24:{?>Bahkan mereka mengatakan: &quot;Dia (Muhammad) telah mengada-adakan dusta terhadap Allah&quot;. Maka jika Allah menghendaki niscaya Dia mengunci mati hatimu; dan Allah menghapuskan yang batil dan membenarkan yang hak dengan kalimat-kalimat-Nya (Al Qur'an). Sesungguhnya Dia Maha Mengetahui segala isi hati.<?php break;}
case 25:{?>Dan Dialah yang menerima tobat dari hamba-hamba-Nya dan memaafkan kesalahan-kesalahan dan mengetahui apa yang kamu kerjakan,<?php break;}
case 26:{?>dan Dia memperkenankan (doa) orang-orang yang beriman serta mengerjakan amal yang saleh dan menambah (pahala) kepada mereka dari karunia-Nya. Dan orang-orang yang kafir bagi mereka azab yang sangat keras.<?php break;}
case 27:{?>Dan jika Allah melapangkan rezeki kepada hamba-hamba-Nya tentulah mereka akan melampaui batas di muka bumi, tetapi Allah menurunkan apa yang dikehendaki-Nya dengan ukuran. Sesungguhnya Dia Maha Mengetahui (keadaan) hamba-hamba-Nya lagi Maha Melihat.<?php break;}
case 28:{?>Dan Dialah Yang menurunkan hujan sesudah mereka berputus asa dan menyebarkan rahmat-Nya. Dan Dialah Yang Maha Pelindung lagi Maha Terpuji.<?php break;}
case 29:{?>Dan di antara ayat-ayat (tanda-tanda kekuasaan) -Nya ialah menciptakan langit dan bumi dan makhluk-makhluk yang melata yang Dia sebarkan pada keduanya. Dan Dia Maha Kuasa mengumpulkan semuanya apabila dikehendaki-Nya.<?php break;}
case 30:{?>Dan apa musibah yang menimpa kamu maka adalah disebabkan oleh perbuatan tanganmu sendiri, dan Allah memaafkan sebagian besar (dari kesalahan-kesalahanmu).<?php break;}
case 31:{?>Dan kamu tidak dapat melepaskan diri (dari azab Allah) di muka bumi, dan kamu tidak memperoleh seorang pelindung pun dan tidak pula seorang penolong selain Allah.<?php break;}
case 32:{?>Dan di antara tanda-tanda kekuasaan-Nya ialah kapal-kapal (yang berlayar) di laut seperti gunung-gunung.<?php break;}
case 33:{?>Jika Dia menghendaki Dia akan menenangkan angin, maka jadilah kapal-kapal itu terhenti di permukaan laut. Sesungguhnya pada yang demikian itu terdapat tanda-tanda (kekuasaan) -Nya bagi setiap orang yang banyak bersabar dan banyak bersyukur,<?php break;}
case 34:{?>atau kapal-kapal itu dibinasakan-Nya karena perbuatan mereka atau Dia memberi maaf sebagian besar (dari mereka).<?php break;}
case 35:{?>Dan supaya orang-orang yang membantah ayat-ayat (kekuasaan) Kami mengetahui bahwa mereka sekali-kali tidak akan memperoleh jalan ke luar (dari siksaan).<?php break;}
case 36:{?>Maka sesuatu apa pun yang diberikan kepadamu, itu adalah kenikmatan hidup di dunia; dan yang ada pada sisi Allah lebih baik dan lebih kekal bagi orang-orang yang beriman, dan hanya kepada Tuhan mereka, mereka bertawakal.<?php break;}
case 37:{?>dan (bagi) orang-orang yang menjauhi dosa-dosa besar dan perbuatan-perbuatan keji, dan apabila mereka marah mereka memberi maaf.<?php break;}
case 38:{?>Dan (bagi) orang-orang yang menerima (mematuhi) seruan Tuhannya dan mendirikan salat, sedang urusan mereka (diputuskan) dengan musyawarah antara mereka; dan mereka menafkahkan sebagian dari rezeki yang Kami berikan kepada mereka.<?php break;}
case 39:{?>Dan (bagi) orang-orang yang apabila mereka diperlakukan dengan lalim mereka membela diri.<?php break;}
case 40:{?>Dan balasan suatu kejahatan adalah kejahatan yang serupa, maka Barang siapa memaafkan dan berbuat baik maka pahalanya atas (tanggungan) Allah. Sesungguhnya Dia tidak menyukai orang-orang yang lalim.<?php break;}
case 41:{?>Dan sesungguhnya orang-orang yang membela diri sesudah teraniaya, tidak ada suatu dosa pun atas mereka.<?php break;}
case 42:{?>Sesungguhnya dosa itu atas orang-orang yang berbuat lalim kepada manusia dan melampaui batas di muka bumi tanpa hak. Mereka itu mendapat azab yang pedih.<?php break;}
case 43:{?>Tetapi orang yang bersabar dan memaafkan sesungguhnya (perbuatan) yang demikian itu termasuk hal-hal yang diutamakan.<?php break;}
case 44:{?>Dan siapa yang disesatkan Allah maka tidak ada baginya seorang Pemimpin pun sesudah itu. Dan kamu akan melihat orang-orang yang lalim ketika mereka melihat azab berkata: &quot;Adakah kiranya jalan untuk kembali (ke dunia)?&quot;<?php break;}
case 45:{?>Dan kamu akan melihat mereka dihadapkan ke neraka dalam keadaan tunduk karena (merasa) hina, mereka melihat dengan pandangan yang lesu. Dan orang-orang yang beriman berkata: &quot;Sesungguhnya orang-orang yang merugi ialah orang-orang yang kehilangan diri mereka sendiri dan (kehilangan) keluarga mereka pada hari kiamat. Ingatlah, sesungguhnya orang-orang yang lalim itu berada dalam azab yang kekal.<?php break;}
case 46:{?>Dan mereka sekali-kali tidak mempunyai pelindung-pelindung yang dapat menolong mereka selain Allah. Dan siapa yang disesatkan Allah maka tidaklah ada baginya sesuatu jalan pun (untuk mendapat petunjuk).<?php break;}
case 47:{?>Patuhilah seruan Tuhanmu sebelum datang dari Allah suatu hari yang tidak dapat ditolak kedatangannya. Kamu tidak memperoleh tempat berlindung pada hari itu dan tidak (pula) dapat mengingkari (dosa-dosamu).<?php break;}
case 48:{?>Jika mereka berpaling maka Kami tidak mengutus kamu sebagai pengawas bagi mereka. Kewajibanmu tidak lain hanyalah menyampaikan (risalah). Sesungguhnya apabila Kami merasakan kepada manusia sesuatu rahmat dari Kami dia bergembira ria karena rahmat itu. Dan jika mereka ditimpa kesusahan disebabkan perbuatan tangan mereka sendiri (niscaya mereka ingkar) karena sesungguhnya manusia itu amat ingkar (kepada nikmat).<?php break;}
case 49:{?>Kepunyaan Allah-lah kerajaan langit dan bumi, Dia menciptakan apa yang Dia kehendaki, Dia memberikan anak-anak perempuan kepada siapa yang Dia kehendaki dan memberikan anak-anak lelaki kepada siapa yang Dia kehendaki,<?php break;}
case 50:{?>atau Dia menganugerahkan kedua jenis laki-laki dan perempuan (kepada siapa yang dikehendaki-Nya), dan Dia menjadikan mandul siapa yang Dia kehendaki. Sesungguhnya Dia Maha Mengetahui lagi Maha Kuasa.<?php break;}
case 51:{?>Dan tidak ada bagi seorang manusia pun bahwa Allah berkata-kata dengan dia kecuali dengan perantaraan wahyu atau di belakang tabir atau dengan mengutus seorang utusan (malaikat) lalu diwahyukan kepadanya dengan seizin-Nya apa yang Dia kehendaki. Sesungguhnya Dia Maha Tinggi lagi Maha Bijaksana.<?php break;}
case 52:{?>Dan demikianlah Kami wahyukan kepadamu wahyu (Al Qur'an) dengan perintah Kami. Sebelumnya kamu tidaklah mengetahui apakah Al Kitab (Al Qur'an) dan tidak pula mengetahui apakah iman itu, tetapi Kami menjadikan Al Qur'an itu cahaya, yang Kami tunjuki dengan dia siapa yang Kami kehendaki di antara hamba-hamba Kami. Dan sesungguhnya kamu benar-benar memberi petunjuk kepada jalan yang lurus.<?php break;}
case 53:{?>(Yaitu) jalan Allah yang kepunyaan-Nya segala apa yang ada di langit dan apa yang ada di bumi. Ingatlah, bahwa kepada Allah-lah kembali semua urusan.<?php break;}
}?>