<?php 
switch($verse){
case 1:{?>Haa Miim.<?php break;}
case 2:{?>Kitab (ini) diturunkan dari Allah Yang Maha Perkasa lagi Maha Bijaksana.<?php break;}
case 3:{?>Sesungguhnya pada langit dan bumi benar-benar terdapat tanda-tanda (kekuasaan Allah) untuk orang-orang yang beriman.<?php break;}
case 4:{?>Dan pada penciptaan kamu dan pada binatang-binatang yang melata yang bertebaran (di muka bumi) terdapat tanda-tanda (kekuasaan Allah) untuk kaum yang meyakini,<?php break;}
case 5:{?>dan pada pergantian malam dan siang dan hujan yang diturunkan Allah dari langit lalu dihidupkan-Nya dengan air hujan itu bumi sesudah matinya; dan pada perkisaran angin terdapat pula tanda-tanda (kekuasaan Allah) bagi kaum yang berakal.<?php break;}
case 6:{?>Itulah ayat-ayat Allah yang Kami membacakannya kepadamu dengan sebenarnya; maka dengan perkataan manakah lagi mereka akan beriman sesudah (kalam) Allah dan keterangan-keterangan-Nya.<?php break;}
case 7:{?>Kecelakaan yang besarlah bagi tiap-tiap orang yang banyak berdusta lagi banyak berdosa,<?php break;}
case 8:{?>dia mendengar ayat-ayat Allah dibacakan kepadanya kemudian dia tetap menyombongkan diri seakan-akan dia tidak mendengarnya. Maka beri kabar gembiralah dia dengan azab yang pedih.<?php break;}
case 9:{?>Dan apabila dia mengetahui barang sedikit tentang ayat-ayat Kami, maka ayat-ayat itu dijadikan olok-olok. Merekalah yang memperoleh azab yang menghinakan.<?php break;}
case 10:{?>Di hadapan mereka neraka Jahanam dan tidak akan berguna bagi mereka Sedikit pun apa yang telah mereka kerjakan, dan tidak pula berguna apa yang mereka jadikan sebagai sembahan-sembahan (mereka) dari selain Allah. Dan bagi mereka azab yang besar.<?php break;}
case 11:{?>Ini (Al Qur'an) adalah petunjuk. Dan orang-orang yang kafir kepada ayat-ayat Tuhannya bagi mereka azab yaitu siksaan yang sangat pedih.<?php break;}
case 12:{?>Allah lah yang menundukkan lautan untukmu supaya kapal-kapal dapat berlayar padanya dengan seizin-Nya, dan supaya kamu dapat mencari sebagian karunia-Nya dan mudah-mudahan kamu bersyukur.<?php break;}
case 13:{?>Dan Dia menundukkan untukmu apa yang ada di langit dan apa yang ada di bumi semuanya, (sebagai rahmat) daripada-Nya. Sesungguhnya pada yang demikian itu benar-benar terdapat tanda-tanda (kekuasaan Allah) bagi kaum yang berpikir.<?php break;}
case 14:{?>Katakanlah kepada orang-orang yang beriman hendaklah mereka memaafkan orang-orang yang tiada takut akan hari-hari Allah karena Dia akan membalas sesuatu kaum terhadap apa yang telah mereka kerjakan.<?php break;}
case 15:{?>Barang siapa yang mengerjakan amal yang saleh maka itu adalah untuk dirinya sendiri, dan barang siapa mengerjakan kejahatan, maka itu akan menimpa dirinya sendiri, kemudian kepada Tuhanmulah kamu dikembalikan.<?php break;}
case 16:{?>Dan sesungguhnya telah Kami berikan kepada Bani Israel Al Kitab (Taurat), kekuasaan dan kenabian dan Kami berikan kepada mereka rezeki-rezeki yang baik dan Kami lebihkan mereka atas bangsa-bangsa (pada masanya).<?php break;}
case 17:{?>Dan Kami berikan kepada mereka keterangan-keterangan yang nyata tentang urusan (agama); maka mereka tidak berselisih melainkan sesudah datang kepada mereka pengetahuan karena kedengkian (yang ada) di antara mereka. Sesungguhnya Tuhanmu akan memutuskan antara mereka pada hari kiamat terhadap apa yang mereka selalu berselisih padanya.<?php break;}
case 18:{?>Kemudian Kami jadikan kamu berada di atas suatu syariat (peraturan) dari urusan (agama) itu, maka ikutilah syariat itu dan janganlah kamu ikuti hawa nafsu orang-orang yang tidak mengetahui.<?php break;}
case 19:{?>Sesungguhnya mereka sekali-kali tidak akan dapat menolak dari kamu Sedikit pun dari (siksaan) Allah. Dan sesungguhnya orang-orang yang lalim itu sebagian mereka menjadi penolong bagi sebagian yang lain, dan Allah adalah pelindung orang-orang yang bertakwa.<?php break;}
case 20:{?>Al Qur'an ini adalah pedoman bagi manusia, petunjuk dan rahmat bagi kaum yang meyakini.<?php break;}
case 21:{?>Apakah orang-orang yang membuat kejahatan itu menyangka bahwa Kami akan menjadikan mereka seperti orang-orang yang beriman dan mengerjakan amal yang saleh, yaitu sama antara kehidupan dan kematian mereka? Amat buruklah apa yang mereka sangka itu.<?php break;}
case 22:{?>Dan Allah menciptakan langit dan bumi dengan tujuan yang benar dan agar dibalasi tiap-tiap diri terhadap apa yang dikerjakannya, dan mereka tidak akan dirugikan.<?php break;}
case 23:{?>Maka pernahkah kamu melihat orang yang menjadikan hawa nafsunya sebagai tuhannya, dan Allah membiarkannya sesat berdasarkan ilmu-Nya dan Allah telah mengunci mati pendengaran dan hatinya dan meletakkan tutupan atas penglihatannya? Maka siapakah yang akan memberinya petunjuk sesudah Allah (membiarkannya sesat). Maka mengapa kamu tidak mengambil pelajaran?<?php break;}
case 24:{?>Dan mereka berkata: &quot;Kehidupan ini tidak lain hanyalah kehidupan di dunia saja, kita mati dan kita hidup dan tidak ada yang membinasakan kita selain masa&quot;, dan mereka sekali-kali tidak mempunyai pengetahuan tentang itu, mereka tidak lain hanyalah menduga-duga saja.<?php break;}
case 25:{?>Dan apabila dibacakan kepada mereka ayat-ayat Kami yang jelas, tidak ada bantahan mereka selain dari mengatakan: &quot;Datangkanlah nenek moyang kami jika kamu adalah orang-orang yang benar&quot;.<?php break;}
case 26:{?>Katakanlah: &quot;Allah-lah yang menghidupkan kamu kemudian mematikan kamu, setelah itu mengumpulkan kamu pada hari kiamat yang tidak ada keraguan padanya; akan tetapi kebanyakan manusia tidak mengetahui.<?php break;}
case 27:{?>Dan hanya kepunyaan Allah kerajaan langit dan bumi. Dan pada hari terjadinya kebangkitan, akan rugilah pada hari itu orang-orang yang mengerjakan kebatilan.<?php break;}
case 28:{?>Dan (pada hari itu) kamu lihat tiap-tiap umat berlutut. Tiap-tiap umat dipanggil untuk (melihat) buku catatan amalnya. Pada hari itu kamu diberi balasan terhadap apa yang telah kamu kerjakan.<?php break;}
case 29:{?>(Allah berfirman): &quot;Inilah kitab (catatan) Kami yang menuturkan terhadapmu dengan benar. Sesungguhnya Kami telah menyuruh mencatat apa yang telah kamu kerjakan.&quot;<?php break;}
case 30:{?>Adapun orang-orang yang beriman dan mengerjakan amal yang saleh maka Tuhan mereka memasukkan mereka ke dalam rahmat-Nya (surga). itulah keberuntungan yang nyata.<?php break;}
case 31:{?>Dan adapun orang-orang yang kafir (kepada mereka dikatakan): &quot;Maka apakah belum ada ayat-ayat-Ku yang dibacakan kepadamu lalu kamu menyombongkan diri dan kamu jadi kaum yang berbuat dosa?&quot;<?php break;}
case 32:{?>Dan apabila dikatakan (kepadamu): &quot;Sesungguhnya janji Allah itu adalah benar dan hari berbangkit itu tidak ada keraguan padanya&quot;, niscaya kamu menjawab: &quot;Kami tidak tahu apakah hari kiamat itu, kami sekali-kali tidak lain hanyalah menduga-duga saja dan kami sekali-kali tidak meyakini (nya)&quot;.<?php break;}
case 33:{?>Dan nyatalah bagi mereka keburukan-keburukan dari apa yang mereka kerjakan dan mereka diliputi oleh (azab) yang mereka selalu memperolok-olokkannya.<?php break;}
case 34:{?>Dan dikatakan (kepada mereka): &quot;Pada hari ini Kami melupakan kamu sebagaimana kamu telah melupakan pertemuan (dengan) harimu ini dan tempat kembalimu ialah neraka dan kamu sekali-kali tidak memperoleh penolong.<?php break;}
case 35:{?>Yang demikian itu, karena sesungguhnya kamu menjadikan ayat-ayat Allah sebagai olok-olokan dan kamu telah ditipu oleh kehidupan dunia, maka pada hari ini mereka tidak dikeluarkan dari neraka dan tidak pula mereka diberi kesempatan untuk bertobat.<?php break;}
case 36:{?>Maka bagi Allah-lah segala puji, Tuhan langit dan Tuhan bumi, Tuhan semesta alam.<?php break;}
case 37:{?>Dan bagi-Nya lah keagungan di langit dan di bumi, Dialah Yang Maha Perkasa lagi Maha Bijaksana.<?php break;}
}?>