<?php 
switch($verse){
case 1:{?>Haa Miim.<?php break;}
case 2:{?>Diturunkan Kitab ini dari Allah Yang Maha Perkasa lagi Maha Bijaksana.<?php break;}
case 3:{?>Kami tiada menciptakan langit dan bumi dan apa yang ada antara keduanya melainkan dengan (tujuan) yang benar dan dalam waktu yang ditentukan. Dan orang-orang yang kafir berpaling dari apa yang diperingatkan kepada mereka.<?php break;}
case 4:{?>Katakanlah: &quot;Terangkanlah kepadaku tentang apa yang kamu sembah selain Allah; perlihatkan kepada-Ku apakah yang telah mereka ciptakan dari bumi ini atau adakah mereka berserikat (dengan Allah) dalam (penciptaan) langit? Bawalah kepada-Ku Kitab yang sebelum (Al Qur'an) ini atau peninggalan dari pengetahuan (orang-orang dahulu), jika kamu adalah orang-orang yang benar&quot;.<?php break;}
case 5:{?>Dan siapakah yang lebih sesat daripada orang yang menyembah sembahan-sembahan selain Allah yang tiada dapat memperkenankan (doa) nya sampai hari kiamat dan mereka lalai dari (memperhatikan) doa mereka?<?php break;}
case 6:{?>Dan apabila manusia dikumpulkan (pada hari kiamat) niscaya sembahan-sembahan itu menjadi musuh mereka dan mengingkari pemujaan-pemujaan mereka.<?php break;}
case 7:{?>Dan apabila dibacakan kepada mereka ayat-ayat Kami yang menjelaskan, berkatalah orang-orang yang mengingkari kebenaran ketika kebenaran itu datang kepada mereka: &quot;Ini adalah sihir yang nyata&quot;.<?php break;}
case 8:{?>Bahkan mereka mengatakan: &quot;Dia (Muhammad) telah mengada-adakannya (Al Qur'an)&quot;, Katakanlah: &quot;Jika aku mengada-adakannya, maka kamu tiada mempunyai kuasa sedikitpun mempertahankan aku dari (azab) Allah itu. Dia lebih mengetahui apa-apa yang kamu percakapkan tentang Al Qur'an itu. Cukuplah Dia menjadi saksi antaraku dan antaramu dan Dia-lah Yang Maha Pengampun lagi Maha Penyayang&quot;.<?php break;}
case 9:{?>Katakanlah: &quot;Aku bukanlah rasul yang pertama di antara rasul-rasul dan aku tidak mengetahui apa yang akan diperbuat terhadapku dan tidak (pula) terhadapmu. Aku tidak lain hanyalah mengikuti apa yang diwahyukan kepadaku dan aku tidak lain hanyalah seorang pemberi peringatan yang menjelaskan&quot;.<?php break;}
case 10:{?>Katakanlah: &quot;Terangkanlah kepadaku, bagaimanakah pendapatmu jika Al Qur'an itu datang dari sisi Allah, padahal kamu mengingkarinya dan seorang saksi dari Bani Israel mengakui (kebenaran) yang serupa dengan (yang disebut dalam) Al Qur'an lalu dia beriman, sedang kamu menyombongkan diri. Sesungguhnya Allah tiada memberi petunjuk kepada orang-orang yang lalim&quot;.<?php break;}
case 11:{?>Dan orang-orang kafir berkata kepada orang-orang yang beriman: &quot;Kalau sekiranya dia (Al Qur'an) adalah suatu yang baik, tentulah mereka tiada mendahului kami (beriman) kepadanya. Dan karena mereka tidak mendapat petunjuk dengannya maka mereka akan berkata: &quot;Ini adalah dusta yang lama&quot;.<?php break;}
case 12:{?>Dan sebelum Al Qur'an itu telah ada kitab Musa sebagai petunjuk dan rahmat. Dan ini (Al Qur'an) adalah kitab yang membenarkannya dalam bahasa Arab untuk memberi peringatan kepada orang-orang yang lalim dan memberi kabar gembira kepada orang-orang yang berbuat baik.<?php break;}
case 13:{?>Sesungguhnya orang-orang yang mengatakan: &quot;Tuhan kami ialah Allah&quot;, kemudian mereka tetap istiqamah maka tidak ada kekhawatiran terhadap mereka dan mereka tiada (pula) berduka cita.<?php break;}
case 14:{?>Mereka itulah penghuni-penghuni surga, mereka kekal di dalamnya; sebagai balasan atas apa yang telah mereka kerjakan.<?php break;}
case 15:{?>Kami perintahkan kepada manusia supaya berbuat baik kepada dua orang ibu bapaknya, ibunya mengandungnya dengan susah payah, dan melahirkannya dengan susah payah (pula). Mengandungnya sampai menyapihnya adalah tiga puluh bulan, sehingga apabila dia telah dewasa dan umurnya sampai empat puluh tahun ia berdoa: &quot;Ya Tuhanku, tunjukilah aku untuk mensyukuri nikmat Engkau yang telah Engkau berikan kepadaku dan kepada ibu bapakku dan supaya aku dapat berbuat amal yang saleh yang Engkau ridai; berilah kebaikan kepadaku dengan (memberi kebaikan) kepada anak cucuku. Sesungguhnya aku bertobat kepada Engkau dan sesungguhnya aku termasuk orang-orang yang berserah diri&quot;.<?php break;}
case 16:{?>Mereka itulah orang-orang yang Kami terima dari mereka amal yang baik yang telah mereka kerjakan dan Kami ampuni kesalahan-kesalahan mereka, bersama penghuni-penghuni surga, sebagai janji yang benar yang telah dijanjikan kepada mereka.<?php break;}
case 17:{?>Dan orang yang berkata kepada dua orang ibu bapaknya: &quot;Cis bagi kamu keduanya, apakah kamu keduanya memperingatkan kepadaku bahwa aku akan dibangkitkan, padahal sungguh telah berlalu beberapa umat sebelumku? lalu kedua ibu bapaknya itu memohon pertolongan kepada Allah seraya mengatakan, &quot;Celaka kamu, berimanlah! Sesungguhnya janji Allah adalah benar&quot;. Lalu dia berkata: &quot;Ini tidak lain hanyalah dongengan orang-orang yang dahulu belaka&quot;.<?php break;}
case 18:{?>Mereka itulah orang-orang yang telah pasti ketetapan (azab) atas mereka bersama umat-umat yang telah berlalu sebelum mereka dari jin dan manusia. Sesungguhnya mereka adalah orang-orang yang merugi.<?php break;}
case 19:{?>Dan bagi masing-masing mereka derajat menurut apa yang telah mereka kerjakan dan agar Allah mencukupkan bagi mereka (balasan) pekerjaan-pekerjaan mereka sedang mereka tiada dirugikan.<?php break;}
case 20:{?>Dan (ingatlah) hari (ketika) orang-orang kafir dihadapkan ke neraka (kepada mereka dikatakan): &quot;Kamu telah menghabiskan rezekimu yang baik dalam kehidupan duniawimu (saja) dan kamu telah bersenang-senang dengannya; maka pada hari ini kamu dibalasi dengan azab yang menghinakan karena kamu telah menyombongkan diri di muka bumi tanpa hak dan karena kamu telah fasik&quot;.<?php break;}
case 21:{?>Dan ingatlah (Hud) saudara kaum Ad yaitu ketika dia memberi peringatan kepada kaumnya di Al Ahqaaf dan sesungguhnya telah terdahulu beberapa orang pemberi peringatan sebelumnya dan sesudahnya (dengan mengatakan): &quot;Janganlah kamu menyembah selain Allah, sesungguhnya aku khawatir kamu akan ditimpa azab hari yang besar&quot;.<?php break;}
case 22:{?>Mereka menjawab: &quot;Apakah kamu datang kepada kami untuk memalingkan kami dari (menyembah) tuhan-tuhan kami? Maka datangkanlah kepada kami azab yang telah kamu ancamkan kepada kami jika kamu termasuk orang-orang yang benar&quot;.<?php break;}
case 23:{?>Ia berkata: &quot;Sesungguhnya pengetahuan (tentang itu) hanya pada sisi Allah dan aku (hanya) menyampaikan kepadamu apa yang aku diutus dengan membawanya tetapi aku lihat kamu adalah kaum yang bodoh&quot;.<?php break;}
case 24:{?>Maka tatkala mereka melihat azab itu berupa awan yang menuju ke lembah-lembah mereka, berkatalah mereka: &quot;Inilah awan yang akan menurunkan hujan kepada kami&quot;. (Bukan)! bahkan itulah azab yang kamu minta supaya datang dengan segera (yaitu) angin yang mengandung azab yang pedih,<?php break;}
case 25:{?>yang menghancurkan segala sesuatu dengan perintah Tuhannya, maka jadilah mereka tidak ada yang kelihatan lagi kecuali (bekas-bekas) tempat tinggal mereka. Demikianlah Kami memberi balasan kepada kaum yang berdosa.<?php break;}
case 26:{?>Dan sesungguhnya Kami telah meneguhkan kedudukan mereka dalam hal-hal yang Kami belum pernah meneguhkan kedudukanmu dalam hal itu dan Kami telah memberikan kepada mereka pendengaran, penglihatan dan hati; tetapi pendengaran, penglihatan dan hati mereka itu tidak berguna sedikit jua pun bagi mereka, karena mereka selalu mengingkari ayat-ayat Allah dan mereka telah diliputi oleh siksa yang dahulu selalu mereka memperolok-olokkannya.<?php break;}
case 27:{?>Dan sesungguhnya Kami telah membinasakan negeri-negeri di sekitarmu dan Kami telah mendatangkan tanda-tanda kebesaran Kami berulang-ulang supaya mereka kembali (bertobat).<?php break;}
case 28:{?>Maka mengapa yang mereka sembah selain Allah sebagai Tuhan untuk mendekatkan diri (kepada Allah) tidak dapat menolong mereka. Bahkan tuhan-tuhan itu telah lenyap dari mereka? Itulah akibat kebohongan mereka dan apa yang dahulu mereka ada-adakan.<?php break;}
case 29:{?>Dan (ingatlah) ketika Kami hadapkan serombongan jin kepadamu yang mendengarkan Al Qur'an, maka tatkala mereka menghadiri pembacaan (nya) lalu mereka berkata: &quot;Diamlah kamu (untuk mendengarkannya)&quot;. Ketika pembacaan telah selesai mereka kembali kepada kaumnya (untuk) memberi peringatan.<?php break;}
case 30:{?>Mereka berkata: &quot;Hai kaum kami, sesungguhnya kami telah mendengarkan kitab (Al Qur'an) yang telah diturunkan sesudah Musa yang membenarkan kitab-kitab yang sebelumnya lagi memimpin kepada kebenaran dan kepada jalan yang lurus.<?php break;}
case 31:{?>Hai kaum kami, terimalah (seruan) orang yang menyeru kepada Allah dan berimanlah kepada-Nya, niscaya Allah akan mengampuni dosa-dosa kamu dan melepaskan kamu dari azab yang pedih.<?php break;}
case 32:{?>Dan orang yang tidak menerima (seruan) orang yang menyeru kepada Allah maka dia tidak akan melepaskan diri dari azab Allah di muka bumi dan tidak ada baginya pelindung selain Allah. Mereka itu dalam kesesatan yang nyata&quot;.<?php break;}
case 33:{?>Dan apakah mereka tidak memperhatikan bahwa sesungguhnya Allah yang menciptakan langit dan bumi dan Dia tidak merasa payah karena menciptakannya, kuasa menghidupkan orang-orang mati? Ya (bahkan) sesungguhnya Dia Maha Kuasa atas segala sesuatu.<?php break;}
case 34:{?>Dan (Ingatlah) hari (ketika) orang-orang kafir dihadapkan kepada neraka, (dikatakan kepada mereka): &quot;Bukankah (azab) ini benar?&quot; Mereka menjawab: &quot;Ya benar, demi Tuhan kami&quot;. Allah berfirman: &quot;Maka rasakanlah azab ini disebabkan kamu selalu ingkar&quot;.<?php break;}
case 35:{?>Maka bersabarlah kamu seperti orang-orang yang mempunyai keteguhan hati dari rasul-rasul telah bersabar dan janganlah kamu meminta disegerakan (azab) bagi mereka. Pada hari mereka melihat azab yang diancamkan kepada mereka (merasa) seolah-olah tidak tinggal (di dunia) melainkan sesaat pada siang hari. (Inilah) suatu pelajaran yang cukup, maka tidak dibinasakan melainkan kaum yang fasik.<?php break;}
}?>