<?php 
switch($verse){
case 1:{?>Orang-orang yang kafir dan menghalang-halangi (manusia) dari jalan Allah, Allah menghapus perbuatan-perbuatan mereka.<?php break;}
case 2:{?>Dan orang-orang yang beriman (kepada Allah) dan mengerjakan amal-amal yang saleh serta beriman (pula) kepada apa yang diturunkan kepada Muhammad dan itulah yang hak dari Tuhan mereka, Allah menghapuskan kesalahan-kesalahan mereka dan memperbaiki keadaan mereka.<?php break;}
case 3:{?>Yang demikian adalah karena sesungguhnya orang-orang kafir mengikuti yang batil dan sesungguhnya orang-orang yang beriman mengikuti yang hak dari Tuhan mereka. Demikianlah Allah membuat untuk manusia perbandingan-perbandingan bagi mereka.<?php break;}
case 4:{?>Apabila kamu bertemu dengan orang-orang kafir (di medan perang) maka pancunglah batang leher mereka. Sehingga apabila kamu telah mengalahkan mereka maka tawanlah mereka dan sesudah itu kamu boleh membebaskan mereka atau menerima tebusan sampai perang berhenti. Demikianlah, apabila Allah menghendaki niscaya Allah akan membinasakan mereka tetapi Allah hendak menguji sebahagian kamu dengan sebahagian yang lain. Dan orang-orang yang gugur pada jalan Allah, Allah tidak akan menyia-nyiakan amal mereka.<?php break;}
case 5:{?>Allah akan memberi pimpinan kepada mereka dan memperbaiki keadaan mereka,<?php break;}
case 6:{?>dan memasukkan mereka ke dalam surga yang telah diperkenalkan-Nya kepada mereka.<?php break;}
case 7:{?>Hai orang-orang yang beriman, jika kamu menolong (agama) Allah, niscaya Dia akan menolongmu dan meneguhkan kedudukanmu.<?php break;}
case 8:{?>Dan orang-orang yang kafir maka kecelakaanlah bagi mereka dan Allah menghapus amal-amal mereka.<?php break;}
case 9:{?>Yang demikian itu adalah karena sesungguhnya mereka benci kepada apa yang diturunkan Allah (Al Qur'an) lalu Allah menghapuskan (pahala-pahala) amal-amal mereka.<?php break;}
case 10:{?>Maka apakah mereka tidak mengadakan perjalanan di muka bumi sehingga mereka dapat memperhatikan bagaimana kesudahan orang-orang yang sebelum mereka; Allah telah menimpakan kebinasaan atas mereka dan orang-orang kafir akan menerima (akibat-akibat) seperti itu.<?php break;}
case 11:{?>Yang demikian itu karena sesungguhnya Allah adalah pelindung orang-orang yang beriman dan karena sesungguhnya orang-orang kafir itu tiada mempunyai pelindung.<?php break;}
case 12:{?>Sesungguhnya Allah memasukkan orang-orang yang beriman dan mengerjakan amal saleh ke dalam surga yang mengalir di bawahnya sungai-sungai. Dan orang-orang yang kafir itu bersenang-senang (di dunia) dan mereka makan seperti makannya binatang-binatang. Dan neraka adalah tempat tinggal mereka.<?php break;}
case 13:{?>Dan betapa banyaknya negeri-negeri yang (penduduknya) lebih kuat dari (penduduk) negerimu (Muhammad) yang telah mengusirmu itu. Kami telah membinasakan mereka; maka tidak ada seorang penolong pun bagi mereka.<?php break;}
case 14:{?>Maka apakah orang yang berpegang pada keterangan yang datang dari Tuhannya sama dengan orang yang (setan) menjadikan dia memandang baik perbuatannya yang buruk itu dan mengikuti hawa nafsunya?<?php break;}
case 15:{?>(Apakah) perumpamaan (penghuni) surga yang dijanjikan kepada orang-orang yang bertakwa yang di dalamnya ada sungai-sungai dari air yang tiada berubah rasa dan baunya, sungai-sungai dari air susu yang tiada berubah rasanya, sungai-sungai dari khamar (arak) yang lezat rasanya bagi peminumnya dan sungai-sungai dari madu yang disaring; dan mereka memperoleh di dalamnya segala macam buah-buahan dan ampunan dari Tuhan mereka, sama dengan orang yang kekal dalam neraka dan diberi minuman dengan air yang mendidih sehingga memotong-motong ususnya?<?php break;}
case 16:{?>Dan di antara mereka ada orang yang mendengarkan perkataanmu sehingga apabila mereka keluar dari sisimu mereka berkata kepada orang yang telah diberi ilmu pengetahuan (sahabat-sahabat Nabi): &quot;Apakah yang dikatakannya tadi?&quot; Mereka itulah orang-orang yang dikunci mati hati mereka oleh Allah dan mengikuti hawa nafsu mereka.<?php break;}
case 17:{?>Dan orang-orang yang mendapat petunjuk Allah menambah petunjuk kepada mereka dan memberikan kepada mereka (balasan) ketakwaannya.<?php break;}
case 18:{?>Maka tidaklah yang mereka tunggu-tunggu melainkan hari kiamat (yaitu) kedatangannya kepada mereka dengan tiba-tiba, karena sesungguhnya telah datang tanda-tandanya. Maka apakah faedahnya bagi mereka kesadaran mereka itu apabila hari kiamat sudah datang?<?php break;}
case 19:{?>Maka ketahuilah, bahwa sesungguhnya tidak ada Tuhan (Yang Hak) melainkan Allah dan mohonlah ampunan bagi dosamu dan bagi (dosa) orang-orang mukmin, laki-laki dan perempuan. Dan Allah mengetahui tempat kamu berusaha dan tempat tinggalmu.<?php break;}
case 20:{?>Dan orang-orang yang beriman berkata: &quot;Mengapa tiada diturunkan suatu surat?&quot; Maka apabila diturunkan suatu surat yang jelas maksudnya dan disebutkan di dalamnya (perintah) perang, kamu lihat orang-orang yang ada penyakit di dalam hatinya memandang kepadamu seperti pandangan orang yang pingsan karena takut mati, dan kecelakaanlah bagi mereka.<?php break;}
case 21:{?>Taat dan mengucapkan perkataan yang baik (adalah lebih baik bagi mereka). Apabila telah tetap perintah perang (mereka tidak menyukainya). Tetapi jika mereka benar (imannya) terhadap Allah, niscaya yang demikian itu lebih baik bagi mereka.<?php break;}
case 22:{?>Maka apakah kiranya jika kamu berkuasa kamu akan membuat kerusakan di muka bumi dan memutuskan hubungan kekeluargaan?<?php break;}
case 23:{?>Mereka itulah orang-orang yang dilaknati Allah dan ditulikan-Nya telinga mereka dan dibutakan-Nya penglihatan mereka.<?php break;}
case 24:{?>Maka apakah mereka tidak memperhatikan Al Qur'an ataukah hati mereka terkunci?<?php break;}
case 25:{?>Sesungguhnya orang-orang yang kembali ke belakang (kepada kekafiran) sesudah petunjuk itu jelas bagi mereka, setan telah menjadikan mereka mudah (berbuat dosa) dan memanjangkan angan-angan mereka.<?php break;}
case 26:{?>Yang demikian itu karena sesungguhnya mereka (orang-orang munafik) itu berkata kepada orang-orang yang benci kepada apa yang diturunkan Allah (orang-orang Yahudi): &quot;Kami akan mematuhi kamu dalam beberapa urusan&quot;, sedang Allah mengetahui rahasia mereka.<?php break;}
case 27:{?>Bagaimanakah (keadaan mereka) apabila malaikat (maut) mencabut nyawa mereka seraya memukul muka mereka dan punggung mereka?<?php break;}
case 28:{?>Yang demikian itu adalah karena sesungguhnya mereka mengikuti apa yang menimbulkan kemurkaan Allah dan (karena) mereka membenci (apa yang menimbulkan) keridaan-Nya; sebab itu Allah menghapus (pahala) amal-amal mereka.<?php break;}
case 29:{?>Atau apakah orang-orang yang ada penyakit dalam hatinya mengira bahwa Allah tidak akan menampakkan kedengkian mereka?<?php break;}
case 30:{?>Dan kalau Kami menghendaki, niscaya Kami tunjukkan mereka kepadamu sehingga kamu benar-benar dapat mengenal mereka dengan tanda-tandanya. Dan kamu benar-benar akan mengenal mereka dari kiasan-kiasan perkataan mereka dan Allah mengetahui perbuatan-perbuatan kamu.<?php break;}
case 31:{?>Dan sesungguhnya Kami benar-benar akan menguji kamu agar Kami mengetahui orang-orang yang berjihad dan bersabar di antara kamu; dan agar Kami menyatakan (baik buruknya) hal ihwalmu.<?php break;}
case 32:{?>Sesungguhnya orang-orang kafir dan menghalangi (manusia) dari jalan Allah serta memusuhi rasul setelah petunjuk itu jelas bagi mereka, mereka tidak dapat memberi mudarat kepada Allah sedikit pun. Dan Allah akan menghapuskan (pahala) amal-amal mereka.<?php break;}
case 33:{?>Hai orang-orang yang beriman, taatlah kepada Allah dan taatlah kepada rasul dan janganlah kamu merusakkan (pahala) amal-amalmu.<?php break;}
case 34:{?>Sesungguhnya orang-orang yang kafir dan menghalangi (manusia) dari jalan Allah kemudian mereka mati dalam keadaan kafir, maka sekali-kali Allah tidak akan memberi ampun kepada mereka.<?php break;}
case 35:{?>Janganlah kamu lemah dan minta damai padahal kamulah yang di atas dan Allah (pun) beserta kamu dan Dia sekali-kali tidak akan mengurangi (pahala) amal-amalmu.<?php break;}
case 36:{?>Sesungguhnya kehidupan dunia hanyalah permainan dan senda gurau. Dan jika kamu beriman serta bertakwa, Allah akan memberikan pahala kepadamu dan Dia tidak akan meminta harta-hartamu.<?php break;}
case 37:{?>Jika Dia meminta harta kepadamu lalu mendesak kamu (supaya memberikan semuanya) niscaya kamu akan kikir dan Dia akan menampakkan kedengkianmu.<?php break;}
case 38:{?>Ingatlah, kamu ini orang-orang yang diajak untuk menafkahkan (hartamu) pada jalan Allah. Maka di antara kamu ada orang yang kikir, dan siapa yang kikir sesungguhnya dia hanyalah kikir terhadap dirinya sendiri. Dan Allah-lah yang Maha Kaya sedangkan kamulah orang-orang yang membutuhkan (Nya); dan jika kamu berpaling niscaya Dia akan mengganti (kamu) dengan kaum yang lain, dan mereka tidak akan seperti kamu (ini).<?php break;}
}?>