<?php 
switch($verse){
case 1:{?>Hai orang-orang yang beriman, janganlah kamu mendahului Allah dan Rasul-Nya dan bertakwalah kepada Allah. Sesungguhnya Allah Maha Mendengar lagi Maha Mengetahui.<?php break;}
case 2:{?>Hai orang-orang yang beriman, janganlah kamu meninggikan suaramu lebih dari suara Nabi, dan janganlah kamu berkata kepadanya dengan suara keras sebagaimana kerasnya (suara) sebahagian kamu terhadap sebahagian yang lain, supaya tidak hapus (pahala) amalanmu sedangkan kamu tidak menyadari.<?php break;}
case 3:{?>Sesungguhnya orang-orang yang merendahkan suaranya di sisi Rasulullah mereka itulah orang-orang yang telah diuji hati mereka oleh Allah untuk bertakwa. Bagi mereka ampunan dan pahala yang besar.<?php break;}
case 4:{?>Sesungguhnya orang-orang yang memanggil kamu dari luar kamar (mu) kebanyakan mereka tidak mengerti.<?php break;}
case 5:{?>Dan kalau sekiranya mereka bersabar sampai kamu keluar menemui mereka sesungguhnya itu adalah lebih baik bagi mereka, dan Allah Maha Pengampun lagi Maha Penyayang.<?php break;}
case 6:{?>Hai orang-orang yang beriman, jika datang kepadamu orang fasik membawa suatu berita, maka periksalah dengan teliti, agar kamu tidak menimpakan suatu musibah kepada suatu kaum tanpa mengetahui keadaannya yang menyebabkan kamu menyesal atas perbuatanmu itu.<?php break;}
case 7:{?>Dan ketahuilah olehmu bahwa di kalangan kamu ada Rasulullah. Kalau ia menuruti (kemauan) kamu dalam beberapa urusan benar-benarlah kamu akan mendapat kesusahan tetapi Allah menjadikan kamu cinta kepada keimanan dan menjadikan iman itu indah dalam hatimu serta menjadikan kamu benci kepada kekafiran, kefasikan dan kedurhakaan. Mereka itulah orang-orang yang mengikuti jalan yang lurus,<?php break;}
case 8:{?>sebagai karunia dan nikmat dari Allah. Dan Allah Maha Mengetahui lagi Maha Bijaksana.<?php break;}
case 9:{?>Dan jika ada dua golongan dari orang-orang mukmin berperang maka damaikanlah antara keduanya. Jika salah satu dari kedua golongan itu berbuat aniaya terhadap golongan yang lain maka perangilah golongan yang berbuat aniaya itu sehingga golongan itu kembali kepada perintah Allah; jika golongan itu telah kembali (kepada perintah Allah), maka damaikanlah antara keduanya dengan adil dan berlaku adillah. Sesungguhnya Allah menyukai orang-orang yang berlaku adil.<?php break;}
case 10:{?>Sesungguhnya orang-orang mukmin adalah bersaudara karena itu damaikanlah antara kedua saudaramu dan bertakwalah kepada Allah supaya kamu mendapat rahmat.<?php break;}
case 11:{?>Hai orang-orang yang beriman janganlah suatu kaum mengolok-olok kaum yang lain (karena) boleh jadi mereka (yang diolok-olok) lebih baik dari mereka (yang mengolok-olok) dan jangan pula wanita-wanita (mengolok-olok) wanita-wanita lain (karena) boleh jadi wanita-wanita (yang diperolok-olokkan) lebih baik dari wanita (yang mengolok-olok) dan janganlah kamu mencela dirimu sendiri dan janganlah kamu panggil memanggil dengan gelar-gelar yang buruk. Seburuk-buruk panggilan ialah (panggilan) yang buruk sesudah iman dan barang siapa yang tidak bertobat, maka mereka itulah orang-orang yang lalim.<?php break;}
case 12:{?>Hai orang-orang yang beriman, jauhilah kebanyakan dari prasangka, sesungguhnya sebagian prasangka itu adalah dosa dan janganlah kamu mencari-cari kesalahan orang lain dan janganlah sebahagian kamu menggunjing sebahagian yang lain. Sukakah salah seorang di antara kamu memakan daging saudaranya yang sudah mati? Maka tentulah kamu merasa jijik kepadanya. Dan bertakwalah kepada Allah. Sesungguhnya Allah Maha Penerima tobat lagi Maha Penyayang.<?php break;}
case 13:{?>Hai manusia, sesungguhnya Kami menciptakan kamu dari seorang laki-laki dan seorang perempuan dan menjadikan kamu berbangsa-bangsa dan bersuku-suku supaya kamu saling kenal mengenal. Sesungguhnya orang yang paling mulia di antara kamu di sisi Allah ialah orang yang paling bertakwa di antara kamu. Sesungguhnya Allah Maha Mengetahui lagi Maha Mengenal.<?php break;}
case 14:{?>Orang-orang Arab Badui itu berkata: &quot;Kami telah beriman&quot;. Katakanlah (kepada mereka): &quot;Kamu belum beriman, tetapi katakanlah: &quot;Kami telah tunduk&quot;, karena iman itu belum masuk ke dalam hatimu dan jika kamu taat kepada Allah dan Rasul-Nya, Dia tiada akan mengurangi sedikit pun (pahala) amalanmu; sesungguhnya Allah Maha Pengampun lagi Maha Penyayang&quot;.<?php break;}
case 15:{?>Sesungguhnya orang-orang yang beriman hanyalah orang-orang yang beriman kepada Allah dan Rasul-Nya kemudian mereka tidak ragu-ragu dan mereka berjihad dengan harta dan jiwa mereka pada jalan Allah, mereka itulah orang-orang yang benar.<?php break;}
case 16:{?>Katakanlah (kepada mereka): &quot;Apakah kamu akan memberitahukan kepada Allah tentang agamamu (keyakinanmu), padahal Allah mengetahui apa yang ada di langit dan apa yang ada di bumi dan Allah Maha Mengetahui segala sesuatu.&quot;<?php break;}
case 17:{?>Mereka merasa telah memberi nikmat kepadamu dengan keislaman mereka. Katakanlah: &quot;Janganlah kamu merasa telah memberi nikmat kepadaku dengan keislamanmu, sebenarnya Allah Dialah yang melimpahkan nikmat kepadamu dengan menunjuki kamu kepada keimanan jika kamu adalah orang-orang yang benar&quot;.<?php break;}
case 18:{?>Sesungguhnya Allah mengetahui apa yang gaib di langit dan di bumi. Dan Allah Maha Melihat apa yang kamu kerjakan.<?php break;}
}?>