<?php 
switch($verse){
case 1:{?>Hai orang-orang yang beriman, penuhilah akad-akad itu. Dihalalkan bagimu binatang ternak, kecuali yang akan dibacakan kepadamu. (Yang demikian itu) dengan tidak menghalalkan berburu ketika kamu sedang mengerjakan haji. Sesungguhnya Allah menetapkan hukum-hukum menurut yang dikehendaki-Nya.<?php break;}
case 2:{?>Hai orang-orang yang beriman, janganlah kamu melanggar syi'ar-syiar Allah, dan jangan melanggar kehormatan bulan-bulan haram, jangan (mengganggu) binatang-binatang had-ya, dan binatang-binatang qalaa-id, dan jangan (pula) mengganggu orang-orang yang mengunjungi Baitullah sedang mereka mencari karunia dan keridaan dari Tuhannya dan apabila kamu telah menyelesaikan ibadah haji, maka bolehlah berburu. Dan janganlah sekali-kali kebencian (mu) kepada sesuatu kaum karena mereka menghalang-halangi kamu dari Masjidilharam, mendorongmu berbuat aniaya (kepada mereka). Dan tolong-menolonglah kamu dalam (mengerjakan) kebajikan dan takwa, dan jangan tolong-menolong dalam berbuat dosa dan pelanggaran. Dan bertakwalah kamu kepada Allah, sesungguhnya Allah amat berat siksa-Nya.<?php break;}
case 3:{?>Diharamkan bagimu (memakan) bangkai, darah, daging babi, (daging hewan) yang disembelih atas nama selain Allah, yang tercekik, yang dipukul, yang jatuh, yang ditanduk, dan yang diterkam binatang buas, kecuali yang sempat kamu menyembelihnya, dan (diharamkan bagimu) yang disembelih untuk berhala. Dan (diharamkan juga) mengundi nasib dengan anak panah, (mengundi nasib dengan anak panah itu) adalah kefasikan. Pada hari ini orang-orang kafir telah putus asa untuk (mengalahkan) agamamu, sebab itu janganlah kamu takut kepada mereka dan takutlah kepada-Ku. Pada hari ini telah Kusempurnakan untuk kamu agamamu, dan telah Ku-cukupkan kepadamu nikmat-Ku, dan telah Ku-ridai Islam itu jadi agama bagimu. Maka barang siapa terpaksa karena kelaparan tanpa sengaja berbuat dosa, sesungguhnya Allah Maha Pengampun lagi Maha Penyayang.<?php break;}
case 4:{?>Mereka menanyakan kepadamu: &quot;Apakah yang dihalalkan bagi mereka?&quot; Katakanlah: &quot;Dihalalkan bagimu yang baik-baik dan (buruan yang ditangkap) oleh binatang buas yang telah kamu ajar dengan melatihnya untuk berburu, kamu mengajarnya menurut apa yang telah diajarkan Allah kepadamu, Maka makanlah dari apa yang ditangkapnya untukmu, dan sebutlah nama Allah atas binatang buas itu (waktu melepasnya). Dan bertakwalah kepada Allah, sesungguhnya Allah amat cepat hisab-Nya&quot;.<?php break;}
case 5:{?>Pada hari ini dihalalkan bagimu yang baik-baik. Makanan (sembelihan) orang-orang yang diberi Al Kitab itu halal bagimu, dan makanan kamu halal pula bagi mereka. (Dan dihalalkan mengawini) wanita-wanita yang menjaga kehormatan di antara wanita-wanita yang beriman dan wanita-wanita yang menjaga kehormatan di antara orang-orang yang diberi Al Kitab sebelum kamu, bila kamu telah membayar maskawin mereka dengan maksud menikahinya, tidak dengan maksud berzina dan tidak (pula) menjadikannya gundik-gundik. Barang siapa yang kafir sesudah beriman (tidak menerima hukum-hukum Islam) maka hapuslah amalannya dan ia di hari akhirat termasuk orang-orang merugi.<?php break;}
case 6:{?>Hai orang-orang yang beriman, apabila kamu hendak mengerjakan salat, maka basuhlah mukamu dan tanganmu sampai dengan siku, dan sapulah kepalamu dan (basuh) kakimu sampai dengan kedua mata kaki, dan jika kamu junub maka mandilah, dan jika kamu sakit atau dalam perjalanan atau kembali dari tempat buang air (kakus) atau menyentuh perempuan, lalu kamu tidak memperoleh air, maka bertayamumlah dengan tanah yang baik (bersih); sapulah mukamu dan tanganmu dengan tanah itu. Allah tidak hendak menyulitkan kamu, tetapi Dia hendak membersihkan kamu dan menyempurnakan nikmat-Nya bagimu, supaya kamu bersyukur.<?php break;}
case 7:{?>Dan ingatlah karunia Allah kepadamu dan perjanjian-Nya yang telah diikat-Nya dengan kamu, ketika kamu mengatakan: &quot;Kami dengar dan kami taati&quot;. Dan bertakwalah kepada Allah, sesungguhnya Allah Maha Mengetahui isi hati (mu).<?php break;}
case 8:{?>Hai orang-orang yang beriman, hendaklah kamu jadi orang-orang yang selalu menegakkan (kebenaran) karena Allah, menjadi saksi dengan adil. Dan janganlah sekali-kali kebencianmu terhadap sesuatu kaum, mendorong kamu untuk berlaku tidak adil. Berlaku adillah, karena adil itu lebih dekat kepada takwa. Dan bertakwalah kepada Allah, sesungguhnya Allah Maha Mengetahui apa yang kamu kerjakan.<?php break;}
case 9:{?>Allah telah menjanjikan kepada orang-orang yang beriman dan beramal saleh, (bahwa) untuk mereka ampunan dan pahala yang besar.<?php break;}
case 10:{?>Adapun orang-orang yang kafir dan mendustakan ayat-ayat Kami, mereka itu adalah penghuni neraka.<?php break;}
case 11:{?>Hai orang-orang yang beriman, ingatlah kamu akan nikmat Allah (yang diberikan-Nya) kepadamu, di waktu suatu kaum bermaksud hendak menggerakkan tangannya kepadamu (untuk berbuat jahat), maka Allah menahan tangan mereka dari kamu. Dan bertakwalah kepada Allah, dan hanya kepada Allah sajalah orang-orang mukmin itu harus bertawakal.<?php break;}
case 12:{?>Dan sesungguhnya Allah telah mengambil perjanjian (dari) Bani Israel dan telah Kami angkat di antara mereka dua belas orang pemimpin dan Allah berfirman: &quot;Sesungguhnya Aku beserta kamu, sesungguhnya jika kamu mendirikan salat dan menunaikan zakat serta beriman kepada rasul-rasul-Ku dan kamu bantu mereka dan kamu pinjamkan kepada Allah pinjaman yang baik sesungguhnya Aku akan menghapus dosa-dosamu. Dan sesungguhnya kamu akan Kumasukkan ke dalam surga yang mengalir di dalamnya sungai-sungai. Maka barang siapa yang kafir di antaramu sesudah itu, sesungguhnya ia telah tersesat dari jalan yang lurus&quot;.<?php break;}
case 13:{?>(Tetapi) karena mereka melanggar janjinya, Kami kutuk mereka, dan Kami jadikan hati mereka keras membatu. Mereka suka merobah perkataan (Allah) dari tempat-tempatnya, dan mereka (sengaja) melupakan sebagian dari apa yang mereka telah diperingatkan dengannya, dan kamu (Muhammad) senantiasa akan melihat kekhianatan dari mereka kecuali sedikit di antara mereka (yang tidak berkhianat), maka maafkanlah mereka dan biarkanlah mereka, sesungguhnya Allah menyukai orang-orang yang berbuat baik.<?php break;}
case 14:{?>Dan di antara orang-orang yang mengatakan: &quot;Sesungguhnya kami ini orang-orang Nasrani&quot;, ada yang telah Kami ambil perjanjian mereka, tetapi mereka (sengaja) melupakan sebahagian dari apa yang mereka telah diberi peringatan dengannya; maka Kami timbulkan di antara mereka permusuhan dan kebencian sampai hari kiamat. Dan kelak Allah akan memberitakan kepada mereka apa yang selalu mereka kerjakan.<?php break;}
case 15:{?>Hai Ahli Kitab, sesungguhnya telah datang kepadamu Rasul Kami, menjelaskan kepadamu banyak dari isi Al Kitab yang kamu sembunyikan, dan banyak (pula yang) dibiarkannya. Sesungguhnya telah datang kepadamu cahaya dari Allah, dan kitab yang menerangkan.<?php break;}
case 16:{?>Dengan kitab itulah Allah menunjuki orang-orang yang mengikuti keridaan-Nya ke jalan keselamatan, dan (dengan kitab itu pula) Allah mengeluarkan orang-orang itu dari gelap gulita kepada cahaya yang terang benderang dengan seizin-Nya, dan menunjuki mereka ke jalan yang lurus.<?php break;}
case 17:{?>Sesungguhnya telah kafirlah orang-orang yang berkata: &quot;Sesungguhnya Allah itu ialah Al Masih putra Maryam&quot;. Katakanlah: &quot;Maka siapakah (gerangan) yang dapat menghalang-halangi kehendak Allah, jika Dia hendak membinasakan Al Masih putra Maryam itu beserta ibunya dan seluruh orang-orang yang berada di bumi semuanya?&quot; Kepunyaan Allah-lah kerajaan langit dan bumi dan apa yang di antara keduanya; Dia menciptakan apa yang dikehendaki-Nya. Dan Allah Maha Kuasa atas segala sesuatu.<?php break;}
case 18:{?>Orang-orang Yahudi dan Nasrani mengatakan: &quot;Kami ini adalah anak-anak Allah dan kekasih-kekasih-Nya&quot;. Katakanlah: &quot;Maka mengapa Allah menyiksa kamu karena dosa-dosamu?&quot; (Kamu bukanlah anak-anak Allah dan kekasih-kekasih-Nya), tetapi kamu adalah manusia (biasa) di antara orang-orang yang diciptakan-Nya. Dia mengampuni bagi siapa yang dikehendaki-Nya dan menyiksa siapa yang dikehendaki-Nya. Dan Kepunyaan Allah-lah kerajaan langit dan bumi serta apa yang ada antara keduanya. Dan kepada Allah-lah kembali (segala sesuatu).<?php break;}
case 19:{?>Hai Ahli Kitab, sesungguhnya telah datang kepada kamu Rasul Kami, menjelaskan (syariat Kami) kepadamu ketika terputus (pengiriman) rasul-rasul, agar kamu tidak mengatakan: &quot;Tidak datang kepada kami baik seorang pembawa berita gembira maupun seorang pemberi peringatan&quot;. Sesungguhnya telah datang kepadamu pembawa berita gembira dan pemberi peringatan. Allah Maha Kuasa atas segala sesuatu.<?php break;}
case 20:{?>Dan (ingatlah), ketika Musa berkata kepada kaumnya: &quot;Hai kaumku, ingatlah nikmat Allah atasmu ketika Dia mengangkat nabi-nabi di antaramu, dan dijadikan-Nya kamu orang-orang merdeka, dan diberikan-Nya kepadamu apa yang belum pernah diberikan-Nya kepada seorang pun di antara umat-umat yang lain&quot;.<?php break;}
case 21:{?>Hai kaumku, masuklah ke tanah suci (Palestina) yang telah ditentukan Allah bagimu, dan janganlah kamu lari ke belakang (karena takut kepada musuh), maka kamu menjadi orang-orang yang merugi.<?php break;}
case 22:{?>Mereka berkata: &quot;Hai Musa, sesungguhnya dalam negeri itu ada orang-orang yang gagah perkasa, sesungguhnya kami sekali-kali tidak akan memasukinya sebelum mereka ke luar daripadanya. Jika mereka ke luar daripadanya, pasti kami akan memasukinya.&quot;<?php break;}
case 23:{?>Berkatalah dua orang di antara orang-orang yang takut (kepada Allah) yang Allah telah memberi nikmat atas keduanya: &quot;Serbulah mereka dengan melalui pintu gerbang (kota) itu, maka bila kamu memasukinya niscaya kamu akan menang. Dan hanya kepada Allah hendaknya kamu bertawakal, jika kamu benar-benar orang yang beriman&quot;.<?php break;}
case 24:{?>Mereka berkata: &quot;Hai Musa, kami sekali-sekali tidak akan memasukinya selama-lamanya, selagi mereka ada di dalamnya, karena itu pergilah kamu bersama Tuhanmu, dan berperanglah kamu berdua, sesungguhnya kami hanya duduk menanti di sini saja.&quot;<?php break;}
case 25:{?>Berkata Musa: &quot;Ya Tuhanku, aku tidak menguasai kecuali diriku sendiri dan saudaraku. Sebab itu pisahkanlah antara kami dengan orang-orang yang fasik itu&quot;<?php break;}
case 26:{?>Allah berfirman: &quot;(Jika demikian), maka sesungguhnya negeri itu diharamkan atas mereka selama empat puluh tahun, (selama itu) mereka akan berputar-putar kebingungan di bumi (padang Tiih) itu. Maka janganlah kamu bersedih hati (memikirkan nasib) orang-orang yang fasik itu.&quot;<?php break;}
case 27:{?>Ceriterakanlah kepada mereka kisah kedua putra Adam (Habil dan Kabil) menurut yang sebenarnya, ketika keduanya mempersembahkan kurban, maka diterima dari salah seorang dari mereka berdua (Habil) dan tidak diterima dari yang lain (Kabil). Ia berkata (Kabil): &quot;Aku pasti membunuhmu!&quot; Berkata Habil: &quot;Sesungguhnya Allah hanya menerima (korban) dari orang-orang yang bertakwa&quot;.<?php break;}
case 28:{?>&quot;Sungguh kalau kamu menggerakkan tanganmu kepadaku untuk membunuhku, aku sekali-kali tidak akan menggerakkan tanganku kepadamu untuk membunuhmu. Sesungguhnya aku takut kepada Allah, Tuhan seru sekalian alam.&quot;<?php break;}
case 29:{?>&quot;Sesungguhnya aku ingin agar kamu kembali dengan (membawa) dosa (membunuh) ku dan dosamu sendiri, maka kamu akan menjadi penghuni neraka, dan yang demikian itulah pembalasan bagi orang-orang yang lalim.&quot;<?php break;}
case 30:{?>Maka hawa nafsu Kabil menjadikannya menganggap mudah membunuh saudaranya, sebab itu dibunuhnyalah, maka jadilah ia seorang di antara orang-orang yang merugi.<?php break;}
case 31:{?>Kemudian Allah menyuruh seekor burung gagak menggali-gali di bumi untuk memperlihatkan kepadanya (Kabil) bagaimana dia seharusnya menguburkan mayit saudaranya. Berkata Kabil: &quot;Aduhai celaka aku, mengapa aku tidak mampu berbuat seperti burung gagak ini, lalu aku dapat menguburkan mayit saudaraku ini?&quot; Karena itu jadilah dia seorang di antara orang-orang yang menyesal.<?php break;}
case 32:{?>Oleh karena itu Kami tetapkan (suatu hukum) bagi Bani Israel, bahwa: barang siapa yang membunuh seorang manusia, bukan karena orang itu (membunuh) orang lain, atau bukan karena membuat kerusakan di muka bumi, maka seakan-akan dia telah membunuh manusia seluruhnya. Dan barang siapa yang memelihara kehidupan seorang manusia, maka seolah-olah dia telah memelihara kehidupan manusia semuanya. Dan sesungguhnya telah datang kepada mereka rasul-rasul Kami dengan (membawa) keterangan-keterangan yang jelas, kemudian banyak di antara mereka sesudah itu sungguh-sungguh melampaui batas dalam berbuat kerusakan di muka bumi.<?php break;}
case 33:{?>Sesungguhnya pembalasan terhadap orang-orang yang memerangi Allah dan Rasul-Nya dan membuat kerusakan di muka bumi, hanyalah mereka dibunuh atau disalib, atau dipotong tangan dan kaki mereka dengan bertimbal balik, atau dibuang dari negeri (tempat kediamannya). Yang demikian itu (sebagai) suatu penghinaan untuk mereka di dunia, dan di akhirat mereka beroleh siksaan yang besar,<?php break;}
case 34:{?>kecuali orang-orang yang tobat (di antara mereka) sebelum kamu dapat menguasai (menangkap) mereka; maka ketahuilah bahwasanya Allah Maha Pengampun lagi Maha Penyayang.<?php break;}
case 35:{?>Hai orang-orang yang beriman, bertakwalah kepada Allah dan carilah jalan yang mendekatkan diri kepada-Nya, dan berjihadlah pada jalan-Nya, supaya kamu mendapat keberuntungan.<?php break;}
case 36:{?>Sesungguhnya orang-orang yang kafir sekiranya mereka mempunyai apa yang di bumi ini seluruhnya dan mempunyai yang sebanyak itu (pula) untuk menebus diri mereka dengan itu dari azab hari kiamat, niscaya (tebusan itu) tidak akan diterima dari mereka, dan mereka beroleh azab yang pedih.<?php break;}
case 37:{?>Mereka ingin ke luar dari neraka, padahal mereka sekali-kali tidak dapat ke luar daripadanya, dan mereka beroleh azab yang kekal.<?php break;}
case 38:{?>Laki-laki yang mencuri dan perempuan yang mencuri, potonglah tangan keduanya (sebagai) pembalasan bagi apa yang mereka kerjakan dan sebagai siksaan dari Allah. Dan Allah Maha Perkasa lagi Maha Bijaksana.<?php break;}
case 39:{?>Maka barang siapa bertobat (di antara pencuri-pencuri itu) sesudah melakukan kejahatan itu dan memperbaiki diri, maka sesungguhnya Allah menerima tobatnya. Sesungguhnya Allah Maha Pengampun lagi Maha Penyayang.<?php break;}
case 40:{?>Tidakkah kamu tahu, sesungguhnya Allah-lah yang mempunyai kerajaan langit dan bumi, disiksa-Nya siapa yang dikehendaki-Nya dan diampuni-Nya bagi siapa yang dikehendaki-Nya. Dan Allah Maha Kuasa atas segala sesuatu.<?php break;}
case 41:{?>Hai Rasul, janganlah hendaknya kamu disedihkan oleh orang-orang yang bersegera (memperlihatkan) kekafirannya, yaitu di antara orang-orang yang mengatakan dengan mulut mereka: &quot;Kami telah beriman&quot;, padahal hati mereka belum beriman; dan (juga) di antara orang-orang Yahudi. (Orang-orang Yahudi itu) amat suka mendengar (berita-berita) bohong dan amat suka mendengar perkataan-perkataan orang lain yang belum pernah datang kepadamu; mereka merobah perkataan-perkataan (Taurat) dari tempat-tempatnya. Mereka mengatakan: &quot;Jika diberikan ini (yang sudah dirobah-robah oleh mereka) kepada kamu, maka terimalah, dan jika kamu diberi yang bukan ini, maka hati-hatilah&quot; Barang siapa yang Allah menghendaki kesesatannya, maka sekali-kali kamu tidak akan mampu menolak sesuatu pun (yang datang) daripada Allah. Mereka itu adalah orang-orang yang Allah tidak hendak menyucikan hati mereka. Mereka beroleh kehinaan di dunia dan di akhirat mereka beroleh siksaan yang besar.<?php break;}
case 42:{?>Mereka itu adalah orang-orang yang suka mendengar berita bohong, banyak memakan yang haram. Jika mereka (orang Yahudi) datang kepadamu (untuk meminta putusan), maka putuskanlah (perkara itu) di antara mereka, atau berpalinglah dari mereka; jika kamu berpaling dari mereka maka mereka tidak akan memberi mudarat kepadamu sedikit pun. Dan jika kamu memutuskan perkara mereka, maka putuskanlah (perkara itu) di antara mereka dengan adil, sesungguhnya Allah menyukai orang-orang yang adil.<?php break;}
case 43:{?>Dan bagaimanakah mereka mengangkatmu menjadi hakim mereka, padahal mereka mempunyai Taurat yang di dalamnya (ada) hukum Allah, kemudian mereka berpaling sesudah itu (dari putusanmu)? Dan mereka sungguh-sungguh bukan orang yang beriman.<?php break;}
case 44:{?>Sesungguhnya Kami telah menurunkan Kitab Taurat di dalamnya (ada) petunjuk dan cahaya (yang menerangi), yang dengan Kitab itu diputuskan perkara orang-orang Yahudi oleh nabi-nabi yang menyerah diri kepada Allah, oleh orang-orang alim mereka dan pendeta-pendeta mereka, disebabkan mereka diperintahkan memelihara kitab-kitab Allah dan mereka menjadi saksi terhadapnya. Karena itu janganlah kamu takut kepada manusia, (tetapi) takutlah kepada-Ku. Dan janganlah kamu menukar ayat-ayat-Ku dengan harga yang sedikit. Barang siapa yang tidak memutuskan menurut apa yang diturunkan Allah, maka mereka itu adalah orang-orang yang kafir.<?php break;}
case 45:{?>Dan kami telah tetapkan terhadap mereka di dalamnya (At Taurat) bahwasanya jiwa (dibalas) dengan jiwa, mata dengan mata, hidung dengan hidung, telinga dengan telinga, gigi dengan gigi, dan luka-luka (pun) ada kisasnya. Barang siapa yang melepaskan (hak kisas) nya, maka melepaskan hak itu (menjadi) penebus dosa baginya. Barang siapa tidak memutuskan perkara menurut apa yang diturunkan Allah, maka mereka itu adalah orang-orang yang lalim.<?php break;}
case 46:{?>Dan Kami iringkan jejak mereka (nabi-nabi Bani Israel) dengan Isa putra Maryam, membenarkan kitab yang sebelumnya, yaitu: Taurat. Dan Kami telah memberikan kepadanya Kitab Injil sedang di dalamnya (ada) petunjuk dan cahaya (yang menerangi), dan membenarkan kitab yang sebelumnya, yaitu Kitab Taurat. Dan menjadi petunjuk serta pengajaran untuk orang-orang yang bertakwa.<?php break;}
case 47:{?>Dan hendaklah orang-orang pengikut Injil, memutuskan perkara menurut apa yang diturunkan Allah di dalamnya. Barangsiapa tidak memutuskan perkara menurut apa yang diturunkan Allah, maka mereka itu adalah orang-orang yang fasik.<?php break;}
case 48:{?>Dan Kami telah turunkan kepadamu Al Qur'an dengan membawa kebenaran, membenarkan apa yang sebelumnya, yaitu kitab-kitab (yang diturunkan sebelumnya) dan batu ujian terhadap kitab-kitab yang lain itu; maka putuskanlah perkara mereka menurut apa yang Allah turunkan dan janganlah kamu mengikuti hawa nafsu mereka dengan meninggalkan kebenaran yang telah datang kepadamu. Untuk tiap-tiap umat di antara kamu, Kami berikan aturan dan jalan yang terang. Sekiranya Allah menghendaki, niscaya kamu dijadikan-Nya satu umat (saja), tetapi Allah hendak menguji kamu terhadap pemberian-Nya kepadamu, maka berlomba-lombalah berbuat kebajikan. Hanya kepada Allah-lah kembali kamu semuanya, lalu diberitahukan-Nya kepadamu apa yang telah kamu perselisihkan itu,<?php break;}
case 49:{?>dan hendaklah kamu memutuskan perkara di antara mereka menurut apa yang diturunkan Allah, dan janganlah kamu mengikuti hawa nafsu mereka. Dan berhati-hatilah kamu terhadap mereka, supaya mereka tidak memalingkan kamu dari sebahagian apa yang telah diturunkan Allah kepadamu. Jika mereka berpaling (dari hukum yang telah diturunkan Allah), maka ketahuilah bahwa sesungguhnya Allah menghendaki akan menimpakan musibah kepada mereka disebabkan sebahagian dosa-dosa mereka. Dan sesungguhnya kebanyakan manusia adalah orang-orang yang fasik.<?php break;}
case 50:{?>Apakah hukum Jahiliah yang mereka kehendaki, dan (hukum) siapakah yang lebih baik daripada (hukum) Allah bagi orang-orang yang yakin?<?php break;}
case 51:{?>Hai orang-orang yang beriman, janganlah kamu mengambil orang-orang Yahudi dan Nasrani menjadi pemimpin-pemimpin (mu); sebahagian mereka adalah pemimpin bagi sebahagian yang lain. Barang siapa di antara kamu mengambil mereka menjadi pemimpin, maka sesungguhnya orang itu termasuk golongan mereka. Sesungguhnya Allah tidak memberi petunjuk kepada orang-orang yang lalim.<?php break;}
case 52:{?>Maka kamu akan melihat orang-orang yang ada penyakit dalam hatinya (orang-orang munafik) bersegera mendekati mereka (Yahudi dan Nasrani), seraya berkata: &quot;Kami takut akan mendapat bencana&quot;. Mudah-mudahan Allah akan mendatangkan kemenangan (kepada Rasul-Nya), atau sesuatu keputusan dari sisi-Nya. Maka karena itu, mereka menjadi menyesal terhadap apa yang mereka rahasiakan dalam diri mereka.<?php break;}
case 53:{?>Dan orang-orang yang beriman akan mengatakan: &quot;Inikah orang-orang yang bersumpah sungguh-sungguh dengan nama Allah, bahwasanya mereka benar-benar beserta kamu?&quot; Rusak binasalah segala amal mereka, lalu mereka menjadi orang-orang yang merugi.<?php break;}
case 54:{?>Hai orang-orang yang beriman, barang siapa di antara kamu yang murtad dari agamanya, maka kelak Allah akan mendatangkan suatu kaum yang Allah mencintai mereka dan mereka pun mencintai-Nya, yang bersikap lemah lembut terhadap orang yang mukmin, yang bersikap keras terhadap orang-orang kafir, yang berjihad di jalan Allah, dan yang tidak takut kepada celaan orang yang suka mencela. Itulah karunia Allah, diberikan-Nya kepada siapa yang dikehendaki-Nya, dan Allah Maha Luas (pemberian-Nya) lagi Maha Mengetahui.<?php break;}
case 55:{?>Sesungguhnya penolong kamu hanyalah Allah, Rasul-Nya, dan orang-orang yang beriman, yang mendirikan salat dan menunaikan zakat, seraya mereka tunduk (kepada Allah).<?php break;}
case 56:{?>Dan barang siapa mengambil Allah, Rasul-Nya dan orang-orang yang beriman menjadi penolongnya, maka sesungguhnya pengikut (agama) Allah itulah yang pasti menang.<?php break;}
case 57:{?>Hai orang-orang yang beriman, janganlah kamu mengambil jadi pemimpinmu, orang-orang yang membuat agamamu jadi buah ejekan dan permainan, (yaitu) di antara orang-orang yang telah diberi Kitab sebelummu, dan orang-orang yang kafir (orang-orang musyrik). Dan bertakwalah kepada Allah jika kamu betul-betul orang-orang yang beriman.<?php break;}
case 58:{?>Dan apabila kamu menyeru (mereka) untuk (mengerjakan) sembahyang, mereka menjadikannya buah ejekan dan permainan. Yang demikian itu adalah karena mereka benar-benar kaum yang tidak mau mempergunakan akal.<?php break;}
case 59:{?>Katakanlah: &quot;Hai Ahli kitab, apakah kamu memandang kami salah, hanya lantaran kami beriman kepada Allah, kepada apa yang diturunkan kepada kami dan kepada apa yang diturunkan sebelumnya, sedang kebanyakan di antara kamu benar-benar orang-orang yang fasik?&quot;<?php break;}
case 60:{?>Katakanlah: &quot;Apakah akan aku beritakan kepadamu tentang orang-orang yang lebih buruk pembalasannya dari (orang-orang fasik) itu di sisi Allah, yaitu orang-orang yang dikutuki dan dimurkai Allah, di antara mereka (ada) yang dijadikan kera dan babi dan (orang yang) menyembah thaghut?&quot; Mereka itu lebih buruk tempatnya dan lebih tersesat dari jalan yang lurus.<?php break;}
case 61:{?>Dan apabila orang-orang (Yahudi atau munafik) datang kepadamu, mereka mengatakan: &quot;Kami telah beriman&quot;, padahal mereka datang kepada kamu dengan kekafirannya dan mereka pergi (daripada kamu) dengan kekafirannya (pula); dan Allah lebih mengetahui apa yang mereka sembunyikan.<?php break;}
case 62:{?>Dan kamu akan melihat kebanyakan dari mereka (orang-orang Yahudi) bersegera membuat dosa, permusuhan dan memakan yang haram. Sesungguhnya amat buruk apa yang mereka telah kerjakan itu.<?php break;}
case 63:{?>Mengapa orang-orang alim mereka, pendeta-pendeta mereka tidak melarang mereka mengucapkan perkataan bohong dan memakan yang haram?. Sesungguhnya amat buruk apa yang telah mereka kerjakan itu.<?php break;}
case 64:{?>Orang-orang Yahudi berkata: &quot;Tangan Allah terbelenggu&quot;, sebenarnya tangan merekalah yang dibelenggu dan merekalah yang dilaknat disebabkan apa yang telah mereka katakan itu. (Tidak demikian), tetapi kedua-dua tangan Allah terbuka; Dia menafkahkan sebagaimana Dia kehendaki. Dan Al Qur'an yang diturunkan kepadamu dari Tuhanmu sungguh-sungguh akan menambah kedurhakaan dan kekafiran bagi kebanyakan di antara mereka. Dan Kami telah timbulkan permusuhan dan kebencian di antara mereka sampai hari kiamat. Setiap mereka menyalakan api peperangan, Allah memadamkannya dan mereka berbuat kerusakan di muka bumi dan Allah tidak menyukai orang-orang yang membuat kerusakan.<?php break;}
case 65:{?>Dan sekiranya Ahli Kitab beriman dan bertakwa, tentulah Kami tutup (hapus) kesalahan-kesalahan mereka dan tentulah Kami masukkan mereka ke dalam surga yang penuh kenikmatan.<?php break;}
case 66:{?>Dan sekiranya mereka sungguh-sungguh menjalankan (hukum) Taurat, Injil dan (Al Qur'an) yang diturunkan kepada mereka dari Tuhannya, niscaya mereka akan mendapat makanan dari atas mereka dan dari bawah kaki mereka. Di antara mereka ada golongan yang pertengahan. Dan alangkah buruknya apa yang dikerjakan oleh kebanyakan mereka.<?php break;}
case 67:{?>Hai Rasul, sampaikanlah apa yang di turunkan kepadamu dari Tuhanmu. Dan jika tidak kamu kerjakan (apa yang diperintahkan itu, berarti) kamu tidak menyampaikan amanat-Nya. Allah memelihara kamu dari (gangguan) manusia. Sesungguhnya Allah tidak memberi petunjuk kepada orang-orang yang kafir.<?php break;}
case 68:{?>Katakanlah: &quot;Hai Ahli Kitab, kamu tidak dipandang beragama sedikit pun hingga kamu menegakkan ajaran-ajaran Taurat, Injil dan Al Qur'an yang diturunkan kepadamu dari Tuhanmu&quot;. Sesungguhnya apa yang diturunkan kepadamu (Muhammad) dari Tuhanmu akan menambah kedurhakaan dan kekafiran kepada kebanyakan dari mereka; maka janganlah kamu bersedih hati terhadap orang-orang yang kafir itu.<?php break;}
case 69:{?>Sesungguhnya orang-orang mukmin, orang-orang Yahudi, Shabiin dan orang-orang Nasrani, siapa saja (di antara mereka) yang benar-benar beriman kepada Allah, hari kemudian dan beramal saleh, maka tidak ada kekhawatiran terhadap mereka dan tidak (pula) mereka bersedih hati.<?php break;}
case 70:{?>Sesungguhnya Kami telah mengambil perjanjian dari Bani Israel, dan telah Kami utus kepada mereka rasul-rasul. Tetapi setiap datang seorang rasul kepada mereka dengan membawa apa yang tidak diingini oleh hawa nafsu mereka, (maka) sebagian dari rasul-rasul itu mereka dustakan dan sebagian yang lain mereka bunuh.<?php break;}
case 71:{?>Dan mereka mengira bahwa tidak akan terjadi suatu bencana pun (terhadap mereka dengan membunuh nabi-nabi itu), maka (karena itu) mereka menjadi buta dan pekak, kemudian Allah menerima tobat mereka, kemudian kebanyakan dari mereka buta dan tuli (lagi). Dan Allah Maha Melihat apa yang mereka kerjakan.<?php break;}
case 72:{?>Sesungguhnya telah kafirlah orang-orang yang berkata: &quot;Sesungguhnya Allah adalah Al Masih putra Maryam&quot;, padahal Al Masih (sendiri) berkata: &quot;Hai Bani Israel, sembahlah Allah Tuhanku dan Tuhanmu&quot; Sesungguhnya orang yang mempersekutukan (sesuatu dengan) Allah, maka pasti Allah mengharamkan kepadanya surga, dan tempatnya ialah neraka, tidaklah ada bagi orang-orang lalim itu seorang penolong pun.<?php break;}
case 73:{?>Sesungguhnya kafirlah orang-orang yang mengatakan: &quot;Bahwasanya Allah salah satu dari yang tiga&quot;, padahal sekali-kali tidak ada Tuhan (yang berhak disembah) selain Tuhan Yang Esa. Jika mereka tidak berhenti dari apa yang mereka katakan itu, pasti orang-orang yang kafir di antara mereka akan ditimpa siksaan yang pedih.<?php break;}
case 74:{?>Maka mengapa mereka tidak bertobat kepada Allah dan memohon ampun kepada-Nya? Dan Allah Maha Pengampun lagi Maha Penyayang.<?php break;}
case 75:{?>Al Masih putra Maryam hanyalah seorang Rasul yang sesungguhnya telah berlalu sebelumnya beberapa rasul, dan ibunya seorang yang sangat benar, kedua-duanya biasa memakan makanan. Perhatikan bagaimana Kami menjelaskan kepada mereka (ahli Kitab) tanda-tanda kekuasaan (Kami), kemudian perhatikanlah bagaimana mereka berpaling (dari memperhatikan ayat-ayat Kami itu).<?php break;}
case 76:{?>Katakanlah: &quot;Mengapa kamu menyembah selain daripada Allah, sesuatu yang tidak dapat memberi mudarat kepadamu dan tidak (pula) memberi manfaat?&quot; Dan Allah-lah Yang Maha Mendengar lagi Maha Mengetahui.<?php break;}
case 77:{?>Katakanlah: &quot;Hai Ahli Kitab, janganlah kamu berlebih-lebihan (melampaui batas) dengan cara tidak benar dalam agamamu. Dan janganlah kamu mengikuti hawa nafsu orang-orang yang telah sesat dahulunya (sebelum kedatangan Muhammad) dan mereka telah menyesatkan kebanyakan (manusia), dan mereka tersesat dari jalan yang lurus.&quot;<?php break;}
case 78:{?>Telah dilaknati orang-orang kafir dari Bani Israel dengan lisan Daud dan Isa putra Maryam. Yang demikian itu, disebabkan mereka durhaka dan selalu melampaui batas.<?php break;}
case 79:{?>Mereka satu sama lain selalu tidak melarang tindakan mungkar yang mereka perbuat. Sesungguhnya amat buruklah apa yang selalu mereka perbuat itu.<?php break;}
case 80:{?>Kamu melihat kebanyakan dari mereka tolong-menolong dengan orang-orang yang kafir (musyrik). Sesungguhnya amat buruklah apa yang mereka sediakan untuk diri mereka, yaitu kemurkaan Allah kepada mereka; dan mereka akan kekal dalam siksaan.<?php break;}
case 81:{?>Sekiranya mereka beriman kepada Allah, kepada Nabi (Musa) dan kepada apa yang diturunkan kepadanya (Nabi), niscaya mereka tidak akan mengambil orang-orang musyrikin itu menjadi penolong-penolong, tapi kebanyakan dari mereka adalah orang-orang yang fasik.<?php break;}
case 82:{?>Sesungguhnya kamu dapati orang-orang yang paling keras permusuhannya terhadap orang-orang yang beriman ialah orang-orang Yahudi dan orang-orang musyrik. Dan sesungguhnya kamu dapati yang paling dekat persabahatannya dengan orang-orang yang beriman ialah orang-orang yang berkata: &quot;Sesungguhnya kami ini orang Nasrani&quot;. Yang demikian itu disebabkan karena di antara mereka itu (orang-orang Nasrani) terdapat pendeta-pendeta dan rahib-rahib, (juga) karena sesungguhnya mereka tidak menyombongkan diri.<?php break;}
case 83:{?>Dan apabila mereka mendengarkan apa yang diturunkan kepada Rasul (Muhammad), kamu melihat mata mereka mencucurkan air mata disebabkan kebenaran (Al Qur'an) yang telah mereka ketahui (dari kitab-kitab mereka sendiri); seraya berkata: &quot;Ya Tuhan kami, kami telah beriman, maka catatlah kami bersama orang-orang yang menjadi saksi (atas kebenaran Al Qur'an dan kenabian Muhammad saw.)<?php break;}
case 84:{?>Mengapa kami tidak akan beriman kepada Allah dan kepada kebenaran yang datang kepada kami, padahal kami sangat ingin agar Tuhan kami memasukkan kami ke dalam golongan orang-orang yang saleh?&quot;<?php break;}
case 85:{?>Maka Allah memberi mereka pahala terhadap perkataan yang mereka ucapkan, (yaitu) surga yang mengalir sungai-sungai di dalamnya, sedang mereka kekal di dalamnya. Dan itulah balasan (bagi) orang-orang yang berbuat kebaikan (yang ikhlas keimanannya).<?php break;}
case 86:{?>Dan orang-orang kafir serta mendustakan ayat-ayat Kami, mereka itulah penghuni neraka.<?php break;}
case 87:{?>Hai orang-orang yang beriman, janganlah kamu haramkan apa-apa yang baik yang telah Allah halalkan bagi kamu, dan janganlah kamu melampaui batas. Sesungguhnya Allah tidak menyukai orang-orang yang melampaui batas.<?php break;}
case 88:{?>Dan makanlah makanan yang halal lagi baik dari apa yang Allah telah rezekikan kepadamu, dan bertakwalah kepada Allah yang kamu beriman kepada-Nya.<?php break;}
case 89:{?>Allah tidak menghukum kamu disebabkan sumpah-sumpahmu yang tidak dimaksud (untuk bersumpah), tetapi Dia menghukum kamu disebabkan sumpah-sumpah yang kamu sengaja, maka kafarat (melanggar) sumpah itu, ialah memberi makan sepuluh orang miskin, yaitu dari makanan yang biasa kamu berikan kepada keluargamu, atau memberi pakaian kepada mereka atau memerdekakan seorang budak. Barang siapa tidak sanggup melakukan yang demikian, maka kafaratnya puasa selama tiga hari. Yang demikian itu adalah kafarat sumpah-sumpahmu bila kamu bersumpah (dan kamu langgar). Dan jagalah sumpahmu. Demikianlah Allah menerangkan kepadamu hukum-hukum-Nya agar kamu bersyukur (kepada-Nya).<?php break;}
case 90:{?>Hai orang-orang yang beriman, sesungguhnya (meminum) khamar, berjudi, (berkorban untuk) berhala, mengundi nasib dengan panah, adalah perbuatan keji termasuk perbuatan setan. Maka jauhilah perbuatan-perbuatan itu agar kamu mendapat keberuntungan.<?php break;}
case 91:{?>Sesungguhnya setan itu bermaksud hendak menimbulkan permusuhan dan kebencian di antara kamu lantaran (meminum) khamar dan berjudi itu, dan menghalangi kamu dari mengingat Allah dan sembahyang; maka berhentilah kamu (dari mengerjakan pekerjaan itu).<?php break;}
case 92:{?>Dan taatlah kamu kepada Allah dan taatlah kamu kepada Rasul (Nya) dan berhati-hatilah. Jika kamu berpaling, maka ketahuilah bahwa sesungguhnya kewajiban Rasul Kami, hanyalah menyampaikan (amanat Allah) dengan terang.<?php break;}
case 93:{?>Tidak ada dosa bagi orang-orang yang beriman dan mengerjakan amalan yang saleh karena memakan makanan yang telah mereka makan dahulu, apabila mereka bertakwa serta beriman, dan mengerjakan amalan-amalan yang saleh, kemudian mereka tetap bertakwa dan beriman, kemudian mereka (tetap juga) bertakwa dan berbuat kebajikan. Dan Allah menyukai orang-orang yang berbuat kebajikan.<?php break;}
case 94:{?>Hai orang-orang yang beriman, sesungguhnya Allah akan menguji kamu dengan sesuatu dari binatang buruan yang mudah didapat oleh tangan dan tombakmu supaya Allah mengetahui orang yang takut kepada-Nya, biar pun ia tidak dapat melihat-Nya. Barang siapa yang melanggar batas sesudah itu, maka baginya azab yang pedih.<?php break;}
case 95:{?>Hai orang-orang yang beriman, janganlah kamu membunuh binatang buruan, ketika kamu sedang ihram. Barang siapa di antara kamu membunuhnya dengan sengaja, maka dendanya ialah mengganti dengan binatang ternak seimbang dengan buruan yang dibunuhnya, menurut putusan dua orang yang adil di antara kamu, sebagai had-ya yang di bawa sampai ke Kakbah, atau (dendanya) membayar kafarat dengan memberi makan orang-orang miskin, atau berpuasa seimbang dengan makanan yang dikeluarkan itu, supaya dia merasakan akibat yang buruk dari perbuatannya. Allah telah memaafkan apa yang telah lalu. Dan barang siapa yang kembali mengerjakannya, niscaya Allah akan menyiksanya. Allah Maha Kuasa lagi mempunyai (kekuasaan untuk) menyiksa.<?php break;}
case 96:{?>Dihalalkan bagimu binatang buruan laut dan makanan (yang berasal) dari laut sebagai makanan yang lezat bagimu, dan bagi orang-orang yang dalam perjalanan; dan diharamkan atasmu (menangkap) binatang buruan darat, selama kamu dalam ihram. Dan bertakwalah kepada Allah yang kepada-Nya lah kamu akan dikumpulkan.<?php break;}
case 97:{?>Allah telah menjadikan Kakbah, rumah suci itu sebagai pusat (peribadatan dan urusan dunia) bagi manusia, dan (demikian pula) bulan Haram, had-ya, qalaid. (Allah menjadikan yang) demikian itu agar kamu tahu, bahwa sesungguhnya Allah mengetahui apa yang ada di langit dan apa yang ada di bumi dan bahwa sesungguhnya Allah Maha Mengetahui segala sesuatu.<?php break;}
case 98:{?>Ketahuilah, bahwa Sesungguhnya Allah amat berat siksa-Nya dan bahwa sesungguhnya Allah Maha Pengampun lagi Maha Penyayang.<?php break;}
case 99:{?>Kewajiban Rasul tidak lain hanyalah menyampaikan, dan Allah mengetahui apa yang kamu lahirkan dan apa yang kamu sembunyikan.<?php break;}
case 100:{?>Katakanlah: &quot;Tidak sama yang buruk dengan yang baik, meskipun banyaknya yang buruk itu menarik hatimu, maka bertakwalah kepada Allah hai orang-orang berakal, agar kamu mendapat keberuntungan.&quot;<?php break;}
case 101:{?>Hai orang-orang yang beriman, janganlah kamu menanyakan (kepada Nabimu) hal-hal yang jika diterangkan kepadamu, niscaya menyusahkan kamu dan jika kamu menanyakan di waktu Al Qur'an itu sedang diturunkan, niscaya akan diterangkan kepadamu. Allah memaafkan (kamu) tentang hal-hal itu. Allah Maha Pengampun lagi Maha Penyantun.<?php break;}
case 102:{?>Sesungguhnya telah ada segolongan manusia sebelum kamu menanyakan hal-hal yang serupa itu (kepada Nabi mereka), kemudian mereka tidak percaya kepadanya.<?php break;}
case 103:{?>Allah sekali-kali tidak pernah mensyariatkan adanya bahiirah, saaibah, washiilah dan haam. Akan tetapi orang-orang kafir membuat-buat kedustaan terhadap Allah, dan kebanyakan mereka tidak mengerti.<?php break;}
case 104:{?>Apabila dikatakan kepada mereka: &quot;Marilah mengikuti apa yang diturunkan Allah dan mengikuti Rasul&quot;. Mereka menjawab: &quot;Cukuplah untuk kami apa yang kami dapati bapak-bapak kami mengerjakannya&quot;. Dan apakah mereka akan mengikuti juga nenek moyang mereka walaupun nenek moyang mereka itu tidak mengetahui apa-apa dan tidak (pula) mendapat petunjuk?<?php break;}
case 105:{?>Hai orang-orang yang beriman, jagalah dirimu; tiadalah orang yang sesat itu akan memberi mudarat kepadamu apabila kamu telah mendapat petunjuk. Hanya kepada Allah kamu kembali semuanya, maka Dia akan menerangkan kepadamu apa yang telah kamu kerjakan.<?php break;}
case 106:{?>Hai orang-orang yang beriman, apabila salah seorang kamu menghadapi kematian, sedang dia akan berwasiat, maka hendaklah (wasiat itu) disaksikan oleh dua orang yang adil di antara kamu, atau dua orang yang berlainan agama dengan kamu, jika kamu dalam perjalanan di muka bumi lalu kamu ditimpa bahaya kematian. Kamu tahan kedua saksi itu sesudah sembahyang (untuk bersumpah), lalu mereka keduanya bersumpah dengan nama Allah jika kamu ragu-ragu: &quot;(Demi Allah) kami tidak akan menukar sumpah ini dengan harga yang sedikit (untuk kepentingan seseorang), walaupun dia karib kerabat, dan tidak (pula) kami menyembunyikan persaksian Allah; sesungguhnya kami kalau demikian tentulah termasuk orang-orang yang berdosa&quot;.<?php break;}
case 107:{?>Jika diketahui bahwa kedua (saksi itu) memperbuat dosa, maka dua orang yang lain di antara ahli waris yang berhak yang lebih dekat kepada orang yang meninggal (memajukan tuntutan) untuk menggantikannya, lalu keduanya bersumpah dengan nama Allah: &quot;Sesungguhnya persaksian kami lebih layak diterima daripada persaksian kedua saksi itu, dan kami tidak melanggar batas, sesungguhnya kami kalau demikian tentulah termasuk orang-orang yang menganiaya diri sendiri&quot;.<?php break;}
case 108:{?>Itu lebih dekat untuk (menjadikan para saksi) mengemukakan persaksiannya menurut apa yang sebenarnya, dan (lebih dekat untuk menjadikan mereka) merasa takut akan dikembalikan sumpahnya (kepada ahli waris) sesudah mereka bersumpah. Dan bertakwalah kepada Allah dan dengarkanlah (perintah-Nya). Allah tidak memberi petunjuk kepada orang-orang yang fasik.<?php break;}
case 109:{?>(Ingatlah), hari di waktu Allah mengumpulkan para rasul, lalu Allah bertanya (kepada mereka): &quot;Apa jawaban kaummu terhadap (seruan) mu?&quot; Para rasul menjawab: &quot;Tidak ada pengetahuan kami (tentang itu); sesungguhnya Engkau-lah yang mengetahui perkara yang gaib&quot;.<?php break;}
case 110:{?>(Ingatlah), ketika Allah mengatakan: &quot;Hai Isa putra Maryam, ingatlah nikmat-Ku kepadamu dan kepada ibumu di waktu Aku menguatkan kamu dengan ruhul qudus. Kamu dapat berbicara dengan manusia di waktu masih dalam buaian dan sesudah dewasa; dan (ingatlah) di waktu Aku mengajar kamu menulis, hikmah, Taurat dan Injil, dan (ingatlah pula) di waktu kamu membentuk dari tanah (suatu bentuk) yang berupa burung dengan izin-Ku, kemudian kamu meniup padanya, lalu bentuk itu menjadi burung (yang sebenarnya) dengan seizin-Ku. Dan (ingatlah), waktu kamu menyembuhkan orang yang buta sejak dalam kandungan ibu dan orang yang berpenyakit sopak dengan seizin-Ku, dan (ingatlah) di waktu kamu mengeluarkan orang mati dari kubur (menjadi hidup) dengan seizin-Ku, dan (ingatlah) di waktu Aku menghalangi Bani Israel (dari keinginan mereka membunuh kamu) di kala kamu mengemukakan kepada mereka keterangan-keterangan yang nyata, lalu orang-orang kafir di antara mereka berkata: &quot;Ini tidak lain melainkan sihir yang nyata.&quot;<?php break;}
case 111:{?>Dan (ingatlah), ketika Aku ilhamkan kepada pengikut Isa yang setia: &quot;Berimanlah kamu kepada-Ku dan kepada rasul-Ku&quot;. Mereka menjawab: &quot;Kami telah beriman dan saksikanlah (wahai rasul) bahwa sesungguhnya kami adalah orang-orang yang patuh (kepada seruanmu)&quot;.<?php break;}
case 112:{?>(Ingatlah), ketika pengikut-pengikut Isa berkata: &quot;Hai Isa putra Maryam, bersediakah Tuhanmu menurunkan hidangan dari langit kepada kami?&quot; Isa menjawab: &quot;Bertakwalah kepada Allah jika betul-betul kamu orang yang beriman&quot;.<?php break;}
case 113:{?>Mereka berkata; &quot;kami ingin memakan hidangan itu dan supaya tenteram hati kami dan supaya kami yakin bahwa kamu telah berkata benar kepada kami, dan kami menjadi orang-orang yang menyaksikan hidangan itu&quot;.<?php break;}
case 114:{?>Isa putra Maryam berdoa: &quot;Ya Tuhan kami, turunkanlah kiranya kepada kami suatu hidangan dari langit (yang hari turunnya) akan menjadi hari raya bagi kami yaitu bagi orang-orang yang bersama kami dan yang datang sesudah kami, dan menjadi tanda bagi kekuasaan Engkau; beri rezekilah kami, dan Engkaulah Pemberi rezeki Yang Paling Utama&quot;.<?php break;}
case 115:{?>Allah berfirman: &quot;Sesungguhnya Aku akan menurunkan hidangan itu kepadamu, barang siapa yang kafir di antaramu sesudah (turun hidangan itu), maka sesungguhnya Aku akan menyiksanya dengan siksaan yang tidak pernah Aku timpakan kepada seorang pun di antara umat manusia&quot;.<?php break;}
case 116:{?>Dan (ingatlah) ketika Allah berfirman: &quot;Hai Isa putra Maryam, adakah kamu mengatakan kepada manusia: &quot;Jadikanlah aku dan ibuku dua orang tuhan selain Allah?&quot; Isa menjawab: &quot;Maha Suci Engkau, tidaklah patut bagiku mengatakan apa yang bukan hakku (mengatakannya). Jika aku pernah mengatakannya maka tentulah Engkau telah mengetahuinya. Engkau mengetahui apa yang ada pada diriku dan aku tidak mengetahui apa yang ada pada diri Engkau. Sesungguhnya Engkau Maha Mengetahui perkara yang gaib-gaib&quot;.<?php break;}
case 117:{?>Aku tidak pernah mengatakan kepada mereka kecuali apa yang Engkau perintahkan kepadaku (mengatakan) nya yaitu: &quot;Sembahlah Allah, Tuhanku dan Tuhanmu&quot;, dan adalah aku menjadi saksi terhadap mereka, selama aku berada di antara mereka. Maka setelah Engkau wafatkan (angkat) aku, Engkau-lah yang mengawasi mereka. Dan Engkau adalah Maha Menyaksikan atas segala sesuatu.<?php break;}
case 118:{?>Jika Engkau menyiksa mereka, maka sesungguhnya mereka adalah hamba-hamba Engkau, dan jika Engkau mengampuni mereka, maka sesungguhnya Engkaulah Yang Maha Perkasa lagi Maha Bijaksana.<?php break;}
case 119:{?>Allah berfirman: &quot;Ini adalah suatu hari yang bermanfaat bagi orang-orang yang benar kebenaran mereka. Bagi mereka surga yang dibawahnya mengalir sungai-sungai; mereka kekal di dalamnya selama-lamanya; Allah rida terhadap mereka dan mereka pun rida terhadap-Nya. Itulah keberuntungan yang paling besar&quot;.<?php break;}
case 120:{?>Kepunyaan Allah-lah kerajaan langit dan bumi dan apa yang ada di dalamnya; dan Dia Maha Kuasa atas segala sesuatu.<?php break;}
}?>