<?php 
switch($verse){
case 1:{?>Bertasbih kepada Allah apa yang ada di langit dan apa yang ada di bumi dan Dia-lah Yang Maha Perkasa lagi Maha Bijaksana.<?php break;}
case 2:{?>Dia-lah yang mengeluarkan orang-orang kafir di antara ahli Kitab dari kampung-kampung mereka pada saat pengusiran kali yang pertama. Kamu tiada menyangka, bahwa mereka akan keluar dan mereka pun yakin, bahwa benteng-benteng mereka akan dapat mempertahankan mereka dari (siksaan) Allah; maka Allah mendatangkan kepada mereka (hukuman) dari arah yang tidak mereka sangka-sangka. Dan Allah mencampakkan ketakutan ke dalam hati mereka; mereka memusnahkan rumah-rumah mereka dengan tangan mereka sendiri dan tangan orang-orang yang beriman. Maka ambillah (kejadian itu) untuk menjadi pelajaran, hai orang-orang yang mempunyai pandangan.<?php break;}
case 3:{?>Dan jika tidaklah karena Allah telah menetapkan pengusiran terhadap mereka benar-benar Allah mengazab mereka di dunia. Dan bagi mereka di akhirat azab neraka.<?php break;}
case 4:{?>Yang demikian itu adalah karena sesungguhnya mereka menentang Allah dan Rasul-Nya. Barang siapa menentang Allah, maka sesungguhnya Allah sangat keras hukuman-Nya.<?php break;}
case 5:{?>Apa saja yang kamu tebang dari pohon kurma (milik orang-orang kafir) atau yang kamu biarkan (tumbuh) berdiri di atas pokoknya, maka (semua itu) adalah dengan izin Allah; dan karena Dia hendak memberikan kehinaan kepada orang-orang fasik.<?php break;}
case 6:{?>Dan apa saja harta rampasan (fai-i) yang diberikan Allah kepada Rasul-Nya (dari harta benda) mereka, maka untuk mendapatkan itu kamu tidak mengerahkan seekor kuda pun dan (tidak pula) seekor unta pun, tetapi Allah yang memberikan kekuasaan kepada Rasul-Nya terhadap siapa yang dikehendaki-Nya. Dan Allah Maha Kuasa atas segala sesuatu.<?php break;}
case 7:{?>Apa saja harta rampasan (fai-i) yang diberikan Allah kepada Rasul-Nya yang berasal dari penduduk kota-kota maka adalah untuk Allah, Rasul, kerabat Rasul, anak-anak yatim, orang-orang miskin dan orang-orang yang dalam perjalanan, supaya harta itu jangan hanya beredar di antara orang-orang kaya saja di antara kamu. Apa yang diberikan Rasul kepadamu maka terimalah dia. Dan apa yang dilarangnya bagimu maka tinggalkanlah; dan bertakwalah kepada Allah. Sesungguhnya Allah sangat keras hukuman-Nya.<?php break;}
case 8:{?>(Juga) bagi para fakir yang berhijrah yang diusir dari kampung halaman dan dari harta benda mereka (karena) mencari karunia dari Allah dan keridaan (Nya) dan mereka menolong Allah dan Rasul-Nya. Mereka itulah orang-orang yang benar.<?php break;}
case 9:{?>Dan orang-orang yang telah menempati Kota Madinah dan telah beriman (Ansar) sebelum (kedatangan) mereka (Muhajirin), mereka mencintai orang yang berhijrah kepada mereka. Dan mereka tiada menaruh keinginan dalam hati mereka terhadap apa-apa yang diberikan kepada mereka (orang Muhajirin); dan mereka mengutamakan (orang-orang Muhajirin), atas diri mereka sendiri. Sekalipun mereka memerlukan (apa yang mereka berikan itu). Dan siapa yang dipelihara dari kekikiran dirinya, mereka itulah orang-orang yang beruntung.<?php break;}
case 10:{?>Dan orang-orang yang datang sesudah mereka (Muhajirin dan Ansar), mereka berdoa: &quot;Ya Tuhan kami, beri ampunlah kami dan saudara-saudara kami yang telah beriman lebih dahulu dari kami, dan janganlah Engkau membiarkan kedengkian dalam hati kami terhadap orang-orang yang beriman; Ya Tuhan kami, sesungguhnya Engkau Maha Penyantun lagi Maha Penyayang&quot;.<?php break;}
case 11:{?>Apakah kamu tiada memperhatikan orang-orang munafik yang berkata kepada saudara-saudara mereka yang kafir di antara ahli Kitab: &quot;Sesungguhnya jika kamu diusir niscaya kami pun akan keluar bersama kamu; dan kami selama-lamanya tidak akan patuh kepada siapa pun untuk (menyusahkan) kamu, dan jika kamu diperangi pasti kami akan membantu kamu&quot;. Dan Allah menyaksikan, bahwa sesungguhnya mereka benar-benar pendusta.<?php break;}
case 12:{?>Sesungguhnya jika mereka diusir, orang-orang munafik itu tiada akan keluar bersama mereka, dan sesungguhnya jika mereka diperangi; niscaya mereka tiada akan menolongnya; sesungguhnya jika mereka menolongnya niscaya mereka akan berpaling lari ke belakang, kemudian mereka tiada akan mendapat pertolongan.<?php break;}
case 13:{?>Sesungguhnya kamu dalam hati mereka lebih ditakuti daripada Allah. Yang demikian itu karena mereka adalah kaum yang tiada mengerti.<?php break;}
case 14:{?>Mereka tiada akan memerangi kamu dalam keadaan bersatu padu, kecuali dalam kampung-kampung yang berbenteng atau di balik tembok. Permusuhan antara sesama mereka adalah sangat hebat. Kamu kira mereka itu bersatu sedang hati mereka berpecah belah. Yang demikian itu karena sesungguhnya mereka adalah kaum yang tiada mengerti.<?php break;}
case 15:{?>(Mereka adalah) seperti orang-orang Yahudi yang belum lama sebelum mereka telah merasai akibat buruk dari perbuatan mereka dan bagi mereka azab yang pedih.<?php break;}
case 16:{?>(Bujukan orang-orang munafik itu adalah) seperti (bujukan) setan ketika dia berkata kepada manusia: &quot;Kafirlah kamu&quot;, maka tatkala manusia itu telah kafir ia berkata: &quot;Sesungguhnya aku berlepas diri dari kamu karena sesungguhnya aku takut kepada Allah Tuhan semesta alam&quot;.<?php break;}
case 17:{?>Maka adalah kesudahan keduanya, bahwa sesungguhnya keduanya (masuk) ke dalam neraka, mereka kekal di dalamnya. Demikianlah balasan orang-orang yang lalim.<?php break;}
case 18:{?>Hai orang-orang yang beriman, bertakwalah kepada Allah dan hendaklah setiap diri memperhatikan apa yang telah diperbuatnya untuk hari esok (akhirat), dan bertakwalah kepada Allah, sesungguhnya Allah Maha Mengetahui apa yang kamu kerjakan.<?php break;}
case 19:{?>Dan janganlah kamu seperti orang-orang yang lupa kepada Allah, lalu Allah menjadikan mereka lupa kepada diri mereka sendiri. Mereka itulah orang-orang yang fasik.<?php break;}
case 20:{?>Tiada sama penghuni-penghuni neraka dengan penghuni-penghuni surga; penghuni-penghuni surga itulah orang-orang yang beruntung.<?php break;}
case 21:{?>Kalau sekiranya Kami menurunkan Al Qur'an ini kepada sebuah gunung, pasti kamu akan melihatnya tunduk terpecah belah disebabkan takut kepada Allah. Dan perumpamaan-perumpamaan itu Kami buat untuk manusia supaya mereka berpikir.<?php break;}
case 22:{?>Dia-lah Allah Yang tiada Tuhan (yang berhak disembah) selain Dia, Yang Mengetahui yang gaib dan yang nyata, Dia-lah Yang Maha Pemurah lagi Maha Penyayang.<?php break;}
case 23:{?>Dia-lah Allah Yang tiada Tuhan (yang berhak disembah) selain Dia, Raja, Yang Maha Suci, Yang Maha Sejahtera, Yang Mengaruniakan keamanan, Yang Maha Memelihara, Yang Maha Perkasa, Yang Maha Kuasa, Yang Memiliki segala keagungan, Maha Suci, Allah dari apa yang mereka persekutukan.<?php break;}
case 24:{?>Dia-lah Allah Yang Menciptakan, Yang Mengadakan, Yang Membentuk Rupa, Yang Mempunyai Nama-Nama Yang Paling baik. Bertasbih kepada-Nya apa yang ada di langit dan di bumi. Dan Dia-lah Yang Maha Perkasa lagi Maha Bijaksana.<?php break;}
}?>