<?php 
switch($verse){
case 1:{?>Segala puji bagi Allah Yang telah menciptakan langit dan bumi, dan mengadakan gelap dan terang, namun orang-orang yang kafir mempersekutukan (sesuatu) dengan Tuhan mereka.<?php break;}
case 2:{?>Dialah Yang menciptakan kamu dari tanah, sesudah itu ditentukannya ajal (kematianmu), dan ada lagi suatu ajal yang ditentukan (untuk berbangkit) yang ada pada sisi-Nya (yang Dia sendirilah mengetahuinya), kemudian kamu masih ragu-ragu (tentang berbangkit itu).<?php break;}
case 3:{?>Dan Dialah Allah (Yang disembah), baik di langit maupun di bumi; Dia mengetahui apa yang kamu rahasiakan dan apa yang kamu lahirkan dan mengetahui (pula) apa yang kamu usahakan.<?php break;}
case 4:{?>Dan tak ada suatu ayat pun dari ayat-ayat Tuhan sampai kepada mereka, melainkan mereka selalu berpaling daripadanya (mendustakannya).<?php break;}
case 5:{?>Sesungguhnya mereka telah mendustakan yang hak (Al Qur'an) tatkala sampai kepada mereka, maka kelak akan sampai kepada mereka (kenyataan dari) berita-berita yang selalu mereka perolok-olokkan.<?php break;}
case 6:{?>Apakah mereka tidak memperhatikan berapa banyaknya generasi-generasi yang telah Kami binasakan sebelum mereka, padahal (generasi itu), telah Kami teguhkan kedudukan mereka di muka bumi, yaitu keteguhan yang belum pernah Kami berikan kepadamu, dan Kami curahkan hujan yang lebat atas mereka dan Kami jadikan sungai-sungai mengalir di bawah mereka, kemudian Kami binasakan mereka karena dosa mereka sendiri, dan kami ciptakan sesudah mereka generasi yang lain.<?php break;}
case 7:{?>Dan kalau Kami turunkan kepadamu tulisan di atas kertas, lalu mereka dapat memegangnya dengan tangan mereka sendiri, tentulah orang-orang yang kafir itu berkata: &quot;Ini tidak lain hanyalah sihir yang nyata&quot;.<?php break;}
case 8:{?>Dan mereka berkata: &quot;Mengapa tidak diturunkan kepadanya (Muhammad) seorang malaikat?&quot; dan kalau Kami turunkan (kepadanya) seorang malaikat, tentu selesailah urusan itu, kemudian mereka tidak diberi tangguh (sedikit pun).<?php break;}
case 9:{?>Dan kalau Kami jadikan rasul itu (dari) malaikat, tentulah Kami jadikan dia berupa laki-laki dan (jika Kami jadikan dia berupa laki-Iaki), Kami pun akan jadikan mereka tetap ragu sebagaimana kini mereka ragu.<?php break;}
case 10:{?>Dan sungguh telah diperolok-olokkan beberapa rasul sebelum kamu, maka turunlah kepada orang-orang yang mencemoohkan di antara mereka balasan ('azab) olok-olokan mereka.<?php break;}
case 11:{?>Katakanlah: &quot;Berjalanlah di muka bumi, kemudian perhatikanlah bagaimana kesudahan orang-orang yang mendustakan itu&quot;.<?php break;}
case 12:{?>Katakanlah: &quot;Kepunyaan siapakah apa yang ada di langit dan di bumi?&quot; Katakanlah: &quot;Kepunyaan Allah&quot;. Dia telah menetapkan atas diri-Nya kasih sayang. Dia sungguh-sungguh akan menghimpun kamu pada hari kiamat yang tidak ada keraguan terhadapnya. Orang-orang yang merugikan dirinya, mereka itu tidak beriman.<?php break;}
case 13:{?>Dan kepunyaan Allah-lah segala yang ada pada malam dan siang hari. Dan Dialah Yang Maha Mendengar lagi Maha Mengetahui.<?php break;}
case 14:{?>Katakanlah: &quot;Apakah akan aku jadikan pelindung selain dari Allah yang menjadikan langit dan bumi, padahal Dia memberi makan dan tidak diberi makan?&quot; Katakanlah: &quot;Sesungguhnya aku diperintah supaya aku menjadi orang yang pertama sekali menyerah diri (kepada Allah), dan jangan sekali-kali kamu masuk golongan orang-orang musyrik.&quot;<?php break;}
case 15:{?>Katakanlah: &quot;Sesungguhnya aku takut akan azab hari yang besar (hari kiamat), jika aku mendurhakai Tuhanku.&quot;<?php break;}
case 16:{?>Barang siapa yang dijauhkan azab daripadanya pada hari itu, maka sungguh Allah telah memberikan rahmat kepadanya. Dan itulah keberuntungan yang nyata.<?php break;}
case 17:{?>Jika Allah menimpakan suatu kemudaratan kepadamu, maka tidak ada yang menghilangkannya melainkan Dia sendiri. Dan jika Dia mendatangkan kebaikan kepadamu, maka Dia Maha Kuasa atas tiap-tiap sesuatu.<?php break;}
case 18:{?>Dan Dialah yang berkuasa atas sekalian hamba-hamba-Nya. Dan Dialah Yang Maha Bijaksana lagi Maha Mengetahui.<?php break;}
case 19:{?>Katakanlah: &quot;Siapakah yang lebih kuat persaksiannya?&quot; Katakanlah: &quot;Allah. Dia menjadi saksi antara aku dan kamu. Dan Al Qur'an ini diwahyukan kepadaku supaya dengannya aku memberi peringatan kepadamu dan kepada orang-orang yang sampai Al Qur'an (kepadanya). Apakah sesungguhnya kamu mengakui bahwa ada tuhan-tuhan yang lain di samping Allah?&quot; Katakanlah: &quot;Aku tidak mengakui&quot;. Katakanlah: &quot;Sesungguhnya Dia adalah Tuhan Yang Maha Esa dan sesungguhnya aku berlepas diri dari apa yang kamu persekutukan (dengan Allah)&quot;.<?php break;}
case 20:{?>Orang-orang yang telah Kami berikan kitab kepadanya, mereka mengenalnya (Muhammad) seperti mereka mengenal anak-anaknya sendiri. Orang-orang yang merugikan dirinya, mereka itu tidak beriman (kepada Allah).<?php break;}
case 21:{?>Dan siapakah yang lebih aniaya daripada orang yang membuat-buat suatu kedustaan terhadap Allah, atau mendustakan ayat-ayat-Nya? Sesungguhnya orang-orang yang aniaya itu tidak mendapat keberuntungan.<?php break;}
case 22:{?>Dan (ingatlah), hari yang di waktu itu Kami menghimpun mereka semuanya kemudian Kami berkata kepada orang-orang musyrik: &quot;Di manakah sembahan-sembahan kamu yang dahulu kamu katakan (sekutu-sekutu Kami)?&quot;<?php break;}
case 23:{?>Kemudian tiadalah fitnah mereka, kecuali mengatakan: &quot;Demi Allah, Tuhan kami, tiadalah kami mempersekutukan Allah&quot;.<?php break;}
case 24:{?>Lihatlah, bagaimana mereka telah berdusta terhadap diri mereka sendiri dan hilanglah daripada mereka sembahan-sembahan yang dahulu mereka ada-adakan.<?php break;}
case 25:{?>Dan di antara mereka ada orang yang mendengarkan (bacaan) mu, padahal Kami telah meletakkan tutupan di atas hati mereka (sehingga mereka tidak) memahaminya dan (Kami letakkan) sumbatan di telinganya. Dan jika pun mereka melihat segala tanda (kebenaran), mereka tetap tidak mau beriman kepadanya. Sehingga apabila mereka datang kepadamu untuk membantahmu, orang-orang kafir itu berkata: &quot;Al Qur'an ini tidak lain hanyalah dongengan orang-orang dahulu&quot;.<?php break;}
case 26:{?>Mereka melarang (orang lain) mendengarkan Al Qur'an dan mereka sendiri menjauhkan diri daripadanya, dan mereka hanyalah membinasakan diri mereka sendiri, sedang mereka tidak menyadari.<?php break;}
case 27:{?>Dan jika kamu (Muhammad) melihat ketika mereka dihadapkan ke neraka, lalu mereka berkata: &quot;Kiranya kami dikembalikan (ke dunia) dan tidak mendustakan ayat-ayat Tuhan kami, serta menjadi orang-orang yang beriman&quot;, (tentulah kamu melihat suatu peristiwa yang mengharukan).<?php break;}
case 28:{?>Tetapi (sebenarnya) telah nyata bagi mereka kejahatan yang mereka dahulu selalu menyembunyikannya. Sekiranya mereka dikembalikan ke dunia, tentulah mereka kembali kepada apa yang mereka telah dilarang mengerjakannya. Dan sesungguhnya mereka itu adalah pendusta-pendusta belaka.<?php break;}
case 29:{?>Dan tentu mereka akan mengatakan (pula): &quot;Hidup hanyalah kehidupan kita di dunia saja, dan kita sekali-kali tidak akan dibangkitkan&quot;.<?php break;}
case 30:{?>Dan seandainya kamu melihat ketika mereka dihadapkan kepada Tuhannya (tentulah kamu melihat peristiwa yang mengharukan). Berfirman Allah: &quot;Bukankah (kebangkitan) ini benar?&quot; Mereka menjawab: &quot;Sungguh benar, demi Tuhan kami&quot;. Berfirman Allah: &quot;Karena itu rasakanlah azab ini, disebabkan kamu mengingkari (nya)&quot;.<?php break;}
case 31:{?>Sungguh telah rugilah orang-orang yang mendustakan pertemuan mereka dengan Tuhan; sehingga apabila kiamat datang kepada mereka dengan tiba-tiba, mereka berkata: &quot;Alangkah besarnya penyesalan kami terhadap kelalaian kami tentang kiamat itu!&quot;, sambil mereka memikul dosa-dosa di atas punggungnya. Ingatlah, amatlah buruk apa yang mereka pikul itu.<?php break;}
case 32:{?>Dan tiadalah kehidupan dunia ini, selain dari main-main dan senda gurau belaka. Dan sungguh kampung akhirat itu lebih baik bagi orang-orang yang bertakwa. Maka tidakkah kamu memahaminya?<?php break;}
case 33:{?>Sesungguhnya, Kami mengetahui bahwasanya apa yang mereka katakan itu menyedihkan hatimu, (janganlah kamu bersedih hati), karena mereka sebenarnya bukan mendustakan kamu, akan tetapi orang-orang yang zalim itu mengingkari ayat-ayat Allah.<?php break;}
case 34:{?>Dan sesungguhnya telah didustakan (pula) rasul-rasul sebelum kamu, akan tetapi mereka sabar terhadap pendustaan dan penganiayaan (yang dilakukan) terhadap mereka, sampai datang pertolongan Kami kepada mereka. Tak ada seorang pun yang dapat merubah kalimat-kalimat (janji-janji) Allah. Dan sesungguhnya telah datang kepadamu sebahagian dari berita rasul-rasul itu.<?php break;}
case 35:{?>Dan jika perpalingan mereka (darimu) terasa amat berat bagimu, maka jika kamu dapat membuat lobang di bumi atau tangga ke langit lalu kamu dapat mendatangkan mukjizat kepada mereka, (maka buatlah). Kalau Allah menghendaki tentu saja Allah menjadikan mereka semua dalam petunjuk, sebab itu janganlah kamu sekali-kali termasuk orang-orang yang jahil.<?php break;}
case 36:{?>Hanya orang-orang yang mendengar sajalah yang mematuhi (seruan Allah), dan orang-orang yang mati (hatinya), akan dibangkitkan oleh Allah, kemudian kepada-Nya-lah mereka dikembalikan.<?php break;}
case 37:{?>Dan mereka (orang-orang musyrik Mekah) berkata: &quot;Mengapa tidak diturunkan kepadanya (Muhammad) suatu mukjizat dari Tuhannya?&quot; Katakanlah: &quot;Sesungguhnya Allah kuasa menurunkan suatu mukjizat, tetapi kebanyakan mereka tidak mengetahui&quot;.<?php break;}
case 38:{?>Dan tiadalah binatang-binatang yang ada di bumi dan burung-burung yang terbang dengan kedua sayapnya, melainkan umat-umat (juga) seperti kamu. Tiadalah Kami alpakan sesuatu pun di dalam Al Kitab, kemudian kepada Tuhanlah mereka dihimpunkan.<?php break;}
case 39:{?>Dan orang-orang yang mendustakan ayat-ayat Kami adalah pekak, bisu dan berada dalam gelap gulita. Barang siapa yang dikehendaki Allah (kesesatannya), niscaya disesatkan-Nya. Dan barangsiapa yang dikehendaki Allah (untuk diberi-Nya petunjuk), niscaya Dia menjadikannya berada di atas jalan yang lurus.<?php break;}
case 40:{?>Katakanlah: &quot;Terangkanlah kepadaku jika datang siksaan Allah kepadamu, atau datang kepadamu hari kiamat, apakah kamu menyeru (tuhan) selain Allah; jika kamu orang-orang yang benar!&quot;<?php break;}
case 41:{?>(Tidak), tetapi hanya Dialah yang kamu seru, maka Dia menghilangkan bahaya yang karenanya kamu berdoa kepada-Nya, jika Dia menghendaki, dan kamu tinggalkan sembahan-sembahan yang kamu sekutukan (dengan Allah).<?php break;}
case 42:{?>Dan sesungguhnya Kami telah mengutus (rasul-rasul) kepada umat-umat yang sebelum kamu, kemudian Kami siksa mereka dengan (menimpakan) kesengsaraan dan kemelaratan, supaya mereka bermohon (kepada Allah) dengan tunduk merendahkan diri.<?php break;}
case 43:{?>Maka mengapa mereka tidak memohon (kepada Allah) dengan tunduk merendahkan diri ketika datang siksaan Kami kepada mereka, bahkan hati mereka telah menjadi keras dan setan pun menampakkan kepada mereka kebagusan apa yang selalu mereka kerjakan.<?php break;}
case 44:{?>Maka tatkala mereka melupakan peringatan yang telah diberikan kepada mereka, Kami-pun membukakan semua pintu-pintu kesenangan untuk mereka; sehingga apabila mereka bergembira dengan apa yang telah diberikan kepada mereka, Kami siksa mereka dengan sekonyong-konyong, maka ketika itu mereka terdiam berputus asa.<?php break;}
case 45:{?>Maka orang-orang yang lalim itu dimusnahkan sampai ke akar-akarnya. Segala puji bagi Allah, Tuhan semesta alam.<?php break;}
case 46:{?>Katakanlah: &quot;Terangkanlah kepadaku jika Allah mencabut pendengaran dan penglihatan serta menutup hatimu, siapakah tuhan selain Allah yang kuasa mengembalikannya kepadamu?&quot; Perhatikanlah, bagaimana Kami berkali-kali memperlihatkan tanda-tanda kebesaran (Kami), kemudian mereka tetap berpaling (juga).<?php break;}
case 47:{?>Katakanlah: &quot;Terangkanlah kepadaku, jika datang siksaan Allah kepadamu dengan sekonyong-konyong atau terang-terangan, maka adakah yang dibinasakan (Allah) selain dari orang-orang yang lalim?<?php break;}
case 48:{?>Dan tidaklah Kami mengutus para rasul itu melainkan untuk memberi kabar gembira dan memberi peringatan. Barang siapa yang beriman dan mengadakan perbaikan, maka tak ada kekhawatiran terhadap mereka dan tidak (pula) mereka bersedih hati.<?php break;}
case 49:{?>Dan orang-orang yang mendustakan ayat-ayat Kami, mereka akan ditimpa siksa disebabkan mereka selalu berbuat fasik.<?php break;}
case 50:{?>Katakanlah: &quot;Aku tidak mengatakan kepadamu, bahwa perbendaharaan Allah ada padaku, dan tidak (pula) aku mengetahui yang gaib dan tidak (pula) aku mengatakan kepadamu bahwa aku seorang malaikat. Aku tidak mengikuti kecuali apa yang diwahyukan kepadaku. Katakanlah: &quot;Apakah sama orang yang buta dengan orang yang melihat?&quot; Maka apakah kamu tidak memikirkan (nya)?<?php break;}
case 51:{?>Dan berilah peringatan dengan apa yang diwahyukan itu kepada orang-orang yang takut akan dihimpunkan kepada Tuhannya (pada hari kiamat), sedang bagi mereka tidak ada seorang pelindung dan pemberi syafaat pun selain daripada Allah, agar mereka bertakwa.<?php break;}
case 52:{?>Dan janganlah kamu mengusir orang-orang yang menyeru Tuhannya di pagi hari dan di petang hari, sedang mereka menghendaki keridaan-Nya. Kamu tidak memikul tanggung jawab sedikit pun terhadap perbuatan mereka dan mereka pun tidak memikul tanggung jawab sedikit pun terhadap perbuatanmu, yang menyebabkan kamu (berhak) mengusir mereka, sehingga kamu termasuk orang-orang yang lalim.<?php break;}
case 53:{?>Dan demikianlah telah Kami uji sebahagian mereka (orang-orang yang kaya) dengan sebahagian mereka (orang-orang miskin), supaya (orang-orang yang kaya itu) berkata: &quot;Orang-orang semacam inikah di antara kita yang diberi anugerah oleh Allah kepada mereka?&quot; (Allah berfirman): &quot;Tidakkah Allah lebih mengetahui tentang orang-orang yang bersyukur (kepada-Nya)?&quot;<?php break;}
case 54:{?>Apabila orang-orang yang beriman kepada ayat-ayat Kami itu datang kepadamu, maka katakanlah: &quot;Salaamun-alaikum. Tuhanmu telah menetapkan atas diri-Nya kasih sayang, (yaitu) bahwasanya barang siapa yang berbuat kejahatan di antara kamu lantaran kejahilan, kemudian ia bertobat setelah mengerjakannya dan mengadakan perbaikan, maka sesungguhnya Allah Maha Pengampun lagi Maha Penyayang.<?php break;}
case 55:{?>Dan demikianlah Kami terangkan ayat-ayat Al Qur'an, (supaya jelas jalan orang-orang yang saleh) dan supaya jelas (pula) jalan orang-orang yang berdosa.<?php break;}
case 56:{?>Katakanlah: &quot;Sesungguhnya aku dilarang menyembah tuhan-tuhan yang kamu sembah selain Allah&quot;. Katakanlah: &quot;Aku tidak akan mengikuti hawa nafsumu, sungguh tersesatlah aku jika berbuat demikian dan tidaklah (pula) aku termasuk orang-orang yang mendapat petunjuk&quot;.<?php break;}
case 57:{?>Katakanlah: &quot;Sesungguhnya aku (berada) di atas hujah yang nyata (Al Qur'an) dari Tuhanku sedang kamu mendustakannya. Bukanlah wewenangku (untuk menurunkan azab) yang kamu tuntut untuk disegerakan kedatangannya. Menetapkan hukum itu hanyalah hak Allah. Dia menerangkan yang sebenarnya dan Dia Pemberi keputusan yang paling baik.<?php break;}
case 58:{?>Katakanlah: &quot;Kalau sekiranya ada padaku apa (azab) yang kamu minta supaya disegerakan kedatangannya, tentu telah diselesaikan Allah urusan yang ada antara aku dan kamu. Dan Allah lebih mengetahui tentang orang-orang yang lalim.<?php break;}
case 59:{?>Dan pada sisi Allah-lah kunci-kunci semua yang gaib; tak ada yang mengetahuinya kecuali Dia sendiri, dan Dia mengetahui apa yang di daratan dan di lautan, dan tiada sehelai daun pun yang gugur melainkan Dia mengetahuinya (pula), dan tidak jatuh sebutir biji pun dalam kegelapan bumi dan tidak sesuatu yang basah atau yang kering, melainkan tertulis dalam kitab yang nyata (Lohmahfuz).<?php break;}
case 60:{?>Dan Dialah yang menidurkan kamu di malam hari dan Dia mengetahui apa yang kamu kerjakan pada siang hari, kemudian Dia membangunkan kamu pada siang hari untuk disempurnakan umur (mu) yang telah ditentukan, kemudian kepada Allah-lah kamu kembali, lalu Dia memberitahukan kepadamu apa yang dahulu kamu kerjakan.<?php break;}
case 61:{?>Dan Dialah yang mempunyai kekuasaan tertinggi di atas semua hamba-Nya, dan diutus-Nya kepadamu malaikat-malaikat penjaga, sehingga apabila datang kematian kepada salah seorang di antara kamu, ia diwafatkan oleh malaikat-malaikat Kami, dan malaikat-malaikat Kami itu tidak melalaikan kewajibannya.<?php break;}
case 62:{?>Kemudian mereka (hamba Allah) dikembalikan kepada Allah, Penguasa mereka yang sebenarnya. Ketahuilah, bahwa segala hukum (pada hari itu) kepunyaan-Nya. Dan Dialah Pembuat perhitungan yang paling cepat.<?php break;}
case 63:{?>Katakanlah: &quot;Siapakah yang dapat menyelamatkan kamu dari bencana di darat dan di laut, yang kamu berdoa kepada-Nya dengan berendah diri dan dengan suara yang lembut (dengan mengatakan): &quot;Sesungguhnya jika Dia menyelamatkan kami dari (bencana) ini, tentulah kami menjadi orang-orang yang bersyukur.&quot;<?php break;}
case 64:{?>Katakanlah: &quot;Allah menyelamatkan kamu daripada bencana itu dan dari segala macam kesusahan, kemudian kamu kembali mempersekutukan-Nya.&quot;<?php break;}
case 65:{?>Katakanlah: &quot;Dialah yang berkuasa untuk mengirimkan azab kepadamu, dari atas kamu atau dari bawah kakimu atau Dia mencampurkan kamu dalam golongan-golongan (yang saling bertentangan) dan merasakan kepada sebahagian) kamu keganasan sebahagian yang lain. Perhatikanlah, betapa Kami mendatangkan tanda-tanda kebesaran Kami silih berganti agar mereka memahami (nya).<?php break;}
case 66:{?>Dan kaummu mendustakannya (azab) padahal azab itu benar adanya. Katakanlah: &quot;Aku ini bukanlah orang yang diserahi mengurus urusanmu&quot;.<?php break;}
case 67:{?>Untuk tiap-tiap berita (yang dibawa oleh rasul-rasul) ada (waktu) terjadinya dan kelak kamu akan mengetahui.<?php break;}
case 68:{?>Dan apabila kamu melihat orang-orang memperolok-olokkan ayat-ayat Kami, maka tinggalkanlah mereka sehingga mereka membicarakan pembicaraan yang lain. Dan jika setan menjadikan kamu lupa (akan larangan ini), maka janganlah kamu duduk bersama orang-orang yang lalim itu sesudah teringat (akan larangan itu).<?php break;}
case 69:{?>Dan tidak ada pertanggungjawaban sedikit pun atas orang-orang yang bertakwa terhadap dosa mereka; akan tetapi (kewajiban mereka ialah) mengingatkan agar mereka bertakwa.<?php break;}
case 70:{?>Dan tinggalkanlah orang-orang yang menjadikan agama mereka sebagai main-main dan senda-gurau, dan mereka telah ditipu oleh kehidupan dunia. Peringatkanlah (mereka) dengan Al Qur'an itu agar masing-masing diri tidak dijerumuskan ke dalam neraka, karena perbuatannya sendiri. Tidak akan ada baginya pelindung dan tidak (pula) pemberi syafa'at selain daripada Allah. Dan jika ia menebus dengan segala macam tebusan pun, niscaya tidak akan diterima itu daripadanya. Mereka itulah orang-orang yang dijerumuskan ke dalam neraka, disebabkan perbuatan mereka sendiri. Bagi mereka (disediakan) minuman dari air yang sedang mendidih dan azab yang pedih disebabkan kekafiran mereka dahulu.<?php break;}
case 71:{?>Katakanlah: &quot;Apakah kita akan menyeru selain daripada Allah, sesuatu yang tidak dapat mendatangkan kemanfaatan kepada kita dan tidak (pula) mendatangkan kemudaratan kepada kita dan (apakah) kita akan dikembalikan ke belakang, sesudah Allah memberi petunjuk kepada kita, seperti orang yang telah disesatkan oleh setan di pesawangan yang menakutkan; dalam keadaan bingung, dia mempunyai kawan-kawan yang memanggilnya kepada jalan yang lurus (dengan mengatakan): &quot;Marilah ikuti kami&quot;. Katakanlah: &quot;Sesungguhnya petunjuk Allah itulah (yang sebenarnya) petunjuk; dan kita disuruh agar menyerahkan diri kepada Tuhan semesta alam,<?php break;}
case 72:{?>Dan agar mendirikan sembahyang serta bertakwa kepada-Nya.&quot; Dan Dialah Tuhan Yang kepada-Nya-lah kamu akan dihimpunkan.<?php break;}
case 73:{?>Dan Dialah yang menciptakan langit dan bumi dengan benar. Dan benarlah perkataan-Nya di waktu Dia mengatakan: &quot;Jadilah, lalu terjadilah&quot;, dan di tangan-Nyalah segala kekuasaan di waktu sangkakala ditiup. Dia mengetahui yang gaib dan yang nampak. Dan Dialah Yang Maha Bijaksana lagi Maha Mengetahui.<?php break;}
case 74:{?>Dan (ingatlah) di waktu Ibrahim berkata kepada bapaknya Aazar: &quot;Pantaskah kamu menjadikan berhala-berhala sebagai tuhan-tuhan? Sesungguhnya aku melihat kamu dan kaummu dalam kesesatan yang nyata&quot;.<?php break;}
case 75:{?>Dan demikianlah Kami perlihatkan kepada Ibrahim tanda-tanda keagungan (Kami yang terdapat) di langit dan bumi, dan (Kami memperlihatkannya) agar Ibrahim itu termasuk orang-orang yang yakin.<?php break;}
case 76:{?>Ketika malam telah menjadi gelap, dia melihat sebuah bintang (lalu) dia berkata: &quot;Inilah Tuhanku&quot; Tetapi tatkala bintang itu tenggelam dia berkata: &quot;Saya tidak suka kepada yang tenggelam&quot;.<?php break;}
case 77:{?>Kemudian tatkala dia melihat bulan terbit dia berkata: &quot;Inilah Tuhanku&quot;. Tetapi setelah bulan itu terbenam dia berkata: &quot;Sesungguhnya jika Tuhanku tidak memberi petunjuk kepadaku, pastilah aku termasuk orang-orang yang sesat&quot;.<?php break;}
case 78:{?>Kemudian tatkala dia melihat matahari terbit, dia berkata: &quot;Inilah Tuhanku, ini yang lebih besar&quot;, maka tatkala matahari itu telah terbenam, dia berkata: &quot;Hai kaumku, sesungguhnya aku berlepas diri dari apa yang kamu persekutukan.<?php break;}
case 79:{?>Sesungguhnya aku menghadapkan diriku kepada Tuhan yang menciptakan langit dan bumi dengan cenderung kepada agama yang benar, dan aku bukanlah termasuk orang-orang yang mempersekutukan Tuhan.<?php break;}
case 80:{?>Dan dia dibantah oleh kaumnya. Dia berkata: &quot;Apakah kamu hendak membantahku tentang Allah, padahal sesungguhnya Allah telah memberi petunjuk kepadaku. Dan aku tidak takut kepada (malapetaka dari) sembahan-sembahan yang kamu persekutukan dengan Allah, kecuali di kala Tuhanku menghendaki sesuatu (dari malapetaka) itu. Pengetahuan Tuhanku meliputi segala sesuatu. Maka apakah kamu tidak dapat mengambil pelajaran (daripadanya)?<?php break;}
case 81:{?>Bagaimana aku takut kepada sembahan-sembahan yang kamu persekutukan (dengan Allah), padahal kamu tidak takut mempersekutukan Allah dengan sembahan-sembahan yang Allah sendiri tidak menurunkan hujah kepadamu untuk mempersekutukan-Nya. Maka manakah di antara dua golongan itu yang lebih berhak mendapat keamanan (dari malapetaka), jika kamu mengetahui?&quot;<?php break;}
case 82:{?>Orang-orang yang beriman dan tidak mencampur adukkan iman mereka dengan kelaliman (syirik), mereka itulah orang-orang yang mendapat keamanan dan mereka itu adalah orang-orang yang mendapat petunjuk.<?php break;}
case 83:{?>Dan itulah hujah Kami yang Kami berikan kepada Ibrahim untuk menghadapi kaumnya. Kami tinggikan siapa yang Kami kehendaki beberapa derajat. Sesungguhnya Tuhanmu Maha Bijaksana lagi Maha Mengetahui.<?php break;}
case 84:{?>Dan Kami telah menganugerahkan Ishak dan Yakub kepadanya. Kepada keduanya masing-masing telah Kami beri petunjuk; dan kepada Nuh sebelum itu (juga) telah Kami beri petunjuk, dan kepada sebahagian dari keturunannya (Nuh) yaitu Daud, Sulaiman, Ayub, Yusuf, Musa dan Harun. Demikianlah kami memberi balasan kepada orang-orang yang berbuat baik,<?php break;}
case 85:{?>dan Zakaria, Yahya, Isa dan Ilyas. Semuanya termasuk orang-orang yang saleh.<?php break;}
case 86:{?>dan Ismail, Alyasa, Yunus dan Lut. Masing-masingnya Kami lebihkan derajatnya di atas umat (di masanya),<?php break;}
case 87:{?>(dan Kami lebihkan pula derajat) sebahagian dari bapak-bapak mereka, keturunan mereka dan saudara-saudara mereka. Dan Kami telah memilih mereka (untuk menjadi nabi-nabi dan rasul-rasul) dan Kami menunjuki mereka ke jalan yang lurus.<?php break;}
case 88:{?>Itulah petunjuk Allah, yang dengannya Dia memberi petunjuk kepada siapa yang dikehendaki-Nya di antara hamba-hamba-Nya. Seandainya mereka mempersekutukan Allah, niscaya lenyaplah dari mereka amalan yang telah mereka kerjakan.<?php break;}
case 89:{?>Mereka itulah orang-orang yang telah kami berikan kepada mereka kitab, hikmah (pemahaman agama) dan kenabian. Jika orang-orang (Quraisy) itu mengingkarinya (yang tiga macam itu), maka sesungguhnya Kami akan menyerahkannya kepada kaum yang sekali-kali tidak akan mengingkarinya.<?php break;}
case 90:{?>Mereka itulah orang-orang yang telah diberi petunjuk oleh Allah, maka ikutilah petunjuk mereka. Katakanlah: &quot;Aku tidak meminta upah kepadamu dalam menyampaikan (Al Qur'an)&quot;. Al Qur'an itu tidak lain hanyalah peringatan untuk segala umat.<?php break;}
case 91:{?>Dan mereka tidak menghormati Allah dengan penghormatan yang semestinya di kala mereka berkata: &quot;Allah tidak menurunkan sesuatu pun kepada manusia&quot;. Katakanlah: &quot;Siapakah yang menurunkan kitab (Taurat) yang dibawa oleh Musa sebagai cahaya dan petunjuk bagi manusia, kamu jadikan kitab itu lembaran-lembaran kertas yang bercerai-berai, kamu perlihatkan (sebagiannya) dan kamu sembunyikan sebagian besarnya, padahal telah diajarkan kepadamu apa yang kamu dan bapak-bapak kamu tidak mengetahui (nya)?&quot; Katakanlah: &quot;Allah-lah (yang menurunkannya)&quot;, kemudian (sesudah kamu menyampaikan Al Qur'an kepada mereka), biarkanlah mereka bermain-main dalam kesesatannya.<?php break;}
case 92:{?>Dan ini (Al Qur'an) adalah kitab yang telah Kami turunkan yang diberkahi; membenarkan kitab-kitab yang (diturunkan) sebelumnya dan agar kamu memberi peringatan kepada (penduduk) Umulkura (Mekah) dan orang-orang yang di luar lingkungannya. Orang-orang yang beriman kepada adanya kehidupan akhirat tentu beriman kepadanya (Al Qur'an), dan mereka selalu memelihara sembahyangnya.<?php break;}
case 93:{?>Dan siapakah yang lebih lalim daripada orang yang membuat kedustaan terhadap Allah atau yang berkata: &quot;Telah diwahyukan kepada saya&quot;, padahal tidak ada diwahyukan sesuatu pun kepadanya, dan orang yang berkata: &quot;Saya akan menurunkan seperti apa yang diturunkan Allah&quot;. Alangkah dahsyatnya sekiranya kamu melihat di waktu orang-orang yang zalim (berada) dalam tekanan-tekanan sakratulmaut, sedang para malaikat memukul dengan tangannya, (sambil berkata): &quot;Keluarkanlah nyawamu&quot;. Di hari ini kamu dibalas dengan siksaan yang sangat menghinakan, karena kamu selalu mengatakan terhadap Allah (perkataan) yang tidak benar dan (karena) kamu selalu menyombongkan diri terhadap ayat-ayat-Nya.<?php break;}
case 94:{?>Dan sesungguhnya kamu datang kepada Kami sendiri-sendiri sebagaimana kamu Kami ciptakan pada mulanya, dan kamu tinggalkan di belakangmu (di dunia) apa yang telah Kami kurniakan kepadamu; dan Kami tiada melihat besertamu pemberi syafaat yang kamu anggap bahwa mereka itu sekutu-sekutu Tuhan di antara kamu. Sungguh telah terputuslah (pertalian) antara kamu dan telah lenyap daripada kamu apa yang dahulu kamu anggap (sebagai sekutu Allah).<?php break;}
case 95:{?>Sesungguhnya Allah menumbuhkan butir tumbuh-tumbuhan dan biji buah-buahan. Dia mengeluarkan yang hidup dari yang mati dan mengeluarkan yang mati dari yang hidup. (Yang memiliki sifat-sifat) demikian ialah Allah, maka mengapa kamu masih berpaling?<?php break;}
case 96:{?>Dia menyingsingkan pagi dan menjadikan malam untuk beristirahat, dan (menjadikan) matahari dan bulan untuk perhitungan. Itulah ketentuan Allah Yang Maha Perkasa lagi Maha Mengetahui.<?php break;}
case 97:{?>Dan Dialah yang menjadikan bintang-bintang bagimu, agar kamu menjadikannya petunjuk dalam kegelapan di darat dan di laut. Sesungguhnya Kami telah menjelaskan tanda-tanda kebesaran (Kami) kepada orang-orang yang mengetahui.<?php break;}
case 98:{?>Dan Dialah yang menciptakan kamu dari seorang diri, maka (bagimu) ada tempat tetap dan tempat simpanan. Sesungguhnya telah Kami jelaskan tanda-tanda kebesaran Kami kepada orang-orang yang mengetahui.<?php break;}
case 99:{?>Dan Dialah yang menurunkan air hujan dari langit, lalu kami tumbuhkan dengan air itu segala macam tumbuh-tumbuhan, maka Kami keluarkan dari tumbuh-tumbuhan itu tanaman yang menghijau, Kami keluarkan dari tanaman yang menghijau itu butir yang banyak; dan dari mayang kurma mengurai tangkai-tangkai yang menjulai, dan kebun-kebun anggur, dan (Kami keluarkan pula) zaitun dan delima yang serupa dan yang tidak serupa. Perhatikanlah buahnya di waktu pohonnya berbuah, dan (perhatikan pulalah) kematangannya. Sesungguhnya pada yang demikian itu ada tanda-tanda (kekuasaan Allah) bagi orang-orang yang beriman.<?php break;}
case 100:{?>Dan mereka (orang-orang musyrik) menjadikan jin itu sekutu bagi Allah, padahal Allah-lah yang menciptakan jin-jin itu, dan mereka membohong (dengan mengatakan): &quot;Bahwasanya Allah mempunyai anak laki-laki dan perempuan&quot;, tanpa (berdasar) ilmu pengetahuan. Maha Suci Allah dan Maha Tinggi dari sifat-sifat yang mereka berikan.<?php break;}
case 101:{?>Dia Pencipta langit dan bumi. Bagaimana Dia mempunyai anak padahal Dia tidak mempunyai istri. Dia menciptakan segala sesuatu; dan Dia mengetahui segala sesuatu.<?php break;}
case 102:{?>(Yang memiliki sifat-sifat yang) demikian itu ialah Allah Tuhan kamu; tidak ada Tuhan (yang berhak disembah) selain Dia; Pencipta segala sesuatu, maka sembahlah Dia; dan Dia adalah Pemelihara segala sesuatu.<?php break;}
case 103:{?>Dia tidak dapat dicapai oleh penglihatan mata, sedang Dia dapat melihat segala penglihatan itu dan Dialah Yang Maha Halus lagi Maha Mengetahui.<?php break;}
case 104:{?>Sesungguhnya telah datang dari Tuhanmu bukti-bukti yang terang; maka Barang siapa melihat (kebenaran itu), maka (manfaatnya) bagi dirinya sendiri; dan barang siapa buta (tidak melihat kebenaran itu), maka kemudaratannya kembali kepadanya. Dan aku (Muhammad) sekali-kali bukanlah pemelihara (mu).<?php break;}
case 105:{?>Demikianlah kami mengulang-ulangi ayat-ayat Kami supaya (orang-orang yang beriman mendapat petunjuk) dan yang mengakibatkan orang-orang musyrik mengatakan: &quot;Kamu telah mempelajari ayat-ayat itu (dari Ahli Kitab)&quot;, dan supaya Kami menjelaskan Al Qur'an itu kepada orang-orang yang mengetahui.<?php break;}
case 106:{?>Ikutilah apa yang telah diwahyukan kepadamu dari Tuhanmu; tidak ada Tuhan selain Dia; dan berpalinglah dari orang-orang musyrik.<?php break;}
case 107:{?>Dan kalau Allah menghendaki, niscaya mereka tidak mempersekutukan (Nya). Dan Kami tidak menjadikan kamu pemelihara bagi mereka; dan kamu sekali-kali bukanlah pemelihara bagi mereka.<?php break;}
case 108:{?>Dan janganlah kamu memaki sembahan-sembahan yang mereka sembah selain Allah, karena mereka nanti akan memaki Allah dengan melampaui batas tanpa pengetahuan. Demikianlah Kami jadikan setiap umat menganggap baik pekerjaan mereka. Kemudian kepada Tuhan merekalah kembali mereka, lalu Dia memberitakan kepada mereka apa yang dahulu mereka kerjakan.<?php break;}
case 109:{?>Mereka bersumpah dengan nama Allah dengan segala kesungguhan, bahwa sungguh jika datang kepada mereka sesuatu mukjizat pastilah mereka beriman kepada-Nya. Katakanlah: &quot;Sesungguhnya mukjizat-mukjizat itu hanya berada di sisi Allah&quot;. Dan apakah yang memberitahukan kepadamu bahwa apabila mukjizat datang mereka tidak akan beriman.<?php break;}
case 110:{?>Dan (begitu pula) Kami memalingkan hati dan penglihatan mereka seperti mereka belum pernah beriman kepadanya (Al Qur'an) pada permulaannya, dan Kami biarkan mereka bergelimang dalam kesesatannya yang sangat.<?php break;}
case 111:{?>Kalau sekiranya Kami turunkan malaikat kepada mereka, dan orang-orang yang telah mati berbicara dengan mereka dan Kami kumpulkan (pula) segala sesuatu ke hadapan mereka niscaya mereka tidak (juga) akan beriman, kecuali jika Allah menghendaki, tetapi kebanyakan mereka tidak mengetahui.<?php break;}
case 112:{?>Dan demikianlah Kami jadikan bagi tiap-tiap nabi itu musuh, yaitu setan-setan (dari jenis) manusia dan (dari jenis) jin, sebahagian mereka membisikkan kepada sebahagian yang lain perkataan-perkataan yang indah-indah untuk menipu (manusia). Jika Tuhanmu menghendaki, niscaya mereka tidak mengerjakannya, maka tinggalkanlah mereka dan apa yang mereka ada-adakan.<?php break;}
case 113:{?>Dan (juga) agar hati kecil orang-orang yang tidak beriman kepada kehidupan akhirat cenderung kepada bisikan itu, mereka merasa senang kepadanya dan supaya mereka mengerjakan apa yang mereka (setan) kerjakan.<?php break;}
case 114:{?>Maka patutkah aku mencari hakim selain daripada Allah, padahal Dialah yang telah menurunkan kitab (Al Qur'an) kepadamu dengan terperinci? Orang-orang yang telah Kami datangkan kitab kepada mereka, mereka mengetahui bahwa Al Qur'an itu diturunkan dari Tuhanmu dengan sebenarnya. Maka janganlah kamu sekali-kali termasuk orang yang ragu-ragu.<?php break;}
case 115:{?>Telah sempurnalah kalimat Tuhanmu (Al Qur'an, sebagai kalimat yang benar dan adil. Tidak ada yang dapat merubah-rubah kalimat-kalimat-Nya dan Dia-lah yang Maha Mendengar lagi Maha Mengetahui.<?php break;}
case 116:{?>Dan jika kamu menuruti kebanyakan orang-orang yang di muka bumi ini, niscaya mereka akan menyesatkanmu dari jalan Allah. Mereka tidak lain hanyalah mengikuti persangkaan belaka, dan mereka tidak lain hanyalah berdusta (terhadap Allah).<?php break;}
case 117:{?>Sesungguhnya Tuhanmu, Dia-lah yang lebih mengetahui tentang orang yang tersesat dari jalan-Nya dan Dia lebih mengetahui tentang orang-orang yang mendapat petunjuk.<?php break;}
case 118:{?>Maka makanlah binatang-binatang (yang halal) yang disebut nama Allah ketika menyembelihnya, jika kamu beriman kepada ayat-ayat-Nya.<?php break;}
case 119:{?>Mengapa kamu tidak mau memakan (binatang-binatang yang halal) yang disebut nama Allah ketika menyembelihnya, padahal sesungguhnya Allah telah menjelaskan kepada kamu apa yang diharamkan-Nya atasmu, kecuali apa yang terpaksa kamu memakannya. Dan sesungguhnya kebanyakan (dari manusia) benar-benar hendak menyesatkan (orang lain) dengan hawa nafsu mereka tanpa pengetahuan. Sesungguhnya Tuhanmu, Dia-lah yang lebih mengetahui orang-orang yang melampaui batas.<?php break;}
case 120:{?>Dan tinggalkanlah dosa yang nampak dan yang tersembunyi. Sesungguhnya orang-orang yang mengerjakan dosa, kelak akan diberi pembalasan (pada hari kiamat), disebabkan apa yang mereka telah kerjakan.<?php break;}
case 121:{?>Dan janganlah kamu memakan binatang-binatang yang tidak disebut nama Allah ketika menyembelihnya. Sesungguhnya perbuatan yang semacam itu adalah suatu kefasikan. Sesungguhnya setan itu membisikkan kepada kawan-kawannya agar mereka membantah kamu; dan jika kamu menuruti mereka, sesungguhnya kamu tentulah menjadi orang-orang yang musyrik.<?php break;}
case 122:{?>Dan apakah orang yang sudah mati kemudian dia Kami hidupkan dan Kami berikan kepadanya cahaya yang terang, yang dengan cahaya itu dia dapat berjalan di tengah-tengah masyarakat manusia, serupa dengan orang yang keadaannya berada dalam gelap gulita yang sekali-kali tidak dapat keluar daripadanya? Demikianlah Kami jadikan orang yang kafir itu memandang baik apa yang telah mereka kerjakan.<?php break;}
case 123:{?>Dan demikianlah Kami adakan pada tiap-tiap negeri penjahat-penjahat yang terbesar agar mereka melakukan tipu daya dalam negeri itu. Dan mereka tidak memperdayakan melainkan dirinya sendiri, sedang mereka tidak menyadarinya.<?php break;}
case 124:{?>Apabila datang sesuatu ayat kepada mereka, mereka berkata: &quot;Kami tidak akan beriman sehingga diberikan kepada kami yang serupa dengan apa yang telah diberikan kepada utusan-utusan Allah&quot;. Allah lebih mengetahui di mana Dia menempatkan tugas kerasulan. Orang-orang yang berdosa, nanti akan ditimpa kehinaan di sisi Allah dan siksa yang keras disebabkan mereka selalu membuat tipu daya.<?php break;}
case 125:{?>Barang siapa yang Allah menghendaki akan memberikan kepadanya petunjuk, niscaya Dia melapangkan dadanya untuk (memeluk agama) Islam. Dan barang siapa yang dikehendaki Allah kesesatannya, niscaya Allah menjadikan dadanya sesak lagi sempit, seolah-olah ia sedang mendaki ke langit. Begitulah Allah menimpakan siksa kepada orang-orang yang tidak beriman.<?php break;}
case 126:{?>Dan inilah jalan Tuhanmu; (jalan) yang lurus. Sesungguhnya Kami telah menjelaskan ayat-ayat (Kami) kepada orang-orang yang mengambil pelajaran.<?php break;}
case 127:{?>Bagi mereka (disediakan) Darussalam (surga) pada sisi Tuhannya dan Dialah Pelindung mereka disebabkan amal-amal saleh yang selalu mereka kerjakan.<?php break;}
case 128:{?>Dan (ingatlah) hari di waktu Allah menghimpunkan mereka semuanya, (dan Allah berfirman): &quot;Hai golongan jin (setan), sesungguhnya kamu telah banyak (menyesatkan) manusia&quot;, lalu berkatalah kawan-kawan mereka dari golongan manusia: &quot;Ya Tuhan kami, sesungguhnya sebahagian daripada kami telah dapat kesenangan dari sebahagian (yang lain) dan kami telah sampai kepada waktu yang telah Engkau tentukan bagi kami&quot;. Allah berfirman: &quot;Neraka itulah tempat diam kamu, sedang kamu kekal di dalamnya, kecuali kalau Allah menghendaki (yang lain)&quot;. Sesungguhnya Tuhanmu Maha Bijaksana lagi Maha Mengetahui.<?php break;}
case 129:{?>Dan demikianlah Kami jadikan sebahagian orang-orang yang lalim itu menjadi teman bagi sebagian yang lain disebabkan apa yang mereka usahakan.<?php break;}
case 130:{?>Hai golongan jin dan manusia, apakah belum datang kepadamu rasul-rasul dari golongan kamu sendiri, yang menyampaikan kepadamu ayat-ayat Ku dan memberi peringatan kepadamu terhadap pertemuanmu dengan hari ini? Mereka berkata: &quot;Kami menjadi saksi atas diri kami sendiri&quot;, kehidupan dunia telah menipu mereka, dan mereka menjadi saksi atas diri mereka sendiri, bahwa mereka adalah orang-orang yang kafir.<?php break;}
case 131:{?>Yang demikian itu adalah karena Tuhanmu tidaklah membinasakan kota-kota secara aniaya, sedang penduduknya dalam keadaan lengah.<?php break;}
case 132:{?>Dan masing-masing orang memperoleh derajat-derajat (seimbang) dengan apa yang dikerjakannya. Dan Tuhanmu tidak lengah dari apa yang mereka kerjakan.<?php break;}
case 133:{?>Dan Tuhanmu Maha Kaya, lagi mempunyai rahmat. Jika Dia menghendaki niscaya Dia memusnahkan kamu dan menggantimu dengan siapa yang dikehendaki-Nya setelah kamu (musnah), sebagaimana Dia telah menjadikan kamu dari keturunan orang-orang lain.<?php break;}
case 134:{?>Sesungguhnya apa yang dijanjikan kepadamu pasti datang, dan kamu sekali-kali tidak sanggup menolaknya.<?php break;}
case 135:{?>Katakanlah: &quot;Hai kaumku, berbuatlah sepenuh kemampuanmu, sesungguhnya aku pun berbuat (pula). Kelak kamu akan mengetahui, siapakah (di antara kita) yang akan memperoleh hasil yang baik dari dunia ini. Sesungguhnya, orang-orang yang lalim itu tidak akan mendapat keberuntungan.<?php break;}
case 136:{?>Dan mereka memperuntukkan bagi Allah satu bahagian dari tanaman dan ternak yang telah diciptakan Allah, lalu mereka berkata sesuai dengan persangkaan mereka: &quot;Ini untuk Allah dan ini untuk berhala-berhala kami&quot;. Maka saji-sajian yang diperuntukkan bagi berhala-berhala mereka tidak sampai kepada Allah; dan saji-sajian yang diperuntukkan bagi Allah, maka sajian itu sampai kepada berhala-berhala mereka. Amat buruklah ketetapan mereka itu.<?php break;}
case 137:{?>Dan demikianlah pemimpin-pemimpin mereka telah menjadikan kebanyakan dari orang-orang yang musyrik itu memandang baik membunuh anak-anak mereka untuk membinasakan mereka dan untuk mengaburkan bagi mereka agamanya. Dan kalau Allah menghendaki, niscaya mereka tidak mengerjakannya, maka tinggalkanlah mereka dan apa yang mereka ada-adakan.<?php break;}
case 138:{?>Dan mereka mengatakan: &quot;Inilah binatang ternak dan tanaman yang dilarang; tidak boleh memakannya, kecuali orang yang kami kehendaki&quot; menurut anggapan mereka, dan ada binatang ternak yang diharamkan menungganginya dan binatang ternak yang mereka tidak menyebut nama Allah di waktu menyembelihnya, semata-mata membuat-buat kedustaan terhadap Allah. Kelak Allah akan membalas mereka terhadap apa yang selalu mereka ada-adakan.<?php break;}
case 139:{?>Dan mereka mengatakan: &quot;Apa yang dalam perut binatang ternak ini adalah khusus untuk pria kami dan diharamkan atas wanita kami,&quot; dan jika yang dalam perut itu dilahirkan mati, maka pria dan wanita sama-sama boleh memakannya. Kelak Allah akan membalas mereka terhadap ketetapan mereka. Sesungguhnya Allah Maha Bijaksana lagi Maha Mengetahui.<?php break;}
case 140:{?>Sesungguhnya rugilah orang yang membunuh anak-anak mereka karena kebodohan lagi tidak mengetahui, dan mereka mengharamkan apa yang Allah telah rezekikan kepada mereka dengan semata-mata mengada-adakan terhadap Allah. Sesungguhnya mereka telah sesat dan tidaklah mereka mendapat petunjuk.<?php break;}
case 141:{?>Dan Dialah yang menjadikan kebun-kebun yang berjunjung dan yang tidak berjunjung, pohon kurma, tanam-tanaman yang bermacam-macam buahnya, zaitun dan delima yang serupa (bentuk dan warnanya), dan tidak sama (rasanya). Makanlah dari buahnya (yang bermacam-macam itu) bila dia berbuah, dan tunaikanlah haknya di hari memetik hasilnya (dengan dikeluarkan zakatnya); dan janganlah kamu berlebih-lebihan. Sesungguhnya Allah tidak menyukai orang-orang yang berlebih-lebihan.<?php break;}
case 142:{?>Dan di antara binatang ternak itu ada yang dijadikan untuk pengangkutan dan ada yang untuk disembelih. Makanlah dari rezeki yang telah diberikan Allah kepadamu, dan janganlah kamu mengikuti langkah-langkah setan. Sesungguhnya setan itu musuh yang nyata bagimu,<?php break;}
case 143:{?>(yaitu) delapan binatang yang berpasangan, sepasang dari domba dan sepasang dari kambing. Katakanlah: &quot;Apakah dua yang jantan yang diharamkan Allah ataukah dua yang betina, ataukah yang ada dalam kandungan dua betinanya?&quot; Terangkanlah kepadaku dengan berdasar pengetahuan jika kamu memang orang-orang yang benar,<?php break;}
case 144:{?>dan sepasang dari unta dan sepasang dari lembu. Katakanlah: &quot;Apakah dua yang jantan yang diharamkan ataukah dua yang betina, ataukah yang ada dalam kandungan dua betinanya. Apakah kamu menyaksikan di waktu Allah menetapkan ini bagimu? Maka siapakah yang lebih lalim daripada orang-orang yang membuat-buat dusta terhadap Allah untuk menyesatkan manusia tanpa pengetahuan?&quot; Sesungguhnya Allah tidak memberi petunjuk kepada orang-orang yang lalim.<?php break;}
case 145:{?>Katakanlah: &quot;Tiadalah aku peroleh dalam wahyu yang diwahyukan kepadaku, sesuatu yang diharamkan bagi orang yang hendak memakannya, kecuali kalau makanan itu bangkai, atau darah yang mengalir atau daging babi, karena sesungguhnya semua itu kotor atau binatang yang disembelih atas nama selain Allah. Barang siapa yang dalam keadaan terpaksa sedang dia tidak menginginkannya dan tidak (pula) melampaui batas, maka sesungguhnya Tuhanmu Maha Pengampun lagi Maha Penyayang.&quot;<?php break;}
case 146:{?>Dan kepada orang-orang Yahudi, Kami haramkan segala binatang yang berkuku; dan dari sapi dan domba, Kami haramkan atas mereka lemak dari kedua binatang itu, selain lemak yang melekat di punggung keduanya atau yang di perut besar dan usus atau yang bercampur dengan tulang. Demikianlah Kami hukum mereka disebabkan kedurhakaan mereka; dan sesungguhnya Kami adalah Maha Benar.<?php break;}
case 147:{?>Maka jika mereka mendustakan kamu katakanlah: &quot;Tuhanmu mempunyai rahmat yang luas; dan siksanya tidak dapat ditolak dari kaum yang berdosa&quot;.<?php break;}
case 148:{?>Orang-orang yang mempersekutukan Tuhan, akan mengatakan: &quot;Jika Allah menghendaki, niscaya kami dan bapak-bapak kami tidak mempersekutukan-Nya dan tidak (pula) kami mengharamkan barang sesuatu apa pun&quot;. Demikian pulalah orang-orang yang sebelum mereka telah mendustakan (para rasul) sampai mereka merasakan siksaan Kami. Katakanlah: &quot;Adakah kamu mempunyai sesuatu pengetahuan sehingga dapat kamu mengemukakannya kepada Kami?&quot; Kamu tidak mengikuti kecuali persangkaan belaka, dan kamu tidak lain hanya berdusta.<?php break;}
case 149:{?>Katakanlah: &quot;Allah mempunyai hujah yang jelas lagi kuat; maka jika Dia menghendaki, pasti Dia memberi petunjuk kepada kamu semuanya&quot;.<?php break;}
case 150:{?>Katakanlah: &quot;Bawalah ke mari saksi-saksi kamu yang dapat mempersaksikan bahwasanya Allah telah mengharamkan (makanan yang kamu) haramkan ini.&quot; Jika mereka mempersaksikan, maka janganlah kamu ikut (pula) menjadi saksi bersama mereka; dan janganlah kamu mengikuti hawa nafsu orang-orang yang mendustakan ayat-ayat Kami, dan orang-orang yang tidak beriman kepada kehidupan akhirat, sedang mereka mempersekutukan Tuhan mereka.<?php break;}
case 151:{?>Katakanlah: &quot;Marilah kubacakan apa yang diharamkan atas kamu oleh Tuhanmu, yaitu: janganlah kamu mempersekutukan sesuatu dengan Dia, berbuat baiklah terhadap kedua orang ibu bapa, dan janganlah kamu membunuh anak-anak kamu karena takut kemiskinan. Kami akan memberi rezeki kepadamu dan kepada mereka; dan janganlah kamu mendekati perbuatan-perbuatan yang keji, baik yang nampak di antaranya maupun yang tersembunyi, dan janganlah kamu membunuh jiwa yang diharamkan Allah (membunuhnya) melainkan dengan sesuatu (sebab) yang benar&quot;. Demikian itu yang diperintahkan oleh Tuhanmu kepadamu supaya kamu memahami (nya).<?php break;}
case 152:{?>Dan janganlah kamu dekati harta anak yatim, kecuali dengan cara yang lebih bermanfaat, hingga sampai ia dewasa. Dan sempurnakanlah takaran dan timbangan dengan adil. Kami tidak memikulkan beban kepada seseorang melainkan sekedar kesanggupannya. Dan apabila kamu berkata, maka hendaklah kamu berlaku adil kendati pun dia adalah kerabat (mu), dan penuhilah janji Allah. Yang demikian itu diperintahkan Allah kepadamu agar kamu ingat,<?php break;}
case 153:{?>dan bahwa (yang Kami perintahkan) ini adalah jalan-Ku yang lurus, maka ikutilah dia; dan janganlah kamu mengikuti jalan-jalan (yang lain), karena jalan-jalan itu mencerai-beraikan kamu dari jalan-Nya. Yang demikian itu diperintahkan Allah kepadamu agar kamu bertakwa.<?php break;}
case 154:{?>Kemudian Kami telah memberikan Al Kitab (Taurat) kepada Musa untuk menyempurnakan (ni'mat Kami) kepada orang yang berbuat kebaikan, dan untuk menjelaskan segala sesuatu dan sebagai petunjuk dan rahmat, agar mereka beriman (bahwa) mereka akan menemui Tuhan mereka.<?php break;}
case 155:{?>Dan Al Qur'an itu adalah kitab yang Kami turunkan yang diberkati, maka ikutilah dia dan bertakwalah agar kamu diberi rahmat,<?php break;}
case 156:{?>(Kami turunkan Al Qur'an itu) agar kamu (tidak) mengatakan: Bahwa kitab itu hanya diturunkan kepada dua golongan saja sebelum kami, dan sesungguhnya kami tidak memperhatikan apa yang mereka baca.&quot;<?php break;}
case 157:{?>Atau agar kamu (tidak) mengatakan: &quot;Sesungguhnya jika kitab itu diturunkan kepada kami, tentulah kami lebih mendapat petunjuk dari mereka.&quot; Sesungguhnya telah datang kepada kamu keterangan yang nyata dari Tuhanmu, petunjuk dan rahmat. Maka siapakah yang lebih zalim daripada orang yang mendustakan ayat-ayat Allah dan berpaling daripadanya? Kelak Kami akan memberi balasan kepada orang-orang yang berpaling dari ayat-ayat Kami dengan siksaan yang buruk, disebabkan mereka selalu berpaling.<?php break;}
case 158:{?>Yang mereka nanti-nanti tidak lain hanyalah kedatangan malaikat kepada mereka (untuk mencabut nyawa mereka), atau kedatangan Tuhanmu atau kedatangan sebagian tanda-tanda Tuhanmu. Pada hari datangnya sebagian tanda-tanda Tuhanmu tidaklah bermanfaat lagi iman seseorang bagi dirinya sendiri yang belum beriman sebelum itu, atau dia (belum) mengusahakan kebaikan dalam masa imannya. Katakanlah: &quot;Tunggulah olehmu sesungguhnya kami pun menunggu (pula).&quot;<?php break;}
case 159:{?>Sesungguhnya orang-orang yang memecah belah agamanya dan mereka (terpecah) menjadi beberapa golongan, tidak ada sedikit pun tanggung jawabmu terhadap mereka. Sesungguhnya urusan mereka hanyalah (terserah) kepada Allah, kemudian Allah akan memberitahukan kepada mereka apa yang telah mereka perbuat.<?php break;}
case 160:{?>Barang siapa membawa amal yang baik maka baginya (pahala) sepuluh kali lipat amalnya; dan barang siapa yang membawa perbuatan yang jahat maka dia tidak diberi pembalasan melainkan seimbang dengan kejahatannya, sedang mereka sedikit pun tidak dianiaya (dirugikan).<?php break;}
case 161:{?>Katakanlah: &quot;Sesungguhnya aku telah ditunjuki oleh Tuhanku kepada jalan yang lurus, (yaitu) agama yang benar; agama Ibrahim yang lurus; dan Ibrahim itu bukanlah termasuk orang-orang yang musyrik&quot;.<?php break;}
case 162:{?>Katakanlah: &quot;Sesungguhnya salat, ibadah, hidup dan matiku hanyalah untuk Allah, Tuhan semesta alam,<?php break;}
case 163:{?>tiada sekutu bagi-Nya; dan demikian itulah yang diperintahkan kepadaku dan aku adalah orang yang pertama-tama menyerahkan diri (kepada Allah)&quot;.<?php break;}
case 164:{?>Katakanlah: &quot;Apakah aku akan mencari Tuhan selain Allah, padahal Dia adalah Tuhan bagi segala sesuatu. Dan tidaklah seorang membuat dosa melainkan kemudaratannya kembali kepada dirinya sendiri; dan seorang yang berdosa tidak akan memikul dosa orang lain. Kemudian kepada Tuhanmulah kamu kembali, dan akan diberitakan-Nya kepadamu apa yang kamu perselisihkan&quot;.<?php break;}
case 165:{?>Dan Dialah yang menjadikan kamu penguasa-penguasa di bumi dan Dia meninggikan sebahagian kamu atas sebahagian (yang lain) beberapa derajat, untuk mengujimu tentang apa yang diberikan-Nya kepadamu. Sesungguhnya Tuhanmu amat cepat siksaan-Nya, dan sesungguhnya Dia Maha Pengampun lagi Maha Penyayang.<?php break;}
}?>