<?php 
switch($verse){
case 1:{?>Bertasbih kepada Allah apa saja yang ada di langit dan apa saja yang ada di bumi; dan Dia-lah Yang Maha Perkasa lagi Maha Bijaksana.<?php break;}
case 2:{?>Hai orang-orang yang beriman, mengapa kamu mengatakan apa yang tidak kamu perbuat?<?php break;}
case 3:{?>Amat besar kebencian di sisi Allah bahwa kamu mengatakan apa-apa yang tiada kamu kerjakan.<?php break;}
case 4:{?>Sesungguhnya Allah menyukai orang-orang yang berperang di jalan-Nya dalam barisan yang teratur seakan-akan mereka seperti suatu bangunan yang tersusun kokoh.<?php break;}
case 5:{?>Dan (ingatlah) ketika Musa berkata kepada kaumnya: &quot;Hai kaumku, mengapa kamu menyakitiku, sedangkan kamu mengetahui bahwa sesungguhnya aku adalah utusan Allah kepadamu?&quot; Maka tatkala mereka berpaling (dari kebenaran), Allah memalingkan hati mereka; dan Allah tiada memberi petunjuk kepada kaum yang fasik.<?php break;}
case 6:{?>Dan (ingatlah) ketika Isa Putra Maryam berkata: &quot;Hai Bani Israel, sesungguhnya aku adalah utusan Allah kepadamu, membenarkan kitab (yang turun) sebelumku, yaitu Taurat dan memberi kabar gembira dengan (datangnya) seorang Rasul yang akan datang sesudahku, yang namanya Ahmad (Muhammad)&quot; Maka tatkala rasul itu datang kepada mereka dengan membawa bukti-bukti yang nyata, mereka berkata: &quot;Ini adalah sihir yang nyata&quot;.<?php break;}
case 7:{?>Dan siapakah yang lebih lalim daripada orang yang mengada-adakan dusta terhadap Allah sedang dia diajak kepada agama Islam? Dan Allah tiada memberi petunjuk kepada orang-orang yang lalim.<?php break;}
case 8:{?>Mereka ingin hendak memadamkan cahaya (agama) Allah dengan mulut (ucapan-ucapan) mereka, dan Allah tetap menyempurnakan cahaya-Nya meskipun orang-orang kafir benci.<?php break;}
case 9:{?>Dia-lah yang mengutus Rasul-Nya dengan membawa petunjuk dan agama yang benar agar Dia memenangkannya di atas segala agama-agama meskipun orang-orang musyrik benci.<?php break;}
case 10:{?>Hai orang-orang yang beriman, sukakah kamu Aku tunjukkan suatu perniagaan yang dapat menyelamatkan kamu dari azab yang pedih?<?php break;}
case 11:{?>(yaitu) kamu beriman kepada Allah dan Rasul-Nya dan berjihad di jalan Allah dengan harta dan jiwamu. Itulah yang lebih baik bagi kamu jika kamu mengetahuinya,<?php break;}
case 12:{?>niscaya Allah akan mengampuni dosa-dosamu dan memasukkan kamu ke dalam surga yang mengalir di bawahnya sungai-sungai, dan (memasukkan kamu) ke tempat tinggal yang baik di dalam surga Adn. Itulah keberuntungan yang besar.<?php break;}
case 13:{?>Dan (ada lagi) karunia yang lain yang kamu sukai (yaitu) pertolongan dari Allah dan kemenangan yang dekat (waktunya). Dan sampaikanlah berita gembira kepada orang-orang yang beriman.<?php break;}
case 14:{?>Hai orang-orang yang beriman, jadilah kamu penolong-penolong (agama) Allah sebagaimana Isa putra Maryam telah berkata kepada pengikut-pengikutnya yang setia: &quot;Siapakah yang akan menjadi penolong-penolongku (untuk menegakkan agama) Allah?&quot; Pengikut-pengikut yang setia itu berkata: &quot;Kami lah penolong-penolong agama Allah&quot;, lalu segolongan dari Bani Israel beriman dan segolongan (yang lain) kafir; maka kami berikan kekuatan kepada orang-orang yang beriman terhadap musuh-musuh mereka, lalu mereka menjadi orang-orang yang menang.<?php break;}
}?>