<?php 
switch($verse){
case 1:{?>Alif, laam miim shaad.<?php break;}
case 2:{?>Ini adalah sebuah kitab yang diturunkan kepadamu, maka janganlah ada kesempitan di dalam dadamu karenanya, supaya kamu memberi peringatan dengan kitab itu (kepada orang kafir), dan menjadi pelajaran bagi orang-orang yang beriman.<?php break;}
case 3:{?>Ikutilah apa yang diturunkan kepadamu dari Tuhanmu dan janganlah kamu mengikuti pemimpin-pemimpin selain-Nya. Amat sedikitlah kamu mengambil pelajaran (daripadanya).<?php break;}
case 4:{?>Betapa banyaknya negeri yang telah Kami binasakan, maka datanglah siksaan Kami (menimpa penduduk) nya di waktu mereka berada di malam hari, atau di waktu mereka beristirahat di tengah hari.<?php break;}
case 5:{?>Maka tidak adalah keluhan mereka di waktu datang kepada mereka siksaan Kami, kecuali mengatakan: &quot;Sesungguhnya kami adalah orang-orang yang lalim&quot;.<?php break;}
case 6:{?>Maka sesungguhnya Kami akan menanyai umat-umat yang telah diutus rasul-rasul kepada mereka dan sesungguhnya Kami akan menanyai (pula) rasul-rasul (Kami),<?php break;}
case 7:{?>maka sesungguhnya akan Kami kabarkan kepada mereka (apa-apa yang telah mereka perbuat), sedang (Kami) mengetahui (keadaan mereka), dan Kami sekali-kali tidak jauh (dari mereka).<?php break;}
case 8:{?>Timbangan pada hari itu ialah kebenaran (keadilan), maka barang siapa berat timbangan kebaikannya, maka mereka itulah orang-orang yang beruntung.<?php break;}
case 9:{?>Dan siapa yang ringan timbangan kebaikannya, maka itulah orang-orang yang merugikan dirinya sendiri, disebabkan mereka selalu mengingkari ayat-ayat Kami.<?php break;}
case 10:{?>Sesungguhnya Kami telah menempatkan kamu sekalian di muka bumi dan Kami adakan bagimu di muka bumi itu (sumber) penghidupan. Amat sedikitlah kamu bersyukur.<?php break;}
case 11:{?>Sesungguhnya Kami telah menciptakan kamu (Adam), lalu Kami bentuk tubuhmu, kemudian Kami katakan kepada para malaikat: &quot;Bersujudlah kamu kepada Adam&quot;; maka mereka pun bersujud kecuali iblis. Dia tidak termasuk mereka yang bersujud.<?php break;}
case 12:{?>Allah berfirman: &quot;Apakah yang menghalangimu untuk bersujud (kepada Adam) di waktu Aku menyuruhmu?&quot; Menjawab iblis: &quot;Saya lebih baik daripadanya: Engkau ciptakan saya dari api sedang dia Engkau ciptakan dari tanah&quot;.<?php break;}
case 13:{?>Allah berfirman: &quot;Turunlah kamu dari surga itu; karena kamu tidak sepatutnya menyombongkan diri di dalamnya, maka ke luarlah, sesungguhnya kamu termasuk orang-orang yang hina&quot;.<?php break;}
case 14:{?>Iblis menjawab: &quot;Beri tangguhlah saya sampai waktu mereka dibangkitkan&quot;.<?php break;}
case 15:{?>Allah berfirman: &quot;Sesungguhnya kamu termasuk mereka yang diberi tangguh.&quot;<?php break;}
case 16:{?>Iblis menjawab: &quot;Karena Engkau telah menghukum saya tersesat, saya benar-benar akan (menghalang-halangi) mereka dari jalan Engkau yang lurus,<?php break;}
case 17:{?>kemudian saya akan mendatangi mereka dari muka dan dari belakang mereka, dari kanan dan dari kiri mereka. Dan Engkau tidak akan mendapati kebanyakan mereka bersyukur (taat).<?php break;}
case 18:{?>Allah berfirman: &quot;Keluarlah kamu dari surga itu sebagai orang terhina lagi terusir. Sesungguhnya barang siapa di antara mereka mengikuti kamu, benar-benar Aku akan mengisi neraka Jahanam dengan kamu semuanya&quot;.<?php break;}
case 19:{?>(Dan Allah berfirman): &quot;Hai Adam bertempat tinggallah kamu dan istrimu di surga serta makanlah olehmu berdua (buah-buahan) di mana saja yang kamu sukai, dan janganlah kamu berdua mendekati pohon ini, lalu menjadilah kamu berdua termasuk orang-orang yang lalim&quot;.<?php break;}
case 20:{?>Maka setan membisikkan pikiran jahat kepada keduanya untuk menampakkan kepada keduanya apa yang tertutup dari mereka yaitu auratnya dan setan berkata: &quot;Tuhan kamu tidak melarangmu dari mendekati pohon ini, melainkan supaya kamu berdua tidak menjadi malaikat atau tidak menjadi orang yang kekal (dalam surga)&quot;.<?php break;}
case 21:{?>Dan dia (setan) bersumpah kepada keduanya. &quot;Sesungguhnya saya adalah termasuk orang yang memberi nasihat kepada kamu berdua&quot;,<?php break;}
case 22:{?>maka setan membujuk keduanya (untuk memakan buah itu) dengan tipu daya. Tatkala keduanya telah merasai buah kayu itu, nampaklah bagi keduanya aurat-auratnya, dan mulailah keduanya menutupinya dengan daun-daun surga. Kemudian Tuhan mereka menyeru mereka: &quot;Bukankah Aku telah melarang kamu berdua dari pohon kayu itu dan Aku katakan kepadamu: &quot;Sesungguhnya setan itu adalah musuh yang nyata bagi kamu berdua?&quot;<?php break;}
case 23:{?>Keduanya berkata: &quot;Ya Tuhan kami, kami telah menganiaya diri kami sendiri, dan jika Engkau tidak mengampuni kami dan memberi rahmat kepada kami, niscaya pastilah kami termasuk orang-orang yang merugi&quot;.<?php break;}
case 24:{?>Allah berfirman: &quot;Turunlah kamu sekalian, sebahagian kamu menjadi musuh bagi sebahagian yang lain. Dan kamu mempunyai tempat kediaman dan kesenangan (tempat mencari kehidupan) di muka bumi sampai waktu yang telah ditentukan&quot;.<?php break;}
case 25:{?>Allah berfirman: &quot;Di bumi itu kamu hidup dan di bumi itu kamu mati, dan dari bumi itu (pula) kamu akan dibangkitkan.<?php break;}
case 26:{?>Hai anak Adam, sesungguhnya Kami telah menurunkan kepadamu pakaian untuk menutupi auratmu dan pakaian indah untuk perhiasan. Dan pakaian takwa itulah yang paling baik. Yang demikian itu adalah sebahagian dari tanda-tanda kekuasaan Allah, mudah-mudahan mereka selalu ingat.<?php break;}
case 27:{?>Hai anak Adam, janganlah sekali-kali kamu dapat ditipu oleh setan sebagaimana ia telah mengeluarkan kedua ibu bapamu dari surga, ia menanggalkan dari keduanya pakaiannya untuk memperlihatkan kepada keduanya 'auratnya. Sesungguhnya ia dan pengikut-pengikutnya melihat kamu dari suatu tempat yang kamu tidak bisa melihat mereka. Sesungguhnya Kami telah menjadikan setan-setan itu pemimpin-pemimpin bagi orang-orang yang tidak beriman.<?php break;}
case 28:{?>Dan apabila mereka melakukan perbuatan keji, mereka berkata: &quot;Kami mendapati nenek moyang kami mengerjakan yang demikian itu, dan Allah menyuruh kami mengerjakannya. Katakanlah: &quot;Sesungguhnya Allah tidak menyuruh (mengerjakan) perbuatan yang keji.&quot; Mengapa kamu mengada-adakan terhadap Allah apa yang tidak kamu ketahui?<?php break;}
case 29:{?>Katakanlah: &quot;Tuhanku menyuruh menjalankan keadilan&quot;. Dan (katakanlah): &quot;Luruskanlah muka (diri) mu di setiap salat dan sembahlah Allah dengan mengikhlaskan ketaatanmu kepada-Nya. Sebagaimana Dia telah menciptakan kamu pada permulaan (demikian pulalah) kamu akan kembali kepada-Nya)&quot;.<?php break;}
case 30:{?>Sebahagian diberi-Nya petunjuk dan sebahagian lagi telah pasti kesesatan bagi mereka. Sesungguhnya mereka menjadikan setan-setan pelindung (mereka) selain Allah, dan mereka mengira bahwa mereka mendapat petunjuk.<?php break;}
case 31:{?>Hai anak Adam, pakailah pakaianmu yang indah di setiap (memasuki) mesjid, makan dan minumlah, dan janganlah berlebih-lebihan. Sesungguhnya Allah tidak menyukai orang-orang yang berlebih-lebihan.<?php break;}
case 32:{?>Katakanlah: &quot;Siapakah yang mengharamkan perhiasan dari Allah yang telah dikeluarkan-Nya untuk hamba-hamba-Nya dan (siapa pulakah yang mengharamkan) rezeki yang baik?&quot; Katakanlah: &quot;Semuanya itu (disediakan) bagi orang-orang yang beriman dalam kehidupan dunia, khusus (untuk mereka saja) di hari kiamat. Demikianlah Kami menjelaskan ayat-ayat itu bagi orang-orang yang mengetahui.<?php break;}
case 33:{?>Katakanlah: &quot;Tuhanku hanya mengharamkan perbuatan yang keji, baik yang nampak atau pun yang tersembunyi, dan perbuatan dosa, melanggar hak manusia tanpa alasan yang benar, (mengharamkan) mempersekutukan Allah dengan sesuatu yang Allah tidak menurunkan hujah untuk itu dan (mengharamkan) mengada-adakan terhadap Allah apa yang tidak kamu ketahui&quot;.<?php break;}
case 34:{?>Tiap-tiap umat mempunyai batas waktu; maka apabila telah datang waktunya mereka tidak dapat mengundurkannya barang sesaat pun dan tidak dapat (pula) memajukannya.<?php break;}
case 35:{?>Hai anak-anak Adam, jika datang kepadamu rasul-rasul daripada kamu yang menceritakan kepadamu ayat-ayat-Ku, maka barang siapa yang bertakwa dan mengadakan perbaikan, tidaklah ada kekhawatiran terhadap mereka dan tidak (pula) mereka bersedih hati.<?php break;}
case 36:{?>Dan orang-orang yang mendustakan ayat-ayat Kami dan menyombongkan diri terhadapnya, mereka itu penghuni-penghuni neraka; mereka kekal di dalamnya.<?php break;}
case 37:{?>Maka siapakah yang lebih lalim daripada orang yang membuat-buat dusta terhadap Allah atau mendustakan ayat-ayat-Nya? Orang-orang itu akan memperoleh bahagian yang telah ditentukan untuknya dalam Kitab (Lohmahfuz); hingga bila datang kepada mereka utusan-utusan Kami (malaikat) untuk mengambil nyawanya, (di waktu itu) utusan Kami bertanya: &quot;Di mana (berhala-berhala) yang biasa kamu sembah selain Allah?&quot; Orang-orang musyrik itu menjawab: &quot;Berhala-berhala itu semuanya telah lenyap dari kami,&quot; dan mereka mengakui terhadap diri mereka bahwa mereka adalah orang-orang yang kafir.<?php break;}
case 38:{?>Allah berfirman: &quot;Masuklah kamu sekalian ke dalam neraka bersama umat-umat jin dan manusia yang telah terdahulu sebelum kamu. Setiap suatu umat masuk (ke dalam neraka), dia mengutuk kawannya (yang menyesatkannya); sehingga apabila mereka masuk semuanya berkatalah orang-orang yang masuk kemudian di antara mereka kepada orang-orang yang masuk terdahulu: &quot;Ya Tuhan kami, mereka telah menyesatkan kami, sebab itu datangkanlah kepada mereka siksaan yang berlipat ganda dari neraka&quot;. Allah berfirman: &quot;Masing-masing mendapat (siksaan), yang berlipat ganda, akan tetapi kamu tidak mengetahui&quot;.<?php break;}
case 39:{?>Dan berkata orang-orang yang masuk terdahulu di antara mereka kepada orang-orang yang masuk kemudian: &quot;Kamu tidak mempunyai kelebihan sedikit pun atas kami, maka rasakanlah siksaan karena perbuatan yang telah kamu lakukan&quot;.<?php break;}
case 40:{?>Sesungguhnya orang-orang yang mendustakan ayat-ayat Kami dan menyombongkan diri terhadapnya, sekali-kali tidak akan dibukakan bagi mereka pintu-pintu langit dan tidak (pula) mereka masuk surga, hingga unta masuk ke lubang jarum. Demikianlah Kami memberi pembalasan kepada orang-orang yang berbuat kejahatan.<?php break;}
case 41:{?>Mereka mempunyai tikar tidur dari api neraka dan di atas mereka ada selimut (api neraka). Demikianlah Kami memberi balasan kepada orang-orang yang lalim.<?php break;}
case 42:{?>Dan orang-orang yang beriman dan mengerjakan amal-amal yang saleh, Kami tidak memikulkan kewajiban kepada diri seseorang melainkan sekedar kesanggupannya, mereka itulah penghuni-penghuni surga; mereka kekal di dalamnya.<?php break;}
case 43:{?>Dan Kami cabut segala macam dendam yang berada di dalam dada mereka; mengalir di bawah mereka sungai-sungai dan mereka berkata: &quot;Segala puji bagi Allah yang telah menunjuki kami kepada (surga) ini. Dan kami sekali-kali tidak akan mendapat petunjuk kalau Allah tidak memberi kami petunjuk. Sesungguhnya telah datang rasul-rasul Tuhan kami, membawa kebenaran&quot;. Dan diserukan kepada mereka: &quot;Itulah surga yang diwariskan kepadamu, disebabkan apa yang dahulu kamu kerjakan.&quot;<?php break;}
case 44:{?>Dan penghuni-penghuni surga berseru kepada penghuni-penghuni neraka (dengan mengatakan): &quot;Sesungguhnya kami dengan sebenarnya telah memperoleh apa yang Tuhan kami menjanjikannya kepada kami. Maka apakah kamu telah memperoleh dengan sebenarnya apa (azab) yang Tuhan kamu menjanjikannya (kepadamu)?&quot; Mereka (penduduk neraka) menjawab: &quot;Betul&quot;. Kemudian seorang penyeru (malaikat) mengumumkan di antara kedua golongan itu: &quot;Kutukan Allah ditimpakan kepada orang-orang yang lalim,<?php break;}
case 45:{?>(yaitu) orang-orang yang menghalang-halangi (manusia) dari jalan Allah dan menginginkan agar jalan itu menjadi bengkok, dan mereka kafir kepada kehidupan akhirat.&quot;<?php break;}
case 46:{?>Dan di antara keduanya (penghuni surga dan neraka) ada batas; dan di atas A'raaf itu ada orang-orang yang mengenal masing-masing dari dua golongan itu dengan tanda-tanda mereka. Dan mereka menyeru penduduk surga:&quot; Salaamun 'alaikum&quot;. Mereka belum lagi memasukinya, sedang mereka ingin segera (memasukinya).<?php break;}
case 47:{?>Dan apabila pandangan mereka dialihkan ke arah penghuni neraka, mereka berkata: &quot;Ya Tuhan kami, janganlah Engkau tempatkan kami bersama-sama orang-orang yang lalim itu&quot;.<?php break;}
case 48:{?>Dan orang-orang yang di atas A'raaf memanggil beberapa orang (pemuka-pemuka orang kafir) yang mereka mengenalnya dengan tanda-tandanya dengan mengatakan: &quot;Harta yang kamu kumpulkan dan apa yang selalu kamu sombongkan itu, tidaklah memberi manfaat kepadamu&quot;.<?php break;}
case 49:{?>(Orang-orang di atas A'raaf bertanya kepada penghuni neraka): &quot;Itukah orang-orang yang kamu telah bersumpah bahwa mereka tidak akan mendapat rahmat Allah?&quot; (Kepada orang mukmin itu dikatakan): &quot;Masuklah ke dalam surga, tidak ada kekhawatiran terhadapmu dan tidak (pula) kamu bersedih hati.<?php break;}
case 50:{?>Dan penghuni neraka menyeru penghuni surga: &quot;Limpahkanlah kepada kami sedikit air atau makanan yang telah dirizekikan Allah kepadamu&quot;. Mereka (penghuni surga) menjawab: &quot;Sesungguhnya Allah telah mengharamkan keduanya itu atas orang-orang kafir,<?php break;}
case 51:{?>(yaitu) orang-orang yang menjadikan agama mereka sebagai main-main dan senda gurau, dan kehidupan dunia telah menipu mereka&quot;. Maka pada hari (kiamat) ini, Kami melupakan mereka sebagaimana mereka melupakan pertemuan mereka dengan hari ini, dan (sebagaimana) mereka selalu mengingkari ayat-ayat Kami.<?php break;}
case 52:{?>Dan sesungguhnya Kami telah mendatangkan sebuah Kitab (Al Qur'an) kepada mereka yang Kami telah menjelaskannya atas dasar pengetahuan Kami; menjadi petunjuk dan rahmat bagi orang-orang yang beriman.<?php break;}
case 53:{?>Tiadalah mereka menunggu-nunggu kecuali (terlaksananya kebenaran) Al Qur'an itu. Pada hari datangnya kebenaran pemberitaan Al Qur'an itu, berkatalah orang-orang yang melupakannya sebelum itu: &quot;Sesungguhnya telah datang rasul-rasul Tuhan kami membawa yang hak, maka adakah bagi kami pemberi syafa'at yang akan memberi syafaat bagi kami, atau dapatkah kami dikembalikan (ke dunia) sehingga kami dapat beramal yang lain dari yang pernah kami amalkan?&quot; Sungguh mereka telah merugikan diri mereka sendiri dan telah lenyaplah dari mereka tuhan-tuhan yang mereka ada-adakan.<?php break;}
case 54:{?>Sesungguhnya Tuhan kamu ialah Allah yang telah menciptakan langit dan bumi dalam enam masa, lalu Dia bersemayam di atas Arasy. Dia menutupkan malam kepada siang yang mengikutinya dengan cepat, dan (diciptakan-Nya pula) matahari, bulan dan bintang-bintang (masing-masing) tunduk kepada perintah-Nya. Ingatlah, menciptakan dan memerintah hanyalah hak Allah. Maha Suci Allah, Tuhan semesta alam.<?php break;}
case 55:{?>Berdoalah kepada Tuhanmu dengan berendah diri dan suara yang lembut. Sesungguhnya Allah tidak menyukai orang-orang yang melampaui batas.<?php break;}
case 56:{?>Dan janganlah kamu membuat kerusakan di muka bumi, sesudah (Allah) memperbaikinya dan berdoalah kepada-Nya dengan rasa takut (tidak akan diterima) dan harapan (akan dikabulkan). Sesungguhnya rahmat Allah amat dekat kepada orang-orang yang berbuat baik.<?php break;}
case 57:{?>Dan Dialah yang meniupkan angin sebagai pembawa berita gembira sebelum kedatangan rahmat-Nya (hujan); hingga apabila angin itu telah membawa awan mendung, Kami halau ke suatu daerah yang tandus, lalu Kami turunkan hujan di daerah itu, maka Kami keluarkan dengan sebab hujan itu pelbagai macam buah-buahan. Seperti itulah Kami membangkitkan orang-orang yang telah mati, mudah-mudahan kamu mengambil pelajaran.<?php break;}
case 58:{?>Dan tanah yang baik, tanaman-tanamannya tumbuh subur dengan seizin Allah; dan tanah yang tidak subur, tanaman-tanamannya hanya tumbuh merana. Demikianlah Kami mengulangi tanda-tanda kebesaran (Kami) bagi orang-orang yang bersyukur.<?php break;}
case 59:{?>Sesungguhnya Kami telah mengutus Nuh kepada kaumnya lalu ia berkata: &quot;Wahai kaumku sembahlah Allah, sekali-kali tak ada Tuhan bagimu selain-Nya.&quot; Sesungguhnya (kalau kamu tidak menyembah Allah), aku takut kamu akan ditimpa azab hari yang besar (kiamat).<?php break;}
case 60:{?>Pemuka-pemuka dari kaumnya berkata: &quot;Sesungguhnya kami memandang kamu berada dalam kesesatan yang nyata&quot;.<?php break;}
case 61:{?>Nuh menjawab: &quot;Hai kaumku, tak ada padaku kesesatan sedikit pun tetapi aku adalah utusan dari Tuhan semesta alam&quot;.<?php break;}
case 62:{?>&quot;Aku sampaikan kepadamu amanat-amanah Tuhanku dan aku memberi nasihat kepadamu, dan aku mengetahui dari Allah apa yang tidak kamu ketahui&quot;.<?php break;}
case 63:{?>Dan apakah kamu (tidak percaya) dan heran bahwa datang kepada kamu peringatan dari Tuhanmu dengan perantaraan seorang laki-laki dari golonganmu agar dia memberi peringatan kepadamu dan mudah-mudahan kamu bertakwa dan supaya kamu mendapat rahmat?<?php break;}
case 64:{?>Maka mereka mendustakan Nuh, kemudian Kami selamatkan dia dan orang-orang yang bersamanya di dalam bahtera, dan Kami tenggelamkan orang-orang yang mendustakan ayat-ayat Kami. Sesungguhnya mereka adalah kaum yang buta (mata hatinya).<?php break;}
case 65:{?>Dan (Kami telah mengutus) kepada kaum Ad saudara mereka, Hud. Ia berkata: &quot;Hai kaumku, sembahlah Allah, sekali-kali tidak ada Tuhan bagimu selain-Nya. Maka mengapa kamu tidak bertakwa kepada-Nya?&quot;<?php break;}
case 66:{?>Pemuka-pemuka yang kafir dari kaumnya berkata: &quot;Sesungguhnya kami benar-benar memandang kamu dalam keadaan kurang akal dan sesungguhnya kami menganggap kamu termasuk orang-orang yang berdusta&quot;.<?php break;}
case 67:{?>Hud berkata: &quot;Hai kaumku, tidak ada padaku kekurangan akal sedikit pun, tetapi aku ini adalah utusan dari Tuhan semesta alam.<?php break;}
case 68:{?>Aku menyampaikan amanat-amanah Tuhanku kepadamu dan aku hanyalah pemberi nasihat yang terpercaya bagimu&quot;.<?php break;}
case 69:{?>Apakah kamu (tidak percaya) dan heran bahwa datang kepadamu peringatan dari Tuhanmu yang dibawa oleh seorang laki-laki di antaramu untuk memberi peringatan kepadamu? Dan ingatlah oleh kamu sekalian di waktu Allah menjadikan kamu sebagai pengganti-pengganti (yang berkuasa) sesudah lenyapnya kaum Nuh, dan Tuhan telah melebihkan kekuatan tubuh dan perawakanmu (daripada Kaum Nuh itu). Maka ingatlah nikmat-nikmat Allah supaya kamu mendapat keberuntungan.<?php break;}
case 70:{?>Mereka berkata: &quot;Apakah kamu datang kepada kami, agar kami hanya menyembah Allah saja dan meninggalkan apa yang biasa disembah oleh bapak-bapak kami? Maka datangkanlah azab yang kamu ancamkan kepada kami jika kamu termasuk orang-orang yang benar&quot;.<?php break;}
case 71:{?>Ia berkata: &quot;Sungguh sudah pasti kamu akan ditimpa azab dan kemarahan dari Tuhanmu&quot;. Apakah kamu sekalian hendak berbantah dengan aku tentang nama-nama (berhala) yang kamu dan nenek moyangmu menamakannya, padahal Allah sekali-kali tidak menurunkan hujah untuk itu? Maka tunggulah (azab itu), sesungguhnya aku juga termasuk orang yang menunggu bersama kamu&quot;.<?php break;}
case 72:{?>Maka Kami selamatkan Hud beserta orang-orang yang bersamanya dengan rahmat yang besar dari Kami, dan kami tumpas orang-orang yang mendustakan ayat-ayat Kami, dan tiadalah mereka orang-orang yang beriman.<?php break;}
case 73:{?>Dan (Kami telah mengutus) kepada kaum Tsamud saudara mereka, Saleh. Ia berkata. &quot;Hai kaumku, sembahlah Allah, sekali-kali tidak ada Tuhan bagimu selain-Nya. Sesungguhnya telah datang bukti yang nyata kepadamu dari Tuhanmu. Unta betina Allah ini menjadi tanda bagimu, maka biarkanlah dia makan di bumi Allah, dan janganlah kamu mengganggunya, dengan gangguan apa pun, (yang karenanya) kamu akan ditimpa siksaan yang pedih.&quot;<?php break;}
case 74:{?>Dan ingatlah olehmu di waktu Tuhan menjadikan kamu pengganti-pengganti (yang berkuasa) sesudah kaum 'Aad dan memberikan tempat bagimu di bumi. Kamu dirikan istana-istana di tanah-tanahnya yang datar dan kamu pahat gunung-gunungnya untuk dijadikan rumah; maka ingatlah nikmat-nikmat Allah dan janganlah kamu merajalela di muka bumi membuat kerusakan.<?php break;}
case 75:{?>Pemuka-pemuka yang menyombongkan diri di antara kaumnya berkata kepada orang-orang yang dianggap lemah yang telah beriman di antara mereka: &quot;Tahukah kamu bahwa Saleh di utus (menjadi rasul) oleh Tuhannya?&quot;. Mereka menjawab: &quot;Sesungguhnya kami beriman kepada wahyu, yang Saleh diutus untuk menyampaikannya&quot;.<?php break;}
case 76:{?>Orang-orang yang menyombongkan diri berkata: &quot;Sesungguhnya kami adalah orang yang tidak percaya kepada apa yang kamu imani itu&quot;.<?php break;}
case 77:{?>Kemudian mereka sembelih unta betina itu, dan mereka berlaku angkuh terhadap perintah Tuhan. Dan mereka berkata: &quot;Hai Saleh, datangkanlah apa yang kamu ancamkan itu kepada kami, jika (betul) kamu termasuk orang-orang yang diutus (Allah)&quot;.<?php break;}
case 78:{?>Karena itu mereka ditimpa gempa, maka jadilah mereka mayit-mayit yang bergelimpangan di tempat tinggal mereka.<?php break;}
case 79:{?>Maka Saleh meninggalkan mereka seraya berkata: &quot;Hai kaumku sesungguhnya aku telah menyampaikan kepadamu amanat Tuhanku, dan aku telah memberi nasihat kepadamu, tetapi kamu tidak menyukai orang-orang yang memberi nasihat&quot;.<?php break;}
case 80:{?>Dan (Kami juga telah mengutus) Lut (kepada kaumnya). (Ingatlah) tatkala dia berkata kepada kaumnya: &quot;Mengapa kamu mengerjakan perbuatan faahisyah itu, yang belum pernah dikerjakan oleh seorang pun (di dunia ini) sebelummu?&quot;<?php break;}
case 81:{?>Sesungguhnya kamu mendatangi lelaki untuk melepaskan nafsumu (kepada mereka), bukan kepada wanita, malah kamu ini adalah kaum yang melampaui batas.<?php break;}
case 82:{?>Jawab kaumnya tidak lain hanya mengatakan: &quot;Usirlah mereka (Lut dan pengikut-pengikutnya) dari kotamu ini; sesungguhnya mereka adalah orang-orang yang berpura-pura menyucikan diri.&quot;<?php break;}
case 83:{?>Kemudian Kami selamatkan dia dan pengikut-pengikutnya kecuali istrinya; dia termasuk orang-orang yang tertinggal (dibinasakan).<?php break;}
case 84:{?>Dan Kami turunkan kepada mereka hujan (batu); maka perhatikanlah bagaimana kesudahan orang-orang yang berdosa itu.<?php break;}
case 85:{?>Dan (Kami telah mengutus) kepada penduduk Madyan saudara mereka, Syuaib. Ia berkata: &quot;Hai kaumku, sembahlah Allah, sekali-kali tidak ada Tuhan bagimu selain-Nya. Sesungguhnya telah datang kepadamu bukti yang nyata dari Tuhanmu. Maka sempurnakanlah takaran dan timbangan dan janganlah kamu kurangkan bagi manusia barang-barang takaran dan timbangannya, dan janganlah kamu membuat kerusakan di muka bumi sesudah Tuhan memperbaikinya. Yang demikian itu lebih baik bagimu jika betul-betul kamu orang-orang yang beriman&quot;.<?php break;}
case 86:{?>Dan janganlah kamu duduk di tiap-tiap jalan dengan menakut-nakuti dan menghalang-halangi orang yang beriman dari jalan Allah, dan menginginkan agar jalan Allah itu menjadi bengkok. Dan ingatlah di waktu dahulunya kamu berjumlah sedikit, lalu Allah memperbanyak jumlah kamu. Dan perhatikanlah bagaimana kesudahan orang-orang yang berbuat kerusakan.<?php break;}
case 87:{?>Jika ada segolongan daripada kamu beriman kepada apa yang aku diutus untuk menyampaikannya dan ada (pula) segolongan yang tidak beriman, maka bersabarlah, hingga Allah menetapkan hukumnya di antara kita; dan Dia adalah Hakim yang sebaik-baiknya.<?php break;}
case 88:{?>Pemuka-pemuka dari kaum Syuaib yang menyombongkan diri berkata: &quot;Sesungguhnya kami akan mengusir kamu hai Syuaib dan orang-orang yang beriman bersamamu dari kota kami, kecuali kamu kembali kepada agama kami&quot;. Berkata Syuaib: &quot;Dan apakah (kamu akan mengusir kami), kendatipun kami tidak menyukainya?&quot;<?php break;}
case 89:{?>Sungguh kami mengada-adakan kebohongan yang besar terhadap Allah, jika kami kembali kepada agamamu, sesudah Allah melepaskan kami daripadanya. Dan tidaklah patut kami kembali kepadanya, kecuali jika Allah, Tuhan kami menghendaki (nya). Pengetahuan Tuhan kami meliputi segala sesuatu. Kepada Allah sajalah kami bertawakal. Ya Tuhan kami, berilah keputusan antara kami dan kaum kami dengan hak (adil) dan Engkaulah Pemberi keputusan yang sebaik-baiknya.<?php break;}
case 90:{?>Pemuka-pemuka kaum Syuaib yang kafir berkata (kepada sesamanya): &quot;Sesungguhnya jika kamu mengikuti Syuaib, tentu kamu jika berbuat demikian (menjadi) orang-orang yang merugi&quot;.<?php break;}
case 91:{?>Kemudian mereka ditimpa gempa, maka jadilah mereka mayit-mayit yang bergelimpangan di dalam rumah-rumah mereka,<?php break;}
case 92:{?>(yaitu) orang-orang yang mendustakan Syuaib seolah-olah mereka belum pernah berdiam di kota itu; orang-orang yang mendustakan Syuaib mereka itulah orang-orang yang merugi.<?php break;}
case 93:{?>Maka Syuaib meninggalkan mereka seraya berkata: &quot;Hai kaumku, sesungguhnya aku telah menyampaikan kepadamu amanat-amanah Tuhanku dan aku telah memberi nasihat kepadamu. Maka bagaimana aku akan bersedih hati terhadap orang-orang yang kafir?&quot;<?php break;}
case 94:{?>Kami tidaklah mengutus seseorang nabi pun kepada sesuatu negeri, (lalu penduduknya mendustakan nabi itu), melainkan Kami timpakan kepada penduduknya kesempitan dan penderitaan supaya mereka tunduk dengan merendahkan diri.<?php break;}
case 95:{?>Kemudian Kami ganti kesusahan itu dengan kesenangan hingga keturunan dan harta mereka bertambah banyak, dan mereka berkata: &quot;Sesungguhnya nenek moyang kami pun telah merasai penderitaan dan kesenangan&quot;, maka Kami timpakan siksaan atas mereka dengan sekonyong-konyong sedang mereka tidak menyadarinya.<?php break;}
case 96:{?>Jika sekiranya penduduk negeri-negeri beriman dan bertakwa, pastilah Kami akan melimpahkan kepada mereka berkah dari langit dan bumi, tetapi mereka mendustakan (ayat-ayat Kami) itu, maka Kami siksa mereka disebabkan perbuatannya.<?php break;}
case 97:{?>Maka apakah penduduk negeri-negeri itu merasa aman dari kedatangan siksaan Kami kepada mereka di malam hari di waktu mereka sedang tidur?<?php break;}
case 98:{?>Atau apakah penduduk negeri-negeri itu merasa aman dari kedatangan siksaan Kami kepada mereka di waktu matahari sepenggalahan naik ketika mereka sedang bermain?<?php break;}
case 99:{?>Maka apakah mereka merasa aman dari azab Allah (yang tidak terduga-duga)? Tiadalah yang merasa aman dari azab Allah kecuali orang-orang yang merugi.<?php break;}
case 100:{?>Dan apakah belum jelas bagi orang-orang yang mempusakai suatu negeri sesudah (lenyap) penduduknya, bahwa kalau Kami menghendaki tentu Kami azab mereka karena dosa-dosanya; dan Kami kunci mati hati mereka sehingga mereka tidak dapat mendengar (pelajaran lagi)?<?php break;}
case 101:{?>Negeri-negeri (yang telah Kami binasakan) itu, Kami ceritakan sebagian dari berita-beritanya kepadamu. Dan sungguh telah datang kepada mereka rasul-rasul mereka dengan membawa bukti-bukti yang nyata, maka mereka (juga) tidak beriman kepada apa yang dahulunya mereka telah mendustakannya. Demikianlah Allah mengunci mati hati orang-orang kafir.<?php break;}
case 102:{?>Dan Kami tidak mendapati kebanyakan mereka memenuhi janji. Sesungguhnya Kami mendapati kebanyakan mereka orang-orang yang fasik.<?php break;}
case 103:{?>Kemudian Kami utus Musa sesudah rasul-rasul itu dengan membawa ayat-ayat Kami kepada Fir'aun dan pemuka-pemuka kaumnya, lalu mereka mengingkari ayat-ayat itu. Maka perhatikanlah bagaimana akibat orang-orang yang membuat kerusakan.<?php break;}
case 104:{?>Dan Musa berkata: &quot;Hai Firaun, sesungguhnya aku ini adalah seorang utusan dari Tuhan semesta alam,<?php break;}
case 105:{?>wajib atasku tidak mengatakan sesuatu terhadap Allah, kecuali yang hak. Sesungguhnya aku datang kepadamu dengan membawa bukti yang nyata dari Tuhanmu, maka lepaskanlah Bani Israel (pergi) bersama aku&quot;.<?php break;}
case 106:{?>Firaun menjawab: &quot;Jika benar kamu membawa sesuatu bukti, maka datangkanlah bukti itu jika (betul) kamu termasuk orang-orang yang benar&quot;.<?php break;}
case 107:{?>Maka Musa menjatuhkan tongkatnya, lalu seketika itu juga tongkat itu menjadi ular yang sebenarnya.<?php break;}
case 108:{?>Dan ia mengeluarkan tangannya, maka ketika itu juga tangan itu menjadi putih bercahaya (kelihatan) oleh orang-orang yang melihatnya.<?php break;}
case 109:{?>Pemuka-pemuka kaum Firaun berkata: &quot;Sesungguhnya Musa ini adalah ahli sihir yang pandai,<?php break;}
case 110:{?>yang bermaksud hendak mengeluarkan kamu dari negerimu&quot;. (Firaun berkata): &quot;Maka apakah yang kamu anjurkan?&quot;<?php break;}
case 111:{?>Pemuka-pemuka itu menjawab: &quot;Beritangguhlah dia dan saudaranya serta kirimlah ke kota-kota beberapa orang yang akan mengumpulkan (ahli-ahli sihir),<?php break;}
case 112:{?>supaya mereka membawa kepadamu semua ahli sihir yang pandai&quot;.<?php break;}
case 113:{?>Dan beberapa ahli sihir itu datang kepada Firaun mengatakan: &quot;(Apakah) sesungguhnya kami akan mendapat upah, jika kamilah yang menang?&quot;<?php break;}
case 114:{?>Firaun menjawab: &quot;Ya, dan sesungguhnya kamu benar-benar akan termasuk orang-orang yang dekat (kepadaku)&quot;.<?php break;}
case 115:{?>Ahli-ahli sihir berkata: &quot;Hai Musa, kamukah yang akan melemparkan lebih dahulu, ataukah kami yang akan melemparkan?&quot;<?php break;}
case 116:{?>Musa menjawab: &quot;Lemparkanlah (lebih dahulu)!&quot; Maka tatkala mereka melemparkan, mereka menyulap mata orang dan menjadikan orang banyak itu takut, serta mereka mendatangkan sihir yang besar (menakjubkan).<?php break;}
case 117:{?>Dan kami wahyukan kepada Musa: &quot;Lemparkanlah tongkatmu!&quot; Maka sekonyong-konyong tongkat itu menelan apa yang mereka sulapkan.<?php break;}
case 118:{?>Karena itu nyatalah yang benar dan batallah yang selalu mereka kerjakan.<?php break;}
case 119:{?>Maka mereka kalah di tempat itu dan jadilah mereka orang-orang yang hina.<?php break;}
case 120:{?>Dan ahli-ahli sihir itu serta merta meniarapkan diri dengan bersujud<?php break;}
case 121:{?>Mereka berkata: &quot;Kami beriman kepada Tuhan semesta alam,<?php break;}
case 122:{?>&quot;(yaitu) Tuhan Musa dan Harun&quot;.<?php break;}
case 123:{?>Firaun berkata: &quot;Apakah kamu beriman kepadanya sebelum aku memberi izin kepadamu?, sesungguhnya (perbuatan) ini adalah suatu muslihat yang telah kamu rencanakan di dalam kota ini, untuk mengeluarkan penduduknya dari padanya; maka kelak kamu akan mengetahui (akibat perbuatanmu ini);<?php break;}
case 124:{?>demi, sesungguhnya aku akan memotong tangan dan kakimu dengan bersilang secara bertimbal balik, kemudian sungguh-sungguh aku akan menyalib kamu semuanya.&quot;<?php break;}
case 125:{?>Ahli-ahli sihir itu menjawab: &quot;Sesungguhnya kepada Tuhanlah kami kembali.<?php break;}
case 126:{?>Dan kamu tidak menyalahkan kami, melainkan karena kami telah beriman kepada ayat-ayat Tuhan kami ketika ayat-ayat itu datang kepada kami&quot;. (Mereka berdoa): &quot;Ya Tuhan kami, limpahkanlah kesabaran kepada kami dan wafatkanlah kami dalam keadaan berserah diri (kepada-Mu)&quot;.<?php break;}
case 127:{?>Berkatalah pembesar-pembesar dari kaum Firaun (kepada Firaun): &quot;Apakah kamu membiarkan Musa dan kaumnya untuk membuat kerusakan di negeri ini (Mesir) dan meninggalkan kamu serta tuhan-tuhanmu?&quot;. Firaun menjawab: &quot;Akan kita bunuh anak-anak lelaki mereka dan kita biarkan hidup perempuan-perempuan mereka dan sesungguhnya kita berkuasa penuh di atas mereka&quot;.<?php break;}
case 128:{?>Musa berkata kepada kaumnya: &quot;Mohonlah pertolongan kepada Allah dan bersabarlah; sesungguhnya bumi (ini) kepunyaan Allah; dipusakakan-Nya kepada siapa yang dikehendaki-Nya dari hamba-hamba-Nya. Dan kesudahan yang baik adalah bagi orang-orang yang bertakwa&quot;.<?php break;}
case 129:{?>Kaum Musa berkata: &quot;Kami telah ditindas (oleh Firaun) sebelum kamu datang kepada kami dan sesudah kamu datang. Musa menjawab: &quot;Mudah-mudahan Allah membinasakan musuhmu dan menjadikan kamu khalifah di bumi (Nya), maka Allah akan melihat bagaimana perbuatanmu.<?php break;}
case 130:{?>Dan sesungguhnya Kami telah menghukum (Firaun dan) kaumnya dengan (mendatangkan) musim kemarau yang panjang dan kekurangan buah-buahan, supaya mereka mengambil pelajaran.<?php break;}
case 131:{?>Kemudian apabila datang kepada mereka kemakmuran, mereka berkata: &quot;Ini adalah karena (usaha) kami&quot;. Dan jika mereka ditimpa kesusahan, mereka lemparkan sebab kesialan itu kepada Musa dan orang-orang yang besertanya. Ketahuilah, sesungguhnya kesialan mereka itu adalah ketetapan dari Allah, akan tetapi kebanyakan mereka tidak mengetahui.<?php break;}
case 132:{?>Mereka berkata: &quot;Bagaimanapun kamu mendatangkan keterangan kepada kami untuk menyihir kami dengan keterangan itu, maka kami sekali-kali tidak akan beriman kepadamu&quot;.<?php break;}
case 133:{?>Maka Kami kirimkan kepada mereka tofan, belalang, kutu, katak dan darah sebagai bukti yang jelas, tetapi mereka tetap menyombongkan diri dan mereka adalah kaum yang berdosa.<?php break;}
case 134:{?>Dan ketika mereka ditimpa azab (yang telah diterangkan itu) mereka pun berkata: &quot;Hai Musa, mohonkanlah untuk kami kepada Tuhanmu dengan (perantaraan) kenabian yang diketahui Allah ada pada sisimu. Sesungguhnya jika kamu dapat menghilangkan azab itu daripada kami, pasti kami akan beriman kepadamu dan akan kami biarkan Bani Israel pergi bersamamu&quot;.<?php break;}
case 135:{?>Maka setelah kami hilangkan azab itu dari mereka hingga batas waktu yang mereka sampai kepadanya, tiba-tiba mereka mengingkarinya.<?php break;}
case 136:{?>Kemudian Kami menghukum mereka, maka Kami tenggelamkan mereka di laut disebabkan mereka mendustakan ayat-ayat Kami dan mereka adalah orang-orang yang melalaikan ayat-ayat Kami itu.<?php break;}
case 137:{?>Dan Kami pusakakan kepada kaum yang telah ditindas itu, negeri-negeri bahagian timur bumi dan bahagian baratnya yang telah Kami beri berkah padanya. Dan telah sempurnalah perkataan Tuhanmu yang baik (sebagai janji) untuk Bani Israel disebabkan kesabaran mereka. Dan Kami hancurkan apa yang telah dibuat Firaun dan kaumnya dan apa yang telah dibangun mereka.<?php break;}
case 138:{?>Dan Kami seberangkan Bani Israel ke seberang lautan itu, maka setelah mereka sampai kepada suatu kaum yang tetap menyembah berhala mereka, Bani Israel berkata: &quot;Hai Musa, buatlah untuk kami sebuah tuhan (berhala) sebagaimana mereka mempunyai beberapa tuhan (berhala)&quot;. Musa menjawab: &quot;Sesungguhnya kamu ini adalah kaum yang tidak mengetahui (sifat-sifat Tuhan)&quot;.<?php break;}
case 139:{?>Sesungguhnya mereka itu akan dihancurkan kepercayaan yang dianutnya dan akan batal apa yang selalu mereka kerjakan.<?php break;}
case 140:{?>Musa menjawab: &quot;Patutkah aku mencari Tuhan untuk kamu yang selain daripada Allah, padahal Dialah yang telah melebihkan kamu atas segala umat.<?php break;}
case 141:{?>Dan (ingatlah hai Bani Israel), ketika Kami menyelamatkan kamu dari (Firaun) dan kaumnya, yang mengazab kamu dengan azab yang sangat jahat, yaitu mereka membunuh anak-anak lelakimu dan membiarkan hidup wanita-wanitamu. Dan pada yang demikian itu cobaan yang besar dari Tuhanmu&quot;.<?php break;}
case 142:{?>Dan telah Kami janjikan kepada Musa (memberikan Taurat) sesudah berlalu waktu tiga puluh malam, dan Kami sempurnakan jumlah malam itu dengan sepuluh (malam lagi), maka sempurnalah waktu yang telah ditentukan Tuhannya empat puluh malam. Dan berkata Musa kepada saudaranya yaitu Harun: &quot;Gantikanlah aku dalam (memimpin) kaumku, dan perbaikilah, dan janganlah kamu mengikuti jalan orang-orang yang membuat kerusakan.&quot;<?php break;}
case 143:{?>Dan tatkala Musa datang untuk (munajat dengan Kami) pada waktu yang telah Kami tentukan dan Tuhan telah berfirman (langsung) kepadanya, berkatalah Musa: &quot;Ya Tuhanku, nampakkanlah (diri Engkau) kepadaku agar aku dapat melihat kepada Engkau&quot;. Tuhan berfirman: &quot;Kamu sekali-kali tidak sanggup melihat-Ku, tapi lihatlah ke bukit itu, maka jika ia tetap di tempatnya (sebagai sediakala) niscaya kamu dapat melihat-Ku&quot;. Tatkala Tuhannya menampakkan diri kepada gunung itu, dijadikannya gunung itu hancur luluh dan Musa pun jatuh pingsan. Maka setelah Musa sadar kembali, dia berkata: &quot;Maha Suci Engkau, aku bertobat kepada Engkau dan aku orang yang pertama-tama beriman&quot;.<?php break;}
case 144:{?>Allah berfirman: &quot;Hai Musa sesungguhnya Aku memilih (melebihkan) kamu dari manusia yang lain (di masamu) untuk membawa risalah-Ku dan untuk berbicara langsung dengan-Ku, sebab itu berpegang teguhlah kepada apa yang Aku berikan kepadamu dan hendaklah kamu termasuk orang-orang yang bersyukur&quot;.<?php break;}
case 145:{?>Dan telah Kami tuliskan untuk Musa pada luh-luh (Taurat) segala sesuatu sebagai pelajaran dan penjelasan bagi segala sesuatu; maka (Kami berfirman): &quot;Berpeganglah kepadanya dengan teguh dan suruhlah kaummu berpegang kepada (perintah-perintahnya) dengan sebaik-baiknya, nanti Aku akan memperlihatkan kepadamu negeri orang-orang yang fasik.<?php break;}
case 146:{?>Aku akan memalingkan orang-orang yang menyombongkan dirinya di muka bumi tanpa alasan yang benar dari tanda-tanda kekuasaan-Ku. Mereka jika melihat tiap-tiap ayat (Ku), mereka tidak beriman kepadanya. Dan jika mereka melihat jalan yang membawa kepada petunjuk, mereka tidak mau menempuhnya, tetapi jika mereka melihat jalan kesesatan, mereka terus menempuhnya. Yang demikian itu adalah karena mereka mendustakan ayat-ayat Kami dan mereka selalu lalai daripadanya.<?php break;}
case 147:{?>Dan orang-orang yang mendustakan ayat-ayat Kami dan mendustakan akan menemui akhirat, sia-sialah perbuatan mereka. Mereka tidak diberi balasan selain dari apa yang telah mereka kerjakan.<?php break;}
case 148:{?>Dan kaum Musa, setelah kepergian Musa ke gunung Thur membuat dari perhiasan-perhiasan (emas) mereka anak lembu yang bertubuh dan bersuara. Apakah mereka tidak mengetahui bahwa anak lembu itu tidak dapat berbicara dengan mereka dan tidak dapat (pula) menunjukkan jalan kepada mereka? Mereka menjadikannya (sebagai sembahan) dan mereka adalah orang-orang yang lalim.<?php break;}
case 149:{?>Dan setelah mereka sangat menyesali perbuatannya dan mengetahui bahwa mereka telah sesat, mereka pun berkata: &quot;Sungguh jika Tuhan kami tidak memberi rahmat kepada kami dan tidak mengampuni kami, pastilah kami menjadi orang-orang yang merugi&quot;.<?php break;}
case 150:{?>Dan tatkala Musa telah kembali kepada kaumnya dengan marah dan sedih hati berkatalah dia: &quot;Alangkah buruknya perbuatan yang kamu kerjakan sesudah kepergianku! Apakah kamu hendak mendahului janji Tuhanmu?&quot; Dan Musa pun melemparkan luh-luh (Taurat) itu dan memegang (rambut) kepala saudaranya (Harun) sambil menariknya ke arahnya. Harun berkata: &quot;Hai anak ibuku, sesungguhnya kaum ini telah menganggapku lemah dan hampir-hampir mereka membunuhku, sebab itu janganlah kamu menjadikan musuh-musuh gembira melihatku, dan janganlah kamu masukkan aku ke dalam golongan orang-orang yang lalim&quot;.<?php break;}
case 151:{?>Musa berdoa: &quot;Ya Tuhanku, ampunilah aku dan saudaraku dan masukkanlah kami ke dalam rahmat Engkau, dan Engkau adalah Maha Penyayang di antara para penyayang&quot;.<?php break;}
case 152:{?>Sesungguhnya orang-orang yang menjadikan anak lembu (sebagai sembahannya), kelak akan menimpa mereka kemurkaan dari Tuhan mereka dan kehinaan dalam kehidupan di dunia. Demikianlah Kami memberi balasan kepada orang-orang yang membuat-buat kebohongan.<?php break;}
case 153:{?>Orang-orang yang mengerjakan kejahatan, kemudian bertobat sesudah itu dan beriman; sesungguhnya Tuhan kamu, sesudah tobat yang disertai dengan iman itu adalah Maha Pengampun lagi Maha Penyayang.<?php break;}
case 154:{?>Sesudah amarah Musa menjadi reda, lalu diambilnya (kembali) luh-luh (Taurat) itu; dan dalam tulisannya terdapat petunjuk dan rahmat untuk orang-orang yang takut kepada Tuhannya.<?php break;}
case 155:{?>Dan Musa memilih tujuh puluh orang dari kaumnya untuk (memohonkan tobat kepada Kami) pada waktu yang telah Kami tentukan. Maka ketika mereka digoncang gempa bumi, Musa berkata: &quot;Ya Tuhanku, kalau Engkau kehendaki, tentulah Engkau membinasakan mereka dan aku sebelum ini. Apakah Engkau membinasakan kami karena perbuatan orang-orang yang kurang akal di antara kami? Itu hanyalah cobaan dari Engkau, Engkau sesatkan dengan cobaan itu siapa yang Engkau kehendaki dan Engkau beri petunjuk kepada siapa yang Engkau kehendaki. Engkaulah Yang memimpin kami, maka ampunilah kami dan berilah kami rahmat dan Engkaulah Pemberi ampun yang sebaik-baiknya&quot;.<?php break;}
case 156:{?>Dan tetapkanlah untuk kami kebajikan di dunia ini dan di akhirat; sesungguhnya kami kembali (bertobat) kepada Engkau. Allah berfirman: &quot;Siksa-Ku akan Kutimpakan kepada siapa yang Aku kehendaki dan rahmat-Ku meliputi segala sesuatu. Maka akan Aku tetapkan rahmat-Ku untuk orang-orang yang bertakwa, yang menunaikan zakat dan orang-orang yang beriman kepada ayat-ayat Kami&quot;.<?php break;}
case 157:{?>(Yaitu) orang-orang yang mengikut Rasul, Nabi yang umi yang (namanya) mereka dapati tertulis di dalam Taurat dan Injil yang ada di sisi mereka, yang menyuruh mereka mengerjakan yang makruf dan melarang mereka dari mengerjakan yang mungkar dan menghalalkan bagi mereka segala yang baik dan mengharamkan bagi mereka segala yang buruk dan membuang dari mereka beban-beban dan belenggu-belenggu yang ada pada mereka. Maka orang-orang yang beriman kepadanya, memuliakannya, menolongnya dan mengikuti cahaya yang terang yang diturunkan kepadanya (Al Qur'an), mereka itulah orang-orang yang beruntung.<?php break;}
case 158:{?>Katakanlah: &quot;Hai manusia sesungguhnya aku adalah utusan Allah kepadamu semua, yaitu Allah yang mempunyai kerajaan langit dan bumi; tidak ada Tuhan (yang berhak disembah) selain Dia, Yang menghidupkan dan mematikan, maka berimanlah kamu kepada Allah dan Rasul Nya, Nabi yang umi yang beriman kepada Allah dan kepada kalimat-kalimat-Nya (kitab-kitab-Nya) dan ikutilah dia, supaya kamu mendapat petunjuk&quot;.<?php break;}
case 159:{?>Dan di antara kaum Musa itu terdapat suatu umat yang memberi petunjuk (kepada manusia) dengan hak dan dengan yang hak itulah mereka menjalankan keadilan.<?php break;}
case 160:{?>Dan mereka Kami bagi menjadi dua belas suku yang masing-masingnya berjumlah besar dan Kami wahyukan kepada Musa ketika kaumnya meminta air kepadanya: &quot;Pukullah batu itu dengan tongkatmu!&quot;. Maka memancarlah daripadanya duabelas mata air. Sesungguhnya tiap-tiap suku mengetahui tempat minum masing-masing. Dan Kami naungkan awan di atas mereka dan Kami turunkan kepada mereka manna dan salwa. (Kami berfirman); &quot;Makanlah yang baik-baik dari apa yang telah Kami rezekikan kepadamu&quot;. Mereka tidak menganiaya Kami, tetapi merekalah yang selalu menganiaya dirinya sendiri.<?php break;}
case 161:{?>Dan (ingatlah), ketika dikatakan kepada mereka (Bani Israel): &quot;Diamlah di negeri ini saja (Baitulmakdis) dan makanlah dari (hasil bumi) nya di mana saja kamu kehendaki.&quot;. Dan katakanlah: &quot;Bebaskanlah kami dari dosa kami dan masukilah pintu gerbangnya sambil membungkuk, niscaya Kami ampuni kesalahan-kesalahanmu&quot;. Kelak akan Kami tambah (pahala) kepada orang-orang yang berbuat baik.<?php break;}
case 162:{?>Maka orang-orang yang lalim di antara mereka itu mengganti (perkataan itu) dengan perkataan yang tidak dikatakan kepada mereka, maka Kami timpakan kepada mereka azab dari langit disebabkan kelaliman mereka.<?php break;}
case 163:{?>Dan tanyakanlah kepada Bani Israel tentang negeri yang terletak di dekat laut ketika mereka melanggar aturan pada hari Sabtu, di waktu datang kepada mereka ikan-ikan (yang berada di sekitar) mereka terapung-apung di permukaan air, dan di hari-hari yang bukan Sabtu, ikan-ikan itu tidak datang kepada mereka. Demikianlah Kami mencoba mereka disebabkan mereka berlaku fasik.<?php break;}
case 164:{?>Dan (ingatlah) ketika suatu umat di antara mereka berkata: &quot;Mengapa kamu menasihati kaum yang Allah akan membinasakan mereka atau mengazab mereka dengan azab yang amat keras?&quot; Mereka menjawab: &quot;Agar kami mempunyai alasan (pelepas tanggung jawab) kepada Tuhanmu, dan supaya mereka bertakwa&quot;.<?php break;}
case 165:{?>Maka tatkala mereka melupakan apa yang diperingatkan kepada mereka, Kami selamatkan orang-orang yang melarang dari perbuatan jahat dan Kami timpakan kepada orang-orang yang lalim siksaan yang keras, disebabkan mereka selalu berbuat fasik.<?php break;}
case 166:{?>Maka tatkala mereka bersikap sombong terhadap apa yang mereka dilarang mengerjakannya, Kami katakan kepadanya: &quot;Jadilah kamu kera yang hina<?php break;}
case 167:{?>Dan (ingatlah), ketika Tuhanmu memberitahukan, bahwa sesungguhnya Dia akan mengirim kepada mereka (orang-orang Yahudi) sampai hari kiamat orang-orang yang akan menimpakan kepada mereka azab yang seburuk-buruknya. Sesungguhnya Tuhanmu amat cepat siksa-Nya, dan sesungguhnya Dia adalah Maha Pengampun lagi Maha Penyayang.<?php break;}
case 168:{?>Dan Kami bagi-bagi mereka di dunia ini menjadi beberapa golongan; di antaranya ada orang-orang yang saleh dan di antaranya ada yang tidak demikian. Dan Kami coba mereka dengan (nikmat) yang baik-baik dan (bencana) yang buruk-buruk, agar mereka kembali (kepada kebenaran).<?php break;}
case 169:{?>Maka datanglah sesudah mereka generasi (yang jahat) yang mewarisi Taurat, yang mengambil harta benda dunia yang rendah ini, dan berkata: &quot;Kami akan diberi ampun&quot;. Dan kelak jika datang kepada mereka harta benda dunia sebanyak itu (pula), niscaya mereka akan mengambilnya (juga). Bukankah perjanjian Taurat sudah diambil dari mereka, yaitu bahwa mereka tidak akan mengatakan terhadap Allah kecuali yang benar, padahal mereka telah mempelajari apa yang tersebut di dalamnya?. Dan kampung akhirat itu lebih baik bagi mereka yang bertakwa. Maka apakah kamu sekalian tidak mengerti?<?php break;}
case 170:{?>Dan orang-orang yang berpegang teguh dengan Al Kitab (Taurat) serta mendirikan shalat, (akan diberi pahala) karena sesungguhnya Kami tidak menyia-nyiakan pahala orang-orang yang mengadakan perbaikan.<?php break;}
case 171:{?>Dan (ingatlah), ketika Kami mengangkat bukit ke atas mereka seakan-akan bukit itu naungan awan dan mereka yakin bahwa bukit itu akan jatuh menimpa mereka. (Dan Kami katakan kepada mereka): &quot;Peganglah dengan teguh apa yang telah Kami berikan kepadamu, serta ingatlah selalu (amalkanlah) apa yang tersebut di dalamnya supaya kamu menjadi orang-orang yang bertakwa&quot;.<?php break;}
case 172:{?>Dan (ingatlah), ketika Tuhanmu mengeluarkan keturunan anak-anak Adam dari sulbi mereka dan Allah mengambil kesaksian terhadap jiwa mereka (seraya berfirman): &quot;Bukankah Aku ini Tuhanmu?&quot; Mereka menjawab: &quot;Betul (Engkau Tuhan kami), kami menjadi saksi&quot;. (Kami lakukan yang demikian itu) agar di hari kiamat kamu tidak mengatakan: &quot;Sesungguhnya kami (bani Adam) adalah orang-orang yang lengah terhadap ini (keesaan Tuhan)&quot;,<?php break;}
case 173:{?>atau agar kamu tidak mengatakan: &quot;Sesungguhnya orang-orang tua kami telah mempersekutukan Tuhan sejak dahulu, sedang kami ini adalah anak-anak keturunan yang (datang) sesudah mereka. Maka apakah Engkau akan membinasakan kami karena perbuatan orang-orang yang sesat dahulu?&quot;<?php break;}
case 174:{?>Dan demikianlah Kami menjelaskan ayat-ayat itu, agar mereka kembali (kepada kebenaran).<?php break;}
case 175:{?>Dan bacakanlah kepada mereka berita orang yang telah Kami berikan kepadanya ayat-ayat Kami (pengetahuan tentang isi Al Kitab), kemudian dia melepaskan diri daripada ayat-ayat itu lalu dia diikuti oleh setan (sampai dia tergoda), maka jadilah dia termasuk orang-orang yang sesat.<?php break;}
case 176:{?>Dan kalau Kami menghendaki, sesungguhnya Kami tinggikan (derajat) nya dengan ayat-ayat itu, tetapi dia cenderung kepada dunia dan menurutkan hawa nafsunya yang rendah, maka perumpamaannya seperti anjing jika kamu menghalaunya diulurkannya lidahnya dan jika kamu membiarkannya dia mengulurkan lidahnya (juga). Demikian itulah perumpamaan orang-orang yang mendustakan ayat-ayat Kami. Maka ceritakanlah (kepada mereka) kisah-kisah itu agar mereka berpikir.<?php break;}
case 177:{?>Amat buruklah perumpamaan orang-orang yang mendustakan ayat-ayat Kami dan kepada diri mereka sendirilah mereka berbuat lalim.<?php break;}
case 178:{?>Barang siapa yang diberi petunjuk oleh Allah, maka dialah yang mendapat petunjuk; dan barang siapa yang disesatkan Allah, maka merekalah orang-orang yang merugi.<?php break;}
case 179:{?>Dan sesungguhnya Kami jadikan untuk isi neraka Jahanam kebanyakan dari jin dan manusia, mereka mempunyai hati, tetapi tidak dipergunakannya untuk memahami (ayat-ayat Allah) dan mereka mempunyai mata (tetapi) tidak dipergunakannya untuk melihat (tanda-tanda kekuasaan Allah), dan mereka mempunyai telinga (tetapi) tidak dipergunakannya untuk mendengar (ayat-ayat Allah). Mereka itu sebagai binatang ternak, bahkan mereka lebih sesat lagi. Mereka itulah orang-orang yang lalai.<?php break;}
case 180:{?>Hanya milik Allah asmaulhusna, maka bermohonlah kepada-Nya dengan menyebut asmaaulhusna itu dan tinggalkanlah orang-orang yang menyimpang dari kebenaran dalam (menyebut) nama-nama-Nya. Nanti mereka akan mendapat balasan terhadap apa yang telah mereka kerjakan.<?php break;}
case 181:{?>Dan di antara orang-orang yang Kami ciptakan ada umat yang memberi petunjuk dengan hak, dan dengan yang hak itu (pula) mereka menjalankan keadilan.<?php break;}
case 182:{?>Dan orang-orang yang mendustakan ayat-ayat Kami, nanti Kami akan menarik mereka dengan berangsur-angsur (ke arah kebinasaan), dengan cara yang tidak mereka ketahui.<?php break;}
case 183:{?>Dan Aku memberi tangguh kepada mereka. Sesungguhnya rencana-Ku amat teguh.<?php break;}
case 184:{?>Apakah (mereka lalai) dan tidak memikirkan bahwa teman mereka (Muhammad) tidak berpenyakit gila. Dia (Muhammad itu) tidak lain hanyalah seorang pemberi peringatan lagi pemberi penjelasan.<?php break;}
case 185:{?>Dan apakah mereka tidak memperhatikan kerajaan langit dan bumi dan segala sesuatu yang diciptakan Allah, dan kemungkinan telah dekatnya kebinasaan mereka? Maka kepada berita manakah lagi mereka akan beriman selain kepada Al Qur'an itu?<?php break;}
case 186:{?>Barang siapa yang Allah sesatkan, maka baginya tak ada orang yang akan memberi petunjuk. Dan Allah membiarkan mereka terombang-ambing dalam kesesatan.<?php break;}
case 187:{?>Mereka menanyakan kepadamu tentang kiamat: &quot;Bilakah terjadinya?&quot; Katakanlah: &quot;Sesungguhnya pengetahuan tentang kiamat itu adalah pada sisi Tuhanku; tidak seorang pun yang dapat menjelaskan waktu kedatangannya selain Dia. Kiamat itu amat berat (huru-haranya bagi makhluk) yang di langit dan di bumi. Kiamat itu tidak akan datang kepadamu melainkan dengan tiba-tiba&quot;. Mereka bertanya kepadamu seakan-akan kamu benar-benar mengetahuinya. Katakanlah: &quot;Sesungguhnya pengetahuan tentang hari kiamat itu adalah di sisi Allah, tetapi kebanyakan manusia tidak mengetahui&quot;.<?php break;}
case 188:{?>Katakanlah: &quot;Aku tidak berkuasa menarik kemanfaatan bagi diriku dan tidak (pula) menolak kemudaratan kecuali yang dikehendaki Allah. Dan sekiranya aku mengetahui yang gaib, tentulah aku membuat kebajikan sebanyak-banyaknya dan aku tidak akan ditimpa kemudaratan. Aku tidak lain hanyalah pemberi peringatan, dan pembawa berita gembira bagi orang-orang yang beriman&quot;.<?php break;}
case 189:{?>Dialah Yang menciptakan kamu dari diri yang satu dan daripadanya Dia menciptakan istrinya, agar dia merasa senang kepadanya. Maka setelah dicampurinya, istrinya itu mengandung kandungan yang ringan, dan teruslah dia merasa ringan (beberapa waktu). Kemudian tatkala dia merasa berat, keduanya (suami istri) bermohon kepada Allah, Tuhannya seraya berkata: &quot;Sesungguhnya jika Engkau memberi kami anak yang sempurna, tentulah kami termasuk orang-orang yang bersyukur&quot;.<?php break;}
case 190:{?>Tatkala Allah memberi kepada keduanya seorang anak yang sempurna, maka keduanya menjadikan sekutu bagi Allah terhadap anak yang telah dianugerahkan-Nya kepada keduanya itu. Maka Maha Tinggi Allah dari apa yang mereka persekutukan.<?php break;}
case 191:{?>Apakah mereka mempersekutukan (Allah dengan) berhala-berhala yang tak dapat menciptakan sesuatu pun? Sedangkan berhala-berhala itu sendiri buatan orang.<?php break;}
case 192:{?>Dan berhala-berhala itu tidak mampu memberi pertolongan kepada penyembah-penyembahnya dan kepada dirinya sendiri pun berhala-berhala itu tidak dapat memberi pertolongan.<?php break;}
case 193:{?>Dan jika kamu (hai orang-orang musyrik) menyerunya (berhala) untuk memberi petunjuk kepadamu, tidaklah berhala-berhala itu dapat memperkenankan seruanmu; sama saja (hasilnya) buat kamu menyeru mereka atau pun kamu berdiam diri.<?php break;}
case 194:{?>Sesungguhnya berhala-berhala yang kamu seru selain Allah itu adalah makhluk (yang lemah) yang serupa juga dengan kamu. Maka serulah berhala-berhala itu lalu biarkanlah mereka memperkenankan permintaanmu, jika kamu memang orang-orang yang benar.<?php break;}
case 195:{?>Apakah berhala-berhala mempunyai kaki yang dengan itu ia dapat berjalan, atau mempunyai tangan yang dengan itu ia dapat memegang dengan keras, atau mempunyai mata yang dengan itu ia dapat melihat, atau mempunyai telinga yang dengan itu ia dapat mendengar? Katakanlah: &quot;Panggillah berhala-berhalamu yang kamu jadikan sekutu Allah, kemudian lakukanlah tipu daya (untuk mencelakakan) ku, tanpa memberi tangguh (kepada ku).<?php break;}
case 196:{?>Sesungguhnya pelindungku ialah Allah yang telah menurunkan Al Kitab (Al Qur'an) dan Dia melindungi orang-orang yang saleh.<?php break;}
case 197:{?>Dan berhala-berhala yang kamu seru selain Allah tidaklah sanggup menolongmu, bahkan tidak dapat menolong dirinya sendiri.&quot;<?php break;}
case 198:{?>Dan jika kamu sekalian menyeru (berberhala-berhala) untuk memberi petunjuk, niscaya berhala-berhala itu tidak dapat mendengarnya. Dan kamu melihat berhala-berhala itu memandang kepadamu padahal ia tidak melihat.<?php break;}
case 199:{?>Jadilah engkau pemaaf dan suruhlah orang mengerjakan yang makruf, serta berpalinglah daripada orang-orang yang bodoh.<?php break;}
case 200:{?>Dan jika kamu ditimpa sesuatu godaan setan, maka berlindunglah kepada Allah. Sesungguhnya Allah Maha Mendengar lagi Maha Mengetahui.<?php break;}
case 201:{?>Sesungguhnya orang-orang yang bertakwa bila mereka ditimpa was-was dari setan, mereka ingat kepada Allah, maka ketika itu juga mereka melihat kesalahan-kesalahannya.<?php break;}
case 202:{?>Dan teman-teman mereka (orang-orang kafir dan fasik) membantu setan-setan dalam menyesatkan dan mereka tidak henti-hentinya (menyesatkan).<?php break;}
case 203:{?>Dan apabila kamu tidak membawa suatu ayat Al Qur'an kepada mereka, mereka berkata: &quot;Mengapa tidak kamu buat sendiri ayat itu?&quot; Katakanlah: &quot;Sesungguhnya aku hanya mengikut apa yang diwahyukan dari Tuhanku kepadaku. Al Qur'an ini adalah bukti-bukti yang nyata dari Tuhanmu, petunjuk dan rahmat bagi orang-orang yang beriman.<?php break;}
case 204:{?>Dan apabila dibacakan Al Qur'an, maka dengarkanlah baik-baik, dan perhatikanlah dengan tenang agar kamu mendapat rahmat.<?php break;}
case 205:{?>Dan sebutlah (nama) Tuhanmu dalam hatimu dengan merendahkan diri dan rasa takut, dan dengan tidak mengeraskan suara, di waktu pagi dan petang, dan janganlah kamu termasuk orang-orang yang lalai.<?php break;}
case 206:{?>Sesungguhnya malaikat-malaikat yang ada di sisi Tuhanmu tidaklah merasa enggan menyembah Allah dan mereka mentasbihkan-Nya dan hanya kepada-Nya lah mereka bersujud.<?php break;}
}?>