<?php 
switch($verse){
case 1:{?>Mereka menanyakan kepadamu tentang (pembagian) harta rampasan perang. Katakanlah: &quot;Harta rampasan perang itu kepunyaan Allah dan Rasul, sebab itu bertakwalah kepada Allah dan perbaikilah perhubungan di antara sesamamu, dan taatlah kepada Allah dan Rasul-Nya jika kamu adalah orang-orang yang beriman&quot;.<?php break;}
case 2:{?>Sesungguhnya orang-orang yang beriman itu adalah mereka yang apabila disebut nama Allah gemetarlah hati mereka, dan apabila dibacakan kepada mereka ayat-ayat-Nya bertambahlah iman mereka (karenanya) dan kepada Tuhan-lah mereka bertawakal,<?php break;}
case 3:{?>(yaitu) orang-orang yang mendirikan salat dan yang menafkahkan sebagian dari rezeki yang Kami berikan kepada mereka.<?php break;}
case 4:{?>Itulah orang-orang yang beriman dengan sebenar-benarnya. Mereka akan memperoleh beberapa derajat ketinggian di sisi Tuhannya dan ampunan serta rezeki (nikmat) yang mulia.<?php break;}
case 5:{?>Sebagaimana Tuhanmu menyuruhmu pergi dari rumahmu dengan kebenaran, padahal sesungguhnya sebagian dari orang-orang yang beriman itu tidak menyukainya,<?php break;}
case 6:{?>mereka membantahmu tentang kebenaran sesudah nyata (bahwa mereka pasti menang), seolah-olah mereka dihalau kepada kematian, sedang mereka melihat (sebab-sebab kematian itu).<?php break;}
case 7:{?>Dan (ingatlah), ketika Allah menjanjikan kepadamu bahwa salah satu dari dua golongan (yang kamu hadapi) adalah untukmu, sedang kamu menginginkan bahwa yang tidak mempunyai kekuatan senjatalah yang untukmu, dan Allah menghendaki untuk membenarkan yang benar dengan ayat-ayat-Nya dan memusnahkan orang-orang kafir,<?php break;}
case 8:{?>agar Allah menetapkan yang hak (Islam) dan membatalkan yang batil (syirik) walaupun orang-orang yang berdosa (musyrik) itu tidak menyukainya.<?php break;}
case 9:{?>(Ingatlah), ketika kamu memohon pertolongan kepada Tuhanmu, lalu diperkenankan-Nya bagimu: &quot;Sesungguhnya Aku akan mendatangkan bala bantuan kepadamu dengan seribu malaikat yang datang berturut-turut&quot;.<?php break;}
case 10:{?>Dan Allah tidak menjadikannya (mengirim bala bantuan itu), melainkan sebagai kabar gembira dan agar hatimu menjadi tenteram karenanya. Dan kemenangan itu hanyalah dari sisi Allah. Sesungguhnya Allah Maha Perkasa lagi Maha Bijaksana.<?php break;}
case 11:{?>(Ingatlah), ketika Allah menjadikan kamu mengantuk sebagai suatu penentraman daripada-Nya, dan Allah menurunkan kepadamu hujan dari langit untuk menyucikan kamu dengan hujan itu dan menghilangkan dari kamu gangguan-gangguan setan dan untuk menguatkan hatimu dan memperteguh dengannya telapak kaki (mu).<?php break;}
case 12:{?>(Ingatlah), ketika Tuhanmu mewahyukan kepada para malaikat: &quot;Sesungguhnya Aku bersama kamu, maka teguhkanlah (pendirian) orang-orang yang telah beriman&quot;. Kelak akan Aku jatuhkan rasa ketakutan ke dalam hati orang-orang kafir, maka penggallah kepala mereka dan pancunglah tiap-tiap ujung jari mereka.<?php break;}
case 13:{?>(Ketentuan) yang demikian itu adalah karena sesungguhnya mereka menentang Allah dan Rasul-Nya; dan barang siapa menentang Allah dan Rasul-Nya, maka sesungguhnya Allah amat keras siksaan-Nya.<?php break;}
case 14:{?>Itulah (hukum dunia yang ditimpakan atasmu), maka rasakanlah hukuman itu. Sesungguhnya bagi orang-orang yang kafir itu ada (lagi) azab neraka.<?php break;}
case 15:{?>Hai orang-orang yang beriman, apabila kamu bertemu dengan orang-orang yang kafir yang sedang menyerangmu, maka janganlah kamu membelakangi mereka (mundur).<?php break;}
case 16:{?>Barang siapa yang membelakangi mereka (mundur) di waktu itu, kecuali berbelok untuk (siasat) perang atau hendak menggabungkan diri dengan pasukan yang lain, maka sesungguhnya orang itu kembali dengan membawa kemurkaan dari Allah, dan tempatnya ialah neraka Jahanam. Dan amat buruklah tempat kembalinya.<?php break;}
case 17:{?>Maka (yang sebenarnya) bukan kamu yang membunuh mereka, akan tetapi Allah-lah yang membunuh mereka, dan bukan kamu yang melempar ketika kamu melempar, tetapi Allah-lah yang melempar. (Allah berbuat demikian untuk membinasakan mereka) dan untuk memberi kemenangan kepada orang-orang mukmin, dengan kemenangan yang baik. Sesungguhnya Allah Maha Mendengar lagi Maha Mengetahui.<?php break;}
case 18:{?>Itulah (karunia Allah yang dilimpahkan kepadamu), dan sesungguhnya Allah melemahkan tipu daya orang-orang yang kafir.<?php break;}
case 19:{?>Jika kamu (orang-orang musyrikin) mencari keputusan, maka telah datang keputusan kepadamu; dan jika kamu berhenti; maka itulah yang lebih baik bagimu; dan jika kamu kembali, niscaya Kami kembali (pula); dan angkatan perangmu sekali-kali tidak akan dapat menolak dari kamu sesuatu bahaya pun, biar pun dia banyak dan sesungguhnya Allah beserta orang-orang yang beriman.<?php break;}
case 20:{?>Hai orang-orang yang beriman, taatlah kepada Allah dan Rasul-Nya, dan janganlah kamu berpaling daripada-Nya, sedang kamu mendengar (perintah-perintah-Nya),<?php break;}
case 21:{?>dan janganlah kamu menjadi sebagai orang-orang (munafik) yang berkata: &quot;Kami mendengarkan, padahal mereka tidak mendengarkan.<?php break;}
case 22:{?>Sesungguhnya binatang (makhluk) yang seburuk-buruknya pada sisi Allah ialah orang-orang yang pekak dan tuli yang tidak mengerti apa-apa pun.<?php break;}
case 23:{?>Kalau kiranya Allah mengetahui kebaikan ada pada mereka, tentulah Allah menjadikan mereka dapat mendengar. Dan jika Allah menjadikan mereka dapat mendengar, niscaya mereka pasti berpaling juga, sedang mereka memalingkan diri (dari apa yang mereka dengar itu).<?php break;}
case 24:{?>Hai orang-orang yang beriman, penuhilah seruan Allah dan seruan Rasul apabila Rasul menyeru kamu kepada suatu yang memberi kehidupan kepada kamu, dan ketahuilah bahwa sesungguhnya Allah membatasi antara manusia dan hatinya dan sesungguhnya kepada-Nya lah kamu akan dikumpulkan.<?php break;}
case 25:{?>Dan peliharalah dirimu daripada siksaan yang tidak khusus menimpa orang-orang yang lalim saja di antara kamu. Dan ketahuilah bahwa Allah amat keras siksaan-Nya.<?php break;}
case 26:{?>Dan ingatlah (hai para muhajirin) ketika kamu masih berjumlah sedikit, lagi tertindas di muka bumi (Mekah), kamu takut orang-orang (Mekah) akan menculik kamu, maka Allah memberi kamu tempat menetap (Madinah) dan dijadikan-Nya kamu kuat dengan pertolongan-Nya dan diberi-Nya kamu rezeki dari yang baik-baik agar kamu bersyukur.<?php break;}
case 27:{?>Hai orang-orang yang beriman, janganlah kamu mengkhianati Allah dan Rasul (Muhammad) dan (juga) janganlah kamu mengkhianati amanat-amanah yang dipercayakan kepadamu, sedang kamu mengetahui.<?php break;}
case 28:{?>Dan ketahuilah, bahwa hartamu dan anak-anakmu itu hanyalah sebagai cobaan dan sesungguhnya di sisi Allah-lah pahala yang besar.<?php break;}
case 29:{?>Hai orang-orang yang beriman, jika kamu bertakwa kepada Allah, niscaya Dia akan memberikan kepadamu furqaan dan menghapuskan segala kesalahan-kesalahanmu dan mengampuni (dosa-dosa) mu. Dan Allah mempunyai karunia yang besar.<?php break;}
case 30:{?>Dan (ingatlah), ketika orang-orang kafir (Quraisy) memikirkan daya upaya terhadapmu untuk menangkap dan memenjarakanmu atau membunuhmu, atau mengusirmu. Mereka memikirkan tipu daya dan Allah menggagalkan tipu daya itu. Dan Allah sebaik-baik Pembalas tipu daya.<?php break;}
case 31:{?>Dan apabila dibacakan kepada mereka ayat-ayat Kami, mereka berkata: &quot;Sesungguhnya kami telah mendengar (ayat-ayat yang seperti ini), kalau kami menghendaki niscaya kami dapat membacakan yang seperti ini, (Al Qur'an) ini tidak lain hanyalah dongengan-dongengan orang-orang purbakala&quot;.<?php break;}
case 32:{?>Dan (ingatlah), ketika mereka (orang-orang musyrik) berkata: &quot;Ya Allah, jika betul (Al Qur'an) ini, dialah yang benar dari sisi Engkau, maka hujanilah kami dengan batu dari langit, atau datangkanlah kepada kami azab yang pedih&quot;.<?php break;}
case 33:{?>Dan Allah sekali-kali tidak akan mengazab mereka, sedang kamu berada di antara mereka. Dan tidaklah (pula) Allah akan mengazab mereka, sedang mereka meminta ampun.<?php break;}
case 34:{?>Kenapa Allah tidak mengazab mereka padahal mereka menghalangi orang untuk (mendatangi) Masjidilharam dan mereka bukanlah orang-orang yang berhak menguasainya? Orang-orang yang berhak menguasai (nya), hanyalah orang-orang yang bertakwa, tetapi kebanyakan mereka tidak mengetahui.<?php break;}
case 35:{?>Sembahyang mereka di sekitar Baitullah itu, lain tidak hanyalah siulan dan tepukan tangan. Maka rasakanlah azab disebabkan kekafiranmu itu.<?php break;}
case 36:{?>Sesungguhnya orang-orang yang kafir itu, menafkahkan harta mereka untuk menghalangi (orang) dari jalan Allah. Mereka akan menafkahkan harta itu, kemudian menjadi sesalan bagi mereka, dan mereka akan dikalahkan. Dan ke dalam neraka Jahanamlah orang-orang yang kafir itu dikumpulkan,<?php break;}
case 37:{?>supaya Allah memisahkan (golongan) yang buruk dari yang baik dan menjadikan (golongan) yang buruk itu sebagiannya di atas sebagian yang lain, lalu kesemuanya ditumpukkan-Nya, dan dimasukkan-Nya ke dalam neraka Jahanam. Mereka itulah orang-orang yang merugi.<?php break;}
case 38:{?>Katakanlah kepada orang-orang yang kafir itu: &quot;Jika mereka berhenti (dari kekafirannya), niscaya Allah akan mengampuni mereka tentang dosa-dosa mereka yang sudah lalu; dan jika mereka kembali lagi sesungguhnya akan berlaku (kepada mereka) sunah (Allah terhadap) orang-orang dahulu&quot;.<?php break;}
case 39:{?>Dan perangilah mereka, supaya jangan ada fitnah dan supaya agama itu semata-mata untuk Allah. Jika mereka berhenti (dari kekafiran), maka sesungguhnya Allah Maha Melihat apa yang mereka kerjakan.<?php break;}
case 40:{?>Dan jika mereka berpaling, maka ketahuilah bahwasanya Allah Pelindungmu. Dia adalah sebaik-baik Pelindung dan sebaik-baik Penolong.<?php break;}
case 41:{?>Ketahuilah, sesungguhnya apa saja yang dapat kamu peroleh sebagai rampasan perang, maka sesungguhnya seperlima untuk Allah, Rasul, kerabat Rasul, anak-anak yatim, orang-orang miskin dan ibnusabil, jika kamu beriman kepada Allah dan kepada apa yang Kami turunkan kepada hamba Kami (Muhammad) di hari Furqaan, yaitu di hari bertemunya dua pasukan. Dan Allah Maha Kuasa atas segala sesuatu.<?php break;}
case 42:{?>(Yaitu di hari) ketika kamu berada di pinggir lembah yang dekat dan mereka berada di pinggir lembah yang jauh sedang kafilah itu berada di bawah kamu. Sekiranya kamu mengadakan persetujuan (untuk menentukan hari pertempuran), pastilah kamu tidak sependapat dalam menentukan hari pertempuran itu, akan tetapi (Allah mempertemukan dua pasukan itu) agar Dia melakukan suatu urusan yang mesti dilaksanakan, yaitu agar orang yang binasa itu binasanya dengan keterangan yang nyata dan agar orang yang hidup itu hidupnya dengan keterangan yang nyata (pula). Sesungguhnya Allah Maha Mendengar lagi Maha Mengetahui,<?php break;}
case 43:{?>(yaitu) ketika Allah menampakkan mereka kepadamu di dalam mimpimu (berjumlah) sedikit. Dan sekiranya Allah memperlihatkan mereka kepada kamu (berjumlah) banyak tentu saja kamu menjadi gentar dan tentu saja kamu akan berbantah-bantahan dalam urusan itu, akan tetapi Allah telah menyelamatkan kamu. Sesungguhnya Allah Maha Mengetahui segala isi hati.<?php break;}
case 44:{?>Dan ketika Allah menampakkan mereka kepada kamu sekalian, ketika kamu berjumpa dengan mereka berjumlah sedikit pada penglihatan matamu dan kamu ditampakkan-Nya berjumlah sedikit pada penglihatan mata mereka, karena Allah hendak melakukan suatu urusan yang mesti dilaksanakan. Dan hanya kepada Allah-lah dikembalikan segala urusan.<?php break;}
case 45:{?>Hai orang-orang yang beriman, apabila kamu memerangi pasukan (musuh), maka berteguh hatilah kamu dan sebutlah (nama) Allah sebanyak-banyaknya agar kamu beruntung.<?php break;}
case 46:{?>Dan taatlah kepada Allah dan Rasul-Nya dan janganlah kamu berbantah-bantahan, yang menyebabkan kamu menjadi gentar dan hilang kekuatanmu dan bersabarlah. Sesungguhnya Allah beserta orang-orang yang sabar.<?php break;}
case 47:{?>Dan janganlah kamu menjadi seperti orang-orang yang keluar dari kampungnya dengan rasa angkuh dan dengan maksud ria kepada manusia serta menghalangi (orang) dari jalan Allah. Dan (ilmu) Allah meliputi apa yang mereka kerjakan.<?php break;}
case 48:{?>Dan ketika setan menjadikan mereka memandang baik pekerjaan mereka dan mengatakan: &quot;Tidak ada seorang manusia pun yang dapat menang terhadap kamu pada hari ini, dan sesungguhnya saya ini adalah pelindungmu&quot;. Maka tatkala kedua pasukan itu telah dapat saling lihat melihat (berhadapan), setan itu balik ke belakang seraya berkata: &quot;Sesungguhnya saya berlepas diri daripada kamu; sesungguhnya saya dapat melihat apa yang kamu sekalian tidak dapat melihat; sesungguhnya saya takut kepada Allah&quot;. Dan Allah sangat keras siksa-Nya.<?php break;}
case 49:{?>(Ingatlah), ketika orang-orang munafik dan orang-orang yang ada penyakit di dalam hatinya berkata: &quot;Mereka itu (orang-orang mukmin) ditipu oleh agamanya&quot;. (Allah berfirman): &quot;Barang siapa yang tawakal kepada Allah, maka sesungguhnya Allah Maha Perkasa lagi Maha Bijaksana&quot;.<?php break;}
case 50:{?>Kalau kamu melihat ketika para malaikat mencabut jiwa orang-orang yang kafir seraya memukul muka dan belakang mereka (dan berkata): &quot;Rasakanlah olehmu siksa neraka yang membakar&quot;, (tentulah kamu akan merasa ngeri).<?php break;}
case 51:{?>Demikian itu disebabkan oleh perbuatan tanganmu sendiri. Sesungguhnya Allah sekali-kali tidak menganiaya hamba-Nya,<?php break;}
case 52:{?>(keadaan mereka) serupa dengan keadaan Firaun dan pengikut-pengikutnya serta orang-orang yang sebelumnya. Mereka mengingkari ayat-ayat Allah, maka Allah menyiksa mereka disebabkan dosa-dosanya. Sesungguhnya Allah Maha Kuat lagi Amat Keras siksaan-Nya.<?php break;}
case 53:{?>Yang demikian (siksaan) itu adalah karena sesungguhnya Allah sekali-kali tidak akan merubah sesuatu nikmat yang telah dianugerahkan-Nya kepada sesuatu kaum, hingga kaum itu merubah apa yang ada pada diri mereka sendiri, dan sesungguhnya Allah Maha Mendengar lagi Maha Mengetahui,<?php break;}
case 54:{?>(keadaan mereka) serupa dengan keadaan Firaun dan pengikut-pengikutnya serta orang-orang yang sebelumnya. Mereka mendustakan ayat-ayat Tuhannya maka Kami membinasakan mereka disebabkan dosa-dosanya dan Kami tenggelamkan Firaun dan pengikut-pengikutnya; dan kesemuanya adalah orang-orang yang lalim.<?php break;}
case 55:{?>Sesungguhnya binatang (makhluk) yang paling buruk di sisi Allah ialah orang-orang yang kafir, karena mereka itu tidak beriman.<?php break;}
case 56:{?>(Yaitu) orang-orang yang kamu telah mengambil perjanjian dari mereka, sesudah itu mereka mengkhianati janjinya pada setiap kalinya, dan mereka tidak takut (akibat-akibatnya).<?php break;}
case 57:{?>Jika kamu menemui mereka dalam peperangan, maka cerai beraikanlah orang-orang yang di belakang mereka dengan (menumpas) mereka, supaya mereka mengambil pelajaran.<?php break;}
case 58:{?>Dan jika kamu khawatir akan (terjadinya) pengkhianatan dari suatu golongan, maka kembalikanlah perjanjian itu kepada mereka dengan cara yang jujur. Sesungguhnya Allah tidak menyukai orang-orang yang berkhianat.<?php break;}
case 59:{?>Dan janganlah orang-orang yang kafir itu mengira, bahwa mereka akan dapat lolos (dari kekuasaan Allah). Sesungguhnya mereka tidak dapat melemahkan (Allah).<?php break;}
case 60:{?>Dan siapkanlah untuk menghadapi mereka kekuatan apa saja yang kamu sanggupi dan dari kuda-kuda yang ditambat untuk berperang (yang dengan persiapan itu) kamu menggentarkan musuh Allah, musuhmu dan orang-orang selain mereka yang kamu tidak mengetahuinya; sedang Allah mengetahuinya. Apa saja yang kamu nafkahkan pada jalan Allah niscaya akan dibalas dengan cukup kepadamu dan kamu tidak akan dianiaya (dirugikan).<?php break;}
case 61:{?>Dan jika mereka condong kepada perdamaian, maka condonglah kepadanya dan bertawakallah kepada Allah. Sesungguhnya Dialah Yang Maha Mendengar lagi Maha Mengetahui.<?php break;}
case 62:{?>Dan jika mereka bermaksud hendak menipumu, maka sesungguhnya cukuplah Allah (menjadi pelindungmu). Dialah yang memperkuatmu dengan pertolongan-Nya dan dengan para mu'min,<?php break;}
case 63:{?>dan Yang mempersatukan hati mereka (orang-orang yang beriman). Walaupun kamu membelanjakan semua (kekayaan) yang berada di bumi, niscaya kamu tidak dapat mempersatukan hati mereka, akan tetapi Allah telah mempersatukan hati mereka. Sesungguhnya Dia Maha Perkasa lagi Maha Bijaksana.<?php break;}
case 64:{?>Hai Nabi, cukuplah Allah (menjadi Pelindung) bagimu dan bagi orang-orang mukmin yang mengikutimu.<?php break;}
case 65:{?>Hai Nabi, kobarkanlah semangat para mukmin itu untuk berperang. Jika ada dua puluh orang yang sabar di antara kamu, niscaya mereka dapat mengalahkan dua ratus orang musuh. Dan jika ada seratus orang (yang sabar) di antaramu, mereka dapat mengalahkan seribu daripada orang-orang kafir, disebabkan orang-orang kafir itu kaum yang tidak mengerti.<?php break;}
case 66:{?>Sekarang Allah telah meringankan kepadamu dan Dia telah mengetahui bahwa padamu ada kelemahan. Maka jika ada di antaramu seratus orang yang sabar, niscaya mereka dapat mengalahkan dua ratus orang; dan jika di antaramu ada seribu orang (yang sabar), niscaya mereka dapat mengalahkan dua ribu orang dengan seizin Allah. Dan Allah beserta orang-orang yang sabar.<?php break;}
case 67:{?>Tidak patut, bagi seorang Nabi mempunyai tawanan sebelum ia dapat melumpuhkan musuhnya di muka bumi. Kamu menghendaki harta benda duniawi sedangkan Allah menghendaki (pahala) akhirat (untukmu). Dan Allah Maha Perkasa lagi Maha Bijaksana.<?php break;}
case 68:{?>Kalau sekiranya tidak ada ketetapan yang telah terdahulu dari Allah, niscaya kamu ditimpa siksaan yang besar karena tebusan yang kamu ambil.<?php break;}
case 69:{?>Maka makanlah dari sebagian rampasan perang yang telah kamu ambil itu, sebagai makanan yang halal lagi baik, dan bertakwalah kepada Allah; sesungguhnya Allah Maha Pengampun lagi Maha Penyayang.<?php break;}
case 70:{?>Hai Nabi, katakanlah kepada tawanan-tawanan yang ada di tanganmu: &quot;Jika Allah mengetahui ada kebaikan dalam hatimu, niscaya Dia akan memberikan kepadamu yang lebih baik dari apa yang telah diambil daripadamu dan Dia akan mengampuni kamu&quot;. Dan Allah Maha Pengampun lagi Maha Penyayang.<?php break;}
case 71:{?>Akan tetapi jika mereka (tawanan-tawanan itu) bermaksud hendak berkhianat kepadamu, maka sesungguhnya mereka telah berkhianat kepada Allah sebelum ini, lalu Allah menjadikan (mu) berkuasa terhadap mereka. Dan Allah Maha Mengetahui lagi Maha Bijaksana.<?php break;}
case 72:{?>Sesungguhnya orang-orang yang beriman dan berhijrah serta berjihad dengan harta dan jiwanya pada jalan Allah dan orang-orang yang memberikan tempat kediaman dan pertolongan (kepada orang-orang muhajirin), mereka itu satu sama lain lindung-melindungi. Dan (terhadap) orang-orang yang beriman, tetapi belum berhijrah, maka tidak ada kewajiban sedikit pun atasmu melindungi mereka, sebelum mereka berhijrah. (Akan tetapi) jika mereka meminta pertolongan kepadamu dalam (urusan pembelaan) agama, maka kamu wajib memberikan pertolongan kecuali terhadap kaum yang telah ada perjanjian antara kamu dengan mereka. Dan Allah Maha Melihat apa yang kamu kerjakan.<?php break;}
case 73:{?>Adapun orang-orang yang kafir, sebagian mereka menjadi pelindung bagi sebagian yang lain. Jika kamu (hai para muslimin) tidak melaksanakan apa yang telah diperintahkan Allah itu, niscaya akan terjadi kekacauan di muka bumi dan kerusakan yang besar.<?php break;}
case 74:{?>Dan orang-orang yang beriman dan berhijrah serta berjihad pada jalan Allah, dan orang-orang yang memberi tempat kediaman dan memberi pertolongan (kepada orang-orang muhajirin), mereka itulah orang-orang yang benar-benar beriman. Mereka memperoleh ampunan dan rezeki (nikmat) yang mulia.<?php break;}
case 75:{?>Dan orang-orang yang beriman sesudah itu, kemudian berhijrah dan berjihad bersamamu maka orang-orang itu termasuk golonganmu (juga). Orang-orang yang mempunyai hubungan itu sebagiannya lebih berhak terhadap sesamanya (daripada yang kerabat) di dalam kitab Allah. Sesungguhnya Allah Maha Mengetahui segala sesuatu.<?php break;}
}?>