<?php 
switch($verse){
case 1:{?>(Inilah pernyataan) pemutusan perhubungan daripada Allah dan Rasul-Nya (yang dihadapkan) kepada orang-orang musyrikin yang kamu (kaum muslimin) telah mengadakan perjanjian (dengan mereka).<?php break;}
case 2:{?>Maka berjalanlah kamu (kaum musyrikin) di muka bumi selama empat bulan dan ketahuilah bahwa sesungguhnya kamu tidak akan dapat melemahkan Allah, dan sesungguhnya Allah menghinakan orang-orang kafir.<?php break;}
case 3:{?>Dan (inilah) suatu permakluman dari Allah dan Rasul-Nya kepada umat manusia pada hari haji akbar, bahwa sesungguhnya Allah dan Rasul-Nya berlepas diri dari orang-orang musyrikin. Kemudian jika kamu (kaum musyrikin) bertobat, maka bertobat itu lebih baik bagimu; dan jika kamu berpaling, maka ketahuilah bahwa sesungguhnya kamu tidak dapat melemahkan Allah. Dan beritakanlah kepada orang-orang kafir (bahwa mereka akan mendapat) siksa yang pedih.<?php break;}
case 4:{?>kecuali orang-orang musyrikin yang kamu telah mengadakan perjanjian (dengan mereka) dan mereka tidak mengurangi sesuatu pun (dari isi perjanjian) mu dan tidak (pula) mereka membantu seseorang yang memusuhi kamu, maka terhadap mereka itu penuhilah janjinya sampai batas waktunya. Sesungguhnya Allah menyukai orang-orang yang bertakwa.<?php break;}
case 5:{?>Apabila sudah habis bulan-bulan Haram itu, maka bunuhlah orang-orang musyrikin itu di mana saja kamu jumpai mereka, dan tangkaplah mereka. Kepunglah mereka dan intailah di tempat pengintaian. Jika mereka bertobat dan mendirikan salat dan menunaikan zakat, maka berilah kebebasan kepada mereka untuk berjalan. Sesungguhnya Allah Maha Pengampun lagi Maha Penyayang.<?php break;}
case 6:{?>Dan jika seorang di antara orang-orang musyrikin itu meminta perlindungan kepadamu, maka lindungilah ia supaya ia sempat mendengar firman Allah, kemudian antarkanlah ia ke tempat yang aman baginya. Demikian itu disebabkan mereka kaum yang tidak mengetahui.<?php break;}
case 7:{?>Bagaimana bisa ada perjanjian (aman) dari sisi Allah dan Rasul-Nya dengan orang-orang musyrikin, kecuali dengan orang-orang yang kamu telah mengadakan perjanjian (dengan mereka) di dekat Masjidilharam? maka selama mereka berlaku lurus terhadapmu, hendaklah kamu berlaku lurus (pula) terhadap mereka. Sesungguhnya Allah menyukai orang-orang yang bertakwa.<?php break;}
case 8:{?>Bagaimana bisa (ada perjanjian dari sisi Allah dan Rasul-Nya dengan orang-orang musyrikin), padahal jika mereka memperoleh kemenangan terhadap kamu, mereka tidak memelihara hubungan kekerabatan terhadap kamu dan tidak (pula mengindahkan) perjanjian. Mereka menyenangkan hatimu dengan mulutnya, sedang hatinya menolak. Dan kebanyakan mereka adalah orang-orang yang fasik (tidak menepati perjanjian).<?php break;}
case 9:{?>Mereka menukarkan ayat-ayat Allah dengan harga yang sedikit, lalu mereka menghalangi (manusia) dari jalan Allah. Sesungguhnya amat buruklah apa yang mereka kerjakan itu.<?php break;}
case 10:{?>Mereka tidak memelihara (hubungan) kerabat terhadap orang-orang mukmin dan tidak (pula mengindahkan) perjanjian. Dan mereka itulah orang-orang yang melampaui batas.<?php break;}
case 11:{?>Jika mereka bertobat, mendirikan salat dan menunaikan zakat, maka (mereka itu) adalah saudara-saudaramu seagama. Dan Kami menjelaskan ayat-ayat itu bagi kaum yang mengetahui.<?php break;}
case 12:{?>Jika mereka merusak sumpah (janji) nya sesudah mereka berjanji, dan mereka mencerca agamamu, maka perangilah pemimpin-pemimpin orang-orang kafir itu, karena sesungguhnya mereka itu adalah orang-orang yang tidak dapat dipegang janjinya, agar supaya mereka berhenti.<?php break;}
case 13:{?>Mengapakah kamu tidak memerangi orang-orang yang merusak sumpah (janjinya), padahal mereka telah keras kemauannya untuk mengusir Rasul dan merekalah yang pertama kali memulai memerangi kamu? Mengapakah kamu takut kepada mereka padahal Allah-lah yang berhak untuk kamu takuti, jika kamu benar-benar orang yang beriman.<?php break;}
case 14:{?>Perangilah mereka, niscaya Allah akan menyiksa mereka dengan (perantaraan) tangan-tanganmu dan Allah akan menghinakan mereka dan menolong kamu terhadap mereka, serta melegakan hati orang-orang yang beriman,<?php break;}
case 15:{?>dan menghilangkan panas hati orang-orang mukmin. Dan Allah menerima tobat orang yang dikehendaki-Nya. Allah Maha Mengetahui lagi Maha Bijaksana.<?php break;}
case 16:{?>Apakah kamu mengira bahwa kamu akan dibiarkan (begitu saja), sedang Allah belum mengetahui (dalam kenyataan) orang-orang yang berjihad di antara kamu dan tidak mengambil menjadi teman yang setia selain Allah, Rasul-Nya dan orang-orang yang beriman. Dan Allah Maha Mengetahui apa yang kamu kerjakan.<?php break;}
case 17:{?>Tidaklah pantas orang-orang musyrik itu memakmurkan mesjid-mesjid Allah, sedang mereka mengakui bahwa mereka sendiri kafir. Itulah orang-orang yang sia-sia pekerjaannya, dan mereka kekal di dalam neraka.<?php break;}
case 18:{?>Hanyalah yang memakmurkan mesjid-mesjid Allah ialah orang-orang yang beriman kepada Allah dan hari kemudian, serta tetap mendirikan salat, menunaikan zakat dan tidak takut (kepada siapa pun) selain kepada Allah, maka merekalah orang-orang yang diharapkan termasuk golongan orang-orang yang mendapat petunjuk.<?php break;}
case 19:{?>Apakah (orang-orang) yang memberi minuman kepada orang-orang yang mengerjakan haji dan mengurus Masjidilharam, kamu samakan dengan orang-orang yang beriman kepada Allah dan hari kemudian serta berjihad di jalan Allah? Mereka tidak sama di sisi Allah; dan Allah tidak memberikan petunjuk kepada kaum yang lalim.<?php break;}
case 20:{?>Orang-orang yang beriman dan berhijrah serta berjihad di jalan Allah dengan harta benda dan diri mereka, adalah lebih tinggi derajatnya di sisi Allah; dan itulah orang-orang yang mendapat kemenangan.<?php break;}
case 21:{?>Tuhan mereka menggembirakan mereka dengan memberikan rahmat daripada-Nya, keridaan dan surga, mereka memperoleh di dalamnya kesenangan yang kekal,<?php break;}
case 22:{?>mereka kekal di dalamnya selama-lamanya. Sesungguhnya di sisi Allah-lah pahala yang besar.<?php break;}
case 23:{?>Hai orang-orang yang beriman, janganlah kamu jadikan bapak-bapak dan saudara-saudaramu pemimpin-pemimpinmu, jika mereka lebih mengutamakan kekafiran atas keimanan dan siapa di antara kamu yang menjadikan mereka pemimpin-pemimpinmu, maka mereka itulah orang-orang yang lalim.<?php break;}
case 24:{?>Katakanlah: &quot;Jika bapak-bapak, anak-anak, saudara-saudara, istri-istri, kaum keluargamu, harta kekayaan yang kamu usahakan, perniagaan yang kamu khawatiri kerugiannya, dan rumah-rumah tempat tinggal yang kamu sukai, adalah lebih kamu cintai daripada Allah dan Rasul-Nya dan (dari) berjihad di jalan-Nya, maka tunggulah sampai Allah mendatangkan keputusan-Nya.&quot; Dan Allah tidak memberi petunjuk kepada orang-orang fasik.<?php break;}
case 25:{?>Sesungguhnya Allah telah menolong kamu (hai para mukminin) di medan peperangan yang banyak, dan (ingatlah) peperangan Hunain, yaitu di waktu kamu menjadi congkak karena banyaknya jumlahmu, maka jumlah yang banyak itu tidak memberi manfaat kepadamu sedikit pun, dan bumi yang luas itu telah terasa sempit olehmu, kemudian kamu lari ke belakang dengan bercerai-berai.<?php break;}
case 26:{?>Kemudian Allah menurunkan ketenangan kepada Rasul-Nya dan kepada orang-orang yang beriman, dan Allah menurunkan bala tentara yang kamu tiada melihatnya, dan Allah menimpakan bencana kepada orang-orang yang kafir, dan demikianlah pembalasan kepada orang-orang yang kafir.<?php break;}
case 27:{?>Sesudah itu Allah menerima tobat dari orang-orang yang dikehendaki-Nya. Allah Maha Pengampun lagi Maha Penyayang.<?php break;}
case 28:{?>Hai orang-orang yang beriman, sesungguhnya orang-orang yang musyrik itu najis, maka janganlah mereka mendekati Masjidilharam sesudah tahun ini. Dan jika kamu khawatir menjadi miskin, maka Allah nanti akan memberikan kekayaan kepadamu dari karunia-Nya, jika Dia menghendaki. Sesungguhnya Allah Maha Mengetahui lagi Maha Bijaksana.<?php break;}
case 29:{?>Perangilah orang-orang yang tidak beriman kepada Allah dan tidak (pula) kepada hari kemudian dan mereka tidak mengharamkan apa yang telah diharamkan oleh Allah dan Rasul-Nya dan tidak beragama dengan agama yang benar (agama Allah), (yaitu orang-orang) yang diberikan Al Kitab kepada mereka, sampai mereka membayar jizyah dengan patuh sedang mereka dalam keadaan tunduk.<?php break;}
case 30:{?>Orang-orang Yahudi berkata: &quot;Uzair itu putra Allah&quot; dan orang Nasrani berkata: &quot;Al Masih itu putra Allah&quot;. Demikian itulah ucapan mereka dengan mulut mereka, mereka meniru perkataan orang-orang kafir yang terdahulu. Dilaknati Allah-lah mereka; bagaimana mereka sampai berpaling?<?php break;}
case 31:{?>Mereka menjadikan orang-orang alimnya, dan rahib-rahib mereka sebagai tuhan selain Allah, dan (juga mereka mempertuhankan) Al Masih putra Maryam; padahal mereka hanya disuruh menyembah Tuhan Yang Maha Esa; tidak ada Tuhan (yang berhak disembah) selain Dia. Maha Suci Allah dari apa yang mereka persekutukan.<?php break;}
case 32:{?>Mereka berkehendak memadamkan cahaya (agama) Allah dengan mulut (ucapan-ucapan) mereka, dan Allah tidak menghendaki selain menyempurnakan cahaya-Nya, walaupun orang-orang yang kafir tidak menyukai.<?php break;}
case 33:{?>Dialah yang telah mengutus Rasul-Nya (dengan membawa) petunjuk (Al Qur'an) dan agama yang benar untuk dimenangkan-Nya atas segala agama, walaupun orang-orang musyrik tidak menyukai.<?php break;}
case 34:{?>Hai orang-orang yang beriman, sesungguhnya sebahagian besar dari orang-orang alim Yahudi dan rahib-rahib Nasrani benar-benar memakan harta orang dengan jalan yang batil dan mereka menghalang-halangi (manusia) dari jalan Allah. Dan orang-orang yang menyimpan emas dan perak dan tidak menafkahkannya pada jalan Allah, maka beritahukanlah kepada mereka, (bahwa mereka akan mendapat) siksa yang pedih,<?php break;}
case 35:{?>pada hari dipanaskan emas perak itu dalam neraka Jahanam, lalu dibakar dengannya dahi mereka, lambung dan punggung mereka (lalu dikatakan) kepada mereka: &quot;Inilah harta bendamu yang kamu simpan untuk dirimu sendiri, maka rasakanlah sekarang (akibat dari) apa yang kamu simpan itu&quot;.<?php break;}
case 36:{?>Sesungguhnya bilangan bulan pada sisi Allah ialah dua belas bulan, dalam ketetapan Allah di waktu Dia menciptakan langit dan bumi, di antaranya empat bulan haram. Itulah (ketetapan) agama yang lurus, maka janganlah kamu menganiaya diri kamu dalam bulan yang empat itu, dan perangilah kaum musyrikin itu semuanya sebagaimana mereka pun memerangi kamu semuanya; dan ketahuilah bahwasanya Allah beserta orang-orang yang bertakwa.<?php break;}
case 37:{?>Sesungguhnya mengundur-undurkan bulan haram itu adalah menambah kekafiran, disesatkan orang-orang yang kafir dengan mengundur-undurkan itu, mereka menghalalkannya pada suatu tahun dan mengharamkannya pada tahun yang lain, agar mereka dapat mensesuaikan dengan bilangan yang Allah mengharamkannya maka mereka menghalalkan apa yang diharamkan Allah. (Setan) menjadikan mereka memandang baik perbuatan mereka yang buruk itu. Dan Allah tidak memberi petunjuk kepada orang-orang yang kafir.<?php break;}
case 38:{?>Hai orang-orang yang beriman, apakah sebabnya apabila dikatakan kepada kamu: &quot;Berangkatlah (untuk berperang) pada jalan Allah&quot; kamu merasa berat dan ingin tinggal di tempatmu? Apakah kamu puas dengan kehidupan di dunia sebagai ganti kehidupan di akhirat? padahal kenikmatan hidup di dunia ini (dibandingkan dengan kehidupan) di akhirat hanyalah sedikit.<?php break;}
case 39:{?>Jika kamu tidak berangkat untuk berperang, niscaya Allah menyiksa kamu dengan siksa yang pedih dan digantinya (kamu) dengan kaum yang lain, dan kamu tidak akan dapat memberi kemudaratan kepada-Nya sedikit pun. Allah Maha Kuasa atas segala sesuatu.<?php break;}
case 40:{?>Jikalau kamu tidak menolongnya (Muhammad) maka sesungguhnya Allah telah menolongnya (yaitu) ketika orang-orang kafir (musyrikin Mekah) mengeluarkannya (dari Mekah) sedang dia salah seorang dari dua orang ketika keduanya berada dalam gua, di waktu dia berkata kepada temannya: &quot;Janganlah kamu berduka cita, sesungguhnya Allah beserta kita.&quot; Maka Allah menurunkan ketenangan-Nya kepada (Muhammad) dan membantunya dengan tentara yang kamu tidak melihatnya, dan Allah menjadikan seruan orang-orang kafir itulah yang rendah. Dan kalimat Allah itulah yang tinggi. Allah Maha Perkasa lagi Maha Bijaksana.<?php break;}
case 41:{?>Berangkatlah kamu baik dalam keadaan merasa ringan atau pun merasa berat, dan berjihadlah dengan harta dan dirimu di jalan Allah. Yang demikian itu adalah lebih baik bagimu jika kamu mengetahui.<?php break;}
case 42:{?>Kalau yang kamu serukan kepada mereka itu keuntungan yang mudah diperoleh dan perjalanan yang tidak berapa jauh, pastilah mereka mengikutimu, tetapi tempat yang dituju itu amat jauh terasa oleh mereka. Mereka akan bersumpah dengan (nama) Allah: &quot;Jika kami sanggup tentulah kami berangkat bersama-samamu&quot; Mereka membinasakan diri mereka sendiri dan Allah mengetahui bahwa sesungguhnya mereka benar-benar orang-orang yang berdusta.<?php break;}
case 43:{?>Semoga Allah memaafkanmu. Mengapa kamu memberi izin kepada mereka (untuk tidak pergi berperang), sebelum jelas bagimu orang-orang yang benar (dalam keuzurannya) dan sebelum kamu ketahui orang-orang yang berdusta?<?php break;}
case 44:{?>Orang-orang yang beriman kepada Allah dan hari kemudian, tidak akan meminta izin kepadamu untuk (tidak ikut) berjihad dengan harta dan diri mereka. Dan Allah mengetahui orang-orang yang bertakwa.<?php break;}
case 45:{?>Sesungguhnya yang akan meminta izin kepadamu, hanyalah orang-orang yang tidak beriman kepada Allah dan hari kemudian, dan hati mereka ragu-ragu, karena itu mereka selalu bimbang dalam keragu-raguannya.<?php break;}
case 46:{?>Dan jika mereka mau berangkat, tentulah mereka menyiapkan persiapan untuk keberangkatan itu, tetapi Allah tidak menyukai keberangkatan mereka, maka Allah melemahkan keinginan mereka, dan dikatakan kepada mereka: &quot;Tinggallah kamu bersama orang-orang yang tinggal itu.&quot;<?php break;}
case 47:{?>Jika mereka berangkat bersama-sama kamu, niscaya mereka tidak menambah kamu selain dari kerusakan belaka, dan tentu mereka akan bergegas-gegas maju ke muka di celah-celah barisanmu, untuk mengadakan kekacauan di antaramu; sedang di antara kamu ada orang-orang yang amat suka mendengarkan perkataan mereka. Dan Allah mengetahui orang-orang yang zalim.<?php break;}
case 48:{?>Sesungguhnya dari dahulu pun mereka telah mencari-cari kekacauan dan mereka mengatur pelbagai macam tipu daya untuk (merusakkan) mu, hingga datanglah kebenaran (pertolongan Allah), dan menanglah agama Allah, padahal mereka tidak menyukainya.<?php break;}
case 49:{?>Di antara mereka ada orang yang berkata: &quot;Berilah saya keizinan (tidak pergi berperang) dan janganlah kamu menjadikan saya terjerumus ke dalam fitnah&quot;. Ketahuilah, bahwa mereka telah terjerumus ke dalam fitnah. Dan sesungguhnya Jahanam itu benar-benar meliputi orang-orang yang kafir.<?php break;}
case 50:{?>Jika kamu mendapat sesuatu kebaikan, mereka menjadi tidak senang karenanya; dan jika kamu ditimpa oleh sesuatu bencana, mereka berkata: &quot;Sesungguhnya kami sebelumnya telah memperhatikan urusan kami (tidak pergi berperang)&quot; dan mereka berpaling dengan rasa gembira.<?php break;}
case 51:{?>Katakanlah: &quot;Sekali-kali tidak akan menimpa kami melainkan apa yang telah ditetapkan oleh Allah bagi kami. Dialah Pelindung kami, dan hanyalah kepada Allah orang-orang yang beriman harus bertawakal.&quot;<?php break;}
case 52:{?>Katakanlah: &quot;tidak ada yang kamu tunggu-tunggu bagi kami, kecuali salah satu dari dua kebaikan. Dan kami menunggu-nunggu bagi kamu bahwa Allah akan menimpakan kepadamu azab (yang besar) dari sisi-Nya, atau (azab) dengan tangan kami. Sebab itu tunggulah, sesungguhnya kami menunggu-nunggu bersamamu&quot;.<?php break;}
case 53:{?>Katakanlah: &quot;Nafkahkanlah hartamu baik dengan sukarela atau pun dengan terpaksa, namun nafkah itu sekali-kali tidak akan diterima dari kamu. Sesungguhnya kamu adalah orang-orang yang fasik.&quot;<?php break;}
case 54:{?>Dan tidak ada yang menghalangi mereka untuk diterima dari mereka nafkah-nafkahnya melainkan karena mereka kafir kepada Allah dan Rasul-Nya dan mereka tidak mengerjakan sembahyang, melainkan dengan malas dan tidak (pula) menafkahkan (harta) mereka, melainkan dengan rasa enggan.<?php break;}
case 55:{?>Maka janganlah harta benda dan anak-anak mereka menarik hatimu. Sesungguhnya Allah menghendaki dengan (memberi) harta benda dan anak-anak itu untuk menyiksa mereka dalam kehidupan di dunia dan kelak akan melayang nyawa mereka, sedang mereka dalam keadaan kafir.<?php break;}
case 56:{?>Dan mereka (orang-orang munafik) bersumpah dengan (nama) Allah, bahwa sesungguhnya mereka termasuk golonganmu; padahal mereka bukanlah dari golonganmu, akan tetapi mereka adalah orang-orang yang sangat takut (kepadamu).<?php break;}
case 57:{?>Jikalau mereka memperoleh tempat perlindungan atau gua-gua atau lobang-lobang (dalam tanah) niscaya mereka pergi kepadanya dengan secepat-cepatnya.<?php break;}
case 58:{?>Dan di antara mereka ada orang yang mencelamu tentang (pembagian) zakat; jika mereka diberi sebahagian daripadanya, mereka bersenang hati, dan jika mereka tidak diberi sebahagian daripadanya, dengan serta merta mereka menjadi marah.<?php break;}
case 59:{?>Jika mereka sungguh-sungguh rida dengan apa yang diberikan Allah dan Rasul-Nya kepada mereka, dan berkata: &quot;Cukuplah Allah bagi kami, Allah akan memberikan kepada kami sebahagian dari karunia-Nya dan demikian (pula) Rasul-Nya, sesungguhnya kami adalah orang-orang yang berharap kepada Allah&quot;, (tentulah yang demikian itu lebih baik bagi mereka).<?php break;}
case 60:{?>Sesungguhnya zakat-zakat itu, hanyalah untuk orang-orang fakir, orang-orang miskin, pengurus-pengurus zakat, para muallaf yang dibujuk hatinya, untuk (memerdekakan) budak, orang-orang yang berutang, untuk jalan Allah dan orang-orang yang sedang dalam perjalanan, sebagai sesuatu ketetapan yang diwajibkan Allah; dan Allah Maha Mengetahui lagi Maha Bijaksana.<?php break;}
case 61:{?>Di antara mereka (orang-orang munafik) ada yang menyakiti Nabi dan mengatakan: &quot;Nabi mempercayai semua apa yang didengarnya&quot;. Katakanlah: &quot;Ia mempercayai semua yang baik bagi kamu, ia beriman kepada Allah, mempercayai orang-orang mukmin, dan menjadi rahmat bagi orang-orang yang beriman di antara kamu&quot;. Dan orang-orang yang menyakiti Rasulullah itu, bagi mereka azab yang pedih.<?php break;}
case 62:{?>Mereka bersumpah kepada kamu dengan (nama) Allah untuk mencari keridaanmu, padahal Allah dan Rasul-Nya itulah yang lebih patut mereka cari keridaannya jika mereka adalah orang-orang yang mukmin.<?php break;}
case 63:{?>Tidakkah mereka (orang-orang munafik itu) mengetahui bahwasanya Barang siapa menentang Allah dan Rasul-Nya, maka sesungguhnya neraka Jahanamlah baginya, dia kekal di dalamnya. Itu adalah kehinaan yang besar.<?php break;}
case 64:{?>Orang-orang yang munafik itu takut akan diturunkan terhadap mereka sesuatu surat yang menerangkan apa yang tersembunyi dalam hati mereka. Katakanlah kepada mereka: &quot;Teruskanlah ejekan-ejekanmu (terhadap Allah dan Rasul-Nya)&quot;. Sesungguhnya Allah akan menyatakan apa yang kamu takuti itu.<?php break;}
case 65:{?>Dan jika kamu tanyakan kepada mereka (tentang apa yang mereka lakukan itu), tentulah mereka akan menjawab: &quot;Sesungguhnya kami hanyalah bersenda gurau dan bermain-main saja&quot;. Katakanlah: &quot;Apakah dengan Allah, ayat-ayat-Nya dan Rasul-Nya kamu selalu berolok-olok?&quot;<?php break;}
case 66:{?>Tidak usah kamu minta maaf, karena kamu kafir sesudah beriman. Jika Kami memaafkan segolongan daripada kamu (lantaran mereka tobat), niscaya Kami akan mengazab golongan (yang lain) disebabkan mereka adalah orang-orang yang selalu berbuat dosa.<?php break;}
case 67:{?>Orang-orang munafik laki-laki dan perempuan, sebagian dengan sebagian yang lain adalah sama, mereka menyuruh membuat yang mungkar dan melarang berbuat yang makruf dan mereka menggenggamkan tangannya. Mereka telah lupa kepada Allah, maka Allah melupakan mereka. Sesungguhnya orang-orang munafik itulah orang-orang yang fasik.<?php break;}
case 68:{?>Allah mengancam orang-orang munafik laki-laki dan perempuan dan orang-orang kafir dengan neraka Jahanam. Mereka kekal di dalamnya. Cukuplah neraka itu bagi mereka; dan Allah melaknati mereka; dan bagi mereka azab yang kekal,<?php break;}
case 69:{?>(keadaan kamu hai orang-orang munafik dan musyrikin adalah) seperti keadaan orang-orang yang sebelum kamu, mereka lebih kuat daripada kamu, dan lebih banyak harta benda dan anak-anaknya daripada kamu. Maka mereka telah meni'mati bagian mereka, dan kamu telah menikmati bagianmu sebagaimana orang-orang yang sebelummu meni'mati bagiannya, dan kamu mempercakapkan (hal yang batil) sebagaimana mereka mempercakapkannya. Mereka itu, amalannya menjadi sia-sia di dunia dan di akhirat; dan mereka itulah orang-orang yang merugi.<?php break;}
case 70:{?>Belumkah datang kepada mereka berita penting tentang orang-orang yang sebelum mereka, (yaitu) kaum Nuh, 'Aad, Tsamud, kaum Ibrahim, penduduk Madyan, dan (penduduk) negeri-negeri yang telah musnah? Telah datang kepada mereka rasul-rasul dengan membawa keterangan yang nyata; maka Allah tidaklah sekali-kali menganiaya mereka, akan tetapi merekalah yang menganiaya diri mereka sendiri.<?php break;}
case 71:{?>Dan orang-orang yang beriman, lelaki dan perempuan, sebahagian mereka (adalah) menjadi penolong bagi sebahagian yang lain. Mereka menyuruh (mengerjakan) yang makruf, mencegah dari yang mungkar, mendirikan sembahyang, menunaikan zakat, dan mereka taat kepada Allah dan Rasul-Nya. Mereka itu akan diberi rahmat oleh Allah; sesungguhnya Allah Maha Perkasa lagi Maha Bijaksana.<?php break;}
case 72:{?>Allah menjanjikan kepada orang-orang yang mukmin lelaki dan perempuan, (akan mendapat) surga yang di bawahnya mengalir sungai-sungai, kekal mereka di dalamnya, dan (mendapat) tempat-tempat yang bagus di surga Adn. Dan keridaan Allah adalah lebih besar; itu adalah keberuntungan yang besar.<?php break;}
case 73:{?>Hai Nabi, berjihadlah (melawan) orang-orang kafir dan orang-orang munafik itu, dan bersikap keraslah terhadap mereka. Tempat mereka ialah neraka Jahanam. Dan itulah tempat kembali yang seburuk-buruknya.<?php break;}
case 74:{?>Mereka (orang-orang munafik itu) bersumpah dengan (nama) Allah, bahwa mereka tidak mengatakan (sesuatu yang menyakitimu). Sesungguhnya mereka telah mengucapkan perkataan kekafiran, dan telah menjadi kafir sesudah Islam, dan mengingini apa yang mereka tidak dapat mencapainya; dan mereka tidak mencela (Allah dan Rasul-Nya), kecuali karena Allah dan Rasul-Nya telah melimpahkan karunia-Nya kepada mereka. Maka jika mereka bertobat, itu adalah lebih baik bagi mereka, dan jika mereka berpaling, niscaya Allah akan mengazab mereka dengan azab yang pedih di dunia dan di akhirat; dan mereka sekali-kali tidak mempunyai pelindung dan tidak (pula) penolong di muka bumi.<?php break;}
case 75:{?>Dan di antara mereka ada orang yang telah berikrar kepada Allah: &quot;Sesungguhnya jika Allah memberikan sebahagian karunia-Nya kepada kami, pastilah kami akan bersedekah dan pastilah kami termasuk orang-orang yang saleh.<?php break;}
case 76:{?>Maka setelah Allah memberikan kepada mereka sebahagian dari karunia-Nya, mereka kikir dengan karunia itu, dan berpaling, dan mereka memanglah orang-orang yang selalu membelakangi (kebenaran).<?php break;}
case 77:{?>Maka Allah menimbulkan kemunafikan pada hati mereka sampai kepada waktu mereka menemui Allah, karena mereka telah memungkiri terhadap Allah apa yang telah mereka ikrarkan kepada-Nya dan (juga) karena mereka selalu berdusta.<?php break;}
case 78:{?>Tidakkah mereka tahu bahwasanya Allah mengetahui rahasia dan bisikan mereka, dan bahwasanya Allah amat mengetahui segala yang gaib?<?php break;}
case 79:{?>(Orang-orang munafik) yaitu orang-orang yang mencela orang-orang mukmin yang memberi sedekah dengan sukarela dan (mencela) orang-orang yang tidak memperoleh (untuk disedekahkan) selain sekedar kesanggupannya, maka orang-orang munafik itu menghina mereka. Allah akan membalas penghinaan mereka itu, dan untuk mereka azab yang pedih.<?php break;}
case 80:{?>Kamu memohonkan ampun bagi mereka atau tidak kamu mohonkan ampun bagi mereka (adalah sama saja). Kendati pun kamu memohonkan ampun bagi mereka tujuh puluh kali, namun Allah sekali-kali tidak akan memberi ampun kepada mereka. Yang demikian itu adalah karena mereka kafir kepada Allah dan Rasul-Nya. Dan Allah tidak memberi petunjuk kepada kaum yang fasik.<?php break;}
case 81:{?>Orang-orang yang ditinggalkan (tidak ikut berperang) itu, merasa gembira dengan tinggalnya mereka di belakang Rasulullah, dan mereka tidak suka berjihad dengan harta dan jiwa mereka pada jalan Allah dan mereka berkata: &quot;Janganlah kamu berangkat (pergi berperang) dalam panas terik ini&quot;. Katakanlah: &quot;Api neraka Jahanam itu lebih sangat panas (nya)&quot;, jika mereka mengetahui.<?php break;}
case 82:{?>Maka hendaklah mereka tertawa sedikit dan menangis banyak, sebagai pembalasan dari apa yang selalu mereka kerjakan.<?php break;}
case 83:{?>Maka jika Allah mengembalikanmu kepada satu golongan dari mereka, kemudian mereka minta izin kepadamu untuk ke luar (pergi berperang), maka katakanlah: &quot;Kamu tidak boleh ke luar bersamaku selama-lamanya dan tidak boleh memerangi musuh bersamaku. Sesungguhnya kamu telah rela tidak pergi berperang kali yang pertama. Karena itu duduklah (tinggallah) bersama orang-orang yang tidak ikut berperang&quot;<?php break;}
case 84:{?>Dan janganlah kamu sekali-kali menyembahyangkan (jenazah) seorang yang mati di antara mereka, dan janganlah kamu berdiri (mendoakan) di kuburnya. Sesungguhnya mereka telah kafir kepada Allah dan Rasul-Nya dan mereka mati dalam keadaan fasik.<?php break;}
case 85:{?>Dan janganlah harta benda dan anak-anak mereka menarik hatimu. Sesungguhnya Allah menghendaki akan mengazab mereka di dunia dengan harta dan anak-anak itu dan agar melayang nyawa mereka dalam keadaan kafir.<?php break;}
case 86:{?>Dan apabila diturunkan sesuatu surat (yang memerintahkan kepada orang munafik itu): &quot;Berimanlah kamu kepada Allah dan berjihadlah beserta Rasul-Nya&quot;, niscaya orang-orang yang sanggup di antara mereka meminta izin kepadamu (untuk tidak berjihad) dan mereka berkata: &quot;Biarkanlah kami berada bersama orang-orang yang duduk&quot;.<?php break;}
case 87:{?>Mereka rela berada bersama orang-orang yang tidak pergi berperang, dan hati mereka telah dikunci mati, maka mereka tidak mengetahui (kebahagiaan beriman dan berjihad).<?php break;}
case 88:{?>Tetapi Rasul dan orang-orang yang beriman bersama dia, mereka berjihad dengan harta dan diri mereka. Dan mereka itulah orang-orang yang memperoleh kebaikan; dan mereka itulah (pula) orang-orang yang beruntung.<?php break;}
case 89:{?>Allah telah menyediakan bagi mereka surga yang mengalir di bawahnya sungai-sungai, mereka kekal di dalamnya. Itulah kemenangan yang besar.<?php break;}
case 90:{?>Dan datang (kepada Nabi) orang-orang yang mengemukakan 'uzur, yaitu orang-orang Arab Badui agar diberi izin bagi mereka (untuk tidak pergi berjihad), sedang orang-orang yang mendustakan Allah dan Rasul-Nya, duduk berdiam diri saja. Kelak orang-orang yang kafir di antara mereka itu akan ditimpa azab yang pedih.<?php break;}
case 91:{?>Tiada dosa (lantaran tidak pergi berjihad) atas orang-orang yang lemah, atas orang-orang yang sakit dan atas orang-orang yang tidak memperoleh apa yang akan mereka nafkahkan, apabila mereka berlaku ikhlas kepada Allah dan Rasul-Nya. Tidak ada jalan sedikit pun untuk menyalahkan orang-orang yang berbuat baik. Dan Allah Maha Pengampun lagi Maha Penyayang,<?php break;}
case 92:{?>dan tiada (pula dosa) atas orang-orang yang apabila mereka datang kepadamu, supaya kamu memberi mereka kendaraan, lalu kamu berkata: &quot;Aku tidak memperoleh kendaraan untuk membawamu&quot;, lalu mereka kembali, sedang mata mereka bercucuran air mata karena kesedihan, lantaran mereka tidak memperoleh apa yang akan mereka nafkahkan.<?php break;}
case 93:{?>Sesungguhnya jalan (untuk menyalahkan) hanyalah terhadap orang-orang yang meminta izin kepadamu, padahal mereka itu orang-orang kaya. Mereka rela berada bersama-sama orang-orang yang tidak ikut berperang dan Allah telah mengunci mati hati mereka, maka mereka tidak mengetahui (akibat perbuatan mereka).<?php break;}
case 94:{?>Mereka (orang-orang munafik) mengemukakan uzurnya kepadamu, apabila kamu telah kembali kepada mereka (dari medan perang). Katakanlah: &quot;Janganlah kamu mengemukakan 'uzur; kami tidak percaya lagi kepadamu, (karena) sesungguhnya Allah telah memberitahukan kepada kami beritamu yang sebenarnya. Dan Allah serta Rasul-Nya akan melihat pekerjaanmu, kemudian kamu dikembalikan kepada Yang Mengetahui yang gaib dan yang nyata, lalu Dia memberitakan kepadamu apa yang telah kamu kerjakan&quot;.<?php break;}
case 95:{?>Kelak mereka akan bersumpah kepadamu dengan nama Allah, apabila kamu kembali kepada mereka, supaya kamu berpaling dari mereka. Maka berpalinglah dari mereka; karena sesungguhnya mereka itu adalah najis dan tempat mereka Jahanam; sebagai balasan atas apa yang telah mereka kerjakan.<?php break;}
case 96:{?>Mereka akan bersumpah kepadamu, agar kamu rida kepada mereka. Tetapi jika sekiranya kamu rida kepada mereka, maka sesungguhnya Allah tidak rida kepada orang-orang yang fasik itu.<?php break;}
case 97:{?>Orang-orang Arab Badui itu, lebih sangat kekafiran dan kemunafikannya, dan lebih wajar tidak mengetahui hukum-hukum yang diturunkan Allah kepada Rasul-Nya. Dan Allah Maha Mengetahui lagi Maha Bijaksana.<?php break;}
case 98:{?>Di antara orang-orang Arab Badui itu, ada orang yang memandang apa yang dinafkahkannya (di jalan Allah) sebagai suatu kerugian dan dia menanti-nanti marabahaya menimpamu; merekalah yang akan ditimpa marabahaya. Dan Allah Maha Mendengar lagi Maha Mengetahui.<?php break;}
case 99:{?>Dan di antara orang-orang Arab Badui itu, ada orang yang beriman kepada Allah dan hari kemudian, dan memandang apa yang dinafkahkannya (di jalan Allah) itu, sebagai jalan mendekatkannya kepada Allah dan sebagai jalan untuk memperoleh doa Rasul. Ketahuilah, sesungguhnya nafkah itu adalah suatu jalan bagi mereka untuk mendekatkan diri (kepada Allah). Kelak Allah akan memasukkan mereka ke dalam rahmat (surga) Nya; sesungguhnya Allah Maha Pengampun lagi Maha Penyayang.<?php break;}
case 100:{?>Orang-orang yang terdahulu lagi yang pertama-tama (masuk Islam) di antara orang-orang muhajirin dan Ansar dan orang-orang yang mengikuti mereka dengan baik, Allah rida kepada mereka dan mereka pun rida kepada Allah dan Allah menyediakan bagi mereka surga-surga yang mengalir sungai-sungai di dalamnya; mereka kekal di dalamnya selama-lamanya. Itulah kemenangan yang besar.<?php break;}
case 101:{?>Di antara orang-orang Arab Badui yang di sekelilingmu itu, ada orang-orang munafik; dan (juga) di antara penduduk Madinah. Mereka keterlaluan dalam kemunafikannya. Kamu (Muhammad) tidak mengetahui mereka, (tetapi) Kami-lah yang mengetahui mereka. Nanti mereka akan Kami siksa dua kali kemudian mereka akan dikembalikan kepada azab yang besar.<?php break;}
case 102:{?>Dan (ada pula) orang-orang lain yang mengakui dosa-dosa mereka, mereka mencampur baurkan pekerjaan yang baik dengan pekerjaan lain yang buruk. Mudah-mudahan Allah menerima tobat mereka. Sesungguhnya Allah Maha Pengampun lagi Maha Penyayang.<?php break;}
case 103:{?>Ambillah zakat dari sebagian harta mereka, dengan zakat itu kamu membersihkan dan mensucikan mereka, dan mendoalah untuk mereka. Sesungguhnya doa kamu itu (menjadi) ketenteraman jiwa bagi mereka. Dan Allah Maha Mendengar lagi Maha Mengetahui.<?php break;}
case 104:{?>Tidakkah mereka mengetahui, bahwasanya Allah menerima tobat dari hamba-hamba-Nya dan menerima zakat, dan bahwasanya Allah Maha Penerima tobat lagi Maha Penyayang?<?php break;}
case 105:{?>Dan katakanlah: &quot;Bekerjalah kamu, maka Allah dan Rasul-Nya serta orang-orang mukmin akan melihat pekerjaanmu itu, dan kamu akan dikembalikan kepada (Allah) Yang Mengetahui akan yang gaib dan yang nyata, lalu diberitakan-Nya kepada kamu apa yang telah kamu kerjakan&quot;.<?php break;}
case 106:{?>Dan ada (pula) orang-orang lain yang ditangguhkan sampai ada keputusan Allah; adakalanya Allah akan mengazab mereka dan adakalanya Allah akan menerima tobat mereka. Dan Allah Maha Mengetahui lagi Maha Bijaksana.<?php break;}
case 107:{?>Dan (di antara orang-orang munafik itu) ada orang-orang yang mendirikan mesjid untuk menimbulkan kemudaratan (pada orang-orang mukmin), untuk kekafiran dan untuk memecah belah antara orang-orang mukmin serta menunggu kedatangan orang-orang yang telah memerangi Allah dan Rasul-Nya sejak dahulu. Mereka sesungguhnya bersumpah: &quot;Kami tidak menghendaki selain kebaikan.&quot; Dan Allah menjadi saksi bahwa sesungguhnya mereka itu adalah pendusta (dalam sumpahnya).<?php break;}
case 108:{?>Janganlah kamu bersembahyang dalam mesjid itu selama-lamanya. Sesungguhnya mesjid yang didirikan atas dasar takwa (mesjid Quba), sejak hari pertama adalah lebih patut kamu bersembahyang di dalamnya. Di dalamnya ada orang-orang yang ingin membersihkan diri. Dan Allah menyukai orang-orang yang bersih.<?php break;}
case 109:{?>Maka apakah orang-orang yang mendirikan mesjidnya di atas dasar takwa kepada Allah dan keridaan (Nya) itu yang baik, ataukah orang-orang yang mendirikan bangunannya di tepi jurang yang runtuh, lalu bangunannya itu jatuh bersama-sama dengan dia ke dalam neraka Jahanam? Dan Allah tidak memberikan petunjuk kepada orang-orang yang lalim.<?php break;}
case 110:{?>Bangunan-bangunan yang mereka dirikan itu senantiasa menjadi pangkal keraguan dalam hati mereka, kecuali bila hati mereka itu telah hancur. Dan Allah Maha Mengetahui lagi Maha Bijaksana.<?php break;}
case 111:{?>Sesungguhnya Allah telah membeli dari orang-orang mukmin, diri dan harta mereka dengan memberikan surga untuk mereka. Mereka berperang pada jalan Allah; lalu mereka membunuh atau terbunuh. (Itu telah menjadi) janji yang benar dari Allah di dalam Taurat, Injil dan Al Qur'an. Dan siapakah yang lebih menepati janjinya (selain) daripada Allah? Maka bergembiralah dengan jual beli yang telah kamu lakukan itu, dan itulah kemenangan yang besar.<?php break;}
case 112:{?>Mereka itu adalah orang-orang yang bertobat, yang beribadah, yang memuji (Allah), yang melawat, yang rukuk, yang sujud, yang menyuruh berbuat makruf dan mencegah berbuat mungkar dan yang memelihara hukum-hukum Allah. Dan gembirakanlah orang-orang mukmin itu.<?php break;}
case 113:{?>Tiadalah sepatutnya bagi Nabi dan orang-orang yang beriman memintakan ampun (kepada Allah) bagi orang-orang musyrik, walaupun orang-orang musyrik itu adalah kaum kerabat (nya), sesudah jelas bagi mereka, bahwasanya orang-orang musyrik itu, adalah penghuni neraka Jahanam.<?php break;}
case 114:{?>Dan permintaan ampun dari Ibrahim (kepada Allah) untuk bapaknya, tidak lain hanyalah karena suatu janji yang telah diikrarkannya kepada bapaknya itu. Maka tatkala jelas bagi Ibrahim bahwa bapaknya itu adalah musuh Allah, maka Ibrahim berlepas diri daripadanya. Sesungguhnya Ibrahim adalah seorang yang sangat lembut hatinya lagi penyantun.<?php break;}
case 115:{?>Dan Allah sekali-kali tidak akan menyesatkan suatu kaum, sesudah Allah memberi petunjuk kepada mereka hingga dijelaskan-Nya kepada mereka apa yang harus mereka jauhi. Sesungguhnya Allah Maha Mengetahui segala sesuatu.<?php break;}
case 116:{?>Sesungguhnya kepunyaan Allah-lah kerajaan langit dan bumi. Dia menghidupkan dan mematikan. Dan sekali-kali tidak ada pelindung dan penolong bagimu selain Allah.<?php break;}
case 117:{?>Sesungguhnya Allah telah menerima tobat Nabi, orang-orang muhajirin dan orang-orang Ansar, yang mengikuti Nabi dalam masa kesulitan, setelah hati segolongan dari mereka hampir berpaling, kemudian Allah menerima tobat mereka itu. Sesungguhnya Allah Maha Pengasih lagi Maha Penyayang kepada mereka,<?php break;}
case 118:{?>dan terhadap tiga orang yang ditangguhkan (penerimaan tobat) mereka, hingga apabila bumi telah menjadi sempit bagi mereka, padahal bumi itu luas dan jiwa mereka pun telah sempit (pula terasa) oleh mereka, serta mereka telah mengetahui bahwa tidak ada tempat lari dari (siksa) Allah, melainkan kepada-Nya saja. Kemudian Allah menerima tobat mereka agar mereka tetap dalam tobatnya. Sesungguhnya Allah-lah Yang Maha Penerima tobat lagi Maha Penyayang.<?php break;}
case 119:{?>Hai orang-orang yang beriman, bertakwalah kepada Allah, dan hendaklah kamu bersama orang-orang yang benar.<?php break;}
case 120:{?>Tidaklah sepatutnya bagi penduduk Madinah dan orang-orang Arab Badui yang berdiam di sekitar mereka, tidak turut menyertai Rasulullah (pergi berperang) dan tidak patut (pula) bagi mereka lebih mencintai diri mereka daripada mencintai diri Rasul. Yang demikian itu ialah karena mereka tidak ditimpa kehausan, kepayahan dan kelaparan pada jalan Allah. dan tidak (pula) menginjak suatu tempat yang membangkitkan amarah orang-orang kafir, dan tidak menimpakan sesuatu bencana kepada musuh, melainkan dituliskanlah bagi mereka dengan yang demikian itu suatu amal saleh. Sesungguhnya Allah tidak menyia-nyiakan pahala orang-orang yang berbuat baik,<?php break;}
case 121:{?>dan mereka tiada menafkahkan suatu nafkah yang kecil dan tidak (pula) yang besar dan tidak melintasi suatu lembah, melainkan dituliskan bagi mereka (amal saleh pula), karena Allah akan memberi balasan kepada mereka (dengan balasan) yang lebih baik dari apa yang telah mereka kerjakan.<?php break;}
case 122:{?>Tidak sepatutnya bagi orang-orang yang mukmin itu pergi semuanya (ke medan perang). Mengapa tidak pergi dari tiap-tiap golongan di antara mereka beberapa orang untuk memperdalam pengetahuan mereka tentang agama dan untuk memberi peringatan kepada kaumnya apabila mereka telah kembali kepadanya, supaya mereka itu dapat menjaga dirinya.<?php break;}
case 123:{?>Hai orang-orang yang beriman, perangilah orang-orang kafir yang di sekitar kamu itu, dan hendaklah mereka menemui kekerasan daripadamu, dan ketahuilah, bahwasanya Allah beserta orang-orang yang bertakwa.<?php break;}
case 124:{?>Dan apabila diturunkan suatu surat, maka di antara mereka (orang-orang munafik) ada yang berkata: &quot;Siapakah di antara kamu yang bertambah imannya dengan (turunnya) surat ini?&quot; Adapun orang-orang yang beriman, maka surat ini menambah imannya, sedang mereka merasa gembira.<?php break;}
case 125:{?>Dan adapun orang-orang yang di dalam hati mereka ada penyakit, maka dengan surat itu bertambah kekafiran mereka, di samping kekafirannya (yang telah ada) dan mereka mati dalam keadaan kafir.<?php break;}
case 126:{?>Dan tidakkah mereka (orang-orang munafik) memperhatikan bahwa mereka diuji sekali atau dua kali setiap tahun, kemudian mereka tidak (juga) bertobat dan tidak (pula) mengambil pengajaran?<?php break;}
case 127:{?>Dan apabila diturunkan satu surat sebagian mereka memandang kepada sebagian yang lain (sambil berkata): &quot;Adakah seorang dari (orang-orang muslimin) yang melihat kamu?&quot; Sesudah itu mereka pun pergi. Allah telah memalingkan hati mereka disebabkan mereka adalah kaum yang tidak mengerti.<?php break;}
case 128:{?>Sesungguhnya telah datang kepadamu seorang rasul dari kaummu sendiri, berat terasa olehnya penderitaanmu, sangat menginginkan (keimanan dan keselamatan) bagimu, amat belas kasihan lagi penyayang terhadap orang-orang mukmin.<?php break;}
case 129:{?>Jika mereka berpaling (dari keimanan), maka katakanlah: &quot;Cukuplah Allah bagiku; tidak ada Tuhan selain Dia. Hanya kepada-Nya aku bertawakal dan Dia adalah Tuhan yang memiliki Arasy yang agung&quot;<?php break;}
}?>